### ISSUE TITLE
Can't create a Breadcrumb with a custom date

### ISSUE THREAD

**Issue by ctweney** [getsentry/sentry-java#1012]
Because `io.sentry.Breadcrumb` was written as a final class with a well-defended constructor, one can only instantiate a Breadcrumb with a date equal to `DateUtils.getCurrentDateTimeOrNull()`. This is a crippling limitation. Please provide a public constructor that allows setting a different date. 

I'm using `io.sentry:sentry-android:3.1.0`.

**Comment by marandaneto** [comment]
@ctweney mind sharing the use-case to create a breadcrumb with a custom breadcrumb?

**Comment by ctweney** [comment]
Sure -- I want the breadcrumbs to persist from one run of the app to the next. Yet, I don't want to send breadcrumbs to the Sentry servers until an actual error is logged or the user pushes a certain button. So I persist breadcrumbs with the date/time they actually occurred into my app's SQLite db. If an error needs to be pushed to Sentry servers I get those breadcrumbs out of SQLite and push them.

**Comment by marandaneto** [comment]
I see @ctweney, good point.

We can make this ctor public then https://github.com/getsentry/sentry-java/blob/a87e484c0ef83cb60086530b049f4b21f7f783a3/sentry/src/main/java/io/sentry/Breadcrumb.java#L42-L44

Would you like to open a PR? :)
