### ISSUE TITLE
Java - Wrong title from chained exceptions

### ISSUE THREAD

**Issue by Blejwi** [getsentry/sentry-java#1013]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 9.1.2

## Description

When using chainged exceptions in java/kotlin title for issue is taken from oldest exception, instead of newest one
In Java stacktrace newest exception is always on top. In languages like Python or Ruby newest exception is one the bottom.

Found a change that possibly broke it for Java (but fixed for other languages):
https://github.com/getsentry/sentry/issues/3961

## Steps to Reproduce

1. Add any chained exception in java:
```
throw RuntimeException("test", RuntimeException("test2", RuntimeException("test3")))
```
2. There will be `test3` taken as issue title (instead of `test` which is newest exception)

**Comment by marandaneto** [comment]
@Blejwi thanks for raising this.

You can use the `BeforeSend` callback to reverse the exception list yourself.

More context about that:
https://forum.sentry.io/t/error-name-as-class-name-instead-of-exception-name/10353/5
