### ISSUE TITLE
Send user.ip_address = {{ auto }} when sendDefaultPii is true 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1015]
If no explicit IpAddress was set by the user code (or framework integration) the SDK should set `{{ auto }}` which tells the server to infer the IP Address to client connection as the `user.ip_address`.

This is true for all SDKs. Like: https://github.com/getsentry/sentry-dotnet/issues/561

**Comment by lucas-zimerman** [comment]
I believe it should set "{{auto}}" ? @bruno-garcia

**Comment by marandaneto** [comment]
Yep @lucas-zimerman is right, thanks for pointing this out

**Comment by bruno-garcia** [comment]
Thanks @lucas-zimerman
