### ISSUE TITLE
Events not send from AWS Lambda

### ISSUE THREAD

**Issue by maciejwalkowiak** [getsentry/sentry-java#1023]
_Platform:_
- [x]  Java -> 1.8

The version of the SDK:
**3.1.1**

---
I have the following issue:

Events triggered from AWS Lambda are not sent to Sentry.

[Original Stackoverflow question](https://stackoverflow.com/questions/64615615/sentry-sdk-java-is-not-working-on-aws-lambda)

**Sample project reproducing an issue**

https://github.com/maciej-scratches/sentry-aws-lambda-issue

The issue likely is that events need to be flushed when Lambda execution is over.

**Comment by satishincr** [comment]
I am also facing the same issue...

**Comment by maciejwalkowiak** [comment]
Fixed with https://github.com/getsentry/sentry-java/pull/1239.

Before the end of execution, you must call `Sentry.flush()` to make sure events are sent to Sentry.
