### ISSUE TITLE
version 3.1.2 fails to use SENTRY_HTTP_PROXY_* variables

### ISSUE THREAD

**Issue by sbartram** [getsentry/sentry-java#1028]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [X]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?  1.8
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [X]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [X]  Gradle -> If yes, which version?  6.5
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Proguard/R8:_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [X] Manually

The version of the SDK:
**3.1.2**

---
I have the following issue:

We were previously using 1.7.30 and specifying our HTTP proxy using these environment variables:

SENTRY_HTTP_PROXY_HOST=host
SENTRY_HTTP_PROXY_PORT=port

This was working fine.  After upgrading the 3.1.2, the proxy is not being set on the connection.  If I set the proxy manually via hardcode, it works again.  The documentation still claims that using the environment variables will work.

**Steps to reproduce:**
- upgrade working code from 1.7.30 to 3.1.2

**Actual result:**
- HTTP connections to Sentry fail because a proxy is required

**Expected result:**
- HTTP connections work

**Comment by marandaneto** [comment]
dup of #981 I believe.
not all the system envs are available on 3.x, still, you could set the proxy yourself.

pseudocode:

```
Sentry.init(options => {
  // read your own system envs (host, port)
  Proxy proxy = new Proxy(host, port);
  options.setProxy(proxy);
})
```

**Comment by sbartram** [comment]
As I stated in the report, if I set the proxy manually, it works.  However, Sentry should acknowledge this as a bug or fix the documentation.


> dup of #981 I believe.
> not all the system envs are available on 3.x, still, you could set the proxy yourself.
> 
> pseudocode:
> 
> ```
> Sentry.init(options => {
>   // read your own system envs (host, port)
>   Proxy proxy = new Proxy(host, port);
>   options.setProxy(proxy);
> })
> ```

**Comment by marandaneto** [comment]
oh sorry I misread that, link to the docs are here https://docs.sentry.io/platforms/java/configuration/#using-a-proxy
we should fix the docs.

**Comment by marandaneto** [comment]
this will be released in the next version, I'll keep it open because we need to work on the docs.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.2.0
