### ISSUE TITLE
Sentry still uses deprecate getMappingFile() function

### ISSUE THREAD

**Issue by nicusorflorin** [getsentry/sentry-java#1034]
_Platform:_
- [ ]  Android ->Device API and compileSdkVersion/targetSdkVersion = 30, buildTools  = 29.0.3
- [ ]  Java -> Java and sourceCompatibility/targetCompatibility = avaVersion.VERSION_1_8
- [ ]  Kotlin -> 1.4.10

_IDE:_
- [ ]  Android Studio -> 4.1
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> gradle-6.5-all

_Android Gradle Plugin:_
- [ ]  Yes ->  4.1.0

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> 1.7.36

_Proguard/R8:_
- [ ]  Disabled

---
I have the following issue:
Sentry still uses deprecate getMappingFile() function, resulting in spamming logs at build time

**Steps to reproduce:**
- Add Sentry
- Build project

**Actual result:**
- Receiving: 
"
WARNING: API 'variant.getMappingFile()' is obsolete and has been replaced with 'variant.getMappingFileProvider()'. 

getMappingFile(): Cannot query the value of this property because it has no value available.
"

**Expected result:**
- Not receive it

**Comment by marandaneto** [comment]
dup https://github.com/getsentry/sentry-android-gradle-plugin/issues/29
