### ISSUE TITLE
how to build sentry android sdk with the sentry java source code?

### ISSUE THREAD

**Issue by guanbo123456** [getsentry/sentry-java#1042]
I have download the sentry java source code , but I cannot build the sentry android sdk. Should I modify the build.gradle.kts(sentry-android) or other file?

**Comment by marandaneto** [comment]
I don't follow the question, all you need to do is `make compile` as described here https://github.com/getsentry/sentry-java/blob/main/CONTRIBUTING.md

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
