### ISSUE TITLE
E/Sentry: Envelope submission failed

### ISSUE THREAD

**Issue by WenLonG12345** [getsentry/sentry-java#1044]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
compileSdkVersion - 29
buildToolVersion - 29.0.3

- [x]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
JavaVersion.VERSION_1_8

- [x]  Timber -> If yes, which version?
implementation 'com.jakewharton.timber:timber:4.7.1'

_IDE:_
- [x]  Android Studio -> If yes, which version?
4.1.1

_Build system:_
- [x]  Gradle -> If yes, which version?
6.5

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
4.1.1

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
classpath 'io.sentry:sentry-android-gradle-plugin:1.7.36'

_Proguard/R8:_
- [x]  Enabled

> 
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
          }

The version of the SDK:
**3.1.1**

---
I have the following issue:

I can't upload any Sentry log to the dashboard after updating from 1.7.5 (very old version) to 3.1.1. 
I had followed the required steps to setup Sentry in Android and also enable debug metadata in AndroidManifest. However, I got the following error. 

> 2020-11-13 17:21:10.866 27822-28022/io.chativo.chat D/Sentry: The transport failed to send the envelope with response code 403
2020-11-13 17:21:10.866 27822-28022/io.chativo.chat E/Sentry: Envelope submission failed
    java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
        at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:249)
        at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

I tried many solution but all is not useful. Please help me and point out any error that I had done in my setup for Sentry Android.

**Comment by marandaneto** [comment]
dup #1001 maybe?

**Comment by WenLonG12345** [comment]
Hi, yes, it is same problem with issue #1001 , but how can I update Sentry-server in my android studio project as mentioned in that issue?

**Comment by marandaneto** [comment]
@WenLonG12345 this is not a client (SDK) issue as described in the linked issue above.

you need to upgrade your sentry server if not using `sentry.io`.

Follow the steps: https://github.com/getsentry/onpremise#updating-sentry
