### ISSUE TITLE
Add example of sending tags with raven-logback

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-java#105]
Examples are provided for sending extra data via MDC, and setTags is provided on SentryAppender, but for an absolute newb like myself it's not obvious how I would actually bind the data.

(This might also affect some of the others)

**Comment by rtyley** [comment]
I think it might be worth extending the example to specify that `MDC.remove()` should be called immediately after the log statement to clear up that threadlocal-metadata - otherwise Confusion Will Ensure.

> Before returning the result however, the values for the client and number are cleared by calling the MDC.remove() method. Normally, a put() operation should be balanced by the corresponding remove() operation. Otherwise, the MDC will contain stale values for certain keys. We would recommend that whenever possible, remove() operations be performed within finally blocks, ensuring their invocation regardless of the execution path of the code.

http://logback.qos.ch/manual/mdc.html
