### ISSUE TITLE
sentry-spring failed integration

### ISSUE THREAD

**Issue by ishin-pie** [getsentry/sentry-java#1051]
_Platform:_
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  IntelliJ -> If yes, which version?

_Build system:_
- [ ]  Gradle -> If yes, which version? 

The version of the SDK:
**3.1.3**

---
I have the following issue:

Configuration problem: io.sentry.spring.SentryInitBeanPostProcessor was @Import'ed but is not annotated with @Configuration nor does it declare any @Bean methods; it does not implement ImportSelector or extend ImportBeanDefinitionRegistrar. Update the class to meet one of these requirements or do not attempt to @Import it.|Offending resource: class path resource [io/sentry/spring/SentryInitBeanPostProcessor.class]

**Comment by maciejwalkowiak** [comment]
Thanks for reporting. I need some more information: do you use Spring Boot or plain Spring? Which version of Spring is it?

**Comment by ishin-pie** [comment]
thank you for your response, I use Spring version 4.0.6.RELEASE

**Comment by maciejwalkowiak** [comment]
We did not implement support for 4.x although this issue should not exist with Spring 4.2+. Is it possible for you to upgrade to newer Spring version? I imagine upgrading to 5.x may be not that straightforward, but at least to the latest version from 4.x line - 4.3.29.RELEASE?

**Comment by marandaneto** [comment]
@maciejwalkowiak it'd be nice to document the required min. version for Spring and a fallback link to the old SDK version?
