### ISSUE TITLE
Version 3.2.0 fails to connect via proxy using http.host && http.port properties.

### ISSUE THREAD

**Issue by benrkia** [getsentry/sentry-java#1072]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? 1.8
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [x]  Logback -> If yes, which version? 1.2.3
- [x]  Spring -> If yes, which version? Spring boot 2.1.8.RELEASE

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [x]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [x] Manually

The version of the SDK:
**3.2.0**

---
I have the following issue:

We had that same issue using version **3.1.1**, searching in the issues I found that a fix has been made and merged in release 3.2.0. Yet, we're still having the same issue.
Nonetheless, cruising the source code i found that the class [SentryOptions](https://github.com/getsentry/sentry-java/blob/8160083c83ea6cb9e0fb14fd652fde30fef70ff4/sentry/src/main/java/io/sentry/SentryOptions.java#L257) load the properties `host, port, user, and pass` using **proxy** as prefix and not **http**.
Only in version `3.2.0` using **sentry.proxy.host and sentry.proxy.port** works fine.

PS: we're using `sentry-spring-boot-starter`.

**Steps to reproduce:**

- Use `sentry-spring-boot-starter` version `3.1.1` or `3.2.0`.
- Follow the doc to setup a connection via proxy.

**Actual result:**
- Sentry sends the report even if the proxy credentials are arbitrary.

**Expected result:**
- Sentry should send the report only if the proxy config is valid.

**Comment by maciejwalkowiak** [comment]
Thanks for pointing out that docs don't match the actual property. This will be fixed vey soon.

**Comment by benrkia** [comment]
@maciejwalkowiak Thanks for your reply. I tried to inject the proxy config using code (Sentry.init or other alternatives) but it doesn't seem to work.

**Comment by maciejwalkowiak** [comment]
> Only in version 3.2.0 using sentry.proxy.host and sentry.proxy.port works fine.

Do you mean that you managed to set the proxy properties but the SDK still does not connect via proxy? Do you have any exceptions? What is the behavior?

**Comment by benrkia** [comment]
I'll list all the scenarios I've tested.

- Version `3.1.1`: sentry.proxy.host is ignored. hence, works just like if there is no proxy config.
- Version `3.2.0`:
  - Setting the values via application.properties work as expected. Except for ignoring proxy if proxy.port value is arbitrary, e.g. "string"
  - Using Sentry.init doesn't seem to work. It does break in case I didn't set the dsn. Otherwise, it works as if sentry is not configured.

**Comment by maciejwalkowiak** [comment]
> * Version `3.1.1`: sentry.proxy.host is ignored. hence, works just like if there is no proxy config.

It was broken indeed in 3.1.1. There you can set it only manually.

> * Version `3.2.0`:
>   
>   * Setting the values via application.properties work as expected. Except for ignoring proxy if proxy.port value is arbitrary, e.g. "string"

If you enable debug on Sentry options you should get a warning about wrong data format for port.

>   * Using Sentry.init doesn't seem to work. It does break in case I didn't set the dsn. Otherwise, it works as if sentry is not configured.

Do you mean here that manual init does not work when used in Spring Boot application? Could you provide a sample that reproduces it?

When using Spring, configuring proxy via `application.properties` is the way to go.

**Comment by benrkia** [comment]
Actually, we're maintaining a legacy app that has a configuration class that contains `proxy config` + other stuff. So, it'd be good if i can init the proxy using these variables.
I tried to init sentry using:
```java
Sentry.init(options -> {
  options.setDsn("url");
  options.setProxy(new SentryOptions.Proxy("host", "port"));
})
```
But it didn't work. I tried to do this initialization in different places namely, inside main, @PostConstruct...
Also, I tried to override the `SentryProperty` bean but it didn't work.

**Comment by maciejwalkowiak** [comment]
You can define custom `Sentry#OptionsConfiguration` bean which will overwrite the original one: https://github.com/getsentry/sentry-java/blob/main/sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java#L61

This means that you can set proxy details there and if you need any of the functionality from the original bean you would need to replicate it. Let me know if it helps.
