### ISSUE TITLE
Add an API health check which guarantees that the SDK and Network (Firewall, Proxy, etc) are properly configured

### ISSUE THREAD

**Issue by fmartinou** [getsentry/sentry-java#1078]
_Platform:_
- [X]  Java 11
- [X]  Logback 1.2.3
- [X]  Spring Boot 2.3.5

_IDE:_
- [X]  IntelliJ

_Build system:_
- [X]  Gradle 6.7

_Android Gradle Plugin:_
- [X]  No

_Sentry Android Gradle Plugin:_
- [X]  No

_Proguard/R8:_
- [X]  Disabled

_Platform installed with:_
- [X] Maven Central

The version of the SDK:
**3.2.0**

---

Hi,

I'm migrating from 1.7.30 to 3.2.0.

I was using the `addEventSendCallback(myCallback)` to compute the Readiness of the Applications:
1. Send an event to sentry
2. Wait for the callback to determine if the event has been successfully sent or not
3. Adjust the readiness status of the App

After having upgraded to 3.x, it seems that **this callback has been removed from the SDK**.
The only callbacks mentioned in the documentation/API  refer to the EventProcessors which run before to send the event.

**Do you know a solution with SDK 3.x to implement a Readiness check at the startup of the application?**
Or a way to get a feedback after an event has been sent (with success or failure) to Sentry?

Regards

**Comment by bruno-garcia** [comment]
The unified API has a callback called `beforeSend`:

https://docs.sentry.io/platforms/java/configuration/filtering/#filtering-error-events

We don't have a hook for after the transport. Basically there's no guarantee that the event will make it to Sentry for multiple reasons that include: Inbound filter, transport dropping due to overflowing, rate limiting, over quota etc.

**Comment by fmartinou** [comment]
I get your point regarding the fact that there is no guarantee that the event is successfully ingested because of rate limiting etc...

Our basic need is just to detect if the SDK is properly configured and ready to send events to a Sentry (on-premise) instance:
- Is the http configuration ok (proxy, routing, certs...)?
- Is the DSN ok (project exist...)?

We implemented this feature with SDK 1.x and integrated it into the regular [/health](https://www.baeldung.com/spring-boot-actuators) of Spring Boot.

```json
curl http://my-spring-boot-app/actuator/health

{
   "status":"UP",
   "components":{
      "diskSpace":{
         "status":"UP"
      },
      "sentry":{
         "status":"UP"
      }
   }
}
```

Those checks occur at startup and then every minute (caused by Nagios checks).
(We have a complex network with firewalling, proxies... and we'd want to be sure that the integration is ok)

I think it would be profitable for everyone if the SDK could implement a method to easily perform a healthcheck.

That what we did (homemade) with the SDK 1.x but now, with the SDK 3.x, I see no way to do it.
Maybe am I missing something?

**Comment by marandaneto** [comment]
@fmartinou I see, your use case makes sense, but the `addEventSendCallback` callback was more a workaround, so I'd rather tag this as a feature request.

**Comment by fmartinou** [comment]
Hi @marandaneto ,

Will you tag this issue as a feature request or do you want me to open a new issue?

**Comment by marandaneto** [comment]
I'll tag this one and rename the issue's title if thats ok

**Comment by fmartinou** [comment]
Hi @marandaneto 
Any news about this feature request?

**Comment by bruno-garcia** [comment]
This makes sense. We'll discuss this further internally as this ideally would be based on a Sentry health check endpoint (that makes sure your DSN is valid, etc)

**Comment by marandaneto** [comment]
we've agreed that that is indeed a use case but we'd not implement this on the SDK side.
you can though call the Sentry APIs manually or via sentry-cli yourself and be sure that everything works.

https://docs.sentry.io/api/events/
https://docs.sentry.io/product/cli/send-event/

**Comment by fmartinou** [comment]
Thanks @marandaneto for your answer.

Unfortunately the solutions you proposed are not very convenient for us :/

1. We cannot embed CLI stuff within our apps (multiple lightweight Docker containers)
2. Calling https://docs.sentry.io/api/events from our apps would require us to distribute authentication tokens with read-only access to the apps (overcomplicated for just healthchecks).
3. Calling https://docs.sentry.io/api/events from our apps would require us to authorize network access from our apps to the API (firewalling, reverse proxy...) whereas we don't want it for security reasons

We'll think about it but it would be so much easier if it was directly integrated into SDK.

**Comment by marandaneto** [comment]
@fmartinou yep, that makes sense, but there are some downsides doing it on the SDK level as well.
it'd need to be a blocking call, do we charge for the request? would you call the health check for each event? it could be easily abused etc
