### ISSUE TITLE
No sane way of configuring SSLSocketFactory in Spring Boot integration

### ISSUE THREAD

**Issue by Infeligo** [getsentry/sentry-java#1080]
_Platform:_
- [x]  Java 11
- [x]  Spring Boot 2.3.0

_IDE:_
- [x]  IntelliJ 2020.2

_Build system:_
- [x]  Gradle 6.3

_Platform installed with:_
- [x] Maven Central

The version of the SDK:
**3.2.0**

---
I have the following issue:

Trying to configure custom `SSLSocketFactory` with Sentry's Spring Boot integration, but there does not seem to be a sane way.

1. Creating an own `HttpTransport` bean, which is seemingly the suggested way, is not trivial. I would have used `HttpTransportFactory`, but it is package-private. It's added value is that it parses DSN from `SentryOptions` to extract credentials necessary for `HttpTransport`. Trying to recreate this logic is also difficult, because `Dsn` class, which does the parsing, is also package-private.

2. Provide own `Sentry.OptionsConfiguration<SentryOptions>` bean to be able to manually configure `SentryOptions` has one significant problem: I am not able to set the default `inAppIncludes`. Those are provided by auto-configured `InAppIncludesResolver`, which is package-private. It can be only configured within the autoconfiguration class.

Is there a way that I am missing?

**Comment by maciejwalkowiak** [comment]
Thanks @Infeligo for reporting. `InAppIncludesResolver` should have been public from the start - my bad. It will be fixed in https://github.com/getsentry/sentry-java/pull/1084.

**Comment by bruno-garcia** [comment]
I think we still need to discuss a way to expose configuring `SSLSocketFactory`

**Comment by maciejwalkowiak** [comment]
It would be now to override `OptionsConfiguration` bean, but we can make it even easier - users would have to provide a bean of type `SSLSocketFactory ` with name `sentrySSLSocketFactory`. What do you think?

**Comment by Infeligo** [comment]
Just to add a note about injecting `ITransport`. It is nearly impossible to create own properly configured instance of `HttpTransport` close to default settings. This is because the constructor takes in `SentryOptions` and configures own serializer using by calling `options.getSerializer()`. However, if I would like to use the default serializer, then I would not get one before `Sentry.init` is called. Until then I get a `NoOpSerializer`.

**Comment by Infeligo** [comment]
> It would be now to override `OptionsConfiguration` bean, but we can make it even easier - users would have to provide a bean of type `SSLSocketFactory ` with name `sentrySSLSocketFactory`. What do you think?

I would personally prefer an additive customization approach similar to `RestTemplateCustomizer`. Currently, overriding the autoconfigured `Sentry.OptionsConfiguration` bean is all-or-nothing approach.

Also note that alongside `SSLSocketFactory` one needs to configure `HostnameVerifier`.

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/getsentry/sentry-java/pull/1093
