### ISSUE TITLE
Adding breadcrumbs taking too much on Android

### ISSUE THREAD

**Issue by samiazar** [getsentry/sentry-java#1081]
Recently I've decided to add breadcrumbs for getting more details on crash reports.
But I notice each time by using the `addBreadcrumb()` method it take too much time (about 10 ms) on the UI thread.

Here is how I try to measure the time of this method.

```
long time = System.currentTimeMillis();
Breadcrumb breadcrumb = new Breadcrumb();
breadcrumb.setCategory("Event");
breadcrumb.setMessage(s);
breadcrumb.setLevel(SentryLevel.INFO);
mScope.addBreadcrumb(breadcrumb);
Timber.w("Adding breadcrumbs take %s millis", System.currentTimeMillis() - time);
```

And here is the result:
<img width="496" alt="Screen Shot 1399-09-11 at 18 02 42" src="https://user-images.githubusercontent.com/23658371/100753719-69d25080-33ff-11eb-97d4-760adfeed9de.png">
.

I think it's not expected. For logging, I almost dropping a frame on the UI.
Do you have a plan to optimize this?
I really need this feature but now its cost is heavy

**Comment by bruno-garcia** [comment]
Do you have a `beforeBreadcrumb` callback defined in your `SentryOptions`?
Is scope synchronization enabled? 

https://github.com/getsentry/sentry-java/blob/3ed2ff105dd246cbf0242e802543c710bcb14a0b/sentry/src/main/java/io/sentry/SentryOptions.java#L1106-L1108

What version of the SDK. Is this on a emulator, device? What device?

**Comment by samiazar** [comment]
Thank you for your quick response.

The sentry version was 3.0.0 and I didn't have a `beforeBreadcrumb` callback and scope synchronization was disabled.
But after more investigating finally, I figure it out that the problem is about using `getCurrentDateTimeOrNull` method from `DateUtils` class.
https://github.com/getsentry/sentry-java/blob/3ed2ff105dd246cbf0242e802543c710bcb14a0b/sentry/src/main/java/io/sentry/Breadcrumb.java#L64

This method takes too much time. I try to use the constructor of the Breadcrumb that get `Date` object but this constructor was package-private. 
After all, by updating the sentry version into 3.2.0 I see this constructor being public.
So I creating breadcrumb with a simple `Date` object. (just `new Date()`)
My issue is resolved but maybe you want to optimize the `getCurrentDateTimeOrNull` for the future.

All these benchmarking had been tested on the Samsung-j7 prime.

**Comment by bruno-garcia** [comment]
@samiazar as you can see the linked PR above done to improve this.
We'll release a new preview tomorrow that'll include this fix.

**Comment by marandaneto** [comment]
@samiazar just be aware that `new Date()` will get device's timezone instead of UTC which is what we do with the `getCurrentDateTimeOrNull`.
the latest alpha has some improvements, please test it out and let us know if it got any better.

**Comment by samiazar** [comment]
Thank you guys for quick action.

I checked the latest alpha release and here is the result of my benchmark on the same device:

<img width="307" alt="Screen Shot 1399-09-23 at 09 18 53" src="https://user-images.githubusercontent.com/23658371/102004321-da913b00-3d24-11eb-8e18-144435261d87.png">

I can see improvement and the time for creating breadcrumb has optimized.
But take look when I use `new Breadcrumb(new Date())` how is the result:

<img width="305" alt="Screen Shot 1399-09-23 at 09 22 20" src="https://user-images.githubusercontent.com/23658371/102004341-0ca29d00-3d25-11eb-8d7f-462153a817ec.png">

Still, I prefer to create breadcrumbs in this way over the default constructor of it.
Again, All these benchmarking had been tested on the Samsung-j7 prime.

**Comment by maciejwalkowiak** [comment]
@samiazar big thanks for reporting back the benchmark results!

**Comment by marandaneto** [comment]
@samiazar just out of curiosity, how did you measure your 2nd benchmarking?
I ask that because I see floating values and your code above subtract both longs, it can't be a float value unless you either did formatting or the code snippet is not accurate, thanks.

**Comment by samiazar** [comment]
@marandaneto for sure. I have used `System.nanoTime()` and then convert the nano time into millisecond.
The reason was to show more accurate spent time for evaluating.

**Comment by marandaneto** [comment]
@samiazar thanks, we've improved even more and 4.x is pretty fast, I've done some benchmarking with https://openjdk.java.net/projects/code-tools/jmh/ btw.
