### ISSUE TITLE
No Browser and no Enviroments in Issue panel (sentry-spring-boot 3.2.x)

### ISSUE THREAD

**Issue by SrMouraSilva** [getsentry/sentry-java#1089]
_Platform:_
- [x]  Logback -> If yes, which version? the default version of **Spring 2.4.0**
- [x]  Spring -> If yes, which version? **Spring 2.4.0**

_IDE:_
- [x]  IntelliJ -> If yes, which version? **2020.3**

_Build system:_
- [x]  Gradle -> If yes, which version?  **6.6.1**

_Platform installed with:_
- [x] JCenter (maybe)
- [x] Maven Central (maybe)

The version of the SDK:
**3.2.x**

---
I have the following issue:

Currently (Sentry-java 3.2.0), no Browser and no Environments information in sentry's Issues panel

In Sentry **1.7.30-7a445**
![image](https://user-images.githubusercontent.com/5341804/100950671-9bc0e100-34eb-11eb-8486-d9a0ba29ecba.png)
![image](https://user-images.githubusercontent.com/5341804/100950692-a4b1b280-34eb-11eb-88db-e087a9636d83.png)
![image](https://user-images.githubusercontent.com/5341804/100950726-be52fa00-34eb-11eb-9c52-55092ea3a05d.png)
![image](https://user-images.githubusercontent.com/5341804/100950768-dcb8f580-34eb-11eb-8098-c8f2ad768934.png)

Now (Sentry **3.2.0**)

![image](https://user-images.githubusercontent.com/5341804/100951057-85675500-34ec-11eb-9a9d-4fdd84a124fd.png)

**Steps to reproduce:**
- Relevant configurations:

**build.graddle.kt**
```kotlin
//...
implementation("io.sentry:sentry-spring:3.2.0")
implementation("io.sentry:sentry-logback:3.2.0")
//...
```

**SentryConfig.kt**
```kotlin
// The SentryExceptionResolver is registered only if uses "@EnableSentry"
@EnableSentry
@Configuration
class SentryConfig {

    @Value("\${spring.application.name}")
    private lateinit var appName: String

    @Value("\${sentry.dsn}")
    private lateinit var dsn: String

    @Value("\${sentry.environment:develop}")
    private lateinit var environment: String

    @Value("\${sentry.release:develop}")
    private lateinit var release: String

    @Value("\${sentry.in-app-include}")
    private lateinit var inAppInclude: Array<String>

    @Value("\${sentry.send-default-pii}")
    private var sendDefaultPii: Boolean = false

    @PostConstruct
    fun initialize() {
        Sentry.init { options: SentryOptions ->
            options.dsn = dsn
            options.environment = environment
            options.release = release
            options.inAppIncludes.addAll(inAppInclude)
            options.isSendDefaultPii = sendDefaultPii
        }
        Sentry.setTag("application", appName)
        Sentry.setExtra("KEYCLOAK_RESOURCE", ...)
    }
}
```

The user information is inserted by 
```kotlin
@Component
@Order(Ordered.LOWEST_PRECEDENCE)
class SentryFilter : GenericFilterBean() {

    @Inject
    private lateinit var autenticacao: InternalClass1

    @Inject
    private lateinit var informacoesAcesso: InternalClass2

    @Inject
    private lateinit var informacoesTracing: InternalClass3

    @Inject
    private lateinit var informacoesAuditoria: InternalClass4

    override fun doFilter(request: ServletRequest, response: ServletResponse, chain: FilterChain) {
        if (informacoesAuditoria.isAutenticado()) {
            Sentry.setUser(createUser())
        }

        chain.doFilter(request, response)
    }

    private fun createUser(): User {
        return generateSentryUser(...)
    }

    private fun generateSentryUser(id: String?, name: String?, entity: InternalClass5): User {
        val user = User()

        user.id = id
        user.username = nome
        user.ipAddress = informacoesAcesso.ip
        user.email = entity.accessToken.email
        user.others = mapOf(
            "scope" to entidade.accessToken.scope,
        )

        return user
    }
}
```

**Actual result:**
- The user information
- No Browser information in Issues panel
- No Environment information in Issues panel

**Expected result:**
- Browser information in Issues panel
- Environment information in Issues panel

**Comment by maciejwalkowiak** [comment]
In 3.x events have a special field `request`. You need to take an instance of `HttpServletRequest` and convert it to Sentry `Request` like done here: https://github.com/getsentry/sentry-java/blob/d0bb29b7ee8cdd54108dd77fcfc8da620f4f860e/sentry-spring/src/main/java/io/sentry/spring/SentryRequestResolver.java#L18

But, could you use Sentry Spring Boot starter instead and just benefit from the auto-configuration? Or is there something that does not work for you and we could improve it?

**Comment by SrMouraSilva** [comment]
Hi @maciejwalkowiak! Thanks for the response

> But, could you use Sentry Spring Boot starter instead and just benefit from the auto-configuration? Or is there something that does not work for you and we could improve it?

I am using Sentry Spring Boot 3.2.0, but it doesn't auto configuring. I don't know exactly why. In Sentry 1.7.x works.

For example, the exceptions are only sent to the Sentry server when I add `@EnableSentry`. But in the documentation, in spring boot it isn't necessary. As you can observer, there are a `.yml` configuration that is defined `sentry.parameters`, but I still needed to call `Sentry.init` to work.

Based in your response, I think that are some misconfiguration. Probably some configuration change that occurred in Spring 2.4.0.

---

My project is a multi project. I think that I need create a empty Spring Boot project to replicate it and share with you...

**Comment by maciejwalkowiak** [comment]
As you said, there should be no need to use `@EnableSentry` if you use Spring Boot integration. Actually using `@EnableSentry` will prevent auto-configuration to configure beans. Ideally, remove your custom config classes, configure Sentry Spring Boot integration and run your application with `debug=true` property to get the auto-configuration report and perhaps you will find why auto config is not triggered. If it doesn't help please send a minimal sample that reproduces this issue.

**Comment by SrMouraSilva** [comment]
I configured with `implementation("io.sentry:sentry-spring:3.2.0")` instead `implementation("io.sentry:sentry-spring-boot-starter:3.2.0")` 😐😐😐

Ok, now I'm using `io.sentry:sentry-spring:3.2.0` with `io.sentry:sentry-logback:3.2.0`.
`SentryConfig` and `SentryFilter` are commented. That is, the only thing I have is the addition of the dependencies and the configuration file it contains:

```yml
sentry:
  dsn: <my sentry dsn>
  in-app-include: <my package>
  enable-tracing: true
  send-default-pii: true
  logging.enabled: true
```

Still, no information is obtained from the spring boot server, nor from the browser :(

**Comment by marandaneto** [comment]
@SrMouraSilva this `session` is related to the [release health](https://docs.sentry.io/product/releases/health/) feature, not related to a browser session, this is only used for Mobile right now.

**Comment by SrMouraSilva** [comment]
Thanks, @marandaneto. 

So I don't know what the absence of browser information could be. 🙁

**Comment by marandaneto** [comment]
idk if the SDK or our backend infers the Browser automatically, the last case, you could still do:

`scope.getContexts().setBrowser(...)` manually, right, but if v1.7.x did it automatically, we'd need to figure this out, ideas @maciejwalkowiak ?

**Comment by maciejwalkowiak** [comment]
@SrMouraSilva could you please create a minimal sample project in separate github repository that reproduces this issue? There must be something off with the configuration. Once I see how exactly the project is set up I am very happy to help and perhaps improve the docs as a result.

**Comment by marandaneto** [comment]
@SrMouraSilva did you have the chance to try this out again? thanks

**Comment by SrMouraSilva** [comment]
Hello, I'm sorry for the lattency. Has a lot of work here, rsrs.

I will try to test again today. If doesn't works, I will prepare a github repository. Thanks!

**Comment by SrMouraSilva** [comment]
I'm sorry by the late resposne.
I will try to update to `4.0.0` today

**Comment by maciejwalkowiak** [comment]
@SrMouraSilva 4.1.0 is the latest :-)

**Comment by SrMouraSilva** [comment]
It's true! Thanks, @maciejwalkowiak!

I checked only at the [documentation](https://docs.sentry.io/platforms/java/guides/spring-boot/#install), not on [mvn](https://search.maven.org/artifact/io.sentry/sentry-spring-boot-starter).

**Comment by SrMouraSilva** [comment]
Ok, I update but this situation persists.

Note: I'm using REST
```kotlin
@RestController
@RequestMapping("/people")
@Api(tags = ["Person"], description="Person data")
class PessoaController {
    @GetMapping("details", produces=[MediaType.APPLICATION_JSON_UTF8_VALUE])
    fun method() {
        throw RuntimeException("Macarronada")
    }
}
```

I'm thinking and I conclude that the browser information isn't important for my backend. 
But by the frontend is important and Sentry works like a charm in it.

Also, the sentry-spring-boot obtains the browser details in the header. It only doesn't tag it.
![image](https://user-images.githubusercontent.com/5341804/107788626-60366480-6d2f-11eb-9b90-0ac2eac8a525.png)

**Comment by maciejwalkowiak** [comment]
User Agent header is present on the screenshot. Since you're making this call from postman Sentry doesn't recognize the browser. Or you mean something else?

How do you set the environment?

**Comment by SrMouraSilva** [comment]
> User Agent header is present on the screenshot. Since you're making this call from postman Sentry doesn't recognize the browser. 

Huuuum. Ok. I will close this issue :)

> How do you set the environment?

Now I'm using:
```
implementation("io.sentry:sentry-spring-boot-starter:4.1.0")
implementation("io.sentry:sentry-logback:4.1.0")
```

```yml
sentry:
  environment: ${SENTRY_ENVIRONMENT:develop}
  dsn: my-dsn
  in-app-include: br.ufc.something.something.something
  enable-tracing: ${SENTRY_ENABLE_TRACING:false}
  sample-rate: ${SENTRY_SAMPLE_RATE:1.0}
  send-default-pii: true
  logging.enabled: true
  debug: true
```

```kotlin
@Configuration
class SentryConfig {
    @PostConstruct
    fun initialize() {
        Sentry.setTag("application",  "something")
        Sentry.setExtra("KEYCLOAK_RESOURCE", "something")
    }
}
```
and
```kotlin
@Component
class CustomSentryUserProvider: SentryUserProvider {
   override fun provideUser(): User {
        if (informacoesAuditoria.isAutenticado()) {
            return criarUser()
        } else {
            return User()
        }
    }

    private fun criarUser(): User {
        // Build the user
    }
}
```
