### ISSUE TITLE
React native android - Unsafe implementation of the HostnameVerifier interface by Google PlayStore

### ISSUE THREAD

**Issue by Sinson48** [getsentry/sentry-java#1101]
Currently, we are facing an issue with HostnameVerifier from a third-party after publishing the app to the Google play store. Kindly help us to find out the issue / any of your customers had faced this issue previously?. We have got an email from Google play store as below.

'We found that your app uses software that contains security vulnerabilities for users. Apps with these vulnerabilities can expose user information or damage a user’s device, and may be considered to be in violation of our Malicious Behavior policy'   'Your app(s) are using an unsafe implementation of the HostnameVerifier interface.'

This app has been in the play store since 2 years.

We need to resolve this before the deadline 1 January 2021.

Please help me sort out this issue.

**Comment by marandaneto** [comment]
@Sinson48 in order to help you out, please fill-up the Issue template, also have a look at #861 and #840

**Comment by bruno-garcia** [comment]
The issue was transfered from another repo so the user wasn't presented with our issue template.

@Sinson48 the template is part of creating an issue here: https://github.com/getsentry/sentry-java/issues/new/choose

**Comment by marandaneto** [comment]
hey @Sinson48 any update on this? thanks

**Comment by bruno-garcia** [comment]
Closing it since it's a known no-issue already discussed here: #861 and #840

Feel free to reopen otherwise.
