### ISSUE TITLE
Upload libsentry symbols on tag builds

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1105]
Use symbol collector to upload symbols of sentry native during a tagged CI run

**Comment by marandaneto** [comment]
if we do it only on CI, we depend on #1063

**Comment by bruno-garcia** [comment]
Also, for reference, this is how it's done:

https://github.com/getsentry/symbol-collector/tree/main/src/SymbolCollector.Console#build-the-project-and-upload-symbols-and-images-from-a-specific-path

**Comment by marandaneto** [comment]
related to #908

**Comment by marandaneto** [comment]
@bruno-garcia I might have found a workaround for that.

https://android-developers.googleblog.com/2020/10/android-studio-41.html

See the flag `android.buildTypes.release.ndk.debugSymbolLevel`

> Supported values are 'none' (default, no native debug metadata will be packaged),
>      * 'symbol_table' (only the symbol tables will be packaged), and 'full' (the debug info and
>      * symbol tables will be packaged)

that means, our AAR files will contain debug symbols if we enable this option, so when people upload their own symbols, sentry's debug symbols will be uploaded too.
this would increase the AAR's size, but only by downloading them, the final App compilation will strip out the symbols anyway, wdyt?
I'd need to test that, of course.

**Comment by bruno-garcia** [comment]
Sounds like a good idea. Although it's convenient to users that we upload the symbols for them and leave it in a generic Android bucket, instead of each project having a copy of it.

**Comment by marandaneto** [comment]
> Sounds like a good idea. Although it's convenient to users that we upload the symbols for them and leave it in a generic Android bucket, instead of each project having a copy of it.

yep, I agree, this would be a temporary workaround while we don't fully automatize this process over craft

**Comment by marandaneto** [comment]
current commands are:

```
export VERSION={version}
cd sentry-android-ndk
{SymbolCollectorFolder}/SymbolCollector.Console --upload directory --path ./ --batch-type android --bundle-id sentry-android-ndk-$VERSION --server-endpoint https://symbol-collector.services.sentry.io
cd ..
```

**Comment by marandaneto** [comment]
Craft does it now: https://github.com/getsentry/sentry-java/blob/main/.craft.yml#L4-L7
