### ISSUE TITLE
environment is always `production` in 3.2.0

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-java#1106]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [X]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? `11`
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [X]  Logback -> If yes, which version? 
- [X]  Spring -> If yes, which version? `2.2.6`

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [X]  Other -> If yes, which one? `VSCode`

_Build system:_
- [X]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Proguard/R8:_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [X] Manually

The version of the SDK:
**3.2.0**

---
I have the following issue:

With a setup like this:

```java
	Sentry.init(
			options -> {
				options.setEnableExternalConfiguration(true);
				options.setRelease("fabscale-api-app@" + version);
				options.setEnvironment("development");
```

I still get environment `production` on 3.2.0. When I downgrade to 3.1.0, it works as expected.
I first thought it was something with the environment not being picked up from `sentry.properties` but it even happens when I directly set the environment. 

We use spring boot and logback

```
implementation 'io.sentry:sentry-spring-boot-starter:3.2.0'
implementation 'io.sentry:sentry-logback:3.2.0'
```

**Comment by marandaneto** [comment]
@mydea `sentry-spring-boot-starter` already calls `Sentry.init` automatically, you just need to configure either the properties or yml file, or via logback as well.

https://docs.sentry.io/platforms/java/guides/spring-boot/#configure

I guess what's happening is, the automatic integration is overriding your value, by default, If an `environment` is not set, we set `production` by default.

@maciejwalkowiak to confirm

**Comment by mydea** [comment]
Hmm, but I also have `environment=development` set in my `sentry.properties` file, which is also ignored. That was the first step, I only added the `options.setEnvironment("development")` declaration to make sure the problem is not in being picked up from the properties file.

**Comment by maciejwalkowiak** [comment]
@mydea yes, in Spring Boot integration we follow Spring's traditional way of providing configuration.
