### ISSUE TITLE
Global tags not picked up

### ISSUE THREAD

**Issue by francisdb** [getsentry/sentry-java#1110]
Platform:

    Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? openjdk 11.0.8 2020-07-14
    Logback -> If yes, which version? 1.2.3

Build system:

    Other -> If yes, which one? sbt

Platform installed with:

    Maven Central

The version of the SDK:
3.2.0

---
I have the following issue:

Globally configured tags are not used when sending exceptions to sentry

**Steps to reproduce:**

Create a small project and do as below

- in main call `System.setProperty("sentry.tags.foo", "bar")` before logging an exception
- in sentry.properties add `tags.foo2=bar2`
- set an env var `SENTRY_TAGS_FIRST_TAG=first-tag-value`

**Actual result:**
- No tags reported

**Expected result:**
- All three tags reported (or at least one, see #874)

Side note:
It would be nice if we could enable debug and see sentry log it's final configuration options

**Comment by maciejwalkowiak** [comment]
This issue has been resolved in SDK 4.0.0-alpha.2. Could you please check if it works well for you after upgrade?

**Comment by francisdb** [comment]
`alpha.2` that does not sound like something we want to use in production

**Comment by maciejwalkowiak** [comment]
@francisdb fair point. It's alpha because the performance feature that's there is under development and the apis may change but I understand your concern. We plan to release 4.0 final in January.

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/getsentry/sentry-java/commit/bb58d451141ed2b8b38c5f762db07577f3b7e998, to be released in 4.0

**Comment by jadbaz** [comment]
I'm not sure this is place for this, but I wanted to point out that it's not clear at all that the tags are not additive.
I would have supposed that tags are added additive in that if we add tags A,B in the environment and we add tags C,D,E in a properties file, we would have A,B,C,D,E. Instead, we end up with the tags from the environment only (A,B)
I'd say there is a definite use case for merging tags

**Comment by francisdb** [comment]
@jadbaz is that on the 4.x beta?

**Comment by jadbaz** [comment]
Yep

**Comment by francisdb** [comment]
I agree that this is somewhat unexpected

**Comment by marandaneto** [comment]
> I'm not sure this is place for this, but I wanted to point out that it's not clear at all that the tags are not additive.
> I would have supposed that tags are added additive in that if we add tags A,B in the environment and we add tags C,D,E in a properties file, we would have A,B,C,D,E. Instead, we end up with the tags from the environment only (A,B)
> I'd say there is a definite use case for merging tags

there's a use case for merging tags, indeed, please upvote https://github.com/getsentry/sentry-java/issues/874
it's not related to this issue though.

**Comment by marandaneto** [comment]
> I agree that this is somewhat unexpected

related to this issue, yes, it's possible to set tags from external configurations, they don't merge yet though
