### ISSUE TITLE
Add Sentry.init overload that takes a Map

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1117]
To make it easier for wrapping SDKs like Flutter and ReactNative, take a map on `Sentry.init`, which can create a SentryOptions and call an overload with it.

**Comment by bruno-garcia** [comment]
If possible, use this from the Android manifest metadata reader too.

**Comment by adinauer** [comment]
@marandaneto should we close this or do we need it for future hybrid SDKs?

**Comment by marandaneto** [comment]
> @marandaneto should we close this or do we need it for future hybrid SDKs?

This reduces boilerplate on the SDK side, so I think we should still do it.

**Comment by marandaneto** [comment]
We decided that having a Map also has downsides, it introduces new problems, ideally, we'd have a shared library for iOS and Android, or any other solution that would not bring other problems.
