### ISSUE TITLE
Make Attachment immutable

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-java#1120]
Attachment has a [setter for contentType](https://github.com/getsentry/sentry-java/blob/b7b5523430dd666577339dc8588e634df20bfb13/sentry/src/main/java/io/sentry/Attachment.java#L108-L110). We can remove the setter and pass the param to the constructors instead. This means we need to add two constructors:
```Java
public Attachment(final @NotNull String pathname, final @NotNull String filename, final @NotNull String contentType) {
  // ...
}

public Attachment(final @NotNull byte[] bytes, final @NotNull String filename, final @NotNull String contentType) {
  // ...
}
```

With this, we achieve immutability for Attachments.

**Comment by philipphofmann** [comment]
@bruno-garcia, @marandaneto, @maciejwalkowiak any objections to this change?

**Comment by marandaneto** [comment]
no objections, just out of curiosity, what was the motivation to be a setter before? if none, even better :D

**Comment by philipphofmann** [comment]
I think I thought having to pass 3 parameters to a constructor is maybe a bit too much and we were not really sure back then if we even need content type. I think 3 parameters are fine. I can't remember what drove me back then.
