### ISSUE TITLE
Add crashedLastRun

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-java#1125]
Add ~a callback~ crashedLastRun to SentryOptions that is called by the SDK passing the event
when Sentry is initialized and the last program execution terminated with a crash.

PR in Cocoa: https://github.com/getsentry/sentry-cocoa/pull/808
Docs in Cocoa: https://docs.sentry.io/platforms/apple/enriching-events/user-feedback/

On Cocoa, we have the advantage that crashes get written to disk by SentryCrash and then the SDK processes them the next time the app starts. So we can check in the [`prepareEvent`](https://github.com/getsentry/sentry-cocoa/blob/9eedc425727f0daccca1bd2be6021f6c3d9c654c/Sources/Sentry/SentryClient.m#L401-L406) of the `Client` if the current event is a crash and call the callback.

On Java, this is a bit more tricky, because the crash event could be sent before the app shuts down. Therefore we need to store the eventID of the crash somewhere, so it is still there when the app starts the next time.

**Comment by marandaneto** [comment]
related to #911

**Comment by bruno-garcia** [comment]
We discussed that an update to the docs is due first: https://develop.sentry.dev/sdk/features/#user-facing-platforms

And that this callback will be taken via the public, static API so the user can call when they are ready to get their callback invoked/get the UI shown to the user.

**Comment by bruno-garcia** [comment]
We dropped the idea of using a callback here. Copying for #1569 

> Similar to the iOS API crashedLastRun: getsentry/sentry-cocoa/search (crashedlastrun)

> We'd like to know if the previous execution resulted in a crash (via Java or Native) while on an Android app.
? This will be used by Unity (see getsentry/sentry-dotnet#1096)

> This could live on SentryAndroid static class.
