### ISSUE TITLE
User.setOthers is marked @Nullable but crashes when passing in null

### ISSUE THREAD

**Issue by angusholder** [getsentry/sentry-java#1131]
_Platform:_
- Android target SDK 29, compile SDK 29
- Java sourceCompatibility 1.8/targetCompatibility 1.8
- Kotlin 1.4.10

_IDE:_
- Android Studio 4.1

_Build system:_
- Gradle 6.5

_Android Gradle Plugin:_
- 4.1

The version of the SDK:
**io.sentry:sentry-android:3.2.0**

---
I have the following issue:

[`User.setOthers`](https://github.com/getsentry/sentry-java/blob/082b4b56575ae7c20bf423f085c38605b194e680/sentry/src/main/java/io/sentry/protocol/User.java#L128) is documented as accepting null, but crashes when passing null, as it passes this straight into `new ConcurrentHashMap(Map)`, which does not accept null.

**Comment by marandaneto** [comment]
@angusholder thanks for raising this, we'll work on it.

**Comment by marandaneto** [comment]
it'll be available in the next release, thanks for reporting.
