### ISSUE TITLE
Empty DSN on Spring configuration fails disable Sentry

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1132]
My app. fails to start when passing sentry.dsn=${SENTRY_DSN:""} or sentry.dsn=${SENTRY_DSN:}, using 3.x

```
Failed to instantiate [io.sentry.IHub]: Factory method 'sentryHub' threw exception; nested exception is 
io.sentry.InvalidDsnException: java.net.URISyntaxException: Illegal character in path at index 0: ""
how to disable it locally?
```

From this comment: https://github.com/getsentry/sentry-java/issues/574#issuecomment-749166589

**Comment by jenni** [comment]
thanks @bruno-garcia !
I am passing `sentry.dsn=${SENTRY_DSN:https://key@host/id}` as a workaround.
also, would gladly pick this issue as a first contribution, seems straight forward, it is expected that works with both "" and null, right?

**Comment by marandaneto** [comment]
@jenni sure, go for it.

just a quick question: are you using an integration? logback, log4j2 or spring?
how are you setting up your configurations? eg `sentry.properties`, `application.properties`?

have you tried as simple as `sentry.dsn=` ? without the `${SENTRY_DSN:something}`

**Comment by jenni** [comment]
@marandaneto 
I've just tried again
it now works with `${SENTRY_DSN:}` (I might've had some wrong or cached config)
but not with `${SENTRY_DSN:""}`, which I'm assuming it's expected since the value of dns is literally the chars "" in this case

**Comment by maciejwalkowiak** [comment]
Thanks @jenni for taking a look. I have also double checked it and as you said, `sentry.dsn=${SENTRY_DSN:}` works as expected. 

Sample repo: https://github.com/maciej-scratches/sentry-empty-dsn
