### ISSUE TITLE
HttpInterface "data" should not include query params

### ISSUE THREAD

**Issue by aldenquimby** [getsentry/sentry-java#114]
According to the [docs](http://sentry.readthedocs.org/en/latest/developer/interfaces/#sentry.interfaces.http.Http), query parameters shouldn't be included in `data`, only form params or the raw request body should be in there.

Logging the raw request body would probably be tricky because you'd also need some way to exclude certain requests (like a file upload), and/or limit the body size.

I'm not sure how to do it, but I image the form params can be pulled from ServletRequest without the query params

**Comment by pascalw** [comment]
I'm also running into this. It's highly confusing to see the query string expressed in a JSON like manner as if it were the request body:

```
{
  argument: [
    value
  ]
}
```

@ColinHebert it seems the reason for this is to report the request body when a form is submitted, correct? If so, would it be possible to only use this behaviour if the request is form encoded?
