### ISSUE TITLE
API request failed: Invalid token (http status: 401)

### ISSUE THREAD

**Issue by WenLonG12345** [getsentry/sentry-java#1140]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
compileSdkVersion - 29
buildToolVersion - 29.0.3

- [x]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
JavaVersion.VERSION_1_8

- [x]  Timber -> If yes, which version?
implementation 'com.jakewharton.timber:timber:4.7.1'

_IDE:_
- [x]  Android Studio -> If yes, which version?
4.1.1

_Build system:_
- [x]  Gradle -> If yes, which version?
6.5

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
4.1.1

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
classpath 'io.sentry:sentry-android-gradle-plugin:1.7.36'

_Proguard/R8:_
- [x]  Enabled

> 
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
          }

The version of the SDK:
**3.2.0**

---
I have the following issue:

I can't point my application from debug mode to release mode. Sentry works fine in debug mode but not release mode. I got the following error. 

> Task :app:persistSentryProguardUuidsForProdReleaseProd-release
> compressing mappings
> uploading mappings
error: API request failed
  caused by: sentry reported an error: Invalid token (http status: 401)

> Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output. Please attach the full debug log to all bug reports.

I saw many people asking on this issue in Sentry/react-native but not java. 
Please help me to point out what mistake had I done since it works perfectly in debug mode. Thanks in advanced.

**Comment by WenLonG12345** [comment]
I found that when 

build.gradle(app)
```
minifyEnabled false <--- can work perfectly  

minifyEnabled true  <--- cannot be built with error of Invalid token(http status:401) 
```

but I read the documentation on R8, it said all already handled by Sentry Android Gradle Plugin (SAGP). 
Please help me as I need to build a release app based on this Sentry urgently

**Comment by bruno-garcia** [comment]
@WenLonG12345 sounds like you didn't add the Sentry auth token. You need that to get permission to push the mappings file to Sentry.

**Comment by WenLonG12345** [comment]
Thanks for the suggestion. I had discuss with my backend team and they had already working on it. 
Thanks for the reply as well 👍

**Comment by marandaneto** [comment]
this is the docs btw https://docs.sentry.io/platforms/android/proguard/
