### ISSUE TITLE
environment and other fields are missing for transactions

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1147]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [X]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
4.0.0-alpha.2

---
I have the following issue:

`transaction` belongs to `SentryEvent` instead of `SentryBaseEvent`.
`SentryTransaction` extends `SentryBaseEvent`, so no `environment` is set.

https://docs.sentry.io/product/performance/distributed-tracing/#transactions

describes that `environment` and other fields should be part of the transaction.

**Steps to reproduce:**
enable tracing, set environment

**Actual result:**
transaction doesn't have `environment` field

**Expected result:**
`transaction` has environment field

**Comment by marandaneto** [comment]
in case this was left out purposely, would you mind elaborating? thanks

**Comment by maciejwalkowiak** [comment]
At the time transactions were implemented it was not clear which fields are common for events and transactions. If you could point which properties from the `SentryEvent` should be moved to `SentryBaseEvent` I am happy to move them.

**Comment by marandaneto** [comment]
> At the time transactions were implemented it was not clear which fields are common for events and transactions. If you could point which properties from the `SentryEvent` should be moved to `SentryBaseEvent` I am happy to move them.

I see, I don't know how to answer either, people that might know is still on vacation, so I'd just start with its written in the docs, link above.
`environment` and `release` are supposed to be part of the transaction.

**Comment by bruno-garcia** [comment]
> environment and release are supposed to be part of the transaction.

yeah for these for sure. We should discuss more broadly the rest
