### ISSUE TITLE
Deprecate cachDirSize and add maxCacheItems

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-java#1162]
Deprecate [`cacheDirSize`](https://github.com/getsentry/sentry-java/blob/81594398ee623b40eb9df1a847dbe21d9e4c25ef/sentry/src/main/java/io/sentry/SentryOptions.java#L108) and introduce maxCacheItems instead. The name `cacheDirSize` doesn't clearly state that it is related to the number of items stored on the disk. Users could be confused and think it is related to KB or MB. `maxCacheItems` communicates the number of items more clearly.

Related issues:
- https://github.com/getsentry/sentry-cocoa/issues/899
- https://github.com/getsentry/sentry-dotnet/issues/736
- https://github.com/getsentry/sentry-docs/issues/2879

**Comment by philipphofmann** [comment]
Also enable this in the basic options of the docs after fixing this issue.

**Comment by marandaneto** [comment]
when doing this, also please add the breaking change to https://docs.sentry.io/platforms/android/migration/
and support for android in the docs https://docs.sentry.io/platforms/android/configuration/options/
