### ISSUE TITLE
Create a wizard for Spring, logback, log4j2

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1167]
There's a [Sentry Wizard for Spring Boot](https://github.com/getsentry/sentry-docs/blob/master/src/wizard/java/spring-boot.md) but none for Spring, log4j2, logback.

It's basically a file sibling to the springboot linked above, with the Spring instructions.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-docs/issues/2897
