### ISSUE TITLE
Spring SentryTracingFilter does not provide a CustomSamplingContext

### ISSUE THREAD

**Issue by dparrella** [getsentry/sentry-java#1168]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? JDK11
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [x]  Spring -> If yes, which version? 5.3.2

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**4.0.0.alpha-2**

---
I have the following issue:

The call in SentryTracingFilter to `IHub.startTransaction(String name)` results in a `null` `CustomSamplingContext`. This does not match up with the documentation which suggests a `url` is available in the dictionary that could be used to filter out requests. This information is available in the filter via `HttpServletRequest`, so it should be provided.

Now we have to resort to filtering by transaction name, or by a very long list of filter URL mapping patterns. All we want to do is filter out health checks.

Documentation: https://docs.sentry.io/platforms/java/guides/spring/performance/sampling/#dynamic-sampling-function

**Steps to reproduce:**
- Run a Spring service in debug mode with a `SENTRY_DSN` configured
- Connect remote debugger and set a breakpoint in `SentryTracingFilter` and the configured `TracesSamplerCallback`.
- Issue any request using cURL

**Actual result:**
- `SentryTracingFilter` and `TracesSamplerCallback` breakpoints are reached but `CustomSamplingContext` is `null`.

**Expected result:**
- `CustomSamplingContext` should be populated with request information available in the filter, such as the URL

**Comment by marandaneto** [comment]
wondering if this would be fixed by the latest release alpha3, just an hour before.
or @maciejwalkowiak could confirm if it's indeed a bug.

thanks for reporting @dparrella

**Comment by dparrella** [comment]
Thanks for the quick fix!
