### ISSUE TITLE
Span 'op' is required, 'description' is optional/nullable

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1170]
The docs point out that, from the server perspective: 'op' is recommended, but not mandatory
'description' is optional

found by https://develop.sentry.dev/sdk/event-payloads/span/

But since the value of such spans are limited, our API can require `op`:
that means we could offer `startChild(op)` and `startChild(op, description) overloads but fields are nullable.

**Comment by maciejwalkowiak** [comment]
Addressed in https://github.com/getsentry/sentry-java/pull/1165/

**Comment by bruno-garcia** [comment]
What does this look like in the UI when they are not there? 
And what are some valid use cases where these values wouldn't be available?

Trying to make sure a trace will be valuable to the user given only the required data when creating a transaction/span.

**Comment by marandaneto** [comment]
> What does this look like in the UI when they are not there?
> And what are some valid use cases where these values wouldn't be available?

auto instrumented transactions should have default values, for sure.
it's not documented a min. payload for transactions/spans, so it's hard to say unless we try sending transactions with missing parts, but not sending an operation works.

> 
> Trying to make sure a trace will be valuable to the user given only the required data when creating a transaction/span.

I agree, but it's not consistent to have a method that starts a span without any params and no default values, and another one that takes non-nullable `description` and `op`.
so ideally, one could pass an `op` but not a `description` and vice versa.

**Comment by bruno-garcia** [comment]
We can make the API require the value even if the server accepts null. The product expects a value (and the user should know what/be able to name the operation they are tracking. I suggest we make both non-optional

**Comment by marandaneto** [comment]
@bruno-garcia what's about making at least `description` nullable? I could imagine many cases where people would need to write either "" or "just bla bla" because it's non-nullable.

**Comment by Tyrrrz** [comment]
![image](https://user-images.githubusercontent.com/1935960/104953263-bcc38f80-59ce-11eb-8460-057167144420.png)

**Comment by bruno-garcia** [comment]
Updated the description

**Comment by maciejwalkowiak** [comment]
Fixed in #1165
