### ISSUE TITLE
SentrySpanClientHttpRequestInterceptor should be in sentry-spring instead of sentry-spring-boot-starter

### ISSUE THREAD

**Issue by dparrella** [getsentry/sentry-java#1178]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**4.0.0.alpha-2**

---
I have the following issue:

`SentrySpanClientHttpRequestInterceptor` does not have any Spring Boot dependencies and should be in `sentry-spring` so that Spring apps not using Spring Boot can use it. That would seem to be consistent with `SentryTracingFilter`'s presence in `sentry-spring`.

**Comment by marandaneto** [comment]
@dparrella that indeed makes sense, probably `SentryLogbackInitializer` could be moved too if no transitive dependencies from spring boot are needed.

@maciejwalkowiak could you check both of them, please? thanks

@dparrella thanks once more for testing out our prereleases and helping us to fix and improve things :)

**Comment by maciejwalkowiak** [comment]
@dparrella thanks good point. I'll be working in upcoming days on making using Performance feature easier with Spring (non-boot).

@marandaneto `SentryLogbackInitializer` is not that useful outside of Spring Boot usage, because Spring (non-boot) users configure Logback in `logback.xml` and it's natural to declare `SentryAppender` there explicitly.

**Comment by dparrella** [comment]
> @dparrella thanks good point. I'll be working in upcoming days on making using Performance feature easier with Spring (non-boot).
> 
> @marandaneto `SentryLogbackInitializer` is not that useful outside of Spring Boot usage, because Spring (non-boot) users configure Logback in `logback.xml` and it's natural to declare `SentryAppender` there explicitly.

@maciejwalkowiak for what it's worth, we do actually have an `InitializerBean` that does pretty much the same thing. The reason is so we didn't have to change `logback.xml` on all of our microservices.
