### ISSUE TITLE
Add addToTransactions to Attachment

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-java#1185]
The SentryClient currently adds attachments to transactions
https://github.com/getsentry/sentry-java/blob/2f8360a001ffe1dff08a374b5ec91cecd34aed12/sentry/src/main/java/io/sentry/SentryClient.java#L359-L360
This can add a huge overhead when putting large attachments to the scope. In order to avoid this, we can add `addToTransactions` to attachments and set the default to `false`. The Python SDK already has [this flag](https://github.com/getsentry/sentry-python/blob/2af3274de22ee00b5254cc6700cc26ddc06dbb66/sentry_sdk/attachments.py#L18).

**Comment by bruno-garcia** [comment]
@philipphofmann we plan to release 4.0 next week, is this going to make into it?

**Comment by philipphofmann** [comment]
@bruno-garcia I can take care of it.

**Comment by bruno-garcia** [comment]
Thanks @philipphofmann !
