### ISSUE TITLE
Spring tags does not work

### ISSUE THREAD

**Issue by brandonguigo** [getsentry/sentry-java#1200]
Hello,

I have a springboot api on which i have tried to set tags. I've tried inside the application.properties, environment variable and nothing works.

Any idea on why ? 

I've used as dependency sentry and logback in my pom.xml and set the dsn and some config in application.properties : 

````

sentry.dsn=dsn
sentry.enable-external-configuration=true
sentry.attach-stacktrace=true
sentry.logging.minimum-event-level=warn
sentry.logging.minimum-breadcrumb-level=debug
sentry.send-default-pii=true
```

**Comment by bruno-garcia** [comment]
The docs on tags is here: https://docs.sentry.io/platforms/java/guides/spring-boot/enriching-events/tags/

Are you trying to add tags via the application.properties file too? There's a way to add some default tags, would be worth adding to the docs.

**Comment by brandonguigo** [comment]
I have tried to set then inside the application.properties and it didn't work.

I've also tried from the environment variable, same result. Same result from the code as mentioned in the documentations you posted (I've set the scope inside the main function of the application).

**Comment by bruno-garcia** [comment]
What version are you using of the Sentry SDK? What packages did you install?

**Comment by brandonguigo** [comment]
I've installed those packages : 

´´´

		<dependency>
			<groupId>io.sentry</groupId>
			<artifactId>sentry-spring-boot-starter</artifactId>
			<version>3.2.0</version>
		</dependency>

		<dependency>
			<groupId>io.sentry</groupId>
			<artifactId>sentry-logback</artifactId>
			<version>3.2.0</version>
		</dependency>
´´´

**Comment by maciejwalkowiak** [comment]
@brandonguigo tags have been added in version `4.0.0-alpha.2`. In case you prefer not to use alpha, 4.0 Final is going to be released in upcoming weeks.

To add tags in 4.0, add something like this in `application.properties`:

```properties
sentry.tags.tag1=value1
```

**Comment by brandonguigo** [comment]
Thanks, will use the latest alpha and update when 4.0 is out.

I've the same problem on the flutter client version 4.0.1, is it supported ?

**Comment by maciejwalkowiak** [comment]
Regarding Flutter, @marandaneto can help.

**Comment by marandaneto** [comment]
@brandonguigo only via the Scope (runtime) for now:

```
  Sentry.configureScope((scope) {
    scope
      ..setTag('build', '579')
  });
```

Please refer Dart/Flutter issues on https://github.com/getsentry/sentry-dart :)

**Comment by brandonguigo** [comment]
> @brandonguigo only via the Scope (runtime) for now:
> 
> ```
>   Sentry.configureScope((scope) {
>     scope
>       ..setTag('build', '579')
>   });
> ```
> 
> Please refer Dart/Flutter issues on https://github.com/getsentry/sentry-dart :)

Thanks, I think I have already tried that without success but I'm not sure. Will try it again and post an issue on the sentry-dart repo if necessary :)
