### ISSUE TITLE
Check if transaction is finished during captureTransaction call

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1208]
If the transaction is captured but not finished yet, what to do?
I'd say let's log it as INFO, finish and capture it.

Ideally `SentryClient.captureTransaction` does that as every call forwards to this method.

Context: https://github.com/getsentry/sentry-dotnet/pull/758#discussion_r564125517

**Comment by bruno-garcia** [comment]
We discussed this in more details on Discord.
Some thoughts:

> Please let's not finish the transaction, it'll make it impossible to debug if the transaction is being captured before it's finished by the code that's supposed to orchestrate it?


In .NET the approach was:

> right now it just sends transaction as is (unfinished) and logs a warning telling the user not to do that in the future
