### ISSUE TITLE
Sentry configuration for android build on Unreal engine

### ISSUE THREAD

**Issue by baloo887** [getsentry/sentry-java#1210]
Hi Sentry!
I've followed this [guide](https://docs.sentry.io/platforms/native/guides/ue4/) to link Unreal Engine crash reporter to Sentry and it works fine in play in editor or windows builds. Currently I'm working on a game for Android(developed with unreal), and I've followed the same guide. No matter what i do from the editor I'm getting the crash reports, but from the packaged version installed on a Device I'm not.

Is there some other configurations that i need to do to run it? Is crash reporting not supported for mobile games developed with unreal engine?

Thanks!

**Comment by marandaneto** [comment]
cc @bruno-garcia

**Comment by marandaneto** [comment]
@baloo887 you need to integrate our mobile SDKs yourself.

Android: https://docs.sentry.io/platforms/android/
iOS: https://docs.sentry.io/platforms/apple/guides/ios/

Not an Unreal expert so not entirely sure how to do it, but thinking that Unreal allows you to change the Gradle file for Android and integrate a CocoaPods for iOS, you should be fine following the docs.

**Comment by baloo887** [comment]
Ok thanks for the hints! Maybe they should add this information to the guide to let the community know which platform are supported on Unreal Engine.

**Comment by bruno-garcia** [comment]
Agreed. @baloo887 would you be keen to contribute with a PR to the docs?

**Comment by baloo887** [comment]
Sure, there is a template or some guidelines to contribute? Or I just need to add the missing docs and open the PR?

**Comment by marandaneto** [comment]
> Sure, there is a template or some guidelines to contribute? Or I just need to add the missing docs and open the PR?

good point, I've raised this issue https://github.com/getsentry/sentry-docs/issues/2981

the way how it is right now under the Native platform, adding mobile stuff there would be still meh.
let's see if folks agree to add a new platform, if so, I'd guide you on that.

The most important bits right now is if you could integrate the Android and iOS SDK seamlessly in your Unity mobile game without any special configuration, or if it requires something else, if it does, we could enrich the docs with this valuable information.

**Comment by bruno-garcia** [comment]
> Sure, there is a template or some guidelines to contribute? Or I just need to add the missing docs and open the PR?

We have docs on contributing to the docs here: https://docs.sentry.io/contributing/

There's a discussion on the issue @marandaneto opened linked above about a potential refactor but we can do that separately from your PR that documents adding it to Android. We'd appreciate the contribution.
