### ISSUE TITLE
SentryEvent has no editable contexts in 4.0.0

### ISSUE THREAD

**Issue by malenalbc** [getsentry/sentry-java#1218]
I'm in the process of updating from `3.2.0` to `4.0.0`. One of my product requirements is to clear any identifying user information before sending an event. I already asked [how to do this in a related question](https://github.com/getsentry/sentry-java/issues/746#issuecomment-694963813).

With the update seems like my approach:
```
     options.setBeforeSend { event, _ ->
                    event.contexts = event.contexts.apply {
                        val safeApp = this.app
                        safeApp.deviceAppHash = null
                        this.app = safeApp
                        val safeDevice = this.device
                        safeDevice.id = null
                        this.device = safeDevice
                    }
                    event.user = null
                    event
                }
   ```
Is not available anymore. `event.contexts = ` is marked as inmutable. 

What would be the alternative?
Thanks!

**Comment by marandaneto** [comment]
@malenalbc you've to use the setters and getters exposed by the `Contexts` class instead of `.apply`, so you can achieve pretty much the same.
