### ISSUE TITLE
4.0.0 Custom Instrumentation spans not working

### ISSUE THREAD

**Issue by sysmat** [getsentry/sentry-java#1223]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [x]  Other -> NetBaens 12?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [x]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**io.sentry:sentry:4.0.0**

---
I have the following issue:
- documentation is not up to date https://docs.sentry.io/platforms/java/performance/custom-instrumentation/
- when using 4.0.0-alpha.3 it was working
- I'm trying to work with spans

**Steps to reproduce:**
```java
public List<Org> getOrgsFamaly() {        
        ITransaction transaction = Sentry.startTransaction("getOrgsFamaly()");
        transaction.setOperation("famaly");

        List<Org> result = new ArrayList<>();
        result.add(build(4, 2));
        result.add(build(2, 3));

        transaction.finish();
        return result;
}

private Org build(int childrens, int leafs){
        ISpan span = Sentry.getSpan();
       // span is always null
        if(nonNull(span)){
            ISpan innerSpan = span.startChild("famaly", "childes_"+childrens+"::leafs_"+leafs);
            Org org = new Org(childrens, leafs);
            innerSpan.finish();
            return org;
        }

        return null;
    }

```
**Actual result:**
- span is always null

**Expected result:**
- To have spans inside one transaction

**Comment by marandaneto** [comment]
@sysmat indeed, if you are not using the `transaction` object to create child spans, you've to set the `transaction` to the current scope.

```
Sentry.configureScope(
          scope -> {
            scope.setTransaction(transaction);
          });
```

so after that, `Sentry.getSpan()` will return the given `transaction`

**Comment by sysmat** [comment]
Uf, this is ugly, was any particular reason to change this

**Comment by sysmat** [comment]
So for every transaction I start I have to do 
```java
Sentry.configureScope(
          scope -> {
            scope.setTransaction(transaction);
          });
```
- So If I have 10 transactions in service and do configureScope it will not be very clean code and spans will be clear

**Comment by sysmat** [comment]
If I do this spans not shown in sentry UI, only transaction and no spans in the transaction, this is not ok

**Comment by marandaneto** [comment]
@sysmat auto instrumentations like Spring boot does it automatically, so you don't have to.
Scopes are thread-local, so you are the best one to decide if it should go to the current's Scope or not, when using the manual instrumentation.

other option would passing your `transaction` object around and using it to `transaction.startChild(...)`

**Comment by marandaneto** [comment]
> So for every transaction I start I have to do
> 
> ```java
> Sentry.configureScope(
>           scope -> {
>             scope.setTransaction(transaction);
>           });
> ```
> 
> * So If I have 10 transactions in service and do configureScope it will not be very clean code and spans will be clear

well, not really, if you start 10 transactions in the same thread, you are gonna overwrite them, be aware of that.
maybe just use the `transaction` object if so?

**Comment by sysmat** [comment]
this is very disappointment , 4.0.0-alpha.3 was very useful, so if I pass the transaction to other functions, then we need to change the signature of those functions(not the way to go)

**Comment by marandaneto** [comment]
> this is very disappointment , 4.0.0-alpha.3 was very useful, so if I pass the transaction to other functions, then we need to change the signature of those functions(not the way to go)

it's a trade-off, if you have a single-threaded application or a single scope in the whole App's lifecycle (Mobile), you'd not want your transactions overwritten.

just create a method wrapper that does both calls at once, as simple as:

```
startMyTransaction(name, op) {
  ITransaction transaction = Sentry.startTransaction("getOrgsFamaly()");
  transaction.setOperation("famaly");
  Sentry.configureScope(
          scope -> {
            scope.setTransaction(transaction);
          });
}
```

and start using `startMyTransaction`

**Comment by sysmat** [comment]
It is not that, you want manually start a span in nested functions, like a distributed trace

```java
create(User user){
 // start transaction
 persistance(user); // want to have span
 notify(user);  // want to have span
}

persistance(User user){
  saveDB(user); // want to have span
  saveLdap(user); // want to have span
}
```

**Comment by marandaneto** [comment]
I don't see any problems when doing that, before & after the breaking change, what is blocking you to do that?

**Comment by sysmat** [comment]
in all functions, I need to pass ITransaction as parameter

**Comment by marandaneto** [comment]
nope, you don't, see this comment:

https://github.com/getsentry/sentry-java/issues/1223#issuecomment-772378575

**Comment by sysmat** [comment]
```
Sentry.configureScope(
          scope -> {
            scope.setTransaction(transaction);
          });
```

when doing this there are NO spans in transactions getOrgsFamaly, I write it before

**Comment by marandaneto** [comment]
@sysmat I am not sure if I follow the problem.

here it explains a bit more https://docs.sentry.io/platforms/java/performance/custom-instrumentation/#add-more-spans-to-the-transaction

maybe @maciejwalkowiak could help here, I guess I don't understand the problem.

**Comment by sysmat** [comment]
as my example, only this is working:

```java
public List<Org> getOrgsFamaly() {
        System.out.println("getOrgsFamaly");
        ITransaction transaction = Sentry.startTransaction("getOrgsFamaly()");
        transaction.setOperation("famaly");

        List<Org> result = new ArrayList<>();
        result.add(build(4, 2, transaction));
        result.add(build(2, 3, transaction));

        transaction.finish();
        return result;
    }

    private Org build(int childrens, int leafs, ITransaction trx){
        ISpan span = trx.startChild("famaly", "childes_"+childrens+"::leafs_"+leafs);
        Org org = new Org(childrens, leafs);
        span.finish();
        return org;
    }
```

**Comment by sysmat** [comment]
even in springboot there is no trace and spans.

```xml
<dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-spring-boot-starter</artifactId>
            <version>4.0.0</version>
        </dependency>
```

- application.properties
```
sentry.dsn = https://xxxx@sentry.my.si:9000/9
sentry.enable-tracing=true

```

**Comment by marandaneto** [comment]
> even in springboot there is no trace and spans.
> 
> ```
> <dependency>
>             <groupId>io.sentry</groupId>
>             <artifactId>sentry-spring-boot-starter</artifactId>
>             <version>4.0.0</version>
>         </dependency>
> ```
> 
> * application.properties
> 
> ```
> sentry.dsn = https://xxxx@sentry.my.si:9000/9
> sentry.enable-tracing=true
> ```

https://docs.sentry.io/platforms/java/guides/spring-boot/performance/#configure-the-sample-rate
you've to set a `traces-sample-rate`, please take some time to read the docs, we are happy to improve if it's not clear enough.

**Comment by marandaneto** [comment]
> as my example, only this is working:
> 
> ```java
> public List<Org> getOrgsFamaly() {
>         System.out.println("getOrgsFamaly");
>         ITransaction transaction = Sentry.startTransaction("getOrgsFamaly()");
>         transaction.setOperation("famaly");
> 
>         List<Org> result = new ArrayList<>();
>         result.add(build(4, 2, transaction));
>         result.add(build(2, 3, transaction));
> 
>         transaction.finish();
>         return result;
>     }
> 
>     private Org build(int childrens, int leafs, ITransaction trx){
>         ISpan span = trx.startChild("famaly", "childes_"+childrens+"::leafs_"+leafs);
>         Org org = new Org(childrens, leafs);
>         span.finish();
>         return org;
>     }
> ```

ok, that's correct, now please share a code snippet that does not work, and what exactly does not work.

**Comment by sysmat** [comment]
For java sentry tracing nothing work as I expected, so I'm going back to jaeger

**Comment by sysmat** [comment]
https://docs.sentry.io/platforms/java/guides/spring-boot/performance/#configure-the-sample-rate
> To get started automatically sending traces you must enable tracing in application.properties:

**Comment by marandaneto** [comment]
look at https://docs.sentry.io/platforms/java/guides/spring-boot/performance/included-instrumentation/
this is what it does automatically using the Spring boot instrumentation, everything else you should do yourself using `startTransaction` and `startChild`.

fwiw, I still fail to understand what's not working for you.

**Comment by maciejwalkowiak** [comment]
@sysmat just in case there was any misunderstanding here - you need to bind the transaction to the scope only once:

```java
public static List<Org> getOrgsFamaly() {
  System.out.println("getOrgsFamaly");
  ITransaction transaction = Sentry.startTransaction("getOrgsFamaly()");
  Sentry.configureScope(scope -> scope.setTransaction(transaction));
  transaction.setOperation("famaly");

  List<Org> result = new ArrayList<>();
  result.add(build(4, 2));
  result.add(build(2, 3));

  transaction.finish();
  return result;
}

private static Org build(int childrens, int leafs) {
  ISpan span = Sentry.getSpan().startChild("famaly", "childes_" + childrens + "::leafs_" + leafs);
  Org org = new Org(childrens, leafs);
  span.finish();
  return org;
}

static class Org {
  private int childrens;
  private int leafs;

  public Org(int childrens, int leafs) {
    this.childrens = childrens;
    this.leafs = leafs;
  }
}
```

With this piece of code you will get a result in the UI like:

![image](https://user-images.githubusercontent.com/1357927/106885036-5931a580-66e2-11eb-9c55-0d514486efdf.png)

**Comment by sysmat** [comment]
Thx, I'll try again

**Comment by maciejwalkowiak** [comment]
@sysmat do you have any update?

**Comment by sysmat** [comment]
@maciejwalkowiak sory not yet, I'll try it tomorow

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
