### ISSUE TITLE
Sentry scope is lost with async Spring controllers

### ISSUE THREAD

**Issue by dparrella** [getsentry/sentry-java#1226]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [x]  Spring -> 5.3.3

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**4.0.0**

---
I have the following issue:

We have noticed that issues generated from async requests our spring controllers lose context. This means we don't see things like the request information. I think it also breaks tracing.

I tried using a `TaskDecorator` (we have one for copying MDC context) but there is no way to pass in a "copy" of the current scope to the Runnable we return. I think ideally we'd have a `Sentry.setScope()` or a `merge()` method on `Scope`.

Example TaskDecorator:
```
public Runnable decorate(final Runnable runnable) {
    final AtomicReference<Scope> currentScope = new AtomicReference<>();
    Sentry.configureScope(scope -> currentScope.set(scope));
    return () -> {
        // Copy currentScope in here somehow
        runnable.run();
    };
}
```

Example Async controller method:
```
    @GetMapping("/v1/hello")
    @NoPreAuthorize
    public Callable<String> sayHello() {
        return () -> {
            log.error("Testing logback integration");
            return this.helloService.sayHello();
        };
    }
```

**Steps to reproduce:**
- See code samples.

**Actual result:**
- Issue is created without any request context.

**Expected result:**
- We should have something that allows us to "copy" over the current scope into another thread.

**Comment by marandaneto** [comment]
I guess this is a dup of #1107 could you confirm @dparrella ?

**Comment by dparrella** [comment]
It's similar but it's not exactly the same. That issue refers to a `StreamingResponseBody` while this is about Spring MVC's Async request handling. The ask is the same: we need a way to copy Scope from one thread to another. The current Scope object's methods do not support this.

**Comment by marandaneto** [comment]
agreed, ideally, we'd make something generic enough to tackle both problems.

**Comment by dparrella** [comment]
Any updates on this issue? This is a major problem for us.

**Comment by maciejwalkowiak** [comment]
For the coroutines implementation we added methods: `Sentry#getCurrentHub` an `Sentry#setCurrentHub` - both are marked as `internal` as they were initially not meant to be used by end users. I am not 100% sure but perhaps you can use them to solve this problem.

**Comment by bruno-garcia** [comment]
If there's no 'framework' API we can hook to do the calls to `getCurrentHub` and `setCurrentHub` ourselves I'm afraid there's just not way the SDK can propagate it automagically.

But as @maciejwalkowiak suggested you could use that API at the right places to propagate state. Would that work for you @dparrella?
