### ISSUE TITLE
Drop Bintray and JCenter

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1227]
Reason: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

There's a blocker (trove 4j only available thru JCenter):

> Execution failed for task ':sentry-android-core:extractDebugAnnotations'.
> > Could not resolve all files for configuration ':sentry-android-core:lintClassPath'.
>    > Could not find org.jetbrains.trove4j:trove4j:20160824.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
>        - https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
>      Required by:
>          project :sentry-android-core > com.android.tools.lint:lint-gradle:27.1.2 > com.android.tools:sdk-common:27.1.2
>          project :sentry-android-core > com.android.tools.lint:lint-gradle:27.1.2 > com.android.tools.external.com-intellij:intellij-core:27.1.2

Replace the Bintray plugin: https://dl.bintray.com/maranda/maven/ by https://docs.gradle.org/current/userguide/publishing_maven.html

requires `POM` rewriting, https://central.sonatype.org/pages/requirements.html#sufficient-metadata

requires `signing artifacts` https://docs.gradle.org/current/userguide/publishing_signing.html

This could be followed by https://github.com/getsentry/sentry-java/issues/1063

Fix https://github.com/getsentry/sentry-java/tree/main/scripts as bintray won't be used anymore

https://chris.banes.dev/publishing-to-maven-central/

**Comment by bruno-garcia** [comment]
jcenter is getting close to shutting down so we need to focus on this.

**Comment by bruno-garcia** [comment]
@maciejwalkowiak we need help on this actually. Basically using bintray as a proxy isn't going to be a possibility soon so we finally want to close in to uploading these packages only to maven central, via either a CLI or an API. We also need to sign all artifacts too.

**Comment by talios** [comment]
Might be useful to run the artifact/poms thru PomChecker to validate with oss.sonatype.org's requirements if going there:

  * https://andresalmiray.com/pomchecker-1-1-0-has-been-released

PomChecker has a maven and gradle plugin as well.

**Comment by marandaneto** [comment]
> UPDATE: To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021.
> 
> To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021.

**Comment by marandaneto** [comment]
looks like trove4j is now available thru the Spring plugins artifact https://mvnrepository.com/artifact/org.jetbrains.trove4j/trove4j/20160824 so we could fix this by adding the repo
