### ISSUE TITLE
Span.data is missing

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1233]
https://develop.sentry.dev/sdk/event-payloads/span/

We don't have a field to set arbitrary data associated with the Span, wondering if we decided to drop it or was an oversight.

Context: https://github.com/getsentry/sentry-cocoa/pull/932#discussion_r570927177

**Comment by marandaneto** [comment]
`Span#data` should exist but `Transaction#data` not, ideally `Transaction` is not even an exposed API, see https://github.com/getsentry/sentry-java/issues/1251

**Comment by marandaneto** [comment]
iOS has it https://github.com/getsentry/sentry-cocoa/blob/ee1dcf28e0e2b87c24ff6d8dae7813b719b3a8ad/Sources/Sentry/SentrySpan.m#L51-L56

**Comment by marandaneto** [comment]
fwiw, SDKs are setting the `span.data` as `span.data` since its part of the spec but if calling `transaction.data`, it goes to the `transaction.extra` field

**Comment by maciejwalkowiak** [comment]
This has been already implemented once, and the decision was to wait with it until we hide/drop `ITransaction` interface: https://github.com/getsentry/sentry-java/pull/1235

**Comment by marandaneto** [comment]
@maciejwalkowiak yep I recall that but since dropping `ITransaction` would still have the same problem, I'd just do the same as the other SDKs, `ITransaction.data` sets to the `transaction.extra`, I'm currently implementing the performance API for Dart and I've done the same.
