### ISSUE TITLE
Allow setting `proguard` via Options and/or external resources

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1236]
A Java App (non Android-probably Desktop) may be obfuscated using the Proguard tooling and right now there's no easy way to set up the `proguard` id if not using the `beforeSend` callback.
Ideally, this would be possible via SentryOptions or external resources.

See on Android: 
https://github.com/getsentry/sentry-java/blob/f6bca67bde00b6b036c41a15c5a4c2f150b34080/sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java#L239-L244

on Android the Sentry Gradle plugin uploads the mapping file via sentry-cli and injects its `id` in the assets folder of the App which is packaged in the final APK.
At runtime, the SDK reads this file and sets the `id` to the debug images.

**Comment by marandaneto** [comment]
every Java app would benefit from it, so removing the specific labels

**Comment by marandaneto** [comment]
a dumb example would be:

```
        sentryOptions.setBeforeSend { event, _ ->
            if (event.debugMeta == null) {
                event.debugMeta = DebugMeta()
            }
            if (event.debugMeta.images == null) {
                event.debugMeta.images = mutableListOf()
            }
            event.debugMeta.images.add(DebugImage().apply {
                type = "proguard"
                uuid = "your_generated_uuid" // using `sentry-cli upload-proguard`
            })

            event
        }
```

**Comment by 0xVesion** [comment]
I also came across this issue and would really like to help. If you could give me some advice on how I should/could implement the solution into sentry-java or sentry-spring, I would be happy to do so.

**Temporary Spring Boot Solution:**
For now you can drop this class into a spring-boot application. After doing so you can set `sentry.proguardUuids` in your application.properties file to pass the uuids to every event that gets sent to sentry.
```java
package XX;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import io.sentry.SentryEvent;
import io.sentry.SentryOptions.BeforeSendCallback;
import io.sentry.protocol.DebugImage;
import io.sentry.protocol.DebugMeta;

@Component
public class SentryProguardBeforeSendCallback implements BeforeSendCallback {
  private final String[] proguardUuids;

  public SentryProguardBeforeSendCallback(@Value("${sentry.proguardUuids}") String[] proguardUuids) {
    this.proguardUuids = proguardUuids;
  }

  @Override
  public SentryEvent execute(SentryEvent event, Object hint) {
    if (event.getDebugMeta() == null) {
      event.setDebugMeta(new DebugMeta());
    }

    if (event.getDebugMeta().getImages() == null) {
      event.getDebugMeta().setImages(new ArrayList<DebugImage>());
    }

    final var debugImages = Arrays
      .stream(proguardUuids)
      .map((uuid) -> {
        final var image = new DebugImage();

        image.setType("proguard");
        image.setUuid(uuid);

        return image;
      })
      .collect(Collectors.toList());
    
    event.getDebugMeta().getImages().addAll(debugImages);

    return event;
  }
}
```
