### ISSUE TITLE
Spans created by SentrySpanClientHttpRequestInterceptor only show request method

### ISSUE THREAD

**Issue by dparrella** [getsentry/sentry-java#1240]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? JDK 11
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [x]  Spring -> If yes, which version? 5.3.3

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**4.0.0**

---
I have the following issue:

Spans created by the `SentrySpringClientHttpRequestInterceptor` only show the request method (e.g. GET).  The request URL is `null`.

Example trace:
![image](https://user-images.githubusercontent.com/9330397/107471946-67376880-6bb1-11eb-9389-d56f9e53551a.png)

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Spans should show the request method AND request URL. Otherwise we don't know what request was being made.

**Comment by maciejwalkowiak** [comment]
Could you please show how you create the `RestTemplate` bean? The correct way to do it is:

```java
  @Bean
  RestTemplate restTemplate(IHub hub) {
    RestTemplate restTemplate = new RestTemplate();
    SentrySpanClientHttpRequestInterceptor sentryRestTemplateInterceptor =
        new SentrySpanClientHttpRequestInterceptor(hub);
    UriTemplateHandler templateHandler = restTemplate.getUriTemplateHandler();
    restTemplate.setUriTemplateHandler(
        sentryRestTemplateInterceptor.createUriTemplateHandler(templateHandler));
    restTemplate.setInterceptors(Collections.singletonList(sentryRestTemplateInterceptor));
    return restTemplate;
  }
```

I was able to reproduce your issue only if I don't set the `UriTemplateHandler` on the `RestTemplate`.

**Comment by dparrella** [comment]
That seems pretty backwards to me considering this is an interceptor. We
have a way to customize interceptors for most of our RestTemplates. If we
have to go and do this for every RestTemplate we create that's a
non-starter.

**Comment by maciejwalkowiak** [comment]
@dparrella understood, thanks for reporting, we will simplify the `RestTemplate` instrumentation.

**Comment by marandaneto** [comment]
@maciejwalkowiak let's fix the docs before closing this issue:

https://docs.sentry.io/platforms/java/guides/spring/performance/included-instrumentation/#resttemplate-instrumentation

**Comment by dparrella** [comment]
This is still not working after making the change as suggested.

**Comment by dparrella** [comment]
I see that this may no longer be relevant with #1246.

**Comment by marandaneto** [comment]
@dparrella we'll release a new version this week that includes this improvement.

**Comment by marandaneto** [comment]
@maciejwalkowiak could you prepare the docs change, so we merge it once is published? thanks
