### ISSUE TITLE
Add overloads for startTrasaction taking op and description

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1241]
The idea is to make it easier and less boilerplate, today we need to:

```
ITransaction transaction = Sentry.startTransaction("ANR Button");
transaction.setOperation("task");
transaction.setDescription("desc");
```

maybe:

`ITransaction transaction = Sentry.startTransaction("ANR Button", "task", "desc");`

or

`ITransaction transaction = Sentry.startTransaction("ANR Button", "task");`

the Span interface already has these overloads

cc @Tyrrrz @brustolin in case you don't have it too

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/blob/05a4c351ec92b6779df15360047e2437aab2a646/sentry/src/main/java/io/sentry/SpanContext.java#L29-L30

I believe `op` should be `@NotNull` too, as it is for `Span`

**Comment by maciejwalkowiak** [comment]
If it's non-null, when user calls `startTransaction(name)` what would be the value of `op`? Or do we want to force users to put both name and op?

**Comment by marandaneto** [comment]
> If it's non-null, when user calls `startTransaction(name)` what would be the value of `op`? Or do we want to force users to put both name and op?

that's the thing, it's mandatory for Span as we agreed before, I'm just assuming it's the same thing for Transaction, we can postpone this null change to the discussion tomorrow.

**Comment by Tyrrrz** [comment]
> If it's non-null, when user calls `startTransaction(name)` what would be the value of `op`? Or do we want to force users to put both name and op?

I'm concerned with this too. Currently we force both arguments on the user, but I see that other SDKs don't do that.

**Comment by marandaneto** [comment]
> > If it's non-null, when user calls `startTransaction(name)` what would be the value of `op`? Or do we want to force users to put both name and op?
> 
> I'm concerned with this too. Currently we force both arguments on the user, but I see that other SDKs don't do that.

what we are trying to achieve here is, while we do care for aligning the SDKs, we also want the best of the product and only giving a transaction name but nothing else it renders poorly on the UI.
Also see this https://develop.sentry.dev/sdk/event-payloads/transaction/
`op` is `Recommended`, `description` as agreed before, `Optional `

Aso here https://develop.sentry.dev/sdk/event-payloads/span/

> While Span attributes will be normalized on the server, a Span is most useful when it includes at least an op and description.

so I'd prefer having it mandatory if it gives a better product at the end, and we could align the other SDKs instead.
this is an open discussion still, let's talk tomorrow.

**Comment by marandaneto** [comment]
as discussed, ingestion accepts null `op` but we should make it mandatory on the SDK level, so we need to make it non-nullable for `op` and `description` is nullable

**Comment by marandaneto** [comment]
we need to fix our docs (Java/Android) code snippets and migration page before closing this issue
