### ISSUE TITLE
Transacrion/Span#finish should be thread-safe

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1253]
The method `finish` should be thread-safe as it could be called from multiple threads.

cc @Tyrrrz @brustolin

**Comment by bruno-garcia** [comment]
Finish is expected to be called once though

**Comment by marandaneto** [comment]
> Finish is expected to be called once though

same for SDK init., still, as discussed, it'd be ideally thread-safe, this gets more important if we decide to create the `transaction` when `finish` is called in the root Span.

**Comment by bruno-garcia** [comment]
`Transaction` doesn't need to be thread-safe.

Sentry.init is a static method. An atomic ref swap on `init` is a cheap enough way to make sure we don't end up with odd behavior if init is called while the SDK is already being used by some other thread. That doesn't mean we need to make all types thread-safe.

SentryEvent isnt' thread-safe and that's OK. Transaction is like SentryEvent.
Making `finish` "thread-safe" will have lots of side effects. Either we'll make the whole type thread-safe, or not bother at all with a one off method.

I'd be more worries about something like `setTag` if the transaction object is being shared by multiple-threads (say, bound to the scope). As we set tags in parallels would definitely crash the process.

We need to be clear on what is designed to be accessed concurrently, and what is not. And for an instance type, unless explicitly documented to be thread-safe, assume not to be. For static types it's fair to assume something is thread-safe though, ideally side-effect free even.

**Comment by marandaneto** [comment]
@bruno-garcia while I don't disagree with your whole explanation, I don't understand what/how made you change your mind from our last call, we've discussed that and we agreed that making `finish` thread-safe would make a lot of sense `if` we go ahead with refactoring things like #1251

also, a `transaction` would be only created when the root span was finished, etc...
so either I lost a lot of Context or we were talking about different things.

**Comment by marandaneto** [comment]
an example would be this: https://github.com/getsentry/sentry-cocoa/pull/950#discussion_r577295228

if we go ahead with something like that, IMO `finish` must be thread-safe, as `spans`, `tags`, etc... could be mutated in different threads
