### ISSUE TITLE
Discard unfinished Spans before sending them over to Sentry

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1262]
We need to discard Spans that are unfinished before sending them over to Sentry, the reason is https://github.com/getsentry/develop/issues/274

Relay drops the whole transaction if a single Span is unfinished.

@Tyrrrz @brustolin I believe this is also important for you both

**Comment by maciejwalkowiak** [comment]
When a parent span is not finished, but his child spans are finished, should the parent be removed with children or just a parent and children should stay?

**Comment by marandaneto** [comment]
> When a parent span is not finished, but his child spans are finished, should the parent be removed with children or just a parent and children should stay?

how is it shown in the UI in such cases? does the transaction still get ingested? does the parentless span gets ingested?
