### ISSUE TITLE
SentryTracingFilter should be a no-op when IHub.isEnabled() is false

### ISSUE THREAD

**Issue by dparrella** [getsentry/sentry-java#1264]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [x]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**4.1.0**

---
I have the following issue:

We have to add `SentryTracingFilter` to our services using a `WebApplicationInitializer`, at which point we have not initialized the environment. There's not a good way to determine at that point whether Sentry and/or tracing is enabled/disabled.

Because of #1263 we need to remove the filter but that is going to mean making a code change instead of being able to use configuration. 

**Steps to reproduce:**

In WebApplicationInitializer implementation:
```
    @Override
    public void onStartup(final ServletContext servletContext) throws ServletException {
        final DelegatingFilterProxy tracingFilterProxy = new DelegatingFilterProxy(SENTRY_TRACING_FILTER);

        final FilterRegistration.Dynamic filterRegistration = servletContext.addFilter(SENTRY_TRACING_FILTER,
                tracingFilterProxy);
        filterRegistration.addMappingForUrlPatterns(EnumSet.of(DispatcherType.ASYNC, DispatcherType.ERROR, DispatcherType.REQUEST),
                true,
                "/*");
    }
```

**Comment by marandaneto** [comment]
@dparrella thanks for reporting, we'll look into it.

would be possible to go around this by checking `Sentry.isEnabled()` before adding the `SentryTracingFilter`?

@maciejwalkowiak please mark it as a bug or enhancement, I'm doubtful about this.

**Comment by maciejwalkowiak** [comment]
Once #1263 is fixed the filter will not cause significant overhead - all calls will invoke `NoOpHub` - just resolving transaction name will run despite Sentry being disabled.

**Comment by dparrella** [comment]
No because it will always be false at this stage as the context is not
loaded yet.
