### ISSUE TITLE
SentryEvent.threads that are crashed=true should not contain a stack trace if exception already has stack traces

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1266]
Found out because of https://github.com/getsentry/sentry/pull/23890

Thread's stack traces are snapshots, gotten at an arbitrary time, so it'd be always better to keep only the exception's stack traces only if the flag crashed=true which means, the thread/s that captured that exception.
Wondering if inner exceptions could be built by multiple threads, so we'd need to check that too.

This would require changes on MainEventProcessor and SentryThreadFactory.

Docs:
https://develop.sentry.dev/sdk/event-payloads/threads/

**Comment by marandaneto** [comment]
@philipphofmann worth checking the Cocoa threads list too

**Comment by philipphofmann** [comment]
This isn't a problem right now, as we don't fill the threads when having an exception with a stacktrace. But we have plans to change this in https://github.com/getsentry/sentry-cocoa/issues/741. So I'm going to add it as a comment there.

**Comment by bruno-garcia** [comment]
We discussed this on a call and it's expected that Sentry will show the Exception stacktrace when that's available, even if all threads' stacktrace are also included in the event. For as long as the thread_id is present on both sides, Sentry should prioritize the stacktrace from the Exception interface instead. 

~Sounds like this could be a bug in Sentry's event detail page, thread selector.~

Sounds like this was fixed
