### ISSUE TITLE
Android Uncaught exception is not being logged in "Issue" but the crash is incremented in "Release"

### ISSUE THREAD

**Issue by cozytrony** [getsentry/sentry-java#1267]
Somehow android uncaught exception e.g. RuntimeException stacktrace is not capture by Sentry issue list, but the Crash # is showing correctly when viewing the “Release” summary.

When i tried to click in the “Crash” number in “Release” it shows empty in the “Issue” page

I tried to troubleshoot with charles, saw it sending out a “crash” log but no stacktrace of sort…

{“sid”:“d7fa0916-8bb9-40d7-a780-ac7372be2cb3”,“did”:“2b7315f2-13da-4eed-afb1-97bc4dd31af4”,“started”:“2021-02-18T07:09:58.127Z”,“status”:“crashed”,“seq”:1613632207149,“errors”:3,“duration”:9.022,“timestamp”:“2021-02-18T07:10:07.149Z”,“attrs”:{“release”:"{Masked out sensitive details}",“environment”:“xxx”}}

Crash count in "Release" page
![image](https://user-images.githubusercontent.com/13394311/108321900-c0317d00-71ff-11eb-8995-0a7de2f8276b.png)

These are my options settings
![image](https://user-images.githubusercontent.com/13394311/108322175-1dc5c980-7200-11eb-9368-806af2b897c8.png)

**Comment by marandaneto** [comment]
@cozytrony please use the PR template.

Also share a code snippet on how you are triggering this exception, so we can have a look at it, thanks

**Comment by cozytrony** [comment]
its ok i found the issue, sorry about it, its app logic problem.
