### ISSUE TITLE
Feature Request: Support so unextracted .so files in APKs

### ISSUE THREAD

**Issue by ansman** [getsentry/sentry-java#1280]
According to this page https://docs.sentry.io/platforms/android/usage/advanced-usage/#requirements you have to extract native libraries to be able to get deobfuscated stack reports.

While this is OK, it's not ideal since your app while use more space once installed. Most other native crash report tools does not have this limitation so it's not a technical requirement at least.

This issue can serve as a tracker for the progress from Sentry's side.

**Comment by marandaneto** [comment]
we'll probably get around this if https://github.com/getsentry/sentry-native/pull/480 goes well

**Comment by ansman** [comment]
Ah, nice timing! 🥇

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/pull/1431 does the job, will do a beta release today

**Comment by deathlyrage** [comment]
> #1431 does the job, will do a beta release today

Could we please get a beta release so we can test this?

**Comment by bruno-garcia** [comment]
There's a beta out: https://github.com/getsentry/sentry-java/releases/tag/5.0.0-beta.1
