### ISSUE TITLE
SENTRY_DSN environment variable not picked up automatically anymore

### ISSUE THREAD

**Issue by brunoballekens** [getsentry/sentry-java#1295]
_Platform:_
- [ x ]  Logback -> 1.2.3

The version of the SDK: 4.2.0

We set our DSN in the environment variable SENTRY_DSN

Our sentry appender was configured as
```
<appender name="Sentry" class="io.sentry.logback.SentryAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>ERROR</level>
        </filter>
</appender>
```
with sentry logback integration 4.1.0 this worked fine.

now (with https://github.com/getsentry/sentry-java/pull/1271) errors are not sent anymore.

**Comment by brunoballekens** [comment]
The documentation says (https://docs.sentry.io/platforms/java/guides/logback/#dsn-configuration) : 

> If the DSN is not present in the logback.xml configuration, Sentry will attempt to read it from the system property sentry.dsn, environment variable SENTRY_DSN or the dsn property in sentry.properties file. See the configuration page for more details on external configuration.

so I was expecting it to work

**Comment by francisdb** [comment]
workaround

```xml
    <appender name="Sentry" class="io.sentry.logback.SentryAppender">
        <options>
            <dsn>${SENTRY_DSN}</dsn>
        </options>
    </appender>
```

**Comment by marandaneto** [comment]
looks like a regression, will look into it, thanks cc @maciejwalkowiak
