### ISSUE TITLE
Not possible to read external files directory error

### ISSUE THREAD

**Issue by ArnyminerZ** [getsentry/sentry-java#1298]
_Platform:_
- [ ] Android -> `minSdkVersion:24`, `targetSdkVersion:30`, `buildToolsVersion:30.0.3`, `compileSdkVersion:30`, `ndkVersion:23.0.7123448`

_IDE:_
- [ ] Android Studio -> Arctic Fox | `2020.3.1 Canary 8`
![imagen](https://user-images.githubusercontent.com/12086466/109302805-12931f00-783a-11eb-9887-f25727b11b26.png)

_Build system:_
- [ ]  Gradle -> `version:6.8.2`

_Android Gradle Plugin:_
- [ ]  Yes -> `com.android.tools.build:gradle:7.0.0-alpha08`, `org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.30`

_Platform installed with:_
- [ ] Maven Central

The version of the SDK:
**4.2.0**

_Device:_
- [ ] Model Name: Google Pixel 3a
- [ ] Android Version: `11`
- [ ] Android Build: `RQ1A.210205.004`

---
I have the following issue:

When trying to capture user feedback, an error shows up.

**Steps to reproduce:**
```kotlin
val name = nameEditText.text.toString()
val email = emailEditText.text.toString()
val message = messageEditText.text.toString()

val sentryId = Sentry.captureMessage(message)
val feedback = UserFeedback(sentryId).apply {
    this.comments = if (contactCheckBox.isChecked)
        "Don't contact me"
        else "I want to be contacted"
    this.email = email
    this.name = name
}
Sentry.captureUserFeedback(feedback)
```

**Actual result:**
Error shows up:
```text
I/Sentry: Not possible to read external files directory
```

**Expected result:**
- User feedback should be shown in the Sentry panel.

**Additional information:**
I have requested the `Manifest.permission.WRITE_EXTERNAL_STORAGE` permission, as the error suggests, but doesn't make any difference.

**Comment by marandaneto** [comment]
@ArnyminerZ `Not possible to read external files directory` isn't an error, just an INFO, you don't need `WRITE_EXTERNAL_STORAGE` either.

**Comment by marandaneto** [comment]
@ArnyminerZ does the `message` appear on Sentry? how are you initing Sentry? if possible, copy and paste all the logs related to `Sentry`

**Comment by ArnyminerZ** [comment]
My initialization for Sentry is done in my main Activity:
```kotlin
Timber.v("Preparing App...")
Timber.v("Instantiating Sentry")
SentryAndroid.init(this) { options ->
    options.addIntegration(
        SentryTimberIntegration(SentryLevel.ERROR, SentryLevel.INFO)
    )
}
```
I'm using the timber integration btw.
Those are my logs:
```text
D/Sentry: io.sentry.auto-init read: true
I/Sentry: Retrieving auto-init from AndroidManifest.xml
I/Sentry: sentry-debug-meta.properties file was not found.
D/Sentry: SU isn't found on this Device.
V/MainActivity: Preparing App...
    Instantiating Sentry
I/Sentry: sentry-debug-meta.properties file was not found.
D/Sentry: SU isn't found on this Device.
```
And when trying to call the code for the feedback sending I get:
```text
I/Sentry: Not possible to read external files directory
```

**Comment by ArnyminerZ** [comment]
Ok, my bad, now it appears on Sentry, it took a while 🤦🏼
