### ISSUE TITLE
How to ignore some exception in sentry using logback.xml ?

### ISSUE THREAD

**Issue by kanai0618** [getsentry/sentry-java#1300]
Hi,
How can we ignore some exception which we dont want to send to sentry ? i am using logback.xml. Please suggest possible solution for that.

**Comment by marandaneto** [comment]
@kanai0618 please use the issue template.

@maciejwalkowiak is there a way to set the `beforeSend` callback using logback? https://docs.sentry.io/platforms/java/guides/logback/configuration/filtering/#using-hints

**Comment by maciejwalkowiak** [comment]
Config can be always overwritten by calling `Sentry#init` somewhere manually in the code, but in this case I believe it's more straightforward to use Logback filters http://logback.qos.ch/manual/filters.html

**Comment by kanai0618** [comment]
Okay using evaluator filter you meant 

```
<filter class="ch.qos.logback.core.filter.EvaluatorFilter">
    <evaluator>
        <expression>java.lang.RuntimeException.class.isInstance(throwable)</expression>
    </evaluator>
    <onMatch>DENY</onMatch>
</filter>
```
Let me try @maciejwalkowiak  Thanks.

**Comment by marandaneto** [comment]
@kanai0618 any feedback? thanks

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
