### ISSUE TITLE
Ignore Exception by type

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1306]
The SDK needs a first class API to filter out exceptions by their type.

The way to filter out today is through `beforeSend` such as:

```java
Sentry.init(options -> {
  options.setBeforeSend((event, _hint_) -> {
    return event.getThrowable() instanceof SQLException ? null : event;
  });
});
```

This is a feature in the [.NET SDK documented here for reference](https://docs.sentry.io/platforms/dotnet/ignoring-exceptions/).

i.e:
`SentrySdk.Init(o => o.AddExceptionFilterForType<OperationCanceledException>());`

In hindsight maybe not the best name `AddExceptionFilterForType`, perhaps `FilterException<TException>` would be a better candidate although keeping the name consistent is also a nice to have.

This issue was originally raised here: https://github.com/getsentry/sentry-java/issues/575

**Comment by marandaneto** [comment]
I've removed the tags cus we use them to filter issues specifically for that platform, if there's no Android or Java tag, then its for both

**Comment by bruno-garcia** [comment]
OK I won't add the tags in such case going forward. One benefit of adding is that you can search "all Android issues" by clicking the tag but I don't think I've ever done that :)

**Comment by maciejwalkowiak** [comment]
Both `AddExceptionFilterForType` and `FilterException` don't make it clear if its filter in or filter out. What about `SentryOptions#ignoredExceptions` with setter and getter (as required for Spring Boot `@ConfigurationProperties`) and a method `SentryOptions#ignoreException(Throwable)` for manual configuration?

**Comment by bruno-garcia** [comment]
> Both `AddExceptionFilterForType` and `FilterException` don't make it clear if its filter in or filter out. What about `SentryOptions#ignoredExceptions` with setter and getter (as required for Spring Boot `@ConfigurationProperties`) and a method `SentryOptions#ignoreException(Throwable)` for manual configuration?

The problem with that is that it's open for interpretation what that method will do. Does it ignore that instance? Does it ignore by message? message+type?

For that reason I went with ugly but descriptive `ForType`.

JS SDK has `ignoreErrors` which I'm not even sure what part of the error it matches against:
https://docs.sentry.io/platforms/javascript/configuration/filtering/#decluttering-sentry

**Comment by marandaneto** [comment]
I think @maciejwalkowiak point is about the `AddExceptionFilter` and not `ForType`
for me, it'd also make more sense `addIgnoreExceptionForType` for example
