### ISSUE TITLE
sentry-logback Unable to complete initialization

### ISSUE THREAD

**Issue by aBoyNicholas** [getsentry/sentry-java#1311]
When using sentry-logback in Spring boot, there is an obvious problem in the code. Where the if condition is obviously written backwards, resulting in a failure to call the Sentry.init() method if DNS is null.

The sentry-logback version is: 4.3.0

```java
if (options.getDsn() == null || !options.getDsn().endsWith("_IS_UNDEFINED")) {
        options.setEnableExternalConfiguration(true);
        options.setSentryClientName(BuildConfig.SENTRY_LOGBACK_SDK_NAME);
        options.setSdkVersion(createSdkVersion(options));
        Optional.ofNullable(transportFactory).ifPresent(options::setTransportFactory);
        try {
          Sentry.init(options);
        } catch (IllegalArgumentException e) {
          addWarn("Failed to init Sentry during appender initialization: " + e.getMessage());
        }
      } else {
        options
            .getLogger()
            .log(SentryLevel.WARNING, "DSN is null. SentryAppender is not being initialized");
      }
```

**Comment by aBoyNicholas** [comment]
I'm trying to modify it because of time issues

**Comment by maciejwalkowiak** [comment]
How do you exactly set up the appender? If DSN is not provided, auto-configuration does not kick in so the appender is not provided at all.

If `dsn` is null, it goes to `Sentry.init` and Sentry does not get initializer.

You're right that this condition can be improved, but I don't understand how does it break anything for you?

**Comment by aBoyNicholas** [comment]
Sorry, it's my mistake here, it has nothing to do with sentry not being able to report
