### ISSUE TITLE
TracesSampler should always apply parent sampling logic even when callback is used

### ISSUE THREAD

**Issue by dparrella** [getsentry/sentry-java#1315]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**4.3.0**

---
I have the following issue:

We were wondering why we weren't seeing consistent end-to-end traces where we expected them (API call results in call to other service with instrumented RestTemplate) and I figured out that it was because our sampler callback wasn't checking `TransactionContext.getParentSampled()`. This logic does get applied when a callback is *not* used. 

This may have a been a design choice but it was not obvious from the documentation that this would be a side effect of using a callback. For consistency in behavior it would be better to just always apply this logic ahead of the callback.

See: https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/TracesSampler.java#L26-L34

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by marandaneto** [comment]
@dparrella thanks for raising this.

Does this spec help? https://develop.sentry.dev/sdk/performance/#sampling

let me discuss this internally too, thanks

**Comment by dparrella** [comment]
Yes that makes it very clear!

**Comment by bruno-garcia** [comment]
This is indeed a bit of a gotcha and unless one reads the docs carefully it's understandable that it can be missed.

The reasoning to this is that we sampler callback is the only current API that allows a user to control sampling. If we took the decision of the incoming trace, that means that the server would be completely our of control of the number of transactions it captures leaving it completely to all of its callers.

I believe one obvious improvement we can do is to add this check in all of our code samples of the trace sampler callback, with a comment.

**Comment by maciejwalkowiak** [comment]
Docs issue has been addressed in https://github.com/getsentry/sentry-docs/issues/3230

In addition to that, the callback can return `null`, in such case there will be a check for the parent sampled and if this is not present for the traces sample rate. 

I believe this issue can be closed @bruno-garcia @marandaneto

**Comment by marandaneto** [comment]
closing it as we have the doc's issue already
