### ISSUE TITLE
RateLimiter logs the the number of dropped item for each dropped item in the SentryEnvelope

### ISSUE THREAD

**Issue by bobinx** [getsentry/sentry-java#1316]
https://github.com/getsentry/sentry-java/blob/bb19d62bda9b161e366dd792d1dd1122c28f87cd/sentry/src/main/java/io/sentry/transport/RateLimiter.java#L64-L76

Just saw that the count of dropped items in envelope is logged every time an item is added to the 'dropItems' list. 
Is this the expected behavior? Can the logging be moved outside the loop to reduce the amount of logs? 
I am new to sentry 🙂 Please excuse if I am missing something here.

**Comment by marandaneto** [comment]
@bobinx thanks for raising this, you're right, would you like contributing with a PR? :)

**Comment by bobinx** [comment]
@marandaneto I have created a PR with the changes.
Please have a look

**Comment by marandaneto** [comment]
thanks :)
