### ISSUE TITLE
[Android] Multidex proguard rules clarification

### ISSUE THREAD

**Issue by lwasyl** [getsentry/sentry-java#1321]
I'm opening this issue to ask about the following section of the Android SDK documentation: https://docs.sentry.io/platforms/android/usage/advanced-usage/#multi-dex-support

> If you're using Multi-Dex and our SDK, we would recommend updating your Multi-Dex configuration:

According to [Android documentation](https://developer.android.com/studio/build/multidex), technically for API21+ multidex is enabled by default:
> If your minSdkVersion is set to 21 or higher, multidex is enabled by default and you do not need the multidex library.

However, the app seems to start and work fine even without the multidex configuration. We're not using the `SentryInitProvider` though, opting for manual initialization instead.

Is there some specific scenario that the documented rules are covering?

**Comment by marandaneto** [comment]
@lwasyl thanks for asking.

the reasoning is https://developer.android.com/studio/build/multidex#keep
we could never reproduce such edge cases, looks like multidex is always clever enough to find out that Sentry is important and should be used in the main dex file as it registers a content provider and needs it.
This is just an edge case that we preferred to write down, but not necessary :)
