### ISSUE TITLE
Error reporting does not work if used with native image (graalvm) due to reflection usage in the lib

### ISSUE THREAD

**Issue by u6f6o** [getsentry/sentry-java#1323]
_Platform:_
- [x] Kotlin -> 1.4.20, graalvm 11
- [x] Logback -> 1.2.3 
- [x] Quarkus.io -> 1.12.1.Final

_Build system:_
- [x]  Gradle -> 6.3

The version of the SDK:
**4.1.0**

---
I have the following issue:

All of our services use sentry.io to report errors. This works nicely for our legacy spring services that do not use graalvm to build native container images. Our latest services use quarkus.io and graalvm though and the reporting does not work for them. Instead of reporting a meaningful error to sentry, the error lacks any content - no stack trace, error message, whatsoever: 

![image](https://user-images.githubusercontent.com/1176370/110980186-de554d80-8365-11eb-8a03-9787608400a0.png)

If I build any of these quarkus.io services with a traditional image (openjdk-11), the reporting works as expected. In native images it does not work though. 

I also created an error on the quarkus.io github: https://github.com/quarkusio/quarkus/issues/15623

This issue can be temporarily worked around by providing the sentry classes that need reflection in a reflection-config.json file, which is read by graalvm. IMO this should be fixed in the sentry library though. 

**Steps to reproduce:**
- Provoke an error that will be reported to sentry 
- Ensure that this application runs natively (graalvm)

**Actual result:**
- Unlabelled error with no content (message, stacktrace)

**Expected result:**
- Regular error with content

**Comment by marandaneto** [comment]
@u6f6o thanks for reporting this.

@maciejwalkowiak @bruno-garcia told me that you've tested this and it worked out, have you experienced such a problem?

could you provide an example of your `reflection-config.json` so if more people come to this problem, they could easily learn from it?

while I do agree that reflection should be avoided whenever possible, it's not a bug, this would require the removal of Gson and it'd require quite a bit of code changes, I'll talk about that internally, thanks.

**Comment by marandaneto** [comment]
not sure if I should consider tag as a `bug` or `enhancement` :D

**Comment by u6f6o** [comment]
@marandaneto : sure, here is the content of the reflection-config: 

```json
[
  {
    "name":"io.sentry.Breadcrumb",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.SentryBaseEvent",
    "allDeclaredFields":true
  },
  {
    "name":"io.sentry.SentryEvent",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.SentryValues",
    "allDeclaredFields":true
  },
  {
    "name":"io.sentry.protocol.DebugImage",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.DebugMeta",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.Mechanism",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.Message",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.Request",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SdkInfo",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SdkVersion",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryException",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryPackage",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryStackFrame",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryStackTrace",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryThread",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.User",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  }
]
```

No guarantees though, if all classes that use reflection are covered. :-)

**Comment by maciejwalkowiak** [comment]
@u6f6o thanks for reporting. We are working now on providing out-of-the box support for native images - you can follow progress here: https://github.com/getsentry/sentry-java/pull/1329
