### ISSUE TITLE
Spring Native Compatibility

### ISSUE THREAD

**Issue by AlexanderNZ** [getsentry/sentry-java#1324]
Hi there,

[Spring Native](https://spring.io/blog/2021/03/11/announcing-spring-native-beta) was recently released.

With `implementation 'org.springframework.experimental:spring-native:0.9.0'` and `compile 'io.sentry:sentry-spring-boot-starter:4.3.0'` present, building a native image per the spring native docs gives the below error:

`Caused by: java.lang.IllegalStateException: ERROR: in 'io.sentry.spring.tracing.SentryAdviceConfiguration' these methods are directly invoking methods marked @Bean: [sentryTransactionAdvisor, sentrySpanAdvisor] - due to the enforced proxyBeanMethods=false for components in a native-image, please consider refactoring to use instance injection. If you are confident this is not going to affect your application, you may turn this check off using -Dspring.native.verify=false.
`

In order to be compatible with Spring Native, it would be good if `io.sentry.spring.tracing.SentryAdviceConfiguration` was refactored per the guidance from Spring Native above - avoid directly using the Bean, and instead inject an instance. Naturally, it would be better to avoid disabling verification on builds.

I don't know if there are going to be any other issues to be compatible but it seems like a goo place to start. What do you think?

**Comment by marandaneto** [comment]
@AlexanderNZ thanks for reporting.

I believe the Sentry Spring and Spring boot starter modules are heavily based on annotation processing, this would require quite a few changes and not only `SentryAdviceConfiguration`, I guess.

@maciejwalkowiak is the expert here.

**Comment by maciejwalkowiak** [comment]
I am keeping this open as putting `@SentrySpan` and `@SentryTransaction` on classes or methods still does not work. Lets wait and see how the Spring Native project development goes, perhaps it will get solved there.

**Comment by marandaneto** [comment]
@maciejwalkowiak maybe rename the PRs title to be a bit more precise about the annotation processing on Spring native, as everything else `should` be working already.
another option would be closing it and creating a new one specifically for that, the reason is, if one reads the title but not the comments, they might think it does not work at all

**Comment by maciejwalkowiak** [comment]
Good idea!
