### ISSUE TITLE
Allow `tracesSampleRate` = 0.0

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1326]
We should allow `tracesSampleRate` to be set to 0.0, 0.0 means no transaction will be created by this SDK unless an incoming trace has been sampled.

cc @Tyrrrz this is relevant for you too, please have a look and create an issue if necessary.

**Comment by Tyrrrz** [comment]
In .NET you can already set `tracesSampleRate` to `0.0`, which would sample out all local transactions, except those started from trace header. Is that how it should be?
