### ISSUE TITLE
Sentry SDK and Google Designed for Families program

### ISSUE THREAD

**Issue by Matej-Hlatky** [getsentry/sentry-java#1340]
_Platform:_
- [X]  Android -> compileSdkVersion 30, targetSdkVersion 30

_IDE:_
- [X]  Android Studio -> 4.1.2

_Build system:_
- [X]  Gradle -> 6.4.1

_Android Gradle Plugin:_
- [X]  Yes -> `com.android.tools.build:gradle:3.5.0`

_Sentry Android Gradle Plugin:_
- [X]  No

_Proguard/R8:_
- [X]  Disabled

_Platform installed with:_
- [X] JCenter

The version of the SDK:
**3.2.0**

---
I have the following issue:

Hello,
we have Flutter app with single Dart codebase for iOS and Android app.
We are using [sentry_flutter](https://pub.dev/packages/sentry_flutter), which for Android includes the `io.sentry:sentry-android:3.2.0` as a dependency.

Our application is for kids, therefore it's placed in the:
- Apple App Store [Kids](https://developer.apple.com/app-store/kids-apps/) category
- Google Play - [Designed for Families](https://support.google.com/googleplay/android-developer/answer/9283445?hl=en&ref_topic=7071529)

With the recent Android app update, our APK got rejected due to this reason:
> *We have detected the use of Sentry SDK in APK Version: nnn, which is not allowed in apps that are in the Families program.* An ad SDK is not allowed if it has not self-certified its compliance with Play’s Families Ads Program (certified ad SDKs), or it is non-COPPA compliant per its own public documentation. Please note, the status of SDKs often changes and it is your responsibility to review documentation of all SDKs used in your app to ensure compliance with Families policies.

Please, have any of the Sentry Android authors or fellow developers came across this or similar issue?
We obviously don't want to remove Sentry SDK from our app, and also we want to stay in the "Designed for Families" program.

I've emailed Google support regarding this, tried to explain them that Sentry is not for serving any ads, but their answer is basically still the same text regarding ads SDK.

Kindly thanks for any help

**Comment by marandaneto** [comment]
@Matej-Hlatky unfortunately yes, thanks for reporting.

It's a dup of https://github.com/getsentry/sentry-dart/issues/371 and we are working to figure this out, I'll close this one.

**Comment by victoriaSh** [comment]
Looks like Google still rejects apps using Sentry ( sentry-react-native ).
I've sent my appeal for reinstatement on the 18 of March and have got this response today (24 March):
"We have detected the use of Sentry SDK, which is not allowed in apps that are in the Families program"

**Comment by marandaneto** [comment]
we have an update, Apps that have been rejected due to the Sentry SDK are now free to submit again, thanks for the patience.

We're going to work on [docs](https://github.com/getsentry/sentry-docs/issues/3344) to be more specific about PII on our SDKs
