### ISSUE TITLE
Sentry-android native libraries size

### ISSUE THREAD

**Issue by lwasyl** [getsentry/sentry-java#1341]
I noticed that `sentry-android` by default pulls in `sentry-android-ndk` dependency. The .so files inside are quite big at ~800KB x 4 targets. Overall after adding Sentry dependency, our apk size jumped from 4,7MB to 8MB. While this may be reduced for end-user by using AABs, it's still a big increase.

What's the purpose of `sentry-android-ndk` dependency? Can it be excluded, or can we just pull `sentry-android-core` instead of `sentry-android`? We don't use native libraries other than one small utility which doesn't cause issues for us so we don't seem to need native crashes reporting?

**Comment by marandaneto** [comment]
if you don't want Android NDK support (code written in C/C++), just use the `sentry-android-core` module, see -> https://docs.sentry.io/platforms/android/usage/advanced-usage/#requirements

**Comment by mateuszkwiecinski** [comment]
For future reference, proper link could be: https://docs.sentry.io/platforms/android/using-ndk/

>Using sentry-android-core, which doesn't contain the NDK and can be used separately, instead of sentry-android when adding the dependency. The minimal required API level for sentry-android-core is 14.

**Comment by marandaneto** [comment]
true, I'm sorry about that, we just reworked the docs and a few pages have moved to a different structure https://docs.sentry.io/platforms/android is still the root page though
