### ISSUE TITLE
Flag for turning off Sentry (for local developement) [feature request]

### ISSUE THREAD

**Issue by davidgodzsak** [getsentry/sentry-java#1342]
**What happens? (Pain)**
The java version of sentry throws an exception when it is not configured with a DSN. Now I need to add a conditional to check for the existence of configuration(I think it's also hard because it can be configured in multiple ways) or do a try-catch to handle its exception.

**Request**
It is nice that I can just call `Sentry.init()` and it works out of the box. However in local development I just want to turn it off temporarily, so I don't litter the logs on the sentry console and to be able to run it without configuring the DSN.

**Suggestion**
b. Sentry.init() could take a flag like `silent` that is false by default, which does an ERROR/WARN level log when no DSN case without throwing an exception
c. Sentry.init() could have a flag for `developmentMode` or `off` to just manually turn it on or off. When it's off we could also do a WARN level log about it to be safe.

**Comment by marandaneto** [comment]
You can use the `beforeSend` callback and return null depending on your `environment` or whatsoever.

https://docs.sentry.io/platforms/java/configuration/filtering/

or set an empty DSN `""` that it disables the SDK https://docs.sentry.io/platforms/java/configuration/options/#dsn
