### ISSUE TITLE
Max Spans per transaction

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1356]
Related to https://github.com/getsentry/develop/issues/298

Let's do 1000 as Python does by default.
Let's not add more if there's already 1000.
Trying to avoid some OOM.
Lets add an option for making it configurable called `maxSpans`, lets make it experimental https://github.com/JetBrains/java-annotations/blob/master/common/src/main/java/org/jetbrains/annotations/ApiStatus.java#L34-L54

@Tyrrrz and @brustolin please create an issue for iOS/.NET

**Comment by marandaneto** [comment]
I've noticed that a few SDKs actually offer an option for that and defaults to 1000 eg Python https://github.com/getsentry/sentry-python/blob/4c09f3203d6d19789c6fa729a2e46557ad4ea913/sentry_sdk/hub.py#L526-L529 so it might be good to do so, or we just add it later cc @bruno-garcia

**Comment by bruno-garcia** [comment]
Sounds good, lets add it

**Comment by bruno-garcia** [comment]
As [@Tyrrrz pointed out this is under `_experimental` on Python](https://github.com/getsentry/sentry-dotnet/pull/908#issuecomment-810486900). Cross posting here:

> Thanks for pointing out this is experimental in Python.
In hindsight we're be stuck with this setting even if we move towards collecting spans only where this would become a confusing configuration option.
I propose we just hide this for now. @Tyrrrz @marandaneto what do you think?

PR: https://github.com/getsentry/sentry-dotnet/pull/908

**Comment by marandaneto** [comment]
@Tyrrrz @bruno-garcia property is called `max_spans` on Python, it's under a `_experiments` object in the options, probably because that's the way they do experimental features, in our case, let's just call it `maxSpans` or `MaxSpans` depending on the language naming convention.
