### ISSUE TITLE
Unable to extend SentryHandler in JUL for configuration in Payara/Glassfish

### ISSUE THREAD

**Issue by davyrod** [getsentry/sentry-java#1360]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ X ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?  Azul JDK 1.8
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ X ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ X ] Maven Central
- [ ] Manually

The version of the SDK:
**4.x.x**

---
I have the following issue:

The description goes here
sentry-jul SentryHandler was added back in 4.x.x, however I am unable to extend the class in order to configure the sentry loghandler as a custom loghandler in an application deployed using Payara/Glassfish.  The reason seems to be related to the class being marked as 'final'.  Is there a reason for the 'final' identifier, and if not, can it be removed to allow extension?  If it is not possible, what is a good workaround for extending and deploying to an application in Payara/Glassfish?

**Steps to reproduce:**
- Try to extend SentryHandler class in custom handler

`import java.util.logging.Handler;
import io.sentry.jul.SentryHandler;

import javax.inject.Singleton;

import org.jvnet.hk2.annotations.ContractsProvided;
import org.jvnet.hk2.annotations.Service;

@Service
@Singleton
@ContractsProvided({PayaraSentryHandler.class, Handler.class})
public class PayaraSentryHandler extends SentryHandler {  
}`

**Actual result:**
- Compile error: The type PayaraSentryHandler cannot subclass the final class SentryHandler

**Expected result:**
- Successful extension of SentryHandler class

**Comment by davyrod** [comment]
In enterprise application servers like Glassfish/Payara (we use Payara), the log handlers are managed by the application server.  In order to add additional LogHandlers an HK2 component needs to be created so Payara can register the additional log handler service, in this case Sentry.  

We currently have a working sentry log handler on v1.7.30 by extending SentryHandler and are trying to upgrade to sentry-jul 4.3.0 with the above mentioned blocker.  Here is a reference to an example of how we currently use Sentry in a Payara server deployment: [Payara Sentry Log Handler Example v1.7.30](https://github.com/fturizo/PayaraSentryLogHandler/blob/master/src/main/java/fish/payara/sentry/PayaraSentryHandler.java)

**Comment by marandaneto** [comment]
@davyrod I see, that makes sense, thanks for explaining.

would you like to contribute with a PR? make it non-final but add the @Open annotation :)

**Comment by davyrod** [comment]
@marandaneto PR submitted and checks passed.
