### ISSUE TITLE
Android SentryOkHttpInterceptor provide mechanism to sanitize logged URL

### ISSUE THREAD

**Issue by alexmetcalfe** [getsentry/sentry-java#1362]
It seems that using the SentryOkHttpInterceptor out of the box all URLs would be logged and visible in Sentry. 

It would be preferable if we could provide a regex or some other mechanism to allow us to sanitize the URL so that we can obscure any customer sensitive information (user generated content)

**Comment by marandaneto** [comment]
@alexmetcalfe that's a fair use case, thanks for reporting, I'll discuss this internally.

**Comment by alexmetcalfe** [comment]
Hey @maciejwalkowiak I noticed that the SentryOkHttpInterceptor will still log the full URL as a breadcrumb. Would it be possible to allow this to be configurable as well?

**Comment by marandaneto** [comment]
@alexmetcalfe for that you can use the https://docs.sentry.io/platforms/android/configuration/options/#before-breadcrumb callback.
