### ISSUE TITLE
NPE while applying `Map` with `nullable` value to `User#setOthers`

### ISSUE THREAD

**Issue by wzieba** [getsentry/sentry-java#1366]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
Device `API`: 26
`compileSdkVersion`: 30
`targetSdkVersion`: 30
`buildTools`: applied by Android Gradle Plugin

_IDE:_
- [x]  Android Studio -> If yes, which version?
`4.2 beta 3` 

_Build system:_
- [x]  Gradle -> If yes, which version?
`6.7.1`

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
`4.2.0-beta03`

_Sentry Android Gradle Plugin:_
- [x]  No

_Proguard/R8:_
- [x]  Disabled

_Platform installed with:_
- [x] Maven Central

The version of the SDK:
**4.3.0**

---
I have the following issue:

Setting `map` with `Nullable` value results with `NullPointerException`. The reason is that SDK uses `ConcurentHashMap` which does not accept nullable values ([ConcurentHashMap source](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ConcurrentHashMap.java#l1011))

**Steps to reproduce:**
Run
```
User().apply {
    others = mapOf("test" to null)
}
```

**Actual result:**
- `ConcurrentHashMap.putVal` throws `NullPointerException`

**Expected result:**
- `User#setOthers` should not accept map with nullable values

---

I know you work on better null-safety (https://github.com/getsentry/sentry-java/issues/1357#issuecomment-809265747) but would you consider accepting a small PR with just a signature update, like this: https://github.com/wzieba/sentry-java/commit/84eb804a8d4967e3cef9fb8e45bbbf3344897edb?

**Comment by marandaneto** [comment]
@wzieba thanks for reporting.

yes, adding such annotations is actually one of the things we'd do, adding to the key makes sense too IMO.
btw TIL you can add such annotations inside of the diamond operator.

even better if we search for all the usage of `ConcurrentHashMap` within this project and when such method exists, add the annotations.
