### ISSUE TITLE
`close` SDK and its integrations when `init` is called twice

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1370]
Currently, we log it https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Sentry.java#L154-L160
but we don't `close` the previous `init`, so integrations run twice and this leads to an infinite loop in the signal handlers

**Comment by maciejwalkowiak** [comment]
When `init` is called the second time, a hub taken from the current thread gets closed (https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Sentry.java#L181) - so all integrations that have been previously registered get closed before the next init finishes. Maybe a failing test would shine more light on this issue? @marandaneto

**Comment by marandaneto** [comment]
@maciejwalkowiak indeed, iirc, this has been solved by https://github.com/getsentry/sentry-java/pull/1358
because not all the integrations were closed, but now they are.
