### ISSUE TITLE
Device's memory for Android NDK hard crashes is added on restart

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1395]
Device's memory for Android NDK crashes is added on the restart, so these values are not accurate.

Ideally, `sentry-native` would add this to the event before writing the event to the disk, so on restart, the Android SDK enriches only with static data.

**Comment by marandaneto** [comment]
on the Android bits, we can read it from https://developer.android.com/reference/android/app/ActivityManager.MemoryInfo but if reading it directly on the NDK side, we'd need to figure this out and if it's actually safe to read such values when the App. is crashing because of OOM.

**Comment by bruno-garcia** [comment]
Can't make JNI calls on the signal handler, so we should just make sure we don't add this on events read off of the disk after restart

**Comment by marandaneto** [comment]
@bruno-garcia that's the 1st step, it'd be cool if the signal handler would be able to read free/used memory on the signal handler, so on the restart, we'd just merge the device info with the static data.
