### ISSUE TITLE
Debounce device.event breadcrumbs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1398]
Sometimes the OS could trigger a few breadcrumbs within a few seconds, it'd be nice to debounce them if they have the same value, which they do sometimes.

e.g. TYPE_AMBIENT_TEMPERATURE

**Comment by philipphofmann** [comment]
Debounce should only apply to breadcrumbs stemming from OS events, as we don't want to drop manually captured breadcrumbs.

**Comment by smeubank** [comment]
closing, this seems to be low enough prio and stale for quite some time
