### ISSUE TITLE
Integrate diffuse for Android

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1411]
https://github.com/JakeWharton/diffuse

Similar to `binary-compatibility-validator` but for Android.

> Diffuse is a tool for diffing APKs, AABs, AARs, and JARs in a way that aims to provide both a high-level view of what changes along with important detailed output.

**Comment by philipphofmann** [comment]
@marandaneto, can you please add more context? I'm not sure what the goal of this issue is.

**Comment by marandaneto** [comment]
> @marandaneto, can you please add more context? I'm not sure what the goal of this issue is.

done, the repo itself has good examples.
