### ISSUE TITLE
Sync attachments from Android -> Native

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1413]
The attachments live on the scope. Sync them to sentry-native.
sentry-native needs to be able to add and remove attachments on the fly.

**Comment by visla-yewang** [comment]
is there issue fixed？ we are meeting exactly the same issue, can anyone give some update on how to solve the issue?

**Comment by stefanosiano** [comment]
Closing as a dup of https://github.com/getsentry/sentry-java/issues/2056
