### ISSUE TITLE
Add android packages to native crashes

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1415]
every event contains the involved packages (eg android-core, android, android-ndk) etc but in case of a hard crash in the native layer, only sentry native package is available, ideally, sentry-native takes all packages on sdk init.

**Comment by romtsn** [comment]
The main goal is to understand what was installed by looking at the event metadata, so we could debug issues easier.

**Comment by markushi** [comment]
@marandaneto could you explain the use-case a bit more? Right now we don't even seem to surface the packages on sentry web.
