### ISSUE TITLE
outbox folder max items

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1417]
Files written to the "out box" by RN and native need to respect "maxItems" options and rotate files when full (deleting the oldest first)

RN, Flutter and Sentry-native write directly to the outbox folder and they don't respect the `maxItems`

**Comment by romtsn** [comment]
The change has to be on the other SDKs likely (writer's site)

**Comment by markushi** [comment]
This should already work: https://github.com/getsentry/sentry-dart/blob/fa16e53b4bb6d070a637610acb48612b82700d3c/flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt#LL137-L137C77

**Comment by stefanosiano** [comment]
This shouldn't be relevant for hybrid SDKs anymore, and it shouldn't be a problem for native.
Closing it
