### ISSUE TITLE
Merge user IP with {{auto}} if IP is null and sendDefaultPii is enabled, for events and transactions

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1427]
https://github.com/getsentry/sentry-java/pull/1424#discussion_r615780432

**Comment by marandaneto** [comment]
MainEventProcessor#mergeUser does it, we just need to extract this and call from multiple places when setting the user

**Comment by maciejwalkowiak** [comment]
Isn't this already implemented? I don't see what's missing.

**Comment by marandaneto** [comment]
I think that this has been automatically solved when executing event processors for transactions too, so if you don't see this missing anywhere, just close it
