### ISSUE TITLE
Add new Contexts fields to spec and UI

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1435]
Add missing `Contexts` (device, app, etc) to [sdk spec](https://develop.sentry.dev/sdk/event-payloads/contexts/) and Sentry UI:

Example:
![image](https://user-images.githubusercontent.com/1633368/115609856-11b8bf80-a2b6-11eb-996e-7267dc761715.png)

The spec should specify the unit (Mb, Celcius).
Sentry's UI can display the unit in such cases, for example 

![image](https://user-images.githubusercontent.com/1633368/115609938-2d23ca80-a2b6-11eb-99ea-405f16ff88e8.png)

![image](https://user-images.githubusercontent.com/1633368/115609966-36149c00-a2b6-11eb-8bdd-1a8d7c9453a5.png)

**Comment by bruno-garcia** [comment]
Relates to: https://github.com/getsentry/sentry-unity/issues/121

**Comment by marandaneto** [comment]
maybe move to https://github.com/getsentry/develop ?
we've had this issue before and we decided not to do it because the protocol already allows arbitrary values, I still agree that makes sense adding it though

**Comment by bruno-garcia** [comment]
I'm afraid if it going to that repo to die. Since we're adding these new fields here (and on unity) we could drive the initiative from here. We can move it there, perhaps create a single issue for all the known fields we've come up lately on the Mobile team's SDKs. Maybe best to discuss on a grooming call.

Adding to the spec has the advantage of becoming a guideline for other SDKs and being the source of truth when it comes to adding proper support in the UI. Specifically a label (so a nice name shows up as opposed to `just_the_key` and also allowing for things like the unit being known, as we did for bytes values, and timestamps (`X minutes before this event`). So we can show `Temperature: 45c` and even a future feature that add a conversion to Fahrenheit. Or reads which metrics you prefer from your users settings and adjusts such things across Sentry.

Now I'm really ahead of myself but we could start by adding the field to the protocol :)

**Comment by marandaneto** [comment]
removed the Android tag though, a Desktop App. could use the same fields

**Comment by bruno-garcia** [comment]
Mostly done through: https://github.com/getsentry/sentry/pull/27230

**Comment by marandaneto** [comment]
there's also this page https://docs.sentry.io/platforms/flutter/enriching-events/context/
ideally we'd have such page for all SDKs, all the context should be documented under this page and develop docs
