### ISSUE TITLE
pin non-verified GH actions

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1442]
Eg https://github.com/getsentry/sentry-java/pull/1440/files#r619501561

worth checking on other non-verified actions too

**Comment by bruno-garcia** [comment]
Checking if it's verified:
![image](https://user-images.githubusercontent.com/1633368/121377275-345b7200-c910-11eb-9d99-7ded82b5a9bd.png)

**Comment by adinauer** [comment]
This might help: https://github.com/sethvargo/ratchet
