### ISSUE TITLE
Remove deprecated methods from tests

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1445]
eg sentry-java/sentry/src/test/java/io/sentry/GsonSerializerTest.kt: (410, 23): 'constructor SdkVersion()' is deprecated. Deprecated in Java

**Comment by bruno-garcia** [comment]
Alternatively, if possible we could suppress the warning and delete the test only when the code gets deleted

**Comment by marandaneto** [comment]
as we do a major bump, we could also delete `@Deprecated` as `SentryProperties.isEnableTracing`
@maciejwalkowiak wdyt?

**Comment by maciejwalkowiak** [comment]
👍

**Comment by marandaneto** [comment]
Addressed on https://github.com/getsentry/sentry-java/pull/1875
