### ISSUE TITLE
Codecov stats are missing for Android modules

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1454]
https://app.codecov.io/gh/getsentry/sentry-java

**Comment by markushi** [comment]
@marandaneto Let's re-priortize this in the Android sync and decouple it from the milestone.

**Comment by markushi** [comment]
To clarify: this is about the android modules (like `sentry-android`, `sentry-android-okhttp`) not being part of the code stats. [This guide should get us started](https://about.codecov.io/blog/code-coverage-for-android-development-using-kotlin-jacoco-github-actions-and-codecov/).

**Comment by markushi** [comment]
Same applies for our SAGP repo: https://github.com/getsentry/sentry-android-gradle-plugin/issues/87

**Comment by romtsn** [comment]
Closed by #2868
