### ISSUE TITLE
Supporting Graceful Shutdown

### ISSUE THREAD

**Issue by sebastianfuss** [getsentry/sentry-java#1458]
Sentry registers automatically during initialization a JVM Shutdown Hook to close the hub after shutdown has been **initiated**. Unfortunately the sentry context is closed to early and following events are discarded.

Spring introduced Graceful Shutdown Mechanism with 2.3.x. It would be great if the sentry context shutdown could be done as last as possible. The benefit would be that sentry events during the graceful shutdown phase could be send to the sentry server.

A quick solution could be a simple new flag `registerShutdownHook` in `SentryOptions` to disable the current registration of the shutdown hook via `ShutdownHookIntegration`. 
Afterwards it would be possible to implement a custom shutdown hook via Spring `SmartLifecycle`.

**Comment by marandaneto** [comment]
@sebastianfuss thanks for reporting, makes sense.

a 2nd option, for now, would be removing the `ShutdownHookIntegration` from `SentryOptions.getIntegrations()` during SDK init.

**Comment by bruno-garcia** [comment]
> Unfortunately the sentry context is closed to early and following events are discarded.

This happened also on [Sentry for ASP.NET Core (related issue)](https://github.com/getsentry/sentry-dotnet/issues/517). We also took this learning into the Unity SDK so when 'App Shutdown' happens there, we'll just flush events but not close the SDK.

The reasoning is that the goal of this integration is to account for a user not closing the SDK before exiting the program. But the reason we close the SDK is really only to flush events that are queued up. The operating system will close down the TCP connection between the SDK's HTTP client and Sentry's server. 

So unless there's really something we need to do through `Close` that must run before the app exists, I believe we should replace such logic from integrations to simply flush the queue.

**Comment by sebastianfuss** [comment]
Hi @marandaneto 
thanks for suggesting the 2nd option. that works :) 
But a simple flag to disable the shutdown hook registration in the `SentryOptions ` would be great.  I had to manual init the Sentry Context before logback context was initialised.

BTW: There is no need of custom Spring `SmartLifecycle`. If the `Hub` is managed by spring, it automatically calls the `close` method if the context is destroyed. This happens after the grace period is over.

```
    @Bean
    fun sentryHub(
        gitProperties: ObjectProvider<GitProperties>,
        environment: Environment
    ): IHub {
    // ...
    }
```
--
@bruno-garcia would be great if the flush is as late as possible.
