### ISSUE TITLE
JBOSS (7.2) and Sentry/java/log4j (1.7.30) integration not working

### ISSUE THREAD

**Issue by klemenag** [getsentry/sentry-java#1471]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [X]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- - openjdk 11.0.10
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Log4j -> If yes, which version?
-- 1.7.30
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [X]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**3.x.x**
**1.7.30**

---
I have the following issue:
I've followed this 'guide' ( https://github.com/getsentry/sentry-java/issues/570 ) trying to integrate JBOSS 7.2 with Sentry-log4j 1.7.30, but I get an error... Triggering sentry-cli from the same host works (so it's not a network problem)

**Steps to reproduce:**
-  Follow this 'guide' ( https://github.com/getsentry/sentry-java/issues/570 ) in first post

**Actual result:**
- 2021-05-12 11:06:28,572 WARN [io.sentry.config.provider.JndiConfigurationProvider] (MSC service thread 1-4) Odd RuntimeException while testing for JNDI: java.lang.IllegalArgumentException: WFLYNAM0041: NamingStore is null
- no traffic whatsoever is sent to sentry server

**Expected result:**
- Error is seen in entry.

**Comment by maciejwalkowiak** [comment]
We don't have at the moment a guide to use Sentry with JBoss. There is a module for Keycloak that uses newer version of the SDK - perhaps you can take a look at sources and prepare a JBoss module yourself using the latest SDK: https://github.com/flip-corp/keycloak-sentry

**Comment by klemenag** [comment]
Hi,

I'm trying to implement Sentry as a root logger on JBOSS 7.2.9 (not logging per app)

Is it ok / enough if I :

- add {sentry,sentry-jul)-4.3.0.jar along with appropriate module.xml (do the need any dependency)?
- custom-handler ( module io.setnry, class io.sentry.jul.SentryHandler )
- add this custom handler to root

Is this enough?

It's not really clear to me, what to do with gson and jboss-jsse-api packages - are they needed?

**Comment by maciejwalkowiak** [comment]
@klemenag Sentry depends on Gson, so however you configure it, Sentry must be able to use Gson classes. Regarding `jboss-jsse-api ` - I don't know. We do not have at the moment a guideline on integrating Sentry with JBoss.

**Comment by marandaneto** [comment]
I've creates this issue https://github.com/getsentry/sentry-java/issues/1498 please upvote it, if we see more demand, we can prioritize it, thanks

**Comment by maciejwalkowiak** [comment]
@klemenag take a look at https://gist.github.com/maciejwalkowiak/02fa1eb0089ebc6e0a4687458a204779 (in progress)
