### ISSUE TITLE
Don't include thread information for FileObserver captures

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1473]
Similar to https://github.com/getsentry/sentry-dart/blob/main/flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt#L207-L216

If there's a captured message from the JS layer, the Android SDK sets the current thread if there's not an exception, but because of the file transport, the thread is always the file observer and this is just noisy/not useful.

**Comment by bruno-garcia** [comment]
We agreed to simply use hints to avoid attaching thread information from FileObserver captures (sentry-native, sentry-react-native, sentry-flutter events)
