### ISSUE TITLE
Simplify DateUtils with ISO8601Utils

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1489]
We use GSON for JSON and GSON ships https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/bind/util/ISO8601Utils.java

which is faster and GC friendlier

**Comment by bruno-garcia** [comment]
Consider the need for high precision, see: https://github.com/getsentry/sentry-java/issues/1689

**Comment by marandaneto** [comment]
ideally yes if it requires breaking changes

**Comment by marandaneto** [comment]
@denrase this one is still pending right, but its not a breaking change
