### ISSUE TITLE
Invalid timestamp

### ISSUE THREAD

**Issue by tuesda** [getsentry/sentry-java#1494]
_Platform:_
Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
  - compileSdkVersion 29
  - targetSdkVersion 29
  - Build tools "29.0.3"

_IDE:_
- [x]  Android Studio -> If yes, which version?
  - 4.2.1

_Build system:_
- [x]  Gradle -> If yes, which version?
  - 6.8.3

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
  - 4.2.1

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
  - 4.3.0

_Proguard/R8:_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**4.3.0**

---
I have the following issue:

The description goes here ...

**Steps to reproduce:**
- Nothing special

**Actual result:**
  ![image](https://user-images.githubusercontent.com/3896690/119773642-83a6a900-bef3-11eb-881e-41a917be1aa1.png)Result

**Expected result:**
  No error

**Comment by marandaneto** [comment]
@tuesda isn't because the device was with the wrong date and time or timezone?

**Comment by tuesda** [comment]
This issue is on customer's device, so I will observe for a while, and close this issue for now.
