### ISSUE TITLE
unable to access 'https://chromium.googlesource.com/linux-syscall-support/': Failed to connect to chromium.googlesource.com port 443”

### ISSUE THREAD

**Issue by guozhaocai90** [getsentry/sentry-java#1507]
_Platform:_
- [ ]  Android -> API 30
- [ ]  Java -> jdk1.8?

_IDE:_
- [ ]   Android Studio -> 4.2.x

_Build system:_
- [ ] Gradle -> 6.7.1

_Android Gradle Plugin:_
- [ ]   4.2.1

_Sentry Android Gradle Plugin:_
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ]JCenter

The version of the SDK:
4.3.0
5.0.0-Beta1
5.0.0-Beta2

---
I have the following issue:

The description goes here ...
the error log: 
”unable to access 'https://chromium.googlesource.com/linux-syscall-support/': Failed to connect to chromium.googlesource.com port 443”
But Browsers in my computer can access this address，
when i get the file "linux_syscall_support.h" form somewhere else,and put it to the external/third_party/lss directory, run application reported "try-native/external/third_party/lss' already exists and is not an empty directory"

How can I solve this problem, please

**Comment by marandaneto** [comment]
@guozhaocai90  not sure I follow, how do you get this error, what are you trying to do? it does not seem to be any related to Sentry
Elaborate, please

**Comment by bruno-garcia** [comment]
This is related to a change in the remote URL from a submodule dependency of sentry-native.
@Swatinem has details

**Comment by guozhaocai90** [comment]
> This is related to a change in the remote URL from a submodule dependency of sentry-native.
> @Swatinem has details
thank you for your answer:
you mean the remote URL  from a submodule dependency of sentry-native has be changed ? i  have download Swatinem  sentry-contrib-native-master code ,But can't find the right URL, and i replace the module sentyr-native code by sentry-contrib-native-master's, i run the sentry-java application, it reported  the error all the same.

**Comment by marandaneto** [comment]
@guozhaocai90 what was the solution to keep it registered?
