### ISSUE TITLE
Undocumented breaking change to EventProcessor in Sentry 5.0

### ISSUE THREAD

**Issue by angusholder** [getsentry/sentry-java#1510]
As of 5.0, the EventProcessor interface has two methods, so it can no longer be created using a lambda, like

    opts.addEventProcessor { event: SentryEvent, hint ->
        event.setTag("foo", "bar")
        event
    }

Easy enough to fix, but probably worth mentioning in the release notes and migration guide?

**Comment by talios** [comment]
I noticed `io.sentry.exception.InvalidDsnException` also no longer exists, was easy enough to work around in our bootstrap ( just remove the throws ), but also not documented anywhere I saw.

**Comment by marandaneto** [comment]
indeed, thanks for raising it, those breaking changes were hidden in the changelog and I could not spot them when writing the breaking changes.
`EventProcessor` has a new default method, so it should not break the implementation of the interface but if using the trailing lambda, it'd be a problem.
