### ISSUE TITLE
Source and Javadoc artifact are mixed up since SDK 5.0.0

### ISSUE THREAD

**Issue by rkraneis** [getsentry/sentry-java#1514]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [X]  Java -> 1.8
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [X]  Log4j2 -> 2.13
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [X]  Other -> Apache NetBeans

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [X]  Maven -> 3.6.3
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Proguard/R8:_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [X] Maven Central
- [ ] Manually

The version of the SDK:
**5.0.0**

---
I have the following issue:

Javadoc and sources are not displayed in my IDE. Investigation shows, that the `-sources.jar` actually contains the javadoc and vice versa:

```shell
jar tf sentry-5.0.0-javadoc.jar | head -n 20
META-INF/
META-INF/MANIFEST.MF
META-INF/native-image/
META-INF/native-image/io.sentry/
META-INF/native-image/io.sentry/sentry/
META-INF/native-image/io.sentry/sentry/native-image.properties
META-INF/native-image/io.sentry/sentry/reflect-config.json
io/
io/sentry/
io/sentry/CustomSamplingContext.java
io/sentry/TracesSampler.java
io/sentry/Dsn.java
io/sentry/DiagnosticLogger.java
io/sentry/MainEventProcessor.java
io/sentry/HubAdapter.java
io/sentry/IScopeObserver.java
io/sentry/EnvelopeSender.java
io/sentry/ILogger.java
io/sentry/NoOpEnvelopeReader.java
io/sentry/SessionAdapter.java
```

```
jar tf sentry-5.0.0-sources.jar | head -n 20
META-INF/
META-INF/MANIFEST.MF
constant-values.html
overview-tree.html
index.html
overview-frame.html
allclasses-noframe.html
serialized-form.html
index-all.html
deprecated-list.html
io/
io/sentry/
io/sentry/CustomSamplingContext.html
io/sentry/MainEventProcessor.html
io/sentry/HubAdapter.html
io/sentry/DiagnosticLogger.html
io/sentry/ILogger.html
io/sentry/IScopeObserver.html
io/sentry/EnvelopeSender.html
io/sentry/UserFeedback.html
```

I also manually checked the contents of
- https://repo1.maven.org/maven2/io/sentry/sentry/5.0.0/sentry-5.0.0-javadoc.jar
- https://repo1.maven.org/maven2/io/sentry/sentry/5.0.0/sentry-5.0.0-sources.jar

This issue was not present with SDK version 4.3.0.

**Steps to reproduce:**
- Run `mvn dependency:sources` and `mvn dependency:resolve -Dclassifier=javadoc` (or the equivalent IDE function) to retrieve source and javadoc artifacts.
- Investigate contents via `jar tf «filename»`.

**Actual result:**
- Source and javadoc jars are mixed up.

**Expected result:**
- Those artifacts should not be mixed up.

**Comment by marandaneto** [comment]
@rkraneis thanks for raising this, let me check that.

**Comment by marandaneto** [comment]
indeed, it's a bug in the release script but I already have prepared a fix.

**Comment by rkraneis** [comment]
Thank you for the quick reaction.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/5.0.1
