### ISSUE TITLE
No way to remove attachments

### ISSUE THREAD

**Issue by xmanu** [getsentry/sentry-java#1517]
While attaching files to events I found out that there is no way to remove attached files. The only way is to completely clear the scope which is not feasible without losing a lot of information.

Would it be possible to add a `clearAttachments()` method in `Scope` analogously to the `clearBreadcrumbs()` method?

Currently I have to resort to reflection to manually clear the `attachments` CopyOnWriteArrayList...

**Comment by marandaneto** [comment]
@xmanu indeed, thanks for raising this, we'll discuss it internally and will keep you posted.
cc @philipphofmann and @bruno-garcia

**Comment by philipphofmann** [comment]
Thanks for opening up this issue. I think adding `clearAttachments` would make sense to me.

**Comment by xmanu** [comment]
Thanks for getting back to me so quickly! Should I create a PR? It should only be a few lines, but I don't know your processes for PRs (testing etc) yet...

**Comment by marandaneto** [comment]
@xmanu hold on while we discuss with the broader team, this would likely be a new added API across all the SDKs, so we need to be sure that its all aligned & discussed.
for reference: https://develop.sentry.dev/sdk/unified-api/

**Comment by xmanu** [comment]
Sure! 👍

**Comment by philipphofmann** [comment]
To help us understand your needs, @xmanu, can you please describe your use case why you need to remove attachments?

**Comment by xmanu** [comment]
I have rolling logs in my Android app with the naming pattern log.1.txt, log.2.txt etc... Only the 2 latest ones are kept. I now use the `beforeSend` callback to attach these logfiles to the reports. When multiple events now trigger the `beforeSend` callback, I get multiple copies of the same files in the attachments list.
I know that there is the local version `withScope` instead of `configureScope` but for me that would not be sufficient as I want to always include the logs, but have the correct log files included.

But this is only one possible use case I can imagine. There might be other reasons why one might want to remove an already configured attachment. 

I could also imagine another solution to my specific problem by allowing to add attachments to the `SentryEvent` in the beforeSend callback.

**Comment by marandaneto** [comment]
I see, wondering if it makes sense to add a boolean param to the addAttachment method, that would pretty much remove itself from the list when it's sent, so you basically add an attachment for being sent only once, default is sending on every following event.

**Comment by xmanu** [comment]
That would also be a valid solution, but it seems weird to me design wise... Attaching for a single event is already possible using `withScope` instead of `configureScope`... This would result in having this functionality twice (even though your proposed solution is more powerful and would cover my use-case whereas `withScope` does not).

I would greatly prefer a way to manipulate the global scope as it is already possible with other scope based values like breadcrumbs, tags, contexts or extras. All of those have different means of also removing not only adding. Having a `clearAttachments` (or alternatively `getAttachments` being public and a `removeAttachment` method) would IMHO be a solution more in line with the rest of the API... (it almost looks like an oversight that this is not possible for attachments right now)

**Comment by marandaneto** [comment]
we'll expose a `clearAttachments` method.

@xmanu would you like to submit a PR? thanks

**Comment by philipphofmann** [comment]
We are going to add `clearAttachments` to the scope right, @marandaneto? I'm also going to open up an issue for Cocoa.

**Comment by xmanu** [comment]
@marandaneto I will create a PR. I will add the `clearAttachments` method to the Scope.

**Comment by philipphofmann** [comment]
Nice @xmanu. I already opened up a PR for Cocoa https://github.com/getsentry/sentry-cocoa/pull/1195.

**Comment by philipphofmann** [comment]
I'm going to open up a PR to update the docs. @marandaneto we should also update them for Java after releasing this PR https://github.com/getsentry/sentry-docs/blob/9c0097241dfd389b6d83c73b5618ef3b62da1070/src/platforms/common/enriching-events/attachments/index.mdx#L10.

**Comment by xmanu** [comment]
I have opened PR #1562 that introduces the `clearAttachments` method.

**Comment by bruno-garcia** [comment]
Requires docs changes. See the cocoa one: https://github.com/getsentry/sentry-docs/pull/3797/files
