### ISSUE TITLE
can't execute the command "../../gradlew appRun" on the moudle sentry-samples-spring

### ISSUE THREAD

**Issue by guozhaocai90** [getsentry/sentry-java#1521]
I want to test the sentty in the Spring environment,when i execute the command "../../gradlew appRun" on the moudle sentry-samples-spring,An error occurred ,
* What went wrong:
Task 'appRun' not found in project ':sentry-samples:sentry-samples-spring',Whether I need to configure this command. 
someone can help me please.

**Comment by marandaneto** [comment]
@guozhaocai90 can confirm, thanks for reporting.

@maciejwalkowiak can you check this one and other samples if the command in readme is up to date? thanks

**Comment by maciejwalkowiak** [comment]
Gretty - the plugin that adds tasks to run Tomcat or Jetty with Spring sample project - is not compatible yet with Gradle 7.0. Right now the only way to run the sample is to build a war file and deploy to Tomcat or any other application server.

**Comment by marandaneto** [comment]
apparently is fixed https://github.com/gretty-gradle-plugin/gretty/issues/206 but not released yet, only as a snapshot, so either we add their https://jitpack.io/#gretty-gradle-plugin/gretty/gretty-3.x-SNAPSHOT repository or wait for a release.

**Comment by maciejwalkowiak** [comment]
I tried and did not manage to make our Gradle config pick up a plugin from Jitpack. I guess its not that high priority that we cannot wait for a release.
