### ISSUE TITLE
Better Java compatibility for `SentryOkHttpInterceptor`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1526]
Today this is not possible:

`SentryOkHttpInterceptor interceptor = new SentryOkHttpInterceptor(HubAdapter.getInstance());`

only if passing also a `BeforeSpanCallback`, the suggestion is adding another ctor.

`constructor(hub: IHub) : this(hub, null)`

**Comment by maciejwalkowiak** [comment]
Since this change isn't breaking, it can be done in 5.x
