### ISSUE TITLE
Rename `shutdownTimeout` to `shutdownTimeoutMillis`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1530]
the reason is to align with other properties like `flushTimeoutMillis`, `sessionTrackingIntervalMillis`, `connectionTimeoutMillis` and `readTimeoutMillis`

we'd need to fix docs too

**Comment by bruno-garcia** [comment]
I propose we add the new one and annotate the other as obsolete. And on 6.0.0 we can drop it (ideally many months ahead to give folks time to move over due to the warning instead of a compilation problem which is harder to 'get'/requires reading migration or guess the alternative API).

**Comment by marandaneto** [comment]
before going ahead with the renaming, I'd like to discuss https://github.com/getsentry/sentry-dart/issues/497 too

**Comment by bruno-garcia** [comment]
Java 8 has `Duration` too? https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html
Can we use that?
It would need to be added as a new field anyway because it'd break any serialized config such as env var, application.yml, AndroidManifest.xml etc

**Comment by marandaneto** [comment]
Let's not just rename, but rather deprecate and add the new one.
