### ISSUE TITLE
DuplicateEventDetectionEventProcessor#capturedObjects could be a thread safe list of WeakReference

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1533]
```
  private final @NotNull Map<Throwable, Object> capturedObjects =
      Collections.synchronizedMap(new WeakHashMap<>());
```

looks like we never use the value, but only the key, does it need to be a `Map` then?

**Comment by marandaneto** [comment]
cc @bruno-garcia and @maciejwalkowiak

**Comment by marandaneto** [comment]
maybe it's a Map because we're trying to make the lookup more efficient?

**Comment by marandaneto** [comment]
we could use a https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ref/ReferenceQueue.html or https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ref/WeakReference.html

**Comment by bruno-garcia** [comment]
Not sure how either of those would help. Could you please elaborate?

**Comment by maciejwalkowiak** [comment]
We could change it to a synchronized `List<WeakReference>` but I don't see benefit. I think the code would not be more readable either.

**Comment by marandaneto** [comment]
ideally `CopyOnWriteArrayList<WeakReference>`, but indeed it's not much benefit rather than correctness, since we use a `Map` but only the key, no value, maybe using a List is cheaper in memory allocation?

**Comment by maciejwalkowiak** [comment]
I think its O(n) in both cases, and I think both need to iterate over whole collection till they find a value.

**Comment by marandaneto** [comment]
@maciejwalkowiak WeakHashMap is O(1) because its a hashtable.
CopyOnWriteArrayList should be O(n) since it goes item per item.

https://www.baeldung.com/java-collections-complexity
I guess its best to keep as it is then, lets close the issue
