### ISSUE TITLE
Vendor JsonWriter/Reader and drop Gson dependency

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1537]
We decided to drop the Gson dependency and write JSON explictly via JsonReader and JsonWriter.

This will address: #1489 #1497 #1420 

- [ ] Timestamps should be encoded as double to get higher preicison than the current format (only up to milliseconds) (See https://github.com/getsentry/sentry-java/issues/1541)

**Comment by antonmos** [comment]
Please consider this issue when doing this work https://github.com/getsentry/sentry-clj/issues/31

**Comment by marandaneto** [comment]
closed by https://github.com/getsentry/sentry-java/pull/1554
