### ISSUE TITLE
Investigate Performance for Jetpack Navigation and Compose

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1542]
https://developer.android.com/guide/navigation/

**Comment by marandaneto** [comment]
Compose too https://developer.android.com/jetpack/compose

**Comment by bruno-garcia** [comment]
Compose has GA'ed recently! 🥳

**Comment by marandaneto** [comment]
> Compose has GA'ed recently! 🥳

We've seen some movement in the Android community using compose already, worth investigating it.

**Comment by romtsn** [comment]
https://chris.banes.dev/composable-metrics/ for metrics, but it's a compiler flag, so needs feasibility check

**Comment by romtsn** [comment]
This is closed by #2136
