### ISSUE TITLE
Insecure HostnameVerifier Issue

### ISSUE THREAD

**Issue by bharathkandula99** [getsentry/sentry-java#1544]
_Platform:_
-   Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?

_IDE:_
-   Android Studio -> If yes, which version?

_Build system:_
-   Gradle -> If yes, which version?

_Sentry Android Gradle Plugin:_
-   Yes -> version 4.3.0

The version of the SDK:
**4.2.1**

---
I have the following issue:

Insecure HostnameVerifier

I integrated sentry logs for the new version of my app and I tried to push to play store production, I'm getting  this error <br>  <br><img width="604" alt="Screenshot 2021-06-18 at 11 44 28 AM" src="https://user-images.githubusercontent.com/62982842/122515110-96138e80-d02a-11eb-983f-e9668877a896.png"> <br> <br>

I have added only sentry logs in sentry integration in a new version, my previous version goes well without any rejections, when added sentry and submitted to the play store, it gets rejected with the above error.

Please help to solve this issue ASAP.

**Comment by bruno-garcia** [comment]
Closing it since it's a known no-issue already discussed here: #861 and #840

Feel free to reopen otherwise.
