### ISSUE TITLE
Support for Markers in logback and log4j2 libraries

### ISSUE THREAD

**Issue by anderscarling** [getsentry/sentry-java#1547]
Since the rewrite/move to unified Sentry Client API it seems support for Marker's was dropped in the logback and log4j2 libraries.

It would be trivial to add back basic support:
```
    if (loggingEvent.getMarker() != null) {
      event.setExtra("marker", loggingEvent.getMarker().toString());
    }
```

Are you interested in adding this functionality? I think I can find time to make a PR but wanted to check if it had a chance to be merged before investing more into this.

**Comment by marandaneto** [comment]
cc @maciejwalkowiak 
did we have this before?

**Comment by anderscarling** [comment]
It seemed to have been there for at least the log4j2 lib, as the feature was expand in #691.

**Comment by marandaneto** [comment]
indeed, and its an easy one, logback would also work via `ILoggingEvent#getMarker`
would you like to open a PR @anderscarling ?

**Comment by marandaneto** [comment]
thanks @anderscarling :)
