### ISSUE TITLE
Support ownership rules/code owners

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1550]
Similar to https://github.com/getsentry/sentry-dart/issues/347

**Comment by marandaneto** [comment]
@philipphofmann check and raise an issue for Apple plat, if it's possible to get the filename and abs path either at runtime or symbolication.

**Comment by adinauer** [comment]
May be related to https://github.com/getsentry/sentry-java/issues/633

**Comment by bruno-garcia** [comment]
Can this be closed?

**Comment by philipphofmann** [comment]
I think it can, @bruno-garcia. We can always reopen if needed.
