### ISSUE TITLE
Waiter, there's a fly in my soup!

### ISSUE THREAD

**Issue by chadwhitacre-test** [getsentry/sentry-java#1560]
Is it doing the breast stroke or the back stroke?

**Comment by chadwhitacre** [comment]
@marandaneto Sorry for the unexplained noise issue. This was to test the new getsantry bot integration. For future (real) issues if you apply a label (any label) then the bot will remove the `Status: Untriaged` label. We're using this label to compute time-to-triage. Cheers! :)

**Comment by marandaneto** [comment]
oh got it, they are just the `image_addr` that have been used for symbolication, no issues in there.

**Comment by marandaneto** [comment]
@chadwhitacre yeah I got it :D
@chadwhitacre the bot isn't removing the label though, See https://github.com/getsentry/sentry-java/issues/1561

**Comment by chadwhitacre** [comment]
Blech, still hitting https://github.com/getsentry/eng-pipes/issues/216 it seems. :-/

Workaround would be to [make your Sentry org membership public](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership). If you do that then the bot should not add `Status: Untriaged` in the first place.
