### ISSUE TITLE
Add `crashedLastRun` for Android

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1569]
Similar to the iOS API `crashedLastRun`: https://github.com/getsentry/sentry-cocoa/search?q=crashedlastrun

We'd like to know if the previous execution resulted in a crash (via Java or Native) while on an Android app.
This will be used by Unity (see https://github.com/getsentry/sentry-dotnet/issues/1096)

This could live on `SentryAndroid` static class.

**Comment by marandaneto** [comment]
dup of https://github.com/getsentry/sentry-java/issues/1125
