### ISSUE TITLE
create craft post release craft

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1580]
add `Unreleased` back to the (changelog)
append `-SNAPSHOT` to `versionName` (gradle.properties)

should the post release script bump the `buildVersionCode`?
https://github.com/getsentry/sentry-java/blob/main/scripts/bump-version.sh#L15-L19

as the `versionName` will have the `next version-SNAPSHOT`, it'd make sense that the `buildVersionCode` is already the correct one.

**Comment by marandaneto** [comment]
check if craft is creating a temp. file called `gradle.propertiese`

**Comment by iker-barriocanal** [comment]
Creation of `gradle.propertiese` is addressed in https://github.com/getsentry/sentry-java/pull/1581.

**Comment by iker-barriocanal** [comment]
Adding an `Unreleased` empty entry back to the changelog is addressed in https://github.com/getsentry/sentry-java/pull/1582.
