### ISSUE TITLE
Method to get the app start measurement afterwards for Hybrid SDKs

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-java#1584]
We will need a method, maybe getAppStartTime, that can be called from hybrid SDKs sometime regardless of the init call, that is called to get the app start measurement.

This would include:

The app start type (warm, cold, etc)
The app start initial time
The app start finish time

Related: https://github.com/getsentry/sentry-cocoa/issues/1208#issue-937093040

**Comment by marandaneto** [comment]
the class is called `AppStartState`, we just need to make it public and add the `@ApiStatus.Internal` annotation
