### ISSUE TITLE
Option to disable some auto performance for Hybrid SDKs

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-java#1586]
Hybrid SDKs will be propagating the tracesSampleRate down to the native SDKs.

So we will need an option to not fully disable auto performance tracing but rather only disable some instances of it.

A suggestion of what to disable would be to disable any instrumentation that creates transactions but keep span-creating ones, this is in the case that if a user decides to use native transactions they would still get spans attached.

cc @bruno-garcia

Related: https://github.com/getsentry/sentry-cocoa/issues/1212

**Comment by marandaneto** [comment]
not sure if I follow the request, this is already possible, the Hybrid SDK just should turn on/off the desired features? eg https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java#L71

**Comment by bruno-garcia** [comment]
Android instrumentation options are already fine grained as @marandaneto pointed out.
Please reopen if there's something you need that's not there in the code yet
