### ISSUE TITLE
Capture events from `System.err`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1593]
Add an integration to read from the stderr stream and capture events.

Could be an opt-in for now, to become an opt-out on the next major.

We need to make sure we don't double report if a logging integration (i.e.: logback) also writes to stderr.

**Comment by maciejwalkowiak** [comment]
Since its a stream of bytes, how would we know that this is the end of the message and should be turned into event?

**Comment by bruno-garcia** [comment]
The default strategy could be based on utf8-encoded string looking for `\n`? 

Let's keep this issue open to see if anyone 👍 and give some feedback on how we could go about this. So far seems like not worth spending time on this.

**Comment by marandaneto** [comment]
the issue is similar to https://github.com/getsentry/sentry-java/issues/1620
the same approach should be taken, or, bytecode manipulation

**Comment by bruno-garcia** [comment]
@marandaneto You can subscribe to a stream with `System.err`, differently than `logcat`

**Comment by marandaneto** [comment]
@bruno-garcia you can, there are a few options, eg `logcat -b default`, which is a buffer, `logcat -f file.txt`, etc... but yeah lets wait some more feedback over it

**Comment by romtsn** [comment]
Since logcat is implement via bytecode manipulation and there are no 👍 here, I think we're good to close this one
