### ISSUE TITLE
SentryAppender not final

### ISSUE THREAD

**Issue by cocorossello** [getsentry/sentry-java#1602]
_Platform:_
- [X]  Logback -> Any version

The version of the SDK:
Any

---
I would like to extend a bit the functionality of the SentryAppender, play a bit more with it, but I can't extend it because the class is final and the append method is protected and the createBreadcrumb is private. 

So, my question is: is there any reason to make it a final class? 

I would like to pass the marker as a hint to the createEvent so I can play a bit more, something like:
LOGGER.error(MyMarker.withFingerprint("SomeSpecificIssueID").withSomeExtraTag("someTag", "someValue"), "Some error");

So with only a marker I could send some more metainfo like the fingerprint key and some more tags without abusing the MDC.

I understand that this is a very opinionated thing, having the SentryAppender not final (and also making the createBreadcrumb method protected and the append method public) would be enough.

**Comment by marandaneto** [comment]
@cocorossello thanks for raising this.

which SentryAppender? logback? log4j2?

@maciejwalkowiak @bruno-garcia if nothing against it, we can check all of our appenders and take the same approach, making it non-final and having protected methods, so people can customize them, wdyt?

**Comment by cocorossello** [comment]
Logback, I haven't looked others

**Comment by maciejwalkowiak** [comment]
It leaks an internal structure, but appenders are very stable - I think we can relax them:

- make `SentryAppender` for Log4j2 and Logback non-final
- make `createEvent` and `createBreadcrumb` protected.

@cocorossello would you like to contribute a PR?

**Comment by cocorossello** [comment]
Sure! thanks

**Comment by marandaneto** [comment]
@cocorossello remember to annotate the nonfinal classes with the `@Open` annotation, otherwise, CI fails.
maybe also do `make api`, not sure if the public API changes when its final or not
