### ISSUE TITLE
Why Min Sdk 21 is requrired for sentry-android-fragment and sentry-android-okhttp?

### ISSUE THREAD

**Issue by Alireza-Farahani** [getsentry/sentry-java#1607]
Both mentioned artifacts have configured api 21 as minimum. `sentry-android-okhttp` depends on OkHttp 4.9 which itself requires minsdk 21, but the functionality doesn't require api 21. `sentry-android-fragment` doesn't require api 21 at all. I was able to use both artifacts in my app, leveraging `tools:overrideLibrary` in `AndroidManifest.xml` file.

Is there a specific reason behind choosing 21 as min sdk? Should I expect any runtime problems?

Anyway, I think related docs in "integrations" segment should explicitly mention about the min sdk requirement.

**Comment by marandaneto** [comment]
@Alireza-Farahani thanks for raising this.

for OkHttp: https://github.com/square/okhttp#requirements

> OkHttp works on Android 5.0+ (API level 21+) and Java 8+.

Might be the case that it works for older versions, but as its not tested by us, we prefer to stick to the official OkHttp docs.

I'll check the fragments compatibility.

indeed docs could better state that, although we've it written down here in the README file https://github.com/getsentry/sentry-java#sentry-sdk-for-java-and-android

**Comment by marandaneto** [comment]
apparently androidx.fragment is min API 14, See https://github.com/getsentry/sentry-java/pull/1608
Let's see if CI gets happy as there are code checks via AGP and code compatibility
