### ISSUE TITLE
Improvement: allow SentryTracingFilter to exclude some urls in order not to deplete Transaction-count rapidly

### ISSUE THREAD

**Issue by hanswesterbeek** [getsentry/sentry-java#1610]
We have a monitoring-system that pings `/actuator/health` quite often.

I'd love for an URL like that to be excluded from Sentry performance metrics collection.

I can imagine multiple ways of making this configurable and the implement it and am happy to provide a PR once I consulted you about it.

A very simple way to get started:

- Add `sentry.trace.ignoredPaths`: a comma-separated list of paths that must be an case-insensitive match with `request.getPath`

**Comment by marandaneto** [comment]
@hanswesterbeek what's about the sampling function? See https://docs.sentry.io/platforms/java/configuration/sampling/#setting-a-sampling-function
does that help?

**Comment by hanswesterbeek** [comment]
Good point :)

Indeed all it takes is to implement this:

```java
@Component
class CustomTracesSamplerCallback implements TracesSamplerCallback { }

```
