### ISSUE TITLE
http proxy not work

### ISSUE THREAD

**Issue by gaojun2048** [getsentry/sentry-java#1613]
### Environment

self-hosted (`onpremise` deployment)

### Version

5.0.1

### Steps to Reproduce

1. I test http proxy about java sdk and my sentry.properties file is like this:
```
#sentry config
proxy.user=
maxBreadcrumbs=300
proxy.pass=
proxy.host=192.168.220.124
uncaught.handler.enabled=true
proxy.port=3128
```

2. I started my java process, and then triggered the event to report to sentry, but I found that the java sdk did not request the proxy server, but skipped the proxy and directly connected to my sentry server. Therefore, the sentry server can receive the event reported by the java sdk, but cannot see the java sdk request log on the proxy server.

Why does the java sdk not request proxy services? Is it a bug?

### Expected Result

Java SDK request the proxy server and I can see the request log on the http proxy server (A nginx server).

### Actual Result

Java SDK skipped the http proxy server and directly connected to my sentry server. So the sentry server can receive the event reported by the java sdk, but cannot see the java sdk request log on the proxy server.

**Comment by gaojun2048** [comment]
Sorry, I now migrate this issue to sentry-java

**Comment by maciejwalkowiak** [comment]
Where do you put `sentry.properties` file? Do other properties from this file are applied to `SentryOptions`? The issue seems to be with passing configuration in your project, not with proxy settings. Ideally, please provide minimal reproducible example either as attached zip file, or a github repository.

**Comment by gaojun2048** [comment]
> Where do you put `sentry.properties` file? Do other properties from this file are applied to `SentryOptions`? The issue seems to be with passing configuration in your project, not with proxy settings. Ideally, please provide minimal reproducible example either as attached zip file, or a github repository.

sentry.properties is in my classpath. Other properties from this file are applied to `SentryOptions` ok.

**Comment by maciejwalkowiak** [comment]
@gaojun2048 I tried and failed to reproduce this issue. Please look at the repository here: https://github.com/maciej-scratches/sentry-proxy-sample

Proxy is configured in `src/main/resources/sentry.properties`, once you run it without proxy running, sending event fails with `java.net.SocketTimeoutException: connect timed out`, which means that proxy properties are loaded from the file. 

It is important to [enable loading external configuration.](https://github.com/maciej-scratches/sentry-proxy-sample/blob/master/src/main/java/org/example/Main.java#L8).

If this does not help you with solving this problem, please create a similar sample repository that reproduces this issue.

**Comment by maciejwalkowiak** [comment]
@gaojun2048 did you manage to get it working?

**Comment by gaojun2048** [comment]
> @gaojun2048 did you manage to get it working?

Yes, It is ok when I add this line: `options.setEnableExternalConfiguration(true)`
