### ISSUE TITLE
Sentry.captureException(e) not working

### ISSUE THREAD

**Issue by tiagodinis33** [getsentry/sentry-java#1617]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> 1.8
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [x]  Log4j2 -> beta9
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> 2021.1.13
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**3.x.x**

---
I have the following issue:
Its just not working, but my sentry issues are empty.
The description goes here ...

**Steps to reproduce:**
- use Sentry.captureException

**Actual result:**
- nothing

**Expected result:**
- Appear an issue on sentry

**Comment by maciejwalkowiak** [comment]
Consider switching to the latest (5.0.1) version of the SDK. Please set `debug` to `true` on `SentryOptions` and maybe output can help to understand what is wrong. 

Look at our samples - maybe you'll find what you have missed in your code: https://github.com/getsentry/sentry-java/tree/main/sentry-samples

If this doesn't help, please create a sample that reproduces this issue and either attach here as a zip file, or put it to a separate github repo.

**Comment by tiagodinis33** [comment]
Btw im using for my minecraft client so its an LWJGL 2 app
idk if it requires a web framework to work
[crash-2021-07-23_10.30.50-client.txt](https://github.com/getsentry/sentry-java/files/6867833/crash-2021-07-23_10.30.50-client.txt)

**Comment by marandaneto** [comment]
@tiagodinis33 can you paste the `debug` output, please? thanks
