### ISSUE TITLE
Support for Feign

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1628]
We currently support OkHttp, RestTemplate (and [WebClient is in the works](https://github.com/getsentry/sentry-java/pull/1621)).

The goal is to extend it by adding Feign: https://github.com/OpenFeign/feign

What to expect from this support is defined in our current 'Expected features: HTTP Client' docs:

https://develop.sentry.dev/sdk/features/#http-client-integrations

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/pull/1632
