### ISSUE TITLE
When can we expect 5.1.0 release?

### ISSUE THREAD

**Issue by VladyslavKasprov** [getsentry/sentry-java#1631]
I'm looking forward towards integratimg Fragment breadcrumbs collection in our app.

It's already been 2 months since 5.0.0 release. I'd like to know when can we expect 5.1.0 release?

**Comment by bruno-garcia** [comment]
@VladyslavKasprov Thanks for raising. We plan to ship this in the upcoming days/weeks. We're looking for more validation of the features we've recently added. Did you try the fragment in the beta releases already?

Also, we've added App Start and Frozen/Slow frames, did you have a chance to look at those numbers and try things out?

If you're on sentry.io I'm also happy to opt you in to our early adoption program to see the new performance dashboard.

**Comment by VladyslavKasprov** [comment]
@bruno-garcia Thanks for the feedback. Yes, I tried fragment breadcrumbs already. They work very well)

No, I haven't seen App Start and Frozen/Slow frames yet. Our plan on sentry.io doesn't include Performance :(

Yes, I'd like to.

**Comment by marandaneto** [comment]
we're going to release it late today, closing it, thanks!
