### ISSUE TITLE
Sentry Issue missing device information when crashing in native code

### ISSUE THREAD

**Issue by adenisonafifi** [getsentry/sentry-java#1639]
_Platform:_
- [X]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version? 
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [X]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

    // Gradle variables
    compileSdkVersion   = 29
    buildToolsVersion   = "29.0.2"
    ndkVersion          = "21.3.6528147"

    // Build/SDK variables
    platformVersion     = 18
    minSdkVersion       = 24
    targetSdkVersion    = 29

cmake_minimum_required(VERSION 3.6.0)

_IDE:_
- [X]  Android Studio -> If yes, which version? 2020.03.1
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [X]  Gradle -> If yes, which version? 6.1.1
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [X]  Yes -> If yes, which version?  4.0.1
- [ ]  No

_Sentry Android Gradle Plugin:_
- [X]  Yes -> If yes, which version? 1.7.28
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [] JCenter
- [ ] Bintray
- [X] Maven Central
- [ ] Manually

The version of the SDK:
5.0.1

---
I have the following issue:

Sentry crash reports do not have enriched device information when the crash occurs in native code.
The custom tags, symbolicated call stacktrace, and custom breadcrumbs (excluding the ui/app/device lifecycle breadcrumbs)   are all present, but I do not see the expected Android SDK portion of the error report.

With the same build configuration if I cause a sentry error in the java portion of the code then I get all Android SDK / device information as expected. 

In my top level build.gradle buildscript block I specify dependencies:
```   
dependencies {
       ...
        // Sentry Crash Reporting
        classpath 'io.sentry:sentry-android-gradle-plugin:1.7.28'
        classpath 'io.github.howardpang:androidNativeBundle:1.0.9'
    }
```
In my application build.gradle android block I specify dependencies and compileOptions:
```
dependencies {
        ...
        // Sentry Crash Reporting
        implementation 'androidx.appcompat:appcompat:1.3.1'
        implementation 'io.sentry:sentry-android:5.0.1'
}

        // Sentry Crash Reporting
compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
```

And finally in CMakeLists I include the mk file and link to the native modules
```
target_link_libraries(application_name
    # Sentry Crash Reporting
       ${ANDROID_GRADLE_NATIVE_MODULES}
)

include (${ANDROID_GRADLE_NATIVE_BUNDLE_PLUGIN_MK})
```

I am relying on the SDK to initialize itself given the configuration in AndroidManifest.xml -- am I supposed to manually initialize the SDK when using NDK?

**Comment by marandaneto** [comment]
@adenisonafifi 

> I am relying on the SDK to initialize itself given the configuration in AndroidManifest.xml -- am I supposed to manually initialize the SDK when using NDK?

no, not really.

I just tried to reproduce it and I do get the Android part, can you specify the "expected Android SDK portion of the error report"?
also, how are you reproducing a crash on native code?

**Comment by adenisonafifi** [comment]
I am attaching screenshots of two error reports from the same build. One error report from calling `Sentry.captureException(e);` in Java, and the other from a C++ crash (executing `*((unsigned int*)0) = 0xDEAD;`).

The same force crash mechanism shows device information for Windows, MacOS, iOS, and tvOS (and has application lifecycle information in the tvOS and iOS versions).

<img width="1971" alt="Native Crash" src="https://user-images.githubusercontent.com/5401552/129067503-eff9c01e-950e-4bd2-9a29-156ca5f2603d.png">

<img width="1801" alt="Java Error" src="https://user-images.githubusercontent.com/5401552/129067517-aa5fab4b-9f47-4495-bc76-816f0c2f219f.png">

**Comment by marandaneto** [comment]
@adenisonafifi I just tried to reproduce this issue and could not, on App restart, the event has full Android context, can you set up a sample project on GitHub that helps to reproduce this issue? I'm looking for your SDK init set up, etc.

Maybe Device Brand, Model and OS version too, it could be related to it, thanks

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
