### ISSUE TITLE
I cannot publish my app :( Sentry does not capture crashes, and my app gets rejected again and again by app stores

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-java#1642]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Proguard/R8:_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
sentry-flutter  5.0.0

---
I have the following issue:

Hi, thanks for the lib! When I publish my app to an Android app store, the reviewers rejected my app, saying that: "the app fails to start". They also provide a (almost useless) screenshot, showing the android system homepage, indicating that they tapped the app icon and it fails to start.

However, I see completely **nothing** in my sentry webpage. Originally, sentry works pretty well - it captures many Flutter (Dart) exceptions, many Android (Java) exception and so on. But this time it fails. 

If this is a rare bug I can tolerate it. However, that Android app store has rejected my app several times, every time saying that it crashes! But I really have zero evidence on what bug it is indeed, because I cannot get any stack trace, neither can I get any logs.

Any help is appreciated!

**Steps to reproduce:**
- see above

**Actual result:**
- see above

**Expected result:**
- see above

**Comment by bruno-garcia** [comment]
Dupe https://github.com/getsentry/sentry-dart/issues/548
