### ISSUE TITLE
Add Radiography integration

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#1647]
Add optional [Radiography](https://github.com/square/radiography) integration to automatically capture view hierarchy in case of a crash. Can be sent as a text file via an [attachment](https://docs.sentry.io/platforms/android/enriching-events/attachments/).

The benefit is that it also supports Jetpack Compose.

**Comment by marandaneto** [comment]
This is partially blocked by https://github.com/getsentry/sentry-cocoa/issues/1772
Ideally, we'd do a quick investigation for Cocoa support, so we know if it's possible and how the widget tree would look like,

**Comment by markushi** [comment]
View Hierarchy is now collected without radiography.
