### ISSUE TITLE
ActivityFrameTracker breaks runtime theme changing.

### ISSUE THREAD

**Issue by lennykano** [getsentry/sentry-java#1659]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [x]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [x] Manually

Using this repository so all dependency/build versions are as specified in the sample code available.
Tested using Android Studio 2021.1.1 (not a build related issue, read below for cause)

Problem occurs on all Android versions >= 29

The version of the SDK:
**5.1.0-beta6+**

---
I have the following issue:

Setting an activity theme at runtime is broken since 5.1.0-beta6 (problem remains on 5.1.0) ...

**Steps to reproduce:**
- Add `setTheme(R.style.Theme_AppCompat);` before `super.onCreate(savedInstanceState);` in the sample apps `MainActivity`.

**Expected result:**
- Activity has a black background as per the theme.

**Actual result:**
- Activity has a white background (which is from the theme defined in AndroidManifest.xml). Window background from runtime theme change is not being applied.

If I remove usages of `ActivityFramesTracker` then it behaves as suspected and window background is applied correctly. Can also hardcode `isAllActivityCallbacksAvailable` to false so the frame tracker applies later, in onCreate, and the issue won't present itself.

My suspicion is that `frameMetricsAggregator.add(activity);` is being called too early (currently in `onActivityPreCreated` lifecycle callback), and is causing WindowManager to 'lock in' the window background, preventing it from changing when the theme is updated later on. Notice that other theme attributes (action bar, text color) are applied successfully.

This makes the SDK unusable as the splash screen background is persisting after the activity has finished loading. Not sure why you need to run anything in `onActivityPreCreate` but if that can be avoided, would be the simplest solution to the problem.

**Comment by marandaneto** [comment]
@lennykano thanks for reporting, interesting corner case, let me investigate this, if its the case, we can move the calls from `onActivityPreCreated` to `onActivityCreated`

**Comment by lennykano** [comment]
@marandaneto thanks for the quick turnaround.

**Comment by marandaneto** [comment]
@VGJohn probably because of https://github.com/getsentry/sentry-java/issues/1768 so a fix is on its way, thanks for reporting.
