### ISSUE TITLE
Improve CI by not running all the tasks for debug and release on Android

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1664]
https://github.com/getsentry/sentry-java/blob/main/.github/workflows/build.yml#L43-L45

`gradlew build` runs `check` which runs tests for debug and release variants on Android, either we filter the debug tests via gradle configuration, or make the gradle call for specific testing flavors like `testReleaseUnitTest`

something like:

```
    testOptions {
        unitTests.apply {
            all {
                if (it.name.endsWith("DebugUnitTest")) {
                    // println(it.name) do not run tests
                }
            }
        }
    }
```

we just need to find out how to filter tests to be run on the debug variant

**Comment by marandaneto** [comment]
@cortinico since you are the Gradle master, do you know an easy way out of it? if I don't filter the debug tests via gradle configuration, I have to use something else instead of `./gradlew build` to trigger all the checks etc

**Comment by cortinico** [comment]
> since you are the Gradle master, do you know an easy way out of it?

Could the `debug` variant be disable entirely? Or are there reason to have it enabled?

**Comment by marandaneto** [comment]
yes but I wanna be able to run and debug my app locally still, if it does not affect that, all good.

**Comment by cortinico** [comment]
> yes but I wanna be able to run and debug my app locally still, if it does not affect that, all good.

I would setup up a `variantFilter` like this one https://stackoverflow.com/a/32129704/3765748 and have a condition that checks for an environment variable (say `CI`).

**Comment by marandaneto** [comment]
very good idea, thanks a lot @cortinico
