### ISSUE TITLE
Allow custom getFragmentNames in FragmentLifecyclesBreadcrumbs

### ISSUE THREAD

**Issue by audkar** [getsentry/sentry-java#1679]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**5.1.1**

---
I have the following issue:

Our Android apps' Fragment names obfuscated in release build. If we enable "enableFragmentLifecycleBreadcrumbs" we get obfuscated "screen" data in breadcrumbs.

We already have a way to get a nice names for _Fragments_ in our app. Would it be possible to set custom _Fragment_ names provider for `SentryFragmentLifecycleCallbacks` to change [this default behaviour](https://github.com/getsentry/sentry-java/blob/6bb215deffc13809aeca6b0799bea89b0ddf62e0/sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt#L119)?

Something like this.
```kotlin
fragmentNameProvider: (fragment: Fragment): String
```

**Steps to reproduce:**
Enable R8 for Android build and add `FragmentLifecycleIntegration`
```
addIntegration(
  FragmentLifecycleIntegration(
    application,
    enableFragmentLifecycleBreadcrumbs = true,
    enableAutoFragmentLifecycleTracing = true,
  )
)
```

**Actual result:**
```json
{screen: b, state: stopped}
```

**Expected result:**
```json
{screen: Login, state: stopped}
```

**Comment by marandaneto** [comment]
its a dup of https://github.com/getsentry/sentry-java/issues/1086 but will keep it open since its specific to the FragmentLifecyclesBreadcrumbs

you can exclude the minification of file names via proguard configuration, you can also customize the breadcrumbs via the callback https://docs.sentry.io/platforms/android/enriching-events/breadcrumbs/#customize-breadcrumbs
but a `fragmentNameProvider` isn't a bad idea either.

**Comment by audkar** [comment]
> you can exclude the minification of file names via proguard configuration, 

This doesn't fit our needs fully, since we would like to have custom name for a screen. e.g. if our fragment is named `com.pkg.InnerClientLoginFragment` we would like to see `ClientLogin`. We have all screens name mapping logic. It's used between all our tools (analytics, etc).

> you can also customize the breadcrumbs via the callback

If we want to get custom name we need reference to a `Fragment` instance

> Another possibility is to make SentryFragmentLifecycleCallbacks extensible

That would be good too. As long as we can get a `Fragment` reference and return a custom name :)

**Comment by marandaneto** [comment]
the method `addBreadcrumb` accepts a `hint` too which can be the `Fragment` instance, so you can use the `BeforeBreadcrumbCallback` to mutate the breadcrumb's name, I will discuss about that

**Comment by bruno-garcia** [comment]
> the method `addBreadcrumb` accepts a `hint` too which can be the `Fragment` instance, so you can use the `BeforeBreadcrumbCallback` to mutate the breadcrumb's name, I will discuss about that

Today this would be a change on:

https://github.com/getsentry/sentry-java/blob/1f575c6e56a54cbd63e4880754a4f632b9e1d33c/sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt#L115

Please be aware we plan to change `hint` from `Object` and type-cast approach to `Map<String, Object>` so the hint can be changed throughout the processing pipeline in the SDK (data added/remove to it). See: #1558 

We're happy to accept a PR for this

**Comment by audkar** [comment]
> the method addBreadcrumb accepts a hint too which can be the Fragment instance, so you can use the BeforeBreadcrumbCallback to mutate the breadcrumb's name

When I think more about this approach from the client side I see we might have some problems in long term.
1. If we would be replacing this [key-value](https://github.com/getsentry/sentry-java/blob/6bb215deffc13809aeca6b0799bea89b0ddf62e0/sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt#L111) ourselves in `BeforeBreadcrumbCallback` then we would be relying on internal details how Sentry library is logging screens. I see the possibility that might change in the future. And since this `"screen"` key is not considered a public API after change and Sentry dependency update no one even notices that.
1. Adding whole fragment reference into the Breadcrumb we place a big trust in Sentry SDK that it is not going to leak/hold that object for some period of time.

**Comment by marandaneto** [comment]
@audkar indeed, those are valid points, but we don't intend to change the key-value name and if we do so, we'd do a major bump.

we don't hold the reference, never, the `hint` is only used during the event/crumb pipeline.

last case is to disable the `enableFragmentLifecycleBreadcrumbs` feature of the integration and add the crumbs yourself.

**Comment by audkar** [comment]
> last case is to disable the enableFragmentLifecycleBreadcrumbs feature of the integration and add the crumbs yourself.

Ok, probably we are going to do this :+1:

**Comment by audkar** [comment]
Could we revisit this issue? Seems that you are adding more integrations. Seems that it would be better for us to use upstream implementations (instead of our in house fragment tracking).
I created a PR which would solve our problem. WDYT?

**Comment by mrzbn** [comment]
> That's already done on Sentry v6, the fragment instance is set as a hint, so you can do as you wish.
> 
> https://github.com/getsentry/sentry-java/blob/6.x.x/sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt#L121-L123

link is not working. is there a solution to change the fragment's name in breadcrumb?
