### ISSUE TITLE
`transaction.contexts.trace.tags` should go under `transaction.tags`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1693]
right now the transaction tags go under `transaction.contexts.trace.tags` but it should go under `transaction.tags`

`transaction.contexts.trace` should only have a few fields which are documented here https://develop.sentry.dev/sdk/event-payloads/transaction/#examples

**Comment by marandaneto** [comment]
@philipphofmann @brustolin can you check that for iOS, please?
@bruno-garcia for .NOT

**Comment by marandaneto** [comment]
<img width="515" alt="Screenshot 2021-09-01 at 17 20 58" src="https://user-images.githubusercontent.com/5731772/131698923-38c245a8-3625-40e5-9efd-a7dcee198d42.png">

**Comment by philipphofmann** [comment]
We don't put the tags to the trace; we only put them directly to the event.

```json

{
  "event_id": "b775c09d9d0e4c42a3f8283fbb097799",
  // other properties
  "tags": [
    [
      "device.family",
      "macOS"
    ]
	// more tags
  ],
  "contexts": {
	// ...
    "trace": {
      "trace_id": "245103f88b334c83948f395bfb71eb8d",
      "span_id": "41c9903380a94edc",
      "op": "some operation",
      "status": "unknown",
      "sampled": "true",
      "start_timestamp": 1630565379.072324,
      "timestamp": 1630565379.652351,
      "type": "trace"
    }
  },
  // ...
}

```

**Comment by marandaneto** [comment]
@philipphofmann are you sure?

see https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentrySpanContext.m#L78-L90

**Comment by philipphofmann** [comment]
Ups sorry, I was mistaken. You are right. We put them in the wrong place. Will create an issue.

**Comment by maciejwalkowiak** [comment]
@marandaneto in the docs, it says that:

> A Transaction has to have a specific contexts.trace entry that contains data from the Span.

and then if you scroll below `status`, you'll find `tags`:

> Optional. A map or list of tags for this event. Each tag must be less than 200 characters.

**Comment by marandaneto** [comment]
@maciejwalkowiak `contexs.trace` isn't the same as the span, actually, `contexs.trace` should not even be of the type `SpanContext` but rather `TraceContext` which would be a type with only the needed fields as described above

**Comment by maciejwalkowiak** [comment]
Perhaps docs are unclear then. IMO, it clearly states that tags is a part of `transaction.contexts.trace`

**Comment by marandaneto** [comment]
yep, docs aren't clear, could be improved, but look at https://develop.sentry.dev/sdk/event-payloads/transaction/#anatomy

> A Transaction must also have a contexts.trace (which contains some data of the Span) and some other properties that will be covered in the next section.

which contains some data of the Span, but not everything
