### ISSUE TITLE
Expose "max json payload size" in the SDK

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-java#1695]
_Platform:_
- [x]  Android

The version of the SDK:
**5.1.2**

---
https://github.com/getsentry/sentry-java/issues/910 was closed with no action taken.  I think this is the wrong decision but one of the comments mentioned that the max payload size can change over time.  

I have [code](https://github.com/getsentry/sentry-java/issues/910#issuecomment-644334854) in my app that trims breadcrumbs to get the payload under the required size, but I'm currently hardcoding the max payload size as 200kb.  Please expose a constant or a function or something that I can call to get this value from the SDK.

**Comment by bruno-garcia** [comment]
The max payload size is defined by Sentry, not the SDK. So if you're hitting a Sentry 9 on prem it'll be one thing and SaaS, another.

You can find the sizes documented here:
https://docs.sentry.io/product/relay/options/#size-limits

Including:
```
limits.max_event_size
String, default: 1MiB
..
limits.max_envelope_size
String, default: 50MiB
```

**Comment by marandaneto** [comment]
@edenman

> #910 was closed with no action taken

the max. payload was increased from 200kb to 1 mb which is 5x times more, the Sentry SDK does not have the ability of loading configurations on start-up, since this depends on the Server and not the SDK, exposing a constant wouldn't work.
