### ISSUE TITLE
Add allowList for the `tracestate` header

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1697]
related to https://github.com/getsentry/sentry-java/pull/1683
reason is https://github.com/getsentry/develop/issues/425

cc @bruno-garcia 

it should be a List in the SentryOptions with an experimental annotation

**Comment by marandaneto** [comment]
@brustolin we'd need that on https://github.com/getsentry/sentry-cocoa/pull/1291 too, we need to align naming and so on

**Comment by lobsterkatie** [comment]
> reason is getsentry/develop#425

The PII part or the incorrect data part? Can you expand upon this a little?

**Comment by marandaneto** [comment]
ups, the PII part, we don't want to send the `tracestate` that may contain PII data when the user is making an API call, that's why we'd like to introduce an allow list that only sends that info if the target URL is in the allow list, that's the reason IIRC, correct me if I am wrong @bruno-garcia

**Comment by lobsterkatie** [comment]
Ah, got it. The equivalent to JS's `tracingOrigins` option.

Thanks.

**Comment by marandaneto** [comment]
its prob a dup of https://github.com/getsentry/sentry-java/issues/1585 then
in case we want to reuse the same list, wdyt @bruno-garcia ?

**Comment by maciejwalkowiak** [comment]
So I am naming this new property `tracingOrigins`. Unlike Javascript, I guess it should not have `['localhost', /^\//]` as a default value. 

What is the expected behavior if no tracing origins are set? Attach headers to every request, or do not attach headers to any request.

If the latter, this would be a breaking change.

**Comment by marandaneto** [comment]
I'd say if it's empty, send it to every request, and it's up to the user either to decide to add just a specific URL or not, otherwise, it'd not be scalable to the final user adding a new entry to `tracingOrigins` in case they want everything but they now have a new external call.

**Comment by bruno-garcia** [comment]
> I'd say if it's empty, send it to every request, and it's up to the user either to decide to add just a specific URL or not, otherwise, it'd not be scalable to the final user adding a new entry to `tracingOrigins` in case they want everything but they now have a new external call.

I agree. It's important to make this very clear in the docs
