### ISSUE TITLE
Should not capture unfinished transaction

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1704]
https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Hub.java#L547-L554

since we don't return if the transaction isn't finished, it still tries to capture and gets dropped by the server probably.

**Comment by maciejwalkowiak** [comment]
Practically it cannot happen - unless someone creates `SentryTransaction` manually and calls `captureTransaction` manually - it's a left over from the first performance implementation.

How about - we remove this check and `isFinished` method from `SentryTransaction`, and throw from `SentryTransaction` constructor if `SentryTracer#timestamp` is `null`?

**Comment by marandaneto** [comment]
that would be a breaking change since it could crash in case somebody does it, whats about just doing an `else if` after the `isEnabled` check, log it and return?

**Comment by maciejwalkowiak** [comment]
Both `SentryTransaction` and `captureTransaction` are annotated with `ApiStatus.Internal` - so it will break only those who went too far.

Doing `else if` is an easy way out, but also a lost opportunity so clean it up.

**Comment by marandaneto** [comment]
the problem is that `isFinished` is used for some other things (eg feature `waitForChildren`), so we can't remove it.
@bruno-garcia opinions?
