### ISSUE TITLE
using SentryTracingConfiguration with Sentry.init throws exception

### ISSUE THREAD

**Issue by bhavayAnand9** [getsentry/sentry-java#1715]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [x]  Spring -> If yes, which version? Spring 5.1.2

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [x]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**5.1.2**

---
I have the following issue:
How to import `SentryTracingConfiguration` without using `@EnableSentry` annotation & rather use `Sentry.init`.
If I add `SentryTracingConfiguration.class` in my `@imports` & use `Sentry.init` in `PostConstruct`, application do not boot up & throws `NoSuchBeanException`'s

I need `SentryTracingConfiguration` to use sentry spring annotations `@StartSpan` & `@StartTransaction`

adding `@EnableSentry` fix that but I want to use Sentry.init as I find it more flexible for some of my use cases like deducing dsn at runtime, setting beforeSend callback, setting tags etc
I didn't find anything in docs about how to do these things when using `@EnableSentry` annotations

The description goes here ...

**Steps to reproduce:**
- Step
```
@Import({SentryTracingConfiguration.class})
class SentryConfig {
  @PostConstruct
  fn init() { ... sentry.init()...}
}
```
throws exceptions & app do not boot up

```
@Import({SentryTracingConfiguration.class})
@EnableSentry(dsn)
class SentryConfig {

}
```
no issue works perfectly

tried adding both, & the app stops reporting exceptions

in EnableSentry.java file, it mentions
```
creates bean of type SentryOptions
registers io.sentry.IHub for sending Sentry events
registers SentryExceptionResolver to send Sentry event for any uncaught exception in Spring MVC flow.
```

Is it possible to do these manually, do we have a code sample that I can refer to?

Thanks

**Comment by maciejwalkowiak** [comment]
I assume you are using plain Spring, not Spring Boot, right? Tracing beans depend on `IHub`. Try creating a bean like:

```
@Bean
IHub hub() {
  return HubAdapter.getInstance();
}
```

If it does not help, please paste whole stack trace with exception.

**Comment by bhavayAnand9** [comment]
Thanks @maciejwalkowiak 
that was it!
