### ISSUE TITLE
Fragments are not listing in Transactions in sentry.io performance Tab

### ISSUE THREAD

**Issue by sraRnd** [getsentry/sentry-java#1729]
### Environment

Android

Which SDK and version?
 implementation 'io.sentry:sentry-android:5.1.2'
    implementation 'io.sentry:sentry-android-fragment:5.1.2'

### Steps to Reproduce
i have added 
Sentry.configureScope(scope -> {
                            scope.setContexts("Basic Antigen", "Form Data Submitted");
                            scope.setTag("Basic Antigen", "Form Data Submitted");
                        });
 In fragment but on sentry.io performance tab my activities are listed in transactions section but my fragments are not listed there ,as my fragments are showing in breadcrumbs. my 80% of app is based on fragments. and i need to show fragments in transaction

picture is attached below. please can you help in doing so. that will be great. thanks waiting for response

![sentry](https://user-images.githubusercontent.com/73343243/133669570-463e041d-490e-49f3-a2a5-8b5c604f41f0.jpg)
### Actual Result

![image](https://user-images.githubusercontent.com/73343243/133669464-a2d56aee-a082-4870-8bcf-6806684146cc.png)

**Comment by romtsn** [comment]
As per [documentation](https://docs.sentry.io/platforms/android/performance/instrumentation/automatic-instrumentation/#androids-fragment-instrumentation)
> Android's Fragment Instrumentation depends on having an active transaction bound to the scope, and ideally it'd be used along with Android's Activity Instrumentation, which starts a transaction and binds it to the scope automatically

Fragments do not create transactions, but spans, which are being bound to an active transaction, if there's one. So if you would like to have transactions for Fragments you'd need to do it manually via `startTransaction/finish` ([docs](https://docs.sentry.io/platforms/android/performance/instrumentation/custom-instrumentation/))

**Comment by marandaneto** [comment]
what @romtsn said ^ we can't have a transaction per Fragment since we only allow a single transaction set in the Scope and a screen may have multiple fragments, it's a limitation of our tooling for now (having multiple transactions bound to the Scope), but nothing holds you creating your own transactions manually using the custom instrumentation
