### ISSUE TITLE
Spring @Async + @SentrySpan duration

### ISSUE THREAD

**Issue by micopiira** [getsentry/sentry-java#1730]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [x]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**5.1.2**

---
I have the following issue:

Would it be possible to implement reporting "correct" duration for async method spans?

Lets say I have method like this:

```
@Async
@SentrySpan
public CompletableFuture<Void> doSomethingAsync() {
    return CompletableFuture.runAsync(() -> {
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    });
}
```

then Sentry will report duration of 0ms and 10000ms missing instrumentation after. I understand why this happens, however would it be possible to detect such cases in the `SentrySpanAdvice` and finish the span once the returned `Future` completes?

**Comment by marandaneto** [comment]
@micopiira thanks for reporting.
@maciejwalkowiak is that even possible? if not, we'd ideally document that, so people that use async methods should instrument themselves, as they have control over the async flow.

**Comment by maciejwalkowiak** [comment]
@micopiira thanks for reporting. The easy way to handle it is to change `SentrySpanAdvice` to check the return type of method - we could add callbacks in case of `ListenableFuture` or `CompletableFuture`. But, if this works within the scope of the Spring MVC request, likely filter will finish the transaction before the callback on the future is called. I am not sure yet how this can/should be handled. @micopiira if you have ideas feel free to share :-)

**Comment by micopiira** [comment]
@maciejwalkowiak Since sentry spans cannot be added to a transaction once a transaction has been finished, I guess the only way to model this would be to start a new transaction for the async operation. `@SentryTransaction` won't work here either since it is a no-op we are already inside a transaction.

I guess my best bet would be to do something like this?: (UNTESTED)
       
    @Async
	public CompletableFuture<Void> doSomethingAsync() {
		final SentryTraceHeader sentryTraceHeader = Sentry.getSpan().toSentryTrace();
		return CompletableFuture.runAsync(() -> {
			final ISpan transaction = Sentry.startTransaction(TransactionContext.fromSentryTrace("name", "op", sentryTraceHeader), true);
			try {
				Thread.sleep(10000);
			} catch (final InterruptedException e) {
				transaction.setThrowable(e);
				transaction.setStatus(SpanStatus.INTERNAL_ERROR);
				throw new RuntimeException(e);
			} finally {
				transaction.finish();
			}
		});
	}

**Comment by maciejwalkowiak** [comment]
Ideally, we would finish existing transaction after async method is finished. Creating transaction within transaction is rather suboptimal. I'll get back to you once I figure it out :-)
