### ISSUE TITLE
sentry-java silently fails to deliver event when conflicting Gson class is on the classpath

### ISSUE THREAD

**Issue by antonmos** [getsentry/sentry-java#1733]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [x]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**5.1.1**

---
I have the following issue:
Another library included a copy of `com.google.gson.Gson` class which caused sentry-java to silently fail to deliver the event to sentry. When we enabled the logs, we observed the following:
```
DEBUG: Capturing event: 138d4d2eeb2845acaf8829723001ba8f
INFO: Session is null on scope.withSession
ERROR: Request failed, API returned 400
ERROR: {"detail":"empty envelope"}
```
Using a debugger, we were able to see that NoSuchMethodError was thrown when calling Gson.excluder() method from UnknownPropertiesTypeAdapterFactory.

**Steps to reproduce:**
- See above.

**Actual result:**
- The error was not informative and we had to use a debugger to find the root cause

**Expected result:**
- informative ERROR should have been logged to the Sentry ILogger.

**Comment by marandaneto** [comment]
logging should have stated it's a serialization issue, we have to improve that, thanks.

there's a note in the docs about min. version (Gson) https://docs.sentry.io/platforms/java/#install

**Comment by adinauer** [comment]
Closing as we've vendored GSON in 6.0
