### ISSUE TITLE
GraphQL integration for server side

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1755]
Similar to our Apollo GraphQL integration but for server-side, using the libs:

com.graphql-java:graphql-java and com.graphql-java:graphql-java-spring-boot-starter-webmvc

https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/

**Comment by maciejwalkowiak** [comment]
GraphQL Java Spring integration is going to be deprecated and superseded by https://spring.io/projects/spring-graphql (which is not GA yet). Another popular GraphQL server side component we can consider integrating with is https://netflix.github.io/dgs/ - likely in the future it will use Spring GraphQL under the hood.
