### ISSUE TITLE
App start time is store in span . How can i get the whole start time data in sentry web

### ISSUE THREAD

**Issue by HenryHaoson** [getsentry/sentry-java#1766]
If using transaction to store the start time data，i can see it in performance and get the p95 data。

**Comment by marandaneto** [comment]
<img width="1395" alt="Screenshot 2021-10-15 at 09 04 28" src="https://user-images.githubusercontent.com/5731772/137446015-392fe486-c9d4-423a-bc00-0bef280368f0.png">

The combo boxes Display 1 and Display 2 should give you access from P50 to P99, or am I missing something?

**Comment by HenryHaoson** [comment]
How to i access this page.
