### ISSUE TITLE
Package OkHttp as a jar instead of aar

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1783]
In order to use our OkHttp library with Jetpack Compose on desktop, it must be packaged as a `jar` since it runs on the JVM.

Additionally we could deprecate `sentry-android-okhttp` in favor of `sentry-okhttp` if it doesn't have any Android specific dependency.

**Comment by bruno-garcia** [comment]
Raised the priority to p2 here since our Kotlin Multiplatform SDK is moving forward with JVM support and we could unblock @remcomokveld and other folks who want to take advantage of this. Also it's a low effort.

**Comment by marandaneto** [comment]
If needed, we can have a `sentry-okhttp` and `sentry-android-okhttp` so people don't have to change their dependencies.
Maybe imports will be broken still, but its more straightforward to fix.

**Comment by romtsn** [comment]
Closed by #3005
