### ISSUE TITLE
Print serialised envelopes to the console in debug mode.

### ISSUE THREAD

**Issue by maciejwalkowiak** [getsentry/sentry-java#1792]
In 6.x with new JSON serialization, we do not print serialized objects to the console anymore - which I find very useful during debugging and development.

**Comment by marandaneto** [comment]
@denrase would you like to have a look? 

examples on how it was done https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/GsonSerializer.java#L142-L144

**Comment by denrase** [comment]
Jup, will take a look! 👍

**Comment by bruno-garcia** [comment]
Closed through #1795
