### ISSUE TITLE
Consider using a more accurate ANR tracking implementation

### ISSUE THREAD

**Issue by vibin** [getsentry/sentry-java#1796]
Hi, i'm currently evaluating Bugsnag and Sentry and one of the differences i've observed in the SDK is that Bugsnag uses a SIGQUIT signal handler to get called by OS when ANR occurs, as opposed to Sentry, which uses the watchdog approach.

I have used https://github.com/SalomonBrys/ANR-WatchDog in production before and while it's a useful library, I saw that it reports many false-positives compared to Play Console, especially in case of ANRs in BroadcastReceivers.

SIGQUIT approach is also not perfect, though. It doesn't track background ANRs: https://github.com/bugsnag/bugsnag-android/issues/1377

There's a third approach to track ANRs and Crashlytics' Alpha version seems to be using it (tracks both foreground and background ANRs): [getHistoricalProcessExitReasons](https://developer.android.com/reference/kotlin/android/app/ActivityManager#gethistoricalprocessexitreasons) on Android 11 and above only, sadly.

Any thoughts?

**Comment by bruno-garcia** [comment]
Thanks you for bringing this up. It makes sense and perhaps we should consider an approach for Android 11+ only and keep the current as-is. Additionally, there's the possibility of relying on `SIGQUIT` through our NDK support which will also require some discussions internally.

**Comment by marandaneto** [comment]
I've tested the 3rd option 2y ago and it worked really well, indeed, https://github.com/marandaneto/android-exit-reasons-api-sample
the approach we could take is, enable the watchdog when Android <= 10 and use the new API when Android >= 11.

the new API returns a InputStream tho, so it requires us converting this info into a SentryEvent https://developer.android.com/reference/kotlin/android/app/ApplicationExitInfo#gettraceinputstream

**Comment by marandaneto** [comment]
[sample_anr.txt](https://github.com/getsentry/sentry-java/files/7660702/sample_anr.txt)

**Comment by marandaneto** [comment]
Let's use the new API for Android >= 11 and keep the watch dog approach for back compatibility.

**Comment by marandaneto** [comment]
https://www.amanjeet.me/demystifying-the-anrs-puzzle/

**Comment by marandaneto** [comment]
Update the [docs](https://docs.sentry.io/platforms/android/configuration/app-not-respond/) after doing this, the docs should state the behavior for older and newer OS versions.

**Comment by marandaneto** [comment]
For reference, that's how Android itself does it https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/am/AnrHelper.java
