### ISSUE TITLE
Add sentry-graphql on release-registry and docs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1802]
Related to https://github.com/getsentry/sentry-java/pull/1801
Available since 5.4.0
uncomment https://github.com/getsentry/sentry-java/blob/main/.craft.yml#L42

**Comment by maciejwalkowiak** [comment]
- Craft: https://github.com/getsentry/sentry-java/pull/1803
- Release Registry: https://github.com/getsentry/sentry-release-registry/pull/64
- Docs: TBD

**Comment by maciejwalkowiak** [comment]
Since it GraphQL Java integration covers both exception handling and performance, perhaps it should be a separate dedicated top level guide.

**Comment by marandaneto** [comment]
@maciejwalkowiak what's about similar to Android? as Integrations, See

https://docs.sentry.io/platforms/android/configuration/integrations/
then as a subitem of automatic instrumentation, we mention the integration -> https://docs.sentry.io/platforms/android/performance/instrumentation/automatic-instrumentation/#okhttp-library-instrumentation

**Comment by maciejwalkowiak** [comment]
This would be one option but I think it means we would need to move around more things. For now I've added it to a main section but is shown only for Java, Spring, Spring Boot and Servlet.
