### ISSUE TITLE
Replace SDKs `catch (Exception e)` to `catch (Throwable e)`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1806]
SDK should not crash the finals App, but rather swallow and log it.
this would avoid issues such as https://github.com/getsentry/sentry-java/pull/1800

Context: https://github.com/getsentry/sentry-java/pull/1800#discussion_r747575295

**Comment by philipphofmann** [comment]
Make sure to log out when we swallow a Throwable. We still need to find out how to log out.

**Comment by bruno-garcia** [comment]
The PR #1812 partially addresses this. See PR description for details.
Goal: Changes all Java catch `Exception` to `Throwable` so we avoid crashes on Unity that should have been suppressed.

For this issue I suggest we add a linter. We we avoid adding `catch Exception` again in the future. The linter should warn that throwable should be used to suppress all errors instead.
