### ISSUE TITLE
No Full Distributed Performance Tracing unless duplicate calls

### ISSUE THREAD

**Issue by arysharifian** [getsentry/sentry-java#1808]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [X]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [X]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [X]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**5.3.0**

---
I have the following issue:
In order to get a full distributed performance trace, I need to call the function twice. For example, let's say I have a frontend and a backend, and I want a full distributed performance trace starting from the frontend and including the backend call. I need to call the backend twice before I get a completed distributed trace.

If I call the backend once, I get a performance trace of only the frontend. Which looks something like the following:

![Screen Shot 2021-11-16 at 11 21 24 AM](https://user-images.githubusercontent.com/88000193/142024107-075c3e65-4df1-4d09-8e15-41078caf0938.png)

Here is the corresponding frontend code:
```
sentry_sdk.init(
    dsn="<my_DSN>",
    traces_sample_rate=1.0,
    debug=True,
)

with start_transaction(op = "Purchase PIN", name="Client Request-Redwolf-SDK"):
    with sentry_sdk.start_span(op ="auth token") as span:
        new_token = get_jwt_token()
        span.finish()
    with sentry_sdk.start_span(op ="create PIN") as span:
        create_pin(new_token)
        span.finish()
```

If I call the backend functions twice, then I get a full performance trace:

![Screen Shot 2021-11-16 at 11 25 26 AM](https://user-images.githubusercontent.com/88000193/142024753-839e7ef4-dfad-461e-97d8-2d3a0bae4be0.png)

Here is the corresponding code:
```
sentry_sdk.init(
    dsn="<my_DSN>",
    traces_sample_rate=1.0,
    debug=True,
)

with start_transaction(op = "Purchase PIN", name="Client Request-Redwolf-SDK"):
    with sentry_sdk.start_span(op ="auth token") as span:
        new_token = get_jwt_token()
        span.finish()
    with sentry_sdk.start_span(op ="create PIN") as span:
        create_pin(new_token)
        span.finish()

new_token = get_jwt_token()
create_pin(new_token)
```

**Steps to reproduce:**
Call the backend functions once.

**Actual result:**
Limited performance tracing.

**Expected result:**
Full distributed performance tracing.

**Comment by arysharifian** [comment]
I am seeing this in the logs:
`sentry DEBUG: Transaction was dropped due to sampling decision.`

**Comment by arysharifian** [comment]
I am getting this error WHEN IT WORKS:


INFO: Initializing SDK with DSN: '<my_DSN>'
--
  | 2021-11-16T12:43:24.356-05:00 | INFO: No outbox dir path is defined in options.
  | 2021-11-16T12:43:24.376-05:00 | INFO: GlobalHubMode: 'false'
  | 2021-11-16T12:43:24.376-05:00 | DEBUG: UncaughtExceptionHandlerIntegration removed.
  | 2021-11-16T12:43:24.377-05:00 | INFO: Closing SentryClient.
  | 2021-11-16T12:43:24.496-05:00 | DEBUG: Hint is not Retryable
  | 2021-11-16T12:43:24.498-05:00 | ERROR: Envelope submission failed
  | 2021-11-16T12:43:24.498-05:00 | java.lang.IllegalStateException: Sending the event failed.
  | 2021-11-16T12:43:24.498-05:00 | java.lang.IllegalStateException: Sending the event failed.
  | 2021-11-16T12:43:24.498-05:00 | at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:229)
  | 2021-11-16T12:43:24.498-05:00 | at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/java.lang.Thread.run(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at io.sentry.transport.HttpConnection.createConnection(HttpConnection.java:145)
  | 2021-11-16T12:43:24.498-05:00 | at io.sentry.transport.HttpConnection.send(HttpConnection.java:150)
  | 2021-11-16T12:43:24.498-05:00 | at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:210)
  | 2021-11-16T12:43:24.498-05:00 | ... 6 more
  | 2021-11-16T12:43:24.498-05:00 | Caused by: java.io.EOFException: SSL peer shut down incorrectly
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
  | 2021-11-16T12:43:24.498-05:00 | ... 16 more
  | 2021-11-16T12:43:24.498-05:00 | DEBUG: Shutting down
  | 2021-11-16T12:43:24.499-05:00 | DEBUG: UncaughtExceptionHandlerIntegration enabled: true
  | 2021-11-16T12:43:24.515-05:00 | DEBUG: UncaughtExceptionHandlerIntegration installed.
  | 2021-11-16T12:43:24.516-05:00 | DEBUG: ShutdownHookIntegration installed.

**Comment by arysharifian** [comment]
I've isolated the error to backend sentry SDK initialization:
```
Sentry.init { options ->
            options.dsn = "https://<chars>@<slightly_fewer_chars>.ingest.sentry.io/<chars>";
            options.setDebug(true);
            options.tracesSampleRate = 1.0
        }
```

**Comment by arysharifian** [comment]
It might be important to note that I am using the same project DSN for both the frontend as the backend

**Comment by arysharifian** [comment]
Basic question: how do we initialize separate Sentry SDK (frontend and backend) for Distributed Tracing?

**Comment by arysharifian** [comment]
This is the java version running in the backend:
```
Runtime
Java 11 (Corretto)
```

**Comment by marandaneto** [comment]
> It might be important to note that I am using the same project DSN for both the frontend as the backend

that's not a problem

**Comment by marandaneto** [comment]
> Basic question: how do we initialize separate Sentry SDK (frontend and backend) for Distributed Tracing?

not sure if I understand the question, if one application is Java, and the other application is Python, the init. is just about the same, `dsn`, `tracesSampleRate` and that's it

**Comment by marandaneto** [comment]
> This is the java version running in the backend:
> 
> ```
> Runtime
> Java 11 (Corretto)
> ```

no issues about that

**Comment by marandaneto** [comment]
@arysharifian can you provide a minimal reproducible example on Github with your frontend and backend code? it looks like you are not using the Sentry SDK correctly, the logs say that you're either calling `Sentry.init` multiple times or manually calling `Sentry.close`, something like that

**Comment by arysharifian** [comment]
Do I need to call Sentry init twice? Once for frontend and once for backend if I am using the same DSN? What if I am using different DSN?

**Comment by arysharifian** [comment]
I think I've resolved the issue. The sentry sdk was initialized in the body of the AWS lambda function. When I called the backend function, it would try to reinitialize an already initialized sdk which caused conflicts and forced the client to close. But once I moved the backend sentry SDK initialization outside the function and inside the handler, the sentry is only initialized once when the lambda function container is deployed.  This seems to have solved the problem.

This might have also helped:
https://github.com/getsentry/sentry-java/issues/1023

**Comment by marandaneto** [comment]
> Do I need to call Sentry init twice? Once for frontend and once for backend if I am using the same DSN? What if I am using different DSN?

no, only once, you can only use 1 DSN per application/process, as I remember, you have a python and java application, both can use the same DSN, its fine

**Comment by marandaneto** [comment]
> I think I've resolved the issue. The sentry sdk was initialized in the body of the AWS lambda function. When I called the backend function, it would try to reinitialize an already initialized sdk which caused conflicts and forced the client to close. But once I moved the backend sentry SDK initialization outside the function and inside the handler, the sentry is only initialized once when the lambda function container is deployed. This seems to have solved the problem.
> 
> This might have also helped: #1023

yep, we've talked about it during our call as well, glad that it helped.
