### ISSUE TITLE
start transaction if none active in the scope for fragment integration

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1810]
since https://github.com/getsentry/sentry-java/blob/main/sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt#L136 only creates spans if there is an active transaction, many apps are using single app activity (eg with navigation controller) and most of the time there will be no active transaction since automatic transactions are only created by the activity integration for now

**Comment by marandaneto** [comment]
sounds like an easy win, maybe even a further discussion, does it make sense to create a transaction always when there's an integration trying to create a span out of it but there's no active in the scope? (eg okhttp, apollo, etc...)

**Comment by marandaneto** [comment]
the downside is that if activity with 4 fragments, 4 fragments would create a transaction, which one binds to the scope?
the other side is naming, that happens with span already, they could be minified and naming is not useful, see https://github.com/getsentry/sentry-java/issues/1734 or https://github.com/getsentry/sentry-java/issues/1086

**Comment by marandaneto** [comment]
we decided to add an option to the ctor of the integration that let the user decide if we should create transactions if there's none active in the scope, this is enabled by default.
the very first fragment creates a transaction and binds it to the scope.
hierarchy might be wrong but the timeline is correct, the same trade-off as JS.

we can try this out and check if that makes sense as a Draft.

**Comment by markushi** [comment]
Let's revisit this once the concept for starfish is fully defined.

**Comment by stefanosiano** [comment]
closing as useless with span-only
