### ISSUE TITLE
Timeout for `waitForChildren` feature

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1811]
Could avoid issues like https://github.com/getsentry/sentry-java/issues/1787

**Comment by marandaneto** [comment]
reminder to create an issue for iOS.

we could have a single timer for the transaction that gets reset when a new span has been created, so we avoid the overhead of having a timer per span.
this timeout in millis should be configurable via SentryOptions

**Comment by romtsn** [comment]
Closing as it's actually implemented with UI transactions (idle timeout)
