### ISSUE TITLE
Error executing post release script from branch instead of main branch

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1817]
› Trying to find merge target:                                                                                                                                                                                                10:57:17
› Checking out merge target branch: 6.x.x                                                                                                                                                                                     10:57:17
› Merging release/6.0.0-alpha.1 into: 6.x.x                                                                                                                                                                                   10:57:17
› Deleting the release branch: release/6.0.0-alpha.1                                                                                                                                                                          10:57:22
ℹ Removed the remote branch: "release/6.0.0-alpha.1"                                                                                                                                                                          10:57:23
✔ Version 6.0.0-alpha.1 has been published!                                                                                                                                                                                   10:57:23
ℹ Running the post-release command...                                                                                                                                                                                         10:57:23

 ERROR  Process "/bin/bash" errored with code 1                                                                                                                                                                               10:57:24

STDOUT: /bin/bash: Your branch is up to date with 'origin/main'.
/bin/bash: 

STDERR:/bin/bash: +++ dirname scripts/post-release.sh
/bin/bash: ++ cd scripts
/bin/bash: ++ pwd
/bin/bash: + SCRIPT_DIR=/Users/user/Github/sentry-java/scripts
/bin/bash: + cd /Users/user/Github/sentry-java/scripts/..
/bin/bash: + OLD_VERSION=
/bin/bash: + NEW_VERSION=6.0.0-alpha.1
/bin/bash: + git checkout main
/bin/bash: Switched to branch 'main'
/bin/bash: + GRADLE_FILEPATH=gradle.properties
/bin/bash: + sed -i '' 's/# Changelog/# Changelog\n\n## Unreleased/' CHANGELOG.md
/bin/bash: + VERSION_NAME_PATTERN=versionName
/bin/bash: ++ awk /versionName/ gradle.properties
/bin/bash: ++ egrep -o '[0-9].*$'
/bin/bash: + version=5.4.2-SNAPSHOT
/bin/bash: ++ awk /versionName/ gradle.properties
/bin/bash: ++ egrep -o '[0-9]+$'
/bin/bash: + version_digit_to_bump=
/bin/bash: 

  
  STDOUT: /bin/bash: Your branch is up to date with 'origin/main'.
  /bin/bash:
  
  
  STDERR:/bin/bash: +++ dirname scripts/post-release.sh
  /bin/bash: ++ cd scripts
  /bin/bash: ++ pwd
  /bin/bash: + SCRIPT_DIR=scripts
  /bin/bash: + cd scripts/..
  /bin/bash: + OLD_VERSION=
  /bin/bash: + NEW_VERSION=6.0.0-alpha.1
  /bin/bash: + git checkout main
  /bin/bash: Switched to branch 'main'
  /bin/bash: + GRADLE_FILEPATH=gradle.properties
  /bin/bash: + sed -i '' 's/# Changelog/# Changelog\n\n## Unreleased/' CHANGELOG.md
  /bin/bash: + VERSION_NAME_PATTERN=versionName
  /bin/bash: ++ awk /versionName/ gradle.properties
  /bin/bash: ++ egrep -o '[0-9].*$'
  /bin/bash: + version=5.4.2-SNAPSHOT
  /bin/bash: ++ awk /versionName/ gradle.properties
  /bin/bash: ++ egrep -o '[0-9]+$'
  /bin/bash: + version_digit_to_bump=
  /bin/bash:
  
  at Iht (/Users/user/.config/yarn/global/node_modules/@sentry/craft/dist/craft:623:320781)
  at d (/Users/user/.config/yarn/global/node_modules/@sentry/craft/dist/craft:627:467)
  at ChildProcess.<anonymous> (/Users/user/.config/yarn/global/node_modules/@sentry/craft/dist/craft:627:762)
  at ChildProcess.emit (node:events:390:28)
  at ChildProcess.emit (node:domain:475:12)
  at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

probably because https://github.com/getsentry/sentry-java/blob/main/scripts/post-release.sh#L14
we'd need to change to the target branch probably, in this case, `6.x.x` probably
latest Craft, 0.27.2, running locally, since the maven target does not support https://github.com/getsentry/publish yet

**Comment by marandaneto** [comment]
@iker-barriocanal how do you do that in other repos?

**Comment by iker-barriocanal** [comment]
This only happens on release branches and can be solved by running the post-release script with the current and new versions as arguments. Not prioritized at the moment.

**Comment by marandaneto** [comment]
@iker-barriocanal fine but this is a craft issue right, should I transfer this issue to the craft repo?

**Comment by marandaneto** [comment]
@iker-barriocanal can you point me where this should be addressed, maybe I look myself since releases now are a pain.

**Comment by iker-barriocanal** [comment]
@marandaneto I don't know where exactly this should be addressed, but you can read the [post-release script conventions](https://github.com/getsentry/craft#post-release-script-conventions).

**Comment by kamilogorek** [comment]
Tbh I dont understand what this issue is about. We need a failing release to get better logs.

**Comment by marandaneto** [comment]
@kamilogorek If you are releasing a version from a release branch, e.g.

`git checkout my_release_branch`
`craft prepare 1.0.0`
`craft publish 1.0.0`

During `craft publish` it fails in the post-release script since the script does `git checkout main`, but it should be rather `git checkout my_release_branch`, the script is unaware of which branch it should checkout and it does `main`, always.
