### ISSUE TITLE
Ending Subspan Prematurely Ends Transaction

### ISSUE THREAD

**Issue by arysharifian** [getsentry/sentry-java#1823]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [X]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [X]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [X]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**5.3.0**

---
I have the following issue:

For some reason, when I end a subspan, the entire transaction ends, and the remainder of the subspans are not published to Sentry.

**Steps to reproduce:**
```
fun startSpan(operationName: String, activeSentryTraceHeader: Boolean, transaction:ISpan?): ISpan? {
        if (activeSentryTraceHeader){
            return transaction?.startChild(operationName)
        }
        return null
    }

fun endSpan(activeSentryTraceHeader: Boolean, span: ISpan?){
        if (activeSentryTraceHeader){
            if (span != null) {
                span.finish()
            }
        }
    }
```

This is the function I am trying trace:
```
fun setThing(){
        //pinUtils.startSpan("op", activeSentryTrace, transaction)
        val result = myClass.doThis()
        //pinUtils.endSpan(activeSentryTrace, transaction)
        return result
    }
```

The function, setThing is my first span before I trace multiple spans that all exist within a `try/catch` block.

**Actual result:**
<img width="695" alt="Screen Shot 2021-11-30 at 11 42 25 AM" src="https://user-images.githubusercontent.com/88000193/144132618-49c8174e-d1da-4e6f-8c13-6ca64f0c83fc.png">

Also note that I get a "deadline_exceeded" status for "setThing" span.

**Expected result:**

something like this but with "setThing" included at the very top:

<img width="707" alt="Screen Shot 2021-11-30 at 11 44 26 AM" src="https://user-images.githubusercontent.com/88000193/144132866-3f3ff656-273c-4ab5-a6bf-ca7994032cde.png">

**Comment by marandaneto** [comment]
`pinUtils.startSpan("op", activeSentryTrace, transaction)` returns an object, which is the child span, you should call `finish` in this object.
`pinUtils.endSpan(activeSentryTrace, transaction)` means you are calling `finish` in the transaction and not in the child span.

a proper way would be:

```
// start child
val mySpan = pinUtils.startSpan("op", activeSentryTrace, transaction)
// finish child (see mySpan)
pinUtils.endSpan(activeSentryTrace, mySpan)
// finish transaction
pinUtils.endSpan(activeSentryTrace, transaction)
```
