### ISSUE TITLE
Create spans from the transaction root instead of latest active span

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1827]
We've decided that automatically created spans should be a child of the root transaction.
It'll be a flat list of spans but the timeline is still correct due to the timestamps.

On Cocoa, https://github.com/getsentry/sentry-cocoa/issues/1215 was already closed to keep creating automatic spans from the root.

This is only necessary for Mobile integrations since they have the concept of `singleHub`, backend instrumentation does not require that since each thread has its own hub/scope.

**Comment by marandaneto** [comment]
We don't think its a breaking change since this public API does not change, the chart timeline does not change, but only the hierarchical view of the spans.

**Comment by marandaneto** [comment]
cc @bruno-garcia

**Comment by marandaneto** [comment]
example: https://github.com/getsentry/sentry-java/blob/main/sentry-android-fragment/src/main/java/io/sentry/android/fragment/SentryFragmentLifecycleCallbacks.kt#L134-L140

**Comment by markushi** [comment]
Closing this one in favor of https://github.com/getsentry/sentry-java/issues/1828
