### ISSUE TITLE
Implement local scope, which is a method parameter for the capture methods

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1829]
Similar to Dart/Flutter https://github.com/getsentry/sentry-dart/pull/463/files

**Comment by bruno-garcia** [comment]
Recently added in .NET: https://github.com/getsentry/sentry-dotnet/pull/1412

**Comment by adinauer** [comment]
Planning not to change `.withScope` at all. These new overloads should implement the **local scope** concept so the scope can be changed for one invocation only without affecting others especially in global hub mode.

Only planning to add overloads to
* `captureMessage`
* `captureException`
* `captureEvent`

**Comment by adinauer** [comment]
@bruno-garcia @marandaneto should we deprecate `withScope` as this is basically the less bug prone version of it? It's been removed in .NET.

**Comment by marandaneto** [comment]
https://develop.sentry.dev/sdk/unified-api/
`Hub::with_scope(callback)` is technically optional, but not deprecated, I'm fine deprecating it tho, let's see what @bruno-garcia says.

**Comment by adinauer** [comment]
I don't see an easy way to fix it as we'd have to pass the `Hub` to the callback and devs would need to use that instead of `Sentry.capture` etc. So even if we did that it could still be a source of bugs / wrong info.

**Comment by marandaneto** [comment]
I've discussed this with @bruno-garcia and this will go to v7 to unblock v6.

**Comment by adinauer** [comment]
Let's deprecate it in v6 and remove with v7. I've opened an issue here https://github.com/getsentry/sentry-java/issues/2083
