### ISSUE TITLE
CWE-250 | Execution with Unnecessary Privileges Improper

### ISSUE THREAD

**Issue by mr-africa** [getsentry/sentry-java#1833]
Hello again!

My react native android app was audited by some security company. And they have found one more issue in sentry-java codebase. 

(I've reported their previous issue here #1830  )

They found problem here:
https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/util/RootChecker.java

I'm not sure is it real issue or not. And how to fix it. They gave strange description. Could you check it please.

```
CWE-250 | Execution with Unnecessary Privileges Improper

❖ Severity 
Medium

❖ Description
The mobile app may request root (Super User) privileges to performs an operation at a privilege level that is higher than the minimum level required, which may create new weaknesses or amplifies the consequences of other weaknesses.

❖ Impact
The extra privileges, such as root or Administrator, can lead to new weaknesses since if enforced it can disable the normal security checks being performed by the operating system or surrounding environment and other pre-existing weaknesses can turn into security vulnerabilities if they occur while operating at raised privileges.

❖ Remediation
Run the mobile app using the lowest privileges that are required to accomplish the necessary tasks. If possible, create isolated accounts with limited privileges that are only used for a single task. That way, a successful attack will not immediately give the attacker access to the rest of the application or its environment. For example, database applications rarely need to run as the database administrator, especially in day-to-day operations.
```

  
![image](https://user-images.githubusercontent.com/3126299/145376750-ce489147-f059-4e7c-aba0-ab217301a2f2.png)

**Comment by marandaneto** [comment]
@mr-africa that's indeed true but we only use it to detect if the device is rooted or not, we don't execute any other command, this is very useful to find out or debug issues with rooted devices, I don't think we can fix this one.
ideas?

**Comment by mr-africa** [comment]
@marandaneto I don't know what we can do here. I suppose we should close the issue.

**Comment by marandaneto** [comment]
> @marandaneto I don't know what we can do here. I suppose we should close the issue.

report as a false positive to the security team, the SDK is open-source, they can inspect and validate that.
