### ISSUE TITLE
if `transaction.finish` was called, we should not allow calling `startChild`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1840]
https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryTracer.java#L134-L157

we'd need to check as we do on `finish` https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryTracer.java#L209

@philipphofmann confirm on iOS, this could avoid concurrent problems like https://github.com/getsentry/sentry-dart/issues/662

**Comment by marandaneto** [comment]
@bruno-garcia worth checking .NET too

**Comment by philipphofmann** [comment]
@marandaneto, what do you exactly mean by not allowing to call `startChild`?

**Comment by marandaneto** [comment]
@philipphofmann If the transaction is finished, we should not allow adding one more child to the children list, which means, we've to check if the transaction is already finished before executing the `startChild` method or bail at the very beginning.

**Comment by philipphofmann** [comment]
Yes, but was does not allowing actually do? Does the transaction return a no-op child? Does it throw an exception?

**Comment by marandaneto** [comment]
> Yes, but was does not allowing actually do? Does the transaction return a no-op child? Does it throw an exception?

I'd say it returns a no-op child, but the issue has a `needs discussion` tag, that's open.

**Comment by marandaneto** [comment]
We're gonna return NoOp if the transaction was already finished, similar to implemented Dart solution, We should also log out when that happens, so the user knows why and what to do, which is also done for every setter on the span, e.g. setData, etc...
