### ISSUE TITLE
Cache Envelope will be deleted when the app restart but the server‘s response is still not successful

### ISSUE THREAD

**Issue by limonzet** [getsentry/sentry-java#1847]
_Platform:_
- [yes]  Android -> If yes, which Device API (and compileSdkVersion = 31/targetSdkVersion = 31/Build tools = 31) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [yes ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ yes]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ yes]  Yes -> 7.0.3
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ yes]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**5.4.3**

---
I have the following issue:

Cache Envelope will be deleted when the app restart but the server‘s response is still not successful.

**Steps to reproduce:**
- App crashed. The envelope will be stored in the directory
- App restart. But the sentry server response 404
 
**Actual result:**
- The envelope file is deleted. However, it's never sent to the server successfully.

**Expected result:**
- The envelope file won't be deleted when it's never sent to the server successfully.

**Comment by marandaneto** [comment]
@limonzet We don't retry to do send envelopes if something went wrong, that's intentional (unless you've reached the rating limit).
The problem here is the API returning 404, are you using sentry.io or selfhosted?

**Comment by limonzet** [comment]
> @limonzet We don't retry to do send envelopes if something went wrong, that's intentional (unless you've reached the rating limit). The problem here is the API returning 404, are you using sentry.io or selfhosted?
It is self-hosted. But if the server is responded with another code, all the crash info in local will be lost. Nobody can guarantee that the server is always running established, is that right?

**Comment by marandaneto** [comment]
> > @limonzet We don't retry to do send envelopes if something went wrong, that's intentional (unless you've reached the rating limit). The problem here is the API returning 404, are you using sentry.io or selfhosted?
> 
> It is self-hosted. But if the server is responded with an error code, all the crash files in local will be deleted. It means we lost some crash info. Nobody can guarantee that the server is always running established, is that right?

that's correct, we don't retry only if the server returns something (e.g. an API error), if there's no connection, we do retry, that's how it should work.
