### ISSUE TITLE
TracesSamplerCallback not called in WebFlux

### ISSUE THREAD

**Issue by volvotrax** [getsentry/sentry-java#1856]
_Platform:_
Microservices architecture.
Some microservices are built with Spring Webflux, others with Spring MVC
- [x]  Java 11
- [x]  Spring Boot 2.6.1

_IDE:_
- [x] IntelliJ IDEA 2021.3 (Ultimate Edition)

_Build system:_
- [x]  Maven 3.6.3

_Platform installed with:_
- [x] Maven Central

The version of the SDK:
**5.5.2**

---
I have the following issue:

I set a `TracesSamplerCallback`. It's called in servlet implementations but not in our reactive microservices.

**Steps to reproduce:**
```
@ConditionalOnProperty(name = { "sentry.dsn" })
@Component
public class SentryTracesSamplerCallback implements SentryOptions.TracesSamplerCallback {

    @Override
    public Double sample(@NotNull SamplingContext context) {
        HttpServletRequest request = (HttpServletRequest) context.getCustomSamplingContext().get("request");
        String url = request.getRequestURI();

        if ("/actuator".equals(url)) {
            // The health check endpoint is just noise - drop all transactions
            return 0d;
        }
        // Rollback to default sample rate
        return null;
    }
}
```

**Actual result:**
- In servlet context, all is going well, I set a breakpoint and I see that the callback is called.  
- In Spring WebFlux, the callback is not called.

**Expected result:**
- The callback should be called when using Spring WebFlux too.

**Comment by maciejwalkowiak** [comment]
@volvotrax we do not support the performance feature in Webflux (yet) - see https://github.com/getsentry/sentry-java/issues/1807. So far we provide only experimental support for exception handling, but it comes with some issues (https://github.com/getsentry/sentry-java/issues/1790)

**Comment by maciejwalkowiak** [comment]
@marandaneto I think this one can be closed as duplicate of https://github.com/getsentry/sentry-java/issues/1807

**Comment by volvotrax** [comment]
ok, thanks for your quick answer.
Could you please update the Sentry documentation about that?  
[https://docs.sentry.io/platforms/java/guides/spring-boot/webflux/](https://docs.sentry.io/platforms/java/guides/spring-boot/webflux/)
