### ISSUE TITLE
TransactionFinishedCallback

### ISSUE THREAD

**Issue by ningmengwork** [getsentry/sentry-java#1870]
Spring Boot Starter, How to tirgger TransactionFinishedCallback Implement?

**Comment by maciejwalkowiak** [comment]
`TransactionFinishedCallback` is an internal SDK class and is not meant to be used by the SDK users. What is your use case? Perhaps there is another way to achieve the same, or alternatively we should revisit `TransactionFinishedCallback`.

**Comment by ningmengwork** [comment]
**traces-sample-rate** configured in my spring boot project with **sentry-spring-boot-starter** .  I wish set some custom data when sampling before the transaction finishes,  but actually  TransactionFinishedCallback Implment would not excute.  So how could I set some custom data when sampling with  **sentry-spring-boot-starter**,  look forward  to your answer.

**Comment by maciejwalkowiak** [comment]
Perhaps you achieve what you need with implementing `TracesSamplerCallback` as described in https://docs.sentry.io/platforms/java/guides/spring-boot/performance/?

**Comment by ningmengwork** [comment]
> Perhaps you achieve what you need with implementing `TracesSamplerCallback` as described in https://docs.sentry.io/platforms/java/guides/spring-boot/performance/?

Thanks!
