### ISSUE TITLE
Sentry Servlet using Servlet API as Runtime Dependency

### ISSUE THREAD

**Issue by anuragagarwal561994** [getsentry/sentry-java#1878]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [x]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [x]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [x]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**5.5.3**

---
I have the following issue:
[Maven Link](https://mvnrepository.com/artifact/io.sentry/sentry-servlet/5.5.3)
From here I came to know that sentry-servlet is using servlet-api as runtime dependency.

The description goes here ...
I am using tomcat 9.0.56 which has it's own implementation of servlet-api and contains all the servlet-api class in itself.

It is usually advised that if we are using servlet-api in our pom.xml we should use it with a provided scope.

provided scope doesn't add sentry-servlet to your classpath because those classes are to be fetched from the tomcat instead and not servlet-api when the application runs. However since the scope here is runtime, sentry-servlet is getting added to the classpath, thus when the application is trying to pick up the class it is getting confused and picking different classes in different environments. Like on local it picks from tomcat while in production it is picking up from sentry-servlet (because of build tools may be this may be happening).

Tomcat 9.0.56 has a class javax.servlet.Filter which has default implementations of methods while servlet-api doesn't have default implementations, then when a wrong class is picked up an error is thrown because the implementation of a method is missing.

**Steps to reproduce:**
- NA

**Actual result:**
- servlet-api is getting added to the classpath

**Expected result:**
- servlet-api should not be added to the classpath

At present we have made servlet-api provided explicitly in our pom.xml files to resolve this issue, but ideally it should be present in sentry-servlet so that other's do not face the same issue.

**Comment by maciejwalkowiak** [comment]
Thanks for reporting @anuragagarwal561994

**Comment by anuragagarwal561994** [comment]
Thanks for quick response @maciejwalkowiak
