### ISSUE TITLE
Add more UI events breadcrumbs

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#1881]
Add breadcrumbs for

- [ ] #1977
- [ ] #1978
- [ ] #1979
- [ ] #1980

Split those up into separate issues before implementing this

**Comment by marandaneto** [comment]
Consider doing https://github.com/getsentry/sentry-java/issues/1877 if tackling those new integrations that depend on lifecycle.

**Comment by marandaneto** [comment]
We'd split them up into issues that need integration and an issue for the super easy ones.
