### ISSUE TITLE
No stacktrace is printed if there is exception in main thread

### ISSUE THREAD

**Issue by Paxa** [getsentry/sentry-java#1887]
_Platform:_
- [ ]  Java -> 8
- [ ]  Logback -> 1.2.3

_Build system:_
- [ ]  Gradle -> 5.2.1

The version of the SDK:
**3.2.1 - 6.0**

If there is exception in main thread, sentry will hide stacktrace

If disable `UncaughtExceptionHandler` then exception is shown as expected
```
Sentry.init(options -> {
  options.setEnableUncaughtExceptionHandler(false);
});
```

**Comment by marandaneto** [comment]
@Paxa dup of https://github.com/getsentry/sentry-java/issues/1077 maybe?

**Comment by chadwhitacre** [comment]
@marandaneto Mind adding the "Status: Needs Information" label? 🙇

**Comment by Paxa** [comment]
> @Paxa dup of #1077 maybe?

yes
