### ISSUE TITLE
Support Timber tags

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#1900]
We have no way to get the tag when inheriting `Timber.Tree`, because it's marked as internal/package-private for consumers https://github.com/JakeWharton/timber/blob/dc45d69b081a03e3fb83e81a7aee0f430f46b4f1/timber/src/main/java/timber/log/Timber.kt#L22. This means, when timber is used like this:

```Kotlin
Timber.tag("Tag")
Timber.e("Issue")
```
the tag will not be reflected on Sentry.

If this gets traction, we could either offer a reflection-based support or automatically infer classname of the caller (that's what `Timber.DebugTree` does by default).

Please, vote on this issue if you'd like us to provide support for Timber tags.

**Comment by bruno-garcia** [comment]
Would they accept a PR upstream that adds an API to get the tags?

**Comment by romtsn** [comment]
There is actually a few open PRs addressing that (this is the closest one to what we want https://github.com/JakeWharton/timber/pull/224/files), but none of them get any traction unfortunately.

**Comment by marandaneto** [comment]
> Would they accept a PR upstream that adds an API to get the tags?

We can try but https://github.com/JakeWharton/timber/pull/393 never got a reply/review.
