### ISSUE TITLE
Report different sdk.name for NDK crashes

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1901]
NDK crashes are captured by `sentry-native` and reported as `sentry.native`. This makes it hard to distinguish by builds bundled by the Android SDK (which are in fact using a different mechanism/backend to capture as any build documented directly on sentry-native repo.

I suggest we have a `#ifdef` that allows us to change the SDK name to `sentry.native.android` when building in this repository.

**Comment by marandaneto** [comment]
This should likely be in the `sentry-native` repo, https://github.com/getsentry/sentry-native/blob/0c5dd442a031e63b34e1941ccd5922b2ebec590a/include/sentry.h#L26

**Comment by bruno-garcia** [comment]
@marandaneto yes, and some bits here, defining the constant for example

**Comment by bruno-garcia** [comment]
When a version after 0.4.15 is released, it should already report `sentry.native.android`: https://github.com/getsentry/sentry-java/issues/1901

**Comment by romtsn** [comment]
Closed by https://github.com/getsentry/sentry-native/pull/677
