### ISSUE TITLE
Inconsistent event drop vs session update logic

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1916]
We've received from a customer:

`captureEvent() :`
* if the event is dropped because its throwable is in the ignoredExceptionForTypes , method will immediately return the SentryId.EMPTY_ID , and nothing will be sent (see [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java#L116))
* if the event is dropped because beforeSend callback returned null (see [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java#L121)), method still will build the envelope without the event, but with the updated session and will send it, because session is updated (error amount is incremented) before the beforeSend filtering is happening (see [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java#L93))
* and if the event is dropped because EventProcessor returned null  (see [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java#L88)), session will be null, so it won't be updated, and also it won't be sent (see [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java#L92))

This means that all 3 ways of dropping events are inconsistent with each other, and it's not documented anywhere:

* using ignoredExceptionForTypes will effectively drop the event, won't update the session, and won't send anything (not the dropped event, not the session, not the attachments)
* using beforeSend callback will drop the event, but still update the session, so it'll still send the updated session (with incremented error count) and attachments (if any)
* using EventProcessor will drop the event, won't update the session, but still will send the attachments, if there are any

We need to align and document the side effect of dropping an event with regards to session updates.

Note, this relates slightly to the Client Reports https://github.com/getsentry/sentry-java/issues/1894

**Comment by bruno-garcia** [comment]
Another thoughts: if the event is dropped due to sampling, we might want to send a session update (event isn't captured likely due to quota limitation, but the session state change is legit)

**Comment by marandaneto** [comment]
> if the event is dropped because its throwable is in the ignoredExceptionForTypes , method will immediately return the SentryId.EMPTY_ID , and nothing will be sent (see [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java?rgh-link-date=2022-02-19T00%3A03%3A57Z#L116))

It should update the session state.

> and if the event is dropped because EventProcessor returned null (see [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java?rgh-link-date=2022-02-19T00%3A03%3A57Z#L88)), session will be null, so it won't be updated, and also it won't be sent (see [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java?rgh-link-date=2022-02-19T00%3A03%3A57Z#L92))

It should update the session state.
If there are attachments, they should not be sent, since attachments require an eventId and the event was discarded.

Follow the `beforeSend` implementation, if the event was dropped for any reason, it's ok, but the session counter should be updated.

**Comment by adinauer** [comment]
Looks like all the ways to drop an event discussed here (beforeSend, eventProcessor, ignoredExceptionForTypes and sample rate) cause the session to **NOT** be updated in the python SDK.

# before_send
* https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/client.py#L336
* session would be updated later but early return prevents it: https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/client.py#L344
* https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/client.py#L206
   
# event processor
* https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/client.py#L149
* session would be updated later but early return prevents it: https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/client.py#L344
* https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/scope.py#L385
* https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/scope.py#L391
   
# ignoredExceptionForTypes
This one is a bit tricky. According to https://github.com/getsentry/sentry-python/issues/149 the `ignore_errors` option should no longer exist. But it's still in the code (https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/client.py#L230)
* https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/client.py#L333

# sample rate
* https://github.com/getsentry/sentry-python/blob/d880f47add3876d5cedefb4178a1dcd4d85b5d1b/sentry_sdk/client.py#L256
