### ISSUE TITLE
SentryTracingFilter.java assumes HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE always available

### ISSUE THREAD

**Issue by sbrattla** [getsentry/sentry-java#1918]
_Platform:_
- [X ]  Java -> 8
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [X]  Other -> Netbeans

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [X ]  Maven -> 3
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ X]  No

_Proguard/R8:_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] Maven Central
- [ ] Manually

The version of the SDK:
**5.7.1**

---
I'm using Sentry in a Spring Boot application. I've followed the configuration guide, and set up tracing with :+1: 

```
        <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-spring-boot-starter</artifactId>
            <version>5.6.1</version>
        </dependency>
```

I've enabled tracing, and tracing works up to the point where `SentryTracingFilter` attempts to get transaction name from the `TransactionNameProvider`. In my case, a `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` is never set because the application use `RequestMappingHandlerMapping`.

I have not been able to figure out how to set my own `TransactionNameProvider`. That would solve this issue. Right now I see no other way but setting `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` manually some where before the `TransactionNameProvider` wants to use that attribute.

**Comment by maciejwalkowiak** [comment]
Setting up custom `TransactionNameProvider` will be available in Sentry Java SDK 6.0 (https://github.com/getsentry/sentry-java/pull/1861). 

If you use `RequestMappingHandlerMapping`, `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` should be set. Could you please show a minimal example (ideally fully working app in a separate repository) that reproduces this problem?

In meantime please follow this thread: https://forum.sentry.io/t/sentry-java-spring-boot-and-grails-performance-tracing-not-working/15765 - it's a workaround and requires copy & pasting, but in case you need to provide your own way of retrieving transaction name its the best I figured out in 5.x version.

**Comment by sbrattla** [comment]
@maciejwalkowiak I don't have time to set up a minimal example here now, but sounds good with the custom `TransactionNameProvider`.

Right now I set the `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` through AOP, which works fine for the time being. Thanks :-)

**Comment by maciejwalkowiak** [comment]
Cool, thanks for quick feedback. I am closing this issue then, and watch for 6.x release when it becomes easier to set up.
