### ISSUE TITLE
Spring SentryExceptionResolver not sending raw exception as BeforeSendCallback hint

### ISSUE THREAD

**Issue by dlopuch** [getsentry/sentry-java#1920]
_Platform:_
- [x]  Spring ->  v5.1

_Platform installed with:_
- [x] Maven Central

The version of the SDK:
**5.6.1**

---
I have the following issue:

Trying to create a filter based off a Spring exception handler -- I want to filter based off a certain exception class that bubbles up from my controller.

https://docs.sentry.io/platforms/java/guides/spring/configuration/filtering/#event-hints says

> Typically a hint holds the original exception so that additional data can be extracted or grouping is affected.

Great, I should check the `hint` to get the exception. However, my `SentryOptions.BeforeSendCallback.execute()` receives a null `hint` param when passed up from an `io.sentry.spring.SentryExceptionResolver`

**Steps to reproduce:**
- Throw an error from a spring controller
- Try to filter it with a `SentryOptions.BeforeSendCallback` implementation

**Actual result:**
- The `hint` parameter is null

**Expected result:**
- Should https://github.com/getsentry/sentry-java/blob/main/sentry-spring/src/main/java/io/sentry/spring/SentryExceptionResolver.java#L53 be sending the Exception as the hint param?

**Comment by maciejwalkowiak** [comment]
You should be able to access the exception captured by `SentryExceptionResolver` through `SentryEvent#getThrowable`. If this is not the one you need, use can access root exception with `org.springframework.core.NestedExceptionUtils#getRootCause`. Let me know if it helps, or if not please provide more details about your specific use case.

**Comment by dlopuch** [comment]
That seems to work, thanks. 

I guess then the issue is the documentation is very ambiguous about what the hint parameter is used for and when it should be expected vs. empty. Is there better documentation about what the hint object is supposed to be / when it should be used to get the underlying exception vs. when to use `SentryEvent#getThrowable`?

**Comment by marandaneto** [comment]
@dlopuch as of now, only use the `SentryEvent#getThrowable`, `hints` are being [refactored](https://github.com/getsentry/sentry-java/issues/1558) on https://github.com/getsentry/sentry-java/milestone/7 and docs updates will follow.
