### ISSUE TITLE
Offline caching improvements - Delay between and backoff when 429 is on

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1926]
The SDK guideline has a couple of new items regarding offline caching: https://github.com/getsentry/develop/pull/509

1. If rate-limit was hit, make sure the caching transport is aware. Meaning: don't read all files from disk to send to the HTTP transport when that's basically dropping everything due to rate-limit
2. Add a delay when reading from disk to avoid bursts of events which could trigger rate limit
3. Once the device is back online, read events preciously cached (as opposed to send only on restart or when a new event is captured)

Relates to:
* https://github.com/getsentry/sentry-dotnet/issues/1504
* https://github.com/getsentry/sentry-cocoa/issues/1671

**Comment by romtsn** [comment]
Closed by #2937
