### ISSUE TITLE
withSentryInterface not working in Sentry 5.6.2 

### ISSUE THREAD

**Issue by Mohitkumar6122** [getsentry/sentry-java#1941]
I have an event in sentry and I want to attach multiple interfaces to it in the latest Sentry version(5.6.1).

Earlier(Sentry 1.7.3) I used to do like this

```
EventBuilder builder = new EventBuilder();         
builder.withSentryInterface(new ExceptionInterface(ex));                               
builder.withSentryInterface(new UserInterface(user, null, remoteAddr, null, null));
```
but on updating the sentry version this method is not working and I can't find anything on the docs either.

Any help or suggestions would be a great help.

I am using java spring boot sentry as a dependency

**Comment by marandaneto** [comment]
Here is our migration [docs](https://docs.sentry.io/platforms/java/migration/).
Here is the usage [docs](https://docs.sentry.io/platforms/java/usage/).

To set the user, you can follow this [docs](https://docs.sentry.io/platforms/java/enriching-events/identify-user/) instead of the `UserInterface`.

You can do `Sentry.captureException(...)` instead of `ExceptionInterface`.

**Comment by Mohitkumar6122** [comment]
@marandaneto, I get it now, how to attach a user with an event, but how do I send an HTTP request to an event( like we used to with ```builder.withSentryInterface(new HTTPInterface)```)
I cannot find it on Migrating docs and in the usage docs?

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/java/enriching-events/context/
The `scope` has a `request` field.

**Comment by Mohitkumar6122** [comment]
> https://docs.sentry.io/platforms/java/enriching-events/context/ The `scope` has a `request` field.

Thanks, @marandaneto for helping me out!
But can I ask why we removed ```HTTPInterface``` in the first place as it is better to send HTTP data with the event itself rather than to send it in the scope of Sentry? and why we didn't make another function as we have with ```UserInterface```?

**Comment by marandaneto** [comment]
@Mohitkumar6122 You can still do

```
SentryEvent event = new SentryEvent();
// personalize all the fields you want.
Sentry.captureEvent(event);
```
