### ISSUE TITLE
Help: Unable to trigger a "Warm" app start event

### ISSUE THREAD

**Issue by cmathew** [getsentry/sentry-java#1950]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.1.2

### Proguard

Disabled

### Version

5.6.3

### Steps to Reproduce

1. Create an app that initializes Sentry inside your Application class's onCreate method
2. Enable "Do Not Keep Activities" inside an Android device's developer options
3. Start the app
4. Background the app
5. Resume the app
6. Note on the Sentry dashboard that no "Warm" start performance events are captured, only "Cold" starts

### Expected Result

This docs make a distinction between [Cold and Warm](https://docs.sentry.io/platforms/android/performance/instrumentation/automatic-instrumentation/#app-start-instrumentation) app starts. From what it says, I would expect the above steps to trigger a Warm start.

### Actual Result

Only Cold start events are reported. I looked into the SDK code and discovered there's a `ActivityLifecycleIntegration` variable called `firstActivityCreated` which gets stuck on `true` after first launch. Seemingly this prevents `setColdStart(false)` from being called, and hence Warm start events from registering:
```
private void setColdStart(final @Nullable Bundle savedInstanceState) {
  if (!firstActivityCreated) {
    // if Activity has savedInstanceState then its a warm start
    // https://developer.android.com/topic/performance/vitals/launch-time#warm
    AppStartState.getInstance().setColdStart(savedInstanceState == null);
  }
```
Looking at the code it's unclear when `firstActivityCreated` could become `false` again, except after a full application restart (in which case it should of course be considered a Cold start). If it matters: my application uses a single Activity and initializes Sentry programmatically. Thank you!

**Comment by cmathew** [comment]
I see that the Android docs define "Warm" starts in two ways: https://developer.android.com/topic/performance/vitals/launch-time#warm, of which the Do Not Keep Activities scenario is only one. I don't know how to simulate the other scenario ("The system evicts your app from memory, and then the user re-launches it") at will, but would that be considered a Warm start?

**Comment by marandaneto** [comment]
Hi, How to reproduce a Warm start:

1. Open the App
2. Enable Developer options if not yet;
3. Go to Settings, System, Advanced, Developer options, Running service, click on the context menu (... button top right of the screen), click on Show cached processes, Find the name of your App in the list and click on it, click on stop and open the app again;
