### ISSUE TITLE
Sentry Timber integration does not submit msg.formatted breadcrumbs.

### ISSUE THREAD

**Issue by martinchiu1991** [getsentry/sentry-java#1956]
### Integration

sentry-android-timber

### Build System

Gradle

### AGP Version

7.0.2

### Proguard

Enabled

### Version

5.7.0

### Steps to Reproduce

Enable timber integration and use timber in the project.

`                options.addIntegration(
                        new SentryTimberIntegration(
                                SentryLevel.ERROR,
                                SentryLevel.INFO
                        )
                );`
                
` Timber.i("App version %s(%s)", BuildConfig.VERSION_NAME, BuildConfig.VERSION_CODE);`

### Expected Result

Breadcrumb on dashboard to filled in with arguments

### Actual Result

Breadcrumb is not filled in with data.

Looks like the following on the Sentry dashboard
`App version %s(%s)`

**Current code in 5.7.0 in SentryTimberTree.kt**

> 
> private fun addBreadcrumb(
>         sentryLevel: SentryLevel,
>         msg: Message,
>         throwable: Throwable?
>     ) {
>         // checks the breadcrumb level
>         if (isLoggable(sentryLevel, minBreadcrumbLevel)) {
>             val throwableMsg = throwable?.message
>             val breadCrumb = when {
>                 msg.message != null -> Breadcrumb().apply {
>                     level = sentryLevel
>                     category = "Timber"
>                     message = msg.message
>                 }
>                 throwableMsg != null -> Breadcrumb.error(throwableMsg).apply {
>                     category = "exception"
>                 }
>                 else -> null
>             }
>             breadCrumb?.let { hub.addBreadcrumb(it) }
>         }
>     }

    
   **Possible fix
   Current code in 5.7.0 in SentryTimberTree.kt**

> private fun addBreadcrumb(
>         sentryLevel: SentryLevel,
>         msg: Message,
>         throwable: Throwable?
>     ) {
>         // checks the breadcrumb level
>         if (isLoggable(sentryLevel, minBreadcrumbLevel)) {
>             val throwableMsg = throwable?.message
>             val breadCrumb = when {
>                 msg.message != null -> Breadcrumb().apply {
>                     level = sentryLevel
>                     category = "Timber"
>                     message = msg.formatted ?: msg.message //this is the fix.
>                 }
>                 throwableMsg != null -> Breadcrumb.error(throwableMsg).apply {
>                     category = "exception"
>                 }
>                 else -> null
>             }
>             breadCrumb?.let { hub.addBreadcrumb(it) }
>         }
>     }

**Comment by marandaneto** [comment]
Thanks for reporting @martinchiu1991
