### ISSUE TITLE
Measure Sentry.init impact on app startup time

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#1965]
### Description

We could use [jetpack.macrobenchmark](https://developer.android.com/studio/profile/macrobenchmark-overview) for continuously measuring it on a sample app. Prior art: https://github.com/android/compose-samples/blob/c6a32ae127b70ac4ea6810c12857758d62da475e/Jetsnack/benchmark/src/main/java/com/example/jetsnack/benchmark/StartupBenchmark.kt

**Comment by marandaneto** [comment]
Related PR https://github.com/getsentry/sentry-android-gradle-plugin/pull/317
