### ISSUE TITLE
All events are not captured by the sentry, Some events go into the dropping state.

### ISSUE THREAD

**Issue by pragnesh1234** [getsentry/sentry-java#1972]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

4.1.2

### Proguard

Enabled

### Version

5.7.0

### Steps to Reproduce

Fire the Sentry exception every 1 second to the sentry. In this case, every exception is not captured by the Sentry. Some events go into the dropping state.

So anyone has an idea, Which events are dropping? So I can find this solution. In the Sentry console, I am not able to find which events are dropping.

### Expected Result

All events should be captured by Sentry.

### Actual Result

All events are not captured by Sentry.

**Comment by marandaneto** [comment]
@pragnesh1234 what do you mean by:

> Some events go into the dropping state.

**Comment by pragnesh1234** [comment]
@marandaneto 
Thanks for the response!

When I fired the 100 events, All events were not captured by a sentry. Some evet is dropped. 
I have attached the image. so you can get more idea. please check it. 
![Usage-Stats-Sentry](https://user-images.githubusercontent.com/56993256/161272929-83e22e69-8de8-41bd-aeaf-c61da6b1be08.png)

**Comment by marandaneto** [comment]
There are many reasons why events get dropped, e.g. rate-limiting, See https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/
