### ISSUE TITLE
Breadcrumbs for RecyclerView

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1980]
RecyclerView is partially supported (the click on an item will be captured, but there's no useful data like which position in the list was selected - again, a new integration?)

**Comment by filipnavara** [comment]
There's rather annoying issue that `RecyclerView` is not treated as scrolling UI element and I get a log full of "Debug: Android: Unable to find scroll target. No breadcrumb captured.".

**Comment by smeubank** [comment]
parent issue is closed, i would rather re-open that, than have all these stale issues, closing, see parent issue to comment or reopen these later if there is capacity to add

https://github.com/getsentry/sentry-java/issues/1881
