### ISSUE TITLE
Investigate ways of supporting javax and jakarta for Spring and Spring Boot

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#1984]
### Description

We've decided to duplicate `sentry-servlet` (javax) into `sentry-servlet-jakarta` (jakarta) to support both as it's only three files that rarely change.

For Spring and Spring Boot we'd like to avoid duplication so we want to find out possible ways of supporting both.

See https://github.com/getsentry/sentry-java/issues/1789

**Comment by rauldeheer** [comment]
Any news on this? We are currently running Spring Boot v3-M3 and we are unable to use the Sentry SDK at this time.

**Comment by adinauer** [comment]
@rauldeheer we don't have a schedule for this yet, it's very high on the backlog though.

**Comment by maciejwalkowiak** [comment]
Current state of investigation:

Our current artifacts that depend on `javax` can be transformed to Jakarta namespace with [Eclipse Transformer](https://github.com/eclipse/transformer).

Manual step by step guide:

1. Download & unzip [Eclipse Transformer CLI distribution](https://repo1.maven.org/maven2/org/eclipse/transformer/org.eclipse.transformer.cli/0.5.0/org.eclipse.transformer.cli-0.5.0-distribution.jar).

2. Transform JARs:

```
$ java -jar org.eclipse.transformer.cli-0.5.0.jar ~/.m2/repository/io/sentry/sentry-spring-boot-starter/6.2.1/sentry-spring-boot-starter-6.2.1.jar ~/.m2/repository/io/sentry/sentry-spring-boot-starter/6.2.1/sentry-spring-boot-starter-6.2.1-jakarta.jar

$ java -jar org.eclipse.transformer.cli-0.5.0.jar ~/.m2/repository/io/sentry/sentry-spring/6.2.1/sentry-spring-6.2.1.jar ~/.m2/repository/io/sentry/sentry-spring/6.2.1/sentry-spring-6.2.1-jakarta.jar
```

3. Include transformed files in `pom.xml` using `classifier`:

```xml
<dependency>
	<groupId>io.sentry</groupId>
	<artifactId>sentry-spring-boot-starter</artifactId>
	<version>6.2.1</version>
	<classifier>jakarta</classifier>
	<exclusions>
		<exclusion>
			<groupId>io.sentry</groupId>
			<artifactId>sentry-spring</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>io.sentry</groupId>
	<artifactId>sentry-spring</artifactId>
	<version>6.2.1</version>
	<classifier>jakarta</classifier>
</dependency>
```

This proves that Transformer works and can be used to produce Jakarta compatible artifacts, but of course we cannot recommend going through this process to our users. We need one of:

1. Produce Jakarta compatible artifacts in our build process - that's possible (Hibernate does it), but there's not straightforward out-of-the-box working solution other than 3rd party https://github.com/sebersole/jakarta-transformer-plugin that I haven't tested yet.
2. Simplify the guide so that it's a single step process and does not require installing Jakarta artifacts to Maven repository manually (perhaps with `transformer-maven-plugin`).

**Comment by maciejwalkowiak** [comment]
I played with `jakarta-transformer-plugin` and came up with following that I believe should work (but it doesn't):

1. Create a new module `sentry-spring-jakarta` with following `build.gradle`:

```kotlin
import io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    `java-library`
    kotlin("jvm")
    id("org.hibernate.jakarta-transformer") version "0.9.6"
    id(Config.BuildPlugins.springBoot) version Config.springBootVersion apply false
    id(Config.BuildPlugins.springDependencyManagement) version Config.BuildPlugins.springDependencyManagementVersion
}

the<DependencyManagementExtension>().apply {
    imports {
        mavenBom(SpringBootPlugin.BOM_COORDINATES)
    }
}

configure<JavaPluginExtension> {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8.toString()
    kotlinOptions.languageVersion = Config.kotlinCompatibleLanguageVersion
}

dependencies {
    // Specifying the transformer's dependencies is optional.  0.2.0 is used by default
    jakartaTransformerTool(
        "org.eclipse.transformer:org.eclipse.transformer:0.5.0",
    )
    jakartaTransformerTool("org.eclipse.transformer:org.eclipse.transformer.cli:0.5.0")
}

jakartaTransformation {
    shadow(projects.sentrySpring) {
        withJavadoc()
        withSources()
    }
}
```

Unfortunately, calling from the module directory:

```
$ ../gradlew shadow
```

results in:

```
Execution failed for task ':sentry-spring-jakarta:shadowJar'.
> Process 'command '/Users/maciej/.sdkman/candidates/java/11.0.16-zulu/zulu-11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

This for now ends my investigation - I think it's clear that if we want to pursue publishing artifacts for both `javax` and `jakarta` we must use Eclipse Transformer, but as usual with Gradle - it will require quite a bit of trial and error.

**Comment by maciejwalkowiak** [comment]
New module is committed to branch: https://github.com/getsentry/sentry-java/tree/gh-1984

**Comment by TomBeckett** [comment]
Any news on this? We've also had to stop using Sentry due to lack of support.

**Comment by adinauer** [comment]
@TomBeckett we're looking to add support in the near future - no detailed timeline yet but we plan to have support for the release at the latest.

**Comment by adinauer** [comment]
@TomBeckett I guess @maciejwalkowiak has already done a lot of the ground work. At this point I assume we can make it work. Maybe we'll need help if we can't figoure out a way around issues like the one linked by Maciej above. We'll post here once we know more.

**Comment by rauldeheer** [comment]
Do you need any help? Please let us know. @adinauer @maciejwalkowiak

**Comment by adinauer** [comment]
Thanks for the offer @rauldeheer . We're planning to take a look at this in the coming weeks. Will let you know as soon as we have specific things we need help with.

**Comment by TomBeckett** [comment]
Spring Boot 3 RC1 is aiming to be ready around 20th October. 

Would it be possible to have Sentry available for testing against that RC? @adinauer

**Comment by adinauer** [comment]
@TomBeckett @rauldeheer we've just released [6.7.0-alpha.1](https://github.com/getsentry/sentry-java/releases/tag/6.7.0-alpha.1) which has separate modules for supporting Spring 6 (`sentry-spring-jakarta`) and Spring Boot 3 (`sentry-spring-boot-starter-jakarta`). We also have samples for them available [Spring](https://github.com/getsentry/sentry-java/blob/feat/6.7.x/sentry-samples/sentry-samples-spring-jakarta/build.gradle.kts) and [Spring Boot](https://github.com/getsentry/sentry-java/tree/feat/6.7.x/sentry-samples/sentry-samples-spring-boot-jakarta). If you decide to give it a try, any feedback is very welcome :-)

**Comment by TomBeckett** [comment]
@adinauer Are these available on maven? Do I need both `sentry-servlet-jakarta` and `sentry-spring-boot-starter` ?

**Comment by adinauer** [comment]
Hey @TomBeckett , I assume it takes a bit until the packages arrive at the different Maven mirrors. I see it here: https://repo1.maven.org/maven2/io/sentry/sentry-spring-boot-starter-jakarta/6.7.0-alpha.1/

> Do I need both sentry-servlet-jakarta and sentry-spring-boot-starter ?

Actually none of those. You want `sentry-spring-boot-starter-jakarta` for Spring Boot or `sentry-spring-jakarta` for Spring. Note the `jakarta` in the name.

**Comment by TomBeckett** [comment]
We've been running this for a few hours in our dev environment - so far so good. I'll open any issues as I see them but early signs are good.

Please pass on my thanks for the team @adinauer (with a big shout out to @lbloder!) for getting it done early before the RC. It really helps us get ready internally 👍

**Comment by TomBeckett** [comment]
@adinauer Just one last update - No issues encountered using this beta build.

FYI it's been good to get Sentry back - it really is a fantastic product.

Thanks again for releasing an early version for us to use 👍

**Comment by adinauer** [comment]
@TomBeckett that's great to hear. Thanks for the kind words ❤️

**Comment by adinauer** [comment]
Closing this now as version `3.0.0` of Spring Boot has been released and it seems to be working. Version has just been bumped in https://github.com/getsentry/sentry-java/pull/2389
