### ISSUE TITLE
Send integrations list as metadata

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1989]
### Problem Statement

Right now we only send the sdk packages but not integrations

### Solution Brainstorm

https://github.com/getsentry/sentry-java/blob/74deb437ab935543aff1e0b27c8bb63e60cb86cc/sentry/src/main/java/io/sentry/protocol/SdkVersion.java#L47-L54

So we can learn about the usages of our integrations

**Comment by romtsn** [comment]
Dupe of #1885?
