### ISSUE TITLE
Native crashes are still reported after manually opting out

### ISSUE THREAD

**Issue by Amejia481** [getsentry/sentry-java#1993]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.0

### Proguard

Enabled

### Version

5.6.1

### Steps to Reproduce

Initialize entry to opt-out for sending  `UncaughtException`

```kotlin
        SentryAndroid.init(applicationContext) { options ->
            options.enableUncaughtExceptionHandler = false
            options.dsn = dsn
            options.environment = environment
        }
```

Something to note is that Java/Kotlin exceptions are not sent after setting `enableUncaughtExceptionHandler` to `false`, but native crashes are still sent.

### Expected Result

No native crashes are sent to Sentry.

### Actual Result

Native crashes are sent to Sentry.

**Comment by romtsn** [comment]
You'd also need to disable NDK integration for that https://docs.sentry.io/platforms/android/using-ndk/#disable-ndk-integration. I don't think we have a way to disable specifically uncaught exceptions on native.

**Comment by Amejia481** [comment]
@romtsn @marandaneto thank you for the help :)


 Is this sufficient to disable both native and no-native crashes from being reported? 


```kotlin
        SentryAndroid.init(applicationContext) { options ->
            options.enableUncaughtExceptionHandler = false

            options.setBeforeSend { event, _ ->
                val tags = event.tags ?: emptyMap()
                val isUnHandled = tags["error.unhandled"]?.equals("true") == true ||
                    tags["error.handled"]?.equals("false") == true
                if (isUnHandled) {
                    null
                } else {
                    event
                }
            }
        }
```

Thanks in advance!

**Comment by marandaneto** [comment]
No, I'd rather use `SentryEvent#isCrashed() == true`, drop it.
`error.unhandled` is not created by the SDK so it won't be available.

**Comment by Amejia481** [comment]
Thank you so much 🙌🏽 !!!
