### ISSUE TITLE
Move Android options from `SentryOptions` to `SentryAndroidOptions`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1994]
### Description

`enableNdk` is one example, there are likely more.

**Comment by romtsn** [comment]
probably `idleTimeout` can also be moved to AndroidOptions since it's kind of a UI-relevant thing - backend probably won't ever need it

**Comment by marandaneto** [comment]
> probably `idleTimeout` can also be moved to AndroidOptions since it's kind of a UI-relevant thing - backend probably won't ever need it

Java desktop apps would use it, so I'd rather keep it.
