### ISSUE TITLE
Configure scope in a filter

### ISSUE THREAD

**Issue by perihelious** [getsentry/sentry-java#2003]
### Problem Statement

I'm using logback with spring. I'd like to create Sentry tags and a Sentry user based on request headers and apply to the relevant logging/Sentry events.

The easiest way to do that seemed to configure the Sentry scope in a filter (implements javax.servlet.Filter).

But Sentry.configureScope etc. in the filter had no effect on logging from the actual request handler.

Sentry.setTag in the filter _did_ set persistent tags. However Sentry.setUser in the filter did not persist the user.

Is it possible to configure scope (tags and user) in a filter, rather than in the controller or exception handler?

**Comment by maciejwalkowiak** [comment]
@perihelious just to make sure - are you working with pure Spring or Spring Boot integration?

**Comment by perihelious** [comment]
Spring Boot -- sentry-spring-boot-starter 5.7.3

**Comment by adinauer** [comment]
@perihelious this works for me:

```
package io.sentry.samples.spring.boot;

import io.sentry.Sentry;
import io.sentry.protocol.User;
import java.io.IOException;
import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

@Component
public class HeaderFieldUserSetterFilter extends OncePerRequestFilter {

  @Override
  protected void doFilterInternal(
      HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
      throws ServletException, IOException {
    Sentry.setTag("my-tag", request.getHeader("X-MyTagHeader"));

    User user = new User();
    user.setEmail("jane.doe@example.sentry.io");
    user.setUsername(request.getHeader("X-MyUserNameHeader"));
    Sentry.setUser(user);

    filterChain.doFilter(request, response);
  }
}
```

**Comment by perihelious** [comment]
Thanks, @adinauer. Both the LOWEST_PRECEDENCE annotation and application.properties entry worked. This is good to know.

**Comment by marandaneto** [comment]
@adinauer do you think we should mention that somewhere in the docs if not yet? otherwise we can close this.

**Comment by adinauer** [comment]
@perihelious fyi there's more ways to do what you want. Then you wouldn't have to create a custom filter and mess with the order.

You could supply a custom `SentryUserProvider` like so:

```
package io.sentry.samples.spring.boot;

import io.sentry.protocol.User;
import io.sentry.spring.SentryUserProvider;

import javax.servlet.http.HttpServletRequest;

import org.jetbrains.annotations.Nullable;
import org.springframework.stereotype.Component;
import org.springframework.web.context.request.RequestAttributes;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

@Component
public class HeaderFieldUserUserProvider implements SentryUserProvider {

  @Override
  public @Nullable User provideUser() {
    RequestAttributes requestAttributes = RequestContextHolder.getRequestAttributes();
    if (requestAttributes instanceof ServletRequestAttributes) {
      HttpServletRequest request = ((ServletRequestAttributes)requestAttributes).getRequest();

      User user = new User();
      user.setEmail("jane.doe@example.sentry.io");
      user.setUsername(request.getHeader("X-MyUserNameHeader"));

      return user;
    }
    
    return null;
  }
}
```

You could also do it by providing an `EventProcessor`. See https://docs.sentry.io/platforms/java/guides/spring-boot/advanced-usage/#registering-custom-event-processor

**Comment by marandaneto** [comment]
Just be aware that `SentryUserProvider ` has been removed on https://github.com/getsentry/sentry-java/releases/tag/6.0.0-alpha.2 and `SentryUserFilter` is the way to go -> https://docs.sentry.io/platforms/java/migration/

**Comment by adinauer** [comment]
@marandaneto when I look at https://github.com/getsentry/sentry-java/pull/1875/files it only shows `SentryUserProviderEventProcessor` as being removed, not `SentryUserProvider`.

**Comment by marandaneto** [comment]
Yep, you are right, my bad, only `SentryUserProviderEventProcessor` got removed, @adinauer would you mind fixing the migration docs? https://docs.sentry.io/platforms/java/migration/ thanks.

**Comment by adinauer** [comment]
@marandaneto PR open here: https://github.com/getsentry/sentry-docs/pull/4982

Closing this issue now, feel free to reopen if you need anymore help with this.
