### ISSUE TITLE
Ignoring an Exception class does not ignore its children

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2015]
### Problem Statement

In .NET ignoring an Exception also ignores all of the Exceptions child classes. In Java only the class explicitly added to the list of ignored exceptions will be ignored.

### Solution Brainstorm

We could align with .NET and also ignore subclasses.

**Comment by adinauer** [comment]
Also see https://github.com/getsentry/sentry-java/issues/1532, https://github.com/getsentry/sentry-java/pull/2014 and https://github.com/getsentry/sentry-docs/pull/4995

**Comment by usrivastava92** [comment]
hi @adinauer I have raised a PR to fix this, please review it and let me know if anything should be changed 🙂  Thanks

**Comment by adinauer** [comment]
Thanks for the PR, I replied there. We'll discuss internally how to treat this breaking change.

**Comment by stefanosiano** [comment]
We are going to keep the current behaviour for SDK version 7.
@adinauer Is there a more useful use case for the backend? In that case we could reconsider it.

**Comment by adinauer** [comment]
@stefanosiano I guess there's nothing special about backends here. Just the usual exception handling. I personally would expect the feature to behave similar to how try/catch behaves which also applies to child classes but if you feel like there's too much of a risk we can keep existing behaviour for now and revisit on the next major.

**Comment by stefanosiano** [comment]
let's close this issue for the moment. In case we want to change the behaviour in the next major we will reopen it.
