### ISSUE TITLE
JsonSerializerTest is flaky

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-java#2020]
### Description

The following error occurred in https://github.com/getsentry/sentry-java/runs/6302364325?check_suite_focus=true

```
io.sentry.JsonSerializerTest > serializes transaction FAILED
    java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
        at io.sentry.JsonSerializerTest.serializes transaction(JsonSerializerTest.kt:623)
```

The code at the line is:
`assertNotNull(element["start_timestamp"] as Double)`

And I'd say what happened was that the timestamp, at the time of the test run, didn't have any fractional value, thus was serialized & deserialized as an integer.

**Comment by adinauer** [comment]
Should be fixed now. Please reopen if it happens again.
