### ISSUE TITLE
Try out JDK 17 for build speed up

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2024]
### Description

https://blog.bitrise.io/post/switch-to-jdk-17-parallel-gc-and-speed-up-your-android-builds-by-9-20

**Comment by bruno-garcia** [comment]
Build is about 15 min so already not too bad

**Comment by philipphofmann** [comment]
> Build is about 15 min so already not too bad

5 minutes would be better 😁

**Comment by bruno-garcia** [comment]
5 seconds even better :trollface:

**Comment by markushi** [comment]
Closing, as we already switched to JDK 17.
