### ISSUE TITLE
Define version constraints for sentry-android-fragment

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2025]
### Description

The `sentry-android-fragment` module depends on `androidx.fragment:fragment-ktx`. This one, in turn, depends on `androidx.lifecycle:lifecycle-viewmodel-ktx`, which had at some point the following change (moving `ViewModelLazyKt` from viewmodel-ktx to viewmodel):
* https://developer.android.com/jetpack/androidx/releases/lifecycle#2.4.0-beta01
* https://android-review.googlesource.com/c/platform/frameworks/support/+/1748234

This change can cause Duplicate classes check to [fail](https://stackoverflow.com/questions/69817925/problem-duplicate-class-androidx-lifecycle-viewmodel-found-in-modules) if the versions of `androidx.lifecycle:viewmodel` and `androidx.lifecycle:viewmodel-ktx` do not much (e.g. `viewmodel` comes as a transitive dependency with a higher version than `viewmodel-ktx`, where this change has been introduced).

In theory, we could mitigate this issue by declaring [dependency constraints](https://docs.gradle.org/current/userguide/dependency_constraints.html) for `androidx.fragment:fragment-ktx`, where we can define a range of allowed transitive dependency versions (`viewmodel-ktx` in this case).

Encountered this issue when using our SAGP auto-installation feature on this [sample project](https://github.com/dorukkangal/braze-sample).

**Comment by marandaneto** [comment]
Does it help if we stop using `fragment-ktx` and use only `fragment`?

**Comment by marandaneto** [comment]
For dependency constraints, we'd need to support Gradle Module Metadata, so it'd not work if using another build system, I guess.

**Comment by romtsn** [comment]
Yeah, but not sure if it's a problem in other build systems (probably it is, but the fraction of those is just too small). So I guess we are good here with just doing it for gradle. 

Using `fragment` would help for this particular case, but again can be a problem, if someone is using `viewmodel-ktx` of an older version, where this class is still present.

**Comment by marandaneto** [comment]
> Using `fragment` would help for this particular case, but again can be a problem, if someone is using `viewmodel-ktx` of an older version, where this class is still present.

Then it's an error on their end since we don't use `ViewModelLazyKt`, right?

**Comment by bruno-garcia** [comment]
We decided to add a troubleshooting page entry for this

**Comment by romtsn** [comment]
So this was actually resolved by #2175 as we declare the transitive dependencies as compileOnly now, and will use whatever the user has defined in their app at runtime, so this problem will not appear anymore.
