### ISSUE TITLE
Isolate cached events with hashed DSN folder

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2026]
### Description

See issue https://github.com/getsentry/sentry-cocoa/issues/1812 for context.
`SentryOptions#cacheDirPath` should be isolated per DSN.
We could hash the DSN and make it a folder, so events from DSN X don't leak to DSN Y.
It's a breaking change so likely do it on v7.

Update the specs as well to consider the isolation https://develop.sentry.dev/sdk/features/#buffer-to-disk

https://github.com/getsentry/sentry-cocoa/blob/e254b733f7706d4c04c02093f5ad0715ced92443/Sources/Sentry/SentryDsn.m#L31-L41

**Comment by bruno-garcia** [comment]
It's out on 6.0.0-rc.1
