### ISSUE TITLE
If StdoutTransport and GsonSerializer are used, the logger does not work properly.

### ISSUE THREAD

**Issue by heowc** [getsentry/sentry-java#2027]
### Integration

sentry

### Java Version

11

### Version

5.2.0

### Steps to Reproduce

1. Set as follows

```java
@Bean
@Profile("local")
ITransportFactory local() {
     return new StdoutTransportFactory();
}

private static class StdoutTransportFactory implements ITransportFactory {
     @Override
     public ITransport create(SentryOptions options, RequestDetails requestDetails) {
         return new StdoutTransport(new GsonSerializer(options));
     }
}
```

2. And send a Sentry event in the middle of the log.

```java
log.info("before:");
Sentry.captureException(new RuntimeException());
log.info("after");
```

3. The output is:

```text
~~~~~~~: before
( blabla~~ )
( blabla~~ )
```

### Expected Result

It should output something like this:

```text
~~~~~~~: before
( blabla~~ )
( blabla~~ )
~~~~~~~: after
```

### Actual Result

```text
~~~~~~~: before
( blabla~~ )
( blabla~~ )
```

**Comment by heowc** [comment]
This is because StdoutTransport provides Sysout.out and GsonSerializer calls flush at the end. 🤔

**Comment by adinauer** [comment]
Thank you @heowc for reporting and also for investigating. I'll take a look and get back to you hopefully later today.
