### ISSUE TITLE
Compare benchmarks with previous versions

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#2037]
### Description

Android has some benchmark ui tests (https://github.com/getsentry/sentry-java/pull/2013) that record several values and check they don't pass a certain threshold, e.g. 5% for profiling, 500 ms to init the sdk, etc.
It would be cool to have a way to compare them with each version of the sdk, to check whether any performance regression was introduced at some point.
Ideally, we could find a way to save all these values in Sentry so that we could retrieve them later and query them in any possible way
The same thing applies to iOS and possibly other platforms, too
@marandaneto Is it fine?

**Comment by adinauer** [comment]
> We could add a file to the GH repo containing a table of benchmark results and commit hashes for storing the results.

Wouldn't that be prone to concurrency issues?

**Comment by philipphofmann** [comment]
> Wouldn't that be prone to concurrency issues?

I don't really understand your question. Can you please elaborate?

**Comment by adinauer** [comment]
Depending on how you want to to this, there might be multiple builds trying to write their result to the file at the same time. Not sure we need to write every result and commit hash, maybe latest result is enough. Could write that to a file named after the branch so this wouldn't only work for master but maybe also for long lived branches like we had with `6.0`.

**Comment by marandaneto** [comment]
> Depending on how you want to do this, there might be multiple builds trying to write their result to the file at the same time. Not sure we need to write every result and commit hash, maybe latest result is enough. Could write that to a file named after the branch so this wouldn't only work for master but maybe also for long lived branches like we had with `6.0`.

That's not a problem, PRs are isolated in a different branch, and even if uploading this file somewhere, let's say using `actions/upload-artifact`, we could use a file name that avoids that.
PRs only read from `main` as well, unless it gets merged with newer baselines.

**Comment by romtsn** [comment]
Here's the relevant github action which already does an APK size diff: [getsentry/action-app-sdk-overhead-metrics](https://github.com/getsentry/action-app-sdk-overhead-metrics)

We could reuse the same infrastructure for storing benchmark results.

**Comment by smeubank** [comment]
benchmarking work comes up in cycles and as far as I know there is no existing effort to this end, let's close until this come back up with some backing to deliver
