### ISSUE TITLE
Investigate JankStats library

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2040]
### Description

https://developer.android.com/topic/performance/jankstats (still in beta)

It could be a replacement for `FrameMetricsAggregator`
https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java

> The JanksStats library offers two additional capabilities that make it more dynamic and easier to use: jank heuristics and UI state.

**Comment by adinauer** [comment]
Could extract the data bag that's available and put it on the transaction when sending to Sentry.

**Comment by adinauer** [comment]
Related to https://github.com/getsentry/team-mobile/issues/55

**Comment by marandaneto** [comment]
Android now recommends improving for 90fps, which means ~11ms per frame instead of 60fps/~16ms, maybe we can consider this when working on the Mobile vitals and how we define slow/frozen frames threshold.

**Comment by romtsn** [comment]
I feel like this is not needed anymore after we've implemented frame delay, #3099
