### ISSUE TITLE
ContextTags are not always taken into account in logging frameworks integration

### ISSUE THREAD

**Issue by maciejwalkowiak** [getsentry/sentry-java#2043]
### Integration

sentry-logback

### Java Version

8

### Version

6.0.0

### Steps to Reproduce

1. Add Sentry appender to `logback.xml`

```
<appender name="sentry" class="io.sentry.logback.SentryAppender"/>
```

2. Initialize Sentry from Java code:

```java
Sentry.init(opts -> {
            opts.setDsn(..);
            opts.addContextTag("userId");
        });
```

3. Put data to MDC and trigger event:

```java
MDC.put("userId", "maciej");
LOGGER.error("Ooops", new RuntimeException());
```

### Expected Result

`userId` value should be set as tag

### Actual Result

`userId` value is set to contexts.

This happens only when Logback/Log4j2 integration is used, but the Sentry init happens in the Java code. Both appenders refer to the `SentryOptions` set on appenders, and not the SentryOptions that are in use by an actual `Sentry` object.

**Comment by marandaneto** [comment]
@maciejwalkowiak is it related to https://github.com/getsentry/sentry-java/pull/1954/files ? if so, we should fix it before going GA.

**Comment by maciejwalkowiak** [comment]
@marandaneto yes, it is. Indeed it should be fixed before GA.
