### ISSUE TITLE
Ser/deser of SentryThreads have wrong value for the `current` boolean

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2047]
### Description

Context https://github.com/getsentry/sentry-dart/pull/847#issuecomment-1125930450

Bug likely introduced by vendoring Gson and doing ser/deser by hand.

**Comment by adinauer** [comment]
@marandaneto are you saying the `DefaultAndroidEventProcessor` overrides whatever is set by hybrid SDKs and that's the problem we should fix?

**Comment by adinauer** [comment]
Opened https://github.com/getsentry/sentry-java/pull/2048 for the current thread not being set in `SentryThreadFactory`.

Do we have a way of detecting we're part of a hybrid SDK run to disable the behaviour in `DefaultAndroidEventProcessor`?

**Comment by marandaneto** [comment]
> Opened #2048 for the current thread not being set in `SentryThreadFactory`.
> 
> Do we have a way of detecting we're part of a hybrid SDK run to disable the behaviour in `DefaultAndroidEventProcessor`?

yes, we use hints for that, check for `shouldApplyScopeData`.
I believe in this case, most likely we should just not overwrite the value when its already set, so its not needed to check if it comes from Hybrid or not.

**Comment by adinauer** [comment]
@marandaneto do you mean like https://github.com/getsentry/sentry-java/pull/2050 or should we check if any thread has already been marked as current, then do nothing in that case?

**Comment by marandaneto** [comment]
> @marandaneto do you mean like #2050 or should we check if any thread has already been marked as current, then do nothing in that case?

yep, I'd just do `if thread.getCurrent != null then continue` so we don't overwrite its value.

**Comment by adinauer** [comment]
Should be fixed via #2050 please reopen if not.
