### ISSUE TITLE
Allow custom instrumentation to collect slow and frozen frames

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2061]
### Description

Right now only `ui.load` transactions add Slow and frozen frames because it depends on using the `activityFramesTracker` and the Activity instance.
We should add an abstraction that if the user is creating custom instrumentation, they don't have to do that manually, but the SDK itself is able to do so, slow and frozen frames are always attached by default on Android.

Related issue https://github.com/getsentry/sentry-java/issues/2101

**Comment by markushi** [comment]
Closing this, as we already attach the slow and frozen frame data to every span.
