### ISSUE TITLE
Unable to manually init transactions

### ISSUE THREAD

**Issue by cmy82** [getsentry/sentry-java#2069]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.1.2

### Proguard

Enabled

### Version

5.7.4

### Steps to Reproduce

When trying to manually initialize transactions :

```
        SentryAndroid.init(this) { options ->
            with(options) {
                dsn = "_dsn_"
                isEnableNdk = false
                release = getString(R.string.sentryReleaseVersion)
                
                isEnableAutoSessionTracking = true
                options.tracesSampleRate = 1.0                
                addIntegration(FragmentLifecycleIntegration(this@GEBApp, enableAutoFragmentLifecycleTracing = true, enableFragmentLifecycleBreadcrumbs = true))

            }
        }
```

I don't get any transactions in Sentry, but with auto-init, they work just fine.

### Expected Result

To see the same transactions I see with the auto-init.

### Actual Result

Nothing

**Comment by romtsn** [comment]
which transactions exactly do not appear? I've just tried your code snippet and it worked fine for me. Maybe you could also post your auto-init config (i.e. Manifest meta-data entries) to compare

**Comment by cmy82** [comment]
Calling the transactions and spans as above works if I set auto-init to true, but if I set it to false and manually init everything (as in the first post) then no transactions are sent. When Sentry does everything, I get all of the transactions and errors, but when manually setting it up, I get nothing. I will check the debug flag and see what happens.

**Comment by cmy82** [comment]
This is the line in my manifest
`<meta-data android:name="io.sentry.auto-init" android:value="false" />`

This is how I init Sentry:
```
        SentryAndroid.init(this) { options ->
            with(options) {
                dsn = "https://9f50c0a42ad04f42b03aa97bdb16aa3a@sentry.io/5184096"
                isEnableNdk = false
                release = getString(R.string.sentryReleaseVersion)
                setDebug(true)

                //screenshot not available yet for android
                // Possibly use to gather user feedback on errors/crashes
                beforeSend = SentryOptions.BeforeSendCallback { event, hint ->
                    event
                }

                isEnableAutoSessionTracking = true
                options.tracesSampleRate = 1.0
                addIntegration(FragmentLifecycleIntegration(this@GEBApp, enableAutoFragmentLifecycleTracing = true, enableFragmentLifecycleBreadcrumbs = true))

            }
        }
```

This is only printout I get in the logs:
```
D/Sentry: io.sentry.auto-init read: false
I/Sentry: Retrieving auto-init from AndroidManifest.xml
```

**Comment by marandaneto** [comment]
@cmy82 where are you placing your `SentryAndroid.init`? can you provide a minimal reproduction example? thanks.

**Comment by cmy82** [comment]
Here is a minimal project with the same behavior:

https://github.com/cmy82/SentryTest
