### ISSUE TITLE
Sentry won't stop threads during web app stop when used with Tomcat 9

### ISSUE THREAD

**Issue by wukrwurk** [getsentry/sentry-java#2074]
### Integration

sentry-spring-boot-starter

### Java Version

11

### Version

5.7.3

### Steps to Reproduce

0. Define a spring boot project, add sentry client to pom.xml
1. Start a tomcat 9 with a war file deployed
2. Redeploy(replace) a war file (without restarting tomcat)

The issue is similar to https://github.com/getsentry/sentry-java/issues/487 or https://github.com/getsentry/sentry-java/issues/420

### Expected Result

Sentry should stop threads once web app is stopped

### Actual Result

org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ftadmin] created a ThreadLocal with key of type [io.sentry.environment.SentryEnvironment$1] (value [io.sentry.environment.SentryEnvironment$1@26c761df]) and a value of type [java.util.concurrent.atomic.AtomicInteger] (value [0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by marandaneto** [comment]
@wukrwurk any news here?

**Comment by wukrwurk** [comment]
@marandaneto @adinauer sorry for a delayed response guys and thanks for looking into this.

Yes the issues is not only in the warning message, web apps consumes a lot of memory. So much that we had to disable it in all our services. We have a bunch(~20) of spring boot services under tomcat9 management and those that have sentry were gobbling memory.

**Comment by adinauer** [comment]
@wukrwurk thanks for the info, we'll look into this but can't say yet if we'll be able to fix this quickly or if it would require bigger changes to how the SDK works. We'll update this issue once we know more.

**Comment by adinauer** [comment]
We'll try to reduce the pain of this by implementing https://github.com/getsentry/sentry-java/issues/2079
