### ISSUE TITLE
Deprecate withScope

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2083]
### Problem Statement

Overloads for `capture` are added via #1829, let's deprecate `withScope` as it has some cases where other calls to capture also have the scope from `withScope`.

### Solution Brainstorm

Deprecate in v6, then remove in v7.

**Comment by marandaneto** [comment]
Unified API didn't deprecate this https://develop.sentry.dev/sdk/unified-api/
Confirm during TSC and update Unified spec?

**Comment by markushi** [comment]
As this came up recently, there are certain use cases for web/backend where `withScope()` makes actually sense. Thus there's no need to deprecate it. Some more javadoc [was added here](https://github.com/getsentry/sentry-java/blob/549cbb4657b9dea1048c4882e79504e87d6acc4f/sentry/src/main/java/io/sentry/IHub.java#L308-L317), as `withScope()` in combination with `globalHubMode` doesn't play well together.
