### ISSUE TITLE
how to ignore info log in issue?

### ISSUE THREAD

**Issue by HantaoCai** [getsentry/sentry-java#2091]
### Integration

sentry-spring-boot-starter

### Java Version

17

### Version

6.0.0

### Steps to Reproduce

```java
     SentryEvent event = new SentryEvent();
                event.setLevel(SentryLevel.INFO);
                event.setTag(BaseConstant.USER_ID, MDC.get(BaseConstant.USER_ID));
                event.setTag(APPID, MDC.get(APPID));
                event.setTag(SENTRY_TYPE, MDC.get(SENTRY_TYPE));
                Message message = new Message();
                message.setMessage(msgContext);
                event.setMessage(message);
                Sentry.captureEvent(event);
```

pom:
```
   <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-logback</artifactId>
            <version>6.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-spring-boot-starter</artifactId>
            <version>6.0.0</version>
        </dependency>
```

here is the  logback issue-level setting:
```
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>debug</level>
        </filter>
        <minimumEventLevel>ERROR</minimumEventLevel>
        <minimumBreadcrumbLevel>debug</minimumBreadcrumbLevel>
```

### Expected Result

I hope the info log is not reported issue....

### Actual Result

<img width="155" alt="image" src="https://user-images.githubusercontent.com/44667064/173228858-e642ac14-40e9-477e-a528-9df9ddd257b9.png">

**Comment by bruno-garcia** [comment]
That option is to control a logger. An explicit capture message always gets sent. If you use logback, it won't

**Comment by bruno-garcia** [comment]
We might need to clarify that on the javadoc of the setter

**Comment by HantaoCai** [comment]
Sir, I want to use info-level logs for data burying, but I don't want to receive issues. Any suggestions?

**Comment by adinauer** [comment]
@HantaoCai have you tried to log a message (e.g. using logback or slf4j) with log level info instead of directly capturing the event using `Sentry.captureEvent`?

As @bruno-garcia explained, `<minimumEventLevel>ERROR</minimumEventLevel>` does not have an effect on direct calls to `Sentry.capture...`, only on events that have been picked up from log messages. That's why it doesn't work in your example above.

**Comment by marandaneto** [comment]
In case you want to filter out events with a lower level, even for manually captured events using the `Sentry` class, you can set up a `beforeSend` callback https://docs.sentry.io/platforms/java/configuration/filtering/

**Comment by adinauer** [comment]
@HantaoCai were we able to help you? Or do you need more help?

**Comment by HantaoCai** [comment]
> 

I have tried this, but I hope that the buried data can be viewed in the sentry system. If I use log.info() to record the buried data, I will not be able to find it in the sentry system, it will only be available in the log file.

**Comment by HantaoCai** [comment]
> In case you want to filter out events with a lower level, even for manually captured events using the `Sentry` class, you can set up a `beforeSend` callback https://docs.sentry.io/platforms/java/configuration/filtering/ In this case, events will never come thru, so you won't see them.

![image](https://user-images.githubusercontent.com/44667064/173731297-75ab59a5-9428-4837-b247-abd0e24645c3.png)
After the configuration like you suggested, the sentry system can't receive any messages, where can I find my buried data in sentry system?

**Comment by maciejwalkowiak** [comment]
@HantaoCai Calling `SpringApplication.run` blocks until Spring application shuts down. If you really want to init Sentry manually, you should do it before Spring Boot application starts.

If you prefer to rely on auto configuration, you can also define `SentryOptions.BeforeSendCallback` as a bean and it will be set on Sentry option automatically.

**Comment by HantaoCai** [comment]
> @HantaoCai Calling `SpringApplication.run` blocks until Spring application shuts down. If you really want to init Sentry manually, you should do it before Spring Boot application starts.
> 
> If you prefer to rely on auto configuration, you can also define `SentryOptions.BeforeSendCallback` as a bean and it will be set on Sentry option automatically.

It doesn't block and can be executed, but not what I expected.

**Comment by adinauer** [comment]
@HantaoCai you can either have the events sent to Sentry and show up as issues or filter them in the SDK and not send them to Sentry at all as you did with `beforeSend`.

**Comment by marandaneto** [comment]
@HantaoCai 

> After the configuration like you suggested, the sentry system can't receive any messages, where can I find my buried data in sentry system?

That's not possible, either you filter out events and don't send them to sentry or you send them and filter in the dashboard using the discover queries such as `level:error`.
https://docs.sentry.io/product/sentry-basics/search/

**Comment by HantaoCai** [comment]
> @HantaoCai
> 
> > After the configuration like you suggested, the sentry system can't receive any messages, where can I find my buried data in sentry system?
> 
> That's not possible, either you filter out events and don't send them to sentry or you send them and filter in the dashboard using the discover queries such as `level:error`. https://docs.sentry.io/product/sentry-basics/search/

@marandaneto 
Okay, I will choose to ignore the buried data in the Sentry issue.  Thanks for your advice.

**Comment by adinauer** [comment]
Closing as it seems you have found a way of working around this. Feel free to reopen if you need more help on this.
