### ISSUE TITLE
Sentry fails to send transaction (payload too large)

### ISSUE THREAD

**Issue by buckett** [getsentry/sentry-java#2092]
### Integration

sentry-spring-boot-starter

### Java Version

11

### Version

5.4.2

### Steps to Reproduce

We have a batch job that has sentry integration and we annotated the whole job as a `@SentryTransaction` and within that job there are lots of `@SentrySpan` (too many). But we were seeing that in some environments transactions weren't getting sent through. Initially we thought this was an inconsistency in our configuration. But after enabling `sentry.debug` we saw that we were getting this logged:

```
  | 2022-06-12T22:37:28.918+01:00 | DEBUG: Shutting down
-- | -- | --
  | 2022-06-12T22:37:30.107+01:00 | ERROR: Request failed, API returned 413
  | 2022-06-12T22:37:30.108+01:00 | ERROR: {"detail":"failed to read request body","causes":["A payload reached size limit."]}
  | 2022-06-12T22:37:30.108+01:00 | ERROR: The transport failed to send the envelope with response code 413
  | 2022-06-12T22:37:30.108+01:00 | ERROR: Envelope submission failed
  | 2022-06-12T22:37:30.108+01:00 | java.lang.IllegalStateException: The transport failed to send the envelope with response code 413
  | 2022-06-12T22:37:30.108+01:00 | java.lang.IllegalStateException: The transport failed to send the envelope with response code 413
  | 2022-06-12T22:37:30.108+01:00 | at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:220)
  | 2022-06-12T22:37:30.108+01:00 | at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
  | 2022-06-12T22:37:30.108+01:00 | at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  | 2022-06-12T22:37:30.108+01:00 | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  | 2022-06-12T22:37:30.108+01:00 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | 2022-06-12T22:37:30.108+01:00 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | 2022-06-12T22:37:30.108+01:00 | at java.base/java.lang.Thread.run(Unknown Source)

```

Now it became obvious that we need to reduce the amount of data that is being included in this transaction. 

It looks like https://develop.sentry.dev/sdk/client-reports/ might have allowed us to know about the events getting dropped, so according to https://docs.sentry.io/platforms/java/configuration/options/#send-client-reports if we upgrade to version 6+ we might have better visibility into this.

### Expected Result

It would have been much easier to debug if sentry didn't silently drop this. We aren't seeing any dropped or filtered events for this application in the sentry web UI.

### Actual Result

Events are silently thrown away.

**Comment by buckett** [comment]
On the surface this looks similar to https://github.com/getsentry/sentry-java/issues/910

I'm going to see if we can upgrade to a later Sentry integration and check to see if we get a client report for the dropped event.

**Comment by adinauer** [comment]
Hello @buckett starting with `6.0.0` of the Java SDK you should start seeing the number of dropped events etc. in the UI.

Would you require more detail than a simple count of dropped items? Or is having the count good enough to make you aware of an issue and dig on your own (e.g. using `debug=true`)?

Were you able to pinpoint what's causing your large payload?

**Comment by adinauer** [comment]
There's a `maxSpans` option that might help if it's just the number of spans causing your problem.

**Comment by buckett** [comment]
Ok, the simplest thing for us (to get transactions working again) is to probably just set `maxSpans` as I see it's available: https://github.com/getsentry/sentry-java/blob/3f8d7b1cc869bb056c9db99b459e43f6c375784a/sentry/src/main/java/io/sentry/SentryOptions.java#L1381

For anyone else in the future this might not always be available as integrations don't have to allow this to be set (as outlined on https://develop.sentry.dev/sdk/performance/#maxspans) and I'm guessing that's why it's not documented on: https://docs.sentry.io/platforms/java/configuration/options/#send-client-reports

**Comment by buckett** [comment]
One of the events that did successfully get processed (containing 1000 spans) is shown in the web UI as being 458kb!

<img width="1599" alt="Screenshot 2022-06-13 at 10 28 59" src="https://user-images.githubusercontent.com/5921/173323783-d9d47215-c853-494c-a474-01f3a483b035.png">

Most of that is taken up with span data.

The documentation seems to say that there is a 200kb limit for events (https://develop.sentry.dev/sdk/event-payloads/), do transactions also have this limit applied? Is compression cause us to be able to send a larger event?

**Comment by adinauer** [comment]
Hmm maybe your span data sometimes makes it, sometimes not depending on how well it compresses.

Are you OK with the `maxSpans` solution?

**Comment by buckett** [comment]
Yep. Thanks for your help on this.
