### ISSUE TITLE
Spring Data Repositories are not instrumented

### ISSUE THREAD

**Issue by Ramblurr** [getsentry/sentry-java#2099]
### Integration

sentry-spring

### Java Version

11

### Version

6.0.0

### Steps to Reproduce

1. Configure project with `io.sentry:sentry-spring-boot-starter` dependency
2. Configure project to emit instrumentation traces
3. Add `@SentrySpan` to your spring data repository interface type

### Expected Result

All method calls to the spring data repository should emit spans

### Actual Result

No spans are emitted

The only mention of spring data repositories I can find in this project is from this old PR https://github.com/getsentry/sentry-java/pull/1024

**Comment by adinauer** [comment]
@Ramblurr can you please give `sentry-jdbc` a try?

It'll give you something like this:

```
DEBUG: Serializing object: {
    "transaction": "GET /product/{id}",
    "start_timestamp": 1655217215.598000,
    "timestamp": 1655217215.610401,
    "spans": [
        {
            "start_timestamp": 1655217215.606000,
            "timestamp": 1655217215.606347,
            "trace_id": "0c43715496424fc0b78b42846c6f9942",
            "span_id": "03260eaa0f1c4e8a",
            "parent_span_id": "d78084117a4a40c7",
            "op": "db.query",
            "description": "select product0_.id as id1_0_0_, product0_.name as name2_0_0_ from product product0_ where product0_.id=?",
            "status": "ok",
            "data": {}
        }
    ],
    "type": "transaction",
...
```

**Comment by maciejwalkowiak** [comment]
@Ramblurr adding `@SentrySpan` on the top of the repository interface will add span around each method invocation - both those declared in the interface and ones that are inherited from parent interface (like `CrudRepository`). The invocation must happen during already running transaction (like an HTTP request processed by Spring MVC). 

Please find a repository with a test simulating instrumenting Spring Data repository: https://github.com/maciej-scratches/sentry-java-gh-2099/blob/master/src/test/java/com/example/demo/DemoApplicationTests.java

I am closing it for now, but if you find something that isn't working, please comment and ideally provide a sample that reproduces your issue.
