### ISSUE TITLE
Mobile Vitals for UI events transactions

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2101]
Report slow and frozen frames for recently added UI events transactions on [iOS](https://github.com/getsentry/sentry-cocoa/pull/1784) and [Android](https://github.com/getsentry/sentry-java/pull/1975).

**Comment by philipphofmann** [comment]
> As I understood, this is already done on iOS for every transaction, since they don't need the instance of the view such as `activity`.

Yes, indeed.

**Comment by adinauer** [comment]
Would probably need to replace `ActivityFramesTracker` with something based on `choreographer.postFrameCallback(frameCallback)` similar to what is done here https://github.com/getsentry/sentry-java/blob/730095684bb732a0a7d0cc88d3c3b913a08d7cfe/sentry-android-integration-tests/sentry-uitest-android-benchmark/src/androidTest/java/io/sentry/uitest/android/benchmark/util/BenchmarkOperation.kt#L142-L166

This would then also be helpful for FPS Mobile Vitals.

**Comment by markushi** [comment]
This is already done for Profiling, as frame metrics are already collected on a frame by frame level.

**Comment by markushi** [comment]
It could make sense to re-use the frame-by-frame profiling collector in case there isn't too much of an overhead.

**Comment by romtsn** [comment]
this is superseded by mobile starfish and will be tackled by the mobile interfactions module
