### ISSUE TITLE
SpringBoot Log4j2 log not sending event to Sentry

### ISSUE THREAD

**Issue by checkcheckrockrock** [getsentry/sentry-java#2104]
### Integration

sentry-log4j2

### Java Version

8

### Version

6.1.0

### Steps to Reproduce

I have issue the with springboot & log4j2 integration the log4j log is not showing in Sentry.

1. Configure project with io.sentry:sentry-spring-boot-starter and sentry-log4j2 dependency https://github.com/checkcheckrockrock/springboot-log4j2-sentry
2. Create simple Rest API to push event to Sentry eg:  logger.error("This is a test");
3. Call the API to trigger event to be push to Sentry http://localhost:8080/

### Expected Result

Logged event should be push to Sentry

### Actual Result

No event log push to Sentry

**Comment by maciejwalkowiak** [comment]
@checkcheckrockrock thanks for providing a sample - it makes it much easier to find out the cause of the problem.

In your particular case - you still have Logback on your classpath, and Log4j configuration just doesn't start.

Make sure to exclude Logback, or in this particular case `spring-boot-starter-logging` from all dependencies that include it. You can get all the details by running `mvn dependency:tree`. 

In this particular case, exclude it from the Actuator dependency:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
	<exclusions>
		<exclusion>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-logging</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

**Comment by checkcheckrockrock** [comment]
> ```
> <exclusions>
> 		<exclusion>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-logging</artifactId>
> 		</exclusion>
> 	</exclusions>
> ```

Hi @maciejwalkowiak , thank you for your suggestion. The project able to send the log event to Sentry already.

**Comment by maciejwalkowiak** [comment]
Great! Happy to help @checkcheckrockrock
