### ISSUE TITLE
RootChecker Causes CTS Failure

### ISSUE THREAD

**Issue by herriojr** [getsentry/sentry-java#2108]
### Integration

sentry-android

### Build System

Other

### AGP Version

Not the issue

### Proguard

Enabled

### Version

5.6.3

### Steps to Reproduce

Build sentry into an application which is included in an android system image. Watch it fail CTS due to RootChecker. We need a way to not include the RootChecker code at all.

Unfortunately, removing and replacing a class from a dependency has proven painful.

### Expected Result

It passes CTS

### Actual Result

It does not pass CTS.

**Comment by romtsn** [comment]
Hey, sorry, I'm not familiar with developing custom ROMs. What code exactly causes the problem? It cannot be the entire class, right, is it the ctor of RootChecker?

I'm also not sure if we ever meant to support this case (@marandaneto wdyt?), so you are probably better off doing it yourself. You could:
* Strip out this class if you are using R8 or Proguard
* Checkout the sentry-java repo, customize it and distribute it locally to your local maven/company's repository/etc.
* Shade the dependency and remove the class

**Comment by herriojr** [comment]
I'm not against stripping it but it relies on the code using it to handle the class not existing. If that's already there, I'll use that. I was trying to avoid forking the project. Basically CTS checks for things that could potentially be trying to gain root privs. Hence the class is flagged because it is scanning for su.

**Comment by marandaneto** [comment]
@herriojr by CTS do you mean https://source.android.com/compatibility/cts ?
Right now the only option is to remove the `DefaultAndroidEventProcessor`, ideally `RootChecker` would have an interface that you can override or a flag that enables or disable this behavior, such as `SentryAndroidOptions#checkDetection` or something.
@herriojr would you like to submit a PR adding such a flag?

**Comment by romtsn** [comment]
I think this class should be moved into a separate module even. As I understood, the problem is that it exists on the classpath, CTS does not check whether it's used or not.

**Comment by herriojr** [comment]
Yes, that's correct. It would need to be a different module that could be
excluded without crashing.  I can whip something up when I get a chance.

**Comment by adinauer** [comment]
We understand this is inconvenient for you but it's not something we're looking to add. Please feel free to fork the SDK and e.g. make the RootChecker a NOOP.
