### ISSUE TITLE
Flaky ApacheHttpClientTransportTest Test

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2112]
### Integration

sentry

### Java Version

11

### Version

6.1.1

### Steps to Reproduce

Run tests on CI

### Expected Result

No failure

### Actual Result

Flaky test

```

**Comment by philipphofmann** [comment]
Isn't this a duplicate of https://github.com/getsentry/sentry-java/issues/2113, @adinauer?

**Comment by adinauer** [comment]
Thanks, guess my browser wanted to have this twice
