### ISSUE TITLE
Lazily create `Timer` to avoid creating not needed threads

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2115]
### Description

ThreadPools> 12887 total threads. Threadpools with more than 5 threads:  Timer (12711 threads) 

Which led to:

app/worker.7 java.lang.OutOfMemoryError: unable to create new native 
app/worker.7     at java.lang.Thread.start0(Native Method) 
app/worker.7     at java.lang.Thread.start(Thread.java:719) 
app/worker.7     at java.util.Timer.<init>(Timer.java:176) 
app/worker.7     at java.util.Timer.<init>(Timer.java:146) 
app/worker.7     at io.sentry.SentryTracer.<init>(SentryTracer.java:68) 

https://github.com/getsentry/sentry-java/blob/b571aaedcfc7f7d1bd47aad5c075e901858e641f/sentry/src/main/java/io/sentry/SentryTracer.java?rgh-link-date=2022-06-20T13%3A54%3A07Z#L68
`SentryTracer#timer` only if `idleTimeout != null` apparently.

Also `LifecycleWatcher#timer` only if `enableSessionTracking` is enabled.

**Comment by adinauer** [comment]
For later we can try to reuse timer, created an issue for it here https://github.com/getsentry/sentry-java/issues/2130

For now we'll try to send a PR soon to only create the `Timer` if needed.

**Comment by adinauer** [comment]
Our assumption is that `LifecycleWatcher` only exists once and thus only creates a single thread on Android.

For `SentryTracer` we have a PR coming soon to only instantiate the `Timer` if `idleTimeout` is set for the `SentryTracer` and also call `cancel` on the timer when the transaction is finished.

**Comment by adinauer** [comment]
Even after the PR there might still be a problem on Android when lots of different gestures are started as each of them will then also create a new `Timer` (and thus a new thread). This should be fixed with #2130 .

**Comment by marandaneto** [comment]
> Our assumption is that `LifecycleWatcher` only exists once and thus only creates a single thread on Android.

Yes, it's much less of a problem, but no need to create the timer if the `enableSessionTracking` feature is disabled.

> For `SentryTracer` we have a PR coming soon to only instantiate the `Timer` if `idleTimeout` is set for the `SentryTracer` and also call `cancel` on the timer when the transaction is finished.
