### ISSUE TITLE
Setting the user on a non-main thread does not work

### ISSUE THREAD

**Issue by welniak** [getsentry/sentry-java#2119]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.4

### Proguard

Enabled

### Version

5.6.1

### Steps to Reproduce

1. Create a user object with an id and set it by calling `Sentry.setUser` from a thread that is not the main thread.
2. Observe the events sent to sentry.

### Expected Result

The user info is correctly set and sent to sentry along with the event or the docs are updated to make this main thread requirement explicit. 

### Actual Result

The user info is missing from the events sent to sentry, in most cases, when the user info is set from a non-main thread (sometimes it is sent but it's a great minority of cases). The issue seems to be gone when the user info is set from the main thread. Did not find an explicit reference to that in the docs.

**Comment by romtsn** [comment]
Hm, from a quick look I can't spot the problem, maybe @marandaneto or @bruno-garcia have ideas?

**Comment by marandaneto** [comment]
There's a single Hub and single Scope, this should not be a problem at all, @welniak can you give us a minimal reproduction example? thanks.

**Comment by philipphofmann** [comment]
@welniak, any update from your side ⬆️ ?

**Comment by romtsn** [comment]
@welniak thanks a lot for the details, we will look into this in the near future (no ETA though). And sorry for the delays.

**Comment by marandaneto** [comment]
@welniak do you call by any chance the `Sentry.setUser(user)` before the SDK got the chance to be inited?

**Comment by welniak** [comment]
Hey @marandaneto, here's some more context about our set-up:
- we init Sentry programmatically,
- the initialisation is done inside of an `Initializer` class,
- the flow is as follows:

```kotlin
override fun create(context: Context) {
    val entryPoint = EntryPointAccessors.fromApplication(
        context.applicationContext,
        SentryInitializerEntryPoint::class.java
    )

    Sentry.init { options: SentryOptions ->
       // set the dsn, environment, release, etc.
    }

    // here we start observing the database and call Sentry.setUser(user) when new user info is emitted from the db
    entryPoint.userObserver().start()
}
```

**Comment by marandaneto** [comment]
@welniak Are you using the `Sentry` or `SentryAndroid` `init` method?

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/android/configuration/manual-init/
You've to use `SentryAndroid.init`.

**Comment by welniak** [comment]
🤦  thank you, I must've seen this page 20 times and never noticed it, indeed this solves it!
