### ISSUE TITLE
Some callbacks do not have their Exceptions caught yet

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2123]
### Integration

sentry

### Java Version

any

### Version

6.1.2

### Steps to Reproduce

There are multiple places where an Exception thrown by a callback is not caught.

- `SentryAndroid.init` param `Sentry.OptionsConfiguration<SentryAndroidOptions> configuration`
- Local scope callback for `captureX` methods with param `ScopeCallback callback`
- *... there's probably more*

### Expected Result

Exceptions should be caught and we should downgrade gracefully (throw away an event, don't enable the SDK, ...).

### Actual Result

Exceptions are not caught

**Comment by marandaneto** [comment]
> If we decide to throw away the event, we should ensure this information ends up in [client reports](https://develop.sentry.dev/sdk/client-reports/).

Actually, it's the opposite, by swallowing the exception during eg `beforeSend`, we make sure that events get sent.

**Comment by markushi** [comment]
Potential callbacks which could crash [WIP]

via IHub
| method | has try/catch | has logging | note |
| --- | --- | --- | --- |
| `withScope / ScopeCallback.run` | x | x | |
| `configureScope / ScopeCallback.run` | x | x | |
| `bindClient / ISentryClient.isEnabled` |  |  | unused / only used in tests?? |
| `bindClient / ISentryClient.captureEvent` | x | x | |
| `bindClient / ISentryClient.close` | x | x | |
| `bindClient / ISentryClient.flush` | x | x | |
| `bindClient / ISentryClient.captureEvent` | x | x | |
| `bindClient / ISentryClient.captureMessage` | x | x | |
| `bindClient / ISentryClient.captureException` | x | x | not used by Hub (calls `captureEvent`) |
| `bindClient / ISentryClient.captureUserFeedback` | x | x | |
| `bindClient / ISentryClient.captureSession` |  | | used by `Hub.startSession/endSession` |
| `bindClient / ISentryClient.captureEnvelope` |  | | on Hub: @ApiStatus.Internal |
| `bindClient / ISentryClient.captureTransaction` | x | x | on Hub: @ApiStatus.Internal |



via SentryOptions
| method | has try/catch | has logging | note |
| --- | --- | --- | --- |
| `BeforeSendCallback` | x | x | `called by SentryClient.captureEvent` |
| `BeforeBreadcrumbCallback` | x | x | `called by Scope.addBreadcrumb` | 
| `SentryClient.processEvent` | x | x | called by 'captureEvent` |
| `Integration.register` | | | called by `Sentry.init` |
| `TracesSamplerCallback` | | | called by `TracesSampler.sample` |
| `ProfilesSamplerCallback.*` | | | called by `TracesSampler.sample` |
| `EventProcessor.close` | x | x | called by `SentryClient.close` |
| `EventProcessor.process` | x | x | called by `SentryClient.captureEvent + captureTransaction` |
| `EventProcessor.close` | x | x | called by `SentryClient.close` |
| `ILogger.*` | | | |
| `IEnvelopeReader.read` | | |
| `IDebugImagesLoader.*` | | |
| `IEnvelopeCache.*` | | |
| `IEnvelopeReader.*`  | | |
| `HostnameVerifier.*` | | |
| `SSLSocketFactory.*`  | | |
| `ISerializer.*` | | |
| `ITransactionProfiler` | | |
| `ITransportFactory` | | |
| `ITransportGate` | | |
| `ISentryExecutorService` | | |
| `IScopeObserver` | | |
| `IClientReportRecorder` | | |
