### ISSUE TITLE
Bump minAPI to 19

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2126]
### Description

![Screenshot 2022-06-22 at 11 08 59](https://user-images.githubusercontent.com/5731772/174990874-fa1283f7-850f-4636-9bdf-2a060c6c9256.png)

Remove workaround for API 14-16 https://docs.sentry.io/platforms/android/using-ndk/#api-level-lower-than-16
Add breaking change entry to migration docs.

**Comment by bruno-garcia** [comment]
https://developer.android.com/studio/releases/platforms#4.1

**Comment by romtsn** [comment]
It's already 19 in the meantime 

![Image](https://user-images.githubusercontent.com/4999776/230142714-f4d21b0d-2ef5-4259-9718-3ca8d6ed1288.png)

Moreover, the new project wizard in Android Studio does not let me pick API version lower than 21. So imho we'll be fine even with 21 as min version. 

![Image](https://user-images.githubusercontent.com/4999776/230142962-41ce650a-f3cf-4ad8-a4d7-57bbb53b58bd.png)

**Comment by romtsn** [comment]
@markushi @stefanosiano opinions on that^?

**Comment by bruno-garcia** [comment]
API 14 forever :trollface:

**Comment by romtsn** [comment]
> API 14 forever :trollface: - Kidding btw, just felt like trolling this OG ticket. Have fun ripping off all those hacks from the past

And no Kotlin for sentry-android :P

**Comment by marandaneto** [comment]
Flutter still supports 19-20 best-effort https://docs.flutter.dev/reference/supported-platforms
@krystofwoldrich can you confirm for RN?
Maybe we bump to 19 for now?

**Comment by romtsn** [comment]
yeah, sounds good

**Comment by krystofwoldrich** [comment]
[The Oldest version of RN we support has min 21.
](https://github.com/facebook/react-native/blob/0.65-stable/ReactAndroid/build.gradle#L390)

Our RN SDK has also min 21.

**Comment by bruno-garcia** [comment]
@bitsandfoxes how about Unity?

**Comment by romtsn** [comment]
Closed by #2883

**Comment by bitsandfoxes** [comment]
Unity LTS 2020 supports `r19`
