### ISSUE TITLE
Sending event succeed, but  not show up on the Sentry Issues

### ISSUE THREAD

**Issue by ckrgithub** [getsentry/sentry-java#2132]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.4

### Proguard

Enabled

### Version

6.1.0

### Steps to Reproduce

my code:

        Sentry.captureMessage("testing SDK setup");
        try {
            throw new Exception("This is a test.");
        } catch (Exception e) {
            Sentry.captureException(e);
        }

        <meta-data android:name="io.sentry.dsn" android:value="@string/sentry_dsn" />
        
        <meta-data android:name="io.sentry.debug" android:value="true" />
        
        <meta-data android:name="io.sentry.session-tracking.timeout-interval-millis" android:value="5000" />
        <meta-data android:name="io.sentry.traces.sample-rate" android:value="1.0" />

### Expected Result

Sentry Id is created after capturing events and exceptions, so we expect them to show up on Sentry dashboard.
[](url)

### Actual Result

**Logs uploaded successfully:**
2022-06-24 11:05:21.005 8710-8710/com.rtasg.intl D/Sentry: Capturing transaction: 50d48be77d3a4bb49b7fe0048fb12264
2022-06-24 11:05:21.013 8710-8823/com.rtasg.intl D/Sentry: Serializing object: {
    	"timestamp": "2022-06-24T03:05:20.895Z",
    	"exception": {
    		"values": [
    			{
    				"type": "Exception",
    				"value": "This is a test.",
    				"module": "java.lang",
    				"thread_id": 2,
    				"stacktrace": {
    					"frames": [
    						{
    							"filename": "ZygoteInit.java",
    							"function": "main",
    							"module": "com.android.internal.os.ZygoteInit",
    							"lineno": 1003,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "RuntimeInit.java",
    							"function": "run",
    							"module": "com.android.internal.os.RuntimeInit$MethodAndArgsCaller",
    							"lineno": 548,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "Method.java",
    							"function": "invoke",
    							"module": "java.lang.reflect.Method",
    							"in_app": false,
    							"native": true
    						},
    						{
    							"filename": "ActivityThread.java",
    							"function": "main",
    							"module": "android.app.ActivityThread",
    							"lineno": 7839,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "Looper.java",
    							"function": "loop",
    							"module": "android.os.Looper",
    							"lineno": 288,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "Looper.java",
    							"function": "loopOnce",
    							"module": "android.os.Looper",
    							"lineno": 201,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "Handler.java",
    							"function": "dispatchMessage",
    							"module": "android.os.Handler",
    							"lineno": 106,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "ActivityThread.java",
    							"function": "handleMessage",
    							"module": "android.app.ActivityThread$H",
    							"lineno": 2210,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "TransactionExecutor.java",
    							"function": "execute",
    							"module": "android.app.servertransaction.TransactionExecutor",
    							"lineno": 95,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "TransactionExecutor.java",
    							"function": "executeCallbacks",
    							"module": "android.app.servertransaction.TransactionExecutor",
    							"lineno": 135,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "LaunchActivityItem.java",
    							"function": "execute",
    							"module": "android.app.servertransaction.LaunchActivityItem",
    							"lineno": 103,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "ActivityThread.java",
    							"function": "handleLaunchActivity",
    							"module": "android.app.ActivityThread",
    							"lineno": 3792,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "ActivityThread.java",
    							"function": "performLaunchActivity",
    							"module": "android.app.ActivityThread",
    							"lineno": 3608,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "Instrumentation.java",
    							"function": "callActivityOnCreate",
    							"module": "android.app.Instrumentation",
    							"lineno": 1329,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "Activity.java",
    							"function": "performCreate",
    							"module": "android.app.Activity",
    							"lineno": 8031,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "Activity.java",
    							"function": "performCreate",
    							"module": "android.app.Activity",
    							"lineno": 8051,
    							"in_app": false,
    							"native": false
    						},
    						{
    							"filename": "SourceFile",
    							"function": "onCreate",
    							"module": "com.wm.dmall.LaunchActivity",
    							"lineno": 2,
    							"in_app": false,
    							"native": false
    						}
    					]
    				}
    			}
    		]
    	},
    	"transaction": "LaunchActivity",
    	"fingerprint": [],
    	"event_id": "38bd147b482c46f59e7eca55ff1a93d6",
    	"contexts": {
    		"app": {
    			"app_identifier": "com.rtasg.intl",
2022-06-24 11:05:21.013 8710-8823/com.rtasg.intl D/Sentry: 			"app_start_time": "2022-06-24T03:05:18.522Z",
    			"app_name": "Cart",
    			"app_version": "5.4.0",
    			"app_build": "57",
    			"permissions": {
    				"WRITE_SETTINGS": "not_granted",
    				"READ_LOGS": "not_granted",
    				"ACCESS_LAUNCHER_DATA": "not_granted",
    				"RECORD_AUDIO": "not_granted",
    				"FOREGROUND_SERVICE": "granted",
    				"ACCESS_FINE_LOCATION": "granted",
    				"INSTALL_SHORTCUT": "granted",
    				"RECEIVE": "granted",
    				"ACCESS_NETWORK_STATE": "granted",
    				"CHANGE_WIFI_STATE": "granted",
    				"READ_SETTINGS": "not_granted",
    				"WAKE_LOCK": "granted",
    				"UNINSTALL_SHORTCUT": "granted",
    				"BLUETOOTH_CONNECT": "granted",
    				"WRITE_EXTERNAL_STORAGE": "granted",
    				"READ_PRIVILEGED_PHONE_STATE": "not_granted",
    				"MODIFY_AUDIO_SETTINGS": "granted",
    				"INTERNET": "granted",
    				"READ_EXTERNAL_STORAGE": "granted",
    				"SYSTEM_ALERT_WINDOW": "not_granted",
    				"ACCESS_LOCATION_EXTRA_COMMANDS": "granted",
    				"RECEIVE_BOOT_COMPLETED": "granted",
    				"MOUNT_UNMOUNT_FILESYSTEMS": "not_granted",
    				"CAMERA": "not_granted",
    				"BIND_GET_INSTALL_REFERRER_SERVICE": "not_granted",
    				"BLUETOOTH_ADMIN": "granted",
    				"intl": "granted",
    				"CHANGE_CONFIGURATION": "not_granted",
    				"ACCESS_COARSE_LOCATION": "granted",
    				"READ_PHONE_STATE": "granted",
    				"GET_TASKS": "granted",
    				"BLUETOOTH_ADVERTISE": "granted",
    				"BLUETOOTH": "granted",
    				"BLUETOOTH_SCAN": "granted",
    				"VIBRATE": "granted",
    				"ACCESS_WIFI_STATE": "granted"
    			}
    		},
    		"device": {
    			"name": "sdk_gphone64_arm64",
    			"manufacturer": "Google",
    			"brand": "google",
    			"family": "sdk_gphone64_arm64",
    			"model": "sdk_gphone64_arm64",
    			"model_id": "SE1A.220203.002.A1",
    			"archs": [
    				"arm64-v8a"
    			],
    			"battery_level": 100.0,
    			"charging": false,
    			"online": true,
    			"orientation": "portrait",
    			"simulator": true,
    			"memory_size": 2061529088,
    			"free_memory": 959578112,
    			"low_memory": false,
    			"storage_size": 1040080896,
    			"free_storage": 486289408,
    			"screen_width_pixels": 1080,
    			"screen_height_pixels": 2196,
    			"screen_density": 3.0,
    			"screen_dpi": 480,
    			"boot_time": "2022-06-24T02:10:31.286Z",
    			"timezone": "Asia/Shanghai",
    			"id": "e83b27a3-2833-421e-818b-a0c21b5d86e5",
    			"language": "en",
    			"connection_type": "wifi",
    			"battery_temperature": 25.0,
    			"locale": "en"
    		},
    		"os": {
    			"name": "Android",
    			"version": "12",
    			"build": "sdk_gphone64_arm64-userdebug 12 SE1A.220203.002.A1 8151367 dev-keys",
    			"kernel_version": "5.10.66-android12-9-00021-g2c152aa32942-ab8087165",
    			"rooted": false
    		},
    		"trace": {
    			"trace_id": "cb7bd3ae9ab44e0bbde4d1f213ec1319",
    			"span_id": "65712d091f3b4ee5",
    			"parent_span_id": "04ae5d1743b24105",
    			"op": "app.start.cold",
    			"description": "Cold Start"
    		}
    	},
    	"sdk": {
    		"name": "sentry.java.android",
    		"version": "6.1.0",
    		"packages": [
    			{
    				"name": "maven:io.sentry:sentry",
    				"version": "6.1.0"
    			},
    			{
    				"name": "maven:io.sentry:sentry-android-core",
    				"version": "6.1.0"
    			},
    			{
    				"name": "maven:io.sentry:sentry-android-ndk",
    				"version": "6.1.0"
    			}
    		]
    	},
    	"tags": {
    		"isSideLoaded": "true"
    	},
    	"release": "com.rtasg.intl@5.4.0+57",
    	"environment": "production",
    	"platform": "java",
    	"user": {
    		"id": "e83b27a3-2833-421e-818b-a0c21b5d86e5"
    	},
    	"dist": "57",
    	"breadcrumbs": [
    		{
    			"timestamp": "2022-06-24T03:05:20.520Z",
    			"type": "navigation",
    			"data": {
    				"screen": "LaunchActivity",
    				"state": "created"
    			},
    			"category": "ui.lifecycle",
    			"level": "info"
    		}
    	]
    }
2022-06-24 11:05:21.163 8710-8823/com.rtasg.intl D/Sentry: **Envelope sent successfully.**
2022-06-24 11:05:21.163 8710-8823/com.rtasg.intl D/Sentry: Discarding envelope from cache: /data/user/0/com.rtasg.intl/cache/sentry/e532c15da754d76469ae9fd55d490ac844c0947/38bd147b482c46f59e7eca55ff1a93d6.envelope
2022-06-24 11:05:21.163 8710-8823/com.rtasg.intl D/Sentry: Envelope flushed
2022-06-24 11:05:21.164 8710-8823/com.rtasg.intl W/Sentry: Current session is not ended, we'd need to end it.

**But It didn't show up on the Sentry Issues.**
![image](https://user-images.githubusercontent.com/18225851/175450909-24abd878-0aff-4513-97ef-2b800c17a984.png)

**Comment by romtsn** [comment]
are you using Sentry self-hosted or SaaS? If SaaS - we had an incident recently in event processing, could you retry it?

**Comment by philipphofmann** [comment]
@ckrgithub, any updates on this one? ⬆️

**Comment by romtsn** [comment]
I suspect the issue is either on your device or your Sentry self-hosted instance if you're using it, otherwise we'd have many reports from other clients I'd assume. Please reopen with a minimal reproducible example if it's still a problem on our side.
