### ISSUE TITLE
Switch from empty AndroidManifest to namespace

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2133]
### Description

AGP will not allow using `package` attribute on an empty AndroidManifest starting from [version 8.0](https://issuetracker.google.com/issues/200682321) (we use it a lot, since we publish android libraries without UI). We should specify a `namespace` attribute in the `android { }` Gradle DSL instead.

Some automation script on how to do it:
https://twitter.com/JakeWharton/status/1540075477108490246?s=20&t=VN5FPQPh_Nf87VXw6038ng 

This will also avoid the manifest merging task altogether

**Comment by philipphofmann** [comment]
@romtsnl, can you maybe add the most important info for this issue here and mention the link as a resource? The tweet could disappear and then the info is lost.

**Comment by stefanosiano** [comment]
merged into master
