### ISSUE TITLE
`JsonObjectReader#nextList` ideally is renamed to `nextListOrNull` in case the list is empty or invalid

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2151]
### Description

```
{
  "breadcrumbs": []
}
```

Currently, an empty list that is deserialized via `nextList` throws if the list is empty or invalid.
The logger is `Failed to deserialize object in list.`
The SDK degrades gracefully but we should not set the error level to `ERROR` in this case, either we do `DEBUG` or not log at all if the list is empty.
Users might understand that there's something wrong but there's not.

**Comment by vaind** [comment]
> Users might understand that there's something wrong but there's not.

Exactly :)

**Comment by marandaneto** [comment]
@adinauer @romtsn maybe increase the priority of this issue? it's already the 4th time that we run into this issue.

**Comment by philipphofmann** [comment]
Moved this to "Needs Discussion" so we can discuss it in the next sync call.

**Comment by wbinarytree** [comment]
Do we have a "Discussion" yet? This is super annoying when use react-native-sentry on Android app.

**Comment by kahest** [comment]
moved back to Needs Discussion - this is relevant for downstream projects (hybrid SDKs), see e.g. deserialization errors in https://github.com/getsentry/sentry-capacitor/issues/450

**Comment by romtsn** [comment]
is this just about renaming it to `OrNull` and then letting the hybrid SDKs handle the null case on their side? @kahest If so, we could do it for v7 I guess

**Comment by markushi** [comment]
Sample applies for parsing dates.
