### ISSUE TITLE
Invalid reflection config referencing a legacy constructor

### ISSUE THREAD

**Issue by ia3andy** [getsentry/sentry-java#2155]
### Integration

sentry

### Java Version

11, 17

### Version

6+

### Steps to Reproduce

See https://github.com/quarkiverse/quarkus-logging-sentry/issues/62

### Expected Result

Should work in native

### Actual Result

Exception:
```
Error: Error parsing reflection configuration in jar:file:/project/lib/io.sentry.sentry-6.1.4.jar!/META-INF/native-image/io.sentry/sentry/reflect-config.json:
Method io.sentry.protocol.SdkVersion.<init>() not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationResources.
com.oracle.svm.core.util.UserError$UserException: Error parsing reflection configuration in jar:file:/project/lib/io.sentry.sentry-6.1.4.jar!/META-INF/native-image/io.sentry/sentry/reflect-config.json:
Method io.sentry.protocol.SdkVersion.<init>() not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
```

**Comment by philipphofmann** [comment]
@ia3andy, when exactly do you get the error? When you start the SDK?

**Comment by ia3andy** [comment]
@philipphofmann in Quarkus at build time. You should have a look at the issue:
https://github.com/quarkiverse/quarkus-logging-sentry/issues/62

**Comment by romtsn** [comment]
yeah the empty ctor doesn't exist anymore, the graalvm config should be updated I guess. Idk a thing about it, but is it auto-generated or manually? maybe we could add a task that generates it, similar to apiDump and apiCheck to prevent this in the future.
