### ISSUE TITLE
Unable to send custom tags with an issues

### ISSUE THREAD

**Issue by hari-ram-s** [getsentry/sentry-java#2159]
### Description

**Integration:** Sentry spring boot starter
**Sentry version:** 3.1.1

We are using Java and trying to send custom tags to Sentry exceptions. I referred to this [document](https://docs.sentry.io/platforms/java/enriching-events/tags) for sending custom tags. But, my exceptions (issues) in Sentry UI do not have the tag that I sent. Here is how my code looks.

```
Sentry.configureScope(scope -> {
     scope.setTag("error_code", "1001");
});
Sentry.captureException(e);
```

Then I tried to set the tag directly through the static method, which didn't work either.
```
Sentry.setTag("error_code", "1001");
Sentry.captureException(e);
```

In either case, I am able to see the exception (issue) in the UI. But the custom tag is not available under my issue/ event.

I expect to send different tags with different exceptions. Please do let me know if you need any other info. Thanks!

**Comment by hari-ram-s** [comment]
Hi @philipphofmann, I updated the version to 6.1.4 and tried again in my local. Still the same issue. Tried both the code snippets mentioned above.

**Comment by hari-ram-s** [comment]
Any update on this @philipphofmann? Are we sending tags the right way?

**Comment by hari-ram-s** [comment]
Enabled debugging and I guess I'm able to figure out what's going on. And FYI, I'm using spring boot's @ExceptionHandler to handle all the exceptions in one place.

Here is what happens in the background.

1. The moment I throw the exception, I get the below logs.
```
DEBUG: Capturing event: d9da27f7f734405eb787c08a0e6253a7
INFO: Session is null on scope.withSession
```
2. In my ExceptionHandler class, I am setting a custom tag and capturing the event (as described in the issue description). Now, I get the below logs.
```
DEBUG: Capturing event: cab24882662d43fbbfbc054314ea7265
DEBUG: Duplicate Exception detected. Event cab24882662d43fbbfbc054314ea7265 will be discarded.
DEBUG: Event was dropped by a processor: io.sentry.DuplicateEventDetectionEventProcessor
```
3. Finally when the thread execution is completed, I get an acknowledgement log.
```
DEBUG: Envelope sent successfully.
DEBUG: Envelope flushed
```


As we see, Sentry assumes that the thrown exception is an unhandled exception. But it is handled via Spring boot's @ExceptionHandler. How to stop Sentry from automatically tracking unhandled exceptions? There will never be unhandled exceptions in our application.

**Comment by maciejwalkowiak** [comment]
@hari-ram-s do you use `sentry-spring-boot-starter` dependency and `SentryAutoConfiguration` for Spring Boot? Do you use integration with any of the logging frameworks? Or you just rely on the `sentry` module and write all the integrations by yourself? Since this event is considered as duplicate:

```
DEBUG: Duplicate Exception detected. Event cab24882662d43fbbfbc054314ea7265 will be discarded.
```

it means that something else is already reporting this exception. 

It would be great if you could explain in more details your setup and ideally provide a minimum sample that reproduces this issue.

**Comment by hari-ram-s** [comment]
@maciejwalkowiak as mentioned, I am using sentry-spring-boot-starter. I think Sentry is falsly considering these exceptions as uncaught exceptions. I even tried disabling `enable-uncaught-exception-handler`. But that didn't help.

I have created a bare minumum setup that only has `sentry-spring-boot-starter` dependency. Here it is - https://github.com/hari-ram-s/demo-sentry

**Steps to reproduce:-**

1. Pull the repo and update dsn in application.yml. (Use some test project)
2. Run the spring boot application.
3. Hit `localhost:8080/demo`. In the logs, you can see `Duplicate Exception detected` from Sentry.

Controller class name: DemoController
Exception handler class name: ExceptionHandlers

As the captured exception in ExceptionHandlers.java is discarded, I do not get the error code in Sentry UI.
Feel free to update any dependencies/ versions in the sample. 

PS: I have already tried the latest Sentry SDK version.

**Comment by maciejwalkowiak** [comment]
@hari-ram-s thanks for a sample! Once I upgrade your sample to Sentry SDK 6.2.1, the behaviour is correct and the exception with a tag added in the advice is reported to Sentry. 

Look at the console output below:

```
DEBUG: Capturing event: a605f697385d4de887be4adb2ff4fd1b
INFO: Session is null on scope.withSession
DEBUG: Serializing object: {
	"timestamp": "2022-07-14T13:05:19.650Z",
	"exception": {
		"values": [
			{
				"type": "Exception",
				"value": "test",
				"module": "java.lang",
				"thread_id": 30,
				"stacktrace": {
					"frames": [ ... ]
				}
			}
		]
	},
	"transaction": "GET /demo",
	"fingerprint": [],
	"event_id": "a605f697385d4de887be4adb2ff4fd1b",
	"contexts": {
		"runtime": {
			"name": "BellSoft",
			"version": "17.0.3"
		}
	},
	"sdk": {
		"name": "sentry.java.spring-boot",
		"version": "6.2.1",
		"packages": [
			{
				"name": "maven:io.sentry:sentry",
				"version": "6.2.1"
			},
			{
				"name": "maven:io.sentry:sentry-spring-boot-starter",
				"version": "6.2.1"
			}
		]
	},
	"request": {
		"url": "http://localhost:8080/demo",
		"method": "GET",
		"headers": {
			"host": "localhost:8080",
			"connection": "keep-alive",
			"accept-encoding": "gzip, deflate",
			"accept": "*/*",
			"user-agent": "HTTPie/3.2.1"
		}
	},
	"tags": {
		"error.code": "1001"
	},
	"environment": "test",
	"platform": "java",
	"user": {},
	"server_name": "maciejs-mbp-2",
	"breadcrumbs": [
		{
			"timestamp": "2022-07-14T13:05:17.818Z",
			"type": "http",
			"data": {
				"method": "GET",
				"url": "/demo"
			},
			"category": "http"
		}
	]
}
DEBUG: Envelope sent successfully.
DEBUG: Envelope flushed
```

Could you please try again with the latest SDK? Maybe there is something else missing in the sample?

To consider as an alternative to capturing errors manually is configuring an error processor that modifies the event based on the type of exception. For example:

```java
@Bean 
EventProcessor eventProcessor() {
    return new EventProcessor() {
        @Override public SentryEvent process(SentryEvent event, Hint hint) {
            if (event.getThrowable() instanceof BusinessException e) {
                String name = e.getBusinessProcessCode().name();
                event.setTag("business-process-tag", name);
            }
            return event;
        }
    };
}
```

**Comment by hari-ram-s** [comment]
Hey @maciejwalkowiak, thanks for the effort. I’m able to get the desired result now with version 6.2.1. 

Just a quick question regarding the version update. We have a lot of teams and projects in our org using Sentry. Will I run into any issues if the Sentry SDK version between those projects doesn’t match?

**Comment by maciejwalkowiak** [comment]
As long as they are not on the same classpath - no. Each separate application can use different SDK version and there won't be any issue. But of course we would recommend staying more or less up to date :)
