### ISSUE TITLE
Report app start more granularly

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2177]
### Description

The app start actually consists of multiple steps (e.g. process creation, bindApplication, etc.), so we could potentially create spans for each of this steps to give more insights for the users on where exactly can they optimize (e.g. system things like process creation cannot be optimized).

Prior art https://github.com/square/papa/blob/db3128e211a3cd916083d87d1d7eeac8cf8b8a56/papa/src/main/java/papa/internal/Perfs.kt

**Comment by philipphofmann** [comment]
On Cocoa, we already do that. Maybe worth having a look before starting to implement this https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/#app-start-instrumentation.

**Comment by adinauer** [comment]
Need to cache what happens before the SDK is initialized and later create spans with that information.

**Comment by markushi** [comment]
Consider adapting the app-start time here as well.
