### ISSUE TITLE
Why sentry reports ANR as level: error

### ISSUE THREAD

**Issue by nienienienie** [getsentry/sentry-java#2182]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.2.1

### Proguard

Enabled

### Version

5.0.2

### Steps to Reproduce

1. get ANR on Android

### Expected Result

ANR is more like fatal level to me, not error level.

Maybe it should be possible to have 3rd level:
- error
- anr
- fatal

### Actual Result

sentry shows
```
ApplicationNotResponding

Application Not Responding for at least 5000 ms.
```
with level: error

**Comment by philipphofmann** [comment]
We mark errors as fatal if your app can't recover and crashes. When an ANR occurs, your app doesn't necessarily crash and can recover from that.
