### ISSUE TITLE
Optional SentryTimberIntegration

### ISSUE THREAD

**Issue by tonyshkurenko** [getsentry/sentry-java#2189]
### Problem Statement

We have Timber on a classpath, but it doesn't mean, that we want to add SentryTimberIntegration (we have our own doing similar things)

### Solution Brainstorm

Please, add some param to the plugin, to remove the integration, right now we're doing this in init block:
```
options.integrations.removeIf { it is SentryTimberIntegration }
```

**Comment by adinauer** [comment]
Hello @tonyshkurenko - just to confirm - are you using https://github.com/getsentry/sentry-android-gradle-plugin ?

If so you could turn off auto installation:

```
sentry {
    ...

    autoInstallation {
        enabled = false
    }
}
```

and then install only the modules you want explicitly.

**Comment by tonyshkurenko** [comment]
Thanks, I haven't seen that
