### ISSUE TITLE
ANR which version of sentry supports ANR

### ISSUE THREAD

**Issue by nienienienie** [getsentry/sentry-java#2193]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.2

### Proguard

Enabled

### Version

5.7.4

### Steps to Reproduce

Which version of sentry has ANR support?

Here https://docs.sentry.io/platforms/android/configuration/app-not-respond/ I see that 6.3.0, but https://github.com/getsentry/sentry-java/blame/main/sentry-android-core/src/main/java/io/sentry/android/core/ANRWatchDog.java was added like 3 yrs ago by https://github.com/getsentry/sentry-android/pull/104, so what's going on there?

### Expected Result

Easy to understand ANR docs.

### Actual Result

I don't understand what sentry android brings to ANR discovery on prod.

**Comment by adinauer** [comment]
Hello @nienienienie, we added ANR support in a late `1.7.x` version around September 2019.

The `6.3.0` you can see in the side bar displays the current version of the SDK that's available.
Does this information help you?

**Comment by nienienienie** [comment]
Yes, it helps me.

But that page of docs https://docs.sentry.io/platforms/android/configuration/app-not-respond/ should be updated, because it's very misleading about "which version of sentry has ANR handling".

**Comment by adinauer** [comment]
We're currently not planning to add a minimum required version to all the docs pages.
