### ISSUE TITLE
ActivityLifecycleIntegration.class would cast mem leak

### ISSUE THREAD

**Issue by vvgool** [getsentry/sentry-java#2201]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

5.4.1

### Proguard

Disabled

### Version

6.2.1

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/10974305/182543477-65c90aad-6b7b-44a9-87b9-bf1a379de11b.png)

┬───
│ GC Root: Global variable in native code
│
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (StatServiceImpl↓ is not leaking and A ClassLoader is never leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (StatServiceImpl↓ is not leaking)
│    ↓ Object[9097]
├─ com.tencent.stat.StatServiceImpl class
│    Leaking: NO (a class is never leaking)
│    ↓ static StatServiceImpl.r
│                             ~
├─ io.sentry.UncaughtExceptionHandlerIntegration instance
│    Leaking: UNKNOWN
│    Retaining 13.2 MB in 11488 objects
│    ↓ UncaughtExceptionHandlerIntegration.options
│                                          ~~~~~~~
├─ io.sentry.android.core.SentryAndroidOptions instance
│    Leaking: UNKNOWN
│    Retaining 13.2 MB in 11360 objects
│    ↓ SentryOptions.integrations
│                    ~~~~~~~~~~~~
├─ java.util.concurrent.CopyOnWriteArrayList instance
│    Leaking: UNKNOWN
│    Retaining 13.2 MB in 10900 objects
│    ↓ CopyOnWriteArrayList[8]
│                          ~~~
├─ io.sentry.android.core.ActivityLifecycleIntegration instance
│    Leaking: UNKNOWN
│    Retaining 13.2 MB in 10864 objects
│    application instance of com.app.SkApplication
│    ↓ ActivityLifecycleIntegration.appStartSpan
│                                   ~~~~~~~~~~~~
├─ io.sentry.Span instance
│    Leaking: UNKNOWN
│    Retaining 284 B in 8 objects
│    ↓ Span.transaction
│           ~~~~~~~~~~~
├─ io.sentry.SentryTracer instance
│    Leaking: UNKNOWN
│    Retaining 13.2 MB in 10747 objects
│    ↓ SentryTracer.transactionFinishedCallback
│                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
├─ io.sentry.android.core.-$$Lambda$ActivityLifecycleIntegration$1Xa20D8rbI_RfOTCST8-8mCjmDU instance
│    Leaking: UNKNOWN
│    Retaining 13.2 MB in 10732 objects
│    f$1 instance of com.app.activity.StartActivity with mDestroyed = true
│    ↓ -$$Lambda$ActivityLifecycleIntegration$1Xa20D8rbI_RfOTCST8-8mCjmDU.f$1

when i started main activity from launch activity,the launch activity would be leak.

the activityLifecycleIntegration is single.

### Expected Result

launch actvity no leak

### Actual Result

launch actvity leaked

**Comment by adinauer** [comment]
@vvgool thank you for raising this. Looks like the callback waiting for the transaction to finish is holding a strong ref to `Activity`. I'm working on a fix.
