### ISSUE TITLE
Adding an Enum in Breadcrumb setData causes a weird behaviour in serialization leading to a huge heap space allocation

### ISSUE THREAD

**Issue by rsolci** [getsentry/sentry-java#2219]
### Integration

sentry

### Java Version

11

### Version

6.3.1

### Steps to Reproduce

- Create an enum with a few entries (local environment took 8 entries to cause a JVM crash)
- Add a breadcrumb (any level, any message) with said enum in the value of `setData`
- Send any event to sentry (making it serialize all the breadcrumbs)

From my tests is seems the problem happens in `JsonReflectionObjectSerializer` class at line 77: `Field[] fields = object.getClass().getDeclaredFields()`
Calling this on a enum returns all other enums making the serialization size and time increase exponentially.

Code example:
```kotlin
enum class DummyEnum {
        E1, E2
    }

@Test
    fun sentrySerializerTest() {
        val sw = StringWriter()

        val jsonWriter = JsonObjectWriter(sw, 100)

        val dummyLogger = object: ILogger {
            override fun log(level: SentryLevel, message: String, vararg args: Any?) { }
            override fun log(level: SentryLevel, message: String, throwable: Throwable?) { }
            override fun log(level: SentryLevel, throwable: Throwable?, message: String, vararg args: Any?) { }
            override fun isEnabled(level: SentryLevel?): Boolean { return false }
        }

        val duration = measureTime {
            jsonWriter.value(dummyLogger, DummyEnum.E1)
            println(sw.toString())
        }

        println(duration.inWholeMilliseconds)
    }
```

Running this piece of code prints out:

```
{"E1":"E1","E2":{"E1":"E1","E2":"E2","$VALUES":["E1","E2"]},"$VALUES":["E1",{"E1":"E1","E2":"E2","$VALUES":"[Lcom.mypackage.MyTestClass$DummyEnum;@4647881c"}]}
```

Adding more entries to DummyEnum increases the string size, time to process and memory exponentially

### Expected Result

Serializing an enum should be just the enum name.

### Actual Result

A lot of investigation is in the Steps to reproduce, but the actual result of the enum serialization in the breadcrumb is a multiplication of all enum entries:

```
{"E1":"E1","E2":{"E1":"E1","E2":"E2","$VALUES":["E1","E2"]},"$VALUES":["E1",{"E1":"E1","E2":"E2","$VALUES":"[Lcom.mypackage.MyTestClass$DummyEnum;@4647881c"}]}
```

**Comment by adinauer** [comment]
@rsolci thank you for raising this! I'm looking into a fix.
