### ISSUE TITLE
Failed to connect to <base domain> is not merged into single issue 

### ISSUE THREAD

**Issue by yangcheng** [getsentry/sentry-java#2236]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.2.2

### Proguard

Enabled

### Version

6.3.0

### Steps to Reproduce

1. code have different path call retrofit 
2. disable wifi on device
3. fire different network calls

### Expected Result

all  " failed to connect to example.com(1.1.1.1) " errors from different path should merge into one error

### Actual Result

I got tens of different issues on sentry.
![sentry_connection](https://user-images.githubusercontent.com/132834/189028460-c6ad2d52-16fb-4422-b264-4e6c449b679c.jpg)

**Comment by adinauer** [comment]
Hello @yangcheng grouping is done via stack traces. If they differ, the issues won't be grouped. You could set a `fingerprint` or group them via the Dashboard. Here's some docs on the subject: https://docs.sentry.io/product/data-management-settings/event-grouping/

Hope this helps.

**Comment by yangcheng** [comment]
if I manually group them in dashboard, does the system learn about the pattern?
