### ISSUE TITLE
User segment should be a top level property on the user

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2240]
### Problem Statement

Currently the `user_segment` is being read from `other['segment']`.

### Solution Brainstorm

A top level property called `segment` on the user should be used as is done in the JS SDK: 

https://github.com/getsentry/sentry-javascript/blob/beb3c973c0f10c538c8369983fc08c5bd031bfde/packages/types/src/user.ts#L8

**Comment by AbhiPrasad** [comment]
Develop docs amended here: https://github.com/getsentry/develop/pull/685
