### ISSUE TITLE
Document how to continue a trace including `baggage`

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2265]
### Description

https://docs.sentry.io/platforms/android/performance/instrumentation/custom-instrumentation/#distributed-tracing still describes how to continue a trace but doesn't include `baggage`. We should update the docs to include `baggage`.

**Comment by philipphofmann** [comment]
Shouldn't we move this to the docs repo then, @adinauer?

**Comment by adinauer** [comment]
@philipphofmann Not sure, it's a Java only API

**Comment by philipphofmann** [comment]
But https://docs.sentry.io/platforms/android/performance/instrumentation/custom-instrumentation/#distributed-tracing is already the docs. Why not add it there?

**Comment by adinauer** [comment]
That's the idea to add it to that page. I don't mind if we move this issue there.

Question is: Do we duplicate the existing docs and add some that use `baggage` or do we simply extend the existing code and only show how to use both `sentry-trace` and `baggage` at the same time?

**Comment by philipphofmann** [comment]
> Question is: Do we duplicate the existing docs and add some that use baggage or do we simply extend the existing code and only show how to use both sentry-trace and baggage at the same time?

What do you think makes the most sense?

**Comment by adinauer** [comment]
I guess it's easier if there's only one example and it's coded in a way that works for both headers even if they're not present. Then people will probably find it easy to just remove the `baggage` related code if they want to ignore it.

**Comment by adinauer** [comment]
Already documented [here](https://docs.sentry.io/platforms/java/performance/instrumentation/custom-instrumentation/#distributed-tracing) via https://github.com/getsentry/sentry-docs/pull/5617 .
