### ISSUE TITLE
Make enums ser/deser forward-compatible

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2268]
### Description

Some enums like https://github.com/getsentry/sentry-java/blob/730095684bb732a0a7d0cc88d3c3b913a08d7cfe/sentry/src/main/java/io/sentry/SpanStatus.java#L119 ser/deser are not forward compatible, meaning if, for example, RN adds a new span status, the deserialization will fail during serialization roundtrip.

We should fallback to UNKNOWN statuses/enums in case the value is not part of the enum set.

**Comment by marandaneto** [comment]
I'd not say that we should always fallback to `UNKNOWN` statues/enums, that's fine if this value is only used at runtime for `ifs`, `switches`, etc, but if the value is forwarded to Sentry, its value should be kept.
Eg. If RN or Flutter captures a transaction with a status that is not defined in the `SpanStatus` enum, this value should not be lost during roundtrip serialization.

**Comment by kahest** [comment]
closing as outdated - if it's still relevant it will come up again
