### ISSUE TITLE
"java.util.logging.LogManager is a restricted class" on AppEngine

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#228]
I'm not sure how Sentry could be working on AppEngine for anyone given a glance at the code.

Details here: https://github.com/getsentry/raven-java/issues/122#issuecomment-232838067

**Comment by wholegroup** [comment]
@bretthoerner 

1) You should load properties direct from file (see sources of https://java.net/projects/javamail/sources/mercurial/content/mail/src/main/java/com/sun/mail/util/logging/LogManagerProperties.java loadLogManager/readConfiguration)

2) Also you can't call methods of parent Handler class if they call checkPermission() (for example this.setFilter(new SentryHandler.DropRavenFilter());). You should use this filter in isLoggable method. 

3) on GAE you can't set custom handlers in logging.properties file. To enable a custom log handler I do: Logger.getLogger("").addHandler(new SentryHandler());

Probably it's better to create new handler like AppengineSentryHandler

p.s. Pls have a look at http://pastebin.com/Cy3AC8Wn (this handler works well on GAE now)

**Comment by bretthoerner** [comment]
@wholegroup Thanks so much, that was very helpful. Do you mind taking a glance at https://github.com/getsentry/raven-java/pull/282 ? I'd live your opinion.

**Comment by bruno-garcia** [comment]
#282 wasn't merged. Reopening.

**Comment by marandaneto** [comment]
Sentry-Java SDK v3 deprecated AppEngine
