### ISSUE TITLE
Add the name of the exception to the `beforeSend` callback failed breadcrumb.

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2280]
### Problem Statement

A failed `beforeSend` callback adds a breadcrumb that only contains the message of the exception.

https://github.com/getsentry/sentry-java/blob/d4087eef639433c3991a478fa6500033a3dbebf0/sentry/src/main/java/io/sentry/SentryClient.java#L664-L681

### Solution Brainstorm

It would also be helpful if the type of the exception was visible on the Sentry UI as sometimes only the combination of the two tells you the full story.

**Comment by romtsn** [comment]
The type of the exception only makes sense if the app is not obfuscated (because we do not de-obfuscate breadcrumbs at the moment), or if it's the exception from JDK.

Let's put this item on the TSC and also check what other SDKs are doing in this case. @adinauer will take care of it.

**Comment by adinauer** [comment]
We decided not to add more details to the breadcrumb but instead no longer send event / transaction in case `beforeSend` / `beforeSendTransaction` throws. More details can be found in https://github.com/getsentry/sentry-java/pull/2591
