### ISSUE TITLE
Use dependabot to upgrade gh-actions versions

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2296]
### Description

We should use dependabot to track gh-actions version changes and update them automatically. Prior art: https://github.com/getsentry/sentry-react-native/blob/main/.github/dependabot.yml

**Comment by philipphofmann** [comment]
Are you referring to warnings similar to 
<img width="970" alt="Screen Shot 2022-10-17 at 16 33 09" src="https://user-images.githubusercontent.com/2443292/196204988-747564e2-d016-4a1f-8084-78be9c0eee1e.png">

We also have them on Cocoa, see https://github.com/getsentry/sentry-cocoa/actions/runs/3248326856 or https://github.com/getsentry/sentry-cocoa/actions/runs/3262681695.

**Comment by markushi** [comment]
@philipphofmann yes, those are the ones we see for Java too.

**Comment by markushi** [comment]
Revisit this once the github-action has been updated.

**Comment by romtsn** [comment]
We should use dependabot so it automatically updates the gh-actions whenever there are new releases.

**Comment by philipphofmann** [comment]
I think you only need to add
```yml
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: weekly
```

to the dependabot.yml.

We already have this for [Cocoa](https://github.com/getsentry/sentry-cocoa/blob/14b681e2205ecb5ec3f510323ac5f435e13ff9c7/.github/dependabot.yml#L13-L16).
