### ISSUE TITLE
error sending events `io.sentry.hints.SessionStartHint is not io.sentry.hints.Retryable`

### ISSUE THREAD

**Issue by farfromrefug** [getsentry/sentry-java#2297]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.3.0

### Proguard

Disabled

### Version

6.5.0

### Steps to Reproduce

For the context it is within `Nativescript` which is a cross platform network like RN. I am upgrading my plugin https://github.com/farfromrefug/nativescript-akylas-sentry to latest JS / Native SDKs.
The code structure is almost exactly the same as RN plugin. 
The iOS works perfectly so the "common" code is working. 
My issue is that on Android events are not received. It started to fail when i switched to "envelope" sending.

I can reproduce it by simply capturing any event/error/message

### Expected Result

event sent to server

### Actual Result

in my logs i get this:
```
bytesPayload {"message":{"message":"Hello Sentry!"},"level":"info","event_id":"30656e6dfc474685a6621360d7b8ee5b","timestamp":"1970-01-20T06:42:15.117Z","environment":"production","sdk":{"integrations":["NativescriptErrorHandlers","Release","Inboun
     dFilters","FunctionToString","Breadcrumbs","LinkedErrors","Dedupe","HttpContext","RewriteFrames","EventOrigin","SdkInfo","DeviceContext"],"name":"sentry.nativescript","packages":[{"name":"npm:@nativescript-community/sentry","version":"4.6.1"},{"na
     me":"npm:@nativescript-community/sentry","version":"4.6.1"}],"version":"4.6.1"},"extra":{"myExtra":"extra-value"},"tags":{"myTag":"tag-value","event.origin":"javascript","event.environment":"javascript"},"release":"org.nativescript.demovuesentry@2
     .0+104","dist":"104.android","platform":"javascript","contexts":{},"user":{}}
/data/user/0/org.nativescript.demovuesentry/cache/sentry/3ad19661dce9734c1f8fde7b39546b0b1c33ecd3/outbox
flush 0
io.sentry.hints.SessionStartHint is not io.sentry.hints.Retryable
Envelope submission failed
```
The bytepayload is to show what s being sent.
The error clearing happens while deserializing the envelope byte array.
The true error seems to be `io.sentry.hints.SessionStartHint is not io.sentry.hints.Retryable` but i dont know what it means or where it is actually triggered.
Can anyone help me?

**Comment by romtsn** [comment]
Hey, I believe we need a bit more details (a reproducible example if possible). How do you send the envelope? Are there any other logs prior/past this point? I belive we rethrow the exception in case the envelop submission fails, so there should be somewhere the underlying exception in the logs

**Comment by farfromrefug** [comment]
@romtsn You can run the demo-vue from the repo i linked but i now it is not that easy to setup as it is in a new framework.
Now for the how we create the envelope it is here  https://github.com/nativescript-community/sentry/blob/master/src/wrapper.android.ts#L253. It is the exact same code as the RN plugin.
The only difference is that i change the `timestamp` format in event and breadcumbs because the `sentry-java` deserializer does not support `timestamp` as number (you have an issue opened about this).

About the exception thrown yes i saw your code about it. But i dont see it in logcat. Actually seeing the lines of the logcat  i think the throwable printed is `io.sentry.hints.SessionStartHint is not io.sentry.hints.Retryable`. This is where i am at a loss because there is stacktrace of the java error.

If you want to run the demo-vue to test it:
* `npm i -g nativescript`
* `git clone git@github.com:nativescript-community/sentry.git`
* `cd sentry`
* `pnpm i` ( i use pnpm but you should be able to use yarn, you cant use npm though as i use `link:` in deps)
* `pnpm run build`
* `cd demo-vue`
* `pnpm i`
* `ns run android --no-hmr`

A sentry message is sent right away on app start.

**Comment by farfromrefug** [comment]
@romtsn you were 100% right! Not sure why my emulator was not managing to communicate with the sentry instance while it can go on the web.
Thanks a lot for your help and sorry for the trouble!
