### ISSUE TITLE
Sentry fails to serialize Locale

### ISSUE THREAD

**Issue by marek-klima** [getsentry/sentry-java#2301]
### Integration

sentry

### Java Version

17

### Version

6.4.3

### Steps to Reproduce

Running a code that tries to encode object of type `Locale` never ends. It probably stays inside `JsonReflectionObjectSerializer` ([here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/JsonReflectionObjectSerializer.java#L79)) because `object.getClass().getDeclaredFields()` returns long list. 

There were recent fixes for enums (https://github.com/getsentry/sentry-java/pull/2220).

```
import io.sentry.JsonObjectWriter;
import io.sentry.NoOpLogger;
import java.io.IOException;
import java.io.StringWriter;
import java.util.HashMap;
import java.util.Locale;

public class StartSentry {
    public static void main(String[] args) {
        JsonObjectWriter writer = new JsonObjectWriter(new StringWriter(), 10);
        HashMap<String, Locale> map = new HashMap<>();
        map.put("one", Locale.GERMAN);
        try {
            writer.value(
                    NoOpLogger.getInstance(),
                    map
            );
        } catch (IOException e) {
            System.out.println("IO exception " + e);
        }
    }
}
```

The same happens on newest version `6.5.0`.

### Expected Result

Locale is correctly serialized

### Actual Result

Potential Out of Memory exception

**Comment by philipphofmann** [comment]
@marek-klima, did this work on any of the previous versions?

**Comment by marek-klima** [comment]
> @marek-klima, did this work on any of the previous versions?

Unfortunately I'm now aware of any older version where this would work correctly.

**Comment by romtsn** [comment]
Hmm, do you really want to serialize the entire `Locale` object? I guess our serializer is not designed to serialize large deeply-nested object hierarchies.. On the other hand it should in theory function the same way Gson reflection serializer works.

**Comment by romtsn** [comment]
Yeah we definitely need to investigate it, that's for sure

**Comment by adinauer** [comment]
I'll take a look

**Comment by adinauer** [comment]
We could skip `static` fields when going through the fields but in this case it would lead to an empty object being serialized for Locale. We could fall back to `toString()` in that case as a generic solution. WDYT?
