### ISSUE TITLE
Finish and capture transaction/span bound to the Scope in case of a fatal crash

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2316]
### Problem Statement

See https://github.com/getsentry/team-mobile/issues/62 for more details.

### Solution Brainstorm

Finish transaction/span in `UncaughtExceptionHandlerIntegration`

**Comment by markushi** [comment]
Similar to ANRs we could trigger a force-finish inside the `SentryClient`, see https://github.com/getsentry/sentry-java/blob/3b5c802fcede7e85ebe520c718ad9a266d9bbe05/sentry/src/main/java/io/sentry/SentryClient.java#L193-L203
