### ISSUE TITLE
Hub.withScope - cloning the scope fails

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-java#2323]
### Integration

sentry

### Java Version

8

### Version

unknown

### Steps to Reproduce

We see two relatively large amount of SDK crashes (exported from Google Play SDK Console), both of them seem to happen when a `Scope` is cloned using the copy constructor.

````
java.lang.NullPointerException: 
  at io.sentry.Breadcrumb.<init>
  at io.sentry.Scope.<init>
  at io.sentry.Hub.pushScope
  at io.sentry.Hub.withScope
  at io.sentry.Sentry.withScope
````

````
java.util.NoSuchElementException: 
  at io.sentry.CircularFifoQueue$1.next
  at io.sentry.Scope.<init>
  at io.sentry.Hub.pushScope
  at io.sentry.Hub.withScope
  at io.sentry.Sentry.withScope
````

### Expected Result

No crashes

### Actual Result

Crashes

**Comment by romtsn** [comment]
Relates to #2183

**Comment by romtsn** [comment]
Since it's affecting ~14k users, we decided that it's a p0
