### ISSUE TITLE
Sentry Extra data being shared between requests

### ISSUE THREAD

**Issue by FireMasterK** [getsentry/sentry-java#2337]
### Integration

sentry

### Java Version

17

### Version

6.7.0

### Steps to Reproduce

1. I have an [ActiveJ](https://activej.io/) application, that uses a common Thread Pool to handle requests.
2. I set extra data using `Sentry.setExtra(key, value);`
3. I have multiple routes that set data of different keys.
4. When an exception or event is caught, sentry sends data of keys that were not involved in the request.

### Expected Result

Sentry sends only the information from that particular request.

Maybe there could be a way to clear extra data?

### Actual Result

Just seeing multiple unrelated extra data in the caught exception.

**Comment by adinauer** [comment]
Hello @FireMasterK, can you try using `Sentry.withScope` to set your extras and then have them auto cleared?

Like this:
```
Sentry.withScope(scope -> {
    scope.setExtra("key", "value");
    // ... your code handling the request goes here
});
```

Alternatively there's also a `Sentry.removeExtra` method in case you know which key(s) to remove.

**Comment by adinauer** [comment]
Closing this now. If you need any more help, feel free to reopen.
