### ISSUE TITLE
ANR before crash when `SentryOptions.BeforeSendCallback` returns null

### ISSUE THREAD

**Issue by michal-chojnacki** [getsentry/sentry-java#2346]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4

### Proguard

Disabled

### Version

5.7.4

### Steps to Reproduce

1. Create new blank project.
2. Add sentry library
3. Add AndroidManifest integration code
4. Add config to `build.gradle` file:
```
sentry {
    tracingInstrumentation {
        enabled.set(false)
    }
    autoInstallation {
        enabled.set(false)
    }
}
```
5. Run Sentry config in `Application` file:
```
    override fun onCreate() {
        super.onCreate()
        SentryAndroid.init(this, loggingOptions())
    }

    private fun loggingOptions() =
        Sentry.OptionsConfiguration<SentryAndroidOptions> { options ->
            options.beforeSend = SentryOptions.BeforeSendCallback { event, _ ->
                null
            }
        }
```
6. Build project
7. Run something which will throw unhandled exception

### Expected Result

App should crash immediately

### Actual Result

When unhandled exception happens UI freezes for few secs, ANR is shown and crash happens after some time.

Everything works correctly until v5.7.3. After bumping when `SentryOptions.BeforeSendCallback ` returns `null` then we have ANR for few seconds before crash. When `SentryOptions.BeforeSendCallback` is returning some event then it also works correctly (crashing immediately).

**Comment by romtsn** [comment]
hey, sorry for the troubles and thanks for the detailed report, we'll take a look at it soon and try to reproduce.

**Comment by romtsn** [comment]
found the cause - the fix is on its way and we'll try to ship it this or next week. Thanks for nailing down the version where it's started to pop up 👍
