### ISSUE TITLE
Use Class#getCanonicalName to log Fragment name in breadcrumbs

### ISSUE THREAD

**Issue by ninniuz** [getsentry/sentry-java#2362]
### Problem Statement

Currently, in case of an obfuscated Android app, it is impossible to determine to which `Fragment` ui breadcrumbs from `SentryFragmentLifecycleCallbacks` refer to.

This is because `SentryFragmentLifecycleCallbacks` retrieves the fragment name using the following function

```
private fun getFragmentName(fragment: Fragment): String {
  return fragment.javaClass.simpleName
}
```

`Class#getSimpleName` does not allow us manually deobfuscate `Fragment` names thus making those breadcrumbs basically useless.

### Solution Brainstorm

Replace `Class#getSimpleName` with `Class#getCanonicalName`

```
private fun getFragmentName(fragment: Fragment): String {
  return fragment.javaClass.canonicalName
}
```

**Comment by romtsn** [comment]
hey @ninniuz we'll take a look and discuss whether we want this or just gonna do this on the backend soon, so we don't need these workarounds on the SDK. Thanks for reporting 👍

**Comment by ninniuz** [comment]
@romtsn that sounds great! Please also consider us poor devs who are on self-hosted instances and cannot always update straight away 😄
