### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2396]
### Description

Just had to rerun integration tests twice on the same PR.

Runs:
- https://github.com/getsentry/sentry-java/actions/runs/3563966107/attempts/1
- https://github.com/getsentry/sentry-java/actions/runs/3563966120/attempts/1

**Comment by adinauer** [comment]
One more: https://github.com/getsentry/sentry-java/actions/runs/3564943734/jobs/5989507699

**Comment by adinauer** [comment]
Another one:
- https://github.com/getsentry/sentry-java/actions/runs/3600896332/jobs/6066070583

**Comment by stefanosiano** [comment]
a [fix](https://github.com/getsentry/sentry-java/pull/2422) was merged into master, so the situation should be better now
