### ISSUE TITLE
Investigate Spring Observability

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2404]
### Description

Spring Observability / Micrometer Tracing / Spring Cloud Sleuth might be something we could use for APM. Need to investigate whether it makes sense or if using via OpenTelemetry is better.

https://spring.io/blog/2022/10/12/observability-with-spring-boot-3

**Comment by smeubank** [comment]
Since v8 will now include OTel support https://github.com/getsentry/sentry-java/issues/3752, I will close this issue. If we want to reopen, I would suggest we move it to a discussion.
