### ISSUE TITLE
Streamline process to get Proguard mapping file for a developer role

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry-java#2406]
### Problem Statement

In Android sometimes there are exceptions with obfuscated class names in exception messages (e.g. something like Attempt to invoke virtual method 'java.lang.String x3g.a()' on a null object reference), and that’s completely fine that they are not deobfuscated automatically, because it’s not the stacktrace. 

But it’s still possible to deobfuscate it manually, but in order to do that it is needed to have access to the Proguard mapping file. 
In order to get the mapping file we need to do:

- go to the raw JSON payload of the issue
- find the debug_meta key (something like "debug_meta":{"images":[{"uuid":"<UUID>","type":"proguard"}]})
- get the UUID from this value
- go to the Settings -> Projects -> pd-android-main -> ProGuard Mappings
- get this specific mapping for the UUID

**Comment by edwardgou-sentry** [comment]
Hey @Angelodaniel , just to confirm, are you referring to this particular attribute for issues?
<img width="732" alt="image" src="https://user-images.githubusercontent.com/83961295/206753990-ce36075f-f221-491b-9d17-25924a0bdf76.png">

If so, if we could deobfuscate this attribute (when mapping is available) would that resolve this problem for you? I'm still looking into the specifics on how we may do this, but I think this might be a simpler solution than exposing easier access to the proguard files.

**Comment by viakunin** [comment]
Hi @edwardgou-sentry , yes, that's correct, e.g.
<img width="824" alt="Screenshot 2022-12-12 at 15 56 12" src="https://user-images.githubusercontent.com/85172479/207078443-710d4681-0d05-4a20-a07c-1bb0f4e839fb.png">
or
<img width="796" alt="Screenshot 2022-12-12 at 15 56 27" src="https://user-images.githubusercontent.com/85172479/207078485-e26d710c-ba21-4017-9228-201ddf150f88.png">
I'm not so sure this is a simpler solution, but yes, automatic deobfuscation of those messages will solve the issue for us.

**Comment by edwardgou-sentry** [comment]
Thanks @viakunin ! I will try to explore how viable it is to automatically deobfuscate those messages. We can fall back to exposing the proguard file if the former is not feasible. Will let you know if we have updates!

**Comment by romtsn** [comment]
@edwardgou-sentry I have explored this a bit in the past, and we might want to hook into event processing through [event_enhancers](https://github.com/getsentry/sentry/blob/c4c1a94a38b6add6ead5d164a5b7fa223259fcc3/src/sentry/plugins/base/v2.py#L398-L416). Ideally we'd want to have it centralized, because we also want to deobfuscate breadcrumbs, span descriptions, transaction names, etc. in the future

**Comment by edwardgou-sentry** [comment]
Hey @viakunin , just wanted to give you a heads up that we've made some improvements to this. If you have new issues being created, you should start seeing some of them being deobfuscated now. This only really applies to new issues for now, so If you have an existing issue, it may not be deobfuscated yet. We're still looking at ways to better this so we'll keep you updated if we have any further improvements!

**Comment by viakunin** [comment]
Thank you, @edwardgou-sentry!

**Comment by edwardgou-sentry** [comment]
Hey @viakunin , sorry for the late reply! You can try to verify this by searching some of your issues that might have previously contained obfuscated messages in the issues page. 

For example from your screenshot above, try searching `Parameter specified as non-null is null` in the issue search bar. Select one of the issues from the results and view the `All Events` tab. In the `All Events` tab, you can sort the table by `timestamp` ascending and descending and look at the `title` column to see if newer events are being deobfuscated compared to older events. You should be able to see a difference here.

The deobfuscation happens on event processing so the JSON response will contain the deobfuscated message. We don't have any flags in the ui at this moment to indicate if the message was deobfuscated at this moment (good feedback though, we can take this into consideration). 

Let me know if you have any other questions, thanks!

**Comment by viakunin** [comment]
@edwardgou-sentry thanks for the clarification! yes, it looks like it works, all recents events in those issues have deobfuscated messages, and also event messages were updated as well. 
great job, thank you!

**Comment by markushi** [comment]
Closing as a dup of https://github.com/getsentry/sentry-java/issues/942
