### ISSUE TITLE
java.lang.ClassNotFoundException: io.sentry.spring.SentrySpringServletContainerInitializer

### ISSUE THREAD

**Issue by js361014** [getsentry/sentry-java#2411]
### Integration

sentry-spring-jakarta

### Java Version

17

### Version

6.9.1

### Steps to Reproduce

1.Put in `pom.xml`
```
<dependency>
	<groupId>io.sentry</groupId>
	<artifactId>sentry-spring-jakarta</artifactId>
	<version>6.9.1</version>
</dependency>
```
2.Create `SentryConfiguration` class
```
import io.sentry.spring.jakarta.EnableSentry;
import org.springframework.context.annotation.Configuration;

@EnableSentry(dsn = "DSN_URL")
@Configuration
public class SentryConfiguration {
}
```
3.Add `SentryConfiguration` to `applicationContext.xml`
```
<bean class="SentryConfiguration"/>
```

### Expected Result

Everything works.

### Actual Result

Error: `Caused by: java.lang.ClassNotFoundException: io.sentry.spring.SentrySpringServletContainerInitializer`

**Comment by js361014** [comment]
Possibly in https://github.com/getsentry/sentry-java/blob/2285d6f7c0f240594d2771287868af8a94df6dc4/sentry-spring-jakarta/src/main/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer
`io.sentry.spring.SentrySpringServletContainerInitializer` should be replaced with `io.sentry.spring.jakarta.SentrySpringServletContainerInitializer`

**Comment by adinauer** [comment]
Thanks @js361014 for the analysis and fix. Just waiting for CI to finish, then I'll merge #2413
