### ISSUE TITLE
OpenTelemetry Support Follow-Ups after Basic Support

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2419]
### Description

Basic support for OpenTelemetry has been added in https://github.com/getsentry/sentry-java/issues/2327

Here are some more TODOs:

- [ ] Set instrumenter (e.g. using  an Aspect) to `OTEL` from the Java Agent so users don't have to manually do it
- [ ] Detect `sentry-opentelemetry-agent` and set instrumenter automatically even when not using auto config (very similar to above)
- [ ] End to end tests for OTEL on a running application
- [x] [Increase timestamp precision for start/end of spans from `ms` to ~~`ns`~~ `10μs` (which will probably be changed to `μs` by relay)] (https://github.com/getsentry/sentry-java/issues/2394)
- [ ] Add a more complex service using Spring Boot to https://github.com/getsentry/opentelemetry-demo and showcase errors and other features Sentry has to offer
- [ ] Once the more complex demo has been merged, revert the adservice close to original state and showcase how easy it is to use Sentry for OTEL even without changing the target application
- [ ] Add a provider for `SentryPropagator`, see https://github.com/getsentry/sentry-java/issues/2254#issuecomment-1575492805

**Comment by smeubank** [comment]
https://github.com/getsentry/opentelemetry-demo/issues/12

related to this as well 👍

**Comment by devurandom** [comment]
Will this allow me to annotate my source code with OpenTelemetry spans, and Sentry picks up attributes from the OpenTelemetry `Context` / `Span` and automatically adds them to events?  I.e. achieve what is done with `withScope` and `setTag` in these examples https://docs.sentry.io/platforms/java/enriching-events/scopes/#local-scopes, but using the OpenTelemetry Java API instead of the Sentry Java API?

How is https://github.com/getsentry/sentry-java/issues/3436 related to this?

**Comment by lbloder** [comment]
Hi @devurandom,
Actually we are focussing on the other way around. I.e. using the Sentry API to create OpenTelemetry spans under the hood. And then export these to Sentry. We are currently also exporting the spans created by OpenTelemetry Instrumentation to Sentry, so in theory, your use case should work as well. I will dig into this and let you know.

#3436 is basically replacing this issue. We did a lot of rework with Hubs/Scopes and also how we interface with OpenTelemetry. These changes will be part of our next Major Version (v 8). There are currently alpha versions available to test if you're interested. As of now we have released alpha 4 (https://github.com/getsentry/sentry-java/releases/tag/8.0.0-alpha.4).

I will update the newer issue with the open tasks from this one and then close it. You can track our progress in #3436 from now on.

**Comment by lbloder** [comment]
Closed in favor of #3436

**Comment by adinauer** [comment]
@devurandom 

> Will this allow me to annotate my source code with OpenTelemetry spans, and Sentry picks up attributes from the OpenTelemetry Context / Span and automatically adds them to events?

This should also work but depends on which attributes you'd like to set. Some of them would work if you use the correct name for the attribute. Some of those are listed in [dev docs](https://develop.sentry.dev/sdk/telemetry/traces/span-data-conventions/). The Sentry SDK should pick up attributes on he OTel span and send it to Sentry automatically.
