### ISSUE TITLE
Skip additional context for low end devices

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-java#2427]
### Description

The Android options offer `io.sentry.additional-context` to avoid adding additional context on low-end android devices because it can be slow. This was added with https://github.com/getsentry/sentry-java/pull/2100. We also point that out in the troubleshooting guide: https://docs.sentry.io/platforms/android/troubleshooting/#sentry-android-sdk-causes-anr

Instead, we should narrow it down on which devices this can be slow or cause ANRs and skip adding the additional context so customers don't have to find that out themselves. This can block customers with a user base in emerging markets.

**Comment by markushi** [comment]
Customer feedback: This not only limited to low-end devices: Relevant devices are on Android version 10, 11, 12. This is not specific to Sentry but historically these have given us some performance related issues. The RAM is about 4-6GB and storage is about 64-128GB.

**Comment by markushi** [comment]
This is currently not actionable for us as we can't narrow it down to the detailed issue.

**Comment by philipphofmann** [comment]
Worth noting that only a handful of customers complained about this. If we see this problem coming up again, we can revisit if we want to disable the feature for specific devices or maybe remove the additional context.
