### ISSUE TITLE
Track usage of APM for Jetpack Compose

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-java#2428]
### Description

We could add an entry to the integrations list to track how many users use the Jetpack Compose performance integration.

**Comment by kahest** [comment]
Related to https://github.com/getsentry/sentry-java/issues/1885

**Comment by adinauer** [comment]
Related to https://github.com/getsentry/sentry-java/issues/1885

**Comment by romtsn** [comment]
Closed by #2179
