### ISSUE TITLE
Get all user feedback reports by API

### ISSUE THREAD

**Issue by nienienienie** [getsentry/sentry-java#2443]
### Problem Statement

How to get all user feedback reports by API?

### Solution Brainstorm

I want to make custom tool for checking and alerting based on user feedback reports. How can I get user reports by sentry API?

**Comment by markushi** [comment]
Hey @nienienienie, our [web APIs](https://docs.sentry.io/api/) allow you to query for user feedback. Here's the link to the corresponding documentation: https://docs.sentry.io/api/projects/list-a-projects-user-feedback/
