### ISSUE TITLE
SDKs should not send tags by default but rather index them in snuba if it needs to be searchable

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-java#2444]
### Description

We should avoid setting tags when possible.

See meta issue for more details: https://github.com/getsentry/team-mobile/issues/60

I just checked Java/Android usage:

* Any tags set via SentryOptions.addContextTag() - but since they're custom values and empty by default I guess we can ignore those
* setTag("TimberTag", ...) -> [link](https://github.com/getsentry/sentry-java/blob/3f8d7b1cc869bb056c9db99b459e43f6c375784a/sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt#L266)
* setSideLoadedInfo(...) -> [link](https://github.com/getsentry/sentry-java/blob/81a3c3273f211de79706ad83e24929ef1ec58f0a/sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java#L896)

**Comment by kahest** [comment]
Need to talk to SnS to find out if using Tags makes sense in this case, and to make sure functionality is not lost if moved to Context.

**Comment by marandaneto** [comment]
Per https://github.com/getsentry/team-mobile/issues/60#issuecomment-1468487797
This issue can also be closed unless there are something new after my discussion with S&S

**Comment by smeubank** [comment]
closing issue, per Manoel's comment above. Yes, SDKs should not set Tags, users set tags and tags can be set on ingestion. If there are tags being set by the SDK, it should be resolved.
