### ISSUE TITLE
Only first event of given type appears in Sentry

### ISSUE THREAD

**Issue by eldar-b2c2** [getsentry/sentry-java#2458]
### Integration

sentry-log4j2

### Java Version

17

### Version

6.10.0

### Steps to Reproduce

1. We are using sentry-log4j2 and configuring Sentry appender in log4j2.xml, used for all application's loggers. The minimum log level for Sentry is ERROR.
2. We specify Sentry parameters using environment variables (SENTRY_DSN, SENTRY_ENVIRONMENT etc.). 
3. The application itself is running inside a container
4. When I generate an ERROR statement in the app log, I can see the first event of given type in Sentry. When I generate subsequent errors of the same type (for given environment), they never appear in Sentry.
5. If I change SENTRY_ENVIRONMENT to a different value and generate same ERROR again, I can see it in Sentry. When I generate subsequent errors of same type in the same environment they never appear in Sentry,.

With an application running outside a container and configured using system properties (rather than environment variables), it seems to work fine, as in all events of given type can be seen in Sentry.

When running with SENTRY_DEBUG=true we can see that events are always published to Sentry, i.e. we can see these lines:
- DEBUG: Envelope sent successfully
- DEBUG: Envelope flushed

Can you please provide any insight as to why this can be happening? Any information or pointers would be really appreciated. 

Versions:
io.sentry:sentry:6.10.0
io.sentry.sentry-log4j2:6.10.0
org.apache.logging.log4j:*:2.17.0

### Expected Result

All events published to Sentry should be visible in Sentry (not just the first event)

### Actual Result

Only first event is visible in Sentry (per environment)

**Comment by adinauer** [comment]
Hello @eldar-b2c2 , does the number of events increase?

<img width="626" alt="Screenshot 2023-01-09 at 08 22 07" src="https://user-images.githubusercontent.com/2542832/211258076-050a856f-5780-41f1-9351-4e8384ad454a.png">

There's a count on the top right of the event detail page (showing 506 in my screenshot). If you click it, it should take you to a list of events. Does that also only show a single event?

**Comment by eldar-b2c2** [comment]
Hello @adinauer ,
In my case event number is 2 (1 per each environment). It remains the same when I publish multiple events. In other words, it only includes the first event published in each env 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/109958834/211278305-542c476d-0574-41be-abbe-4d24da9388cc.png">

**Comment by adinauer** [comment]
I'll ask around. Will update here.

**Comment by adinauer** [comment]
@eldar-b2c2 can you please go to "Help" > "Contact Support" on the Sentry UI and ask for help there. Please also include the link to this issue. There could be many reasons for this. For looking into this it helps to know your org and project so please also include the name of the project in the request.

**Comment by adinauer** [comment]
It appears our support has handled your request. Closing this now. Please feel free to reopen if you need more help.
