### ISSUE TITLE
Spring Boot 3.0.1 does not work with with sentry

### ISSUE THREAD

**Issue by JakobStadlhuber** [getsentry/sentry-java#2461]
### Integration

sentry

### Java Version

17

### Version

6.11.0

### Steps to Reproduce

1. Create spring boot starter project with 3.0.1 with intelliJ, kotlin and gradle
2. Added io.sentry:sentry-spring-boot-starter:6.11.0" and io.sentry:sentry-logback:6.11.0
3. added application.properties sentry.dsn=xxx and sentry.traces-sample-rate=1.0
4. 
```
@Component
class Startup(
) : CommandLineRunner {
    override fun run(vararg args: String) {
        try {
            throw Exception("This is a test.")
        } catch (e: Exception) {
            Sentry.captureException(e)
        }
    }

}
```

### Expected Result

A log in the UI but in the tutorial it is still Waiting for error

### Actual Result

Nothing

**Comment by JakobStadlhuber** [comment]
Sentry.init("dsn") is necessary, then it works. Why is't that mentioned in the documentation? According to the documentation the application.properties entry is enough.

**Comment by adinauer** [comment]
Hello @JakobStadlhuber, Sentry should automatically initialize if you're using `sentry-spring-boot-starter` via `SentryAutoConfiguration`. Have you tried enabling `debug` (https://docs.sentry.io/platforms/java/guides/spring-boot/configuration/#debug) to see if it shows any problems?

**Comment by JakobStadlhuber** [comment]
I can now confirm it works with spring boot 2.7.7 but NOT with the newest release version of spring boot 3.0.1.

**Comment by JakobStadlhuber** [comment]
So Sentry just works with 3.0.1 when calling it programmatically BUT performance monitoring still does not work even calling it like this:

```
  Sentry.init { options ->
      options.dsn = sentryDsn
      options.tracesSampleRate = 1.0
  }
```

**Comment by adinauer** [comment]
@JakobStadlhuber are you using `sentry-spring-boot-starter-jakarta`? `sentry-spring-boot-starter` is meant for older versions of Spring Boot.

**Comment by JakobStadlhuber** [comment]
> @JakobStadlhuber are you using `sentry-spring-boot-starter-jakarta`? `sentry-spring-boot-starter` is meant for older versions of Spring Boot.

Thank you please provide this information the tutorial.

**Comment by adinauer** [comment]
We've just updated the wizard and docs https://docs.sentry.io/platforms/java/guides/spring-boot/
