### ISSUE TITLE
Auto instrumentation doesn't work + JDBC metrics doesn't send

### ISSUE THREAD

**Issue by NDruce** [getsentry/sentry-java#2465]
### Integration

sentry-spring-boot-starter

### Java Version

17

### Version

6.0.0

### Steps to Reproduce

Followed official tutorials, rereading them ~30 times, searching a lot of Internet for week, and now I decided to create issue.

I have all Maven dependencies, Sentry Exceptions are successfully sending (but settings in application.properties wasn't work so I wasted 1-2 days to make just work anything). But no one Spring Boot MVC requests was traced:
https://docs.sentry.io/platforms/java/guides/spring-boot/performance/instrumentation/automatic-instrumentation/
(all written in instruction I was made and this Bean was told me via System.out.println that it was called). But no Transactions in Sentry. My `sentry.properties` config:

```
dsn=https://**********@**************.ingest.sentry.io/**********
traces-sample-rate=1.0
sample-rate=1.0
debug=true
enable-tracing=true
enable-user-interaction-tracing=true
#exception-resolver-order=-2147483647
send-default-pii=true
max-request-body-size=medium
logging.minimum-event-level=info
logging.minimum-breadcrumb-level=debug
max-breadcrumbs=150
#in-app-includes="com.companyname.application"
```

I made custom instrumentation:
https://hastebin.com/uwulijeput.php

But I think it's kind of crutch and just a desperation, because no other (and more correct) way of tracing requests doesn’t want to work, and therefore I write the entire implementation myself...

With my instrumentation I have no ability to get all detailed stack trace of calling functions where each submethod call is new child span. And I forced to manually declare spans for each submethod in code.

I just want to understand __why__ automatic instrumentation don't working. Because now I have to take time for write each separate span for a lot of method calls.
When with automatic instrumentation, having code like

```
public void checkout() {
    paymentServiceCall();
    anyOtherMethod();
}

public void paymentServiceCall() {
    runFraudScorer();
    withdrawFunds();
}
```

, I can leave this code as is and see in Sentry this:

==========================================================

- checkout span [took X ms]:
  - paymentServiceCall span [took X ms]:
    - runFraudScorer span [took X ms]
    - withdrawFunds span [took X ms]
  - anyOtherMethod span [took X ms]

==========================================================

I want see this look of Trace ^
And to don't to write a lot of times this:
```
public void checkout() {
    ITransaction transaction = httpServletRequest.getAttribute("sentryTransactionStoredInRequestAttributesToRetrieveItFromDoFilterMethod");

    ISpan paymentServiceCall_Span = transaction.startChild("paymentServiceCall()");
    paymentServiceCall(paymentServiceCall_Span);
    paymentServiceCall_Span.finish();

    ISpan anyOtherMethod_Span = transaction.startChild("anyOtherMethod()");
    anyOtherMethod(anyOtherMethod_Span);
    anyOtherMethod_Span.finish();
}

public void paymentServiceCall(ISpan parentSpan) {
    ISpan runFraudScorer_Span = parentSpan.startChild("runFraudScorer()");
    runFraudScorer(runFraudScorer_Span);
    runFraudScorer_Span.finish();

    ISpan withdrawFunds_Span = parentSpan.startChild("withdrawFunds()");
    withdrawFunds(withdrawFunds_Span);
    withdrawFunds_Span.finish();
}
```

### Expected Result

Described above. 

Also JDBC tracing is not working, I don't see anything in Sentry, but configured that by instruction. My `application.properties`:
```
pebble.suffix = .peb
pebble.cache=false
spring.application.name=Application
management.metrics.web.server.auto-time-requests=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.hibernate.ddl-auto=create

spring.datasource.url=jdbc:p6spy:h2:mem:testdb
spring.datasource.username=********
spring.datasource.password=********
spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver

endpoints.enabled=true
endpoints.actuator.enabled=true
management.endpoints.enabled-by-default=false
management.endpoint.metrics.enabled=true
management.endpoints.metrics.enabled=true
management.endpoints.web.exposure.include=*
```

Maven:
```
<dependency>
    <groupId>io.sentry</groupId>
    <artifactId>sentry-jdbc</artifactId>
    <version>6.11.0</version>
</dependency>
```

### Actual Result

No any transaction for any controller request was created. Only with instrumentation coded on my own... As the latest way and the only possible (and single working) way

**Comment by adinauer** [comment]
Hello @NDruce I presume you're using Spring Boot 3 in combination with `sentry-spring-boot-starter`. Can you please give this another try with  `sentry-spring-boot-starter-jakarta`? Sorry for the inconvenience, we're working on improving the docs on the matter.

**Comment by adinauer** [comment]
@NDruce can you please share a reproducible sample. I'm unable to reproduce your issue so far. Putting your properties in `application.properties` (and prefixing them with `sentry.`, e.g. `sentry.dsn=...`) works for me.

**Comment by adinauer** [comment]
Can you try updating your `pom.xml`:

```
<dependency>
	<groupId>io.sentry</groupId>
	<artifactId>sentry-bom</artifactId>
	<version>6.0.0-beta.2</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>
```

Having an old version here might be causing issues.

Do other settings, that are not Sentry specific but spring specific in your `applicaton.properties` take effect?

**Comment by adinauer** [comment]
Things you can try:
- provide a reproducible sample so I can test things and help you
- check (e.g. using debugger) what's calling Sentry.init; I assume it's not our Spring Boot integration performing the init because it checks for `dsn` to be present.
- check Spring DEBUG log. It should show, amongst others, these lines:
```
Creating shared instance of singleton bean 'sentry-io.sentry.spring.boot.jakarta.SentryProperties'
SentryAutoConfiguration matched:
      - @ConditionalOnProperty (sentry.dsn) matched (OnPropertyCondition)
SentryLogbackAppenderAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'ch.qos.logback.classic.LoggerContext', 'io.sentry.logback.SentryAppender' (OnClassCondition)
      - @ConditionalOnProperty (sentry.logging.enabled=true) matched (OnPropertyCondition)
      - @ConditionalOnBean (types: io.sentry.spring.boot.jakarta.SentryProperties; SearchStrategy: all) found bean 'sentry-io.sentry.spring.boot.jakarta.SentryProperties' (OnBeanCondition)
```

**Comment by adinauer** [comment]
Have you looked at https://docs.sentry.io/platforms/java/guides/spring-boot/performance/instrumentation/custom-instrumentation/ . It explains how you can do it. Please let me know if you have any more questions.

**Comment by adinauer** [comment]
`restartedMain` indicates dev tools restarting, haven't tried that. I assume that's the reason for the different logs as well. Please try a clean restart of the application.

**Comment by adinauer** [comment]
> Developer tools are automatically disabled when running a fully packaged application. If your application is launched from java -jar or if it is started from a special classloader, then it is considered a “production application”. You can control this behavior by using the spring.devtools.restart.enabled system property. To enable devtools, irrespective of the classloader used to launch your application, set the -Dspring.devtools.restart.enabled=true system property. This must not be done in a production environment where running devtools is a security risk. To disable devtools, exclude the dependency or set the -Dspring.devtools.restart.enabled=false system property.

Maybe this helps. Found it here: https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.devtools

I'm still unable to reproduce. Please provide a sample that allows me to help you if you need my assistance.

**Comment by adinauer** [comment]
You can find a sample here: https://github.com/getsentry/sentry-java/tree/main/sentry-samples/sentry-samples-spring-boot-jakarta

There's more in the parent directory if it's not the one you need.

**Comment by adinauer** [comment]
Did you try starting the sample with your own DSN to verify that's working?

**Comment by adinauer** [comment]
So the problem only shows up in your own application but not our sample, correct? I'm still unable to help you without a sample that reproduces this. If you can tell me how I need to modify our sample to get your error to show up, I might be able to help.

**Comment by adinauer** [comment]
Hello @NDruce. Thank you for the sample. I tested and it sends events to Sentry.

After adding an `@Entity` and `Repository` to your sample and using the repo in `TestController` a transaction is created for `/api/test` which contains a `Span` for the DB query. This also shows up in Sentry UI.

The log messages seem to be linked to using `spring-boot-starter-data-jpa`. If I strip that (and related code) from your sample the log messages disappear. When adding `spring-boot-starter-data-jpa` to our sample the log messages also show up.

I still haven't figured out how to fix it. I also haven't found any broken features due to this either.

**Comment by adinauer** [comment]
1. The `http.server` op should only be shown for the topmost span of the transaction. You can see the nicer looking name on top of your screenshot: `POST /api/autocomplete`.
2. You can use `beforeSend` to filter out errors and `beforeSendTransaction` to filter out transactions
	- https://docs.sentry.io/platforms/java/guides/spring-boot/configuration/filtering/#using-platformidentifier-namebefore-send-
	- https://docs.sentry.io/platforms/java/guides/spring-boot/configuration/filtering/#using-platformidentifier-namebefore-send-transaction-
3. We use a `ThreadLocal` to set the `Hub` on the current `Thread`. So invocations to the static `Sentry.*` should go to the correct transaction. This (https://docs.sentry.io/platforms/java/guides/spring-boot/performance/instrumentation/custom-instrumentation/#add-more-spans-to-the-transaction) should help figure out the code.
4. Should be as simple as slapping `@SentryTransaction` on the job class. See https://docs.sentry.io/platforms/java/guides/spring-boot/performance/instrumentation/custom-instrumentation/#capturing-a-transaction
5. This is just a breadcrumb that was added because your `sentry-logback` is configured to add breadcrumbs for log lines of level `debug` or higher (`sentry.logging.minimum-breadcrumb-level=debug` in `application.properties`). These may be of varying usefulness.

Hope this helps.

**Comment by adinauer** [comment]
In Spring WebMVC requests are handled in a blocking manner. Number of threads can be controlled using config properties like `server.tomcat.threads.max=1`. So the `ThreadLocal` approach works there. For WebFlux and similar the model doesn't work so well. There's multiple issues on this repo and we're exploring fixes for it but haven't found one we like yet.

I'll take a look at the `Shutdown in progress`.

**Comment by adinauer** [comment]
Closing this now as all questions seem to have been answered and the PR has been merged. Feel free to reopen if you need more assistance.
