### ISSUE TITLE
Support Jetpack Compose in profiling

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2487]
### Description

For now, our profiling product will ignore Jetpack Compose functions/traces, because they are ignored from systrace when not using their special `androidx.compose:tracing` artifact.

More details:
https://medium.com/androiddevelopers/jetpack-compose-composition-tracing-9ec2b3aea535
https://developer.android.com/jetpack/compose/performance/tracing#terminal

**Comment by romtsn** [comment]
Some investigations from @markushi https://www.notion.so/sentry/Jetpack-Compose-Tracing-2f580399ad854293898faf632ef902e9. The tracing annotations are kept even in production release builds.

We should check how much does it affect the size of the app - perhaps, this could be just a docs update, where we recommend our users to manually include the `androidx.compose:tracing:` artifact to get the profiling working for Jetpack Compose.

@stefanosiano is gonna verify if the current profiling implementation works with Jetpack Compose or not and summarize his findings here.

**Comment by stefanosiano** [comment]
Profiling works fine with compose. The `androidx.compose:tracing` artifact is needed only when taking system traces via android studio, or when capturing profiles using perfetto in the command line.
The method we use (the Java/Kotlin method sample provided by the Android runtime) collects the traces correctly.
