### ISSUE TITLE
Matrix build for OTEL versions

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2490]
### Description

Currently we only build against a single version of OTEL (e.g. `1.20.1`). We could create a build matrix that releases our OTEL Java Agent based on different OTEL versions leading to multiple artifacts produced.

**Comment by smeubank** [comment]
Why? Would this give users the ability to only use our SDK version according to different OTel version? I don;t think this is somethin we want to support, if it is something users ask for we can re-open, but the user facing version of this sounds rather complex and unnecessary
