### ISSUE TITLE
`ContextTagsEventProcessor` should add context tags to transactions too

### ISSUE THREAD

**Issue by verglor** [getsentry/sentry-java#2495]
### Problem Statement

Currently [ContextTagsEventProcessor](https://github.com/getsentry/sentry-java/blob/main/sentry-spring/src/main/java/io/sentry/spring/ContextTagsEventProcessor.java) adds context tags only to events (errors) not transactions.

**Comment by adinauer** [comment]
Thanks for creating this issue. Makes sense. Should be fairly straight forward to also add the tags coming from MDC to a transaction in the same EventProcessor by overriding `SentryTransaction process(@NotNull SentryTransaction transaction, @NotNull Hint hint)`.

Can't say when we'll implement this but you can create your own `EventProcessor` in your application and put the logic there as a workaround.

**Comment by verglor** [comment]
I already created workaround in [grails-sentry](https://github.com/pmedianetwork/grails-sentry/commit/f2b7e46cca6d785f7865f69e83e0b4824d792f4f). I can also create PR here.

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
