### ISSUE TITLE
Sentry Spring Boot Starter 6.12.1 uses a lot of memory

### ISSUE THREAD

**Issue by ayrtonnadgel** [getsentry/sentry-java#2496]
### Integration

sentry-spring-boot-starter

### Java Version

17

### Version

6.12.1

### Steps to Reproduce

I have a spring application, with Sentry. This week we update sentry from 6.9.2 to 6.12.1. After the update, a few hours later, Sentry started to register "OutOfMemoryError Java heap space" on that application. Monitoring the stats, we could see a continuous growth of memory. One of the instances had 5GB of memory usage, where usually uses 250MB.

![image](https://user-images.githubusercontent.com/1630585/214704482-eff75f4c-c307-4691-83cd-928b6918e749.png)

Then we did the downgrade of sentry to 6.9.2, and after that everything return to normal.  

![image_1](https://user-images.githubusercontent.com/1630585/214706321-b832494a-ebf2-4fef-a71c-dde187745527.png)

No sentry special configuration,  

### Expected Result

With version 6.12.1, we could see a large use of memory, where with the version 6.9.2 everything runs normal.

### Actual Result

With version 6.12.1, we could see a large use of memory.

**Comment by adinauer** [comment]
@ayrtonnadgel thanks for reporting. Will take a look.

**Comment by adinauer** [comment]
I'm able to reproduce the problem. Now trying to pinpoint where we introduced this then figure out a fix.

**Comment by adinauer** [comment]
Found the problem. https://github.com/getsentry/sentry-java/pull/2498 simply mitigates the problem. We'll work on that feature and add it back once it's working properly. Hoping to get out a release with the fix soon.

**Comment by cocorossello** [comment]
I also noticed this behaviour upgrading from 6.11.0 to  6.1.2.1. Glad you found it

**Comment by adinauer** [comment]
Apologies to everyone affected. `6.13.0` is now out.

**Comment by adinauer** [comment]
Anything up to `6.11.0` should not be affected. If you're on `6.12.0` or `6.12.1` please upgrade to `6.13.0`.

**Comment by cocorossello** [comment]
Just deployed 6.13.0 this morning, works fine
