### ISSUE TITLE
ignore exception configuration is not working properly

### ISSUE THREAD

**Issue by muhammedOzbilici** [getsentry/sentry-java#2497]
### Integration

sentry-log4j2

### Java Version

17

### Version

6.12.1

### Steps to Reproduce

spring boot version is `2.5.8`.
set this property;

`sentry.ignored-exceptions-for-type=java.lang.RuntimeException,java.lang.IllegalStateException`

### Expected Result

not to see that custom exception that I gave for `sentry.ignored-exceptions-for-type`

### Actual Result

still getting that exception on sentry panel.

**Comment by lbloder** [comment]
@muhammedOzbilici Just tested this with our spring-boot-sample application (https://github.com/getsentry/sentry-java/tree/main/sentry-samples/sentry-samples-spring-boot) and converted it to work with log4j

With the following property set in `application.properties`
`sentry.ignored-exceptions-for-type=java.lang.RuntimeException,java.lang.IllegalStateException,io.sentry.samples.spring.boot.MyIgnoredException`

When throwing `MyIgnoredException` it is ignored and not sent to Sentry, indicated by following line in the log: `Event was dropped as the exception class io.sentry.samples.spring.boot.MyIgnoredException is ignored`

Could you provide more details on how we can reproduce?

**Comment by muhammedOzbilici** [comment]
I don't know if it's related to dependencies.
I used this dependency ;
<```
dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-log4j2</artifactId>
            <version>6.12.1</version>
        </dependency>
```
then changed it to;
```
        <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-spring-boot-starter</artifactId>
            <version>6.12.1</version>
        </dependency>
        <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-logback</artifactId>
            <version>6.12.1</version>
            <scope>test</scope>
        </dependency>      
```
same as in sample project.
And I set dsn address in application.properties.
Now it's not sending anything to Sentry.
It's just a simple project with a controller throws an exception that I test with Postman. nothing else.

**Comment by lbloder** [comment]
@muhammedOzbilici 
For `log4j2` to work properly, please follow the instructions mentioned on the docs page (https://docs.sentry.io/platforms/java/guides/spring-boot/logging-frameworks/#log4j2).

Your second example regarding `logback` looks like it doesn't work because you have set the dependency scope to `test`.

Also, please note, that only exceptions that fully match will be ignored..
The following configuration will only ignore `RuntimeException` and `IllegalStateException`, none of their descendants:
`sentry.ignored-exceptions-for-type=java.lang.RuntimeException,java.lang.IllegalStateException`

**Comment by muhammedOzbilici** [comment]
@lbloder ok, found the cause. I need to add `sentry-spring-boot-starter` dependency to use `ignored-exceptions-for-type` . if you want to use only `sentry-log4j2` dependency, there is a workaround for that also ;

```
Sentry.init(options -> {
                    options.setEnableExternalConfiguration(true);
                    options.setDsn("");
                    options.setBeforeSend((event, hint) -> {
                        if (SENTRY_IGNORED_EXCEPTIONS.contains(event.getThrowable().getClass().getSimpleName())) {
                            return null;
                        }
                        return event;
                    });
                }
        );
```

**Comment by adinauer** [comment]
@muhammedOzbilici glad you figured it out. Please upgrade to the latest version of the SDK as `6.12.1` has some memory issues causing your application to go OOM. Sorry for the inconvenience.
