### ISSUE TITLE
Validate Hybrid Sentry SDKs Compile

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-java#2506]
### Description

To ensure changes in this repository don't break the hybrid SDKs as RN and Flutter, we can add a GH action to validate that the current changes of a PR still compile with the hybrid SDKs. We could use a similar approach as the Cocoa SDK uses for integration tests see https://github.com/getsentry/sentry-cocoa/issues/2672.

**Comment by markushi** [comment]
Let's extend our PR template to consider breaking changes for hybrid SDKs.

**Comment by philipphofmann** [comment]
PR request template change https://github.com/getsentry/sentry-java/pull/2511.
