### ISSUE TITLE
Add a `finalTimeout` option to the UI event transactions

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2514]
### Description

As part of that, we could also improve UI event transactions duration, and have a configurable `finalTimeout` which defaults to 30 seconds to forcefully finish the transaction with DEADLINE_EXCEEDED status.

**Comment by stefanosiano** [comment]
We are dropping the INP support from this issue for the moment.
We'll open a new issue about that later on.

**Comment by markushi** [comment]
Let's also consider this for Java backend transactions.

**Comment by romtsn** [comment]
Closed by #2865
