### ISSUE TITLE
No event sent when I use apollo3 interceptors

### ISSUE THREAD

**Issue by bellierjonathan** [getsentry/sentry-java#2524]
### Problem Statement

Hello,

I tried to implement `Apollo3` interceptor by using the extension [here](https://github.com/getsentry/sentry-java/blob/main/sentry-apollo-3/src/main/java/io/sentry/apollo3/SentryApolloBuilderExtensions.kt) but when I test it looks to not work.

**Init my apollo client**

```Kotlin
return ApolloClient.Builder()
            .serverUrl(customEndpoint ?: getClientUrl())
            .sentryTracing()
            .okHttpClient(
                createOkHttpClient(
                    interceptors = interceptors,
                    isLongTimeout = withLongTimeout,
                    authenticator = getAuthenticator()
                )
            )
            .normalizedCache(cacheFactory, getCacheKeyGenerator(), getCacheKeyResolver())
            .also { builder ->
                adapters.forEach {
                    builder.addCustomScalarAdapter(it.key, it.value)
                }
                getAdditionalApolloInterceptors().forEach {
                    builder.addInterceptor(it)
                }
            }
            .build()
```

**Manifest**
```XML
<meta-data
            android:name="io.sentry.auto-init"
            android:value="false" />

        <meta-data
            android:name="io.sentry.dsn"
            android:value="XXXXXXXX" />
        <!-- Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
           We recommend adjusting this value in production. -->
        <meta-data
            android:name="io.sentry.traces.sample-rate"
            android:value="1.0" />
        <!-- Enable user interaction tracing to capture transactions for various UI events (such as clicks or scrolls). -->
        <meta-data
            android:name="io.sentry.traces.user-interaction.enable"
            android:value="true" />
```

**Sentry init**

```Kotlin
SentryAndroid.init(application) { options ->
            options.dsn = XXXXXX
            // Add a callback that will be used before the event is sent to Sentry.
            // With this callback, you can modify the event or, when returning null, also discard the event.
            options.environment = BuildConfig.FLAVOR
            options.beforeSend = SentryOptions.BeforeSendCallback { event: SentryEvent, hint: Hint ->
                if (SentryLevel.DEBUG == event.level) {
                    null
                } else {
                    event
                }
            }
            options.isDebug = true
            options.tracesSampleRate = 1
        }
```

When I use the debugger I pass inside the `SentryApollo3HttpInterceptor` the `hub.addBreadcrumb(breadcrumb, hint)` is called.
But when I got to **Sentry issues** nothing is dispatched...

I try to understand what happening.

1. Do you have any idea why it's not working?
2. Is there a way to configure logic of defining what is an error depending of the backend logic? For example if we have error in `response.errors.message` we should considerate this response as an error and send it to sentry by using the interceptor? Should I use the `BeforeSpanCallback`?

Thanks

**SDK Versions**
```Groovy
const val sentry = "6.13.0"
const val sentry_plugin_version = "3.4.1"
```

**Comment by adinauer** [comment]
Hello @bellierjonathan, can you please try reordering the builder calls and put `.sentryTracing()` later in the chain. I'm guessing it's overridden by something else.

**Comment by adinauer** [comment]
We haven't yet investigated how to add the feature. So my suggestion would be to play around with it and see for yourself what you find most helpful in pinpointing problems. If you have a meaningful exception, capture that. You may also want to take a look at how issues are grouped in Sentry UI. We're happy to learn from your findings, so please share them 🙏 .

**Comment by romtsn** [comment]
Created https://github.com/getsentry/sentry-java/issues/2639 to track this feature there, closing this one.
