### ISSUE TITLE
`HintUtils.isFromHybridSdk` and `HintUtils.setIsFromHybridSdk` should use hints instead

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#2525]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.0

### Proguard

Disabled

### Version

6.13.1

### Steps to Reproduce

Events captured on Hybrid SDKs directly in the native layer (Java/Kotlin) will not add extra context on the `DefaultAndroidEventProcessor`, `ScreenshotEventProcessor`, etc.
The reason is that the `HintUtils.isFromHybridSdk` method checks if the event was created by a certain SDK prefix.

After [those changes](https://github.com/getsentry/sentry-dart/commit/8bea1f1e12c87602db6efaccfa4bfab27a7f15a1):

```
val sdkVersion = SdkVersion(name, version)
options.setSentryClientName(name)
options.setSdkVersion(sdkVersion)
```

Where the `name` and `version` are actually the name and version of the Hybrid SDK, every event will be considered coming from the Hybrid SDK even though they were captured directly in the native layer.

### Expected Result

Events will be enriched with extra context

### Actual Result

Events won't be enriched with extra context

**Comment by marandaneto** [comment]
@krystofwoldrich I believe this method was introduced by you, have you considered this use case?
Did RN already migrate to calling `setSentryClientName` and `setSdkVersion`?

**Comment by krystofwoldrich** [comment]
@marandaneto RN Did not migrate to calling `setSentryClientName` and `setSdkVersion` yet.

By should use hints you mean introducing new property for example `Hint.isFromHybrid`?

**Comment by marandaneto** [comment]
The SDK already had something similar called `HintUtils.shouldApplyScopeData(hints)` and other options.
With hints, if we pass something specific when capturing events, it's possible to know where the events come from (Hybrid SDKs or not).

`event.platform` is very limited, for Dart, for example, is `other`.
I don't think SDKs have `platform_context`.

I don't know the solution for this as of now, would need to think thru it.

**Comment by krystofwoldrich** [comment]
I've tested this with RN and the native crashes are not marked as hybrid even after setting the [RN SDK name and version](https://github.com/getsentry/sentry-react-native/pull/2814).

Event hint `isHybrid` is added in `OutboxSender`. I don't know enough about the Java SDK to say in what case this will fail. 
https://github.com/getsentry/sentry-java/blob/16371c5aaef2233c2eb4084c8b923534dca58357/sentry/src/main/java/io/sentry/OutboxSender.java#L137

**Comment by krystofwoldrich** [comment]
@romtsn @markushi Do you know when is `OutboxSender` used besides Hybrid SDKs?
I guess when an error comes from a native?

**Comment by marandaneto** [comment]
> @romtsn @markushi Do you know when is `OutboxSender` used besides Hybrid SDKs? I guess when an error comes from a native?

`EnvelopeFileObserverIntegration` so Hybrid SDKs and sentry-native events.
`SendCachedEnvelopeFireAndForgetIntegration` sending of cached/offline events when the above failed to send right away (after restarting the app).
I believe those 2 use cases.

**Comment by krystofwoldrich** [comment]
Thanks for the details.

So `SendCachedEnvelopeFireAndForgetIntegration` is also used for cached/offline java events, right? 
Cached and offline don't go thru the regular pipeline anyway (they already have viewHierarchy and screenshots and other context). So even tho they will get marked as hybrid, it won't cause issues at the moment.

Or am I missing something.

**Comment by krystofwoldrich** [comment]
Based on the latest updates from https://github.com/getsentry/team-mobile/issues/48

This won't be an issue as the native SDKs shipped with Hybrids will be named `sentry.java.android.hybrid-name`.

**Comment by markushi** [comment]
@krystofwoldrich could we close this issue in favor of https://github.com/getsentry/team-mobile/issues/48?
cc @marandaneto
