### ISSUE TITLE
Sentry Server to Spring Boot SDK or other SDK version compatibility matrix

### ISSUE THREAD

**Issue by Aleson95** [getsentry/sentry-java#2529]
### Description

Hello recently in our organization we upgrade our Sentry Server version from 20.10.1 to 22.09.

The applications or microservices that uses the sentry with the same SDK version are still able to put data into the server.
Is there any compatibilty matrix between Sentry Server and SDK version? 
example many in our team uses the Spring Boot SDK, in case there is a compatibility issue the application teams can perform mitigation to upgrade the dependency.

**Comment by adinauer** [comment]
Hello @Aleson95 we don't have any compatibility matrix to offer sadly. Are you experiencing any issues? We try to be backward compatible where possible.

**Comment by Aleson95** [comment]
Hello @adinauer thank you for the reply, currently everything still works just wanted to make sure if there is some specification that needs to be followed.

**Comment by adinauer** [comment]
OK great to hear. If you run into issues, please let us know. I'll close this now. Feel free to reopen if you need help.
