### ISSUE TITLE
Support for Sentry User Feedback

### ISSUE THREAD

**Issue by jezell** [getsentry/sentry-java#253]
Is this coming soon?

**Comment by tkaemming** [comment]
You can fetch the last event ID as of GH-255, which was released as part of [7.7.1](https://github.com/getsentry/raven-java/releases/tag/v7.7.1). We'll probably provide some more explicit documentation and possibly some tooling around this soon, but until then, this at least allows you to grab the last event recorded by the `Raven` instance (assuming you've instantiated only one), which you can drop into an error template as discussed in the [user feedback blog post.](https://blog.sentry.io/2016/04/21/introducing-user-feedback.html)

**Comment by nbransby** [comment]
@bretthoerner maybe you can help with this one?

**Comment by bretthoerner** [comment]
Sorry, it's not widely supported in our mobile SDKs currently. I think there is some work going on for iOS that may guide the plans here.

**Comment by DanielHabenicht** [comment]
Are there any updates to this?

**Comment by marandaneto** [comment]
@DanielHabenicht unfortunately not in Q1, but it's on the roadmap.
btw this feature won't land on this repo but on https://github.com/getsentry/sentry-android
it's our brand new SDK, please try it out and feedback is welcomed, we intend to move away from RC this week.

**Comment by nbransby** [comment]
My project is java desktop based, what does this new android sdk mean for me?

**Comment by bruno-garcia** [comment]
It'll come in Q4 btw, earlier later than later in the Q.

**Comment by bruno-garcia** [comment]
Coming up on the next release: #1017 Thanks @philipphofmann

**Comment by philipphofmann** [comment]
PR is already merged. This is going to be in the next release.
