### ISSUE TITLE
Extend Device Context with CPU info

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2561]
Our [device context docs](https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context) describe a few new CPU related fields which are not provided by the mobile SDKs yet.

* `processor_count`
* `cpu_description`
* `processor_frequency`

We already send this with profiles, so we could just reuse the same logic and enrich events with this data in our `DefaultAndroidEventProcessor`

**Comment by romtsn** [comment]
We could also apply this for Java backend/desktop, so maybe makes sense to have a generic interface that you set to `SentryOptions` and android has its own specific implementation.

**Comment by markushi** [comment]
This feature shipped with the `6.17.0` release 🚀
