### ISSUE TITLE
Check Session Cookies sent by SDK

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-java#2562]
## Summary

Session cookie values logged in Sentry issues, allowing for impersonation if injected into a cookie.

## Cause

Originally discovered in the Sentry Python SDK (specifically the Django Integration) sends the cookie values by default. In addition, Sentry SaaS / self-hosted is configured to send_default_pii.

**Comment by adinauer** [comment]
Only Spring (Boot) integrations did send cookies (if `sendDefaultPii` enabled). Sent a PR to fix.
