### ISSUE TITLE
Native debug image module list cache can't be refreshed

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-java#2586]
### Integration

sentry-android-ndk

### Build System

Gradle

### AGP Version

7.4.0

### Proguard

Enabled

### Version

latest

### Steps to Reproduce

1. Have an app which loads native libs
2. Delay the loading of extra native libs

### Expected Result

When events are sent the debug images list should be complete. But since the list get's cached it might be incomplete. On top of that there's no easy way to clear the cache right now.

As a workaround you could keep the reference to `SentryAndroidOptions` an call clear manually.
````
final SentryAndroidOptions options = new SentryAndroidOptions();
// ....
SentryAndroid.init(options);

// at a later point in time
System.loadLibrary(...)
options.getDebugImagesLoader().clearDebugImages();
```` 

### Actual Result

The debug images list can be incomplete, which in turn lead to missing information in stack trace elements.

Related `sentry-native` issue: https://github.com/getsentry/sentry-native/issues/483

**Comment by romtsn** [comment]
Maybe we could also add some docs to troubleshooting/ndk pages on how to clear the cache from native after investigation

**Comment by markushi** [comment]
Quick update: After some more investigation the modules list for crashes is created within `sentry-native` and therefore it's best to clear the cache on the native side as well. This can be done using the 
````
sentry_clear_modulecache();
```` 
More [details can be found here](https://github.com/getsentry/sentry-native/blob/903c17ae20888679caab1871cc74de577509452e/include/sentry.h#L1222-L1231).

**Comment by markushi** [comment]
Let's document this better in the NDK section of our docs.
