### ISSUE TITLE
Send time-to-initial-display and time-to-full-display as measurement too

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#2587]
### Problem Statement

`time-to-initial-display` and `time-to-full-display` spans are cool, but they would be cooler if sent as measurements, other than spans, too

Meta-issue: https://github.com/getsentry/team-mobile/issues/86

**Comment by romtsn** [comment]
Closed in https://github.com/getsentry/sentry-java/pull/2611
