### ISSUE TITLE
UI Event Transactions Same Event on Same Element Change 

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2594]
We decided in https://github.com/getsentry/sentry-javascript/pull/7236 that the SDKs should behave in the same way if there is the same or different event on the same UI element.

Previously, the SDKs rescheduled the idle timeout if they received the same UI event with the same type for the same UI element. This changes now to discard the transactions if it doesn't have any children or to finish the transaction with status ok when having children.

For more info see https://github.com/getsentry/develop/pull/856.

**Comment by markushi** [comment]
As discussed in the daily, we want to have this behavior for clicks - but not for scrolls or swipes.
