### ISSUE TITLE
Crash when closing sentry

### ISSUE THREAD

**Issue by bmarty** [getsentry/sentry-java#2601]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.6

### Proguard

Enabled

### Version

6.15.0

### Steps to Reproduce

Call `Sentry.close()`

### Expected Result

No crash

### Actual Result

The application crashes.

Here is the stack trace:

```
Thread: main, Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.lifecycle.LifecycleRegistry.removeObserver, parameter observer
at androidx.lifecycle.LifecycleRegistry.removeObserver(LifecycleRegistry.kt:4)
at io.sentry.android.core.AppLifecycleIntegration$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:12)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

I believe that the issue is coming from [these lines](https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java#L112-L131)

When `removeObserver` is invoked, the `watcher` is null.

This is not new code, but the crash is occurring only now, I am not sure why.

Also this does not crash on every device. Crash on Android 10.

**Comment by jmartinesp** [comment]
When I tried to debug the issue I confirmed that this [`watcher = null`](https://github.com/getsentry/sentry-java/blob/469420402e4717906783a744f8e2fb156168ec25/sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java#L126) line gets called before the runnable in [`handler.post(() -> removeObserver());`](https://github.com/getsentry/sentry-java/blob/469420402e4717906783a744f8e2fb156168ec25/sentry-android-core/src/main/java/io/sentry/android/core/AppLifecycleIntegration.java#L124), so at the `removeObserver` call, watcher is already null.

**Comment by romtsn** [comment]
Hey, apologies for the crash, yeah that indeed can be a problem when we use handler, we'll look into this!

**Comment by milos-steps-app** [comment]
Hi @romtsn, thx for the fast reaction.

In my case it's:
id 'io.sentry.android.gradle' version '3.4.2'
sentryVersion = '6.15.0'

and when going from 
def lifecycle_version = "2.5.1" // July 27, 2022
to 
def lifecycle_version = "2.6.0" // March 8, 2023

it started happening on app start for all emulators/devices.

**Comment by romtsn** [comment]
@milos-steps-app thanks for the extra info, we'll check this as well, I'm gonna raise the priority here as it seems to be more critical

**Comment by milos-steps-app** [comment]
@romtsn  just an update 

id 'io.sentry.android.gradle' version '3.4.3'
sentryVersion = '6.16.0'

and when going from
androidx.activity:activity-ktx:1.6.1 // October 24, 2022
to
androidx.activity:activity-ktx:1.7.0 // March 22, 2023

happens on app start for all emulators/devices.

**Comment by nvkleban** [comment]
This happened to me as well after updating my dependencies, do we have any workarounds?

**Comment by markushi** [comment]
Hey everyone, thanks for providing additional feedback!
Good news: I could reproduce the issue.

Right now I see two workarounds:
1. Calling `Sentry.close()` on the main thread
2. Disabling both "Auto Session Tracking" and "App Lifecycle Breadcrumbs"

We're already working on fix, I'll keep you posted about any update.

**Comment by markushi** [comment]
Waiting for feedback, see https://github.com/getsentry/team-mobile/issues/77#issuecomment-1482773678

**Comment by milos-steps-app** [comment]
Hi @markushi , thx for the quick fix and release.

I can confirm my issue is all gone with use of latest 6.17.0 release.

Thank you.
