### ISSUE TITLE
The desensitization log is displayed

### ISSUE THREAD

**Issue by FangPengbo** [getsentry/sentry-java#2613]
### Integration

sentry

### Java Version

8

### Version

1.7.30

### Steps to Reproduce

@Slf4j

log.info("this result{}",true)

### Expected Result

Actual Result

The desensitization data is displayed

### Actual Result

![T4SpF.png](https://i.328888.xyz/2023/03/21/T4SpF.png)

**Comment by adinauer** [comment]
Hello @FangPengbo I wasn't able to reproduce the problem. Will ask the team for ideas. What Senry logging integration are you using combined with SLF4J? Is it Logback, Log4j2 or JUL?

**Comment by FangPengbo** [comment]
The log content is desensitized, but the message in the placeholder will be output to #0 #1 #2...

**Comment by adinauer** [comment]
@FangPengbo can you please contact support from the Sentry UI and link this issue?

**Comment by FangPengbo** [comment]
> @FangPengbo can you please contact support from the Sentry UI and link this issue?

ok
