### ISSUE TITLE
Wrong idle transactions duration

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#2615]
### Description

Automatic ui transactions have wrong duration.
I can see it on every screen load with the `time-to-initial-display` and `time-to-full-display` spans, except for the first screen, where the app start span is present. I'm not sure how it is related, though.
The strange thing is that the root span duration is correct, but the transaction duration is lower.
We can open any screen load transaction to verify it.
It's probably something related to the idle timeout and the waitForChildren flag

**Comment by philipphofmann** [comment]
The start_timestamp of the transaction is `1679418448.178`, while the spans started at `1679418445.494`


[Transaction link](https://sentry-sdks.sentry.io/performance/sentry-android:9a5900084c7141e5bb95d94dae5956d8/?breakdown=none&project=5428559&query=&showTransactions=p100&sort=-transaction.duration&statsPeriod=14d&transaction=ProfilingActivity)

[JSON link](https://sentry-sdks.sentry.io/api/0/projects/sentry-sdks/sentry-android/events/78f05fc3c9474c4190ff1813b6ac546c/json/)

```json
  "spans": [
    {
      "timestamp": 1679418452.241278,
      "start_timestamp": 1679418445.494,
      "exclusive_time": 6747.277975,
      "description": "ProfilingActivity initial display",
      "op": "ui.load.initial_display",
      "span_id": "0cfc6f5fb7784a4b",
      "parent_span_id": "729a97b83ccb4ff2",
      "trace_id": "601988c455c54cf3b3a856db86c8b8ee",
      "status": "ok",
      "data": {
        
      },
      "hash": "07e990d2f6650a59"
    },
    {
      "timestamp": 1679418452.241278,
      "start_timestamp": 1679418445.494,
      "exclusive_time": 6747.277975,
      "description": "ProfilingActivity full display",
      "op": "ui.load.full_display",
      "span_id": "407e7d1a95844abe",
      "parent_span_id": "729a97b83ccb4ff2",
      "trace_id": "601988c455c54cf3b3a856db86c8b8ee",
      "data": {
        
      },
      "hash": "3c7af27957a1b75a"
    }
  ],
  "start_timestamp": 1679418448.178,
  "timestamp": 1679418452.241972,
```
