### ISSUE TITLE
Report AppStart time till First Frame Drawn and not onResume

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2627]
### Description

onResume isn't correct according to https://developer.android.com/topic/performance/vitals/launch-time#cold

<img width="888" alt="image" src="https://user-images.githubusercontent.com/4999776/228181720-f0468a39-bc5a-4c72-aeca-5cfb340c78a9.png">

Potentially we should also change when we start measuring app start time (first class load) https://github.com/square/papa/blob/26f21379a8efb14b292c1db5188d4a3be6a48872/papa/src/main/java/papa/internal/Perfs.kt#L300-L359

Relates to #2177 and https://github.com/getsentry/sentry-cocoa/issues/2840.

**Comment by markushi** [comment]
Apps start time is tackled with #2177
