### ISSUE TITLE
Capture event for HTTP errors for Apollo

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2639]
### Description

Apollo HTTP errors should be captured as Sentry events, similar to [OkHttp](https://github.com/getsentry/sentry-java/blob/4337591b314fe88e057378084baa2e860864c09a/sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt#L151) 

More info https://github.com/getsentry/team-mobile/issues/38

**Comment by kahest** [comment]
Blocked (and might be superseded) by https://github.com/getsentry/sentry/discussions/38913 and subsequent GraphQL integration initiative

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/android/configuration/integrations/apollo3/ already possible using Apollo3
Apollo2 isn't implemented but since Apollo4 is already cooking, I'd not add support to older versions.
Apollo3 is GA since Dec 16, 2021
