### ISSUE TITLE
SecurityException  when call sentry.init in some Android 11

### ISSUE THREAD

**Issue by wangzs** [getsentry/sentry-java#2646]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.2.2

### Proguard

Enabled

### Version

6.17.0

### Steps to Reproduce

call `SentryAndroid.init`

### Expected Result

No exception

### Actual Result

![image](https://user-images.githubusercontent.com/2378478/230818268-cfb5bf35-722d-4724-887e-74e5a3ac4a04.png)

some online user occur this exception (I did not reproduce this exception)

**Comment by G00fY2** [comment]
There is a Android OS bug in Android 11 (API 30)  which causes the [ConnectivityManager.getNetworkCapabilities](https://developer.android.com/reference/android/net/ConnectivityManager#getNetworkCapabilities(android.net.Network)) to crash with a SecurityException.

You can check out this issue in the Google issue tracker: [ConnectivityManager registering callback throws security exception](https://issuetracker.google.com/issues/175055271)
There is also a SO discussion: [Getting Security exception while trying to fetch networkcapabilities on android 11](https://stackoverflow.com/questions/66652819/getting-security-exception-while-trying-to-fetch-networkcapabilities-on-android)

**Comment by markushi** [comment]
Hey everyone, thanks for opening this issue and providing feedback! Good news: We'll ship a fix with the next release, I'll keep you posted once it's out.

**Comment by markushi** [comment]
The fix shipped with the `6.18.0` version of our SDK.
