### ISSUE TITLE
Boolean argument globalHubMode is ignored in Sentry.init() when DSN is empty

### ISSUE THREAD

**Issue by volkert-fastned** [getsentry/sentry-java#2651]
### Integration

sentry

### Java Version

17

### Version

Tested with the following Sentry versions, with the same result:

- 6.16.0
- 6.17.0

### Steps to Reproduce

Consider the unit tests in the class below. It's written in Kotlin, but this issue affects Java as well.

(**NOTE**: Be careful not to confuse "capturing" by _Sentry_ with "capturing" by _MockK_. I'm using MockK to "capture the capturing", so to speak.)

```kotlin
package nl.fastned.sentry.bugreport

import io.mockk.every
import io.mockk.mockk
import io.mockk.slot
import io.sentry.ISentryClient
import io.sentry.Sentry
import io.sentry.protocol.SentryId
import java.util.UUID
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class SentryBugTest {

    private val sentryClientMock: ISentryClient = mockk()
    private val sentryMessageSlot = slot<String>()

    @BeforeTest
    fun setUp() {

        every {
            sentryClientMock.captureMessage(capture(sentryMessageSlot), any())
        } returns SentryId(UUID.randomUUID())

        every {
            sentryClientMock.captureMessage(capture(sentryMessageSlot), any(), any())
        } returns SentryId(UUID.randomUUID())

    }

    @AfterTest
    fun tearDown() {
        sentryMessageSlot.clear()
    }

    private fun testSentryMessageCapturing(dsn: String, globalHubMode: Boolean) {
        Sentry.init({ options -> options.dsn = dsn }, globalHubMode)
        Sentry.bindClient(sentryClientMock)

        val expectedSentryMessage = "This is the message that should be sent to Sentry"

        Sentry.captureMessage(expectedSentryMessage)

        assertTrue(sentryMessageSlot.isCaptured)
        assertEquals(expected = expectedSentryMessage, actual = sentryMessageSlot.captured)
    }

    @Test
    fun reproduce() {
        testSentryMessageCapturing(dsn = "", globalHubMode = true)
    }

    @Test
    fun workAround() {
        testSentryMessageCapturing(dsn = "https://bogus-user-info@12345.x.y.z/12345", globalHubMode = true)
    }

}
``` 

### Expected Result

Both tests (`reproduce()` and `workAround()`) should pass, since the documentation of function `Sentry.init(optionsConfiguration, globalHubMode)` does not make any mention of the `globalHubMode` being ignored when the DSN is empty.

### Actual Result

`reproduce()` fails. Only `workAround()` passes.

The likely cause is the following code in `Sentry.java`:

```java
    if (!initConfigurations(options)) {
      return;
    }

    options.getLogger().log(SentryLevel.INFO, "GlobalHubMode: '%s'", String.valueOf(globalHubMode));
    Sentry.globalHubMode = globalHubMode;
```

The if-check will evaluate to `false` when the DSN string is empty, causing the method to return before the line `Sentry.globalHubMode = globalHubMode;` is reached. This does not seem to be deliberate, and seems like a bug, since this is not apparent behavior.

I'd like to add some more comments to this finding:

- I have done a lot of searching on-line, but I could not find any proper documentation on how to properly mock Sentry in Java and Kotlin, specifically the static capture methods: `captureEvent`, `captureException` and `captureEvent`. There appears to be some documentation on testing and mocking on the Sentry website, but only for other languages. Perhaps I completely missed it, but I really spent a lot of time Googling for this.
- I was hoping that with the migration from the Sentry 1.7 legacy API, Sentry would also have gotten more test-friendly. The fact that you are using interfaces such as `ISentryClient`, already makes it more mock-friendly. But apparently, I have to take multiple undocumented and non-obvious steps in order for this to work:
  - I have to enable `globalHubMode` when I'm testing Kotlin code that includes coroutines, due to different threads having different hubs, unless Global Hub Mode is explicitly enabled.
  - I have to call `Sentry.init()` with the `globalHubMode` argument set to `true`, before I invoke `Sentry.bindClient()` to inject the client mock. It won't work if I happen to set this up in the wrong order. You can try this in the test code I shared above: just move the `Sentry.bindClient()` line above the `Sentry.init()` line: that will cause both tests to fail.
  - Due to this (apparent) bug, I have to set a bogus DSN that has the proper URL pattern, even though it's generally recommended to pass an empty string as the DSN in local development environments.

It would be nice if there was some (Java/Kotlin-specific) documentation about this on your website. And it would be even nicer if there were a more practical (and obvious) way to test Sentry invocations in unit tests.

Please let me know if you need any further clarification or additional information.

Thank you for your consideration.

**Comment by volkert-fastned** [comment]
After extending the test, it would appear that the injection/binding of the `ISentryClient` mock also works properly when a non-empty DSN is specified, even when `globalHubMode` is explicitly set to `false`:

```kotlin
    @Test
    fun reproduce1() {
        testSentryMessageCapturing(dsn = "", globalHubMode = false)
    }

    @Test
    fun workaround1() {
        testSentryMessageCapturing(dsn = "https://bogus-user-info@12345.x.y.z/12345", globalHubMode = false)
    }

    @Test
    fun reproduce3() {
        testSentryMessageCapturing(dsn = "", globalHubMode = true)
    }

    @Test
    fun workAround2() {
        testSentryMessageCapturing(dsn = "https://bogus-user-info@12345.x.y.z/12345", globalHubMode = true)
    }
```

So these would appear to be in fact two different (albeit related) bugs. Either that, or non-obvious behavior that should really be documented. Feel free to use this unit test code in your documentation or examples, if that helps.

**Comment by volkert-fastned** [comment]
Another update: I just confirmed that `globalHubMode` must indeed be set to `true` when testing code that uses Kotlin coroutines that make use of multiple threads. (It might not be necessary when all your coroutines run in a single-threaded context, but I haven't tested that, and I don't think that's a common scenario.)

**Comment by romtsn** [comment]
@volkert-fastned apologies for the frustration caused. Before making any suggestion, I'd like to better understand why are you trying to test the Sentry API via mocks? We have a pretty solid test coverage, e.g. what you're trying to test in your example is already extensively tested [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/test/java/io/sentry/HubTest.kt).

For what it's worth, all of our own tests use a fake DSN and never an empty string - this is a deliberate decision, as an empty DSN is not valid and is supposed to disable the SDK.

**Comment by volkert-fastned** [comment]
@romtsn I'm not trying to test the Sentry API. I'm trying to _mock_ Sentry in unit tests, to verify that our code is interacting with Sentry in the right way, in the right scenarios.

And the reason why we want to mock Sentry in our tests is because we don't want our unit tests to actually trigger Sentry alerts. (Otherwise, these would be integration tests. Those would have an external dependency on the Sentry on-line service, they would unnecessarily trigger actual alerts, and would pollute collected data. Plenty of reasons why want to mock Sentry instead.)

It may just seem like I'm directly testing Sentry in the test code I'm sharing here, but this code is just to clearly reproduce the issue that we encountered while testing code that invokes Sentry. I just left our own code-under-test out of this example.

Specifically, I want to mock `Sentry.captureEvent()`, `Sentry.captureException()` and `Sentry.captureMessage()`, but since these are static methods, there is no simple way to do so. That's why I'm trying to inject a mock instance of  `ISentryClient` and verify interactions with that mock.

I know there are also ways to mock static methods directly, for instance by using MockK's `mockkStatic()` function or something like PowerMock, but I have bad experiences with mocking static methods, because such mocks tends to interfere with other (unrelated) tests if such mocks are not set up or cleaned up properly. Injecting a mock client in the Sentry configuration seems like a more proper approach. But maybe others disagree?

**Comment by romtsn** [comment]
> Specifically, I want to mock Sentry.captureEvent(), Sentry.captureException() and Sentry.captureMessage(), but since these are static methods, there is no simple way to do so. That's why I'm trying to inject a mock instance of ISentryClient and verify interactions with that mock.

But for that you're better off creating a wrapper interface for your crash reporting tool and then it's easy to mock that out. It's also easier to switch to a different vendor, so you would have to change it only in one place and not all over your code base (though, I shouldn't be saying that here, really 😅).

I guess the lack of documentation here can be explained by a low demand from our users, and what we have currently (`bindClient` + a fake dsn) serves our own purpose pretty well. But I'll discuss this internally to see if it makes sense to have a dedicate section in docs for testing.

Alternatively to what I suggested, you could also use [beforeSend](https://docs.sentry.io/platforms/android/configuration/options/#before-send) to record events that are about to be sent and then drop them, something like:
```
Sentry.init { 
  it.beforeSend { event, hint ->
    recordedEvents.add(event)
	null
  }
}
```

**Comment by volkert-fastned** [comment]
First of all, thanks for the `beforeSend` suggestion. That might indeed also work. And this might not need the enabling of Global Hub Mode as a workaround for testing multithreaded code.

However, I'm quite surprised by the low demand from your other users. Are we really the only customer that wants to assert in unit tests that our code triggers Sentry events when its supposed to?

Indeed, either the `bindClient` + fake DSN approach or the `beforeSend` solution would work. We got the former approach to work in our tests, at least. 👍 But even then, more documentation on this would still be useful. Just a small section on how to mock and verify Sentry interactions from Java and Kotlin would help. (Also useful in case this needs to be changed as part of any future API changes, as was the case with the migration from the Sentry 1.7 API.)

Thanks again.

**Comment by romtsn** [comment]
Filed https://github.com/getsentry/sentry-docs/issues/6676 to track this rather for all of our mobile platforms. I'm gonna close this issue then since you've figured your way out and you can track it on the docs repo. Thank you for a thorough investigation and good points!
