### ISSUE TITLE
attach screenshots only when crash happens

### ISSUE THREAD

**Issue by kasogg** [getsentry/sentry-java#2665]
### Problem Statement

Is there a way to attach screenshots only in crash issues? Custom exception do not need to attach screenshots.

### Solution Brainstorm
Add an option in SentryAndroidOptions.

_No response_

**Comment by hu441444238xin** [comment]
My question is similar




Can the screenshot function be reported based on custom scenarios?Not necessarily

**Comment by romtsn** [comment]
For the moment, you can drop screenshots for non-crashed events via `beforeSend`:
```kotlin
SentryAndroid.init(context) { options ->
    options.beforeSend = SentryOptions.BeforeSendCallback { event, hint ->
        if (!event.isCrashed) {
            hint.screenshot = null
        }
        event       
    }
}
```

We're discussing internally whether we want to introduce a new option for capturing screenshots for handled events, but no decision yet.

@hu441444238xin what custom scenarios do you have in mind? Would like to better understand them before suggesting anything.

**Comment by markushi** [comment]
Hi @kasogg @hu441444238xin I have good news for you: We've added support for customizing the capture behavior with the upcoming `6.24.0` release of our SDK. [The docs also illustrate](https://github.com/getsentry/sentry-docs/pull/7239/files) on how your use-case can be supported.

**Comment by hu441444238xin** [comment]
Happy



发自我的iPhone


------------------ Original ------------------
From: Markus Hintersteiner ***@***.***&gt;
Date: Thu,Jun 22,2023 3:39 PM
To: getsentry/sentry-java ***@***.***&gt;
Cc: feiwang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [getsentry/sentry-java] attach screenshots only when crashhappens (Issue #2665)





 
Hi @kasogg @hu441444238xin I have good news for you: We've added support for customizing the capture behavior with the upcoming 6.24.0 release of our SDK. The docs also illustrate on how your use-case can be supported.
