### ISSUE TITLE
Make `androidx.core:core` dependency `compileOnly`

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2671]
### Description

The dependency could be `compileOnly` because we are checking for presence of its classes before using them, so nothing should break and we won't pull in additional dependency when our artifact is downloaded.

**Comment by marandaneto** [comment]
That means some features would not work by default for people not using `androidx.core` at all, and we'd need to tell/document that this dependency is actually required, this is common for Flutter/RN.

**Comment by romtsn** [comment]
> That means some features would not work by default for people not using `androidx.core` at all, and we'd need to tell/document that this dependency is actually required, this is common for Flutter/RN.

Good point! I haven't thought about hybrid SDKs case. Maybe we shouldn't do that at all and keep it as `implementation` still

**Comment by markushi** [comment]
Let's close it for now as most apps have a dependency on it anyway.
