### ISSUE TITLE
Sentry screenshotting seems to cause crashes with Compose

### ISSUE THREAD

**Issue by smartfuse** [getsentry/sentry-java#2674]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.0

### Proguard

Disabled

### Version

6.12.1

### Steps to Reproduce

1. Enable Sentry Android screenshots in an app with Compose views
2. When a non-fatal occurs on a screen with Compose views, a Compose crash has a high likelihood of happening.
3. Crashes are usually Segfaults or Compose inconsistency crashes. It seems that Sentry is attempting to take a screenshot of a Compose view while it's detached from the view hierarchy which Compose doesn't seem to support.
4. When we turned off screenshots, non-fatals were still properly reported but the crashes stopped occurring.

<img width="1092" alt="Screen Shot 2023-04-17 at 3 08 14 PM" src="https://user-images.githubusercontent.com/5400589/234077621-e8f27dd2-a1d1-4036-ab81-fcaac70cb43a.png">

### Expected Result

App crash rate should not increase when screenshots are turned on.

### Actual Result

App crash rate is high since every non-fatal triggers a potential crash.

**Comment by markushi** [comment]
@smartfuse Thanks for reporting! Could you provide us with the following details:
* Do you use [any of our Jetpack Compose features](https://docs.sentry.io/platforms/android/configuration/integrations/jetpack-compose/)?
* Could you provide some details about your non-fatal errors? Any chance those are happening on a background thread?

**Comment by helloword1** [comment]
I have the same problem。

**Comment by markushi** [comment]
@smartfuse any chance you could take a look at my questions above?

We're having some discussions around this topic (see similar issue: https://github.com/getsentry/sentry-java/issues/2665) and would love to have some more context around this.

**Comment by smartfuse** [comment]
@markushi Sorry for the late response. It looks like notifications aren't quite working for my personal Github account so I didn't see your follow-up.

Some more details:
* We are not using any Sentry Compose features
* Crashes look something like this (usually Compose complaining about an invalid state change or attempting to measure a disposed Composable, we also had Segfaults for libart and libhwui). These crashes would happen on the main thread.

<img width="300px" alt="Screen Shot 2023-05-08 at 7 41 41 PM" src="https://user-images.githubusercontent.com/5400589/236980422-f6f70901-f744-4327-b58f-7a9ec4ea808e.png">
<img width="300px" alt="Screen Shot 2023-05-08 at 7 41 59 PM" src="https://user-images.githubusercontent.com/5400589/236980425-fd4118ae-ff44-4c93-a503-e50c2a3a1c7c.png">
<img width="300px" alt="Screen Shot 2023-05-08 at 7 42 11 PM" src="https://user-images.githubusercontent.com/5400589/236980428-0cf141a3-8944-45d1-aab4-6bd23e28ca33.png">

**Comment by markushi** [comment]
@smartfuse we recently published 6.19.1, which fixes this issue. It would be great if you could give it a try! Feel free to re-open this issue in case you're still facing problems with screenshots.
