### ISSUE TITLE
Unexpected char 0xe1 at 7 in SENTRY-APOLLO-3-VARIABLES value: {name=á}

### ISSUE THREAD

**Issue by Syer10** [getsentry/sentry-java#2680]
### Integration

sentry-apollo-3

### Java Version

17

### Version

6.17.0

### Steps to Reproduce

1. Write a GraphQL query that takes variables
2. Input non-ASCII character in the variable, such as `á`
3. Query fails

### Expected Result

The query goes through and works, like it does without the Sentry interceptor.

### Actual Result

Exception in thread “AWT-EventQueue-0” com.apollographql.apollo3.exception.ApolloNetworkException: Unexpected char 0xe1 at 7 in SENTRY-APOLLO-3-VARIABLES value: {name=á}.

Based on my research, non-ASCII characters are not usually allowed in headers, while it may work for some clients, it may not for others. Users have suggested using Base64 to work around this issue, which may be what Sentry needs to do.

**Comment by romtsn** [comment]
@Syer10 Thanks for reporting and the suggested workaround, we'll look into this!

**Comment by adinauer** [comment]
Encoding and decoding values seems like a good approach. @lbloder will take a look.

**Comment by lbloder** [comment]
Hi @Syer10,
I'm currently looking into this. However, it seems like I'm unable to reproduce the issue within our Test-Suite.
Could you provide a minimum sample that causes this issue? Alternatively, could you provide a bit more detail on the system/tech-stack/client this issue arises on?

We want to make sure that this is reproducible in our Test-Suite so we can make sure it keeps working as expected after the fix.

Thank you
