### ISSUE TITLE
Null value in `extra` map causes event to get silently dropped

### ISSUE THREAD

**Issue by harlandduman** [getsentry/sentry-java#2681]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.2

### Proguard

Enabled

### Version

6.9.2

### Steps to Reproduce

I'm using React Native, but manually initializing Sentry on Android (not sure if the manual initialization is relevant or not)

Capture exception in Javascript, passing in an `extra` map with a `null` value in it, e.g.
```
Sentry.withScope((scope) => {
  scope.setExtras({someKey: null});
  Sentry.captureException(error)
}
```

### Expected Result

The event should be processed successfully and sent to Sentry.

### Actual Result

There's an error on the Android side when deserializing the event, and it gets silently dropped. I also would expect that an error during processing would get sent to Sentry since it seems like that's what happens in the Javascript library, but maybe I'm wrong about that.

![Screen Shot 2023-04-28 at 9 22 17 AM](https://user-images.githubusercontent.com/21026974/235201578-6670383f-578d-4f76-b5ab-6e4ace78cdbf.png)

It looks like this line https://github.com/getsentry/sentry-java/blob/308cdb2687e591e30440c00d2b0c27d4570e80c2/sentry/src/main/java/io/sentry/SentryBaseEvent.java#L447 is the issue, since `ConcurrentHashMap`s don't support null values

**Comment by romtsn** [comment]
@harlandduman thanks for the report, we'll look into this soon!
