### ISSUE TITLE
sentry-java  upgrade ?

### ISSUE THREAD

**Issue by 2012110325** [getsentry/sentry-java#2703]
### Description

The current client version used  is:

    <dependency>
        <groupId>io.sentry</groupId>
        <artifactId>sentry-spring</artifactId>
        <version>1.7.5</version>
    </dependency>
The server version is: 9.1.2

Is it possible to upgrade the client version from 1.7.5 to 3.2.0 without any loss, while keeping the server version unchanged. 
    Please help confirm if there is any risk involved.

or      Sentry_sdk –> server version compatibility list?

**Comment by markushi** [comment]
Hi @2012110325, thanks for reaching out!
As mentioned in [our README.md](https://github.com/getsentry/sentry-java#sentry-self-hosted-compatibility) SDK version >=3.0.0 requires server version >= v20.6.0
