### ISSUE TITLE
Refrain from overwriting the span status for unfinished spans

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-java#2730]
### Problem Statement

As discussed in https://github.com/getsentry/sentry-java/issues/1690 unfinished spans should be sent, but their status should not be set to `deadline_exceeded`.

### Solution Brainstorm

Don't overwrite the span status.

**Comment by markushi** [comment]
Let's keep self-hosted in mind here, and add corresponding information to the release.

**Comment by stefanosiano** [comment]
the corresponding [pr](https://github.com/getsentry/relay/pull/1690) in relay was in Dec 2022
