### ISSUE TITLE
Unexpected char 0x0a at 8 in SENTRY-APOLLO-3-OPERATION-TYPE value: cXVlcnk=

### ISSUE THREAD

**Issue by SebPawp** [getsentry/sentry-java#2737]
### Integration

sentry

### Java Version

11

### Version

6.20.0

### Steps to Reproduce

Execute a GraphQL query using an OkHttp 4.10 client.

### Expected Result

The GraphQL query should execute and not throw an exception.

### Actual Result

Throw exception `Unexpected char 0x0a at 8 in SENTRY-APOLLO-3-OPERATION-TYPE value: cXVlcnk=`

The header generated by Sentry is not accepted by OkHttp.
This is the line throwing the exception: https://github.com/square/okhttp/blob/parent-4.10.0/okhttp/src/main/kotlin/okhttp3/Headers.kt#L450

Downgrading to `6.19.1` seems to fix the issue.

**Comment by SebPawp** [comment]
This PR seems to be the issue : https://github.com/getsentry/sentry-java/pull/2707

Instead of `Base64.Default` maybe use `Base64.NO_WRAP`?

**Comment by adinauer** [comment]
@SebPawp thanks for reporting and suggesting a fix. I've opened #2745 to switch to `Base64.NO_WRAP`.
