### ISSUE TITLE
Anr rate card shows nothing

### ISSUE THREAD

**Issue by kasogg** [getsentry/sentry-java#2750]
### Description

<img width="395" alt="1" src="https://github.com/getsentry/sentry-java/assets/2409229/71d2a9f7-1f83-4f8e-83fb-fa103c6b67fc">
The card only shows a dash line, not the rate number.
Sentry-java version: 6.17.0
Sentry version: 23.3.1

**Comment by romtsn** [comment]
@kasogg but does your associated app release have any ANR events?

**Comment by romtsn** [comment]
@kasogg can you try to switch the period selector from 14d to 90d for example, does this change anything? 

![image](https://github.com/getsentry/sentry-java/assets/4999776/63378f67-cabe-4f80-b18d-b1157cb61464)

**Comment by kasogg** [comment]
> @kasogg can you try to switch the period selector from 14d to 90d for example, does this change anything?
> 
> ![image](https://user-images.githubusercontent.com/4999776/242218748-63378f67-cabe-4f80-b18d-b1157cb61464.png)
<img width="823" alt="1" src="https://github.com/getsentry/sentry-java/assets/2409229/3a130a87-d28b-4a39-a8eb-f78a3373e0be">
It makes no change.

**Comment by romtsn** [comment]
@kasogg do you perhaps use/set a custom config/version for Relay or Snuba? Or do you use the latest ones https://develop.sentry.dev/self-hosted/releases/#nightly-builds

**Comment by kasogg** [comment]
> Hi @kasogg - when did you [activate ANR rate on your instance](https://github.com/getsentry/sentry/issues/48919#issuecomment-1547807125)? Can you verify that you have ANR events after that date?
I activated it last Friday and have anr events after that day.

**Comment by kasogg** [comment]
> @kasogg do you perhaps use/set a custom config/version for Relay or Snuba? Or do you use the latest ones https://develop.sentry.dev/self-hosted/releases/#nightly-builds

@romtsn I don't use these Relay or Snuba or nightly builds.
current sentry version: 23.3.1 0787c74

**Comment by romtsn** [comment]
@kasogg alright, thank you for all the details, we'll investigate what is up there.

**Comment by kahest** [comment]
Hi @kasogg, thank you for your patience. ANR rate card and graph are currently not available on self hosted. While they can be activated via feature flag, the required processing in the backend is not available yet.
