### ISSUE TITLE
Closing sentry when my library close

### ISSUE THREAD

**Issue by javokhirsavriev** [getsentry/sentry-java#2776]
### Problem Statement

I use sentry sdk in my android library. Users use my library in their android parent app. If there is some kind of error in the parent app, the sentry in my library work. But I don't want it. How can I catch errors only inside the library?

I am using this code in library when I finish the libray. But it doesn't work. Errors in parent app are visible in sentry.

```kotlin
internal fun closeSentry() {
    tryCatch {
        Sentry.clearBreadcrumbs()
        Sentry.endSession()
        Sentry.close()
    }
}
```

**Comment by romtsn** [comment]
Sorry we don't officially support using the Sentry SDK in a library for that exact reason (the host app will be also reporting to the same Sentry project). The correct way to implement this would be to manage your own instance of [Hub](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Hub.java) with your own custom dsn to not clash with the host app. But that would mean you'll have to add and manage all the integrations/event processors/etc (basically everything that enriches our crash events and make them useful) on your own.

I'm going to close this, but eventually we're gonna document this properly, so you can follow it here https://github.com/getsentry/sentry-docs/issues/3611
