### ISSUE TITLE
Refactor try catch blocks

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#2780]
### Description

There are places in the SDK where a `finally` block in a try/catch block performs operations, like sending a breadcrumb, that could potentially lead to another `Exception`
There are also places where we call potentially crashing framework functions without wrapping them.
Sentry should degrade gracefully, without crashing the whole app

**Comment by markushi** [comment]
As of now there're no known major crashes caused by this, let's keep this in mind when touching existing code.
