### ISSUE TITLE
Envelope submission failed/ connect timed out

### ISSUE THREAD

**Issue by QianyunLin** [getsentry/sentry-java#2807]
### Self-Hosted Version

23.7.0.dev0

### CPU Architecture

x64

### Docker Version

20.10.23

### Docker Compose Version

none

### Steps to Reproduce

When using vue, you can report errors to sentry, 
but when using languages such as java or go, you cannot receive error messages. The following is the error message I recorded using springboot's sentry-spring-boot-starter: 6.19.1.

### Expected Result

Envelope submission success

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/87403147/864e5474-19cf-4bd7-8b43-b72fb80edc38)

**Comment by adinauer** [comment]
I'm assuming your frontends are trying to reach the self hosted instance from somewhere else than your backend (Spring). Could it be some SSL issue on your server running the Spring application?

Maybe you get some more specific pointers by using `curl -vvv YOURDSN` on your server?

**Comment by QianyunLin** [comment]
We checked the server's firewall and confirmed that the problem was caused by the whitelist.
