### ISSUE TITLE
Java Sdk in not working in android release build as expected, wrong stack trace. 

### ISSUE THREAD

**Issue by MukeshBlippar** [getsentry/sentry-java#2813]
### Integration

sentry

### Java Version

11

### Version

6.23.0

### Steps to Reproduce

Hi,

I'm using Java Sdk for android library project, because due to android aar generation limitation i can't use android gradle based Sdk (sentry) in my library project. 

This is how i have initiated the sentry sdk.

```
  Sentry.init(options -> {
            options.setDsn("mydsn");
            options.setTracesSampleRate(1.0);
            options.setProguardUuid(uuid);
            options.setEnableTracing(true);
            options.setDebug(true);
        });
```
When i use the debug build i get the proper stack trace
```

com.XXXlibrary.level.package. initializeSdk at line 114 //inner module level
System
com.XXX.app.level.package.MainActivity in onCreate at line 53 //first entry of the app
System
android.app.Activity in performCreate at line 8241
System
android.app.Activity in performCreate at line 8207
System
android.app.Instrumentation in callActivityOnCreate at line 1329
System
```
Here actual crash happened at library level code and stack trace is correct ( initializeSdk at line 114)
But same code when i tested with release build got the below stack trace. 

```
com.XXX.app.level.package.MainActivity in onCreate at line 673 //first entry of the app
System
android.app.Activity in performCreate at line 8241
System
android.app.Activity in performCreate at line 8207
System
android.app.Instrumentation in callActivityOnCreate at line 1329
```
You can see that stack trace is not entering into my inner level library code, where actual crash happened. Even line number is wrong (should be -onCreate at line 53).

Note: I have also uploaded the mapping.txt file in sentry manually with same UUID. I got the same result. Even if i disabled the proguard for release build still same result. 

1. Can i use the sentry Java sdk for android project. If yes then can i use this for library project?
2. Is there any settings i should enable for release stack trace because with disabled proguard also it doesn't catch the right stacktrace and line number. 

Please help. 

### Expected Result

```

com.XXXlibrary.level.package. initializeSdk at line 114 //inner module level
System
com.XXX.app.level.package.MainActivity in onCreate at line 53 //first entry of the app
System
android.app.Activity in performCreate at line 8241
System
android.app.Activity in performCreate at line 8207
System
android.app.Instrumentation in callActivityOnCreate at line 1329
System
```

### Actual Result

```
com.XXX.app.level.package.MainActivity in onCreate at line 673 //first entry of the app
System
android.app.Activity in performCreate at line 8241
System
android.app.Activity in performCreate at line 8207
System
android.app.Instrumentation in callActivityOnCreate at line 1329
```

**Comment by romtsn** [comment]
@MukeshBlippar first off, we don't officially support using Sentry SDKs in libraries due to the reasons listed here https://docs.sentry.io/platforms/. 

If you've set the correct proguard uuid to SentryOptions then deobfuscation should still work, we don't alter the stacktrace depending on the release/debug variant, so this is most likely a problem with your mapping or proguard uuid mismatch.

Again, even if you've figured it out and fixed it, there's no guarantee the consumers of your library will not override this proguard uuid with theirs if they use Sentry and you'll face the same problem again (another reason we don't support running our SDK in 3rd-party libs)

**Comment by MukeshBlippar** [comment]
@romtsn Thanks for your advise and giving more insights on it.

**Comment by romtsn** [comment]
@MukeshBlippar I'm gonna close this issue, feel free to re-open/open a new one if there are problems with the SDK usage in apps. thanks
