### ISSUE TITLE
What is the reason of event rejected due to rate limit (API returned 429)?

### ISSUE THREAD

**Issue by filipatbnp** [getsentry/sentry-java#2817]
### Problem Statement

Sometimes I see in Android app logs this

> 2023-07-03 17:24:15.769 D/Sentry: Request failed, API returned 429
2023-07-03 17:24:15.770 D/Sentry: {"detail":"event rejected due to rate limit"}

what limit have I just hit? That log seems a little bit cryptic.

**Comment by romtsn** [comment]
You can read up on it here https://develop.sentry.dev/sdk/rate-limiting/, but basically if you're using
* sentry saas - you're sending too many events for your billing plan, you'd have to either purchase more events or reach out to our customer support for increasing the limits. You also can configure it [here](https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#6-rate-limiting) 
* sentry self-hosted - you'd have to change the rate limit somewhere in the sentry/relay config (better to ask on #self-hosted discord about that)

**Comment by filipatbnp** [comment]
That limit I just exceeded is something that **me** as a client of sentry SDK should take care (handle that HTTP 429 and retry_after etc.), or this is something that sentry SDK I'm using will take care of?

**Comment by romtsn** [comment]
> That limit I just exceeded is something that
> 
> * **me** as a client of sentry SDK should take care (handle that HTTP 429 and retry_after etc.),
> * or this is something that sentry SDK I'm using will take care of?

Ah, no, the SDK will take care of that of course, I've just described how you can increase the limits. Probably we should change the log level to WARNING to not show this in the logs if the `debug` flag is not enabled
