### ISSUE TITLE
Improve Backpressure Management

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-java#2829]
## Description
Please see the project issue for further details: https://github.com/getsentry/team-sdks/issues/10

**Comment by adinauer** [comment]
We're looking for customers to give this a try in a backend application environment. If you'd like to do so, please let us know.

It allows you to set a `tracesSampleRate` of `1.0` and reduce the rate in case the system is under load to reduce the overhead we cause.
