### ISSUE TITLE
Not possible to pass empty string into DSN under logback

### ISSUE THREAD

**Issue by cowwoc** [getsentry/sentry-java#2833]
### Integration

sentry-logback

### Java Version

20

### Version

6.25.0

### Steps to Reproduce

Sentry.java shows an exception `throw new IllegalArgumentException("DSN is required. Use empty string to disable SDK.");`

However, it is impossible to pass an empty string as the DSN in logback.xml because Logback interprets an empty string value as the property not existing altogether.

The only thing that seems to work is to pass an undefined property as the value because `SentryAppender` checks if the DSN ends with "IS_UNDEFINED".

### Expected Result

Either document a way to pass an empty string into dsn in logback.xml, or update the documentation and exception message to indicate what we *are* supposed to do under Logback.

### Actual Result

N/A

**Comment by adinauer** [comment]
Thanks for the feedback @cowwoc. We'll take a look.

**Comment by adinauer** [comment]
Talked to the team, our plan is to add a separate boolean flag to disable Sentry (`enabled=false`). JavaScript SDK already does it this way: https://github.com/getsentry/sentry-javascript/blob/86a42197d4500b2932acc5eccfd278d35de54290/packages/types/src/options.ts#L22

**Comment by cowwoc** [comment]
Thanks for the quick turnaround

**Comment by adinauer** [comment]
@cowwoc starting with `6.28.0` of the Java SDK you should now be able to use the following config in logback to disable the SDK:

```
  <appender name="sentry" class="io.sentry.logback.SentryAppender">
    <options>
      <enabled>false</enabled>
    </options>
  </appender>
```
