### ISSUE TITLE
AndroidStudio Integration or Plugin

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-java#2834]
### Problem Statement

User at Androidcon Berlin was telling me Sentry is really great and does everything he needs but an integration with AndroidStudio would be nice. I asked him how his Android Studio integrations worked with other vendor Mobile SDK's and he said something like:

> In AndroidStudio, see the Sentry errors, and it will point me to the code right in my IDE Android Studio

Not sure if he means Production errors, or Development environment errors.
Also not sure if this requires any integration with Github/Bitbucket/Gitlab.

### Solution Brainstorm

> In AndroidStudio, see the Sentry errors, and it will point me to the code right in my IDE Android Studio

Here is Instabug's plugin idk if it works the same or this is the one he was referencing:
https://www.instabug.com/blog/introducing-instabugs-android-studio-plugin

**Comment by romtsn** [comment]
Existing community integration https://github.com/nhat-phan/sentry-integration

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
