### ISSUE TITLE
Crons support for Java

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2875]
### Problem Statement

We have a crons product so we could start sending check ins from the Java SDK.

### Solution Brainstorm

- Spring @Scheduled
- quartz library
- investigate if there's more libs

**Comment by buckett** [comment]
We have some jobs that are effectively docker containers running in AWS ECS on a schedule. Providing an easy way to send cron data back from these jobs would also be useful.

**Comment by adinauer** [comment]
Hello @buckett I presume you're using Java in those containers? If so, which libraries are you using? Quartz? Spring?

**Comment by buckett** [comment]
@adinauer Yeah Java, they are Spring Boot, but the triggering of the containers is AWS, so it would be nice to have the ability to start a cron monitor when the Spring application context is initialised and then complete it when it is destroyed.

Or the hook could be against the JVM instead of binding against spring.

**Comment by adinauer** [comment]
I guess that means you're not using `@Scheduled` or Quartz but instead the container starts on a schedule and executes some Spring application. I presume that's not a Web (WebMVC / WebFlux) application but a Spring CLI?

We'll consider the manually reporting CRONS use case when implementing.

**Comment by adinauer** [comment]
@buckett we're releasing CRONS support for Java. `6.30.0` should be available soon.

Your container use case should be covered by either annotating your method with `@SentryCheckIn("monitor_slug")` or if that doesn't work using `Sentry.captureCheckIn()` manually.

We've also added support for Quartz but decided not to automatically create monitors for all jobs for now. If you're using Spring, all you need is to add the new `sentry-quartz` dependency and then on either your `JobDetail` or `Trigger` add a `sentry-slug` (also available as constant called `SENTRY_SLUG_KEY`) entry with your monitor slug to the job data map.

Docs will be published soonish. We've added something to our [Spring Boot 3](https://github.com/getsentry/sentry-java/tree/main/sentry-samples/sentry-samples-spring-boot-jakarta) and [Spring Boot 2](https://github.com/getsentry/sentry-java/tree/main/sentry-samples/sentry-samples-spring-boot) samples.

We'd love your feedback!
