### ISSUE TITLE
Attachment Support for Crashes.

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry-java#2881]
### Problem Statement

[Android docs: ](https://docs.sentry.io/platforms/android/enriching-events/attachments/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2Fplatforms%2Fandroid%2Fenriching-events%2Fattachments%2F)
> Please note that attachments don't work yet with crashes.

**Comment by romtsn** [comment]
It's already supported via `EventProcessor` or `beforeSend` or attaching them to the `Scope` as pointed in the doc you linked. I'm gonna remove that note from the docs and close this issue.
