### ISSUE TITLE
Privacy compliance issues

### ISSUE THREAD

**Issue by gaoluhan** [getsentry/sentry-java#2882]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

io.sentry.android.gradle  version: 3.5.0
sentryVersion: 6.18.1

### Expected Result

SDK needs to obtain the application installation list after initialization

### Actual Result

The SDK accessed the application installation list before initialization, causing privacy compliance issues and leading to rejection from the app marketplace. How to handle the SDK's privacy compliance problem?

### Product Area

Unknown

**Comment by markushi** [comment]
Hi @gaoluhan, thanks for reaching out!
Could you explain a bit more in detail what is meant by the following
> obtain the application installation list after initialization

The SDK does not obtain the SDK installation list, however we
* query information about the app itself
* check if certain apps are installed for determining if the device is rooted or not (see [RootChecker](https://github.com/getsentry/sentry-java/blob/7cdf1216cba07a8bc4adb24ca9356bb8231ee724/sentry-android-core/src/main/java/io/sentry/android/core/internal/util/RootChecker.java))

**Comment by markushi** [comment]
@gaoluhan did you have any chance to look into this?

**Comment by romtsn** [comment]
@gaoluhan we're gonna close this issue in a week. Have you had a chance to look into this? You could also try disabling [auto-init](https://docs.sentry.io/platforms/android/configuration/manual-init/#manual-initialization) of the SDK, so it's not initialized until you explicitly call it.

**Comment by gaoluhan** [comment]
The setup you mentioned works, and thank you very much for your assistance.
