### ISSUE TITLE
GraalVM properties file in Android artifact

### ISSUE THREAD

**Issue by G00fY2** [getsentry/sentry-java#2887]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.0.2

### Proguard

Enabled

### Version

6.28.0

### Steps to Reproduce

Build Android project which uses Sentry.

### Expected Result

META-INF in build artifact (APK) should only contain required files.

### Actual Result

Sentry adds [META-INF/native-image/io.sentry/sentry/native-image.properties](https://github.com/getsentry/sentry-java/blob/549cbb4657b9dea1048c4882e79504e87d6acc4f/sentry/src/main/resources/META-INF/native-image/io.sentry/sentry/native-image.properties) file.

Not really a "bug" but since we like to keep our artifact clean would be nice if this file could be excluded from being packaged when used with Android.

Update: Looks like this can't be easily done. At least AGP seems to not support exclude rules from libraries. Even Google itself run into this limitation: https://github.com/google/android-fhir/issues/534#issuecomment-1006752578

So maybe something we can just exclude on client side or maybe a FR for the Sentry Android Gradle Plugin.

**Comment by romtsn** [comment]
hi @G00fY2 indeed this should not be bundled within apk, we'll fix that 👍

**Comment by romtsn** [comment]
FYI I've looked into this and I think there's not much we can do from the android sdk side, as we can't control what's packaged into the final apk, but we can still do 2 things as suggested:
* Do this automatically from the Gradle plugin when applied to an android app
* Provide a troubleshooting page to show how users can exclude this from their side via `android.packagingOptions.excludes` for those who don't use the gradle plugin

**Comment by G00fY2** [comment]
Thanks for looking into. In the end it's a minor optimization. Maybe a short notice in the docs is sufficient. E.g. coroutines (similar case) does it like this: https://github.com/Kotlin/kotlinx.coroutines?tab=readme-ov-file#avoiding-including-the-debug-infrastructure-in-the-resulting-apk

Not sure if it is worth adding additional logic into the Gradle plugin.
