### ISSUE TITLE
UserFeedback envelope not cached

### ISSUE THREAD

**Issue by MarcinGawel-TomTom** [getsentry/sentry-java#2902]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.2

### Proguard

Disabled

### Version

6.28.0

### Steps to Reproduce

With internet connection disabled:
```
val sentryId = Sentry.captureMessage("message")

val userFeedBack = UserFeedback(sentryId).apply {
    comments = "comment"
    this.name = "reporter name"
    this.email = "email@gmail.com"
}

Sentry.captureUserFeedback(userFeedBack)
```

### Expected Result

captureMessage envelope and captureUserFeedback should be stored locally in cache if internet connection is not available.

### Actual Result

Envelope from captureMessage (containing some attachments) is stored in the cache. Envelope from captureUserFeedback (with comment, name and email) is **not** added to the cache. Looks like EnvelopeCache.getEnvelopeFile() is using the same file for both envelopes.

**Comment by markushi** [comment]
@MarcinGawel-TomTom thanks for reporting, we'll look into this!
