### ISSUE TITLE
✨ Where is Profiling on the Spring Boot / Java feature roadmap?

### ISSUE THREAD

**Issue by bjornharvold** [getsentry/sentry-java#2907]
### Problem Statement

As a fan of OpenZipkin, I am also a Sentry fanboy. Wondering when the Profiling feature will hit Spring Boot. According to your docs, it's currently only available for Android [which should make it an easy port to the rest of the Java ecosystem].

Also, Sentry Performance for webflux / reactive Spring Boot apps is highly desired.

A Feature Roadmap for each language ecosystem would be nice.

Regards,
Bjorn

**Comment by adinauer** [comment]
Hello @bjornharvold, we've added Sentry Performance for WebFlux in `6.16.0` and improved it since - just in case you missed that.

**Comment by bjornharvold** [comment]
Hi @adinauer 

Yes, I can see Sentry uses OpenTelemetry for capturing performance in a webflux environment. The instructions are a bit blurry though. Could you possibly add an example of this here: https://github.com/getsentry/sentry-java/tree/main/sentry-samples.

Is it as simple as adding: 
```
        <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-opentelemetry-agent</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
        </dependency>
```

to my Maven project and adding 

sentry.dsn & sentry.traces-sample-rate to my application.properties file?

Thank you,
Bjorn

**Comment by adinauer** [comment]
@bjornharvold while it's still possible to use Sentry and OpenTelemetry for Spring WebFlux, you no longer need OpenTelemetry as of `6.16.0` of the Sentry Java SDK. You can find examples for using WebFlux for [Spring Boot 2](https://github.com/getsentry/sentry-java/tree/main/sentry-samples/sentry-samples-spring-boot-webflux) and [Spring Boot 3](https://github.com/getsentry/sentry-java/tree/main/sentry-samples/sentry-samples-spring-boot-webflux-jakarta) in the samples you linked - those have performance enabled (`sentry.enable-tracing=true` in `application.properties`).

**Comment by adinauer** [comment]
Oh and if you'd still like to go ahead with OpenTelemetry, we have some [docs](https://docs.sentry.io/platforms/java/guides/spring-boot/performance/instrumentation/opentelemetry/) available.

**Comment by bjornharvold** [comment]
Thank you. That was NOT clear in the documentation here: https://docs.sentry.io/platforms/java/guides/spring-boot/webflux/. No, I do not want to use OpenTelemetry if not necessary. So enabling Sentry Performance in webflux is now the same as a regular Spring Boot non-reactive configuration?

Cheers 🍺

**Comment by adinauer** [comment]
> So enabling Sentry Performance in webflux is now the same as a regular Spring Boot non-reactive configuration?

Yes. [Docs](https://docs.sentry.io/platforms/java/guides/spring-boot/performance/) apply to both WebMVC and WebFlux now.

I've opened a [PR](https://github.com/getsentry/sentry-docs/pull/7731) to remove the OTEL sentence from the docs to avoid confusion.

**Comment by Kah0ona** [comment]
So we are running Clojure web app and loving Sentry. Since Clojure runs on the JVM, is there any future roadmap towards supporting profiling for 'other JVM languages'? 

Or can it never be so generic, as in, do you always need information about what framework is used etc?
