### ISSUE TITLE
OkHttp not closing on responses not closed

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#2908]
### Description

We automatically instrument rest calls done through OkHttp, using its `EventListener`.
The `EventListener`'s `callEnd` method is called only after the `Response` is consumed. That is, after any of `Response.close()`, `Response.body.text()` or `Response.body.bytes()` is called.
So, when the user performs a request and doesn't read/close the response, we don't automatically finish the `connection` span, neither the `http.client` span. This means that we end up with never ending transactions, in case of idle transactions.
This applies to both GET and POST requests.

v7 will have a final timeout that would mitigate this issue, but we should find a way to automatically stop those spans, even if the user doesn't close the response.

**Comment by markushi** [comment]
According to the docs [Response](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response/) is closable, so in theory it should auto-close itself.

**Comment by markushi** [comment]
Let's try to remove the `Response` from the hint and see if the body closes automatically or not.
