### ISSUE TITLE
Missing transaction even if performance is enabled

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-java#2909]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

?

### Proguard

Enabled

### Version

6.28.0

### Steps to Reproduce

Use our SDK with all enabled settings and performance enabled.
Find more details in our [internal slack thread](https://sentry.slack.com/archives/CA2V2LBDL/p1693482326574559). 

### Expected Result

Transaction including spans should show up.

### Actual Result

Transaction is missing, only trace header is available.

**Comment by markushi** [comment]
Likely related to https://github.com/getsentry/sentry-java/issues/2908

**Comment by romtsn** [comment]
Also related to #2316
