### ISSUE TITLE
Ready-made instrumentation decorator for thread pools

### ISSUE THREAD

**Issue by sentryadam0000345** [getsentry/sentry-java#2918]
### Problem Statement

There is no ready-made instrumentation decorator for thread pools (it exists for spring sleuth)

### Solution Brainstorm

Right now custom instrumentation is the solution to deal with this.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1927) by [Unito](https://www.unito.io)

**Comment by adinauer** [comment]
@sentryadam0000345 @Kobby-Bawuah do you have any more info to share here?

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
