### ISSUE TITLE
Add option send-modules to SentryOptions

### ISSUE THREAD

**Issue by evmetatron** [getsentry/sentry-java#2925]
### Problem Statement

I saw this option is in [ruby options](https://docs.sentry.io/platforms/ruby/configuration/options/).

<img width="544" alt="image" src="https://github.com/getsentry/sentry-java/assets/30232281/ba330cc2-d952-4343-a553-e3a567229b91">

However, this option is not present in java options.

This can be useful when you don't need to send a list of modules with versions.

### Solution Brainstorm

I can create a pull request with a solution, if you don't mind.

**My plan:**

1. Add option sendModules in [SentryOptions](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryOptions.java)
2. Modify condition in [the code](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Sentry.java#L363) for using this option. When the condition sendModules==false is met NoOpModulesLoader will be used.

**Comment by sergey-volkov-lm** [comment]
More on motivation: we use sentry-spring-boot-starter and tune sentry in application.yml. These is no property there to disable sending packages.
Our version is 6.28.0.

**Comment by adinauer** [comment]
Hello @evmetatron and @sergey-volkov-lm thanks for the feedback. A PR would be very welcome :-).

As a workaround for Spring you should be able to set an `IModulesLoader` instance that simply returns `null` using `setModulesLoader`. You can copy the code from `NoOpModulesLoader` just don't use `NoOpModulesLoader` directly as that'll be overriden by the code you linked above. For Android however that wouldn't work (just in case someone else also needs this).

**Comment by evmetatron** [comment]
I created [the pull request](https://github.com/getsentry/sentry-java/pull/2926)

**Comment by adinauer** [comment]
Closing this as it has already been implemented. Thanks again for the PR!
