### ISSUE TITLE
Report "device.class" in transactions

### ISSUE THREAD

**Issue by kylannjohnson** [getsentry/sentry-java#2929]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.1.0

### Proguard

Enabled

### Version

6.29.0

### Steps to Reproduce

Errors emitted from the Sentry SDK have `device.class` set as a tag.  Transactions do not, but the docs say that "events" should have device.class on them.  Am I missing something?  I used the latest master on the Sentry Sample app to replicate this.

### Expected Result

device.class to be attached to all errors and transactions.

### Actual Result

I made a discover query with columns of Project, Device.Class, Event.Type, Count.  For Event.Type=transaction, Device.Class is blank/empty, but for the error event I issued, it's "medium".  iOS attaches this tag for both transactions and errors.

**Comment by romtsn** [comment]
hi @kylannjohnson, indeed we were not sending memory information for transactions - this was the missing piece to have our device classification work on the backend side. Should be fixed by #2936. Thanks for reporting!
