### ISSUE TITLE
Add ServerWebExchange as hint in SentryWebExceptionHandler

### ISSUE THREAD

**Issue by usrivastava92** [getsentry/sentry-java#2974]
### Problem Statement

Problem:
In SpringBoot Webflux, exceptions are intercepted by the `SentryWebExceptionHandler`. Here, a SentryEvent is generated prior to invoking `hub.captureEvent(event, hint);`. Both `ServerHttpRequest` and `ServerHttpResponse` are embedded in the Hint object. Given that the same Hint and Sentry Event objects are forwarded to `SentryOptions.BeforeSendCallback`, information derived solely from the request or response can be utilized to establish logic within BeforeSendCallback. 

This creates a limitation where if a user intends to utilize exchange attributes within BeforeSendCallback to formulate logic, they are restricted from doing so.

Screenshots:
<img width="1152" alt="Screenshot 2023-10-09 at 9 02 33 PM" src="https://github.com/getsentry/sentry-java/assets/22717147/783778e1-0f2d-4bbd-a414-1eb4d5e0f99a">

### Solution Brainstorm

An easy fix for this problem involves setting `ServerWebExchange` as a property in `internalStorage` map of the Hint object

**Comment by adinauer** [comment]
Hello @usrivastava92 thanks for the feedback. I presume simply adding `ServerWebExchange` to `Hint`, e.g. as `WEBFLUX_EXCEPTION_HANDLER_EXCHANGE` would solve the problem, correct?

**Comment by usrivastava92** [comment]
that is correct, if we accept this as an enhancement I will be happy to raise a PR for this 🙂
