### ISSUE TITLE
Jetpack Compose user interaction integration is broken

### ISSUE THREAD

**Issue by audkar** [getsentry/sentry-java#2978]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.1

### Proguard

Disabled

### Version

6.30.0

### Steps to Reproduce

1. Setup project according to https://docs.sentry.io/platforms/android/configuration/integrations/jetpack-compose/#user-interactions
2. Add any `clickable`/`scrollable` Composable
```kotlin
@Composable
fun MainScreen() {
        Button(
            modifier = Modifier.testTag("btn"),
            onClick = { },
        ) { Text(text = "The button") }
}
```
3. Interact with the Composable
4. Observe Logcat output. e.g. `Unable to find click target. No breadcrumb captured.`

This can be reproduced on the `sentry-samples-android` module in this repo on the `main` branch. "Open Compose Activity"

I think it's related to https://github.com/getsentry/sentry-java/blob/a0e3c8b1903e6d38912f2a592c812b61b10a95d4/sentry-compose-helper/src/jvmMain/java/io/sentry/compose/gestures/ComposeGestureTargetLocator.java#L73 changed type of Semantic nodes

### Expected Result

Click properly registered for Compose component

### Actual Result

Target UI component is not detected. Logcat output: `Unable to find click target. No breadcrumb captured.`

**Comment by audkar** [comment]
Are there any tests that cover the real behavior of Compose user interaction tracking? I wanted to quickly check if I could fix this problem, but could not find any tests I could use for this investigation.

**Comment by markushi** [comment]
Thanks for reporting!
Yes, we do have some basic automated UI tests for this: https://github.com/getsentry/sentry-java/blob/main/sentry-android-integration-tests/sentry-uitest-android/src/androidTest/java/io/sentry/uitest/android/UserInteractionTests.kt

Could you share which version of Jetpack Compose you're using? Especially the compose compiler plugin and the `compose-ui` pakcage.

**Comment by audkar** [comment]
compiler - `androidx.compose.compiler:compiler:1.5.3`
ui  from BOM - `androidx.compose:compose-bom:2023.09.02` `1.5.2`

**Comment by audkar** [comment]
Do you have any insight into what the problem might be? Are we using the Sentry Compose integration incorrectly, is it a bug, does Sentry not support stable Android Compose, or something else?

**Comment by audkar** [comment]
Did you have a change to :eyes: this? We are kind of seriously blocked by this.

**Comment by markushi** [comment]
Hey @audkar, sorry for the delay - I'll have a look at it now!

**Comment by markushi** [comment]
Indeed it's broken right now, newer releases of Jetpack Compose no longer store `Clickable` information as semantics, but rather attach this information as [ClickableElement].(https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/Clickable.kt;l=417;bpv=1)
<img width="841" alt="image" src="https://github.com/getsentry/sentry-java/assets/1411808/a8d071ce-d039-4d84-a759-c092841db882">
