### ISSUE TITLE
Spring Boot auto configuration does not consider config in `sentry.properties`

### ISSUE THREAD

**Issue by yufeikang** [getsentry/sentry-java#2996]
### Integration

sentry-spring-boot-starter

### Java Version

17

### Version

6.30.0

### Steps to Reproduce

**Environment:**
- Spring Boot version: 2.7.16
- sentry-spring-boot-starter version: 6.30.0

**Description:**
I am integrating Sentry with my Spring Boot application using the `sentry-spring-boot-starter`. However, I've observed a discrepancy in the information contained in the Sentry events based on the configuration file used.

When I use `sentry.properties` for configuring Sentry, the reported events to Sentry lack crucial information such as the URL, browser, and client details. Here's a snippet of my `sentry.properties` configuration:

1. Configure Sentry using sentry.properties.
2. Trigger an exception in the application.
3. Check the reported event in Sentry, the URL, browser, and client information are missing.
4. Switch the configuration to application.yaml.
5. Trigger the same exception in the application.
6. Check the reported event in Sentry, now the URL, browser, and client information are present.

### Expected Result

The information about URL, browser, and client should be reported in Sentry events regardless of whether sentry.properties or application.yaml is used for configuration.

### Actual Result

The URL, browser, and client information are missing when sentry.properties is used for configuration, but are present when application.yaml is used.

**Comment by adinauer** [comment]
Hello @yufeikang how are you initializing Sentry in each of the cases? With `application.yml`/`application.properties` our Spring integration automatically initializes Sentry and auto configures some filters.

**Comment by yufeikang** [comment]
Hello again,

Thank you for bringing the initialization aspect into light. Initially, I was configuring Sentry through the command line parameter `-Dsentry.properties=/sentry.properties` and manually calling the Sentry initialization method in the code. Here's how I was doing it:

```bash
java -Dsentry.properties=/sentry.properties -jar my-app.jar



However, after switching to sentry-spring-boot-starter, I removed the manual initialization from the code. I noticed that Sentry was working as expected except that the events lacked browser information when using sentry.properties. When I switched the configuration to application.yml, the events reported to Sentry contained all the necessary information including the URL, browser, and client details.

# In application.yml
sentry:
  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
  # ... other Sentry configurations

It seems like the auto-configuration provided by sentry-spring-boot-starter is only fully activated when using application.yml or application.properties, and not with sentry.properties. This auto-configuration appears to set up certain filters and listeners that capture additional context information which wasn’t captured when using sentry.properties.

So, my primary question revolves around understanding the differences in initialization and configuration when using sentry.properties versus application.yml/application.properties, and if there’s a way to ensure all relevant context is captured with sentry.properties without switching to application.yml.

Thank you for your assistance.

**Comment by adinauer** [comment]
I'd recommend using `applicaton.yml`/`application.properties` for Spring (Boot). Config from `sentry.properties` isn't loaded into Spring Boot configuration, only into Sentry causing the difference in auto instrumentation you noticed because we use some conditional configuration mechanisms in `SentryAutoConfiguration`.

I'll rename this issue, so we can more quickly see what this is about. I'm moving this to the backlog but can't say when we'll get to implementing this.

Can you please give us some details about why you prefer to use `sentry.properties`?

**Comment by yufeikang** [comment]
Thank you for your prompt response and clarification. It makes sense why `application.yml/application.properties` is preferred for Spring Boot integration, and I appreciate the transparency regarding the issue. I'll switch to using `application.yml` for configuring Sentry in my Spring Boot application to ensure all relevant context information is captured in the reported events. Looking forward to the potential enhancement regarding `sentry.properties`. Thanks again.
