### ISSUE TITLE
In-app includes don't work when minification is enabled

### ISSUE THREAD

**Issue by angusholder** [getsentry/sentry-java#3012]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.1.0

### Proguard

Enabled

### Version

6.25.0

### Steps to Reproduce

Enable in-app includes

```kotlin
SentryAndroid.init(this) { opts ->
    opts.dsn = "DSN HERE"
    opts.addInAppInclude("co.mopo")
}
```

and enable minification

```gradle
android {
    // ...

    buildTypes {
        release {
            debuggable = false
            minifyEnabled = true
            shrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
}
```

### Expected Result

Stack traces should highlight the stack lines from code within the `com.example` package, and collapse other stack lines.

### Actual Result

All stack lines are displayed equally.

![image](https://github.com/getsentry/sentry-java/assets/7407345/578ed081-b743-4561-9b57-820e3c097938)

I had a look at where `SentryOptions.getInAppIncludes()` gets used, and it appears that in-app includes are processed client-side:

https://github.com/getsentry/sentry-java/blob/93a76ca3ed5e22b37a521784f4b601668bfa7e07/sentry/src/main/java/io/sentry/SentryStackTraceFactory.java#L46-L48

For this to work it seems like there needs to be a way to have the backend process them instead, because unlike the client, it has access to the source maps. Currently the client must be seeing all those `co.mopo` packages as `a.b` or something, so it thinks there are no in-app packages present in the trace.

**Comment by romtsn** [comment]
hi @angusholder, yes it's a known problem, for now you could circumvent this via defining [server-side stacktrace rules](https://docs.sentry.io/platforms/android/enhance-errors/proguard/#in-app-frames) (they apply _after_  deobfuscation has happened), you can see them a "server-side inAppIncludes". 

We'd still like to improve this behavior by at least setting in-app to the app package name by default after deobufscation, but if you have your own in-app includes, the docs I linked would be the way to go.

**Comment by angusholder** [comment]
Ah I hadn't seen that! Looks perfect, thank you

**Comment by romtsn** [comment]
Cool, if that's working for you I'm gonna close the issue. We are tracking the other improvement I mentioned separately. Thanks!
