### ISSUE TITLE
How to exclude some url from being reported to sentry in spring boot3

### ISSUE THREAD

**Issue by dengdaoping** [getsentry/sentry-java#3037]
### Description

I would like to know how to exclude some url from being reported to sentry in spring boot3. How can I configure via yml is the best

**Comment by adinauer** [comment]
Hello @dengdaoping we have `beforeSend` (for errors) and `beforeSendTransaction` (for transactions) callbacks you can use to filter out events you don't want to send to Sentry. Here's some [docs](https://docs.sentry.io/platforms/java/guides/spring-boot/configuration/filtering/) that should help. There's currently no option you can set on `application.yml`.

**Comment by dengdaoping** [comment]
In sentry, is it possible to count the entire execution chain and execution time from http.server to the response to the client after each request to the server, and if so, how do I use it in spring?

I try to use @SentrySpan when added to the controller class, but I can't get the processing time before to after the controller, this is because of the spring mvc execution flow problem, how can I count the whole execution flow and execution time, as follows
![image](https://github.com/getsentry/sentry-java/assets/114464886/7b47d8dd-71ba-45ff-906d-26d8f2008330)

**Comment by adinauer** [comment]
Hey @dengdaoping I'm not sure I understand what you'd like to do. Would you like to add instrumentation for the parts you marked? Those are most likely Spring internals. We're looking into providing more detail there: https://github.com/getsentry/sentry-java/issues/2772

**Comment by dengdaoping** [comment]
Hi @adinauer , yes. For example, when a request arrives at the server, if we can set a parameter, the timeout method will automatically be caught without us having to manually add @SentrySpan. thanks you.

I have another question for you. How can I change the trace id of sentry to a customized trace id?

**Comment by adinauer** [comment]
Can you please describe in more detail what you're trying to do. Is it a trace ID from an incoming HTTP header?

**Comment by dengdaoping** [comment]
Hey, @adinauer, yes.For example In the request header I pass in an x-trace-id, which I want to replace with the `x-trace-id` that sentry generates itself

**Comment by adinauer** [comment]
Hey @dengdaoping we currently do not support picking up a trace ID from incoming headers except `sentry-trace`. You'd have to disable our auto instrumentation and manually start a transaction basically replicating `SentryTracingFilter` which uses `Sentry.continueTrace` and passes the `TransactionContext` returned by it to `startTransaction`.

Anther way to solve this would be to send in a `sentry-trace` header if you have control over headers on the client calling into your backend.

**Comment by dengdaoping** [comment]
Okay, thanks for the answer.
