### ISSUE TITLE
Sentry Spring Boot Integration Can Produce Lots of "not eligible for getting processed by all BeanPostProcessors" Noise In Startup Logs

### ISSUE THREAD

**Issue by adase11** [getsentry/sentry-java#3042]
### Integration

sentry-spring-boot-starter-jakarta

### Java Version

21

### Version

6.33.1

### Steps to Reproduce

I created a demo repository [here](https://github.com/adase11/spring-boot-starter-sentry-demo) the details should be in the README.md.  Essentially the combination of `sentry-spring-boot-starter-jakarta` and some basic spring-boot starters (`spring-boot-starter-data-jpa` and `spring-boot-starter-web` in my case) cause lots of noise about the sentry beans not being eligible for all bean post processors in the startup logs.

I've observed this with Java 17 and Spring Boot 3.1.x as well as Java 21 and Spring Boot 3.2.x.

The noise in the logs makes it very easy to miss some change that a developer is making that is actually introducing an issue.

### Expected Result

No bean post processor noise in the logs.

### Actual Result

Lots of bean post processor noise in the logs related to sentry beans.

**Comment by adase11** [comment]
Just to note, I'm aware this can be turned off with `logging.level.org.springframework.context.support.PostProcessorRegistrationDelegate=ERROR` in the properties. However I'm looking for a solution that does not require me to disable that (potentially valuable) logging.

**Comment by adinauer** [comment]
Thanks for the report, we'll look into it. Can't give an ETA yet.

**Comment by rtsio** [comment]
+1

**Comment by rtsio** [comment]
Besides noise, it seems to affect most if not all Sentry beans and some Spring beans, and it also seems to result in Sentry completely ignoring random SentryOptions like logging event levels and etc.:

```
2023-11-18 02:45:06 01:45:06.749 [main] INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker {} - Bean 'sentryCheckInPointcut' of type [org.springframework.aop.support.ComposablePointcut] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-11-18 02:45:06 01:45:06.755 [main] INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker {} - Bean 'io.sentry.spring.boot.jakarta.SentryAutoConfiguration$HubConfiguration' of type [io.sentry.spring.boot.jakarta.SentryAutoConfiguration$HubConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-11-18 02:45:06 01:45:06.924 [main] INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker {} - Bean 'sentry-io.sentry.spring.boot.jakarta.SentryProperties' of type [io.sentry.spring.boot.jakarta.SentryProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```
Using @SpringBootApplication(exclude = {SentryAutoConfiguration.class}) obviously fixes things but also turns off Sentry completely.

**Comment by rtsio** [comment]
Downgrading to 6.26.0 for now solves this issue.

**Comment by werner77** [comment]
I also noticed this, but a more serious side effect is the startup time of my Spring Boot application .

Notice only the first few statements in my log:

SENTRY DISABLED:

```
2023-11-21 16:32:46.119  INFO 5019 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 211 ms. Found 48 JPA repository interfaces.
2023-11-21 16:32:46.136  INFO 5019 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-11-21 16:32:46.234  INFO 5019 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 97 ms. Found 28 JPA repository interfaces.
```

SENTRY ENABLED

```
2023-11-21 16:26:26.888  INFO 4894 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 172 ms. Found 48 JPA repository interfaces.
2023-11-21 16:26:27.082  INFO 4894 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-11-21 16:26:30.939  INFO 4894 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 3856 ms. Found 28 JPA repository interfaces.
```

Notice it takes 4000 with Sentry enabled vs 300 ms with Sentry disabled. The rest of the startup is equally slow as well.

**Comment by adase11** [comment]
That's a very interesting observation @rtsio, I double checked with my sample project and confirmed that when you downgrade to 6.26.0 the warnings do go away.

I knew I had seen this in another project with a lower version of the sentry bom (v6.18.1) and so I was interested to see what could be different. It looks to me that with lower versions the enabling of `SentryPerformanceAspectsConfiguration` autoconfiguration via setting the property `sentry.traces-sample-rate` brings back this issue.

I demonstrated this by adding the `sentry.traces-sample-rate` property to the `application.properties` file with `sentry-bom` version 6.26.0 on a new branch of my demo project [here](https://github.com/adase11/spring-boot-starter-sentry-demo/tree/demo-6-26-0-version) if you want to take a look.

**Comment by kahest** [comment]
@rtsio @adase11 thanks you for the findings and the details, much appreciated!

**Comment by piotrooo** [comment]
For me, downgrading to version `6.29.0` worked. The issue started with version `6.30.0`.

Java 21
Spring Boot 3.2.0

**Comment by bjornharvold** [comment]
Same issue here.

**Comment by supereckspert** [comment]
Both this and #3098 are closed and refer to each other.

**Comment by adinauer** [comment]
@supereckspert this issue is still open for me.

**Comment by woosungkim0123** [comment]
While implementing `Spring Batch` with `Spring Boot version 3.2.0`, I encountered warning logs in trationDelegate$BeanPostProcessorChecker that were the same as the issues mentioned above.

This issue was encountered when the project was tested with only the following dependencies:
```gradle
implementation 'org.springframework.boot:spring-boot-starter-batch'
runtimeOnly 'com.h2database:h2'
```

The problem occurred with the following Gradle configuration:
- Java 17, 21 
- Spring Boot 3.2.0

However, when the version of Spring Boot was downgraded to 3.1.6, these warning logs were not observed, regardless of using Java version 17 or 21.

**Comment by piotrooo** [comment]
This fix is not in the 7.1.0 version as stand in the changelog.

![screenshot-github com-2024 01 02-14_29_36](https://github.com/getsentry/sentry-java/assets/2005054/681c273b-1d4a-4849-a13d-5246d52df77d)

**Comment by romtsn** [comment]
@piotrooo indeed this will be part of the upcoming release, thanks for noticing it! I've opened https://github.com/getsentry/sentry-java/pull/3123 to address

**Comment by adinauer** [comment]
We've just released https://github.com/getsentry/sentry-java/releases/tag/7.2.0 which should get rid of the issue. Any feedback is welcome.

**Comment by adase11** [comment]
@adinauer - I just pushed a branch using using v 7.2 to this repository that I used to demonstrate the issue when I originally reported it. I'm still able to observe the same warnings using version 7.2.

https://github.com/adase11/spring-boot-starter-sentry-demo/tree/demo-7-2-0-version

**Comment by adinauer** [comment]
Thanks for the feedback @adase11 we'll take another look at your demo and see what's different there.

**Comment by adinauer** [comment]
We think we've figured out the problem.

Looks like our AspectJ configs were causing beans to be pulled in before all bean post processors were done (via `AnnotationAwareAspectJAutoProxyCreator`). We have been focusing on our own bean post processors before but the sample provided by @adase11 showed that even without our bean post processor the problem was present. Thank you very much! This pointed us in the right direction.

We're now working on a fix by removing the `IHub` bean dependency from our advices and marking AOP related beans and configurations with `@Role(BeanDefinition.ROLE_INFRASTRUCTURE)`.

**Comment by lbenedetto** [comment]
I'm still getting this issue with 7.3.0
```
Bean 'permissionConfigVoter' of type [application.security.authorization.PermissionConfigVoter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [meterRegistryPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies.
Bean 'globalSecurityConfig' of type [application.security.GlobalSecurityConfig$$SpringCGLIB$$0] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [meterRegistryPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies.
```

**Comment by adinauer** [comment]
@lbenedetto can you confirm these log messages go away, when removing Sentry?

**Comment by lbenedetto** [comment]
It still happens if I remove Sentry, so nevermind.
