### ISSUE TITLE
Fix total frames metrics

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#3063]
### Description

The [callback](https://developer.android.com/reference/android/view/Window#addOnFrameMetricsAvailableListener(android.view.Window.OnFrameMetricsAvailableListener,%20android.os.Handler)) we rely on is called only when the frames change, so we cannot get the real total number of frames.
We already use the [same approach of JankStats](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:metrics/metrics-performance/src/main/java/androidx/metrics/performance/JankStatsApi24Impl.kt;l=150).
We could try to use Choreographer directly, but that's [bad for performance](https://twitter.com/Piwai/status/1643662212614201344).
We have to find a way to calculate total frames.
[Internal doc](https://www.notion.so/sentry/Total-Frames-992c8b3704e94d6baa5f9532c14731be?pvs=4) with some considerations

**Comment by markushi** [comment]
Let's check if we can get notified if the refresh-rate changes. We could fallback to the last known refresh-rate and simply count the number of expected frames.

**Comment by romtsn** [comment]
This is done by the frame delay PR
