### ISSUE TITLE
[Starfish] Use a better way to determine app foreground launch

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-java#3084]
### Description

Instead of checking for process foreground like we did earlier 
https://github.com/getsentry/sentry-java/blob/d43311af4de9697012a932ff860c9f2b2ff3d3e0/sentry-android-core/src/main/java/io/sentry/android/core/performance/AppStartMetrics.java#L136

we could use a similar approach [as firebase](https://github.com/firebase/firebase-android-sdk/blob/28e3a6821910a0ae452fbcc5b173fafe919ddbaf/firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java#L552-L573).

In simplified terms this would looks like the following:
```java
final AtomicBoolean anyActivityCreated = new AtomicBoolean(false);
registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacksAdapter() {
  @Override
  public void onActivityCreated(@NonNull Activity activity, @Nullable Bundle savedInstanceState) {
    super.onActivityCreated(activity, savedInstanceState);
    anyActivityCreated.set(true);
    unregisterActivityLifecycleCallbacks(this);
  }
});
new Handler(Looper.getMainLooper()).post(() -> {
  final boolean isForegroundAppLaunch = anyActivityCreated.get();
  Log.e(TAG, "onCreate: isForegroundAppLaunch: " + isForegroundAppLaunch);
});
```

**Comment by stefanosiano** [comment]
Implemented by https://github.com/getsentry/sentry-java/pull/3550
