### ISSUE TITLE
SentrySchedulerFactoryBeanCustomizer overrides existing quartz listeners

### ISSUE THREAD

**Issue by lexek** [getsentry/sentry-java#3088]
### Integration

sentry-spring-boot-starter-jakarta

### Java Version

17

### Version

6.34.0

### Steps to Reproduce

Implement custom SchedulerFactoryBeanCustomizer bean that registers additional global job listeners via schedulerFactoryBean.setGlobalJobListeners

### Expected Result

Job listeners registered via custom SchedulerFactoryBeanCustomizer are not overridden

### Actual Result

SentrySchedulerFactoryBeanCustomizer is executed after SchedulerFactoryBeanCustomizer overrides previously set custom job listeners via setGlobalJobListeners

**Comment by adinauer** [comment]
Thanks for the report @lexek and sorry for the inconvenience. We'll make sure not to replace existing listeners.

**Comment by adinauer** [comment]
Unfortunately there's no API to retrieve them in `SchedulerFactoryBean` (or rather `SchedulerAccessor`). We'll try to come up with a different way of not replacing.

**Comment by adinauer** [comment]
We're thinking about simply adding `@Order(Ordered.HIGHEST_PRECEDENCE)` to the `@Bean` definition of our `SchedulerFactoryBeanCustomizer`. Do you think that'd solve the issue in your case? Our testing looks promising.

**Comment by lexek** [comment]
Hi,

I think `Ordered.HIGHEST_PRECEDENCE` for sentry customizer bean should work.

Opt-out via property might also be a viable option.

**Comment by adinauer** [comment]
Thanks, we'd prefer not to add extra options if we can avoid it.

**Comment by adinauer** [comment]
@lexek we've just released https://github.com/getsentry/sentry-java/releases/tag/7.2.0 in case you decide to give it a try, please do provide feedback.
