### ISSUE TITLE
Sentry worker tasks.store.preprocessors.error

### ISSUE THREAD

**Issue by zKoz210** [getsentry/sentry-java#3091]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.5, build ced0996

### Docker Compose Version

Docker Compose version v2.20.2

### Steps to Reproduce

1. Run Sentry self-hosted (docker compose up -d)
2. Send transactions & errors from iOS, Android, Laravel (PHP)

### Expected Result

We expect that no errors will occur and everything will be processed correctly. We are getting a lot of errors with this.

### Actual Result

```
docker logs -f -n 200 sentry-self-hosted-worker-1
```

```
08:54:36 [ERROR] sentry.errors.events: tasks.store.preprocessors.error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 422, in do_process_event
    result = processor(data)
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/java/processing.py", line 16, in deobfuscate_exception_value
    re.escape(raw_method_name), deobfuscated_method_name, exception["value"]
KeyError: 'value'
```

**Comment by kahest** [comment]
This error is caused by the backend trying to deobfuscate a Java (in this case Android) exception value, but the value is not present in the exception. We need to align whether this is a valid case from the SDK side, and whether it makes sense to guard this code on the backend against missing exception values.

@zKoz210 I'm assuming your Android application is obfuscated, correct? Do you send in Proguard mappings to your Sentry backend for deobfuscation?

**Comment by zKoz210** [comment]
Our application is obfuscated and we are sending Proguard mappings

**Comment by romtsn** [comment]
@zKoz210 could you share the json payload that is being sent from Android? Do you create custom `SentryEvent`s or do you fully rely on the SDK for sending the events?

**Comment by romtsn** [comment]
fwiw, we set [Throwable.getMessage()](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#getMessage--) as the exception value and this is not guaranteed to always be present, so we should probably fix it on the backend side.

**Comment by zKoz210** [comment]
We only use Sentry SDK and do not send custom events

**Comment by markushi** [comment]
We should guard against null values (`exception["value"]`) on the backend side.

**Comment by romtsn** [comment]
hi @zKoz210 I don't know when the next self-hosted version will be released, but fix will be part of the next release cycle (probably in 3-4 weeks). Thanks for opening the issue!
