### ISSUE TITLE
Support for ProGuard outside of Android

### ISSUE THREAD

**Issue by Nohus** [getsentry/sentry-java#3109]
### Problem Statement

Currently ProGuard only seems to be supported specifically on Android.
I am using Sentry in a desktop application (using Compose Multiplatform / Compose Desktop), and I don't see an easy process to upload the mapping file.

**Comment by adinauer** [comment]
Hello @Nohus thanks for the feedback. We have https://github.com/getsentry/sentry-android-gradle-plugin/issues/403 to track ProGuard outside of Android which we want to support via our Gradle plugin at some point.

Closing this as a duplicate now.

**Comment by Nohus** [comment]
@adinauer Thanks for the response. I don't use the Gradle plugin in my project and I was just looking for a way to upload the mapping file on the Sentry web interface. Why force the Gradle plugin for this functionality?
