### ISSUE TITLE
isCrashedLastRun always true after crash

### ISSUE THREAD

**Issue by MikaReesu** [getsentry/sentry-java#3114]
### Gradle Version

8.2.0

### AGP Version

8.2.0

### Code Minifier/Optimizer

None

### Version

7.1.0

### Sentry SDK Version

7.1.0

### Steps to Reproduce

Hello, 
I discovered that in the version 7, I could use the "Sentry.isCrashedLastRun()". It's indeed working, except that here, it stays TRUE all the time after a crash.

### Expected Result

isCrashedLastRun should be TRUE at the first run and the following FALSE.

### Actual Result

isCrashedLastRun is TRUE all the time after a crash and every time that this boolean is used it is true.

**Comment by MikaReesu** [comment]
As I remember it was not working or not present in the version 6.3X(don't remember the exact version). 

The behaviour is different in iOS sentry. (SentrySDK.crashedLastRun)

I'm using it to show a dialog with a feedback area in it. In iOS it is working perfectly. 


1. There was a crash. App got killed.
2. The user opens the app again.
4. The isCrashedLastRun is triggered let's say in the home page and it is true(there was a crash just before)
5. I show my dialog. 
6. The user write a feedback or close the dialog.
7. After that, I navigate in the app.
8. I go back to the Home page, and the isCrashedLastRun is still true. 

Here is the issue, if it's true, the dialog will be displayed again. Which shouldn't be the case, since I showed it already to the user.

At that moment in iOS, the boolean would have been false. Which is also the case with Firebase.crashlytics.didCrashOnPreviousExecution().

I hope my explanation was clear enough. Don't hesitate if you have any questions.

**Comment by romtsn** [comment]
Hmm, that's weird that even without leaving the app the flag turns into `false`, that's definitely not how it should be in sentry-cocoa (cc @philipphofmann or @brustolin to confirm). It should only flip the flag when the app process is restarted or when the app is sent to background for more than 30s (when we finish the previous session).

> Which is also the case with Firebase.crashlytics.didCrashOnPreviousExecution().

Maybe it's the case for crashlytics-ios, but in crashlytics-android they also just read the marker file once on app start and never flip the flag until the next sdk init (see [here](https://github.com/firebase/firebase-android-sdk/blob/a5d0f0d71d806e1e2f739f9fe67cbb7ba49d618d/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java#L490C16-L514))

**Comment by philipphofmann** [comment]
No, the `SentrySDK.crashedLastRun` on iOS should stay `true` for the application's runtime. I just tested this with a simulator, and it does stay true. Maybe you confuse this with `SentryOptions.onCrashedLastRun` on Cocoa, a callback the SDK only executes once: https://docs.sentry.io/platforms/apple/user-feedback/, @MikaReesu.

**Comment by romtsn** [comment]
@MikaReesu We're closing the issue, but feel free to reply here if you think our SDKs should still change their behavior. Thanks!
