### ISSUE TITLE
Network call is missing from Breadcrumbs

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry-java#3129]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.1.1

### Proguard

Enabled

### Version

6.33.1

### Steps to Reproduce

1. Make multiple network calls after an app start (9 in this case)
2. Fail the last call which should generate a HttpClientException

### Expected Result

All network calls are visible in breadcrumbs

### Actual Result

First network call is missing.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2063) by [Unito](https://www.unito.io)

**Comment by kahest** [comment]
possibly related: https://github.com/getsentry/sentry-android-gradle-plugin/issues/617

**Comment by markushi** [comment]
Hey @gid-sentry, do you have an update for us?

**Comment by gid-sentry** [comment]
Hi @markushi and @stefanosiano , I am checking back with the customer and haven't heard as of yet. I will let you know if the issue persists but I think we might be ok to close the issue for now.

**Comment by kahest** [comment]
@gid-sentry thank you for the update, then I'll close this for now!
