### ISSUE TITLE
when the new version of mapping.txt remains unchanged, it will not be uploaded, resulting in a stack parsing failure.

### ISSUE THREAD

**Issue by jiagengArctuition** [getsentry/sentry-java#3132]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.2.0

### Proguard

Enabled

### Version

6.29.0

### Steps to Reproduce

![image](https://github.com/getsentry/sentry-java/assets/103102265/9183cff9-5b45-4f63-9ffd-37b71bd1446e)
![image](https://github.com/getsentry/sentry-java/assets/103102265/da810763-131d-43d9-8025-b18e327dabbf)

Our Android app is developed using Flutter, with minimal Java code. When we create a new version, often only the Dart code changes, while the Java code remains the same. Consequently, the mapping.txt file remains unchanged compared to the previous version. When we build the app in GitHub Actions and use the mathieu-bour/setup-sentry-cli@1.2.0 action to upload mapping.txt, it detects that there is no new mapping.txt, and thus, it doesn't upload it. I believe this behavior is reasonable.

However, when a new version with Java exceptions occurs, Sentry does not use the existing mapping.txt for resolution.

### Expected Result

![image](https://github.com/getsentry/sentry-java/assets/103102265/affd3ba2-1a1d-4d02-9698-60d5f0448013)

### Actual Result

![image](https://github.com/getsentry/sentry-java/assets/103102265/331cea19-3d93-44c5-b940-57a83775558b)

**Comment by romtsn** [comment]
hey @jiagengArctuition, can you check the raw json event payload (you can access it by clicking the button as shown on the screenshot)? 
![image](https://github.com/getsentry/sentry-java/assets/4999776/c84b7f2b-d96a-41fb-8459-b01806f52d0c)


It should contain a `debug_meta` entry similar to this one below:
```
"debug_meta":{"images":[{"uuid":"<your_uuid>","type":"proguard"}
```
This is necessary to deobfuscate your stacktraces. If it's missing, then I'd suggest you to open an issue in the respective github action repo. The uuid always has to be present in the payload, even if the mapping file did not change.

**Comment by jiagengArctuition** [comment]
@romtsn Thank you, I indeed couldn't find 'debug_meta' in the JSON payload. Can Sentry provide an official GitHub Action for this task?

**Comment by stefanosiano** [comment]
hi @jiagengArctuition 
there is no plan to provide a Github Action for this task.
Anyway, you should provide a `proguard_uuid` for every obfuscated event. You can have a look at https://docs.sentry.io/product/cli/dif/#proguard-mapping-upload

**Comment by jiagengArctuition** [comment]
@romtsn Thank you very much! The gradle plugin will upload the mapping.txt every time, even if its md5 has not changed. The problem has been solved.
