### ISSUE TITLE
Auto-Instrumentation without Activities

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-java#3141]
### Problem Statement

**Problem:**
If an app does not use Activities then not much will be auto-instrumented. User's app happens to use Fragments.

**Context:**
User developes software that runs on a Android OS device+app that's a payment terminal. Their customer buys this payment terminal and uses it to collect credit card payments in physical store locations.

Their app is only a single Activity when it's launched (they said this was required) then it's mostly Fragments.

### Solution Brainstorm

Instrumentation of Fragments or some other approach altogether.

**Comment by romtsn** [comment]
This is a duplicate of #1810 and is also gonna be solved by only-spans. Closing.
