### ISSUE TITLE
Don't wait when SDK is reinitialized

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#3162]
### Description

Currently we wait for a `flushTimeout` when we close the `Hub`. 
That's wanted on a backend case, and in some way even on the Android side. 
But when the user initializes the SDK multiple times, we close the previous instance and start a new one, so we may:
1. just skip the timeout entirely in that case and drop any connection
2. find a way to make it stop in the background by starting another hub

This would fix issues with double inits, including [an issue with Flutter](https://github.com/getsentry/sentry-dart/issues/1804#issuecomment-1908779074) that doesn't depend on the user.

**Comment by markushi** [comment]
@romtsn whenever you have time, would be great to get your opinion on this.

**Comment by adinauer** [comment]
Ideally we should still try to flush in the background without waiting.

**Comment by ltq918** [comment]
When the SDK is initialized, is it possible for us to reuse the previous instance without creating a new instance if a previous instance exists?

**Comment by adinauer** [comment]
@ltq918 changing options after `Sentry.init` isn't really something we support and test. So while it may work for some features it mostly likely will lead to problems somewhere down the road.

**Comment by romtsn** [comment]
This sounds good to me, but there might be multiple problems that we would have to solve:
* Perhaps a potential conflict in DirectoryProcessor, where the old hub still processes unsent envelope, and the new one kicks in at the same time 
* Same with the SentryExecutorService which we use quite extensively in multiple parts of the SDK, e.g. when we use it to write to disk, this can be problematic

**Comment by stefanosiano** [comment]
We could close the `SentryExecutorService` in the background and start a new one or reuse it as @adinauer suggests.
I was trying to get my head around the `Flushable` awaits, including the `DirectoryProcessor`. What about closing them in the background and waiting a delay before they are restarted?
