### ISSUE TITLE
[Java] Add support for Sentry Metrics

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-java#3190]
### Description
Metrics! Sentry will support Metrics finally! First we need all of our SDKs to support Metrics, including Java and dependent SDKs

#### Requirements:

- [x] Basic API https://github.com/getsentry/sentry-java/pull/3205
- [x] Metrics Summary https://github.com/getsentry/sentry-java/pull/3238
- [x] Tag normalization https://github.com/getsentry/sentry-java/pull/3205
- [x] Before Emit Callback https://github.com/getsentry/sentry-java/pull/3250
- [x] Span creating mode https://github.com/getsentry/sentry-java/pull/3248
- [x] Proper changelog https://github.com/getsentry/sentry-java/pull/3251
- [x] Create docs for Java/Android/Platform https://github.com/getsentry/sentry-docs/pull/9374
- [ ] (Postponed for now) Code location~ https://github.com/getsentry/sentry-java/issues/3241
https://docs.sentry.io/product/metrics/metrics-set-up/

#### Question:
> How much of this can the Android SDK inherit if added in Java?  

All of it.

#### Document(s)
[Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/)
[SDK Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/)
[Product Specs](https://develop.sentry.dev/sdk/metrics/)

**Comment by markushi** [comment]
Having looked into the docs and the .NET implementation I want to highlight a few development aspects:
* The [product specs describe the overall API behavior](https://develop.sentry.dev/sdk/metrics/) best
* We not only need to provide APIs on the SDK side, but also need some basic logic to aggregate metrics into 10s buckets
* We need some async flush functionality to send past buckets to our backend
* There's a new envelope item, type = statsd for sending metrics
* We have to keep thread safety (metrics can be emitted by any thread, reading and cleaning up happens every 10s) in mind
* There's a timing API which connects spans with metrics AND creates gauge metrics aka "summaries" of metrics on a span level
* When capturing metrics, stack traces are used to determine a code location for an emitted metric, if feasible at all, some caching needs to be done

To get going fast let's split this up into smaller PRs / tasks:

- [ ] Implement basic API, add protocol definitions for sending `statsd` envelope items
- [ ] Add support for code locations, linking metrics to source code
- [ ] Add support for the timing API, connecting spans with metrics and creating gauges

**Comment by smeubank** [comment]
> The [product specs describe the overall API behavior](https://develop.sentry.dev/sdk/metrics/) best

do you mean the develop spec? the link is to develop docs, not product

Thanks for investigating in more detail!

**Comment by kahest** [comment]
[released with 7.6.0](https://github.com/getsentry/sentry-java/releases/tag/7.6.0) (excluding [code location](https://github.com/getsentry/sentry-java/issues/3241), which is currently blocked and tracked separately)
