### ISSUE TITLE
Resolve spring expressions in @SentryCheckIn

### ISSUE THREAD

**Issue by Stevelicious** [getsentry/sentry-java#3191]
### Problem Statement

The latest version of spring-sentry 7.3.0 only accepts regular string values.
This makes it hard to use separate monitor-slugs for different deployments.

Some more background.
We have created a separate project in sentry for production environment because we need to limit access to it to a few people.
This results in the need of creating two cron monitors and two globally unique slugs.
We would like to be able to override the slug in the production environment, and what is better than using spring properties.
 Unfortunately this is not supported in the latest spring-sentry version.

### Solution Brainstorm

Evaluate and resolve the spring expression if it is one.

**Comment by adinauer** [comment]
@Stevelicious have you tried simply setting `sentry.environment=dev` or whatever environment name you prefer? This should take care of having a split for CRONS. See this screenshot:

production:
<img width="1262" alt="Screenshot 2024-02-05 at 12 45 09" src="https://github.com/getsentry/sentry-java/assets/2542832/a9ebc4ba-08e0-4091-9e28-14f0b31c0b28">

dev:
<img width="1270" alt="Screenshot 2024-02-05 at 12 45 02" src="https://github.com/getsentry/sentry-java/assets/2542832/71729fd6-9d9d-44b3-8676-d205fe82b4d5">

Or would you like to have multiple production instances of the same cronjob in code, one per deployment and still keep all of them listed as environment "production"?

**Comment by Stevelicious** [comment]
Hi,

What we want to achieve is to have one application, two projects and two cron monitorings. 
Lets call our projects: app-test and app-prod.
The reason we split this up is because only a few selected people get access to app-prod due to sensitive data that cannot be shared with the whole team.

Because we have split it up in two projects, we need to create the same cron monitoring in both projects. 
If I am not mistaken the monitor slugs are globally unique within the sentry instance.
Lets call the monitor slugs: monitor-slug-test and monitor-slug-prod.

When we deploy our spring boot application to test we will use the point to app-test and monitor-slug-test.
For production it will be app-prod and monitor-slug-prod.

The most logic way to achieve this would be to set the values in application.properties or as environment variables. Thats why we would like to use spring expression in the annotation. Eg. @SentryCheckIn("${a.spring.property}")

**Comment by adinauer** [comment]
I'm not entirely sure I understand but it sounds like you simply use a different project (and DSN) for each of your deployments.

> If I am not mistaken the monitor slugs are globally unique within the sentry instance.

As far as I know, monitors are unique to the project and a quick test seems to confirm this.

In theory it should be sufficient to change the DSN according to your deployment (`app-test` vs. `app-prod`), e.g. in `application.properties` or using ENV variables. This should take care of splitting monitors for you. Does this not work for you?

**Comment by Stevelicious** [comment]
If you would create a cron monitor in a project that uses the same slug as any other existing one then you get an error. As shown in the screenshot.
![image](https://github.com/getsentry/sentry-java/assets/13227386/a7e4c764-62a4-4bed-afc5-db81c4dbdb96)

Apart from using a different DSN we would need to use a different monitor slug as well.

**Comment by adinauer** [comment]
Ah my bad, you're right, I didn't look at the slug in full detail. This means you'd need to manually append the env to each of your monitor slugs. We'll add it to our backlog and update here once we have news about implementing this.
