### ISSUE TITLE
Move the onFinishCallback before the span is finished

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#3228]
### Description

https://github.com/getsentry/sentry-java/pull/3219#discussion_r1500496194

**Comment by markushi** [comment]
Let's also keep our `SpanFrameMetricsCollector` as it's `onSpanFinished` callback requires the finish date to be already set.

**Comment by markushi** [comment]
Given that we have a mixed behavior for txn/spans, let's consider this broken and fix it.
