### ISSUE TITLE
[Metrics] `IllegalMonitorStateException` in `Sentry.metrics().notifyAll();`

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-java#3242]
### Description

Originally posted by @sysmat in https://github.com/getsentry/sentry-java/pull/3205#issuecomment-1974705748

- when using `Sentry.metrics().notifyAll();` I get error

```
IllegalMonitorStateException: current thread is not owner
    at java.lang.Object.notifyAll(Object.java)
    at sentry.SentryMain.main(SentryMain.java:33)
```
- java 21, sentry 7.5.0

**Comment by markushi** [comment]
@sysmat is there any reason why your calling `notifyAll()`?

This stems from the `java.lang.Object` class in [Object.notifyAll](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#notifyAll--), which naturally every Java class inherits from. 
E.g. even `"Example".notifyAll();` would cause a crash unless you use the object for some custom thread synchronization logic.

**Comment by romtsn** [comment]
@sysmat we're gonna close the issue, let us know if there's still a problem for you.
