### ISSUE TITLE
Sentry is grouping two messages even though the messages are different

### ISSUE THREAD

**Issue by ColtonIdle** [getsentry/sentry-java#3246]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.0

### Proguard

Enabled

### Version

6.30.0

### Steps to Reproduce

Call

`Sentry.captureMessage("Performed with 100`

then in a subsequent build update it to

`Sentry.captureMessage("Performed with 200`

sentry dashboard will have these under the same issue.

### Expected Result

 What I really want is for these to be separate messages so that every time

"Performed with 100" is called, it's under one issue entry in the dashboard, and the same with 200. Is there a way to fix this grouping.

### Actual Result

![CleanShot 2024-03-05 at 11 29 39@2x](https://github.com/getsentry/sentry-java/assets/31751141/21f7a932-62ca-40e3-81d5-0f65581cc775)

Because of this, the header and the message doesn't line up so when we were searching for a specific instance of something (basically anything "not Performed with 100") it was impossible to find because they were hiding in the Performed with 100 issue, even though they were performed with 200.

**Comment by romtsn** [comment]
the reason they were grouped together is that they have the same stacktrace and code location, and our grouping works based on the stacktrace of multiple events. If you want to have separate issues for these two events, you have the following options:
* Provide a custom fingerprint as described [here](https://docs.sentry.io/platforms/android/usage/sdk-fingerprinting/ ) and set the fingerprint based off of your title (something like `listOf("{{ default }}", "performed-with-$number")`)
* Disable the [attachStacktrace](https://docs.sentry.io/platforms/android/configuration/options/#attach-stacktrace) flag, so your messages do not have stacktraces attached and therefore do not get grouped together based on their stacktrace

Let me know if this helps!

**Comment by ColtonIdle** [comment]
Thanks, that's helpful, but I wish I could set a fingerprint when logging the message instead of having to do it on init. The reason this is annoying is (at least on android) I don't actually call sentry.init

Same thing with attachStackTrace. Since it looks like it has to be done on the sentry level, it's more of a hassle to setup for a 1 time log. Maybe there's a way to disable android auto-init

**Comment by ColtonIdle** [comment]
I think I got this working on with fingerprinting. had to disable auto init.
I'd like to turn this into a feature request to allow fingerprinting at time of logging, or attachStackTrace at time of logging too. 😄

**Comment by ColtonIdle** [comment]
Ah, how'd I miss that! That is **MUCH** better! And just checking... can I disable the stacktrace at that same point or no?

**Comment by romtsn** [comment]
No, unfortunately it's only possible to either disable this globally (via SentryOptions), or individually for each event via beforeSend

**Comment by ColtonIdle** [comment]
Gotcha. Okay, well the fingerprinting is really what i want i think so i appreciate the pointers. cheers
