### ISSUE TITLE
Failed to init Sentry during appender initialization: DSN is required

### ISSUE THREAD

**Issue by ramilS** [getsentry/sentry-java#3249]
### Integration

other

### Java Version

21

### Version

7.4.0

### Steps to Reproduce

io.sentry.jvm.gradle: 4.3.1
spring-boot 3.2.3

if add logback configuration and provide dsn config in application.yaml - fails init appender, but if I pass config via env variable - its works

**Demo** https://github.com/ramilS/sentry-logback

### Expected Result

application.yaml  config should work

### Actual Result

it is not working

**Comment by adinauer** [comment]
Hello @ramilS, can you try to also add the DSN to your `logback.xml`?

https://docs.sentry.io/platforms/java/guides/spring-boot/logging-frameworks/ suggestes the following:

> You do not need to configure your DSN in the Logback configuration file since Sentry is configured from the Spring Boot integration.
> However, if errors that may appear during startup should to be sent to Sentry, the DSN must be provided to both the Logback and Spring Boot configurations.

Your repro prints `INFO: Initializing SDK with DSN: 'https://123@some-sentry.com/1'`. I can't find anything in logs that suggest, Sentry wouldn't work.

If you want to have errors during startup reported to Sentry, you can try replacing your appender in `logback.xml` with:

```
    <appender name="SENTRY" class="io.sentry.logback.SentryAppender">
        <options>
            <!-- NOTE: Replace the test DSN below with YOUR OWN DSN to see the events from this app in your Sentry project/dashboard -->
            <dsn>https://123@some-sentry.com/1</dsn>
        </options>
    </appender>
```

I did not add any ENV vars for startup. Just enabled `debug` in `application.yaml`:

```
sentry:
  dsn: https://123@some-sentry.com/1
  environment: DEV
  debug: true
```
