### ISSUE TITLE
Add span descriptions for OkHttp child spans

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-java#3262]
### Description

Currently, the parent span `http.client` has a description and therefore the span summary shows stats grouped by description (e.g. separate for specific endpoints).

OTOH, the child spans (e.g. `http.client.connection` and below) are all mashed into one `(unnamed span)` group because they don't have a description set. Therefore you can’t see stats separated by endpoint. 

For the span summary module we should add duplicate the description for the child spans. This will likely also be relevant/required for a more span oriented world and Performance v2.

**Comment by Lisio** [comment]
Same story with sentry-php. Setting description for the span solves it and shows that description under "name" column.

**Comment by kahest** [comment]
> Same story with sentry-php. Setting description for the span solves it and shows that description under "name" column.

Can you clarify which spans are affected? 

cc @cleptric

**Comment by Lisio** [comment]
Direct children of transaction. If I don't call setDescription for them, they'll be shown as (unnamed span). It's not very obvious that description = name.

![image](https://github.com/getsentry/sentry-java/assets/1868244/7aa9c6c7-2a13-429b-a344-84002655d90e)

**Comment by kahest** [comment]
@Lisio so you're creating custom spans - that's a different topic, but we'll take a note that the docs on custom instrumentation could be improved by explaining the reasons for setting a span description.
