### ISSUE TITLE
Gwani

### ISSUE THREAD

**Issue by umarG9** [getsentry/sentry-java#3264]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

6.1

### Proguard

Enabled

### Version

5.0.

### Steps to Reproduce

T2t b2b

### Expected Result

Dear lord 

### Actual Result

_new world revolutionary

**Comment by adinauer** [comment]
Closing this, if you're having issues with the Sentry Java SDK, please open an issue with actual information in it.
