### ISSUE TITLE
The Kanban does not see data after the Android 13 device reports, but the earlier version can normally see the reported time

### ISSUE THREAD

**Issue by shiduan** [getsentry/sentry-java#3268]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

4.1.2

### Proguard

Enabled

### Version

7.6.0

### Steps to Reproduce

The Kanban does not see data after the Android 13 device reports, but the earlier version can normally see the reported time
my android 13 had permission 
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

### Expected Result

The Kanban does not see data after the Android 13 device reports, but the earlier version can normally see the reported time

### Actual Result

this my gradle config
    implementation "io.sentry:sentry-android:7.6.0"
    
    classpath 'com.android.tools.build:gradle:4.1.2'
    classpath 'io.sentry:sentry-android-gradle-plugin:1.7.33'

**Comment by kahest** [comment]
@shiduan sorry I do not follow - what is "The Kanban"? And what data are you missing? Can you provide links or screenshots? (make sure you don't post any sensitive information though!)

**Comment by shiduan** [comment]
Sorry, it's a network issue with my local service.Thank you for your reply
