### ISSUE TITLE
Align/extend User Agent

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-java#3274]
SDK should sent events to Sentry with user agent in the format `<sdk-name>/<sdk-version>`

**Comment by kahest** [comment]
@markushi I think the user agent is already set here

https://github.com/getsentry/sentry-java/blob/61981dc1039b766300d6e38e82ccacb439387cb7/sentry/src/main/java/io/sentry/RequestDetailsResolver.java#L41

which is used here

https://github.com/getsentry/sentry-java/blob/61981dc1039b766300d6e38e82ccacb439387cb7/sentry/src/main/java/io/sentry/SentryClient.java#L62

Is this sufficient?

**Comment by markushi** [comment]
> Is this sufficient?
@kahest oh right, yes this should be fine then! Let's close this as done.
