### ISSUE TITLE
Record all thread stacks

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#330]
```java
Thread.getAllStackTraces()
```

Limit size of stacktraces, only send on mobile.

Apparently iOS events are *huge* and threads are a big reason why. Need to coordinate to figure out what exactly should be sent for threads-that-didn't-create-the-event.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1

`options.setAttachThreads(true)`
