### ISSUE TITLE
SentryHttpClientException is being sent to sentry

### ISSUE THREAD

**Issue by mrzbn** [getsentry/sentry-java#3315]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.2.1

### Proguard

Enabled

### Version

7.1.0

### Steps to Reproduce

SentryHttpClientException is being sent to sentry, while I haven't specified that it should be sent.

### Expected Result

SentryHttpClientException should not be sent automatically.

### Actual Result

![Screenshot 2024-04-04 110700](https://github.com/getsentry/sentry-java/assets/58802944/94c9b9d2-8540-4ce6-841e-524d222a5a27)

**Comment by kahest** [comment]
Hey @mrzbn thanks for getting in touch! We auto-enabled capturing of failed HTTP requests for our OkHttp and Apollo integrations with version 7.0.0 of the SDK (see [release notes](https://github.com/getsentry/sentry-java/blob/main/CHANGELOG.md#behavioural-changes)).

You can of course still disable them - or you can provide a list of HTTP status codes and/or request endpoints that you want to monitor: https://docs.sentry.io/platforms/android/integrations/okhttp/#http-client-errors

**Comment by mrzbn** [comment]
thanks for the quick reply. how can I disable it.

**Comment by kahest** [comment]
@mrzbn you need to [disable the auto-installation](https://docs.sentry.io/platforms/android/integrations/okhttp/#disable) of the integration, and then use [manual installation](https://docs.sentry.io/platforms/android/integrations/okhttp/#manual-installation) to configure the integration the way you want it. To only disable HTTP CLient Errors, you can use this:

```kotlin
private val client = OkHttpClient.Builder()
  .eventListener(SentryOkHttpEventListener())
  .addInterceptor(SentryOkHttpInterceptor(captureFailedRequests = false))
  .build()
```
