### ISSUE TITLE
UserInterface does not allow for custom tags/data (and no way to easily customize user creation to use it)

### ISSUE THREAD

**Issue by dlopuch** [getsentry/sentry-java#336]
Sentry allows custom data to be included with the user interface if submitted under a `data` dictionary, but the java implementation of UserInterface doesn't support it.

My code example https://github.com/getsentry/raven-java/issues/259#issuecomment-285764196 shows how to extend the UserInterface and UserInterfaceBinding to allow it, but the lib would have to provide some implementation hook to override [the default user creation process](https://github.com/getsentry/raven-java/blob/v7.8.3/raven/src/main/java/com/getsentry/raven/event/helper/HttpEventBuilderHelper.java#L51), which doesn't use it (nor lots of other user fields).

Perhaps the solution is to break `HttpEventBuilderHelper.addUserInterface` into it's own EventBuilderHelper (eg `DefaultEventUserBuilder`?), the helper being created in a protected method in the DefaultRavenFactory.  If someone wants to create their own users differently, they can extend the default raven factory and provide their own implementation of `createEventUserBuilderHelper()` that would supply their own UserInterface, applying whatever custom tags they want.

**Comment by bretthoerner** [comment]
Merged this in.
