### ISSUE TITLE
Some Sentry XML options (eg.: traces.user-interaction.enable) cause a C++ SIGSEV SIGFAULT error on API 21

### ISSUE THREAD

**Issue by rolandsarosy** [getsentry/sentry-java#3392]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.2.0

### Proguard

Disabled

### Version

7.6.0

### Steps to Reproduce

1. Have Sentry enabled, and run it on an API 21 device.
2. Enable the following options in XML: 
```XML
        <meta-data
            android:name="io.sentry.traces.user-interaction.enable"
            android:value="true" />
        <meta-data
            android:name="io.sentry.traces.sample-rate"
            android:value="1.0" />
        <meta-data
            android:name="io.sentry.traces.profiling.sample-rate"
            android:value="1.0" />
```
3. Go into your (Jetpack Compose UI) application, and start clicking on various UI elements in rapid succession. (The issue 100% happens with regular use as well, but this is the easiest way to reproduce it.)
4. After a while, the interactions will slow down a bit, then, the crash happens.

### Expected Result

Application should not cause SIGSEV C++ errors on API 21.

### Actual Result

The application first slows down, then crashes with a native C++ SIGSEV SIGFAULT error. Often the crash cannot even be caught by Sentry itself. When it can be, the [exception looks something like this](https://gist.github.com/rolandsarosy/4552ab49180dd2b0cee5fe8e331661aa). 

You can find our exact list of libraries and more information about our setup in the stacktrace above, but I'm here to answer any questions you have too. 

We first encountered this issue on our android-based PoS terminals running API 21, but we were able to reproduce the issue on an emulator running the same API level too. 

If you guys are unable to reproduce this issue, I'll see if I can't procure some sort of simplifed part of the codebase to help. 

Something to note (maybe?) is that we're setting up Sentry with a proxy: 

```Kotlin
        SentryAndroid.init(this) { options ->
            options.environment = BuildConfig.FLAVOR
            options.proxy = SentryOptions.Proxy(BuildConfig.SENTRY_APN_PROXY_IP, BuildConfig.SENTRY_APN_PROXY_PORT)
        }
```

The issue goes away as soon as we remove the 3 parts mentioned above from the Manifest.

**Comment by markushi** [comment]
Thanks for reaching out @rolandsarosy, let me try to reproduce this on our end.

**Comment by markushi** [comment]
Next steps:
* Try other API levels < 26
* Dump native memory / log free memory right before the crash

**Comment by markushi** [comment]
I the meantime disabling user interaction tracing would at least prevent the crashes

```xml
   <meta-data
            android:name="io.sentry.traces.user-interaction.enable"
            android:value="false" />
```

**Comment by rolandsarosy** [comment]
Yeah, we've disabled `user-interaction` all-together. If the issue won't get resolved in the near future (_which would be understandable as this seems like a harder-to-solve issue_), we'll look into programmatically enabling/disabling `user-interaction` depending on API levels.

**Comment by markushi** [comment]
Quick update: After some further investigation we could reproduce the issue, but only on API level 21 devices. There's seems to be no clear root cause, and the stack traces actually indicate that the system profiler seems to be the root cause.

If you can reproduce this issue on newer device (>= API 22) please let us know and we'll take another look.

**Comment by rolandsarosy** [comment]
We could only reproduce the issue on API level 21 devices too. API level 22 and above did not replicate this behavior.

**May I ask why is it being marked as done, however?**  This issue still persists on API level 21 and API level 21 is officially supported by Sentry.

**Comment by romtsn** [comment]
@rolandsarosy from what I can tell we've decided to just drop support for profiling on API 21 in https://github.com/getsentry/sentry-java/pull/3478, which should mitigate the issue.  There's no way for us to fix it properly, as we're relying on the OS profiler, and the original issue seems to lie there.
