### ISSUE TITLE
Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

### ISSUE THREAD

**Issue by nirav-tukadiya** [getsentry/sentry-java#3405]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.2.2

### Proguard

Enabled

### Version

7.3.0

### Steps to Reproduce

run assembleRelease

### Expected Result

It should fetch the sentry SDK version and continue building the project

### Actual Result

Error: 
Could not resolve io.sentry:sentry-android-navigation:7.3.0.
         > Could not parse module metadata **/io/sentry/sentry-android-navigation/7.3.0/sentry-android-navigation-7.3.0.module
            > Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

**Comment by nirav-tukadiya** [comment]
@markushi Fresh run with below command works. What do you think could have corrupted the cache? 

FYI, This was only happening for 7.3.0 and we have migrated to 7.4.0 but would like to understand in detail so that we could fix the root cause and migrating latest version may not be feasible all the time and also, caching tasks is important is we build 4 different flavors and would like to save time on build.

**Comment by nirav-tukadiya** [comment]
thanks for clarification. @romtsn

**Comment by markushi** [comment]
Closing this in favor of https://github.com/getsentry/sentry-java/issues/2233
