### ISSUE TITLE
Contexts.setTrace can't be null

### ISSUE THREAD

**Issue by leonchen83** [getsentry/sentry-java#3414]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.2

### Proguard

Enabled

### Version

7.8.0

### Steps to Reproduce

Contexts.setTrace(final @Nullable SpanContext traceContext)

### Expected Result

it's Nullable. so traceContext can set to null.

### Actual Result

throw NPE.
We want set this value to null as same as iOS sdk.

**Comment by adinauer** [comment]
Thanks for opening this issue @leonchen83. We'll change this to actually allow setting `null`.

**Comment by adinauer** [comment]
Thanks, I'll clarify about consistency, but for now I'll move forward with the `@NotNull` since that reflects what the current implementation does.

**Comment by adinauer** [comment]
We just had a talk about this and want to keep trace context required, i.e. `@NotNull`.
