### ISSUE TITLE
Make it possible to disable dedupe filter in spring boot

### ISSUE THREAD

**Issue by piotrblasiak** [getsentry/sentry-java#3426]
### Problem Statement

Currently it is impossible to disable the deduplication filter when using the spring boot starter.

**Comment by adinauer** [comment]
Hello @piotrblasiak, can you please elaborate on why you'd like to disable the filter? Is it filtering too much? There'll likely be a lot more events being sent to Sentry, consuming your quota.

**Comment by piotrblasiak** [comment]
I'm actually surprised the filter is enabled by default - I want to be able to see how often some errors occur. Some one-time errors may not be super serious, but some may affect a lot of users and should be dealt with as soon as possible. Is this not a very common way to reason about error reporting?

**Comment by adinauer** [comment]
Hmm maybe there's a misunderstanding here, the filter shouldn't filter out a similar error happening again but instead is meant to filter out actual duplicates, e.g. when a logging integration as well as an exception handler try to capture the same exception twice.

**Comment by adinauer** [comment]
It'd have to be the exact *same* `Throwable` reference (i.e. `==`) being captured again for it to be filtered out by `DuplicateEventDetectionEventProcessor`, so in the case you're describing it should NOT filter it out. Did you run into problems when playing around or is this a theoretical concern?

**Comment by piotrblasiak** [comment]
Aha ok, I thought I had read it compared the stack traces and not the object references. If that's the case, I guess all is fine. Thanks.
