### ISSUE TITLE
How to implement SSL Pinning in Android

### ISSUE THREAD

**Issue by dinakaranm13** [getsentry/sentry-java#3435]
### Problem Statement

Currently i'm using Sentry version 1.7.16 need to implement SSL pinning. Can you help on this

**Comment by dinakaranm13** [comment]
Hi Team

Can you check it and give me the solution

**Comment by markushi** [comment]
@dinakaranm13 thanks for reaching out!

SSL pinning is an Android system feature, and needs to be configured on an app level. More details about this can be found on the [Android docs page](https://developer.android.com/privacy-and-security/security-config#pin-set).

In case you want to make the Sentry SDK work with self-signed certificates (e.g. in a self-hosted use case) you can utilize `SentryOptions.setSslSocketFactory()` to trust your own certificate.

**Comment by dinakaranm13** [comment]
@markushi Thanks for the reply

From which SDK version "SentryOptions.setSslSocketFactory()" method is accessible and Currently i'm using Sentry version 1.7.16

**Comment by markushi** [comment]
Support for `SentryOptions.setSslSocketFactory()` was added in [SDK version 3.0](https://github.com/getsentry/sentry-java/pull/944). 1.7.16 was released more than 5 years ago - if possible I strongly recommend upgrading to the latest version.

**Comment by dinakaranm13** [comment]
@markushi Ok Thanks
