### ISSUE TITLE
Custom User Id not working

### ISSUE THREAD

**Issue by sakibanda** [getsentry/sentry-java#3447]
### Gradle Version

8.4

### AGP Version

8.3.2

### Code Minifier/Optimizer

Proguard

### Version

4.4.0

### Sentry SDK Version

7.9.0

### Steps to Reproduce

I am using this code to set StatsigUser but, it worked fine earlier. Now I am seeing some random user ids in issues. My user id doesnot contain hyphens. 
Example ID: ee9ad1a1-14e4-4db1-a5d6-57cd354319
```
var uid: String = "demo123456"
val statsigUser = StatsigUser(uid).apply {
    custom = mapOf(
        "userID" to uid,
        "email" to value.email,
        "name" to value.name,
        "chatCount" to value.chatCount,
        "imageCount" to value.imageCount,
        "speechCount" to value.speechCount,
        "creditsBalance" to value.creditsBalance,
        "referrerId" to value.referrerId,
        "deviceId" to deviceId,
        "signedIn" to value.signedIn,
    )
}
Statsig.updateUser(statsigUser)
```

### Expected Result

User id like hX00ReNV9sdfsdfdsfACpjHstAyx1

I am using the same user id with other third party sdks and they are working fine.

### Actual Result

Example ID: ee9ad1a1-14e4-4db1-a5d6-57cd354319

**Comment by romtsn** [comment]
hi @sakibanda have you had a chance to look at the above suggestion from @kahest ?

**Comment by sakibanda** [comment]
Thanks for your suggestion, it helps a lot. Its my mistake, confused Sentry with Statsig.
