### ISSUE TITLE
Android Performance V2 - missing application.load, contentprovider.load spans

### ISSUE THREAD

**Issue by zhukic** [getsentry/sentry-java#3449]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.2.2

### Proguard

Disabled

### Version

7.9.0

### Steps to Reproduce

Hi!

`enablePerformanceV2` feature is enabled

I see that that the spans should be collected via `AppStartMetrics.onApplicationCreate` and `AppStartMetrics.onApplicationPostCreate` calls but I haven't found any usages of these methods.

### Expected Result

`application.load`, `contentprovider.load` spans are presented as on the screenshot from the [doc](https://docs.sentry.io/platforms/android/performance/instrumentation/perf-v2/)

![image](https://github.com/getsentry/sentry-java/assets/10047598/2b3ffa8f-30b9-4ddd-af5c-d467499e3187)

### Actual Result

`application.load`, `contentprovider.load` spans are missing

![image](https://github.com/getsentry/sentry-java/assets/10047598/55b7487c-82bc-435e-a01b-2fd2254cf6b1)

**Comment by romtsn** [comment]
hey, in the same doc you've [linked](https://docs.sentry.io/platforms/android/performance/instrumentation/perf-v2/#app-start), we also mention that the feature requires that you use our Gradle plugin - have you tried to integrate it?

<img width="713" alt="Google Chrome 2024-05-30 22 42 13" src="https://github.com/getsentry/sentry-java/assets/4999776/e912d61c-4d00-478b-a415-336261bb6047">

**Comment by zhukic** [comment]
@romtsn Yes, I use the plugin version `4.6.0`
Config in my `app` module:
```
sentry {
    autoUploadProguardMapping = true
    includeDependenciesReport = false
    tracingInstrumentation {
        enabled = false
    }
    autoInstallation {
        enabled = false
    }
}
```

**Comment by zhukic** [comment]
Looks like it's because the disabled `tracingInstrumentation`

**Comment by romtsn** [comment]
yes, `tracingInstrumentation` controls all bytecode manipulation logic, so if it's disalbed, then app starts are also not instrumented

**Comment by zhukic** [comment]
I guess it's worth updating the [doc](https://docs.sentry.io/platforms/android/performance/instrumentation/perf-v2/#app-start) that `tracingInstrumentation` should be enabled.

Thank you for help!

**Comment by romtsn** [comment]
great point! there's also a flag specific to app starts `tracingInstrumentation.appStart.enabled`, @markushi maybe worth to update the doc
