### ISSUE TITLE
Change OkHttp events from spans to attributes

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#3520]
### Description

We charge performance per span, so we can remove all sub-spans of the `http.client` span, changing them to measurements.
This could also improve readability of the span waterfall. We have a "workaround" that automatically collapses http.client sub-spans, but that's not ideal.
Slack discussion: https://sentry.slack.com/archives/GUCRT2B70/p1719330898362759?thread_ts=1719323921.345899&cid=GUCRT2B70

**Comment by cleptric** [comment]
Spann attributes, measurements are something else we don’t want to keep using in SDKs.

**Comment by stefanosiano** [comment]
We can create a sample and compare the result with the current implementation to check the developer experience
