### ISSUE TITLE
Deprecate `enableTracing` option

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#3566]
### Description

We want to remove the `enableTracing` option at some point as it's causing confusion regarding incoming traces. Also tracing != performance

https://github.com/getsentry/team-sdks/issues/84

**Comment by markushi** [comment]
Let's deprecate in 7.x and remove it in the upcoming 8.x release

**Comment by markushi** [comment]
Also consider updating the wizard + docs
