### ISSUE TITLE
Incorrect cold app start measurement when the app was opened after recev push notification receive

### ISSUE THREAD

**Issue by zhukic** [getsentry/sentry-java#3567]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.4.2

### Proguard

Enabled

### Version

7.9.0

### Steps to Reproduce

Hi!

We noticed incorrect values for `app.start.cold` metric, and we managed to reproduce it if a push notification is received and the app is opened after some time(minutes or hours).

<img width="1464" alt="11" src="https://github.com/getsentry/sentry-java/assets/10047598/a0c35bd1-aea5-4f67-ac79-9f0f9bbaff69">

I see that it duplicates the https://github.com/getsentry/sentry-java/issues/3538 https://github.com/getsentry/sentry-java/issues/3329 issues, but I decided to create a separate one because it may be a different case.

I also see that some [fix](https://github.com/getsentry/sentry-java/pull/3550) is on the way, and it would be good to know if the fix also solves my problem.

Sentry Gradle plugin version: `4.6.0`
Performance V2 enabled

Thank you!

### Expected Result

Incorrect `app.start.cold` values.

### Actual Result

Do not report cold app start in such cases?

**Comment by kahest** [comment]
Hey @zhukic thanks for reporting, especially with this important detail

> reproduce it if a push notification is received and the app is opened after some time(minutes or hours).

As you mention, the open PR might fix this issue as well 👍 
Out of curiosity - did you try/manage to reproduce this with Performance V2 turned off?

cc @stefanosiano @markushi

**Comment by zhukic** [comment]
@kahest 

> did you try/manage to reproduce this with Performance V2 turned off?

I haven't tried to reproduce with V2 turned off but I can try if it may help somehow

**Comment by kahest** [comment]
@zhukic thanks for offering, no need atm - we'll try ourselves and get back to you in case we need more info

**Comment by zhukic** [comment]
@kahest Hi!
I see that you merged the [fix](https://github.com/getsentry/sentry-java/pull/3550). Could you please explain how the SDK will behave in case of push notifications after the fix?

**Comment by stefanosiano** [comment]
@zhukic  The [fix](https://github.com/getsentry/sentry-java/pull/3550) was released in the SDK version 7.12.1. 
Please, reopen this issue in case the problem persists.
