### ISSUE TITLE
[SR] Jetpack Compose views are not redacted

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#3577]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

latest

### Proguard

Enabled

### Version

latest

### Steps to Reproduce

Try Beta Session replay with redaction on (default)

### Expected Result

Jetpack Compose views are redacted

### Actual Result

Not redacted

# Next steps

Edit docs, since we linked to this issue and noted that we don't support it yet

**Comment by iamrita** [comment]
HI @bruno-garcia - are there any updates on when redacting jetpack compose views might be completed?

**Comment by romtsn** [comment]
@iamrita sorry for the late response, but we're working on it as we speak, so stay tuned :)
