### ISSUE TITLE
io.sentry.android.core.AndroidOptionsInitializer.initializeIntegrationsAndProcessors ANR triggered by slow operations in main thread

### ISSUE THREAD

**Issue by seven415** [getsentry/sentry-java#3584]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.3.1

### Proguard

Enabled

### Version

7.9.0

### Steps to Reproduce

sdk init from firebase

### Expected Result

ANR

### Actual Result

log from firebase:

io.sentry.android.core.AndroidOptionsInitializer.initializeIntegrationsAndProcessors (AndroidOptionsInitializer.java:147)
io.sentry.android.core.SentryAndroid.lambda$init$1 (SentryAndroid.java:137)
io.sentry.Sentry.applyOptionsConfiguration (Sentry.java:196)
io.sentry.Sentry.init (Sentry.java:165)
io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:87)
io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:58)
io.sentry.android.core.SentryInitProvider.onCreate (SentryInitProvider.java)
android.content.ContentProvider.attachInfo (ContentProvider.java:2516)
android.content.ContentProvider.attachInfo (ContentProvider.java:2486)
io.sentry.android.core.SentryInitProvider.attachInfo (SentryInitProvider.java:39)
android.app.ActivityThread.installProvider (ActivityThread.java:8308)
android.app.ActivityThread.installContentProviders (ActivityThread.java:7810)
ccc.rrr.hhh.s.a.setEnd (Native method)
ccc.rrr.hhh.s.a.attachBaseContext (a.java:82)
android.app.Application.attach (Application.java:350)
android.app.Instrumentation.newApplication (Instrumentation.java:1178)
android.app.LoadedApk.makeApplication (LoadedApk.java:1457)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7540)
android.app.ActivityThread.access$1600 (ActivityThread.java:315)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2286)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8751)
java.lang.reflect.Method.invoke (Native method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)

**Comment by markushi** [comment]
We're closing this as a duplicate in favor of https://github.com/getsentry/sentry-java/issues/2541
