### ISSUE TITLE
Respect server backoff responses across restarts

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#360]
429 / DSN revoked (need other examples) should be persisted to disk and respected across app restarts.

**Comment by bruno-garcia** [comment]
It seems 429 is not being respected atm.
An exception is thrown but no state is kept to short circuit the next request until `Retry-After` is reached.

Perhaps I'm missing something? I was looking at [this ](https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/connection/HttpConnection.java)and [this](https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/connection/AsyncConnection.java).

**Comment by bretthoerner** [comment]
It's handled by the `LockdownManager` as part of `AbstractConnection`:

https://github.com/getsentry/sentry-java/blob/c5002e9b58fa3312eaabef76c81f8aeefa249b50/sentry/src/main/java/io/sentry/connection/AbstractConnection.java#L99-L102

It's pretty convoluted. I can't remember completely why now. I think because we wanted to handle the logic for any type of connection, and we were maintaining some backwards compatibility with the old client?

There are tests that cover the "lockdown" process, and I've tried it manually (though it's been a long time now). Have you seen it fail in practice or is this just from code viewing?

**Comment by bruno-garcia** [comment]
@bretthoerner thanks for clarifying.
I was answering a question about the Java SDK and while digging through the code I saw the catch blocks only logging which made me wonder.

**Comment by maciejwalkowiak** [comment]
@bruno-garcia is this something we want to implement?

**Comment by marandaneto** [comment]
there was already some discussion around it, and ideally yes, but it was not a high priority as the SDK would hit only once on app restart and it'd hit 429 again, let's keep it open

**Comment by bruno-garcia** [comment]
I wouldn't bother with this tbh. It's not worth doing I/O for the rate limit stuff to optimize to a restart. No SDK has this, never got discussed outside of this issue that I'm aware.

If it restarts, it hits Sentry once, and stops.
I'll close, if u strong disagree, feel free to reopen and we can discuss this.

**Comment by marandaneto** [comment]
I'm fine not doing it.

This has been discussed offline, @mitsuhiko wanted to implement it a while ago.

IMO the biggest problem is when there's an SDK breakage like the Facebook one

Most of the Apps crash on App. start, people try to open 3, 4 times at least, in this case, if they get 429, it's hitting again and again on each try.
