### ISSUE TITLE
Sentry can't read stacktraces generated by Project Reactor with operatorStacktrace feature

### ISSUE THREAD

**Issue by IcyEagle** [getsentry/sentry-java#3602]
### Integration

sentry

### Java Version

21

### Version

7.9.0

### Sentry instance

24.3.0 self-hosted

### Steps to Reproduce

1. Create a project with WebFlux/Project Reactor support.
2. Make sure that [operatorStacktrace](https://projectreactor.io/docs/core/release/reference/#_reading_a_stack_trace_in_debug_mode) feature is on
3. Throw an error

Your stacktrace may look like this:

```
retrofit2.HttpException: HTTP 400 Bad Request
	at com.home.util.RetrofitExtKt.bodyOrThrow(RetrofitExt.kt:21)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ io.sentry.spring.jakarta.webflux.SentryWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/admin/call" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at com.home.util.RetrofitExtKt.bodyOrThrow(RetrofitExt.kt:21)
                at.foo.bar(Bazz:42)
                ...
```

### Expected Result

Stacktrace is properly parsed and sent to the Sentry server. Then it could be read and linked with Source Maps.

### Actual Result

Sentry only reads the first 2 lines, the error message and 1 stacktrace line. It probably stops at `Suppressed` and ignores what comes after that.

**Comment by lbloder** [comment]
Hi @IcyEagle,
Thanks for reaching out.

Could you verify, maybe through debugging, that this is in fact a supressed exception? If so, supressed exception are currently not supported/reported on/to sentry in our stable versions. We have, however, implemented support for them already in our branch for the upcoming 8.0 release in #3396 . There's currently 8.0.0-alpha.4 out for it. You could give that a try if you'd like, you can find it [here](https://github.com/getsentry/sentry-java/releases/tag/8.0.0-alpha.4).

Hope this helps. If you have any more questions/issues, don't hesitate to let us know.
