### ISSUE TITLE
Android manifest int/float parsing

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-java#3603]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

n/a

### Proguard

Enabled

### Version

7.12.0

### Steps to Reproduce

Add `    <meta-data android:name="io.sentry.session-replay.session-sample-rate" android:value="1" />` to android manifest (this is what was output by a custom tooling that creates items programatically during build from a `1.0` double value after calling `ToString()` on it in c#

### Expected Result

Recognizes `1` as `1.0`

### Actual Result

`Key io.sentry.session-replay.session-sample-rate expected Float but value was a java.lang.Integer.  The default value -1.0 was returned.`

**Comment by markushi** [comment]
@vaind thanks for reporting! Let's ensure we fix this for all attributes where we expect `float` values.
