### ISSUE TITLE
Session replays not recorded and are not available in Sentry Dashboard

### ISSUE THREAD

**Issue by Zhelyazko-A** [getsentry/sentry-java#3605]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.2.2

### Proguard

Disabled

### Version

7.12.0

### Steps to Reproduce

1. Setup Session Replay as described in the docs: https://docs.sentry.io/platforms/android/session-replay/
These are our settings:
```
SentryAndroid.init(appContext) { options ->
            options.dsn = BuildConfig.SENTRY_DSN

            // Enable session replay
            // https://docs.sentry.io/platforms/android/session-replay/

            // The sample rate for replays that are recorded when an error happens.
            // This type of replay will record up to a minute of events prior to the error and continue recording until the session ends.
            // Session reply will only be uploaded to Sentry if an error occurs.
            options.experimental.sessionReplay.errorSampleRate = 1.0
            // The sample rate for replays that begin recording immediately and last the entirety of the user's session.
            options.experimental.sessionReplay.sessionSampleRate = 1.0

            // Disable automatic redaction of text and images
            options.experimental.sessionReplay.redactAllText = false
            options.experimental.sessionReplay.redactAllImages = false
        }
```

2. Optionally, add a testing exception somewhere in the app
3. Run the app and close it after some time playing around or trigger the test exception

### Expected Result

There should be Session Replays in Sentry Dashboard -> Explore -> Replays.
Or when you open your test exception in Sentry Dashboard -> Issues -> Select your test Exception -> Replays tab should contain the session replay .

### Actual Result

There are no session replays anywhere in the Sentry Dashboard, even after multiple runs of the app.
I'm attaching Logcat output. There are constantly log outputs from MPEG4Writer and every 5 seconds there are logs saying:
```
2024-07-25 16:44:32.259 MPEG4Writer                D  Video track stopped. Stop source
2024-07-25 16:44:32.259 MPEG4Writer                D  Stopping writer thread
2024-07-25 16:44:32.259 MPEG4Writer                D  0 chunks are written in the last batch
2024-07-25 16:44:32.259 MPEG4Writer                D  Writer thread stopped
2024-07-25 16:44:32.260 MPEG4Writer                I  Ajust the moov start time from 0 us -> 0 us
2024-07-25 16:44:32.260 MPEG4Writer                D  Video track stopping. Stop source
2024-07-25 16:44:34.478 OMXClient                     I  IOmx service obtained
2024-07-25 16:44:34.528 ExtendedACodec          I  setupVideoEncoder()
```
It seems like it's not recording anything.

It has been tested on emulator and physical devices running Android 10 and 11

[Session-replay-log.txt](https://github.com/user-attachments/files/16379109/Session-replay-log.txt)

**Comment by romtsn** [comment]
hi @Zhelyazko-A, thanks for trying the replay feature and reporting back! The logs you've posted are to be expected, because we create a video segment every 5 seconds. 

Could you:
* Enable debug logging via `options.setDebug(true)` and report back if there's anything suspicious
* Post a link to your project?

Thanks!

**Comment by romtsn** [comment]
@Zhelyazko-A oh wait, I just actually realized that your org is in denylist for now, because it's sales-led (=big). Please talk to your sales representative to get a better idea when we can open up replay for your org. In the meantime, you can create a new org and project just to try it out on the side.
