### ISSUE TITLE
Cold start measurement doesn't work in 7.12.1

### ISSUE THREAD

**Issue by zhukic** [getsentry/sentry-java#3608]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.5.1

### Proguard

Enabled

### Version

7.12.1

### Steps to Reproduce

Updated SDK from 7.9.0 to 7.12.1

Performance V2 is enabled

Application launch from foreground(`isForegroundImportance` is `true`)

### Expected Result

Cold start measurement works

### Actual Result

Transactions are missing the `app.start.cold` span.

I debugged the SDK, and the problem is here 
https://github.com/getsentry/sentry-java/blob/7ee04939ef1d36a477fc99f382a4268975bdae36/sentry-android-core/src/main/java/io/sentry/android/core/performance/AppStartMetrics.java#L237

The `Runnable` passed to `Handler.post` is called before `AppStartMetrics.onActivityCreated` so that `appLaunchedInForeground` set to `false` which leads to `AppStartMetrics.getAppStartTimeSpanWithFallback` returns the empty span.

**Comment by kahest** [comment]
@zhukic thanks for reporting - @stefanosiano pls take a look 🙏

**Comment by stefanosiano** [comment]
> The Runnable passed to Handler.post is called before AppStartMetrics.onActivityCreated so that appLaunchedInForeground set to false which leads to AppStartMetrics.getAppStartTimeSpanWithFallback returns the empty span.

hey @zhukic 
The runnable is put at the end of the main thread queue. If the app is starting and an Activity is going to be created, the creation of the Activity is already in the queue. This means that the runnable runs after the Activity onCreate().
I tried in our sample app and in a newly created project and it seems to work fine.
Could you provide a link to a transaction that should have a cold start span, but doesn't have one?

**Comment by stefanosiano** [comment]
@zhukic simply copy the url of the Sentry page where you see the spans of the transaction (or even just a screenshot).
If you don't want to publicly show any information here on Github, you can even send it to `stefano.siano@sentry.io`

> Could it be that the creation of the first activity is not in queue at that moment, and that's why SDK's runnable is run first?

From my test projects it works correctly even when the `AppStartMetrics.registerApplicationForegroundCheck` is called in the ContentProvider.
So I'd need to look at the transaction to check if there's something wrong with it

**Comment by zhukic** [comment]
@stefanosiano I'll share the transactions by email a bit later.

**Comment by stefanosiano** [comment]
Hi @zhukic, did you have a chance to share the transactions?

**Comment by zhukic** [comment]
Hi @stefanosiano. I've sent an email stefano.siano@sentry.io

**Comment by stefanosiano** [comment]
thanks, i'll have a look and get back to you!

**Comment by stefanosiano** [comment]
The issue is reproducible on some devices (including Pixel 6a, Pixel 7 and probably others), that break the assumption that the activity creation is executed before other tasks added to the main thread queue.
We'll have to find a way to improve our detection for these devices

**Comment by stefanosiano** [comment]
Hi @zhukic 
the fix has been released in version 7.14.0
Feel free to reopen this issue in case the fix doesn't work in you case
