### ISSUE TITLE
Sentry Replay Crashing App: Fatal Exception: java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by focux** [getsentry/sentry-java#3618]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.2.1

### Proguard

Enabled

### Version

7.12.0

### Steps to Reproduce

I still haven't been able to reproduce it but I have lots of crashes in crashlytics about it. Seems to be happening in all android versions.

Strack trace:
![Image](https://github.com/user-attachments/assets/f04ecaf2-a288-4bf7-870c-c68a95de7b36)

### Expected Result

To not crash

### Actual Result

Crashes

**Comment by romtsn** [comment]
hi, thanks for reporting the issue and trying out the replay feature! we're already aware of the problem and working on a fix, will post an update here once it's shipped
