### ISSUE TITLE
Source code not shown in Sentry next to stack trace

### ISSUE THREAD

**Issue by AlbertoCortina** [getsentry/sentry-java#3625]
### Integration

sentry-spring-boot-starter-jakarta

### Java Version

21

### Version

7.13.0

### Environment

self-hosted running version 23.4.0

### Steps to Reproduce

1. Configure Sentry in my Spring Boot project, this is my `build.gradle.kts` configuration
```kotlin
plugins {
    id("io.sentry.jvm.gradle") version "4.11.0"
}

dependencies {
    implementation("io.sentry:sentry-spring-boot-starter-jakarta:7.13.0")
}

sentry {
    includeSourceContext.set(true)
    includeDependenciesReport.set(true)
    autoUploadSourceContext.set(true)
    autoInstallation {
        enabled.set(true)
    }

    org.set("sentry")
    projectName.set("my-project-name")
    url.set("my-instance-url")
    authToken.set("my-token")
}
```

2. Write some code to trigger the error
3. Do `./gradlew assemble` so the sources are uploaded to Sentry (I can see them uploaded with the proper `debug_id`)
4. Run the application and force the error

### Expected Result

1. ✅ See the error in Sentry
2. ❌ See the source code next to the stack trace as shown in https://docs.sentry.io/platforms/java/guides/spring-boot/source-context/

![Image](https://github.com/user-attachments/assets/6846c4ba-3511-481c-978b-928f7bfdc1b5 )
*Example from the documentation mentioned above*

### Actual Result

After triggering an error, I only see the stack trace without any code around like in the example provided in the Sentry documentation

![Image](https://github.com/user-attachments/assets/7c83f36c-2474-4347-96ce-fe9ff6c52a11)

----
### More (hopefully useful) information
Running the project locally I can see that the `debug_id` sent in the Sentry envelope when the exception is triggered matches the one uploaded as a debug file (I can see it uploaded successfully after running `./gradlew assemble`)

```json
{
  "debug_meta": {
    "images": [
      {
        "type": "jvm",
        "debug_id": "8f6cf514-5aae-48d1-b99f-ad01df069460"
      }
    ]
  }
}
```

Debug file upload matching the `debug_id`
![Image](https://github.com/user-attachments/assets/6a584ca3-3575-4054-a9f6-63470c258a95)

**Comment by kahest** [comment]
Hey @AlbertoCortina thanks for the report, we'll take a look and follow up here. Would you be able to share a link to the issue on sentry.io, either here or via email to karl.struggl@sentry.io?

**Comment by AlbertoCortina** [comment]
Hello @kahest,
I can't provide a link on sentry.io because we are using a self-hosted instance. Just in case it matters, we're experiencing the issue while running Sentry version 24.7.1.

**Comment by AlbertoCortina** [comment]
Hello @kahest,

We downgraded our instance to version 24.6.0, and everything is working as expected -- I can see the code next to the stack trace again. It might be worth checking the changes introduced between versions 24.6.0 and 24.7.1 that could be causing this issue.

**Comment by kahest** [comment]
@AlbertoCortina that's interesting, thanks for letting us know! We'll take a look

**Comment by lbloder** [comment]
Hi @AlbertoCortina,
Good to hear, that it works after downgrading. 
However, I was unable to reproduce your problem with either `24.7.0` or `24.7.1` on my own self-hosted instance.

I set-up a simple controller and a service that throws a runtime exception and here's my build.gradle.kts:
```
plugins {
    java
    id("org.springframework.boot") version "3.3.2"
    id("io.spring.dependency-management") version "1.1.5"
    id("io.sentry.jvm.gradle") version "4.11.0"
}

group = "org.example"
version = "0.0.1-SNAPSHOT"

dependencies {
    implementation("io.sentry:sentry-spring-boot-starter-jakarta:7.13.0")
    implementation("org.springframework.boot:spring-boot-starter-web")
}

sentry {
    includeSourceContext.set(true)
    includeDependenciesReport.set(true)
    autoUploadSourceContext.set(true)
    autoInstallation {
        enabled.set(true)
    }

    org.set("org")
    projectName.set("project")
    url.set("self-hosted-url")
    authToken.set("token")
}
```

Would you be able to provide a minimal reproducible sample?

**Comment by madopew** [comment]
+1, self hosted sentry v 24.7.1, source bundle is uploaded and debug id is sent, no source code is shown
```json
"debug_meta": {
    "images": [
      {
        "debug_id": "b1235361-8d90-4533-b403-b6610202f5bb",
        "type": "jvm"
      }
    ]
  }
```
![Image](https://github.com/user-attachments/assets/e2ec0d0d-9959-4d4a-8e76-2cbcf3c41840)
![Image](https://github.com/user-attachments/assets/25011224-2b62-4823-a466-cb42e30c87f0)
