### ISSUE TITLE
Emit `transaction.data` inside `contexts.trace.data`

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-java#3626]
- find out if we already do this
- if we don't implement it like this :)

**Comment by lbloder** [comment]
@kahest We are currently sending transaction (root span) data as part of `EXTRAS` [here](https://github.com/getsentry/sentry-java/blob/9762f09afa51944b40a9b77e116a55e54636e6c5/sentry/src/main/java/io/sentry/protocol/SentryTransaction.java#L98-L103). Should we keep that for the sake of backwards compatibility?

**Comment by kahest** [comment]
@lbloder I'm not sure, I don't have context why we do this - maybe @stefanosiano @markushi have an idea.

**Comment by stefanosiano** [comment]
> [@kahest](https://github.com/kahest) We are currently sending transaction (root span) data as `extra` [here](https://github.com/getsentry/sentry-java/blob/9762f09afa51944b40a9b77e116a55e54636e6c5/sentry/src/main/java/io/sentry/protocol/SentryTransaction.java#L98-L103). Should we keep that for the sake of backwards compatibility?

I'd keep it for compatibility, also because we are updating v7.
We can think about removing it in v8, if it's not used by our product

**Comment by markushi** [comment]
@lbloder as [discussed here](https://github.com/getsentry/team-sdks/issues/95#issuecomment-2324425445), let's remove sending it as `event.extra`.
