### ISSUE TITLE
Add Profiles to Custom Transactions

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-java#3643]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

4.11.0

### Proguard

Enabled

### Version

7.14.0

### Steps to Reproduce

Hi I have profiling enabled and created a Custom Transaction but there's no associated profile.
demo app creates a custom transaction [here](https://github.com/sentry-demos/android/blob/main/app/src/main/java/com/example/vu/android/empowerplant/MainFragment.java#L307) and I don't see a Profile appear with it ([trace](https://demo.sentry.io/performance/trace/61b2efd3b98b45618ae8f5de98f2f12b/?node=txn-063e5d33947f41d49c982d2e83fd7f87&project=1801383&query=&referrer=performance-transaction-summary&source=performance_transaction_summary&statsPeriod=14d&timestamp=1723488388&transaction=checkout+%5Bandroid%5D&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)) by default, and we have Profiling [enabled](https://github.com/sentry-demos/android/blob/main/app/src/main/AndroidManifest.xml#L74).

Documentation mentions how to add spans, connect errors and do other things with Custom Instrumentation but no mention on profiling. Is it possible?

https://docs.sentry.io/platforms/android/tracing/instrumentation/custom-instrumentation/
![Image](https://github.com/user-attachments/assets/6abf66bb-ccb0-479e-ab00-98190445d618)

Customer I'm working with is going to do this for their iOS app too.

Documentation Request
https://github.com/getsentry/sentry-docs

### Solution Idea
A good solution would not involve having to do something like `profile.start()` and then set it on scope of the transaction/span object. It'd be nice to have it recording...as soon as you start the new transaction/span.
1. start a custom transaction [docs say transaction, not span]
2. profile starts being recorded (assuming they have SDK Profiling enabled)
3. end the custom transaction and this ends the profile

### Expected Result

Custom Transaction with a Profile

### Actual Result

Custom Transaction with no Profile

**Comment by kahest** [comment]
Just noting that this should work ootb and we're analysing if/why this might not work as expected in these cases.

**Comment by markushi** [comment]
Let's give this a quick test, but by using a profiler callback this should work fine.

**Comment by markushi** [comment]
As discussed internally:
You can use profilesSampler to control which transactions get profiled and which not, more details are [on our docs page](https://docs.sentry.io/platforms/android/configuration/options/#profiles-sampler).

Closing this for now, @thinkocapo please let us know if there's still an issue and we'll re-open!
