### ISSUE TITLE
Fix issue leaked IntentReceiver for SystemEventBreadcrumbsIntegration

### ISSUE THREAD

**Issue by mayananand369** [getsentry/sentry-java#3658]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.2.2

### Proguard

Disabled

### Version

7.8.0

### Steps to Reproduce

When i run the app with the following configurations(as shown in the image attached), it shows the Leaked Intent receiver error for io.sentry.android.core.SystemEventsBreadcrumbsIntegrations$SystemEventsBroadcastReceiver 

Following is my SentryLogger class:
![Image](https://github.com/user-attachments/assets/f1374466-dbd4-479d-8255-6257fb606234)

Following is the entry point of my app `CheckInternetAndSessionActivity` where i have configured sentry:
![Image](https://github.com/user-attachments/assets/a742acb2-b222-44e9-a28f-c869b74e3a87)

### Expected Result

There should not be any error regarding this.

### Actual Result

![Image](https://github.com/user-attachments/assets/bba0c91a-fca9-4119-b677-fb75961fb177)

![Image](https://github.com/user-attachments/assets/fb5ed241-d62b-4359-bb54-77b7d4c14048)

**Comment by markushi** [comment]
@mayananand369 thanks for reporting! This indeed looks like a bug on our end.

In the meantime you can init the Sentry SDK by using the application context, like this:
```kotlin
SentryAndroid.init(context.getApplicationContext(), ...
```

**Comment by mayananand369** [comment]
@markushi i have already init the Sentry SDK like this. Thanks

**Comment by markushi** [comment]
@mayananand369 are you sure? As far as I can see from your screenshots your `fun configureSentryEnvironment()` passes `this` as a context parameter, which is an `Activity` Context - hence the leak.

**Comment by mayananand369** [comment]
@markushi okay. I got your point. Thanks for pointing this out. I passed `applicationContext` in place of `this` and it worked. You may close this issue now.
