### ISSUE TITLE
ANR root cause analysis not showing in issues details

### ISSUE THREAD

**Issue by mrzbn** [getsentry/sentry-java#3666]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.2

### Proguard

Enabled

### Version

7.1.0

### Steps to Reproduce

this section is not showing in my issues. is there any kind of options or settings that need to be set?

![Image](https://github.com/user-attachments/assets/66e6616c-1b37-44b7-9a41-3cb58b35d5ef)

### Expected Result

I want "Suspect root issues" section to be visible on my ANR issues

### Actual Result

 "Suspect root issues" section is not there

**Comment by markushi** [comment]
Hey @mrzbn, thanks for reaching out! Currently we only link a set of known performance issues with ANRs, [see the docs for more details](https://docs.sentry.io/platforms/android/configuration/app-not-respond/#common-patterns).

In your case the ANR likely has a root cause which unfortunately couldn't be detected as a common pitfall. If you have any ideas on how we can improve the detectors, please let us know!

**Comment by mrzbn** [comment]
thanks. it is weird that i don't see any "Suspect root issues", because I have lots of ANR and none have it. also I can't see Android device classification and I thought maybe there is some kind of settings that is not applied to my sentry.

**Comment by romtsn** [comment]
@mrzbn do you use sentry self-hosted or SaaS? If it's the latter, could post a link to one of the ANRs that you expect to have root causes?

**Comment by romtsn** [comment]
@mrzbn which version of self-hosted?

**Comment by mrzbn** [comment]
@romtsn version 23.10.1

**Comment by romtsn** [comment]
@mrzbn I think you'd have to enable the feature by flipping the `organizations:anr-analyze-frames` feature flag to `True`. See here: https://github.com/getsentry/sentry/blob/88c7f2d98d379e68d27adfaf5c9b815a4d54cb89/src/sentry/conf/server.py#L1756

**Comment by mrzbn** [comment]
thanks. i'll try it.

**Comment by romtsn** [comment]
this one is probably necessary as well: https://github.com/getsentry/sentry/blame/88c7f2d98d379e68d27adfaf5c9b815a4d54cb89/src/sentry/conf/server.py#L1754
