### ISSUE TITLE
Make SentryLogbackInitializer public

### ISSUE THREAD

**Issue by DzmitryShylovich** [getsentry/sentry-java#3707]
### Problem Statement

I would like to make `SentryLogbackInitializer` work with [ContextRefresher](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java) from spring-cloud. `ContextRefresher` emits `RefreshScopeRefreshedEvent` instead of `ContextRefreshedEvent`, so I would like to extend `SentryLogbackInitializer` and override `supportsEventType` method to support new event type instead of copy-paste everything.

### Solution Brainstorm

Is it possible to make `SentryLogbackInitializer` public?

**Comment by adinauer** [comment]
Hey @DzmitryShylovich, sure we can make it public.

**Comment by adinauer** [comment]
@DzmitryShylovich we've just released `8.0.0-beta.1` of the Java SDK where `SentryLogbackInitializer` is now public. If you decide to give it a try, feedback would be great :-)
