### ISSUE TITLE
Breadcrumb sharing across Multiple Processes - Android

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-java#3748]
### Problem Statement

**StepsToReproduce**

1. open app, which opens `process_1` in Android
2. do stuff in `process_1` which records breadcrumbs
3. DO NOT CRASH THE APP, NO CRASH HAPPENS
4. navigate to new screen which launches `process_2` in Android
5. do stuff in `process_2` which records breadcrumbs
6. CRASH in `process_2`

**Expected Behavior**
Breadcrumbs from both process_1 and process_2 should be in the resulting Issue in Sentry

**Actual Behavior**
Breadcrumbs from process_2 are in the resulting Issue in Sentry.
Breadcrumbs from process_1 are not in the resulting Issue in Sentry.

### Solution Brainstorm

Share breadcrumbs (hub&scope) across processes.
https://docs.sentry.io/platforms/android/configuration/multi-process-apps/

**Comment by romtsn** [comment]
Closing in favour of #3849
