### ISSUE TITLE
Allow to configure globalHubMode for SentryAppender from logback.xml

### ISSUE THREAD

**Issue by marbon87** [getsentry/sentry-java#3779]
### Problem Statement

We have a java swing app, that uses logback for logging and the SentryAppender from sentry-logback.
Sentry is configured in the logback.xml.

We need to enable globalHubMode, to get breadcrumbs across multiple threads. I didn't find a way to enable globalHubMode by using logback.xml. Only solution i found is to copy the content from SentryAppender#start() 

### Solution Brainstorm

Add the attribute globalHubMode in SentryAppender to get the possibilit of configuring globalHubMode from logback.xml

**Comment by adinauer** [comment]
Hey @marbon87 we only provide a subset of config options directly via the XML config. The intended way for more complex config is to use `sentry.properties` (ExternalOptions) but it seems `globalHubMode` also isn't configurable there yet. We can add it so it's read from `sentry.properties`. The way this will work is shown in our [logback sample](https://github.com/getsentry/sentry-java/tree/main/sentry-samples/sentry-samples-logback/src/main/resources).

**Comment by adinauer** [comment]
We have just released [`8.0.0-beta.2`](https://github.com/getsentry/sentry-java/releases/tag/8.0.0-beta.2) of the Java SDK, which allows configuring `global-hub-mode` through external options like `sentry.properties`. Happy to receive any feedback in case you decide to give it a try.

**Comment by marbon87** [comment]
Work's perfectly. Thank you @adinauer !

**Comment by adinauer** [comment]
Thanks for the feedback!
