### ISSUE TITLE
android replay record is blank

### ISSUE THREAD

**Issue by zxx7x** [getsentry/sentry-java#3804]
### Description

When using sentry-android-replay, the management console can see the replay records, but the screen recording of each record is blank
version：7.15.0，8.0.0-beta.1，7.16.0-alpha.1

**Comment by markushi** [comment]
@zxx7x thanks for reporting! Can you reproduce this issue locally on your device? 
If so, could you share the log output of the SDK (can be enabled via `SentryOptions.setDebug(true)`)?

**Comment by markushi** [comment]
@zxx7x did you have any time to look into this?

**Comment by zxx7x** [comment]
@markushi Thanks for reply! I have turned on debug mode, but I don't see any error messages. I can see the local Reply file, but the video I see in the  management console  is blank.
My sampleRate is
options.experimental.sessionReplay.onErrorSampleRate = 1.0
options.experimental.sessionReplay.sessionSampleRate = 1.0
![Image](https://github.com/user-attachments/assets/d2672fb7-5f88-4d3f-8f58-f5cb800007e0)
![Image](https://github.com/user-attachments/assets/71c75b4f-c430-4207-a3a1-00303e23bf4d)

**Comment by romtsn** [comment]
@@zxx7x what version of self-hosted sentry are you using? I think we don't support replay for self-hosted yet, but would have to double-check

**Comment by zxx7x** [comment]
7.15.0

**Comment by zxx7x** [comment]
@romtsn 7.15.0

**Comment by romtsn** [comment]
@zxx7x I meant this: https://github.com/getsentry/self-hosted. I assume you're not using sentry SaaS, but self-hosted?

**Comment by markushi** [comment]
@zxx7x any updates on this?

**Comment by romtsn** [comment]
@zxx7x we're closing the issue for now since no response was provided for more than a month. Our suspicion is that you're using and older version of self-hosted that does not contain Session Replay for Mobile yet, so we advise you to update the self-hosted version and get back to us if it still does not work. Thanks!
