### ISSUE TITLE
Failed to bind properties under 'sentry.parsed-dsn' to io.sentry.Dsn

### ISSUE THREAD

**Issue by detomarco** [getsentry/sentry-java#3825]
### Integration

sentry

### Java Version

22

### Version

7.16.0

### Steps to Reproduce

Use version 7.16 and set `SENTRY_DSN=""` (empty string)

### Expected Result

Application starts and sentry is disabled

### Actual Result

from Sentry v7.16.0 I get this error
```
Failed to bind properties under 'sentry.parsed-dsn' to io.sentry.Dsn:

    Reason: java.lang.IllegalArgumentException: Invalid DSN scheme: null

Action:

Update your application's configuration
```

I think it's related to this PR https://github.com/getsentry/sentry-java/pull/3796

**Comment by markushi** [comment]
Thanks for opening this issue @detomarco ! Are you sure this worked before?
I just tried our spring boot demo app `7.15.0` and compared it with `7.16.0` - both fail if the DSN is an invalid string containing only ticks `""""` .

However setting `SENTRY_DSN=` instead of `SENTRY_DSN=""` works as expected, and disables sentry.

Could share a few more details about your environment / sentry setup?

**Comment by evmetatron** [comment]
I have the same problem. When I use 7.16.0, I get the same error.

Hovever when I use 7.15.0, I don't get any error.

I use springboot v3.3 and there's application.yaml with param `sentry.dsn: ''`

**Comment by adinauer** [comment]
I've done some testing and so far I'm unable to reproduce the exact problem (`Invalid DSN scheme: null`).

Can you please share more details like integrations used, config settings etc.?

**Comment by micopiira** [comment]
I managed to reproduce this, using Spring Boot 3.3.5 and Sentry 7.16.0. For some reason for me this does not happen when using embedded tomcat but does happen when deploying traditional WAR to Tomcat.

I have this in my application.properties


`sentry.dsn=`

**Comment by adinauer** [comment]
Thanks for providing more info @micopiira, we'll take another look

**Comment by lbloder** [comment]
Hi @micopiira @detomarco,
We believe we figured out what causes this issue.

It seems that, in contrast to the embedded Tomcat, the standalone Tomcat has `JNDI` enabled which causes premature calls to `SentryOptions.getParsedDsn()` during property binding.

Renaming the method to `retrieveParsedDsn()` circumvents this as only bean properties (i.e. `getXXXX()`) are being bound by `JNDI`. Will open a PR in the next few minutes for this.

**Comment by adinauer** [comment]
@detomarco @micopiira @evmetatron we've released https://github.com/getsentry/sentry-java/releases/tag/7.17.0 which includes a fix for this problem. If you decide to give it a try - feedback would be great.

**Comment by adinauer** [comment]
Thank you for feedback!
