### ISSUE TITLE
Possibility to exclude tags from Appender

### ISSUE THREAD

**Issue by benoit-lateltin** [getsentry/sentry-java#383]
We have overridden the `buildEvent(ILoggingEvent iLoggingEvent)` method of `ExtendedSentryAppender` in order to exclude the `JSESSIONID` tag for security reasons:

```java
for (Map.Entry<String, String> mdcEntry : iLoggingEvent.getMDCPropertyMap().entrySet()) {
    // remove JSESSIONID and URI tag
    if (!mdcEntry.getKey().equals("JSESSIONID") && !mdcEntry.getKey().equals("URI")) {
        if (extraTags.contains(mdcEntry.getKey())) {
            eventBuilder.withTag(mdcEntry.getKey(), mdcEntry.getValue());
        } else {
            eventBuilder.withExtra(mdcEntry.getKey(), mdcEntry.getValue());
        }
    }
}
```

Would it be possible to do this in a cleaner way?

**Comment by bretthoerner** [comment]
`EventBuilderHelper`s in recent versions have a `getEvent` method so you can get and mutate fields. It's a bit ugly and configuring new builder helpers still requires using your own factory (until we handle #222).

Maybe we need an API for some kind of "event field filters"?

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1

`options.setBeforeSend(...)` to mutate events before being sent
