### ISSUE TITLE
TTFD timer sometimes not working

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-java#3831]
### Description

We have 2 timers for timeouts, one for the transaction and one for the TTFD span.
The transaction's timer finishes any running span with `deadline_exceeded`.
The TTFD span's timer finishes the TTFD and trims it to the TTID timestamps.

If the transaction's timer runs first, then the TTFD timer does nothing, as the span is already finished.

Possible solutions:

1. Change TTFD timeout tp 25 seconds
2. Remove the TTFD timer and make it part of an EventProcessor

**Comment by markushi** [comment]
Let's go for 1) as it seems to be the easiest to fix. Let's also update the docs.
