### ISSUE TITLE
fromHttpStatusCode in SpanStatus L79 does not handle 3xx

### ISSUE THREAD

**Issue by mikand13** [getsentry/sentry-java#3841]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This is our relevant code:

transaction?.finish(fromHttpStatusCode(status ?: 500))

### Expected Result

Would expect this to return an ok spanstatus or something of that order for a 3xx response, 304 f.ex is a very normal cache response, and 301 or 302 is not unusual either, f.ex. in auth apis.

### Actual Result

It seems a null SpanStatus is returned which again marks this as a failed transaction. We have a lot of 304 so basically all our requests are tagged as failed giving us a >99 failure rate.

### Product Area

APIs

**Comment by adinauer** [comment]
Thanks for the feedback, not sure why there's a gap in status codes, I'll try to find out and report back.

**Comment by mikand13** [comment]
@adinauer One might argue that 301, 303 and 307 are responses that expect some kind of change, ie. it is not a successful request, but not sure if that level of detail is necessary.

**Comment by adinauer** [comment]
Thanks, I'll check with python SDK maintainers if they're aware of any complaints regarding those.

**Comment by adinauer** [comment]
We have just released [`8.0.0-beta.2`](https://github.com/getsentry/sentry-java/releases/tag/8.0.0-beta.2) of the Java SDK, which now maps status codes below 400 to `SpanStatus.OK`. If you decide to give it a try, feedback would be great.
