### ISSUE TITLE
sentry crash free rate not showing correctly

### ISSUE THREAD

**Issue by mrzbn** [getsentry/sentry-java#3865]
sentry is reporting that on a specific version, there is 8 crashes. but when i click the "8" to see what are those 8 crashes, it only shows 1 crash. can anyone explain to me which on is correct? 8 or 1?![Image](https://github.com/user-attachments/assets/14803b07-22ee-4e3c-b7cb-f232c505f5b6)

**Comment by mrzbn** [comment]
one guess i have is that maybe events are being dropped, BUT are being counted anyways

**Comment by romtsn** [comment]
hi @mrzbn do you use sentry self-hosted or cloud? If cloud could you post a link to your project in sentry?

**Comment by mrzbn** [comment]
@romtsn I'm using self-hosted.

**Comment by romtsn** [comment]
Ok, when you say 

> but when i click the "8" to see what are those 8 crashes, it only shows 1 crash. 

Does it show 1 _issue_ or 1 _event_? It also depends what's the time range you selected on the releases page and on the issues page (is it 30d for both?)

![Image](https://github.com/user-attachments/assets/f968bf32-eb5c-4cba-ab8b-2d38bfee5c4c)

**Comment by mrzbn** [comment]
![Image](https://github.com/user-attachments/assets/df5232a2-b037-44e6-80a9-da00f5229a8a)

*********
i set the time range to 90D in both pages. when i click the 1.2k, it goes to issues page and shows me only about 60 events. image below:
*********

![Image](https://github.com/user-attachments/assets/7f654937-f782-4829-bb79-52961c1654e0)

**Comment by romtsn** [comment]
@mrzbn alright, thanks for the details. Which SDK and self-hosted versions do you use?

**Comment by mrzbn** [comment]
Sentry SDK version: 7.1.0
Self-hosted version: 23.10.1

**Comment by mrzbn** [comment]
any clue of what is the problem? as i'm seeing a very low crash free rate, but cant see much of errors.

**Comment by romtsn** [comment]
@mrzbn I suspect this might be your self-hosted version, it's over a year old and there were some improvements with regards to release health in the meantime. I'd suggest you try to update the version and check how it looks. It's also possible the SDK is doing something wrong, but I'd expect we would've received much more reports in that case, so it's likely something's off with your SDK config or self-hosted.

**Comment by markushi** [comment]
@mrzbn did you have any chance to look into this?

**Comment by mrzbn** [comment]
@markushi yes. i haven't been able to change self-hosted version. I just updated SDK version and problem still exists. I left a comment earlier "one guess i have is that maybe events are being dropped, BUT are being counted anyways". do you think it could be the reason?

**Comment by stefanosiano** [comment]
@mrzbn if the event is dropped by the server, it could be counted, but that's easily verifiable. You should be able to see how many events were dropped. 
Do they align with the missing crashes?

However, updating the SDK shouldn't change the situation, until the self-hosted version is not updated

**Comment by romtsn** [comment]
There's also a problem that these two stats use different datasets (session count with status `crashed` vs events with level `crashed`), and that can also contribute to the discrepancy here. https://github.com/getsentry/sentry/issues/70570

So if the events are dropped on the server (e.g. inbound filter or rate-limiting), that's probably the reason for this discrepancy.

**Comment by markushi** [comment]
@mrzbn did you have a chance to look into [the comment above](https://github.com/getsentry/sentry-java/issues/3865#issuecomment-2517520760)?

**Comment by markushi** [comment]
Closing this one now in favor of https://github.com/getsentry/sentry/issues/70570
