### ISSUE TITLE
SentryExecutorService Thread Continuously Running, Causing High Power Consumption

### ISSUE THREAD

**Issue by sunxu3074** [getsentry/sentry-java#3891]
### Description

![Image](https://github.com/user-attachments/assets/7bde37f0-7516-4d76-91be-87208444edfb)

![Image](https://github.com/user-attachments/assets/c138e9e2-af5c-4da9-ba5b-8622121f8b8b)

While using Perfetto for performance analysis, we observed that the SentryExecutorS thread stays in a "Running" state consistently. Specifically, the thread shows continuous green blocks over certain time periods, indicating sustained CPU usage (see attached screenshot). This raises concerns about power consumption, especially during prolonged activity.

We would like to understand the following:

What is the purpose of the SentryExecutorS thread?
Is this continuous "Running" state expected behavior, and is there any way to optimize or reduce its CPU usage?
Are there any recommendations from the team regarding power optimization?
Looking forward to your guidance!

**Comment by markushi** [comment]
@sunxu3074 thanks for reaching out! Our `SentryExecutorService` is a single background thread responsible for performing tasks off the main thread. There could be many reasons for it run, e.g. any navigation events, user clicks or system callbacks (e.g. changes to network speed) are processed using `SentryExecutorService`. 

Do you want to optimize the power consumption? You can definitely disable a few features to reduce it. If you can provide some more details about your app / environment we're happy to give you some more guidance!

**Comment by sunxu3074** [comment]
> [@sunxu3074](https://github.com/sunxu3074) thanks for reaching out! Our `SentryExecutorService` is a single background thread responsible for performing tasks off the main thread. There could be many reasons for it run, e.g. any navigation events, user clicks or system callbacks (e.g. changes to network speed) are processed using `SentryExecutorService`.感谢您伸出援手！我们的`SentryExecutorService`是一个后台线程，负责执行主线程之外的任务。它运行的原因可能有很多，例如任何导航事件、用户点击或系统回调（例如网络速度的更改）都是使用`SentryExecutorService`处理的。
> 
> Do you want to optimize the power consumption? You can definitely disable a few features to reduce it. If you can provide some more details about your app / environment we're happy to give you some more guidance!您想优化功耗吗？您绝对可以禁用一些功能来减少它。如果您可以提供有关您的应用程序/环境的更多详细信息，我们很乐意为您提供更多指导！

I have tried the following change, set every configuration option to false, but this thread keeps running. Below is a screenshot from the official OPPO app market, where they indicate that my app is continuously consuming battery power.

![Image](https://github.com/user-attachments/assets/97fb38cc-1523-4a09-8dcf-59b75d6ef0f5)

![Image](https://github.com/user-attachments/assets/4d6e9e25-aa58-4ffd-adde-5f793efca255)

**Comment by romtsn** [comment]
@sunxu3074  could you try to disable `isEnableScopePersistence = false`? This should make the SentryExecutor way less busy. This disables collecting breadcrumbs for ANR events, but it should improve the power consumption signficantly.

**Comment by romtsn** [comment]
RxCache threads should have nothing to do with the Sentry SDK, we don't use RxJava (or any dependency fwiw) in the Android SDK. In general, you could look out for the amount of breadcrumbs that your app generates:
- If it has many Fragments, they will generate a lot of breadcrumbs, you can filter out some [Fragment states](https://docs.sentry.io/platforms/android/integrations/fragment/#configure) that you're not interested in to reduce the number of breadcrumbs logged and persisted
- If you use the Logcat integration, you can also specify a [minLevel](https://docs.sentry.io/platforms/android/integrations/logcat/#configure) for breadcrumbst o reduce the number of breadcrumbs logged and persisted, or you could also disable it altogether if it's not critical for your case

As for this specific issue with breadcrumbs (with scope persistence), we're working on resolving it as we speak, so expect an update in the next couple of weeks.

**Comment by markushi** [comment]
@sunxu3074 any chance you had time to look into the `RxCache` thread utilization?

**Comment by sunxu3074** [comment]
Thank you for your response. I tried using this configuration **isEnableScopePersistence = false** while keeping all previous settings unchanged, and I noticed that the **SentryExecutorService** indeed showed fewer running states. Correspondingly, the running time of the associated daemon threads has also decreased. We’ll roll this out in the next phase and observe.

I’d also like to clarify that our app primarily operates in two processes. The main process is for the keyboard configuration interface, while the **:keyboard** process is a subprocess running the **InputMethodService**. The issues we observed occurred in the subprocess. When using **TikTok**, the **SentryExecutorService** walltime for our keyboard exceeded TikTok's significantly. Could this be related to both processes initializing Sentry? As far as I know, it’s expected to initialize Sentry in both processes, right?

Regarding the **Breadcrumb** issue, we’ve been logging some events to make it easier to observe specific logs directly on the Sentry platform. However, I don’t think this is the primary issue, as we’re not logging constantly—only at critical points do we record logs.

**Comment by sunxu3074** [comment]
> > it’s expected to initialize Sentry in both processes, right?它应该在两个进程中初始化 Sentry，对吧？
> 
> Yes since they run in separate memory spaces (pls correct me if I'm wrong [@markushi](https://github.com/markushi))是的，因为它们在单独的内存空间中运行（如果我错了，请纠正我）
> 
> > we’ve been logging some events to make it easier to observe specific logs directly我们一直在记录一些事件，以便更容易直接观察特定日志
> 
> But you're not using our [logcat integration](https://docs.sentry.io/platforms/android/integrations/logcat/) if I understand correctly但如果我理解正确的话，你没有使用我们的[logcat 集成](https://docs.sentry.io/platforms/android/integrations/logcat/)

I used both the system’s logcat and [Tencent’s xlog](https://github.com/Tencent/mars/blob/master/mars/libraries/mars_xlog_sdk/src/main/java/com/tencent/mars/xlog/Xlog.java) to record logs simultaneously. I only converted xlog into the Sentry log format and recorded it on Sentry.

```kotlin
fun printLogToSentry(logLevel: Int, tag: String, info: String) {
    val level = when (logLevel) {
        Xlog.LEVEL_DEBUG -> SentryLevel.DEBUG
        Xlog.LEVEL_INFO -> SentryLevel.INFO
        Xlog.LEVEL_WARNING -> SentryLevel.WARNING
        Xlog.LEVEL_ERROR -> SentryLevel.ERROR
        Xlog.LEVEL_FATAL -> SentryLevel.FATAL
        else -> SentryLevel.INFO
    }

    val breadcrumb = Breadcrumb().apply {
        setLevel(level)
        category = tag
        message = info
    }
    Sentry.addBreadcrumb(breadcrumb)
}
```

**Comment by markushi** [comment]
@sunxu3074 we're closing this issue as a duplicate in favor of https://github.com/getsentry/sentry-java/issues/3168 If you have any more details to share, please let us know!
