### ISSUE TITLE
Initial display time is reported incorrectly

### ISSUE THREAD

**Issue by zhukic** [getsentry/sentry-java#3896]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.7.2

### Proguard

Enabled

### Version

7.14.0

### Steps to Reproduce

1. Enable "Don't keep activities" in developer options.
2. Open app
3. Leave the app
4. Open the app again in 20 seconds 

### Expected Result

Correct `ui.load` span

### Actual Result

`ui.load` span duration is more than 20 seconds

![Image](https://github.com/user-attachments/assets/f8797a72-50ae-4f5e-b537-e497dbb2a7ac)

As I understand, the root cause is [here](https://github.com/getsentry/sentry-java/blob/ce09ad4523b10ddaa0df90c12c17fb0b7a89bf78/sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java#L222C25-L222C31) - when an activity gets destroyed in the background its paused time is used as the start time for the next `ui.load` transaction

**Comment by markushi** [comment]
@zhukic Thanks for reporting, we'll have a closer look at this.
