### ISSUE TITLE
Scope.setContexts is not working on native crash event.

### ISSUE THREAD

**Issue by ganadist** [getsentry/sentry-java#3955]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.7.2

### Proguard

Enabled

### Version

7.17.0

### Steps to Reproduce

Call following logic

```
Sentry.configureScope { scope ->
  scope.setContexts("Something", something)
}
```

### Expected Result

`Something` should be displayed on Native crash events.

### Actual Result

`Something` is not included on Native crash events.

Documentation:
* https://docs.sentry.io/platforms/android/enriching-events/context/

* `NdkScopeObserver` provides `set/removeExtra` only, and don't provide `set/removeContexts`
  * https://github.com/getsentry/sentry-java/blob/main/sentry-android-ndk/src/main/java/io/sentry/android/ndk/NdkScopeObserver.java#L107-L125

**Comment by markushi** [comment]
@ganadist thanks for your feedback! Yes, as of now only a [limited set of attributes are being synced to the NDK](https://github.com/getsentry/sentry-java/blob/main/sentry-android-ndk/src/main/java/io/sentry/android/ndk/NdkScopeObserver.java). Setting the attributes as tags could work in the meantime, depending on the amount of data you want to sync to the NDK parts. We'll be moving this to the backlog, as it sounds reasonable to sync all context attributes out of the box.

**Comment by markushi** [comment]
As NDK crashes are picked up by the Android SDK on the next app start we should consider persisting the scope to disk and utilizing this here as well.

**Comment by markushi** [comment]
Closing as a dup of https://github.com/getsentry/sentry-java/issues/2056
