### ISSUE TITLE
Agent performance measurement & improvement

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#414]
I need to figure out what kind of latency/throughput the agent adds to "real" code.

Some ideas for improving performance:

- [ ] Don't collect locals for inner frames (like Python slim frames).
- [ ] Cache class/method handles (if possible) rather than looking them up every time.
- [x] Don't aggressively `.toString()` Objects, store a reference and do it later (this may come with other issues, variables changing state or no longer being live?)
- [x] Filter out some exception types from being processed at all, allow users to customize said filters.
- [ ] `WeakHashMap` expunges stale entries on every access (not sure if this will be an issue in practice)

**Comment by bretthoerner** [comment]
Slim frame logic from Python:

```python
frames_len = 0
app_frames = []
system_frames = []
for frame in frames:
    frames_len += 1
    if frame.get('in_app'):
        app_frames.append(frame)
    else:
        system_frames.append(frame)

if frames_len <= frame_allowance:
    return frames

remaining = frames_len - frame_allowance
app_count = len(app_frames)
system_allowance = max(frame_allowance - app_count, 0)
if system_allowance:
    half_max = int(system_allowance / 2)
    # prioritize trimming system frames
    for frame in system_frames[half_max:-half_max]:
        frame.pop('vars', None)
        frame.pop('pre_context', None)
        frame.pop('post_context', None)
        remaining -= 1

else:
    for frame in system_frames:
        frame.pop('vars', None)
        frame.pop('pre_context', None)
        frame.pop('post_context', None)
        remaining -= 1

if not remaining:
    return frames

app_allowance = app_count - remaining
half_max = int(app_allowance / 2)

for frame in app_frames[half_max:-half_max]:
    frame.pop('vars', None)
    frame.pop('pre_context', None)
    frame.pop('post_context', None)
return frames
```

**Comment by neseleznev** [comment]
Hi @bretthoerner!
Thanks a lot for improving sentry-java.

What's the state of java agent?
Is performance degradation still so heavy on real projects like it's said here https://github.com/getsentry/sentry-java/issues/617#issuecomment-461312253 ?

I also faced a link https://docs.sentry.io/clients/java/agent/ multiple times which is 404 now.
Is the feature deprecated or not recommended to use?

**Comment by bruno-garcia** [comment]
@neseleznev we made no changes since that initial alpha and decided to archive that project for the time being.

**Comment by bruno-garcia** [comment]
We'll close this issue until we bring the agent back

**Comment by olsavmic** [comment]
Are there any plans to revive this java agent project? We've been using Sentry for PHP projects for a long time which has this functionality natively and the additional context of stack traces in Java is a huge disadvantage in comparison.

The MDC and breadcrumbs require a lot of manual tuning to get right :/
