### ISSUE TITLE
Is there a way to configure sentry.properties path via Java System Properties ?

### ISSUE THREAD

**Issue by igorperciuleac** [getsentry/sentry-java#416]
I wish to do something like this:
`java -Dsentry.properties=some/path/sentry.properties -jar app.jar`
But can not find such approach in docs.

**Comment by bretthoerner** [comment]
There isn't, but this is a good idea. I'll add it on Monday.

**Comment by igorperciuleac** [comment]
Thank you !

**Comment by bretthoerner** [comment]
Merged in #419, will be released this week.

**Comment by bretthoerner** [comment]
You can find your DSN in your project settings on http://sentry.io/

There is a section in the settings called "Client Keys (DSN)"
