### ISSUE TITLE
raven starting hundreds of threads that block each other and sometimes me

### ISSUE THREAD

**Issue by josh-hight** [getsentry/sentry-java#421]
Stacks at 2017-06-19 02:41:09 PM. Uptime is 14m 46s 200ms.

Thread-1342 State: BLOCKED CPU usage on sample: 0ms
java.net.InetAddress.getLocalHost() InetAddress.java:1486
com.getsentry.raven.event.EventBuilder$HostnameCache$HostRetriever.call() EventBuilder.java:685
com.getsentry.raven.event.EventBuilder$HostnameCache$HostRetriever.call() EventBuilder.java:682
java.util.concurrent.FutureTask.run() FutureTask.java:266
java.lang.Thread.run() Thread.java:745

it looks like raven isn't checking to see whether or not it's already started up a thread to get the local host, is there any way y'all could do a singleton type thing here?

**Comment by bretthoerner** [comment]
I'll check this out ASAP, for now you can ensure this isn't called by manually setting the server name via an env var or something. `SENTRY_SERVERNAME=$(hostname)` for example.

**Comment by josh-hight** [comment]
@bretthoerner That is working awesome as a temporary solution, many thanks 👍

**Comment by bretthoerner** [comment]
Merged something that should fix this, releasing soon.
