### ISSUE TITLE
ShouldSendEvent callback

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-java#426]
We need something like `shouldSendEvent` callback for react native.
Because we don't want to send javascript crashes after the app relaunches, because we already do it as soon the error happens in javascript see: https://github.com/getsentry/react-native-sentry/pull/115/files#diff-2e4f37f244d5e3deb3ba02cf84afd3ecR191

Here is the iOS implementation, pretty simple, if return `NO` the event will not be sent, and the block passes in the event to check for any kind of properties.

https://github.com/getsentry/sentry-cocoa/commit/8a422aa1c508bcfb76d9bbfe2b1f8f527fcf1249
@bretthoerner I think I would need your help please 🍺

**Comment by bretthoerner** [comment]
PR link: #428
