### ISSUE TITLE
Investigate possibility of duplicate events when Android app crashes

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#430]
A user saw duplicate events sent with the following test code (using `sentry-android`)

```java
Sentry.capture("Sentry test");
Sentry.capture(new RuntimeException("Non-fatal crash"));
throw new RuntimeException("Fatal crash"));
```

I haven't been able to reproduce it myself yet, but I can imagine a scenario where duplicates are possible in the case where the application itself is crashing.

Brain dump:

1. We have to do I/O off the main thread on Android, so all data is sent async (which is good/expected).
2. We write all events to disk *before* attempting to send because we have no idea when the app might suddenly die or be killed.
3. It's possible the async thread sends the data to Sentry and then the app is killed *before* the event is cleaned from the disk.
4. This means (in theory) when the app is relaunched, the event is seen on disk and sent again.

I don't know how to fix 3 above, it seems impossible almost by definition.

Our only hope for perfection here is somehow being able to complete some code as the app is crashing, but I highly doubt Android allows us to continue working for an undefined amount of time before the app's process is just destroyed? If anyone has ideas I'm all ears.

---

To make this a little more confusing: my understanding is that the stats for a project are incremented by the dupe, but then in deeper/later processing in the worker the dupe is detected and dropped. So counts end up wrong, but the event itself is not actually duplicated in the project details.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
