### ISSUE TITLE
Crash when adding breadcrumb

### ISSUE THREAD

**Issue by fab1an** [getsentry/sentry-java#434]
```
java.util.NoSuchElementException: queue is empty
    at com.getsentry.raven.util.CircularFifoQueue.remove(CircularFifoQueue.java:313)
    at com.getsentry.raven.util.CircularFifoQueue.add(CircularFifoQueue.java:236)
    at com.getsentry.raven.context.Context.recordBreadcrumb(Context.java:77)
    at com.getsentry.raven.event.Breadcrumbs.record(Breadcrumbs.java:23)
    at ...mycode
```

**Comment by bretthoerner** [comment]
Very odd. This is clearly a bug but I'll need some information to fix it.

1. What version of `raven-java` are you using?
2. What options do you have set (either via DSN or otherwise)?
3. Are you setting breadcrumnbs from multiple threads or is there any other information you can provide?

**Comment by fab1an** [comment]
1. I used raven-android-8.0.3, where I got this bug. (I got this only once in a couple of months of usage though). Today I switched to sentry-android-1.2.1, so maybe it won't happen again.

2. Not sure what you mean exactly. I'm using the DSN to connect and have registered a custom event-builder which collects some information before sending.

3. Yes, multiple threads.

I'm using Sentry via a wrapper for some convenience. (code is in Kotlin): https://gist.github.com/fab1an/4a0ec03a097ab88028c16d803f2a4de1

**Comment by fab1an** [comment]
Oh and I just realized that the breadcrumb prior to that crash was duplicated.The event-id is `1fc7b13c6b4242f4862359a40671bc2f`

**Comment by bretthoerner** [comment]
> Not sure what you mean exactly.

I was just curious if you had any of these set: https://docs.sentry.io/clients/java/config/#options

But honestly, it seems like we just forgot to synchronize breadcrumb access. I'll fix that for sure.

**Comment by bretthoerner** [comment]
Merged a fix, will release shortly.
