### ISSUE TITLE
Document alternative configuration for the Android Gradle Integration (sentry-cli)

### ISSUE THREAD

**Issue by Hazer** [getsentry/sentry-java#436]
Actually the credentials for the upload step are loaded from a `sentry.properties` file in the project root, and this file, has and `auth.token` parameter.

My problem is, I have my project setup on CI, and I want this Token to be configured as an Environment Variable. I cannot commit this token to our Git repo, and Gradle Properties File cannot interpolate Environment Variables.

So I would like an alternate configuration method.

Thanks.

**Comment by bretthoerner** [comment]
This makes sense, thanks for the report.

**Comment by mitsuhiko** [comment]
You can already do this. Since the file is loaded by sentry-cli all the sentry-cli environment variables are supported. Just leave the file empty and export `SENTRY_AUTH_TOKEN` instead.

**Comment by bretthoerner** [comment]
Ah right, well I'll leave this open to add a note about it in the Android docs.

**Comment by Hazer** [comment]
@mitsuhiko @bretthoerner Tried it right now, solved for me!

Thank you!
