### ISSUE TITLE
Support Android Gradle build buildTypes/flavors

### ISSUE THREAD

**Issue by AndrewJack** [getsentry/sentry-java#437]
Could you add the ability to specify a sentry.properties file per buildType/Flavor?

In my case I have separate projects for each build type.
e.g. dogfood & release sentry projects

Similar to how Google have implemented their `google-services` plugin

Build types
```
app/
    sentry.properties
    src/dogfood/sentry.properties
    src/release/sentry.properties
```

flavors & build types
```
app/
    sentry.properties
    src/dogfood/paid/sentry.properties
    src/release/free/sentry.properties
```
https://developers.google.com/android/guides/google-services-plugin#adding_the_json_file

**Comment by bretthoerner** [comment]
Oops, good call, thanks for the report.

**Comment by AndrewJack** [comment]
Using this as a workaround for now

```
apply from: 'sentry-switch-env.gradle'
```

```
def appModuleRootFolder = '.'
def sentryProperties = 'sentry.properties'

task switchToDogfood(type: Copy) {
    def buildType = 'dogfood'
    description = "Switches to $buildType sentry.properties"
    from "$appModuleRootFolder/src/${buildType}"
    include "$sentryProperties"
    into "${rootProject.rootDir}"
}

task switchToRelease(type: Copy) {
    def buildType = 'release'
    description = "Switches to $buildType sentry.properties"
    from "$appModuleRootFolder/src/${buildType}"
    include "$sentryProperties"
    into "${rootProject.rootDir}"
}

afterEvaluate {
    persistSentryProguardUuidsForDogfood.dependsOn switchToDogfood
    persistSentryProguardUuidsForRelease.dependsOn switchToRelease
}
```

**Comment by AndrewJack** [comment]
@bretthoerner Do you support apk splits too? My build seems to work with it so far.

https://developer.android.com/studio/build/configure-apk-splits.html

**Comment by bretthoerner** [comment]
I just did a local test, it seems to me that we already work with splits because it looks like Proguard runs for all source one time, we generate the UUID and drop the `sentry-debug-meta.properties` file which is included in each `.apk`.

Unrelated: have you sent a Sentry event with an `.apk` built using our wrapper yet? I'm actually trying to debug a Proguard issue in production and I'm curious if it has been working (or not) for you. 😬

**Comment by AndrewJack** [comment]
@bretthoerner Probably not i'm still setting it all up.

**Comment by bretthoerner** [comment]
For what it's worth Proguard on Sentry SaaS is working, I'm looking into the build type thing now.
