### ISSUE TITLE
Gradle Plugin not generating sentry-debug-meta.properties

### ISSUE THREAD

**Issue by Hazer** [getsentry/sentry-java#438]
Running into exception:
```
io.sentry.android.event.helper.AndroidEventBuilderHelper: Error getting Proguard UUIDs.
  java.io.FileNotFoundException: sentry-debug-meta.properties
      at android.content.res.AssetManager.openAsset(Native Method)
      at android.content.res.AssetManager.open(AssetManager.java:679)
      at android.content.res.AssetManager.open(AssetManager.java:653)
      at io.sentry.android.event.helper.AndroidEventBuilderHelper.getProGuardUuids(AndroidEventBuilderHelper.java:157)
      at io.sentry.android.event.helper.AndroidEventBuilderHelper.helpBuildingEvent(AndroidEventBuilderHelper.java:73)
      at io.sentry.SentryClient.runBuilderHelpers(SentryClient.java:109)
      at io.sentry.SentryClient.sendEvent(SentryClient.java:162)
      at io.sentry.Sentry.capture(Sentry.java:160)
```

Looking inside the apk, there's no assets folder with sentry-debug-meta.properties.

Android Studio `3.0 Alpha 4`
com.android.tools.build:gradle:`3.0.0-alpha4`
sentry-android-gradle-plugin:`1.0.0-beta`
sentry-android:`1.2.1`
Gradle `4.0`

```Groovy
apply plugin: 'com.android.application'
apply plugin: 'io.sentry.android.gradle'

sentry {
    autoProguardConfig true

    autoUpload IS_CI // Actually false, doing local tests.
}

android {
    // ..........
}
```

**Comment by bretthoerner** [comment]
What command are you running to build the apk?

Can you share the log output of that command?

Can you show the buildType config for the variant you are building?

We only hook `"transformClassesAndResourcesWithProguardFor${name}"` so I think for some reason the Proguard step is not running?

**Comment by Hazer** [comment]
@bretthoerner Sorry for the delay, I got sick and was away from everything related to tech.

I will need to revert my Android Studio update or wait for a fix for the new issue #451 to give you more details, because right know I cannot use your plugin.

But, somehow I am believing, proguard isn't being really called. Because the task you told me isn't being called, and instead, this one is: `transformClassesWithAndroidGradleClassShrinkerFor${name}`. This leads me to believe that Android Studio is skipping proguard and using the experimental Gradle Shrink, I will try to force proguard.

I have 2 productFlavors, `dev` and `prod` and 2 buildTypes `debug` and `release`. 
```
    buildTypes {
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by bretthoerner** [comment]
I updated the plugin to `1.0.2`, can you try that with the Android Studio beta?

I did a test yesterday: OS X, app flavors, Android Studio beta, and 1.0.2 and the whole chain worked for me -- my crash was properly un-Proguard'ed by Sentry. If you still have an issue I'm guessing it's configuration based and I'd like to figure it out so we can better document things.

**Comment by Hazer** [comment]
@bretthoerner Yeah, I cannot do it right now, maybe later today or tomorrow, but I will try building for release with this new version on OSX and in our CI.

**Comment by bretthoerner** [comment]
Any update here, or is the plugin working for you?

**Comment by Hazer** [comment]
@bretthoerner Sorry for the really, really long delay, tried today in my CI with Android Studio Beta2 and Sentry Plugin 1.4.0, sentry-cli 1.19, no logs so far, not even the "skipping upload".

I will try later locally in my OSX setup, maybe there's something related. Also, will set log to info level.

**Comment by Hazer** [comment]
@bretthoerner Tried locally and I am happy to say that its all working fine with latest versions! I didn't work in the CI because as it wasn't working people just "tweaked" it freely and it became a mess. No issue with the plugin at all.

Great work, sorry for the long time to try this one. I am sure it got fixed way before.

Thank you :D
