### ISSUE TITLE
Investigate whether 403 (and other) responses should start a backoff

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#452]
Related to: https://github.com/getsentry/sentry/issues/4695

**Comment by cruftex** [comment]
Already commented on https://github.com/getsentry/sentry/issues/4695.

Since a non-2xx response could originate from intermediate HTTP gateways, its not a good idea to treat a 403 not as a serious problem.

**Comment by bretthoerner** [comment]
Hm, do you have an idea/proposal of what needs to be done to fix your issue?

**Comment by yangyi** [comment]
In my case, the sentry root url suffix with "/" result in double / in dsn url. 

try check sentry root url setting. should not suffix with "/",   should be "http://sentry.example.com", not "http://sentry.example.com".

**Comment by marandaneto** [comment]
403 drops the event
