### ISSUE TITLE
Allow programatically disabling sentry

### ISSUE THREAD

**Issue by francisdb** [getsentry/sentry-java#454]
We use the properties file to configure sentry but would like sentry to only start when running in production mode

I tried the following (scala playframework)

```scala
    // disable sentry when not in production mode
    if(context.environment.mode != Mode.Prod) {
      Sentry.init(null)
    }
```

but in case of null or empty dsn it falls back to the config file.

```
14:50:41.980 WARN  - io.sentry.Sentry                     - Overwriting statically stored SentryClient instance SentryClient{...}.
```

**Comment by bretthoerner** [comment]
The recommendation for this kind of setup would be to not set the DSN in the properties file, but instead set it via an environment variable or system property (only in production). Is that a reasonable solution for you?

The reason I dislike any sort of code solution is that many kinds of exceptions can occur (and be logged) before your first line of application code is called. The only real way to control whether Sentry is off or on is to start the application up with the proper configuration from the start (and environment variables are the best way to do so).

**Comment by francisdb** [comment]
I personally think that it's up to the user to make that decision, you offer the option and already warn about the consequences in the documentation.

Anyway for my part this can be closed as we use logback integration and we have a different logger config for production.
