### ISSUE TITLE
Only 'http' or 'https' connections are supported in Sentry Android, but received: noop

### ISSUE THREAD

**Issue by Shubham1992** [getsentry/sentry-java#457]
Anyone gets this error on using  "compile 'io.sentry:sentry-android:1.2.2'"

**Comment by bretthoerner** [comment]
How are you configuring your Sentry DSN?

**Comment by bretthoerner** [comment]
I just double-checked the code. I should change it to allow for `noop` (with a warning) but that is likely not what you want here -- it sounds like you aren't providing the Sentry DSN: https://docs.sentry.io/clients/java/config/#setting-the-dsn-data-source-name
