### ISSUE TITLE
Break JSON encoding out to a facade (to reduce Android dep size)

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#462]
Discussed in #461.

**Comment by iamareebjamal** [comment]
> Guys, can you please look at this. Having 2 libraries(GSON and Jackson) in our codebase is not quite optimal. We considered moving to Jackson but overall it's not a better choice for us in terms of method count and size

Pinging for attention to this issue.

**Comment by marandaneto** [comment]
it's Gson only now since Android SDK 2.x
