### ISSUE TITLE
logback: throw error if someone tries to use the loback config to set SENTRY config

### ISSUE THREAD

**Issue by graingert** [getsentry/sentry-java#477]
I had sentry silently failing because I misunderstood the upgrade process.

Please make the application fail hard when "\<dsn\>"  or similar is configured via logback.xml

**Comment by bretthoerner** [comment]
That's a good idea, sorry about that.

Out of curiosity, did you not at least get this warning (when an event should have been sent, not necessarily at startup): https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/dsn/Dsn.java#L83-L84

**Comment by graingert** [comment]
@bretthoerner yeah but it didn't go anywhere!

**Comment by bretthoerner** [comment]
It didn't go anywhere?

**Comment by graingert** [comment]
@bretthoerner because there's nowhere for it to go! It couldn't find a DSN.

**Comment by graingert** [comment]
@bretthoerner another idea would be an [everything's ok alarm](https://www.youtube.com/watch?v=lTzByQTeyJQ) that sends a sentry event every hour that sentry is working, and if it stops turning up Sentry logs an error to the timeline.

**Comment by bretthoerner** [comment]
> because there's nowhere for it to go! It couldn't find a DSN.

Oh, sorry, I meant just in normal logs.

I'll see about making it hard fail, but most of that configuration is handled lazily, and so the most it could do is... log a message.

**Comment by graingert** [comment]
@bretthoerner we don't look at those unless sentry alerts an error

**Comment by marandaneto** [comment]
@maciejwalkowiak is this still an issue?

**Comment by maciejwalkowiak** [comment]
It's not am issue because it's perfectly acceptable in v3 to [set DSN via logback configuration](https://docs.sentry.io/platforms/java/guides/logback/#dsn-configuration).
