### ISSUE TITLE
Upgrade (or replace) testng and jmockit

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#478]
The versions we use are old and require we run JDK `1.7.0_80`, otherwise the tests either hang indefinitely or immediately fail.

I'm not sure which is the culprit but we use old versions and the upgrade process isn't easy (I've tried a couple times before). It's also not a burning need since it doesn't affect production users, just ... me.

Travis is currently pinned to Precise so that tests pass. 🦀

**Comment by bruno-garcia** [comment]
Pinning travis to `Precise` won't be possible soon:

> This job ran on our Precise environment, which is in the process of being decommissioned. Please update to a newer Ubuntu version by specifying dist: xenial in your .travis.yml.

**Comment by metlos** [comment]
I've opened https://github.com/getsentry/sentry-java/pull/759 where I'm replacing TestNG and JMockit with JUnit and Mockito (without PowerMock to keep mocking magic to the necessary minimum).

**Comment by bruno-garcia** [comment]
Resolved. Thanks @metlos
