### ISSUE TITLE
Add breadcrumbs support to Logback SentryAppender

### ISSUE THREAD

**Issue by winterbe** [getsentry/sentry-java#485]
Hi,

I'm currently evaluating Sentry via Logback as a replacement for SMTPAppender. SentryAppender works quite well so far however I'm missing one feature from SMTPAppender.

SMTPAppender supports sending the last X log messages (e.g. INFO logs) via defining `cyclicBufferTracker`. It's also possible to filter those log messages via `discriminator` e.g. by providing the current username via MDC.

See this example config:

```xml
<appender name="mail" class="ch.qos.logback.classic.net.SMTPAppender">
        <smtpHost>***</smtpHost>
        <username>***</username>
        <password>***</password>
        <to>***</to>
        <from>***</from>
        <subject>Oops, somethings went terribly wrong</subject>
        <discriminator class="ch.qos.logback.classic.sift.MDCBasedDiscriminator">
            <key>username</key>
            <defaultValue>unknown</defaultValue>
        </discriminator>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%d %-15.15X{username} %5p  %-40.40logger{39} : %m%n%ex</pattern>
        </layout>
        <cyclicBufferTracker class="ch.qos.logback.core.spi.CyclicBufferTracker">
            <bufferSize>15</bufferSize>
        </cyclicBufferTracker>
</appender>
``` 

I'd like to have similar capabilities for SentryAppender such that INFO and WARN logs are automatically converted to Sentry breadcrumbs.

Is this already possible in one way or another?

Thanks.
Benjamin

**Comment by bretthoerner** [comment]
We don't support this yet, but I had the issue #450 created and it's high on my list.

This is interesting though, I'll have to see how they implemented it -- this will be good to compare to (since I just thought up the idea independently before).

**Comment by winterbe** [comment]
Thanks for info. Looking forward to it. Hope the provided info will be
somewhat helpful for you to implement this feature.

Brett Hoerner <notifications@github.com> schrieb am Mi. 9. Aug. 2017 um
16:02:

**Comment by Gensa23** [comment]
Is there any update on this issue or is it stale? this is much needed feature.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1
