### ISSUE TITLE
sentry-android Automatically Enhancing Events - SentryClient

### ISSUE THREAD

**Issue by tajchert** [getsentry/sentry-java#486]
Currently on Android SDK there is no way (none I'm aware of) to automatically enhance outgoing events. Similar to setCaptureListener() on https://github.com/joshdholtz/Sentry-Android 

I would like to pass some static extra data with every capture (as well unhandled exceptions).

In sentry-java there is EventBuilderHelper - which is not possible to use on AndroidSentryClientFactory.

**Comment by bretthoerner** [comment]
The client itself has methods to set things like tags, extras and more. I'll

```java
// grab the client from init
SentryClient client = Sentry.init(...);
client.addExtra("foo", "bar");

// OR do your initialization, then:
SentryClient client = Sentry.getStoredClient();
client.addExtra("foo", "bar");
```

I'll see about better documenting this. Hopefully in most cases `EventBuilderHelper` isn't required. Let me know if you can't accomplish what you need, though.

**Comment by tajchert** [comment]
To clarify - so it is enough to add those extras to SentryClient and they will be passed with every capture from now on (both events, messages, and crashes)?

**Comment by bretthoerner** [comment]
Correct, when it's set at the client level it will be set on all future events. Note that you can also configure this via `sentry.properties` on Android.

The only time the extra data won't be attached is if you send a "fully formed" `Event` object.

In other words, if you're manually sending an event, prefer to do this:

`Sentry.capture(eventBuilder);`

Over this:

`Sentry.capture(eventBuilder.build());`

As in the latter the `Event` object is completely built and not touched at all by the client. If you simply pass a `String` or `Throwable` you are OK, as those will be properly built for you.

**Comment by tajchert** [comment]
How I should utilize `SentryClient` on Android? 

This is not clear by SDK itself (I would guess to pass this in `Sentry.init()` instead of `androidSentryClientFactory`.
As well is not documented `[in docs](https://github.com/getsentry/sentry-java/blob/master/docs/modules/android.rst)`

**Comment by bretthoerner** [comment]
Hmm, did either of solutions in [this comment](https://github.com/getsentry/sentry-java/issues/486#issuecomment-321263260) not work for you? Or are you trying to do something else?

`Sentry.init` returns the `SentryClient` it creates. You can also get it at any time with `Sentry.getStoredClient()`.

I'll be improving the docs for sure, though.

**Comment by tajchert** [comment]
Oh, thanks!
I was sure I had to pass 'SentryClient' to init (after adding extras to it) - not other way around.
Now with that knowledge I will test it and brb with results.
