### ISSUE TITLE
Rename culprit to transaction, allow pushing/popping txns on the context.

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#489]
See: https://forum.sentry.io/t/replacing-culprits-with-transaction-names/105/3

**Comment by dmclain** [comment]
Fixed with 1.6.0?

**Comment by bretthoerner** [comment]
The transaction still isn't available in the context. :(

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1
