### ISSUE TITLE
impossible to extend or subclass HttpInterface for other HTTP servers

### ISSUE THREAD

**Issue by megahall** [getsentry/sentry-java#494]
The `HttpInferface` seems to be almost deliberately hostile to re-implementation or extension for unclear reasons. If these apparently over-protective restrictions could be removed from `HttpInterface`, it would be easier for users and community members to keep extending and broadening the use of Sentry. The product's most key features, and the whole reason I want to use it, which is connecting up exceptions with the HTTP stack and providing context and debuggability, is totally blocked because of this`HttpInterface`:

1. All of the object fields are immutable and no setter methods are provided. No reason for the immutability is given in the object's comments.

2. There is no default constructor in public scope, package scope, not even in private scope. So it's impossible to make a subclass without calling a specific parent constructor. All parent constructors expect `HttpServletRequest request` to be non-null, and reference tons of fields inside it in a hard-coded fashion, so there's no possible way to skip over the assumption you always have an `HttpServletRequest` present. However there are tons of high performance HTTP environments where that object doesn't exist.

   For example, when you use Jersey JAX-RS (the best / most popular Java Pure REST framework) with embedded Grizzly HTTP server (their default server, with very good performance), your requests are  actually a much lighter weight and higher performance object called `org.glassfish.grizzly.http.server.Request` which doesn't implement any heavy-weight Servlet stuff.

3. All of this seems pointlessly over-protective of this object, because there's nothing it's doing which seems to require such lockdown. It would be much better for the community if this things supported some form of extension via default constructors and setters, or subclassing with default constructors, so all of the users could develop and contribute support for lots more Java HTTP and IO frameworks.

**Comment by bretthoerner** [comment]
I agree. My guess is the original implementation (which predates me, so I can only guess) was just supposed to be a best effort that automatically ripped everything it could out of the servlet request and nothing more.

It should definitely be more extendable, as you say.

**Comment by arjantop** [comment]
I have the same issue but using scala. At first I thought I could implement my own `SentryInterface` but after some investigation I found out that I will not be ablo to register the necessary `InterfaceBinding`.

The only way I could see to do this is to implement a request wrapper that implements `HttpServletRequest`. This is a lot of work if you just want to send URL and METHOD information to sentry.

**Comment by bretthoerner** [comment]
So you actually should be able to register your own `SentryInterface` and `InterfaceBinding`, but you'll need to subclass `DefaultSentryClientFactory` and configure Sentry to use your custom factory.

Here's an example:

```java
import com.fasterxml.jackson.core.JsonGenerator;
import io.sentry.DefaultSentryClientFactory;
import io.sentry.dsn.Dsn;
import io.sentry.event.interfaces.SentryInterface;
import io.sentry.marshaller.Marshaller;
import io.sentry.marshaller.json.InterfaceBinding;
import io.sentry.marshaller.json.JsonMarshaller;

import java.io.IOException;

public class MySentryFactory extends DefaultSentryClientFactory {
    @Override
    protected Marshaller createMarshaller(Dsn dsn) {
        Marshaller marshaller = super.createMarshaller(dsn);

        if (marshaller instanceof JsonMarshaller) {
            ((JsonMarshaller) marshaller).addInterfaceBinding(MyHttpInterface.class, new MyHttpInterfaceBinding());
        }

        return marshaller;
    }

    public static class MyHttpInterface implements SentryInterface {
        private String field;

        public MyHttpInterface(String thing) {
            this.field = thing;
        }

        public String getInterfaceName() {
            return "sentry.interfaces.Http";
        }

        public String getField() {
            return field;
        }
    }

    public static class MyHttpInterfaceBinding implements InterfaceBinding<MyHttpInterface> {
        public void writeInterface(JsonGenerator generator, MyHttpInterface myHttpInterface) throws IOException {
            generator.writeStartObject();
            generator.writeStringField("field", myHttpInterface.getField());
            generator.writeEndObject();
        }
    }
}
```

And then I'd set `factory=io.sentry.example.MySentryFactory` in my configuration.

This may be the best route for y'all for now.

**Comment by arjantop** [comment]
Ah, missed the possible `DefaultSentryClientFactory`. This will do for now, still not the nicest but manageable. Thanks @bretthoerner

**Comment by fprochazka** [comment]
My two cents: I really like that the `HttpInterface` is immutable - this is actually an advantage. Instead of making it mutable, I'd suggest creating alternative implementations as @bretthoerner showed.

**Comment by arjantop** [comment]
@fprochazka You could add a `Builder` and still keep it immutable

**Comment by marandaneto** [comment]
Sentry Java SDK v3 made it considerably easy, please open an issue if this is still a problem.
