### ISSUE TITLE
NPE during event serialization

### ISSUE THREAD

**Issue by sbezkostnyi** [getsentry/sentry-java#500]
I've enabled buffering events to disk, but encounter issue during events serialization.

It seems that if `Event.extra` contains mapping to null value, serialization will fail [here](https://github.com/getsentry/sentry-java/blob/ebea973815759256d4ed2c6dde113977867eaade/sentry/src/main/java/io/sentry/event/Event.java#L309), since `objectEntry.getValue()` returns null.

**Comment by bretthoerner** [comment]
Thanks for the report, PR up, bugfix release soon.

**Comment by bretthoerner** [comment]
Fix for this was released in 1.5.3
