### ISSUE TITLE
Disable stacktrace.app.packages warning when set to empty string.

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#503]
From: https://github.com/getsentry/sentry/issues/6033

**Comment by bretthoerner** [comment]
@eximius313 thanks for the report, I've fixed this on `master`: https://github.com/getsentry/sentry-java/commit/d1257513bf67ec188d94140396e207b724196ea5

I'll cut a bugfix release this week.

**Comment by eximius313** [comment]
thanks!

**Comment by bretthoerner** [comment]
Fix for this was released in 1.5.3

**Comment by bretthoerner** [comment]
This looks like a bug in how we parse DSN options, in `foo=` the value is treated as `null` and not `''`.

https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/dsn/Dsn.java#L166

Can you set it via Java System Properties, `sentry.properties` or System Environment Variable for now? I'll try to fix that soon.
