### ISSUE TITLE
Make docs clear on how to use various options from the code initialization

### ISSUE THREAD

**Issue by anshbansal** [getsentry/sentry-java#505]
I was reading through https://docs.sentry.io/clients/java/config/#in-application-stack-frames and it says that I can use any of the options. But it is not clear how to use the property "stacktrace.app.packages" from the code.

The reason I want to do it via code instead is because of the property name "stacktrace.app.packages". If I add it by itself in our properties file noone will know it is sentry related and that makes things confusing.

Similarly it is not clear how after doing this  how do I do anything else.
```
Sentry.init("https://public:private@host:port/1");
```

So under the options https://docs.sentry.io/clients/java/config/#options you need to add at least one example of using these options via code.

**Comment by bretthoerner** [comment]
I could use some help clarifying "Configuration methods" if it was unclear: https://docs.sentry.io/clients/java/config/#configuration-methods

So as the docs note you could put the option a `sentry.properties` file which would make it clear it's Sentry related.

Or you could use `SENTRY_STACKTRACE_APP_PACKAGES=foo` environment variable.

Or you could use the option in your DSN, like:

```
Sentry.init("https://public:private@host:port/1?stacktrace.app.packages=foo");
```

I tried to make the last example more clear here: https://github.com/getsentry/sentry-java/commit/669853e3fe3358a9c5368d8d22b54c9badf360dc

**Comment by anshbansal** [comment]
@bretthoerner  That makes it clear. Thanks for sharing that.
