### ISSUE TITLE
Exclude certain exceptions

### ISSUE THREAD

**Issue by thisdotvoid** [getsentry/sentry-java#507]
Hello,
I'm using Spring integration, what I want is, to control which exceptions are reported and which aren't. I tried using `sentryClient.addShouldSendEventCallback` but can't figure out where is exception instance on `Event` object.

**Comment by thisdotvoid** [comment]
Ended up using this solution, but looks very complicated.
```java
sentryClient.addShouldSendEventCallback(event ->
  event.getSentryInterfaces()
    .entrySet()
    .stream()
    .map(entry -> (ExceptionInterface) entry.getValue())
    .anyMatch(exceptionInterface ->
      exceptionInterface.getExceptions()
        .stream()
        .anyMatch(exception -> {
          return Arrays.stream(EXCLUDED_EXCEPTIONS)
            .anyMatch(Predicate.isEqual(exception.getExceptionClassName()));
        })
    )
);
```

**Comment by bretthoerner** [comment]
Yeah, sorry, I want to improve the API to just pass the exception in the future.

**Comment by thisdotvoid** [comment]
Ok, no worries. I'll close this
