### ISSUE TITLE
Log4j2 - sentry does not work with async loggers

### ISSUE THREAD

**Issue by pwielgolaski** [getsentry/sentry-java#508]
I wrote small test to show problem 
https://github.com/pwielgolaski/sentry-log4jasync

In general issue is that if we use asynch logger append is called from other thread than message is coming.
https://logging.apache.org/log4j/2.0/manual/async.html

All is fine until we dont use https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/event/helper/EventBuilderHelper.java 

I wonder can it be fixed or we at least should warn user that it is not working as it should.
We know what thread event is reported, so we could use it to validate if we are in the same one.

**Comment by bretthoerner** [comment]
Hmm, we had a warning in the documentation about this but I must have accidentally deleted it in a refactor.

The `SentryAppender` is async itself (internally) by default, so it should never block progress on the thread you log from. I think we warned against using the log4j async utilities and this was why. I'll have to dig that up. Is it possible to use async for your other appenders but just not the Sentry one?

**Comment by pwielgolaski** [comment]
Yes, it is possible to use File/Console as all they care is message and message is "build" before you pass it to async loggers.
With Sentry all is fine, till you start use ThreadLocal ...

I wonder in my application if I should switch from async loggers to async appenders and make sentry synchronous.
But as you can see with log4j2 performance report, async loggers are superior.

**Comment by bretthoerner** [comment]
> But as you can see with log4j2 performance report, async loggers are superior.

That's true for File/Console appenders, but the Sentry appender doesn't do any I/O on the main thread. It builds the event and passes it to another thread, then returns control to your program, so it's already fast/async. If you can disable the extra async wrapper on Sentry that would be best.

**Comment by jiacai2050** [comment]
@bretthoerner Hi, after add `-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector` option, it seems `io.sentry/sentry-log4j2 "1.7.4"` can't send msg to sentry server. any ideas ?

**Comment by bretthoerner** [comment]
Hmm, if you enable DEBUG logging what does `io.sentry.*` log?

**Comment by jiacai2050** [comment]
No errors found in DEBUG level, only a warning: 
```
2018-05-10 09:51:46,639 Log4j2-TF-1-AsyncLogger[AsyncContext@723e88f9]-1 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
```
After remove `AsyncLoggerContextSelector` option, this warning remains but in a different thread:
```
2018-05-10 09:52:29,479 sentry-pool-1-thread-1 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger 
```

Using tcpdump, I found when run with `AsyncLoggerContextSelector`, there is no packages sent to sentry server, I make my demo sleep 5s before exit, but still no use.

**Comment by jiacai2050** [comment]
Sorry, my mistake.  sentry-log4j2 did work with AsyncLoggerContextSelector.
Thanks.
