### ISSUE TITLE
Support for multiple DSNs and appenders

### ISSUE THREAD

**Issue by mridang** [getsentry/sentry-java#512]
The documentation for the Log4j2 appender configuration doesn't seem to outline how to use multiple DSNs and appenders.

In the previous `raven-log4j2` we were able to specify the DSNs as a part of the appender configuration e.g.

```        <Raven name="SENTRY_XYZ"
               dsn=https://username:password@sentry1.example.com/1"
               extraTags="account,attribution,platform">
            <Filters>
                <ThresholdFilter level="ERROR" onMatch="ACCEPT" onMismatch="DENY"/>
            </Filters>
        </Raven>
        <Raven name="SENTRY_API"
               dsn="https://username:password@sentry1.example.com/7"
               extraTags="account,attribution,platform">
            <Filters>
                <ThresholdFilter level="ERROR" onMatch="ACCEPT" onMismatch="DENY"/>
            </Filters>
        </Raven>
```

In the current `sentry-log4j2`, the DSN needs to be configured via a properties file but I see no reference on how to couple a DSN with an appender

**Comment by bretthoerner** [comment]
This isn't possible in `sentry-java`, reasoning is given here: https://docs.sentry.io/clients/java/migration/#logging-integration-configuration

I'm curious about the reasoning for using multiple projects in a single app. Could this be handled with tags (and then filtering in the Sentry UI) or is something you need not supported?

**Comment by marandaneto** [comment]
you could create multiple instances of Hub with different DSNs and use it to capture events instead of the Sentry static class
