### ISSUE TITLE
Date Formatting Issue - "app_start_time"

### ISSUE THREAD

**Issue by msrubino** [getsentry/sentry-java#514]
It looks like [this line](https://github.com/getsentry/sentry-java/blob/dfc86e0a8d78ec29954e4249f2ca1ac1b93afc33/sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java#L512) is causing some locale-related issues for us when passing `app_start_time` through our data pipeline. For example, one of our Android user's devices is set to Arabic, and the associated `app_start_time` value is `٢٠١٧-١٠-٠٩T١٣:٤١:٢٢Z`.

**Comment by bretthoerner** [comment]
Oops, thanks for the report. Does #515 look right to you?

**Comment by msrubino** [comment]
Sure does! Thanks for resolving that so quickly.

**Comment by bretthoerner** [comment]
Great, I'll push out a release tomorrow morning.
