### ISSUE TITLE
Check if files was removed from disk buffer

### ISSUE THREAD

**Issue by sbezkostnyi** [getsentry/sentry-java#518]
Currently, when `DiskBuffer` deletes files with buffered events, it calls `eventFile.delete()` without checking return value. If for some reason `delete()` fails, we would not know about it and event will stay on disk.

I suggest to check return value and log warning if file was not deleted.

**Comment by bretthoerner** [comment]
Good catch, I'll add that soon.

I'm curious: have you noticed any issues with this in practice or was this just something you saw when reading the code?

**Comment by sbezkostnyi** [comment]
Yeah, I've issues with disk buffer.

For some reason it stored events and failed to remove them later. I got events ~2 weeks old living in the buffer folder, while new events are rejected because buffer is full.

I was trying to understand what's gone wrong and found this. This may or may not be the cause of my issues, but it's better to warn about possible delete issues.

**Comment by bretthoerner** [comment]
Interesting. I've added some warnings here: https://github.com/getsentry/sentry-java/commit/38006e14ea43764d762e8bae231eb764cac8af9d

I'll push a release, please let me know if you find anything out in regards to `DiskBuffer`.

**Comment by sbezkostnyi** [comment]
Thanks.

I've cleaned disk buffer directory and now it works fine. I'll let you know if I find the reason of this issue.
