### ISSUE TITLE
Events are getting left in /tmp/sentry-events

### ISSUE THREAD

**Issue by vektor330** [getsentry/sentry-java#519]
We are using the version with the fix for #518 , but we still see events getting left in our /tmp/sentry-events folder. No warnings related to #518 are getting logged.

For example right now I see 5 events, 2 of them are 24+ hours old and 3 are from today.

What can we do to help you investigate this problem?

Let me start with some context:
* Linux 3.16.0-4-amd64 # 1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux
* Oracle Java 1.8.0_144
* Apache Tomcat/7.0.75 (Debian)
* Hosted Sentry 8.19.0

I've located one of the events left on the disk in our Elastic/Logstash/Kibana installation. I can see the event itself but no surrounding errors/warnings. It seems Sentry had no trouble around that time - it stored the event and just left it there.

The event itself did not make it into our Sentry yet.

**Comment by vektor330** [comment]
I've located one of the events left on the disk in our Elastic/Logstash/Kibana installation. I can see the event itself but no surrounding errors/warnings. It seems Sentry had no trouble around that time - it stored the event and just left it there.

**Comment by bretthoerner** [comment]
Is there any way you could enable `DEBUG` logging for the `io.sentry.buffer` package? Maybe to a different file or something?

I'm going to go through the code again now.

Out of curiosity though, what's your reason for using disk buffering? Network connectivity issues, hosted Sentry outages?

**Comment by bretthoerner** [comment]
So my only guess right now is that *some* kind of exception is being thrown repeatedly for these events.

How large are the files? You haven't seen any `ERROR` level logs that start with `"An exception occurred while sending the event to Sentry.`" and have an exception traceback?

**Comment by vektor330** [comment]
Why yes, we get quite a lot of those, that's actually the whole reason we started with this disk buffer 😄 Here is a sample stack trace:

```
io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server.
	io.sentry.connection.HttpConnection.doSend(HttpConnection.java:182) ~[sentry-1.5.3.jar:?]
	io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71) ~[sentry-1.5.3.jar:?]
	io.sentry.connection.BufferedConnection.send(BufferedConnection.java:102) ~[sentry-1.5.3.jar:?]
	io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171) [sentry-1.5.3.jar:?]
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.net.SocketTimeoutException: connect timed out
	java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_144]
	java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_144]
	java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_144]
	java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_144]
	java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_144]
	java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_144]
	sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673) ~[?:1.8.0_144]
	sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_144]
	sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_144]
	sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_144]
	sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_144]
	sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_144]
	sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_144]
	sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[?:1.8.0_144]
	sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[?:1.8.0_144]
	sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_144]
	sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153) ~[?:1.8.0_144]
	io.sentry.connection.HttpConnection.doSend(HttpConnection.java:153) ~[sentry-1.5.3.jar:?]
```

After a short search this is the only type of stacktrace I can see. There are several such events logged per day.

The file themselves are between 3 and 10 kB.

I will try adding the logging tomorrow. Thanks for your help!

**Comment by bretthoerner** [comment]
I wonder if there's an issue with the events that for some reason the Sentry server is rejecting them.

A timeout wouldn't make sense, but follow-on attempts to send are currently logged at `DEBUG` so at not to be so noisy. I'll be curious to see if you see periodic log spam from it attempting to resend those events and failing.

**Comment by vektor330** [comment]
That is consistent with what we are seeing. On manual inspection the event files resemble events we usually get a lot, but there can be some metadata that breaks upload to Sentry.

Out of curiosity, should I be looking into our Sentry as well? Would something get logged if uploading from this client failed?

**Comment by bretthoerner** [comment]
Hmm, I don't think so. It shouldn't be an unhandled (and thus logged) error in Sentry. Rather my guess is it's failing some part of validation and Sentry is returning some HTTP error to the client that we must be swallowing.

I'd definitely like to fix this one. 😊

**Comment by vektor330** [comment]
I've turned on the logging as suggested. I got this right now:

```
java.io.FileNotFoundException: /tmp/sentry-events/0c9c25ee-c754-472e-85e1-72dac13a90cc.sentry-event (No such file or directory) 
    	at java.io.FileInputStream.open0(Native Method) 
    	at java.io.FileInputStream.open(FileInputStream.java:195) 
    	at java.io.FileInputStream.<init>(FileInputStream.java:138) 
    	at io.sentry.buffer.DiskBuffer.fileToEvent(DiskBuffer.java:118) 
    	at io.sentry.buffer.DiskBuffer.getNextEvent(DiskBuffer.java:155) 
    	at io.sentry.buffer.DiskBuffer.access$000(DiskBuffer.java:19) 
    	at io.sentry.buffer.DiskBuffer$1.next(DiskBuffer.java:190) 
    	at io.sentry.buffer.DiskBuffer$1.next(DiskBuffer.java:179) 
    	at io.sentry.connection.BufferedConnection$Flusher.run(BufferedConnection.java:212) 
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
    	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) 
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) 
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
    	at java.lang.Thread.run(Thread.java:748)
```

The file really does not exist. How did Sentry figure out the file name?

Also, I can send you the 5 still hanging events privately if it helps you. Thanks!

**Comment by bretthoerner** [comment]
Ya that'd be great. brett@sentry.io

**Comment by bretthoerner** [comment]
@vektor330 For the ` java.io.FileNotFoundException` did you change the logging in a running JVM or was a brand new JVM instance?

**Comment by vektor330** [comment]
That was another instance without the logging changed, so I removed my comment.

**Comment by bretthoerner** [comment]
What version of `sentry-java` are you using?

**Comment by bretthoerner** [comment]
Oh, I guess 1.5.6?

**Comment by vektor330** [comment]
Indeed.

**Comment by bretthoerner** [comment]
OK, it looks like it is hanging the background thread that flushes buffered events here: https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/buffer/DiskBuffer.java#L116

For some reason the files are not what it expects, so it's hanging waiting for more bytes from the stream (even though it's backed by a file).

We flush/close when we write them, so that's shouldn't be it. Trying to figure out why else they wouldn't be "correct"...

**Comment by bretthoerner** [comment]
I think we need to refactor the marshalling code to convert to JSON earlier in the lifecycle so that we can write JSON to disk here.

**Comment by vektor330** [comment]
Ah, now I see a lot of DEBUG events - ELK is showing them, for some reason they did not get send in an email appender.

There is a bunch of `12 stored events are now in dir: /tmp/sentry-events` (number varies). There is even more `Discarding Event from offline storage: /tmp/sentry-events/2daca6a7-0305-4c5a-82f8-4593a80eca4a.sentry-event`. And every once in a while there is a `Flusher failed to send Event: 7fb199c4-b5a1-4083-b5b2-ffaa8118f995`, it has a stacktrace and it looks like this:

```
io.sentry.connection.ConnectionException: {"error":"Event dropped due to filter"}
	io.sentry.connection.HttpConnection.doSend(HttpConnection.java:182) ~[sentry-1.5.6.jar:?]
	io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71) ~[sentry-1.5.6.jar:?]
	io.sentry.connection.BufferedConnection.send(BufferedConnection.java:102) ~[sentry-1.5.6.jar:?]
	io.sentry.connection.BufferedConnection$Flusher.run(BufferedConnection.java:231) [sentry-1.5.6.jar:?]
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://sentry.realpad.eu/api/3/store/
	sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[?:1.8.0_144]
	sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_144]
	sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_144]
	io.sentry.connection.HttpConnection.doSend(HttpConnection.java:157) ~[sentry-1.5.6.jar:?]
```

**Comment by bretthoerner** [comment]
Oh, very helpful. I wonder if my serialization issues were a red herring because our systems are very different?

Can you check the "Inbound Filters" section of your project settings in Sentry and tell me which are enabled?

Either way this seems like something that the buffer code needs to handle (it should discard events that are rejected by filters). I'll see what I can do there.

**Comment by vektor330** [comment]
<img width="1011" alt="screen shot 2017-10-19 at 15 31 21" src="https://user-images.githubusercontent.com/377878/31773300-9800bee6-b4e2-11e7-82a8-5aeea1943aeb.png">

Looks like this. We do actually seem to be filtering out a lot of events, but the only filter turned on seems to be **Filter out known web crawlers**.

**Comment by bretthoerner** [comment]
And you're using a Servlet (thus sending the HTTP metadata) right? Something must be triggering the crawler filter.

**Comment by vektor330** [comment]
We are using Tomcat and yes you can use the word "Servlet" in the connection to our application, but could you tell me how to definitely answer yes or no?  I presume the files I've sent you are exactly the one that can't be sent, thus the ones rejected by the filter, therefore you could probably find the HTTP metadata inside (or the lack of thereof)?

Also I have no strong opinion about the filters setup at the moment ("would probably enable all of them"), so I can probably disable the only one that is active now and wait if we observe the problem again?

In any case I agree that the buffer should detect "Sentry does not want this event due to a filter" and just delete it.

**Comment by bretthoerner** [comment]
Well, I'm having trouble unserializing those events on my machine. If you events in Sentry show a 'Headers' section then you're sending HTTP info.

Like you said, the best thing to do may be to disable the crawler filter on Sentry, then restart one of the application with events still on disk and wait a few minutes to see if they are sent (and deleted).

I'll work on fixing the SDK too.

**Comment by vektor330** [comment]
So I've disabled the filter, restarted the application and the events have disappeared from `/tmp`! Can't really confirm if they made it to Sentry - there is nothing "new" or extraordinary. If they were older they probably were sorted somewhere in the past or among other events (just with specific headers).

So far so good 😃

**Comment by bretthoerner** [comment]
Great! They should only be deleted if it received a `200 OK` from Sentry.

**Comment by bretthoerner** [comment]
Releasing 1.6.1 to delete filtered events.
