### ISSUE TITLE
Local Host

### ISSUE THREAD

**Issue by arielesc** [getsentry/sentry-java#524]
Is there an option to make a local host instead of using the dsn? 
Thanks

**Comment by bretthoerner** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by arielesc** [comment]
I mean i want to run the Sentry on my local, instead of the web.

**Comment by bretthoerner** [comment]
Oh, yeah you'll have to go through the installation steps here: https://docs.sentry.io/server/installation/

It will require a lot of work though, the SaaS version is recommended.
