### ISSUE TITLE
More Details

### ISSUE THREAD

**Issue by arielesc** [getsentry/sentry-java#525]
Hi,
in the Sentry their is a exception example with a lot of details, when i create a issue i cant see the same details as the example, and all i see is this:
![image](https://user-images.githubusercontent.com/33019286/31929569-45209f90-b8a5-11e7-8e1a-22bb30e3f0fe.png)

is that all the information i can get? or their is a way to see more (as the example)?

Thanks

**Comment by bretthoerner** [comment]
You can provide things like additional `tags`, `extra data`, and the current user using the examples shown here: https://docs.sentry.io/clients/java/usage/

And if you are using Spring (or another servlet based application) and there is an active web request it should attach HTTP information (such as headers and more) if you've configured it properly: https://docs.sentry.io/clients/java/modules/spring/

**Comment by arielesc** [comment]
under "Capture an Error"?

**Comment by bretthoerner** [comment]
Yep, like these:

```java
        Sentry.getContext().recordBreadcrumb(
            new BreadcrumbBuilder().setMessage("User made an action").build()
        );

        // Set the user in the current context.
        Sentry.getContext().setUser(
            new UserBuilder().setEmail("hello@sentry.io").build()
        );

        // Add extra data to future events in this context.
        Sentry.getContext().addExtra("extra", "thing");

        // Add an additional tag to future events in this context.
        Sentry.getContext().addTag("tagName", "tagValue");
```

**Comment by arielesc** [comment]
and where should i put my exception error on this code?
thanks

**Comment by bretthoerner** [comment]
That stores the information in the current context, so that when future exceptions are sent the information is attached.

For example, you might set the current user and some useful tags at the very start of a request. Then, if (and only if) an exception occurred in the future it would attach that extra data with the error automatically.

**Comment by arielesc** [comment]
Great thanks!

**Comment by arielesc** [comment]
Can you explain please the use of ADDITIONAL DATA field? 
// Add extra data to future events in this context.
        Sentry.getContext().addExtra("extra", "thing");

**Comment by bretthoerner** [comment]
It lets you attach any kind of Java object to be included at the bottom of the event page. Like if you had a list or hash if information that would be helpful to see when an error occurred.

**Comment by arielesc** [comment]
Cool, thanks

**Comment by arielesc** [comment]
What is the command that i need for add details to my User? 
Sentry.getContext().setUser(new UserBuilder().setEmail("abc@gmail.com").build());
so here i will get the email, but how can i do for adding the user name for example?
Thanks.

**Comment by arielesc** [comment]
How can i get the Body,Cookies,Headers,Environment? cant find the command line that make it.

**Comment by bretthoerner** [comment]
If you're using Spring you should check these out:

https://docs.sentry.io/clients/java/modules/spring/
https://github.com/getsentry/examples/tree/master/java/spring-boot
