### ISSUE TITLE
Additional Data

### ISSUE THREAD

**Issue by arielesc** [getsentry/sentry-java#526]
Hi,
as i understand from the example, the addidonal data is for the object that makes "problems":
![image](https://user-images.githubusercontent.com/33019286/31953309-89601186-b8eb-11e7-9fac-ea76cd938652.png)

how can i make it happen automatically (as the example)? for that object in my code.
Thanks.

**Comment by bretthoerner** [comment]
"Additional data" isn't automatic, you have to manually decide which items to send along with events, because there's no way for us to know which objects are important and which are not.
