### ISSUE TITLE
Add a web-fragment.xml

### ISSUE THREAD

**Issue by markus-s24** [getsentry/sentry-java#538]
To reduce classpath scanning in web containers, it would be nice, if sentry has a web-fragment.xml. This way 'metadata-complete="true"' can be used in combination 'absolute-ordering' in the 'web.xml' to reduce classpath scanning to the required minimum.

**Comment by bretthoerner** [comment]
Interesting, I hadn't heard of this. I'll have to do some testing on my own -- but this doesn't have any downsides? Do you mind reviewing #539 for me?
