### ISSUE TITLE
Allow configuring SentryJsonGenerator recursion limits etc

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#543]
These should be configurable somehow.

https://github.com/getsentry/sentry-java/blob/027544f8a4063740294bde23073ea409d38ed5e1/sentry/src/main/java/io/sentry/marshaller/json/SentryJsonGenerator.java#L27-L31

**Comment by kwladyka** [comment]
PS It would be great to make right sizes by automate. Data are cut, so I will have to set here the biggest possible values. There is no info about limits also. I use old ver. all the time, because of this issue. Please fix it and make it more clever. Assumption is when i push some data I really want to see this data without any cut. So I don't want limit it by nesting or whatever. Just cut it when it is not fit after max bytes. It is my problem as developer to make data smaller when I am sending to Sentry. Send only what is needed. Cut data by automate like it looks now miss the point of debug. It doesn't help in any way at that moment. It makes Sentry useless for me.

Do you have any plan to change it?

**Comment by bretthoerner** [comment]
I plan to, just haven't had time. I'll try to give it another look.

Going by byte size does make sense.

**Comment by bretthoerner** [comment]
@kwladyka Out of curiosity, which of these you most often? Nesting? String length? Or do you actually need to inspect each value in huge lists/maps?

Looking at the code, it's a shame that there's seemingly no byte count on Jackson's `JsonGenerator`. It seems difficult for me to be able to track exactly how many bytes have been written so far. I would wrap it, but it seems like there isn't a clean single entry point for all writes, ugh.

**Comment by kwladyka** [comment]
It is half a year after report this issue. I guess there are no plans to do it. Why? Am I miss something?

**Comment by bretthoerner** [comment]
> Why?

Just lack of time.

You could override these and make a custom build: https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/marshaller/json/SentryJsonGenerator.java#L27-L30

Or PRs are welcome.

**Comment by kwladyka** [comment]
I wish I could do PR, but I am Clojure developer. Probably my Java solution would be average.

Should it include this possibility of settings?
`https://...@sentry.io/204682?buffer.dir=./sentry-buffer&max_length_list=100&max_size_map=500....`

Any suggestion how to implement solution for this issue in this Java module?

**Comment by bretthoerner** [comment]
The main issues are looking up those configuration values at startup and passing them all the way down to the `SentryJsonGenerator`, and then the fact that a value too high may mean your events are rejected from Sentry itself.

I've considered a hacky/experiment solution where we just did something like,

`private static final int MAX_LENGTH_LIST = Lookup.lookup('experimental.list.max-length');`

With a fallback to the default value, of course. But that would just look up the configuration in the `SentryJsonGenerator` itself which is definitely a gross hack but would allow you and others an escape hatch (that we may not maintain) for now...

**Comment by ameshkov** [comment]
You don't need a custom build to override these. Just do something like this.

```java
    /**
     * Our own sentry client factory implementation.
     * The purpose is to configure {@link SentryJsonGenerator}.
     */
    private static class CustomAndroidSentryClientFactory extends AndroidSentryClientFactory {

        /**
         * Construct an AndroidSentryClientFactory using the specified Android Context.
         *
         * @param ctx Android Context.
         */
        CustomAndroidSentryClientFactory(Context ctx) {
            super(ctx);
        }

        @Override
        protected JsonMarshaller createJsonMarshaller(int maxMessageLength) {
            return new CustomJsonMarshaller(maxMessageLength);
        }
    }

    /**
     * A marshaller implementation that configures {@link SentryJsonGenerator}.
     */
    private static class CustomJsonMarshaller extends JsonMarshaller {

        private final JsonFactory jsonFactory = new JsonFactory();

        CustomJsonMarshaller(int maxMessageLength) {
            super(maxMessageLength);
        }

        @Override
        protected JsonGenerator createJsonGenerator(OutputStream destination) throws IOException {
            SentryJsonGenerator sentryJsonGenerator = new SentryJsonGenerator(jsonFactory.createGenerator(destination));
            sentryJsonGenerator.setMaxLengthString(MAX_STRING_LENGTH);
            return sentryJsonGenerator;
        }
    }
```

**Comment by kwladyka** [comment]
@ameshkov thank you, but unfortunately I will have to also do custom build to include Java custom build for https://github.com/getsentry/sentry-clj . It sounds like a lot of overhead.

That is why I wish to see solution in official repository.

**Comment by bretthoerner** [comment]
@ameshkov makes a good point. `sentry-clj` even uses its own factory to override the JSON generator:

https://github.com/getsentry/sentry-clj/blob/64e3cc8b5f9aef053a271d14345ec2f785a2c3bb/src/sentry_clj/internal.clj#L23-L28

Can't you call `setMaxLengthString` (and others) from Clojure and avoid having to deal with Java at all?

**Comment by kwladyka** [comment]
hah I love this comment https://github.com/getsentry/sentry-clj/blob/64e3cc8b5f9aef053a271d14345ec2f785a2c3bb/src/sentry_clj/internal.clj#L2+L4

So I have to get from `sentry-clj.internal/factory` the `JsonGenerator`. Use on it `setMaxLengthString`. How to set this value on it? I don't see function to set something on `JsonGenerator` in `factory`.

https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java#L110
What is this value vs https://github.com/getsentry/sentry-java/blob/f9f04c29b2f8267183ed621b7474a0fd76da67c2/sentry/src/main/java/io/sentry/marshaller/json/SentryJsonGenerator.java#L27-L30
?

What is true max for Sentry?

**Comment by bretthoerner** [comment]
It's one level deeper, so you'll need another proxy:

https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java#L183

https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/marshaller/json/SentryJsonGenerator.java#L202-L217

Sentry has no maximum at this level or I would have just changed the values. The problem is Sentry will reject at 100k gzipped JSON and I found no clean/easy way to track the size of the generated object in Jackson. It's very customer dependent how those numbers will effect the event body.

**Comment by lobsterkatie** [comment]
Reviving this thread as the question of max depth has come up again with respect to [the RN SDK](https://github.com/getsentry/sentry-react-native/issues/713). In that case, the creation of the Android client isn't exposed, so @ameshkov's solution unfortunately won't work.

Can we make `maxNesting` (etc) configurable the same way `maxMessageLength` is [here](https://github.com/getsentry/sentry-java/blob/4a7e5b092dbfc90af78962fd4e3c33e34c76c7ea/sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java#L142-L149)? Then work can be done on the RN SDK side to allow its config to tap into these options.

**Comment by frankyjuang** [comment]
Any news?

**Comment by kwladyka** [comment]
I am afraid nothing changed.

**Comment by lobsterkatie** [comment]
If you're landing here because of the Java SDK itself, it's true, there's been no change. But if you landed here by way of https://github.com/getsentry/sentry-react-native/issues/713, then you should be good to go, as the RN SDK will no longer rely on this one.

**Comment by jokefaker** [comment]
@bretthoerner Hi, I have a question. Will the sentry server side cut the text? I changed maxLengthString and maxMessageLength to a big number，but the text in sentry is still cut
PS. I print the gzipped json string to a file, its just 17kb

**Comment by maciejwalkowiak** [comment]
The new Java SDK v3 uses GSON under the hood for JSON serialization making this ticket not valid anymore as we rely on GSON defaults.
