### ISSUE TITLE
New releases are not announced on Github anymore

### ISSUE THREAD

**Issue by tajchert** [getsentry/sentry-java#544]
There are some version that never made to [repo release versions](https://github.com/getsentry/sentry-java/releases) and are available (+public via docs on docs.sentry.io).
I would love to see keeping up with github releases as this is very easy/fast way to check new version changelog.

Versions reported by Maven:
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.sentry%22%20AND%20a%3A%22sentry-android%22

**Comment by bretthoerner** [comment]
Oops, I just assumed people used something like this (or the Gradle, SBT, lein equivalents): http://www.mojohaus.org/versions-maven-plugin/display-dependency-updates-mojo.html

But I should be able to publish to Github releases easily enough, too.

**Comment by tajchert** [comment]
No problem, just please keep one channel of publishing releases (with changelog if possible) - I assumed Github is that place so I was a bit surprised to see 1.6.3 already public in docs.

**Comment by fprochazka** [comment]
Github releases are great, you can subscribe to them via RSS - please keep using them :) thank you!
