### ISSUE TITLE
Retain breadcrumbs even if Android kill app process

### ISSUE THREAD

**Issue by piotrek-chmielowski** [getsentry/sentry-java#547]
I have a following scenario:
1. User uses my app
2. User clicks home button so the app goes foreground
3. Android kills app's process in order to free memory
4. User opens the app again, Android restores its state
5. Crash happens

In this scenario I have full stack trace and error info on Sentry, however I do not know what happened before app was killed and reopened because I have only breadcrumbs from the beginning of current app process. 

Is it possible to force breadcrumbs to be retained during the process death?

**Comment by bretthoerner** [comment]
Good idea, I honestly never considered it. We should probably attempt to store all context information on Android.

**Comment by romtsn** [comment]
should be pretty straightforward to implement, once ANRv2 lands

**Comment by dharmita1990** [comment]
Any update on this?

**Comment by markushi** [comment]
Ideally we can just restore the breadcrumbs on app-start
