### ISSUE TITLE
ShutdownHook leak

### ISSUE THREAD

**Issue by obourgain** [getsentry/sentry-java#548]
Hello, 
Our application is using the sentry-java library and we noticed that we have a very large amount of shutdown hooks registered, as can be seen on the screenshot below, taken while analysing a heapdump with Eclipse MAT.

Sentry was not the reason why we were looking at the heapdump, but this may still end up causing issues.

I am not sure why so many AsyncConnection were created, it may be related to the use of Spring's [RefreshScope](https://cloud.spring.io/spring-cloud-static/docs/1.0.x/spring-cloud.html#_refresh_scope) but I could not reproduce yet.

I noticed that the code in AsyncConnection in not removing the shutdownhook on close(), but looking at the history this is intentional (https://github.com/getsentry/sentry-java/issues/167).

Instead of leaking the hook, the removal of the hook may be done in a try catch.
An alternative workaround is to disable the graceful shutdown.

What do you think about this ? If you are ok with the try-catch solution, I can contribute the code.

![sentry-shutdown-hook-threads](https://user-images.githubusercontent.com/975826/35333955-f5711dd0-0110-11e8-8175-97cb38710acf.png)

**Comment by bretthoerner** [comment]
I'm curious what you mean by the `try/catch` solution, maybe code would help there?

But I think the underlying issue of why so many `AsyncConnections` were created is something we should figure out. Each shutdown hook is responsible for closing and flushing its own instance (there should really only be one). If something like Spring is reloading Sentry then it'd be good if we could clean up *everything* each time it does that?

**Comment by obourgain** [comment]
Excuse me for not being clear. I was thinking of something like this for AsyncConnection.close()
```
public void close() throws IOException {
        if (gracefulShutdown) {
            try {
                Runtime.getRuntime().removeShutdownHook(shutDownHook);
            } catch (IllegalStateException e) {
                if (e.getMessage().equals("Shutdown in progress")) {
                    // ignore
                } else {
                    throw e;
                }
            }
            shutDownHook.enabled = false;
        }

        doClose();
    }
```

That would avoid the leak when several AsyncConnections are created while still allowing the hook to flush pending events.

I am not sure that Spring is responsible here, but AFAIK with Spring Boot, it took over the logging system, and we already hit an [issue](https://github.com/spring-cloud/spring-cloud-commons/issues/260) with it.

**Comment by bretthoerner** [comment]
Ahhh, yeah that seems like something that'd be harmless to add to me. Go ahead and make a PR if you don't mind?

**Comment by obourgain** [comment]
I opened https://github.com/getsentry/sentry-java/pull/550
I will try to find more tiime to investigate this issue to find an detailed explanation.

**Comment by bretthoerner** [comment]
Merged and released.
