### ISSUE TITLE
Initializing sentry in static context causes it to swallow Exceptions

### ISSUE THREAD

**Issue by domisum** [getsentry/sentry-java#552]
When using sentry with the logback appender it hides exceptions from System.out/System.err

I created a project that demonstrates this: https://github.com/domisum/SentrySwallowUncaughtException

I am aware that sentry isn't configured with a DSN in the project provided, but I just want to demonstrate that exceptions thrown are not visible in the console. I would expect sentry to log the exception and still forward it to the out/error stream.

**Comment by bretthoerner** [comment]
Thanks, good catch. I changed it to do what the JVM does by default: https://github.com/getsentry/sentry-java/commit/11240d8cfd53f129b85a4a5466c83ef42f2502bb

Going to do a bugfix release as soon as Sonatype OSS is back up.
