### ISSUE TITLE
Proguard UUID file is stored at wrong path

### ISSUE THREAD

**Issue by irgendeinich** [getsentry/sentry-java#554]
I integrated Sentry into our application and we use a non default name for our main app module.
As you can see here https://github.com/getsentry/sentry-java/blob/master/sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L135 , Sentry is hardcoded to always use `app` for the directory to put the UUID file in. 

This causes the app to log `Proguard UUIDs file not found.` when running, and stacktraces to not get deobfuscated.

The `persistSentryProguardUuidsFor` task should use the correct name when determining where to put `sentry-debug-meta.properties`.

**Comment by bretthoerner** [comment]
Hmm, any idea how we can dynamically get the main module name?

**Comment by irgendeinich** [comment]
I'd assume that `project.name` should return the name of the module you are currently building.
So if I'd run `:myapp:assembleRelease` `project.name` should be `myapp`.

**Comment by bretthoerner** [comment]
Thanks @irgendeinich, do you mind reviewing (or even trying) #555 ?

If you `./gradlew install` you can use `io.sentry:sentry-android-gradle-plugin:1.6.8-SNAPSHOT` locally.

**Comment by irgendeinich** [comment]
Just tried it out, the file is now created at the right spot. 👍 
Thanks for the quick response.

**Comment by bretthoerner** [comment]
Awesome, thanks for trying it out!
