### ISSUE TITLE
MDC context not set on child threads

### ISSUE THREAD

**Issue by markwoon** [getsentry/sentry-java#557]
When sentry performs it's own logging, it is does not appear to be passing the MDC context into it's threads.

See https://logback.qos.ch/manual/mdc.html#managedThreads for what should happen.

**Comment by bretthoerner** [comment]
Can you give an example of how this presents itself to you as a user? I'm having a hard time understanding and I think an event/log example would help clarify the issue for me. Thanks!

**Comment by markwoon** [comment]
We direct logging info into different files based on a MDC key.  The relevant config looks like:

```
<appender name="logfile" class="ch.qos.logback.classic.sift.SiftingAppender">
    <discriminator>
      <key>logKey</key>
      <defaultValue>default</defaultValue>
    </discriminator>
    <sift>
      <appender name="FILE-${logKey}" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <File>@LOG_DIR@/${logKey}.log</File>
        <encoder>
          <pattern>%d{ISO8601} %-5p [%c] : %m%n</pattern>
        </encoder>
      </appender>
    </sift>
  </appender>
```

I'm seeing Sentry's log statements showing up in the `default` log file but I'm expecting it to show up in another one.

**Comment by bretthoerner** [comment]
Thanks, that makes more sense. Do you mind reviewing #558 @markwoon?

**Comment by markwoon** [comment]
@bretthoerner That makes sense to me.
