### ISSUE TITLE
Gradle incompatibilities

### ISSUE THREAD

**Issue by RegoJ** [getsentry/sentry-java#565]
After adding the new Sentry gradle integration, my build fails with error: "could not find com.android.tools.build:gradle:2.3.3; Required by: project:app>io.sentry:sentry-android-gradle-plugin:1.7.1"

I'm essentially looking to upload my ProGuard Mapping files.

**Comment by bretthoerner** [comment]
Very odd, what version did you upgrade from? Are you using Gradle from the command line or via Android Studio? And which version?

**Comment by bretthoerner** [comment]
Oh, can you try setting up your `build.gradle` like our example app? https://github.com/getsentry/examples/blob/6bd3770f7e0b704c306683b83861d28a00ad349e/android/build.gradle

**Comment by mariovp** [comment]
I had the same problem. I solved it by including the line `classpath 'io.sentry:sentry-android-gradle-plugin:1.7.2'` in the project's `build.gradle` dependencies, the error happens when you put it in the module's `build.gradle`. Hope it helps @RegoJ .

Example:
`project/build.gradle`
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'io.sentry:sentry-android-gradle-plugin:1.7.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

**Comment by bretthoerner** [comment]
Thanks @mariovp!
