### ISSUE TITLE
Integration of android.util.log

### ISSUE THREAD

**Issue by gabek** [getsentry/sentry-java#569]
I know sentry-java has out of the box integrations with a few logging options, but what is the suggested method for using Android's standard logging?

I could write a wrapper, of course, but it seems like this is probably a solved problem, though I couldn't find any discussion about it in the Github issues.

Thanks for your suggestions!

**Comment by bretthoerner** [comment]
My understanding is that Android logging is disabled in release builds. Are you using a custom implementation or maybe I'm missing something?

**Comment by gabek** [comment]
Nothing custom, just standard Android logging.  That would make sense why Sentry wouldn't be able to use it if Android logging is disabled in release builds.  I hadn't seen any reference to that other than the ability to strip logging via Proguard.

**Comment by bretthoerner** [comment]
Hmm, I'm having trouble finding it now too. I guess it wasn't in every release build, but I could have sworn the environment that runs APKs from the store just has a no-op logging stub (so as not to fill disk or whatever).

I did see "Turn off logging and debugging" in the "Configuring Your Application for Release" section here: https://developer.android.com/studio/publish/preparing.html

I guess my feeling on Android was that most people were doing `Sentry.capture(exception)` themselves: https://docs.sentry.io/clients/java/modules/android/

But I do understand the desire/issue. I don't think Android logging is very extensible (like SLF4J) though. I think it'd need to be a wrapper that calls out to logging AND sends to Sentry. :frowning:

**Comment by gabek** [comment]
Got it, that's what I thought.  Thanks for the sanity check!
