### ISSUE TITLE
Document the official way to disable Sentry (using a null DSN)

### ISSUE THREAD

**Issue by mcomella** [getsentry/sentry-java#574]
We provide users the option to disable uploading of analytics data and Sentry is included in that. It'd be great if there is an official mechanism for disabling upload and recording (i.e. don't buffer to disk when operations happen while Sentry is disabled).

Currently, we're using a workaround where we pass in a null DSN if Sentry is disabled:
```kotlin
        // If the DSN is null, Sentry will attempt to find a DSN from other sources,
        // it'll fail, and it won't be able to upload.
        //
        // The BuildConfig value is populated from a file at compile time.
        // If the file did not exist, the value will be null.
        val sentryDsn = if (isEnabled) BuildConfig.SENTRY_DSN else null

        // Unfortunately, Sentry doesn't make it easy to disable upload. However,
        // in the current implementation, each time `init` is called, it will overwrite
        // the stored client. If we give it a client with an invalid DSN, it'll have
        // the effect of disabling the client.
        Sentry.init(sentryDsn, AndroidSentryClientFactory(context.applicationContext))
```

But I'm concerned this solution might break in future releases.

**Comment by bretthoerner** [comment]
The `null` DSN is officially supported. I could probably document that better.

When a `null` DSN is used (the default, if you were to just start calling Sentry methods like `Sentry.capture(e)`) a no-op connection is used: https://github.com/getsentry/sentry-java/blob/c856b762047fe00115000a8d76b027e5157be950/sentry/src/main/java/io/sentry/dsn/Dsn.java#L21

This won't buffer to disk, attempt to connect, or anything.

**Comment by mcomella** [comment]
> The null DSN is officially supported. I could probably document that better.

I changed the issue title accordingly: thanks! :)

**Comment by mcomella** [comment]
@bretthoerner If I wanted to change enabled/disabled state at runtime, is it okay to call `Sentry.init` more than once?

**Comment by bretthoerner** [comment]
Yeah, each `init` call with replace the statically stored `SentryClient`, so that should work fine.

**Comment by bruno-garcia** [comment]
It's documented here: https://docs.sentry.io/development/sdk-dev/overview/#usage-for-end-users

> If an empty DSN is passed, you should treat it as valid option which signifies disabling the SDK.

**Comment by xr0master** [comment]
Hey. I have to reopen it.
If we set DSN as null, then an integrations plugin doesn't work. ngSentry doesn't exist:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app 
[$injector:nomod] Module 'ngSentry' is not available! You either misspelled the module name or forgot to load it
```

**Comment by blacelle** [comment]
Unclear in `noop://` is kind of supported since Sentry 3.X

**Comment by marandaneto** [comment]
@blacelle pass an empty DSN `""` to disable the SDK on Sentry 3.x

**Comment by jenni** [comment]
My app. fails to start when passing `sentry.dsn=${SENTRY_DSN:""}`, using 3.x
```
Failed to instantiate [io.sentry.IHub]: Factory method 'sentryHub' threw exception; nested exception is io.sentry.InvalidDsnException: java.net.URISyntaxException: Illegal character in path at index 0: ""
```
how to disable it locally?

**Comment by bruno-garcia** [comment]
@jenni this issue is closed.
Seems like you found a bug, I've created an issue for it;

https://github.com/getsentry/sentry-java/issues/1132
