### ISSUE TITLE
Automatically add IP Address to user context on Android

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#582]
Apparently we do this on iOS, so we should do it on Android also: https://github.com/getsentry/sentry-java/blob/9e11a3a3c5d099acc7a9ee28304c8f89257f6cdf/sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java#L65

**Comment by bruno-garcia** [comment]
We could use [ANDROID_ID](https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID) to set the User by default.

**Comment by bruno-garcia** [comment]
Fixed: https://github.com/getsentry/sentry-java/blob/9f8212144986e57591db89742f305160458ff511/sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java#L67

**Comment by momadthenomad** [comment]
The ticket said **IP Address**, not sure how we ended up with **Android ID** instead. 😕

**Comment by bruno-garcia** [comment]
@momadthenomad the IP address should be anyway added by the Server so I'm not sure if it makes sense.
