### ISSUE TITLE
Android O/P: Crashes are not getting uploaded

### ISSUE THREAD

**Issue by pocmo** [getsentry/sentry-java#583]
I'm using a Pixel XL device with Android P Beta (previously Android O / 8.1) and crashes do not seem to get uploaded most of the time.

If I crash the app multiple times Android starts to show a "{app} keeps stopping" dialog and in this situation the crash gets uploaded just fine. In all other cases the app disappears after the crash and nothing appears in the web interface. I noticed that Android keeps the app's process alive while the dialog is shown. So it seems like in the other case the process gets killed too fast, maybe?

I tried another device running Android 5.1.1 and everything just worked normally with the exact same build of the app.

**Comment by pocmo** [comment]
I registered my own UncaughtExceptionHandler before initializing Sentry so that it sits between Sentry's implementation and the system. If I delay calling the system's handler (which will kill the process) by just calling Thread.sleep(3000) then those crashes appear on the web interface. So I assume this is caused by some race where Android kills the process before Sentry (asynchronously?) is done.

**Comment by pocmo** [comment]
I do not set any. It's just:

```Kotlin
        val factory = AndroidSentryClientFactory(context)
        Sentry.init(sentryDsn, factory)
```

We (Mozilla) are using a private Sentry instance. However I was able to reproduce the same issue using a free account on sentry.io.

Looking at HttpConnection I noticed that the sentry client does not read anything from the http connection. I wonder if that's the reason why the request is not blocking the current thread and therefore the process dies before the request completes?

**Comment by bretthoerner** [comment]
We do get and set the response code and other headers. The Sentry server doesn't do anything as smart as pre-sending response headers before the event has been processed.

By default Sentry's graceful shutdown should be on, but maybe Android has weird rules about when it's respected? It's interesting that your sleep worked...

Have you had a chance to run with DEBUG logging (not sure if Sentry's non-Android SLF4J logs will be emitted by default with an implementation though)? I'll try to test this out myself also but it may be a bit.

**Comment by bretthoerner** [comment]
Oh, I'm also curious if buffering is working, which should be on by default in Android. Events should send from the disk buffer the next time the app launches (after a minute delay, or so, if I recall correctly). Do you notice any files in the app's cache directory under `sentry-buffered-events`?

**Comment by pocmo** [comment]
> We do get and set the response code and other headers. 

I only see the response code and headers being read in the case of an IOException happening:
https://github.com/getsentry/sentry-java/blob/5421f49272c8074fa54c5e501cbed9aed76b684c/sentry/src/main/java/io/sentry/connection/HttpConnection.java#L167

> Have you had a chance to run with DEBUG logging

I couldn't find any option to enable debug logging on the Sentry singleton or SentryClient object?

> Oh, I'm also curious if buffering is working, which should be on by default in Android. Events should send from the disk buffer the next time the app launches (after a minute delay, or so, if I recall correctly). Do you notice any files in the app's cache directory under sentry-buffered-events?

I think occasionally I saw that working; but most of the time the crashes were just lost. I can try to debug this more and look into the cache directory.

**Comment by bretthoerner** [comment]
> I only see the response code and headers being read in the case of an IOException

Oh, good point. It's probably worth changing that if only to rule this out.

> I couldn't find any option to enable debug logging on the Sentry singleton or SentryClient object?

Yeah sorry, it's not that simple. They use SLF4J and "just" need a working implementation to exist and be configured. :(

Maybe this: https://www.slf4j.org/android/ ?

> I think occasionally I saw that working; but most of the time the crashes were just lost. I can try to debug this more and look into the cache directory.

We add to the buffer before any send, and only discard on success or some exceptions. Now I'm more curious about whether some exception is happening and being missed in the logs?

https://github.com/getsentry/sentry-java/blob/9e11a3a3c5d099acc7a9ee28304c8f89257f6cdf/sentry/src/main/java/io/sentry/connection/BufferedConnection.java#L188

**Comment by pocmo** [comment]
The cache directory seems to only contain none-sentry things in this situation:

```Bash
$ adb shell run-as org.mozilla.focus.debug ls /data/data/org.mozilla.focus.debug/cache
WebView
org.chromium.android_webview
```

**Comment by bretthoerner** [comment]
Very odd, unless you're overriding something it should be creating a directory on `init`.

https://github.com/getsentry/sentry-java/blob/master/sentry-android/src/main/java/io/sentry/android/AndroidSentryClientFactory.java#L114

**Comment by bretthoerner** [comment]
Ah, I see your code now:

https://github.com/mozilla-mobile/focus-android/blob/c169cf6b186b9ddb93de970368dc112a29a621d9/app/src/main/java/org/mozilla/focus/telemetry/SentryWrapper.kt

So, one random thought: since it looks like you're *only* using Sentry for crashes (?) and not for other exception logging, you could try setting Sentry's `async=false`.

**Comment by pocmo** [comment]
Managed to get slf4j working and see this in the log:

```
     BufferedConnection  E  Exception occurred while attempting to add Event to buffer:
                         E  java.lang.NullPointerException: Attempt to get length of null array
                         E      at io.sentry.buffer.DiskBuffer.getNumStoredEvents(DiskBuffer.java:202)
                         E      at io.sentry.buffer.DiskBuffer.add(DiskBuffer.java:62)
                         E      at io.sentry.connection.BufferedConnection$2.send(BufferedConnection.java:188)
                         E      at io.sentry.SentryClient.sendEvent(SentryClient.java:135)
                         E      at io.sentry.SentryClient.sendEvent(SentryClient.java:176)
                         E      at io.sentry.Sentry.capture(Sentry.java:177)
                         E      at io.sentry.SentryUncaughtExceptionHandler.uncaughtException(SentryUncaughtExceptionHandler.java:55)
                         E      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                         E      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                         E      at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
```

**Comment by bretthoerner** [comment]
See that would only happen if the cache dir create failed. Is anything logged before that?

**Comment by bretthoerner** [comment]
But I should still handle that branch. Just really curious why buffering isn't working right since that would be useful for you too.

**Comment by bretthoerner** [comment]
What version of `sentry-android` are you using?

**Comment by pocmo** [comment]
> 'io.sentry:sentry-android:1.7.4'

**Comment by pocmo** [comment]
With async=false set I see:

```
                         E  android.os.NetworkOnMainThreadException
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1509)
                         E      at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
                         E      at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
                         E      at java.net.InetAddress.getAllByName(InetAddress.java:1154)
                         E      at com.android.okhttp.Dns$1.lookup(Dns.java:39)
                         E      at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
                         E      at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
                         E      at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
                         E      at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
                         E      at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                         E      at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                         E      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                         E      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                         E      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                         E      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
                         E      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                         E      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
                         E      at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:168)
                         E      at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:76)
                         E      at io.sentry.connection.BufferedConnection.send(BufferedConnection.java:105)
                         E      at io.sentry.connection.BufferedConnection$2.send(BufferedConnection.java:193)
                         E      at io.sentry.SentryClient.sendEvent(SentryClient.java:135)
                         E      at io.sentry.SentryClient.sendEvent(SentryClient.java:176)
                         E      at io.sentry.Sentry.capture(Sentry.java:177)
                         E      at io.sentry.SentryUncaughtExceptionHandler.uncaughtException(SentryUncaughtExceptionHandler.java:55)
                         E      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                         E      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                         E      at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
                Process  I  Sending signal. PID: 17793 SIG: 9
```

I do not have StrictMode enabled but after disabling it explicitly the upload seems to work:

```
        val policy = StrictMode.ThreadPolicy.Builder().permitAll().build()
        StrictMode.setThreadPolicy(policy)
```

I still see the NullPointerException (and nothing related on startup etc.).

**Comment by bretthoerner** [comment]
As for the buffer exception: we do catch and simply log that exception, then continue on to the real `send`. It shouldn't be effecting you but I'd still like to figure out why the default buffer dir isn't working for you. It is: `bufferDir = new File(ctx.getCacheDir().getAbsolutePath(), DEFAULT_BUFFER_DIR);`

Ah ya, I forgot about the main thread bit. So we need to use async on Android... hm.

**Comment by bretthoerner** [comment]
With logging on DEBUG can you share all `io.sentry.*` related logs maybe?

**Comment by pocmo** [comment]
Oh!

The problem with the cache directory is caused by Focus: We clean up the cache directory to avoid leaving any traces from the last session behind. After disabling this part of the code I see the buffer folder (and there's no exception anymore). And yes, with that I see the crash uploaded later on the next app start. Sorry for derailing this.

The initial problem remains though (although it's not as critical anymore): The process seems to die before the upload can run/complete.

**Comment by bretthoerner** [comment]
Ahhh, interesting. Can you whitelist the Sentry events dir or do you need me to do something there?

I'll look into the async/shutdown thing still when I get a little time.

**Comment by pocmo** [comment]
Yes, I'm going to whitelist the directory. :)

For the upload problem I still wonder if reading from the connection will help as it should block the thread and wait for something to come back from the server. I would try a modified client locally but as the client is not build with Gradle this requires a bigger setup on my machine. :)

**Comment by realdeadfish** [comment]
Ok, skip that. Totally our fault. The sentry server was not available from the device's network, therefor nothing obviously reached the installation :( Sorry for the noise!

**Comment by realdeadfish** [comment]
After debugging a bit more we figured that crash logs are (silently) removed if the server responds with a 403 Forbidden message. The reason for that was that we only entered the DSN with the public key information, not with the public and private key. After changing the DSN sending in crashes worked.

It's a little confusing why apps need a different authorization than web (where apparently only the public part suffices). It was even a bit more confusing to see two kinds of authorization mechanisms, the auth key that is bound to a specific user to upload mapping files and the public/private key per project to upload crashes. I'd have expected a similar "project authentication" key for the crash upload, but hey, what do I complain, I now got it working :)

**Comment by realdeadfish** [comment]
Yes, I'm positive. I just added the private key part to the DSN and it magically worked.

**Comment by bretthoerner** [comment]
I wonder if this has to do with the version of the server? You said you're running on-prem right? What version?

I just ran a test with just the public DSN (on sentry.io) on 1.7.5 and it worked fine as usual.

**Comment by realdeadfish** [comment]
Yes, we're running on premise. I don't know what our versions was back when I tested it because it was updated since then, so ignore the issue for a moment if you could verify that it works with the latest version as expected. Thanks for taking care!
