### ISSUE TITLE
stacktrace.app.packages can not be configed in code

### ISSUE THREAD

**Issue by Alireza-Farahani** [getsentry/sentry-java#589]
When initializing sentry in java, parameters like `release` and `servername` could be set on `SentryClient`, but I don't see an option for setting `stacktrace.app.packages`. Is this a intended behavior or a bug? What are the workarounds?

**Comment by Alireza-Farahani** [comment]
I'm writing a springboot project and I wanted to use different sentry configuration per springboot active profile which I couldn't manage using sentry.properties. 
I know this could be set via system properties or env vars but I liked to set sentry properties in `application.yml` file. I couldn't find a way so decided to define a configuration in my code and load parameters from application.yml and initialize a `SentryClient`. `Release` and `servername` were available but `stacktrace.app.package`, `sample.rate` and some other properties were missing. I thought this was a bug but seems its intended.
And also, some guide or tutorial on configuring sentry with springboot would be great.

**Comment by bretthoerner** [comment]
We probably should add more configuration to the `SentryClient` itself.

As for configuration, I would just follow the configuration guide for the logging framework you use: https://docs.sentry.io/clients/java/modules/

**Comment by sanvisser** [comment]
Note that one workaround could be to add the `stacktrace.app.packages=<whatever>` as a query parameter to the DSN
`<DSN>?stacktrace.app.packages=<PACKAGE>`

This is what I am currently doing but I would rather have it as a separate option.

**Comment by Favorlock** [comment]
+1 for this issue. I am not able to use the sentry properties file or environment/system variables to configure sentry for my project, since I can't configure stacktrace.app.packages= programmatically I constantly see warnings about this. Quite annoying.

**Comment by maciejwalkowiak** [comment]
In the new, just released Java SDK v3 app packages can be configured in the code:

```java
Sentry.init(options -> options.addInAppInclude(...));
```
