### ISSUE TITLE
Sentry on android can't find `sentry.properties`, even though it's in classpath

### ISSUE THREAD

**Issue by ssrihari** [getsentry/sentry-java#590]
- I've tried adding it in the root dir, app dir, app/src/main/assets dir, etc
- I haven't set a java system property or an env variable
- Debugging shows that doing `new File("sentry.properties")` doesn't exist

Where should the `sentry.properties` file be present, in a typical android studio project?

**Comment by bretthoerner** [comment]
Hey, good question. I had to try a few different ones but this worked for me:

```
find . -name sentry.properties
./app/src/main/resources/sentry.properties
```

```
cat ./app/src/main/resources/sentry.properties
dsn=https://<secret>@sentry.io/<project>
```

I'll update the documentation.

**Comment by bretthoerner** [comment]
I guess it's worth noting I added that in the example project, I didn't do any other/special Gradle configuration. Apparently it looks for `resources/` as a standard "put this stuff on the Classpath" directory like other Java projects.

**Comment by bretthoerner** [comment]
Noted in https://github.com/getsentry/sentry-java/commit/4e5742d3eb9c34de6e5139420e3a6a27d8e84181

**Comment by ssrihari** [comment]
@bretthoerner thanks much!
