### ISSUE TITLE
Android Gradle Plugin: "error: not a JSON response"

### ISSUE THREAD

**Issue by yusufiga** [getsentry/sentry-java#592]
We are having an issue with sentry gradle plugin. It breaks the release build with "error: not a JSON response".

Strangely it doesn't happen all the time but 4 out of 5 build fails
  
I enabled sentry debugging you can find the logs below.

sentry-cli version: 1.32.0 (I also installed sentry-cli version 1.33.0 manually but plugin always uses 1.32.0)
sentry gradle plugin version: 1.7.5

EDIT: We are trying to build on Debian OS if relevant.
EDIT 2: I manage to test with 1.33.0 result is same "error: not a JSON response" on "POST /api/0/projects/<org>/<project>/files/dsyms/associate/"

```
> uploading mappings
[INFO] sentry_cli::api request POST https://self.deployed.server/0/projects/<org>/<project>/files/dsyms/
[INFO] sentry_cli::api using token authentication
[INFO] sentry_cli::api sending form data
[INFO] sentry_cli::api > POST /api/0/projects/<org>/<project>/files/dsyms/ HTTP/1.1
[INFO] sentry_cli::api > Host: self.deployed.server
[INFO] sentry_cli::api > Accept: */*
[INFO] sentry_cli::api > Connection: TE
[INFO] sentry_cli::api > TE: gzip
[INFO] sentry_cli::api > User-Agent: sentry-cli/1.32.0
[INFO] sentry_cli::api > Authorization: Bearer ***
[INFO] sentry_cli::api > Content-Length: 1189005
[INFO] sentry_cli::api > Content-Type: multipart/form-data; boundary=------------------------*****************
[INFO] sentry_cli::api < HTTP/1.1 201 CREATED
[INFO] sentry_cli::api < Content-Length: 2
> Uploaded a total of 0 new mapping files
[INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
[INFO] sentry_cli::api < Content-Language: en
[INFO] sentry_cli::api < X-Content-Type-Options: nosniff
[INFO] sentry_cli::api < Vary: Accept-Language, Cookie
[INFO] sentry_cli::api < Allow: GET, POST, HEAD, OPTIONS
[INFO] sentry_cli::api < X-Frame-Options: deny
[INFO] sentry_cli::api < Content-Type: application/json
[INFO] sentry_cli::api response: 201
[INFO] sentry_cli::api body: []
[INFO] sentry_cli::api request POST https://self.deployed.server/api/0/projects/<org>/<project>/files/dsyms/associate/
[INFO] sentry_cli::api using token authentication
[INFO] sentry_cli::api sending JSON data (195 bytes)
[INFO] sentry_cli::api > POST /api/0/projects/<org>/<project>/files/dsyms/associate/ HTTP/1.1
[INFO] sentry_cli::api > Host: self.deployed.server
[INFO] sentry_cli::api > Accept: */*
[INFO] sentry_cli::api > Connection: TE
[INFO] sentry_cli::api > TE: gzip
[INFO] sentry_cli::api > User-Agent: sentry-cli/1.32.0
[INFO] sentry_cli::api > Authorization: Bearer ***
[INFO] sentry_cli::api > Content-Type: application/json
[INFO] sentry_cli::api > Content-Length: 195
[INFO] sentry_cli::api response: 0
[INFO] sentry_cli::api body: 
error: not a JSON response
...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:persistSentryProguardUuidsForAlphaReleaseAlpha-release'.
> Process 'command '/tmp/.sentry-cli9115127124971229130.exe'' finished with non-zero exit value 1

```

**Comment by bretthoerner** [comment]
What version of Sentry server?

There should be an error in your Sentry logs, something must be up with the DSYM (but only sometimes). Maybe the length of a randomly generated field? This seems familiar.

**Comment by yusufiga** [comment]
Server version is 8.22.0 I will check the server logs.

**Comment by yusufiga** [comment]
We found this error log could it be related? By the way it started always failing so not only sometimes anymore.

`sentry-web: [uwsgi-body-read] Error reading 11203 bytes. Content-Length: 11203 consumed: 0 left: 11203 message: Client closed connection`

**Comment by bretthoerner** [comment]
Is there any possibility you could coordinate tailing the error logs while you tried to push the dsyms?

**Comment by yusufiga** [comment]
I tried but unfortunately that's all what I have. Do you have any idea in which case it returns "error: not a JSON response" with response code 0.

**Comment by bretthoerner** [comment]
I'm not sure, maybe @mitsuhiko or @jan-auer have an idea? Context: Response code 0 for uploading dsyms to self-hosted 8.22.0 using sentry-cli (via Android Gradle Plugin).

**Comment by mitsuhiko** [comment]
Sounds like uwsgi is not being passed data? How is this deployed: behind nginx?

**Comment by yusufiga** [comment]
I set `http.keepalive=false` in sentry.properties and now it works 👍
