### ISSUE TITLE
Attach HTTP headers to Sentry request

### ISSUE THREAD

**Issue by anapitupulu** [getsentry/sentry-java#594]
Hi -  I have two questions about Sentry Java client:

#### 1. Attach custom HTTP header to Sentry request
We setup our sentry server in our premise behind a proxy in which the request to it needs to be authenticated. The request is authenticated by looking at a custom HTTP header request. So two questions: 1) How do I attach a custom HTTP header to Sentry request? I notice that perhaps it can be done with subclassing [SentryClientFactory](https://docs.sentry.io/clients/java/config/#custom-functionality) but I don't really see the way to customize the header. 2) Related to this, since `SentryClientFactory` doesn't take any parameter, how I could pass in my credential to it? Using Dagger, maybe I could use Dependency Injection but wondering if there is a better way of passing information to it.

#### 2. Looking for an equivalent JS API
On our JS client, we override the HTTP transport handler using `transport` [option](https://docs.sentry.io/clients/javascript/config/):

![image](https://user-images.githubusercontent.com/10458496/43212289-942964a8-9001-11e8-88bb-3a81436d9a42.png)

Then, when we send our request to our proxy, we use several fields (underlined above) from that `options` object. Here is a snippet of our code:

```javascript
    transport: (options: any) => {
      const url = new URL(options.url);
      axios.post('/services/sentry-proxy' + url.pathname, options.data, {
        params: options.auth,
      });
    },
```
So my question is, how do I get this information in the Java API?

Thank you very much for your assistance!
-alex

**Comment by bretthoerner** [comment]
Hey Alex,

There's no built-in way to add headers or adjust the transport currently, but PRs are definitely welcome in that regard.

In the meantime, I think you'd want to have your own [SentryClientFactory](https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java#L401) that has its own `getConnection` much like the included one, but it should return your own [HttpConnection](https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/connection/HttpConnection.java#L127) subclass that overrides `getConnection` to set your own custom headers as necessary.

**Comment by maciejwalkowiak** [comment]
In the new, just released v3 SDK you have a possibility to set custom transport on `SentryOptions`. Look at https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/transport/ITransport.java and https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/transport/HttpTransport.java for inspiration. It would probably mean copy & pasting most of the `HttpTransport` and adding your custom headers there. 

In the future, we could allow setting custom `IConnectionConfigurator` on `SentryOptions` that would make modifications like adding custom header a breeze. What do you think @marandaneto @bruno-garcia?

**Comment by sbaechler** [comment]
Is there any documentation on the transport class?

**Comment by maciejwalkowiak** [comment]
@sbaechler In 4.0 (which will be released this month) we are simplifying creating custom transports. Take a look at the alternative transport implementation based on Apache Http Client 5 as the reference: https://github.com/getsentry/sentry-java/pull/1136

**Comment by marandaneto** [comment]
> In the new, just released v3 SDK you have a possibility to set custom transport on `SentryOptions`. Look at https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/transport/ITransport.java and https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/transport/HttpTransport.java for inspiration. It would probably mean copy & pasting most of the `HttpTransport` and adding your custom headers there.
> 
> In the future, we could allow setting custom `IConnectionConfigurator` on `SentryOptions` that would make modifications like adding custom header a breeze. What do you think @marandaneto @bruno-garcia?

looks like a real use case, it'd be way easier for people to set up a new IConnectionConfigurator that takes a Map other than writing its own Transport.

**Comment by marandaneto** [comment]
@sbaechler I believe it'd be easier & faster, making `IConnectionConfigurator` public and available thru `SentryOptions`, and adding a ctor overload for `CredentialsSettingConfigurator` that takes a Map, this Map would be appended to `connection.setRequestProperty` if not null & empty, something like that.

or even a new method IConnectionConfigurator.addNewHeader(key, value), so every subsequent request would append this too, just ideas.

glad to guide you if you feel contributing with a PR.

**Comment by maciejwalkowiak** [comment]
@marandaneto please take a look at the changes in https://github.com/getsentry/sentry-java/pull/1114 and https://github.com/getsentry/sentry-java/pull/1136. `IConnectionConfigurator` has been removed from there as it does not fit http client agnostic transports. In the new implementation the option would be to implement custom `TransportFactory` that takes new headers. Ideally lets discuss it in the mentioned pull requests.

**Comment by marandaneto** [comment]
oh yeah well thought, this has been changed, thanks for pointing out.

**Comment by sbaechler** [comment]
> glad to guide you if you feel contributing with a PR.

I am sorry I did not correctly read the title of this issue. I was looking for a documentation for the _Javascript_ version of the transport class.

**Comment by maciejwalkowiak** [comment]
Starting from 4.0 which just got released, custom headers can be attached by providing custom `ITransportFactory` implementation:

```
class CustomTransportFactory implements ITransportFactory {

  @Override
  public ITransport create(SentryOptions options, RequestDetails requestDetails) {
    requestDetails.getHeaders().put("custom-header", "custom-value");
    return new AsyncHttpTransport(
      options, new RateLimiter(options.getLogger()), options.getTransportGate(), requestDetails);
  }
}
```
and then setting it on `SentryOptions`:

```
Sentry.init(options -> {
  options.setTransportFactory(new CustomTransportFactory());
});
```

**Comment by marandaneto** [comment]
@maciejwalkowiak should we close this issue then?

**Comment by maciejwalkowiak** [comment]
I believe so. We could provide better abstraction to let users add custom headers but lets see if we get any feedback.

**Comment by adinauer** [comment]
@anjinok123 can you please describe your use case? It may involve writing your own implementation of `ITransport` which you can then return from e.g. a `CustomTransportFactory` as shown above.

**Comment by anjinok123** [comment]
> @anjinok123 can you please describe your use case? It may involve writing your own implementation of `ITransport` which you can then return from e.g. a `CustomTransportFactory` as shown above.
class CustomTransportFactory implements ITransportFactory {

  @Override
  public ITransport create(SentryOptions options, RequestDetails requestDetails) {
    String checkSum = checkSum(body)
    requestDetails.getHeaders().put(“verify_id”, checkSum);
    return new AsyncHttpTransport(
      options, new RateLimiter(options.getLogger()), options.getTransportGate(), requestDetails);
  }
}

As shown above, on each POST request, I need to generate a checkSum from the request body and put the checkSum into the request header for server-side validation

**Comment by anjinok123** [comment]
> @adinauer 
class CustomTransportFactory implements ITransportFactory {

  @Override
  public ITransport create(SentryOptions options, RequestDetails requestDetails) {
    String checkSum = checkSum(requestDetails.getBody())
    requestDetails.getHeaders().put(“verify_id”, checkSum);
    return new AsyncHttpTransport(
      options, new RateLimiter(options.getLogger()), options.getTransportGate(), requestDetails);
  }
}

As shown above, on each POST request, I need to generate a checkSum from the request body and put the checkSum into the request header for server-side validation

**Comment by adinauer** [comment]
Unfortunately the factory is invoked way before the actual request happens so you won't have access to the request body at that time. All you can do with `RequestDetails` is predefine things like headers that will then be added when the actual request happens.

I can't think of an easy way to support checksum calculation without providing a custom `ITransport` that calculates the checksum and puts it into a header.

This would basically require a hook in the SDK that allows you to manipulate the request before it goes out. There are no immediate plans on adding this, so I recommend you play around with a custom `ITransport`. Take a look at [`AsyncHttpTransport`](https://github.com/getsentry/sentry-java/blob/e9bec6ec2c5092673e12b21b008c3abf8e3cccc1/sentry/src/main/java/io/sentry/transport/AsyncHttpTransport.java) including `HttpConnection`.
