### ISSUE TITLE
Strange user information on Android 

### ISSUE THREAD

**Issue by kuno** [getsentry/sentry-java#597]
Although I've set the username and email in context
```kotlin
    Sentry.getContext().user = UserBuilder().setUsername(UserPrefsUtil.getCustomerUserName(app))
                                                .setEmail(UserPrefsUtil.getCustomerUserEmail(app))
                                                .build()
```

But we got these user information
<img width="286" alt="get_https___o2o-staging-sbux_wiredcraft_net_assortment_menu_product_recommendation_store_id_88801___" src="https://user-images.githubusercontent.com/161327/44141746-a1045dee-a0b0-11e8-83ae-6647c63a9160.png">

Name | sentry-java
-- | --
Version | 1.7.5-dccb1

**Comment by bretthoerner** [comment]
Hm, we default the user to the Android Id, but we shouldn't replace a value if you set one:

https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java#L66-L67

You say `Sentry.getContext().user =` but unless I'm missing something `user` is private, are you using `setUser`?

**Comment by kuno** [comment]
@bretthoerner 
yes, we tried actually.

But Android Studio suggested that `Sentry.setUser` somehow,  was deprecated.

**Comment by bretthoerner** [comment]
It is, I'm talking about:

https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/context/Context.java#L223-L230

And how are you calling `Sentry.init`?

**Comment by kuno** [comment]
@bretthoerner 

We using dagger 2 to inject the sentry client at our application
```kotlin
  @Provides
    fun provideSentry(app: MobileApp) =
            Sentry.init(SecurityEnv.SENTRY_DSN, AndroidSentryClientFactory(app.applicationContext))
```

```kotlin
    @Inject
    lateinit var sentry: SentryClient
```

**Comment by bretthoerner** [comment]
Sorry for the delay, were you ever able to resolve this?

I'm still confused about the reference to `Sentry.getContext().user`, is that really `Sentry.getContext().setUser(...)`? The `user` there should be `private`.

**Comment by kuno** [comment]
oh, if you were confused by the syntax, this is from kotlin language

In kotlin, it has a convention  that makes traditional Java getter/setter looks like an assignation option.

It works well in the most cases but might have some problems with sentry.

To no honest, we have not really solved the problem, but I managed to insert user information by some work around. 

It sort works for me now.

**Comment by AdamGrzybkowski** [comment]
@kuno what was your workaround? I do not see user id in the console either

**Comment by bretthoerner** [comment]
@AdamGrzybkowski how are you providing the User? I'd love to identify the bug if there is one here.

**Comment by AdamGrzybkowski** [comment]
@bretthoerner my bad, I was not initializing Sentry correctly. I set it up based on the Java doc not Android
