### ISSUE TITLE
Send crash logs in new process

### ISSUE THREAD

**Issue by realdadfish** [getsentry/sentry-java#598]
I've skimmed through sentry-java's code and figured that crash logs probably won't reach the server in two possible scenarios:

1. The app crashes right at the startup and therefor the background executor never gets the chance to run and upload the crash
2. The app crashes, but the user decides to not open the application again, thus the crash is never uploaded

IIRC Fabric's crashlytics doesn't have these issues, because they spawn a new Android service using a separate process (defined through `android:process` in the service' manifest entry) that uploads the crash right after the crash was catched by the `UncaughtExceptionHandler`. Have you thought about such an implementation for `sentry-android` eventually?

**Comment by bretthoerner** [comment]
I didn't realize that was possible, it's definitely something we should add if it's well supported.

**Comment by realdadfish** [comment]
What's the status on this one? This is still a major bummer for us :(

**Comment by marandaneto** [comment]
@realdadfish hey, we have a new Android SDK, it's on beta though. do you mind testing it and see if the same problem still happens? we still don't use a new process, but so far we were able to send the events right away.

https://github.com/getsentry/sentry-android

feedback is welcomed, thanks.

**Comment by realdadfish** [comment]
@marandaneto I'm not actively working on a project anymore that has a Sentry setup; still I think a separate process to send the crashlog out would be the superior implementation in cases where the existing ART process is simply not capable of doing resource-intensive work anymore, like in cases where `OutOfMemory` errors occur.
Imagine also that errors can occur at a time where the network coverage is bad, so even though you're trying to send out the crashlog immediately, you can't just reach the Sentry instance and retrying in-process would keep the (dead) process in a zombie state for too long.

So in the end this might sound like "corner corner cases" but you know how it is, sometimes it's the stuff your users care about and you just don't get your hands on this one device that triggers that error and you're basically blind for what is going on. Wouldn't it be great then if you'd have a crashreporting tool that would *reliably* tell you what was going on on this one device, regardless of the actual situation, and not a "99% solution"?

**Comment by marandaneto** [comment]
@realdadfish I totally agree with you and I've added in our backlog for investigation.

Definitely it will improve these corner cases, although there are downsides too.

One more process on memory.

The process also might be killed and should be able to recover, I guess the OS takes care of it most of the cases, but some custom ROMs might need special attention on that because they are usually more aggressive about not visible processes.

Architecture design might change a little because we aim to have a cross-platform lib. where it works `almost` everything on the backend side as well.

Processes need to communicate through IPC.

I still think it's a good idea, just pointing out a few things :)

**Comment by realdadfish** [comment]
Since Android Oreo it should be fine to start a foreground service in such a case, so your process is not killed. So what you could play with as a start would be to package your state into an Intent (or serialize it somewhere) and then start a foreground service in a separate process to actually send the information over the wire.

**Comment by marandaneto** [comment]
@realdadfish yep, that would be a way to go, but we need to support API >= 14, so we cannot rely only on `startForegroundService`.
When this gets prioritized and we have a better understanding of how it could be done, it would be nice to discuss about it, thanks.

**Comment by realdadfish** [comment]
@marandaneto Older versions of Android have fewer background restrictions, just spawing off a regular service should be ok for them (with or without notification display). Surely you can come back to me on this :)

**Comment by markushi** [comment]
Closing this for now, maybe it's worth considering using other means like WorkManager for taking care of sending events.
