### ISSUE TITLE
Package sentry-android as an AAR and bundle ProGuard rules in it

### ISSUE THREAD

**Issue by ninniuz** [getsentry/sentry-java#601]
It would be a neat improvement to package the sentry-android library as an AAR and ship a default ProGuard config with it through the consumerProguard feature, supported by the Android building mechanism by default.

References are here https://developer.android.com/studio/projects/android-library

**Comment by bretthoerner** [comment]
Sorry for the delay, I agree this would be good. Definitely open to PRs too. :)

**Comment by ninniuz** [comment]
I can work on a PR for sure but I would have to make the following choices which would affect the way you build and distribute artifacts:
- whether to transform the `sentry-android` module into a Gradle project and leverage AGP features or to stick with the Maven nature and tweak `android-maven-plugin`
- how to deal with the Android SDK requirement which is needed to build an aar

Any suggestions?

P.S. sorry for the delay :)

**Comment by ninniuz** [comment]
> * What would the AGP let you do that you can't do with Maven? We build everything (except the Gradle plugin) in the one Maven project so that compile/test is easy. So long as we kept it easy I don't care if it has to change to Gradle.

It seems the most used features when building apk/aar are already supported by the `android-maven-plugin`, which is though **NOT** endorsed by Google for apk/aar development. That means new features would require voluntary development on the Maven plugin to catch up with changes and/or unexpected bugs/behaviors.

Migrating to Gradle would have some drawbacks with dependencies on sibling projects (namely `sentry`) during development. You can easily depend on a sibling Gradle project but the only way I see to manage those mixed deps would be to rely on m2, that means installing `sentry` version locally and so on.

We could move the whole project to Gradle :D

> * I'm guessing it requires something newer than this? 
>     
>       
>         [sentry-java/sentry-android/pom.xml](https://github.com/getsentry/sentry-java/blob/7291a61d0f01dbd5508c08dc8496c34b7dc96320/sentry-android/pom.xml#L18)
>       
>       
>            Line 18
>         in
>         [7291a61](/getsentry/sentry-java/commit/7291a61d0f01dbd5508c08dc8496c34b7dc96320)
>       
>       
>       
>       
>   
>           
>             
>              <android.version>4.1.1.4</android.version> 
>           
>       
>     
>   
>    My only concern would be that we need to continue to support people targeting older Android versions.

You can target any API level you require, you do not have to switch to the latest available in order to use AGP.

**Comment by bretthoerner** [comment]
> We could move the whole project to Gradle :D 

I'm not opposed, but that's a lot of work that I probably won't be doing anytime soon. :P

> you do not have to switch to the latest available in order to use AGP

Oh, I was replying to:

> how to deal with the Android SDK requirement which is needed to build an aar

I'm not sure I follow that bit?

**Comment by ninniuz** [comment]
> Oh, I was replying to:
> 
> > how to deal with the Android SDK requirement which is needed to build an aar
> 
> I'm not sure I follow that bit?

In order to build an aar you have to use some platform tools available within the Android SDK (e.g. `aapt2` etc). Those tools must be available in the building machine no matter if you use AGP or `android-maven-plugin`.

I just am worried about an additional building tool you would have to deal with.

**Comment by ninniuz** [comment]
That's cool. I will try and build up something in the next days :-)

**Comment by ninniuz** [comment]
I am able to build an aar with android-maven-plugin (sticking to Maven since converting the whole project to Gradle is a mess at the moment).
I am stuck at the release phase as I don't know exactly how maven-release-plugin works.

**Comment by ninniuz** [comment]
They are distributed on Maven repositories such as Maven Central (or jcenter etc).
I am not sure how to make the maven-release-plugin upload the aar file on the maven repo instead of the built jar file.

**Comment by ninniuz** [comment]
I was mistaking the role of maven-release-plugin.
Tested a local deploy on my `.m2` with `mvn install` and the aar is correctly picked up and transferred to m2 (since the module packaging will switch to aar). 
I cannot test the behavior of `maven-deploy-plugin` or the nexus staging one but I expect them to behave the same for what regards artifact selection.
I am going to make a PR in the following days.

**Comment by bretthoerner** [comment]
👍

**Comment by marandaneto** [comment]
hey @ninniuz as you already know, the new Android SDK is on beta and it is `AAR` packaged, this won't be done on this version.

**Comment by ninniuz** [comment]
👍

**Comment by marandaneto** [comment]
The Android SDK 2.0 is packed as Android libs.
Please upgrade it, the new repo sits at https://github.com/getsentry/sentry-android
Let us know if you find any issues, thanks :)
