### ISSUE TITLE
RFC: support for runtime configuration and introspection via JMX

### ISSUE THREAD

**Issue by t-8ch** [getsentry/sentry-java#602]
It would be nice if Sentry could be introspected and reconfigured at runtime.
(Changing the DSN, tags, environment etc.)
This will be useful if the process using Sentry is long-running and not easily restartable.

The standard mechanism in Java to provide this functionality is JMX which is quite flexible.
I am proposing a new module `sentry-jmx` that provides both a default MBean (manageable object) for the global sentry client and the necessary tooling to expose custom managed clients via MBeans.

I am willing to perform the implementation if this proposal receives positive feedback.

**Comment by bretthoerner** [comment]
The idea in general seems fine to me. I worry less about the effort required to add the JMX side as I do the effort/bugs from changing Sentry at runtime (since no consideration has been given to this before).

That is, unless you're OK with just configuring a new `SentryClient` and swapping out the global shared reference each time something changes?

**Comment by t-8ch** [comment]
It seems to me that the normal properties of all clients should be changeable at runtime.
The DSN would need special handling though, as it can't be changed on a given client.
We could provide a special JMX operation that swaps the global reference for a new client with the new DSN (clearing all dynamically set properties in the process), effectively calling `Sentry.init(String dsn)`.
For non-global clients we can provide the scaffolding to configure normal properties and allow them to reinitialize the client.

**Comment by bretthoerner** [comment]
I've never been a big JMX user, how would users identify a single `SentryClient` instance among multiple in a single JVM?

**Comment by bretthoerner** [comment]
But I should say: definitely open to PRs related to this.

**Comment by t-8ch** [comment]
Object have a name.
Will do.

**Comment by maciejwalkowiak** [comment]
It could be done but I am not sure if it ever get high enough priority. @bruno-garcia do you think its something we should keep in backlog or close?

**Comment by bruno-garcia** [comment]
Given that this issue has been stale for 2 years, lets close it.

Feel free to reopen or comment if this is still relevant to your.
