### ISSUE TITLE
Sentry.init blocks main thread on startup to retrieve SDK version number (android)

### ISSUE THREAD

**Issue by mcomella** [getsentry/sentry-java#605]
[The Android integration documentation](https://docs.sentry.io/clients/java/modules/android/) suggests that `Sentry.init` should be called on startup. However, `Sentry.init` blocks the main thread for an extended period of time – 463ms wall clock time and 219ms CPU time on a Fire TV 4K – which is notably half of our `Activity.onCreate` run time:
![screen shot 2018-08-31 at 14 08 16](https://user-images.githubusercontent.com/759372/44935927-80246a00-ad27-11e8-8ec4-2a0cde214867.png)

Here's the trace file: [startup.trace.tar.gz](https://github.com/getsentry/sentry-java/files/2341629/startup.trace.tar.gz)

Looking to the Sentry call stack:
![screen shot 2018-08-31 at 14 15 08](https://user-images.githubusercontent.com/759372/44936117-4d2ea600-ad28-11e8-974d-9bf408782c00.png)

It looks like this line is causing the blocking call: https://github.com/getsentry/sentry-java/blob/33f8b7edb41879a9e669aa863a7abfbb79247aa0/sentry/src/main/java/io/sentry/environment/SentryEnvironment.java#L23

Which is reading the JAR. Notes:
- This is a long time to wait for an SDK version, especially on startup; I'd rather this be filled asynchronously and potentially have a few crash reports without SDK versions (especially because I can often identify the sdk version by app version)
- My assumption is that reading the JAR reads from disk and reading from disk on the main thread in Android is generally frowned upon

---

STR
- Clone my [firefox-tv/host-startup-trace branch](https://github.com/mcomella/firefox-tv/tree/host-startup-trace)
- Launch and run on device until UI appears
- Filter logcat for "lol", you should see a path to a file
- Extract the file (e.g. with Android Studio's device file explorer which can access private dirs or `adb pull`)
- Open and examine trace in AS

**Comment by bretthoerner** [comment]
Sorry for the delay, and thanks for the very detailed report.

This definitely sucks, I'll see what I can do.

**Comment by bretthoerner** [comment]
@mcomella do you mind looking at (or trying?) #607

**Comment by mcomella** [comment]
Thanks Brett! I think there may be a way to access this value at compile time: I know how to do this in an app but not a library. I'm asking my team if they have suggestions and will get back to you shortly.

btw, sorry for the delay: I was out of town.

**Comment by ncalexan** [comment]
> Thanks Brett! I think there may be a way to access this value at compile time: I know how to do this in an app but not a library. I'm asking my team if they have suggestions and will get back to you shortly.

For Android, the Android-Gradle build plugin supports a nice `BuildConfig` option (that works just fine for libraries).  See, for example, https://searchfox.org/mozilla-central/source/mobile/android/geckoview/build.gradle#71.  That'll be for Android -- the question is how flexible is the Android-on-Java layer-cake that Sentry has.  Is it easy to do different things on Android and in the JRE?  'cuz the underlying `.properties` Java resource approach is definitely the regular JRE way to achieve this.

**Comment by ncalexan** [comment]
> Yeah it gets a bit weird because we actually build our Android library with Maven (and no Android plugin at all) as a sub-project (or whatever it'd be called) of the normal Java SDK.

I didn't dig into your repo, but I did wonder if you'd be using the Android-Gradle build plugin.  Since you're not, but you are using Maven's resources plugin, you might find https://stackoverflow.com/a/11740749 achieves the goal.  It's not particularly pretty but it is consistent with your existing toolchain and it can be scoped to just the `sentry-android/pom.xml`.

**Comment by bretthoerner** [comment]
Alright please check out #609

**Comment by ncalexan** [comment]
> Pushing 1.7.9 to Maven Central if you want to give it a whirl.

@bretthoerner thanks so much for jumping on this so quickly.  @mcomella can you verify that Brett's changes improve the main-thread IO profile you were seeing?

**Comment by mcomella** [comment]
Confirmed: startup time went from 463/219ms wall/CPU (https://github.com/getsentry/sentry-java/issues/605#issue-356129619) to 58/34ms. Thanks Brett!

fwiw, in the next startup trace, I noticed there is an attempt to get an InputStream for a file:

https://github.com/getsentry/sentry-java/blob/9133ad6f96b64136d6e12f4808b2c63df1ce9836/sentry/src/main/java/io/sentry/config/Lookup.java#L35-L37

but the startup time seems insignificant so it's probably fine.
