### ISSUE TITLE
Uncaught exception handler is added multiple times

### ISSUE THREAD

**Issue by ArloL** [getsentry/sentry-java#606]
I was investigating multiple `ClassLoader` leaks in our environment and found this allocation tree in applications that leaked:

![image](https://user-images.githubusercontent.com/195367/44995756-d9e59800-afa4-11e8-82d7-4b55846b1c69.png)

Due note the different Object Identifiers. This is a chain of `SentryUncaughtExceptionHandler`'s.

I have looked at the source code and the current implementation of SentryUncaughtExceptionHandler wraps itself if the SentryClient is initialized multiple times. The setup() method does not check whether the current uncaught exception handler is an instanceof SentryUncaughtExceptionHandler.

IMO this is not necessary and wrapping itself should be omitted. I would propose something akin to

````
public static SentryUncaughtExceptionHandler setup() {
    logger.debug("Configuring uncaught exception handler.");

    Thread.UncaughtExceptionHandler currentHandler = Thread.getDefaultUncaughtExceptionHandler();
    if (currentHandler != null) {
        logger.debug("default UncaughtExceptionHandler class='" + currentHandler.getClass().getName() + "'");
    }
    if (currentHandler instanceof SentryUncaughtExceptionHandler) {
        return (SentryUncaughtExceptionHandler) currentHandler;
    }

    SentryUncaughtExceptionHandler handler = new SentryUncaughtExceptionHandler(currentHandler);
    Thread.setDefaultUncaughtExceptionHandler(handler);
    return handler;
}
````

And I was also thinking that it might be a bad idea to register an uncaught exception handler in a Tomcat application? Should I disable it globally?

**Comment by bretthoerner** [comment]
You can disable it, and you're correct that it's unlikely to be useful in Tomcat: https://docs.sentry.io/clients/java/config/#uncaught-exception-handler

One issue with replacing/removing existing handlers is that technically an application can instantiate multiple `SentryClient`s. So I'd need to handle that somehow. I believe they should be harmless (if a small leak) because they are disabled if the client is closed.

**Comment by ArloL** [comment]
FYI: We have disabled it for all our Tomcat deployments now. So our specific issue is gone. Don't know whether you want to keep the issue open.
