### ISSUE TITLE
logback Threshhold Filter

### ISSUE THREAD

**Issue by adrian-goe** [getsentry/sentry-java#610]
Hello, Unfortunately it is not possible for me to use logback SentryAppander properly.
My code:
```

ThresholdFilter filter = new ThresholdFilter();
        filter.setLevel("WARN");
        sentryAppender.addFilter(filter);
```
In the documentation of the AppanderBase I read the following: 

> The next if statement checks the results of the attached filters. Depending on the result of the filter chain, events can be denied or interpreted accepted. In the absence of a decision by the filter chain, events are accepted by default.
[https://logback.qos.ch/manual/appenders.html#AppenderBase](https://logback.qos.ch/manual/appenders.html#AppenderBase)

I suppose that's it.

For now, i use the Deprecated `setMinLevel()`

**Comment by bretthoerner** [comment]
Sorry, it's not clear to me exactly what our code is or isn't doing that it should or shouldn't be doing here, can you elaborate?

**Comment by Flashnos** [comment]
For sure. I created the threshold filter here and set it to "WARN".
When debugging I can see that `sentryAppender.addFilter (filter)` is empty. SentryAppander says in the debugger `io.sentry.logback.SentryAppander [null]`
It may well be that it is something other than what I first suspected. In any case, the filter will not be applied and all logs will be sent to the server.
I can give you the complete method.
```
    @SuppressWarnings("Deprecated")
    @Bean(initMethod = "start", destroyMethod = "stop")
    public SentryAppender sentryAppender() {
        SentryAppender sentryAppender = new SentryAppender();

        LoggerContext ctx = (LoggerContext) LoggerFactory.getILoggerFactory();
        sentryAppender.setContext(ctx);
        
       // sentryAppender.setMinLevel("WARN");
        
        ThresholdFilter filter = new ThresholdFilter();
        filter.setLevel("WARN");
        sentryAppender.addFilter(filter);

        Logger root = (Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        root.addAppender(sentryAppender);

        return sentryAppender;
    }
```

**Comment by bretthoerner** [comment]
Can you try doing this in addition to what you have there: `logger.setAdditive(false)`

https://stackoverflow.com/a/17386343/11958

**Comment by Flashnos** [comment]
This doesn't work.

**Comment by bruno-garcia** [comment]
@Flashnos Is this still happening on the latest version?

**Comment by nigelsim** [comment]
It is because you need to `start()` the filter, otherwise it simply gets ignored:

```
ThresholdFilter filter = new ThresholdFilter();
filter.setLevel("WARN");
filter.start();
sentryAppender.addFilter(filter);
```

**Comment by maciejwalkowiak** [comment]
Starting from Java SDK 3.0 you can set `minimumEventLevel` and `minimumBreadcrumbLevel` directly on the `SentryAppender`. Read more in the guide: https://docs.sentry.io/platforms/java/guides/logback/#minimum-log-level

If this does not fit your use case I advice to configure threshold filter in `logback.xml` then you don't need to call `start` anywhere manually. 

If you're still having issue with setting the minimum level you're welcome to drop a comment and we will reopen this issue then.
