### ISSUE TITLE
"API request failed" while uploading proguard mappings

### ISSUE THREAD

**Issue by ayavilevich** [getsentry/sentry-java#611]
Hi,

Added and configured Sentry.io for the project and not can't build a release configuration.

Build log ends with

```
Printing classes to [C:\x\build\outputs\mapping\release\dump.txt]...
The TaskInternal.execute() method has been deprecated and is scheduled to be removed in Gradle 5.0. There are better ways to re-use task logic, see https://docs.gradle.org/4.4/userguide/custom_tasks.html#sec:reusing_task_logic.
> compressing mappings
> uploading mappings
error: API request failed
  caused by: sentry reported an error: not found (http status: 404)
:transformClassesAndResourcesWithProguardForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':persistSentryProguardUuidsForReleaseArm64-v8a-release'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 23s
29 actionable tasks: 6 executed, 23 up-to-date
```

dump.txt is 217MB and mapping.txt is 10MB.

Having two ``sentry.properties`` files. One in ``src\main\resources`` with ``dsn`` and another in root with: ``defaults.project``, ``defaults.org``, ``auth.token``.
Before having two separate ``sentry.properties`` files I was getting "An organization slug is required".

I am using sentry library and plugin version 1.7.5 .

How to debug further?

**Comment by bretthoerner** [comment]
Can you run with `SENTRY_LOG_LEVEL=debug` environment variable set?

The error is an HTTP 404 so I'm curious what URL it is trying to hit.

**Comment by bretthoerner** [comment]
Oh damn, thanks for the report. That is a documentation bug.

As for the message, it only reports how many *new* files were uploaded. Had you already run it successfully once? If you change some files and run it again it should hopefully be `> 0`.

**Comment by bretthoerner** [comment]
Fixed docs here, thanks again: https://github.com/getsentry/sentry-docs/pull/342

**Comment by ayavilevich** [comment]
Thanks for the quick fix.
What would be the way to know if there is a valid mapping registered on your end?

**Comment by bretthoerner** [comment]
In your project settings there is a "Debug Files" section on the left, for example my org/project would be: https://sentry.io/settings/bretthoerner/brett-hoerner-test/debug-symbols/
