### ISSUE TITLE
Build error with Android Studio 3.3 Canary 11, io.sentry.android.gradle 1.7.10, macOS 10.14

### ISSUE THREAD

**Issue by smoothdvd** [getsentry/sentry-java#614]
gradle out log:
```
:app:persistSentryProguardUuidsForBaiduDebugBaidu-debug FAILED
error: No such file or directory (os error 2)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:persistSentryProguardUuidsForBaiduDebugBaidu-debug'.
> Process 'command '/var/folders/qm/mb1vc1w95pd25tvc4fpty0qm0000gn/T/.sentry-cli2515672975003161956.exe'' finished with non-zero exit value 1
```
detail at: [https://scans.gradle.com/s/jyi4pdg3lmukc/](url)

**Comment by bretthoerner** [comment]
Weird, I can't tell if it's not finding `sentry-cli` or whether `sentry-cli` is running and failing to find something? I think it's the latter, if possible could you run this with the environment `SENTRY_LOG_LEVEL=debug` set?

**Comment by bretthoerner** [comment]
Oh, two other things:

1. Is this a new integration or was this project working with Sentry before the upgrade to Android Studio 3.3?
2. Does it work with an older `sentry-android` plugin version, like `1.7.5`?

**Comment by smoothdvd** [comment]
@bretthoerner And why there is so many same sentry-cli files in tmp folder

at  /var/folders/1_/rz7fvk5n47l2twsn5p3jd__w0000gn/T/
```
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli1796431400659358211.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli2778039570031276702.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli347389853621281901.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli383255447132214088.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli4085346359538802588.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli4338817773262853563.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli4688462420077190487.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli4975633267179613249.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli5287377020292618648.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli6355562257335033313.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli6512656890563881138.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli6614028006047820219.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli6975225553303939472.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli6983672137868912973.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli740878939184683608.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli7889101107167863124.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli8333443788381987666.exe
-rwxr--r--    1 alexgao  staff   14111896  9 27 08:39 .sentry-cli9045232384560757950.exe
```
and the version is 1.35.5

**Comment by smoothdvd** [comment]
I clean the folder .idea/libraries, then error is gone.

**Comment by smoothdvd** [comment]
@bretthoerner sentry-android plugin (1.7.5) worked perfect with Android Studio 3.1.

**Comment by smoothdvd** [comment]
Looks 1.7.12 fix this issue. Thanks!

**Comment by EvgenyTerebenin** [comment]
You can try 1.7.19. It works too. 

But 1.7.20 - 1.7.27 version has the bug already
`An organization slug is required (provide with --org)`

`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:persistSentryProguardUuidsForReleaseRelease'.`

`Caused by: org.gradle.process.internal.ExecException: Process 'command '/var/folders/jj/xbml6hjd7nn9djxntd93jr4h0000gn/T/.sentry-cli5839559214403123200.exe'' finished with non-zero exit value 1`

**Comment by simoneventurini** [comment]
i'm using 1.7.27 and i have the same problem during release build.

**Comment by marandaneto** [comment]
@simoneventurini and @EvgenyTerebenin thanks for your message.

Where is your `sentry.properties` placed?
Which version of `AS`, `AGP`, and `Gradle` do you have?
I'll assume that `sentry-java` and `Sentry plugin` are `1.7.27`, correct me if I am wrong.

Thanks.

**Comment by marandaneto** [comment]
@EvgenyTerebenin I think it's the same issue -> #803 so, please test it with the latest version and if not, reopen the issue.
It worked for @simoneventurini 

Thanks.
