### ISSUE TITLE
Release Field not setted.

### ISSUE THREAD

**Issue by marcinOz** [getsentry/sentry-java#615]
I've tried to set release field but it always shows `package + version_name` in the crash console.
version: 1.7.10

I've tried :
1) with sentry.properties
```
        val sentryClient = Sentry.init(AndroidSentryClientFactory(app))
        sentryClient.environment = BuildConfig.BUILD_TYPE
        sentryClient.release = releaseName
```

2)
```
         Sentry.init(
                     "<dsn>",
                     AndroidSentryClientFactory(app)
         )
        sentryClient.release = releaseName
```

3)
```
         Sentry.init(
                     "<dsn>?release=${releaseName}",
                     AndroidSentryClientFactory(app)
         )
```

I've double check `releaseName` is always there with proper value but in the console, it's not.

**Comment by bretthoerner** [comment]
Yeah, it seems like we force override it in the `AndroidEventBuilderHelper` :( We'll have to fix this to only set it if it isn't already set.

https://github.com/getsentry/sentry-java/blob/9293b44e02ee7c735e20398a717c6de7d0971ed6/sentry-android/src/main/java/io/sentry/android/event/helper/AndroidEventBuilderHelper.java#L58-L61

I'll try to make that change soon. In the meantime I think you should be able to add your own `EventBuilderHelper` that should run last and therefore "win."

```
Sentry.getStoredClient().addBuilderHelper(new EventBuilderHelper() {
            @Override
            public void helpBuildingEvent(EventBuilder eventBuilder) {
                eventBuilder.withRelease("foo");
            }
        });
```

Sorry about that!
