### ISSUE TITLE
Add option that uses certificate pinning for Sentry.io

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#623]
Via forum: https://forum.sentry.io/t/certificate-pinning/4859/7?u=bretthoerner

I think we'd do something similar to this: https://developer.android.com/training/articles/security-ssl#UnknownCa

**Comment by realdadfish** [comment]
If the Java-Implementation ever opts in and uses okhttp for transport, this issue could be easily solved by OkHttp's own [CertificatePinner](https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html).

In any case I'd argue to solve this in a way that both, cloud and on-premise instances can enable / configure that, i.e. don't let on-premise users fall back to a custom trust manager installation, but rather give them an easy way to configure their certificate chain for their Sentry host. This also allows you to keep the configuration for `sentry.io` out of the code base and just tell people through the documentation what the (current) correct certificate chain for `sentry.io` looks like.

**Comment by marandaneto** [comment]
dup of #906
