### ISSUE TITLE
Sentry.setStoredClient may introduce race condition

### ISSUE THREAD

**Issue by ssouris** [getsentry/sentry-java#628]
There are cases where 
1. if logback appender tries to initialize the Sentry client (first call to init) and
2. [from another thread] I'm trying to `Sentry.setStoredClient`

It is not guaranteed who will set the client first. 

One workaround would be to initialize Sentry early on for example in a server application.

Any thoughts ? :)

**Comment by bretthoerner** [comment]
What is your use case for having two clients (using `setStoredClient`) and storing them statically?

**Comment by ssouris** [comment]
I don't have two clients. 
I'm basically trying to integrate the `Sentry.init(dsn)` with Spring `application.properties` , so that I can provide the `sentry.dsn` through application.properties.

In that case, the appender will try to initialize the Sentry client without a DSN (spring properties not loaded yet) but when I have my Spring context available with the properties I will initialize again with a custom component and try to set it with `Sentry.setStoredClient`.

I'm afraid though that this approach introduces a race condition.

**Comment by bretthoerner** [comment]
I wonder if it would make more sense to programatically add the SentryAppender after you initialize Sentry (and leave it out of your logback config file)?

**Comment by ssouris** [comment]
I'm currently experimenting with an approach like that :). I'll let you know.

**Comment by ssouris** [comment]
Yes, it works really well like that and I am avoiding the race condition :)

**Comment by bretthoerner** [comment]
Great! This seems like the best solution since this is a pretty special case.

**Comment by ssouris** [comment]
Thanks :)
