### ISSUE TITLE
ProGuard fails in os error 1006 when -dontobfuscate specified

### ISSUE THREAD

**Issue by 4eRTuk** [getsentry/sentry-java#630]
When I try to assemble apk (debug or release, any flavor), next error appears:
> What went wrong:
Execution failed for task ':app:persistSentryProguardUuidsForProductionReleaseProduction-release'.
> Process 'command 'cmd'' finished with non-zero exit value 1

I think the reason in backward slash in Windows, because when I set sentry logs to debug sentry-cli command runs with next ***--write-properties*** arg:

> INFO    2018-10-24 18:02:57.404789600 +03:00 Loaded config from C:\\Users\\...\\.sentryclirc
  INFO    2018-10-24 18:02:57.405790400 +03:00 sentry-cli was invoked with the following command line: "C:\\Users\\...\\.sentry-cli1772965816167522517.exe" "upload-proguard" "--android-manifest" "C:\\Android\\...\\app\\build\\intermediates\\merged_manifests\\betaDebug\\processBetaDebugManifest\\merged\\AndroidManifest.xml" "--write-properties" "C:\\Android\\...\\app\\build/intermediates/assets/beta/debug/sentry-debug-meta.properties" "C:\\Android\\...\\app\\build\\outputs\\mapping\\beta\\debug\\mapping.txt"
  DEBUG   2018-10-24 18:02:57.431818200 +03:00 skipping update nagger because session is not attended
error: The volume for a file has been externally altered so that the opened file is no longer valid. (os error 1006)
  DEBUG   2018-10-24 18:02:57.432818800 +03:00 client close; no transport to shut down  (from sentry)

Not sure, maybe it's connected with #528, but I also tried to separate dsn in sentry.properties in /app/src/main/resources and auth token and defaults org in C:\\Users\\...\.sentryclirc with no luck.

**Comment by bretthoerner** [comment]
Could you try invoking the `sentry-cli` with the same arguments but with the slashes fixed? It does seem like a bug but we have other users using Windows without issues (that I know of) so I want to rule this in or out.

**Comment by 4eRTuk** [comment]
You are right. After manually invoking sentry-cli same result - `error: The volume for a file has been externally altered so that the opened file is no longer valid. (os error 1006)`

Maybe any option from my ProGuard is the reason?
> -dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-verbose
-dontobfuscate
-dontoptimize
-dontpreverify

**Comment by 4eRTuk** [comment]
OK, actually I figured out that if obfuscation is disabled, sentry does not require dSYMs (no wonder :). But if sentry gradle plugin is enabled (as I have in build.gradle), this error occurs anyway for debug build. I think it should respect or somehow skip this step if there is no obfuscation.

Moreover, for release build I have another proguard file with obfuscation enabled, and I encounter exactly the same error on uploading in #622

**Comment by bretthoerner** [comment]
@mitsuhiko @jan-auer Do you have any ideas what `error: The volume for a file has been externally altered so that the opened file is no longer valid. (os error 1006)` is when dealing with files in Windows? (this is from `sentry-cli`. I haven't had a report of this before so I wonder if nobody has used it on Windows 10 (seems doubtful?) or if something changed in the `sentry-cli`?

**Comment by 4eRTuk** [comment]
@bretthoerner As I found `error: The volume for a file has been externally altered so that the opened file is no longer valid. (os error 1006)` appears when -dontobfuscate flag exists in proguard file. Checked on Windows 8 too.

**Comment by mitsuhiko** [comment]
Seems like a very obscure error from the windows io system. Not sure what triggers it. Arr any files here symlinked, junctioned or on locally mounted ntfs drives?

**Comment by 4eRTuk** [comment]
All my files are stored in main NTFS system drive (C:\).

And #622 should be reopened I think.

**Comment by bretthoerner** [comment]
Can you run with SENTRY_LOG_LEVEL=debug and post your logs?

**Comment by 4eRTuk** [comment]
Sure, see in #622. Renamed this issue to more specific problem.

**Comment by 4eRTuk** [comment]
Yes, ESET Internet Security 12. Tried to disable protection & firewall - same error.

**Comment by blattersturm** [comment]
We experienced this issue with breakpad-style symbols if any .sym file was 0 bytes in size. Removing these from the input set fixed the I/O error.

**Comment by jan-auer** [comment]
I was able to reproduce this. We will fix this in an upcoming release.

**Comment by marandaneto** [comment]
@jan-auer have you fixed this? maybe https://github.com/getsentry/sentry-cli/pull/484 ?

**Comment by marandaneto** [comment]
@4eRTuk closing this issue, if you see that is still happening, let us know :)
