### ISSUE TITLE
Sentry Android Plugin invalid manifest location

### ISSUE THREAD

**Issue by nicusorflorin** [getsentry/sentry-java#637]
I use the  'io.sentry:sentry-android-gradle-plugin:1.7.13' and the  'io.sentry:sentry-android:1.7.10'(this one is hosted in a library which is added as a dependency in the main project) versions

Sentry does not run the transform for the manifest, we have a merged manifest. I set debug level to info and got this in the logs:

sentry-cli was invoked with the following command line: "C:\\Users\\[USERNAME]\\AppData\\Local\\Temp\\.sentry-cli3126958598252517512.exe" "upload-proguard" "--android-manifest" "property(interface org.gradle.api.file.Directory, transform(property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultProjectLayout$FixedDirectory, D:\\magnolia-android\\app\\build))))\\AndroidManifest.xml" "--write-properties" "D:\\magnolia-android\\app\\build/intermediates/assets/store/release/sentry-debug-meta.properties" "D:\\magnolia-android\\app\\build\\outputs\\mapping\\store\\release\\mapping.txt"
error: The system cannot find the path specified. (os error 3)

**Comment by bretthoerner** [comment]
https://github.com/getsentry/sentry-java/blob/c58cbdedee5b5cfbeb28cfd4cf590a17aeab5c25/sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L149-L165

So I guess that code is returning:

```
property(interface org.gradle.api.file.Directory, transform(property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultProjectLayout$FixedDirectory, D:\magnolia-android\app\build))))\AndroidManifest.xml
```
I've never seen this before, do you have any idea how to get your merged manifest path in Gradle?

**Comment by nicusorflorin** [comment]
We got a similar issue with crashlytics, and they allowed us to specify the path manually  
  //seems android build tools 3.3.0-alpha05 has changed the merged manifest path
    crashlytics {
        manifestPath = "$buildDir/intermediates/library_manifest/release/AndroidManifest.xml"
    }

**Comment by bretthoerner** [comment]
> they allowed us to specify the path manually

Ah, OK, we can add that.

**Comment by bretthoerner** [comment]
OK with Sentry Gradle Plugin version `1.7.15` you can add this:

```
sentry {
    manifestPath "/foo/bar"
}
```

It's syncing to Maven Central now.
