### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#639]
If the user is on a modern JVM (such as 11), SSL can cause the exception noted in the title.

Adding '-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2' to the JVM options should fix the issue.

Not sure if we can do anything more here.

**Comment by aze-kool** [comment]
we are having the same issue with sentry and java 13

**Comment by maciejwalkowiak** [comment]
I could not reproduce this issue. We have just released SDK v3 - would be nice if you could check if it still happens with the new version. 

In v3, we added an option to set custom `SSLSocketFactory` on `SentryOptions`. Perhaps it can help. 

I am closing it for now, please comment if issue still occurs.
