### ISSUE TITLE
Failed to Generate Signed Apk - An organization slug is required (provide with --org)

### ISSUE THREAD

**Issue by AlirezaNoorali** [getsentry/sentry-java#643]
After setting up the [Sentry.io][1] error tracking in my Android (Java) Project, I get this error when I try to **Generate Signed Apk**:

    Java Compiler
    error: An organization slug is required (provide with --org)

Click on this image and open it to see more details:
[![Error][2]][2]

I cannot understand anything from this one:

    Process 'command
    '/var/folders/j4/_fzm1rks3tsc2h3j4l2qbq4w0000gn/T/.sentry-cli1369818638611304938.exe'
    ' finished with non-zero exit value 1

This is the file address that was raised in error:
[![Address in error][3]][3]

How can I solve this problem and Generate Signed Apk?

  [1]: https://sentry.io/
  [2]: https://i.stack.imgur.com/Ufsb6.png
  [3]: https://i.stack.imgur.com/qHJAy.png

**Comment by bretthoerner** [comment]
https://docs.sentry.io/clients/java/modules/android/#gradle-integration

What is the contents of the `sentry.properties` file in *the root of your project*? In that documentation link above it should show an example of the file contents you'll need there.

**Comment by bretthoerner** [comment]
This is different configuration, required at compile time (not in the code). From the documentation link above:

The credentials for the upload step are loaded via environment variables or from a sentry.properties file in your project root. Please note the sentry.properties in your project root that configures sentry-cli is different than the one you include in your application resources to configure the Sentry SDK at runtime

**Comment by AlirezaNoorali** [comment]
@bretthoerner 
I'm going to use Sentry for My Android project I’m working on.
My company is using a self hosted Sentry, version 9.0.0

I followed [Sentry.io Installation Guide][1].

These permissions were added in Manifest:

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

This is my **app/build.gradle** file:

    dependencies {
        ...
        implementation 'io.sentry:sentry-android:1.7.10'
        implementation 'org.slf4j:slf4j-nop:1.7.25'
    }

    apply plugin: 'io.sentry.android.gradle'

    sentry {
        autoProguardConfig true
        autoUpload true
    }

This is my top level project **build.gradle** :

    dependencies {
        ...
        classpath 'io.sentry:sentry-android-gradle-plugin:1.7.10'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

This is MainActivity:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Context ctx = this.getApplicationContext();
        String sentryDsn = "https://MyPublicKey:MySecretKey...";
        Sentry.init(new AndroidSentryClientFactory(ctx));

        setContentView(R.layout.activity_main);

        Sentry.capture("This Is My First Log!");
        ...
    }

and I put sentry.properties file in the root of my project:
`[defaults]
url = https://log.mydomain.ir
org = myorg
project = myproject

[auth]
token = auth_token`

but nothing sent to Sentry Panel. What's the problem?

  [1]: https://docs.sentry.io/clients/java/modules/android/

**Comment by bretthoerner** [comment]
Can you check the Sentry server logs to see if a request is made to the server at all, or if an error occurs? Is your DSN correct?

**Comment by bruno-garcia** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists.
