### ISSUE TITLE
Sends improperly formatted timestamps in certain locales

### ISSUE THREAD

**Issue by nolanamy** [getsentry/sentry-java#646]
<img width="501" alt="screenshot 2018-12-05 10 43 34" src="https://user-images.githubusercontent.com/1137310/49536153-b586a980-f87a-11e8-9440-af3f312eaf58.png">

In case it's helpful, this code works for me:

```kotlin
val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.UK)
dateFormat.timeZone = TimeZone.getTimeZone("UTC")

...

dateFormat.format(Date())
```

**Comment by bretthoerner** [comment]
Good catch, thanks: https://github.com/getsentry/sentry-java/commit/10da2f6ee67a957e0be97cf17703e4614eb7c71d
