### ISSUE TITLE
sentry-android is exposing DSN in logcat

### ISSUE THREAD

**Issue by ninniuz** [getsentry/sentry-java#649]
Sentry is logging info even if the application is not debuggable and in some cases it is exposing data that we might not want to, e.g. DSN.

Example log:
```
2018-12-14 11:07:51.817 21547-21547/? D/io.sentry.a.a: Sentry init with ctx='xxxxxx' and dsn='Dsn{uri=https://sentry.xxxx.xyz/}'
```

It could be possible to completely remove `android.util.Log` calls with ProGuard but that requires to enable optimizations which are quite time consuming and error prone.

In general it would be better to avoid logging altogether in release builds.
Possible solutions include using a logging library like Timber or to implement a basic logging helper which can be turned on/off at runtime.

**Comment by ninniuz** [comment]
Or maybe use SLF4J for Android logging as well?
What would you prefer? I can work on a PR.

**Comment by bretthoerner** [comment]
This is a tough one. I don't want to add dependencies for Android users, or stomp on any other existing logging solutions they have.

We could also just remove this debug log line maybe.

Where would an end user be able to view these logs? I thought they were disabled on actual phones?

**Comment by ninniuz** [comment]
An end user can see this in logcat. 
Some manufacturers disable some log levels, but others do not. This specific log line was taken from a Pixel 2 device.

Logging can be an expensive operation and should be avoided as much as possible on release builds.

Possible solutions:
- Simply remove this "offending" debug log line (I am calling this offending since it is exposing some internal data in plain text):
  - Easy to implement, exposes to future errors
- Wrap log calls with if statements checking whether the hosting application is in release mode:
  - Verbose and prone to errors
- Add a logging proxy class which forward calls to Android logging only if the hosting application is in release mode:
  - No external dependencies, dev must remember to use the logging proxy class instead of Android logging directly
- Rely on external logging libraries, e.g. Timber
  - New dependency, widely used in the Android community, requires refactoring
- Use SLF4J for logging in the `sentry-android` module as well as in the `sentry-java` parent module and let the hosting app dev decide how to enable/disable logging (e.g. rely on `slf4j-android` for debug builds and on `slf4j-no-op` for release builds):
  - No external dependencies, refactoring needed

I can work on any of these as I need this to be fixed in the end :-) 
I would go for the SLF4J approach at the moment as it offers an easy to way to turn on/off logging altogether and fits with the logging system already used in the `sentry-java` module.

**Comment by ninniuz** [comment]
And of course support for Android in SLF4J has been dropped in 1.8.0-alpha0...

**Comment by ninniuz** [comment]
> I think removing the line is decent short-term solution.

Ok, do you need me to send a PR for this?

> An end user could always grep your .apk for the DSN anyway, right? This is the same problem we have with JS.

Yes, a "malicious" agent could extract this info from an apk somehow. Of course that would be a little more difficult than reading a plain log :-)

**Comment by bretthoerner** [comment]
Yeah if you don't mind a PR would be great, I'm mostly offline this week but I can approve and merge.
