### ISSUE TITLE
Report ANRs on Android

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#658]
https://developer.android.com/topic/performance/vitals/anr

https://github.com/SalomonBrys/ANR-WatchDog

**Comment by Christophe31** [comment]
Hi, would using this lib would offer the feature right now?

It looks like a cool feature ;-).

**Comment by bruno-garcia** [comment]
We're working on integrating it in the SDK: #752 
It'll be an opt-in that will send events to Sentry when ANR is detected
