### ISSUE TITLE
Sentry.capture(null) causes NullPointerException

### ISSUE THREAD

**Issue by deftelf** [getsentry/sentry-java#663]
Cause is obvious, `SentryClient.sendException()` is just doing `getMessage()` on whatever is passed in.

Perhaps it is not valid to pass in null here, but this is 
(a) not documented in the javadoc
(b) not annotated so that Kotlin compiler / lint / whatever can pick it up.

```
NullPointerException
Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
io.sentry.SentryClient in sendException at line 200
io.sentry.Sentry in capture at line 156
popsa.com.repository.ErrorReporter in report at line 17
```

**Comment by finci-square** [comment]
Hi, I found this github issue as a result of google search for NPE's not logging to sentry (java spring boot).  What i'm seeing is that NPE's without an exception message aren't sent to sentry.  this must be a mistake- I certainly want to know about the NPE regardless of whether it contains an exception message.  Thougts?

**Comment by marandaneto** [comment]
hey @finci-square upgrade the SDK, pretty sure it's not an issue since v3

**Comment by finci-square** [comment]
I'm on 3.1.1

**Comment by marandaneto** [comment]
> I'm on 3.1.1

not possible, `Sentry.capture(..)` nor `SentryClient.sendException()` don't even exist under API v3, open a new issue then please and fill up the bug template.

**Comment by marandaneto** [comment]
> > I'm on 3.1.1
> 
> not possible, `Sentry.capture(..)` nor `SentryClient.sendException()` don't even exist under API v3 (they have different names), open a new issue then please and fill up the bug template.
