### ISSUE TITLE
Task :persistSentryProguardUuidsForReleaseArm64-v8a-release FAILED (AS:3.3 ABP:3.3.0 Gradle:4.10.1 sentry-android-gradle-plugin:1.7.16)

### ISSUE THREAD

**Issue by ayavilevich** [getsentry/sentry-java#667]
Project was working fine with sentry plugin before upgrade to AS 3.3 and the matching dev tools.

Now I have more build variants than just release/debug which I had before.

When I build a release version of the APK I get "Task :persistSentryProguardUuidsForReleaseArm64-v8a-release FAILED". The plugin is trying to run command:

```
"[user]\\AppData\\Local\\Temp\\.sentry-cli8452420388174734644.exe" "upload-proguard" "--android-manifest" "[project_root]\\build\\intermediates\\merged_manifests\\release\\AndroidManifest.xml" "--write-properties" "[project_root]\\build\\intermediates\\merged_assets\\release\\mergeReleaseAssets\\out/sentry-debug-meta.properties" "[project_root]\\build\\outputs\\mapping\\release\\mapping.txt"
```

but there is no ``"[project_root]\\build\\intermediates\\merged_manifests\\release\\AndroidManifest.xml"``, instead there is ``"[project_root]\\build\\intermediates\\merged_manifests\\release\\arm64-v8a\\AndroidManifest.xml"``. The task fails with "error: The system cannot find the file specified. (os error 2)".

I am running the build on Windows 10.

**Comment by bretthoerner** [comment]
What version of the Sentry Gradle Plugin?

**Comment by ayavilevich** [comment]
1.7.16 AFAIK. I am declaring it as

``classpath 'io.sentry:sentry-android-gradle-plugin:1.7.16'``

**Comment by bretthoerner** [comment]
Hm, can you try 1.7.17 for kicks?

**Comment by ayavilevich** [comment]
I tried it. It is different but still doesn't work.

The output is:

```
> Task :persistSentryProguardUuidsForReleaseX86_64-release FAILED
  INFO    2019-01-21 20:41:58.727862300 +02:00 Loaded config from [user]\.sentryclirc
  DEBUG   2019-01-21 20:41:58.727862300 +02:00 sentry-cli version: 1.37.4, platform: "windows", architecture: "i686"
  INFO    2019-01-21 20:41:58.727862300 +02:00 sentry-cli was invoked with the following command line: "[user]\\AppData\\Local\\Temp\\.sentry-cli566513390579874671.exe" "upload-proguard" "--android-manifest" "[project_root]\\build\\intermediates\\merged_manifests\\release\\AndroidManifest.xml" "--write-properties" "[project_root]\\build\\intermediates\\merged_assets\\release\\mergeReleaseAssets\\out/sentry-debug-meta.properties" "[project_root]\\build\\outputs\\mapping\\release\\mapping.txt"
  DEBUG   2019-01-21 20:41:58.731815200 +02:00 error: running update nagger
  DEBUG   2019-01-21 20:41:58.731815200 +02:00 skipping update nagger because session is not attended
error: The system cannot find the file specified. (os error 2)
  DEBUG   2019-01-21 20:41:58.733808400 +02:00 client close; no transport to shut down  (from sentry)

> Task :persistSentryProguardUuidsForReleaseX86-release FAILED
  INFO    2019-01-21 20:41:59.050745600 +02:00 Loaded config from [user]\.sentryclirc
  DEBUG   2019-01-21 20:41:59.051742 +02:00 sentry-cli version: 1.37.4, platform: "windows", architecture: "i686"
  INFO    2019-01-21 20:41:59.051742 +02:00 sentry-cli was invoked with the following command line: "[user]\\AppData\\Local\\Temp\\.sentry-cli5633728940175926171.exe" "upload-proguard" "--android-manifest" "[project_root]\\build\\intermediates\\merged_manifests\\release\\AndroidManifest.xml" "--write-properties" "[project_root]\\build\\intermediates\\merged_assets\\release\\mergeReleaseAssets\\out/sentry-debug-meta.properties" "[project_root]\\build\\outputs\\mapping\\release\\mapping.txt"
  DEBUG   2019-01-21 20:41:59.053737200 +02:00 error: running update nagger
  DEBUG   2019-01-21 20:41:59.053737200 +02:00 skipping update nagger because session is not attended
error: The system cannot find the file specified. (os error 2)
  DEBUG   2019-01-21 20:41:59.054734 +02:00 client close; no transport to shut down  (from sentry)

> Task :persistSentryProguardUuidsForReleaseArmeabi-v7a-release FAILED
  INFO    2019-01-21 20:41:59.390066900 +02:00 Loaded config from [user]\.sentryclirc
  DEBUG   2019-01-21 20:41:59.391098600 +02:00 sentry-cli version: 1.37.4, platform: "windows", architecture: "i686"
  INFO    2019-01-21 20:41:59.391098600 +02:00 sentry-cli was invoked with the following command line: "[user]\\AppData\\Local\\Temp\\.sentry-cli1169914661652554113.exe" "upload-proguard" "--android-manifest" "[project_root]\\build\\intermediates\\merged_manifests\\release\\AndroidManifest.xml" "--write-properties" "[project_root]\\build\\intermediates\\merged_assets\\release\\mergeReleaseAssets\\out/sentry-debug-meta.properties" "[project_root]\\build\\outputs\\mapping\\release\\mapping.txt"
  DEBUG   2019-01-21 20:41:59.393059300 +02:00 error: running update nagger
  DEBUG   2019-01-21 20:41:59.393059300 +02:00 skipping update nagger because session is not attended
error: The system cannot find the file specified. (os error 2)
  DEBUG   2019-01-21 20:41:59.394064900 +02:00 client close; no transport to shut down  (from sentry)

> Task :persistSentryProguardUuidsForReleaseArm64-v8a-release FAILED
  INFO    2019-01-21 20:41:59.741264400 +02:00 Loaded config from [user]\.sentryclirc
  DEBUG   2019-01-21 20:41:59.742230300 +02:00 sentry-cli version: 1.37.4, platform: "windows", architecture: "i686"
  INFO    2019-01-21 20:41:59.742230300 +02:00 sentry-cli was invoked with the following command line: "[user]\\AppData\\Local\\Temp\\.sentry-cli6568250991765753417.exe" "upload-proguard" "--android-manifest" "[project_root]\\build\\intermediates\\merged_manifests\\release\\AndroidManifest.xml" "--write-properties" "[project_root]\\build\\intermediates\\merged_assets\\release\\mergeReleaseAssets\\out/sentry-debug-meta.properties" "[project_root]\\build\\outputs\\mapping\\release\\mapping.txt"
  DEBUG   2019-01-21 20:41:59.744224900 +02:00 error: running update nagger
  DEBUG   2019-01-21 20:41:59.744224900 +02:00 skipping update nagger because session is not attended
error: The system cannot find the file specified. (os error 2)
  DEBUG   2019-01-21 20:41:59.745221800 +02:00 client close; no transport to shut down  (from sentry)
```

So now it tries to do it once for each release architecture, but the path to the ``AndroidManifest.xml`` is still wrong.

If you are having issues reproducing this, LMK. Could be something non-default in my project or the fact that it underwent an upgrade from Android Studio 3.2 to 3.3 .

For example, this project uses ABI split.

```
    // Specify that we want to split up the APK based on ABI
    // faster builds and smaller APK, but more than one APK per release
    splits {
        abi {
            // Enable ABI split
            enable true

            // Clear list of ABIs
            reset()

            // Specify each architecture currently supported
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"

            // Specify that we do not want an additional universal SDK
            universalApk false
        }
    }
```

**Comment by ayavilevich** [comment]
Commented out the "splits" section and tried to build without it. Manifest was created as expected and cli started fine, but then got error from server:

```
> Task :persistSentryProguardUuidsForReleaseRelease
  INFO    2019-01-21 21:03:01.053459300 +02:00 Loaded config from [user]\.sentryclirc
  DEBUG   2019-01-21 21:03:01.053459300 +02:00 sentry-cli version: 1.37.4, platform: "windows", architecture: "i686"
  INFO    2019-01-21 21:03:01.053459300 +02:00 sentry-cli was invoked with the following command line: "[user]\\AppData\\Local\\Temp\\.sentry-cli8081640012938934376.exe" "upload-proguard" "--android-manifest" "[project root]\\build\\intermediates\\merged_manifests\\release\\AndroidManifest.xml" "--write-properties" "[project root]\\build\\intermediates\\merged_assets\\release\\mergeReleaseAssets\\out/sentry-debug-meta.properties" "[project root]\\build\\outputs\\mapping\\release\\mapping.txt"
> compressing mappings
> uploading mappings
  DEBUG   2019-01-21 21:03:04.388949800 +02:00 request POST https://sentry.io/api/0/projects/x/y/files/dsyms/
  DEBUG   2019-01-21 21:03:04.388949800 +02:00 using token authentication
  DEBUG   2019-01-21 21:03:04.388949800 +02:00 sending form data
  DEBUG   2019-01-21 21:03:04.388949800 +02:00 retry number 0, max retries: 0
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > POST /api/0/projects/x/y/files/dsyms/ HTTP/1.1
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > Host: sentry.io
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > Accept: */*
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > Connection: TE
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > TE: gzip
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > User-Agent: sentry-cli/1.37.4
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > Authorization: Bearer 679cd84f***
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > Content-Length: 624181
  DEBUG   2019-01-21 21:03:04.940606500 +02:00 > Content-Type: multipart/form-data; boundary=------------------------0036d46a2c3a52df
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < HTTP/1.1 400 BAD REQUEST
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Server: nginx
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Date: Mon, 21 Jan 2019 19:03:10 GMT
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Content-Type: application/json
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Content-Length: 35
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Connection: keep-alive
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Content-Language: en
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < X-Content-Type-Options: nosniff
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Allow: GET, POST, DELETE, HEAD, OPTIONS
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < X-Frame-Options: deny
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < X-Served-By: web-b378b859
  DEBUG   2019-01-21 21:03:10.765475800 +02:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2019-01-21 21:03:10.766473200 +02:00 response status: 400
  DEBUG   2019-01-21 21:03:10.766473200 +02:00 body: {"detail": "Missing uploaded file"}
  DEBUG   2019-01-21 21:03:10.766473200 +02:00 error: running update nagger
  DEBUG   2019-01-21 21:03:10.766473200 +02:00 skipping update nagger because session is not attended
error: API request failed
  caused by: sentry reported an error: Missing uploaded file (http status: 400)
  DEBUG   2019-01-21 21:03:10.767469 +02:00 client close; no transport to shut down  (from sentry)

> Task :persistSentryProguardUuidsForReleaseRelease FAILED

FAILURE: Build failed with an exception.
```

mapping file is 10MB.

Seems like the plugin is not working well with ABI split projects using the new build tools.

Seems like there is another issue with uploads.

**Comment by grennis** [comment]
Having same issue. Sentry cant find the manifest file when using ABI splits and product flavors. This starting failing when I upgraded to Gradle 3.3.0.

**Comment by bretthoerner** [comment]
OK, will have to look into the split issue.

> but then got error from server

Odd, is this sentry.io or self-hosted (and if so what version)?

**Comment by ninniuz** [comment]
> "--write-properties" "[project root]\\build\\intermediates\\merged_assets\\release\\mergeReleaseAssets\\**out/sentry-debug-meta.properties**"

@bretthoerner I am seeing a Unix path separator here. Maybe `io.sentry.android.gradle.SentryPlugin#getDebugMetaPropPath` should be updated to use the File API to build the path?

**Comment by grennis** [comment]
It seems like the error with ABI splits could be more of an android tools bug in 3.3.0, because the `manifestOutputDirectory` just is wrong because it doesn't contain the CPU architecture.

So I was able to get things working again by inserting this line just before the sentry plugin constructs the manifest path:

`outputDir = new File(outputDir, variantOutput.getFilter(OutputFile.ABI))

So this works at least until the gradle bug is fixed (?)

**Comment by bretthoerner** [comment]
But it's not always safe to do that, is it? We need a safe way to know when we should/shouldn't add the ABI. I guess we just check the existence of the directory? Is anyone able to make a PR that works for their project?

> I am seeing a Unix path separator here

It is weird, but this has worked for our Windows users. I'd like to fix it to use File API though.

**Comment by grennis** [comment]
@bretthoerner  Correct, it would not always be safe to do that. I can only say it worked for my project where I know I'm using flavors and ABI splits and gradle 3.3.0. I think maybe logic that would work might be something like: If manifest is not at expected path, try appending OutputFile.ABI to path, if it does exist there, use it.
BUT Maybe it will be back to expected behavior in gradle 3.3.1... who knows? If that is the case I think it's best not to change anything at all.

**Comment by ninniuz** [comment]
You should be able to safely get the right path by appending variantOutput.getDirName() to the manifestOutputDirectory

**Comment by ninniuz** [comment]
I am seeing this in the Gradle Plugin `manifestPath = new File(outputDir, "AndroidManifest.xml")`.
Cannot get hold of a PC right now to check further and to try on a sample project though.

**Comment by grennis** [comment]
Oh interesting, so it is falling into the catch block, I didn't realize that

**Comment by ninniuz** [comment]
@bretthoerner I confirm `variantOutput.getDirName()` will provide you with the right subpath to append to `manifestOutputDirectory` to retrieve the manifest file for any buildType, flavor, apk split or any combination of these.

So, something like `${manifestOutputDirectory}/${variantOutput.getDirName()}/AndroidManifest.xml` will work.

You could use `java.nio.file.Paths` API to build the file path.

**Comment by bretthoerner** [comment]
Anyone want to try a PR? I don't have a broken project to try this against currently, and have to catch up on some other things. If not I'll try to look at this soon.

**Comment by ayavilevich** [comment]
I am happy to try a fix on my broken project, but I would need detailed installation instructions.

At the moment I just ``classpath 'io.sentry:sentry-android-gradle-plugin:1.7.16'`` the plugin and I am not sure hot to try a custom version.

**Comment by bretthoerner** [comment]
In the `sentry-android-gradle-plugin` in a checkout of this repo you just run `./gradlew clean install` preferably with JDK8. That should install to your local repo.

Then, in your project `build.gradle` I would use something like this in `buildscript`:

```
    repositories {
        jcenter()
        mavenLocal()
        mavenCentral()
        google()
    }
```

The current version on `master` is `1.7.19-SNAPSHOT` and you should be able to change your plugin version to that after you do the above. It should find your locally installed copy.

**Comment by ayavilevich** [comment]
@bretthoerner perhaps it is not that hard to make a test project that is affected. Seems like it will be a good practice to have a test project with splits anyway for testing future releases.

Did you try to take one of your existing test projects and just add:

```
splits {
        abi {
            // Enable ABI split
            enable true

            // Clear list of ABIs
            reset()

            // Specify each architecture
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"

            // Specify that we do not want an additional universal SDK
            universalApk false
        }
    }
```

**Comment by ninniuz** [comment]
> java.lang.NullPointerException: Cannot invoke method getFile() on null object
> If I disable `apply plugin` I can sync fine.
> 
> Any idea what is wrong?

Personally, I had to init the Sentry Gradle plugin by invoking the `download-sentry-cli.sh` bash script to add sentry-cli binaries to the `resources/bin` folder.
Can you do the same before `./gradlew clean install`? (I don't know if that script is supposed to work under Windows env).

**Comment by bretthoerner** [comment]
Oh right, sorry I forgot you wouldn't have the binaries there. I doubt it would work on Windows unless you can use WSL.

**Comment by ayavilevich** [comment]
Ok, took a look at the script, it was not that complex.
Downloaded cli from https://github.com/getsentry/sentry-cli/releases to sentry-java\sentry-android-gradle-plugin\src\main\resources\bin\sentry-cli-Windows-i686.exe

Ran ``./gradlew clean install`` again. Now I can sync fine.

Tried build again but it is still looking for the manifest in the ``release`` folder rather than in the individual folders. How can I check that the repo I pulled contains the fix? What is the commit id for the fix? Was the PR merged? Into what branch?

**Comment by ninniuz** [comment]
I don't think there is a PR for this yet.
Can you try replacing this line https://github.com/getsentry/sentry-java/blob/4495ea8105641fc612b85d0a0f209658d37e2de7/sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L186 with
`manifestPath = new File(new File(outputDir, variantOutput.dirName), "AndroidManifest.xml")` and try again `clean install` to refresh the plugin locally?

**Comment by bretthoerner** [comment]
> I don't think there is a PR for this yet.

That's correct, sorry, I meant for someone to try the posted solution and maybe submit a PR or tell us whether it works or not.

**Comment by ayavilevich** [comment]
@ninniuz @bretthoerner with the proposed change I can now pass the sentry-cli execution stage. The mapping seems to be getting compressed however I get a "400 BAD REQUEST" from the sentry.io server as I described earlier in https://github.com/getsentry/sentry-java/issues/667#issuecomment-456173839

I now get the same issue at upload for both the split and no split builds of the app.

Any idea what I can do about it?

**Comment by bretthoerner** [comment]
Hmm,

`{"detail": "Missing uploaded file"}`

Does the file it's trying to upload exist?

`"[project root]\\build\\outputs\\mapping\\release\\mapping.txt"`

Or if you try it with your change, what file path does it print as the last argument to `sentry-cli` and does that file exist? Is it empty?

**Comment by ayavilevich** [comment]
@bretthoerner the mapping.txt file does exist. The printed headers also specify a "Content-Length" with ~600KB size.

Where is it compressing the mapping to? Another file? Memory?

Who is responsible for the sentry.io/api services? Can somebody take a look at the server log? Seems like a failure to parse the uploaded data.

**Comment by ayavilevich** [comment]
Good news. I am now in a sort-of working condition.

The mapping upload issue was fixed in latest sentry-cli 1.39.1 . Possibly: https://github.com/getsentry/sentry-cli/pull/484

Now if I use 1.7.21-SNAPSHOT with the fix:

```
- manifestPath = new File(outputDir, "AndroidManifest.xml")
+ manifestPath = new File(new File(outputDir, variantOutput.dirName), "AndroidManifest.xml")
```

I can do a successful build and it does upload the mappings.

Still not resolved: It uploads the mapping 4 times. One for each configuration, where there only seems to be one mapping. The fix is not in the official released version of the plugin.

Hope these issues can be fixed.

**Comment by bretthoerner** [comment]
> It uploads the mapping 4 times.

The Sentry server should be deduplicating (and not storing) any symbols that are exactly the same. In theory your mapping files could be different between variants/splits right? Seems better to be safe than sorry.

We can make a release with the newest `sentry-cli` though.

**Comment by bretthoerner** [comment]
Oh, and the code fix. I forget if we decided that this wouldn't break existing code (users without splits) or whether we need another branch?

**Comment by ayavilevich** [comment]
Well, if I comment out splits it builds and uploads just fine with the same configuration and fix. So it seems to work without needing to branch but I guess you guys should put it through the regular qa process.

**Comment by ninniuz** [comment]
@bretthoerner on top of this, if you go back through the history of this class you will see that that way of retrieving the manifest path was already used some releases ago.
I would say this is safe enough.

**Comment by ayavilevich** [comment]
Are there plans to merge the fix above to the released version?

**Comment by KrisOch** [comment]
Hi, I faced the same issue with ABI-splits and the wrong manifest path. Do you have a snapshot version with a fix I could test? I got a project with splits and flavours, and also a project without any split-config where I could try the fix. We actually use AGP 3.4.1.

Please let me know. Thx.

**Comment by bruno-garcia** [comment]
@KrisOch We've publish a [new release (1.7.24) that addresses flavors and dimensions](https://github.com/getsentry/sentry-java/releases/tag/v1.7.24). Could you please give it a try?

**Comment by ayavilevich** [comment]
@bruno-garcia 
It looks there is still no 1.7.24 version at https://mvnrepository.com/artifact/io.sentry/sentry-android-gradle-plugin
Is that intentional?

**Comment by bruno-garcia** [comment]
@ayavilevich It was hanging on sonatype with the repo closed but not published. My bad.
I've released it now.

**Comment by ayavilevich** [comment]
@bruno-garcia tried the new version. Unfortunately it still looks for the AndroidManifest.xml file in the wrong directory (as described above). This fails the build and we can't use the gradle plugin as a result.

**Comment by ninniuz** [comment]
@bruno-garcia it should be enough to replace
https://github.com/getsentry/sentry-java/blob/52d7836f0d642b079238a3e4736dd96143d3f9d5/sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L171

with 

```manifestPath = new File(new File(dir, variantOutput.dirName), "AndroidManifest.xml")```

**Comment by grennis** [comment]
@bruno-garcia  Thanks... assuming this last change locating the manifest didnt make it in to version 24? Will this be in 1.7.25?

**Comment by bruno-garcia** [comment]
@grennis right. We'll ship 1.7.25 soon though.

**Comment by grennis** [comment]
@bruno-garcia Great, thank you

**Comment by KrisOch** [comment]
Sorry for the late answer...

I built a snapshot with [this fix](https://github.com/getsentry/sentry-java/issues/667#issuecomment-511767535) and it worked for me.

**Comment by KrisOch** [comment]
Tested with 1.7.25. Works fine. Thanks.
