### ISSUE TITLE
EventBuilder's breadcrumbs are replaced by Context's breadcrumbs

### ISSUE THREAD

**Issue by ninniuz** [getsentry/sentry-java#670]
Breadcrumbs added to an `EventBuilder` through `io.sentry.event.EventBuilder#withBreadcrumbs` are replaced by Context's registered breadcrumbs when sending the event through `io.sentry.SentryClient#sendEvent(io.sentry.event.EventBuilder)`.

From `io.sentry.event.helper.ContextBuilderHelper#helpBuildingEvent`:

```
List<Breadcrumb> breadcrumbs = context.getBreadcrumbs();
if (!breadcrumbs.isEmpty()) {
    eventBuilder.withBreadcrumbs(breadcrumbs);
}
```

Is this the expected behavior?

**Comment by bretthoerner** [comment]
Yeah, the general idea is that context-specific data always wins. Did you have something else in mind, like merging them?

**Comment by ninniuz** [comment]
Yes, I was expecting breadcrumbs from the EventBuilder to be appended to the Context's ones.

**Comment by maciejwalkowiak** [comment]
Thanks @ninniuz for reporting. In the new Java SDK 3.0 this issue is solved - scope breadcrumbs are set on the event only if event does not have its own breadcumbs. See: https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryClient.java#L281
