### ISSUE TITLE
Separate sentry project for each android build type

### ISSUE THREAD

**Issue by nesterov-n** [getsentry/sentry-java#671]
Is it possible to use multiple sentry projects with sentry gradle plugin? 
[Docs](https://docs.sentry.io/cli/configuration/#config-defaults) say that `default.project` option must be defined in `sentry.properties` that is placed in the root dir of a project.

My app uses two build types e.g (`release` and `staging`). Each type uses Proguard for obfuscation. And I want to set different sentry projects for them. 

How do I make crashes from `release` be sent to `myapp-release` sentry project and crashes from `staging` be sent to `myapp-staging`?

**Comment by ninniuz** [comment]
Isn't the plugin already supposed to look for Sentry properties in the following locations, for each variant:
```
def possibleProps = [
                                "${project.projectDir}/src/${variantName}/${propName}",
                                "${project.projectDir}/src/${flavorName}/${propName}",
                                "${project.projectDir}/src/${variantName}/${flavorName}/${propName}",
                                "${project.projectDir}/src/${flavorName}/${variantName}/${propName}",
                                "${project.rootDir.toPath()}/src/${variantName}/${propName}",
                                "${project.rootDir.toPath()}/src/${flavorName}/${propName}",
                                "${project.rootDir.toPath()}/src/${variantName}/${flavorName}/${propName}",
                                "${project.rootDir.toPath()}/src/${flavorName}/${variantName}/${propName}",
                                "${project.rootDir.toPath()}/${propName}"
                        ]
```

**Comment by nesterov-n** [comment]
@ninniuz according to [docs](https://docs.sentry.io/clients/java/modules/android/#gradle-integration) gradle plugin uses only `sentry.properties` that is placed in the root directory.
> The credentials for the upload step are loaded via environment variables or from a sentry.properties file in your project root. Please note the sentry.properties in your project root that configures sentry-cli is different than the one you include in your application resources to configure the Sentry SDK at runtime (as seen in the configuration documentation).

**Comment by bretthoerner** [comment]
Please try 1.7.18

https://github.com/getsentry/sentry-java/releases/tag/v1.7.18

**Comment by nesterov-n** [comment]
@bretthoerner Yes, it works. Thank you!
