### ISSUE TITLE
Feature Request: capture native crashes in Android

### ISSUE THREAD

**Issue by amir169** [getsentry/sentry-java#672]
We need to use Sentry in an Android project with native codes. It seems it fails to capture native crashes.
Is it possible to capture native crashes with current version of the SDK, if not is there any plan to add this feature in next versions?

Thanks in advance

**Comment by bretthoerner** [comment]
It's not possible currently, but we have planned support for NDK.

**Comment by HazAT** [comment]
As brett mentioned, we are currently working on adding support for NDK, please stay tuned it's not that far off and we are determined to add it to the SDK.

**Comment by JAStanton** [comment]
@HazAT this is wonderful news. Any idea when we can expect an update to the timeline for when this will land? Even vague dates will help with our planning. Thank you!

**Comment by markcerqueira** [comment]
Hi Sentry folks 👋 Do you have any estimated timelines on NDK support? Would love to explore Sentry but not having NDK support or a clear timeline on NDK support is a dealbreaker. Thanks!

**Comment by bruno-garcia** [comment]
We're working on [sentrypad](https://github.com/getsentry/sentrypad) which provides the basis for an NDK support. There's a couple of releases of sentrypad and we're looking for feedback.

**Comment by markcerqueira** [comment]
Obrigado, @bruno-garcia! 🙏

**Comment by marandaneto** [comment]
hey people, we have a beta version of the new Android SDK which also supports NDK:
https://github.com/getsentry/sentry-android

This will require a migration as it's a major bump.
Feedback is welcomed on the new repo :)

Thanks.

**Comment by JAStanton** [comment]
@marandaneto is it possible to depend on this new version of sentry-android when using https://github.com/getsentry/sentry-react-native ?  I'm not quite sure how they play together. Thanks :)

**Comment by marandaneto** [comment]
hey @JAStanton when the beta version moves to a stable version, `sentry-react-native` will depend on the new `sentry-android`, stay tuned :)

**Comment by JAStanton** [comment]
@marandaneto any rough idea when that will be? Is that like 6 months away or 1-2 years+?

**Comment by marandaneto** [comment]
@JAStanton I'm not the `sentry-react-native` maintainer, but I'll check with them and will come back to you asap.

**Comment by HazAT** [comment]
@JAStanton It's definitely less than 6 months away. 
I would say 1-2 months from now, depends when we make the first stable release of the new Android SDK. There is only one internal larger change we want to do.

**Comment by JAStanton** [comment]
@HazAT thanks 👍

**Comment by marandaneto** [comment]
@JAStanton https://github.com/getsentry/sentry-react-native/releases/tag/1.3.0

**Comment by JAStanton** [comment]
@marandaneto thank you!

**Comment by marandaneto** [comment]
The Android SDK 2.0 has NDK support ootb.
Please upgrade it, the new repo sits at https://github.com/getsentry/sentry-android
Let us know if you find any issues, thanks :)
