### ISSUE TITLE
How should I show client ip?

### ISSUE THREAD

**Issue by Yjnull** [getsentry/sentry-java#675]
How should I show client ip?

SDK Name : sentry-java
version: 1.7.4-94da4

**Comment by Yjnull** [comment]
First of all, thank you for your reply.

I want to describe my problem in detail.

1. I am using sentry on Android.
2. What does this `client ip` mean?  Is it a private ip or a public ip or a unique identifier for customization?
3. Because I have seen some answers on the issue, so does iOS automatically add this client ip?
4. This `client ip` can be set on the `sentry` website? or Android  can only be set in the code?

English is not good, please forgive me if there is disrespectful expression.
Thanks!

**Comment by bretthoerner** [comment]
> I am using sentry on Android.

Ah, then you should be able to set it in the context before you send a message, and not worry about clearing it?

> What does this `client ip` mean?  Is it a private ip or a public ip or a unique identifier for customization?

I'm not sure what you mean, it's whatever you want it to mean. On an Android application I would assume it's the phone's current ip address, there are some examples here: https://stackoverflow.com/a/13007325/11958

> does iOS automatically add this client ip?

I'm not sure.

> This `client ip` can be set on the `sentry` website? or Android  can only be set in the code?

Only by the SDK, all event data comes directly from the crash itself.

**Comment by Yjnull** [comment]
Thank you very much for your detailed answer, I got it.
