### ISSUE TITLE
Sentry compatibility issue with Gradle, Timber, Android SDK

### ISSUE THREAD

**Issue by dainius1984** [getsentry/sentry-java#680]
Hi,

We receive a crash when using following sentry: 

Timber version: 4.7.1

sentry version 1.7.16

and gradle version 2.3.2

We used Android SDK -  https://docs.sentry.io/clients/java/modules/android/

[log (6).txt](https://github.com/getsentry/sentry-java/files/2839669/log.6.txt)

Attaching log file,

Regards,

Marcin

**Comment by ninniuz** [comment]
The errors shown in the log are coming from custom lint checks provided by Timber (https://github.com/JakeWharton/timber/tree/master/android-lint).

It's failing on retrieving the `UastScanner` class which is available from AGP 3.0.0 on (https://github.com/JakeWharton/timber/issues/275).

Is 2.3.2 the version of the Android Gradle Plugin used in the project?

Anyway, this is not a Sentry issue.

**Comment by bruno-garcia** [comment]
Closing this since it appears not to be a Sentry issue.
Thanks @ninniuz for verifying.
