### ISSUE TITLE
Feature request: sentry-spring only notifying for exceptions that result in 5xx response

### ISSUE THREAD

**Issue by kilink** [getsentry/sentry-java#681]
It would be great if there were a mechanism to only forward exceptions that resulted in a 5xx HTTP response when using the sentry-spring integration.

For instance, I may have a Spring ExceptionHandler registered that maps an Exception to a "400 Bad Request" or "404 Not Found" response, and I don't really care about seeing such errors in Sentry.

Other people seem to have requested a mechanism for filtering out specific exception types, and I get that I could do that same by adding a ShouldSendEventCallback that filters out unwanted exceptions, but that can become burdensome since it requires me to enumerate and understand all of the exceptions that may be mapped back to non-5xx repsonses.

**Comment by marandaneto** [comment]
@maciejwalkowiak is there a way to do that on v3?

**Comment by maciejwalkowiak** [comment]
We can make it configurable in Spring Boot integration - users could decide if they want `SentryExceptionResolver` to run with the highest priority (turn exceptions into events before any other exception handler is triggered) or with the lowest priority - turn only those exceptions into events that have not been caught by other exception handlers.

**Comment by bruno-garcia** [comment]
Could we expose a callback in the spring integration called `shouldCapture` where we pass the HTTP request data and the user code can inspect (like status code) and return true/false (or more data if relevant)?

**Comment by timtebeek** [comment]
Should @kilink / anyone else watching this issue wish to weigh in: there's now a pull request that might fix this issue: https://github.com/getsentry/sentry-java/pull/1008

**Comment by marandaneto** [comment]
this is going to be released in the next version, please give it a try :)

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.2.0
