### ISSUE TITLE
HttpInterface body field is not correctly generated with HttpInterfaceBinding

### ISSUE THREAD

**Issue by erhangullu** [getsentry/sentry-java#683]
I have managed successfully assign body for Spring Boot project this:  
Created a filter to wrap body in [ContentCachingRequestWrapper](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/ContentCachingRequestWrapper.html)
```kotlin 
@Component
@Order(1)
class ContentCachingRequestFilter : GenericFilterBean() {

    @Throws(IOException::class, ServletException::class)
    override fun doFilter(
        request: ServletRequest,
        response: ServletResponse,
        chain: FilterChain
    ) {
        chain.doFilter(ContentCachingRequestWrapper(request as HttpServletRequest), response)
    }
}
```

Crated body builder class to build http interface manually
```kotlin
class SentryBodyBuilder : EventBuilderHelper {

    override fun helpBuildingEvent(eventBuilder: EventBuilder) {
        val request =
            (RequestContextHolder.getRequestAttributes() as ServletRequestAttributes).request
                as ContentCachingRequestWrapper

        val body = String(request.contentAsByteArray, Charset.defaultCharset())
        //val body = "{\n\t\"whitelist\":\"ALWAYS\"\n}"
        eventBuilder.withSentryInterface(
            HttpInterface(
                request,
                BasicRemoteAddressResolver(),
                body
            ), true
        )
    }
}
```
And added this builder helper to client:
```kotlin
Sentry.getStoredClient().addBuilderHelper(SentryBodyBuilder())
```
But in the sentry web interface the body shows like this:
![screen shot 2019-02-26 at 15 57 35](https://user-images.githubusercontent.com/38051212/53428365-f3fbb280-39ea-11e9-992b-09c69ebf3316.png)

And creates the curl command like this: 
![screen shot 2019-02-26 at 15 57 42](https://user-images.githubusercontent.com/38051212/53428388-037afb80-39eb-11e9-9d07-724d8431b2cf.png)

I think the issue is here: https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/marshaller/json/HttpInterfaceBinding.java#L114

Which wraps the given json body in another body field. And causes to display body field incorrectly.

**Comment by bretthoerner** [comment]
Hm, that's just titling the field `body` and putting your body in as the value.

It's nested in another object so that parameters (if provided) can live alongside the `body`:

https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/marshaller/json/HttpInterfaceBinding.java#L116-L124

And it seems like Sentry expects it to be there:

https://github.com/getsentry/sentry/blob/a465319322830eb7e858ca6db94581cc58b9adee/src/sentry/interfaces/http.py#L197

What's the raw JSON for the event look like?

**Comment by erhangullu** [comment]
When I debug I see that my json string like this: 
```
"{\n\t\"whitelist\":\"ALWAYS\"\n}"
```

I think it is safe to assume if the body parameter in `HttpInterface` is set, there won't be any `parameterMap`. Since the parametermap only consist of body parameters and query string.

**Comment by bretthoerner** [comment]
You can have query string and a body, though.

Is that string you pasted not the actual body?

**Comment by erhangullu** [comment]
String is the actual body. This is the curl command I used:
```bash
curl -X PATCH \
  http://localhost:8081/charge-cards/ \
  -H 'Content-Type: application/json' \
  -d '{
	"whitelist":"ALWAYS"
        }'
```

Query strings was showing in body but it is already shown in different field:
https://github.com/getsentry/sentry/blob/a465319322830eb7e858ca6db94581cc58b9adee/src/sentry/interfaces/http.py#L158

I implemented another request wrapper (`ParameterMapFilterRequestWrapper`)thats filters query string parameters from parameterMap. And only used when building event

```kotlin
class SentryBodyBuilder : EventBuilderHelper {
    override fun helpBuildingEvent(eventBuilder: EventBuilder) {
        val request =
            (RequestContextHolder.getRequestAttributes() as ServletRequestAttributes).request
                as ContentCachingRequestWrapper

        val body = String(request.contentAsByteArray, Charset.defaultCharset())
        eventBuilder.withSentryInterface(
            HttpInterface(
                ParameterMapFilterRequestWrapper(request),
                BasicRemoteAddressResolver(),
                body
            ), true
        )
    }
}
```

![screen shot 2019-02-27 at 17 13 29](https://user-images.githubusercontent.com/38051212/53504881-15c06c80-3ab3-11e9-9eeb-64df162d314e.png)
