### ISSUE TITLE
Using Sentry outside of Servlets (Scala, Finatra)

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [getsentry/sentry-java#685]
We would like to be able to add sentry to our Finatra services, but from my light investigation it appears to be tightly coupled to java servlet servers right now. The httpinterface seems to be tied up in the event creation and serialization which is problematic for us since it references implementation details like `javax.servlet.http.HttpServletRequest`directly. 

Which classes already support the customization I need and which should I look at modifying? 

If possible I'd like to get this work back into open source client and not maintain a fork.

**Comment by bretthoerner** [comment]
This would be great.

So I think the primary issue is that we have this `ConextManager` interface with only a couple simple implementations, like this: https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/context/ThreadLocalContextManager.java

We'd need to have a `ContextManager` impl that would work for Finatra, which means handling async and requests moving between threads (right?), and we may have to change the `ContextManager` interface itself to support that.

And I guess we'd also allow you to set an interface (like `HttpInterface`) on the context, so you could provide HTTP info for the request?

**Comment by chris-smith-zocdoc** [comment]
Finatra has its own way of handling context which isn't thread dependent, so having a new implementation of ContextManager could work. 

Is `Context` thread safe? Finatra expects items placed in their context to be immutable (which sentry's context can't be). Finatra expects this because everything is async in Finata, Futures can execute concurrently but share the same parent context. Forcing sentry's context to be thread safe is the next best thing.

We need some way of providing the details of the http request, I guess that could go on the context class, I'm not really familiar with sentry's codebase yet.

**Comment by bretthoerner** [comment]
We synchronize most of `Context`, it looks like a few things need to be handled.

At the end of the day there is a helper that pushes context data onto the event: https://github.com/getsentry/sentry-java/blob/9807197352a023900907d36a1b0b1cbc0ee4d617/sentry/src/main/java/io/sentry/event/helper/ContextBuilderHelper.java#L34

So if we added an HttpInterface field to the Context we could hopefully let you stuff it onto the event: https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/event/interfaces/HttpInterface.java

**Comment by chris-smith-zocdoc** [comment]
Despite its name, `HttpInterface` is actually a class, and we can't use it directly because it is tied to the servlet classes. I think need to rename this class to `ServletHttpAdapter` or similar and make a real interface that can be placed on `Context`

**Comment by bretthoerner** [comment]
Yeah, the name isn't meant to be in regards to Java, but rather to what we call "Sentry Interfaces": https://docs.sentry.io/development/sdk-dev/interfaces/http/

What I meant is that I think we can store the HTTP information in the Context, and then in the ContextBuilderHelper we can do something like this:

```
        eventBuilder.withSentryInterface(
                new HttpInterface(...)
        )
```

Which would put the HTTP data into the event.

Maybe Context should allow the user to provide SentryInterface implementations directly, and those are all added to the event?

**Comment by chris-smith-zocdoc** [comment]
Ah yes, I think that approach should work

**Comment by Falmarri** [comment]
In terms of handling the context, I use sentry in akka-http application and created a custom context manager for Kamon, which is what we use for tracing and such.

```
/**
 * A context manager that proxies to the Kamon thread storage, so that it can be carried around with threads
 */
public class KamonContextManager implements ContextManager {

    /**
     * Do not use. Consider this private
     */
    public static Key<Context> localKey = Key.local("sentryContext", null);

    public KamonContextManager() { }

    @Override
    public Context getContext() {
        Context context = Kamon.currentContext().get(localKey);
        if (context == null){
            context = new Context();
            Kamon.storeContext(
                Kamon.currentContext().withKey(localKey, context)
            );
        }
        return context;

    }

    @Override
    public void clear() {
        getContext().clear();
    }
}
```

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
