### ISSUE TITLE
A proguard mapping file does not contain line info. 

### ISSUE THREAD

**Issue by Bresiu** [getsentry/sentry-java#688]
I am using `io.sentry:sentry-android-gradle-plugin:1.7.22` Sentry Gradle plugin and `r8` code shrinker. Proguard has `-keepattributes LineNumberTable,SourceFile`.

During `assembleRelease` mappings are sent correctly:

```
compressing mappings
> uploading mappings
> Uploaded a total of 1 new mapping files
Newly uploaded debug symbols:
  ae8513b1-0c13-569e-8f19-1107bcb82010
```

When exception occurs, on Sentry I see that there was 1 error encountered while processing event:

> A proguard mapping file does not contain line info. 
> Mapping Uuid	
> ae8513b1-0c13-569e-8f19-1107bcb82010

And stack trace is not retraced.
Can you give me hints what can be wrong?

**Comment by ninniuz** [comment]
Does your mapping.txt file have line numbers in it? (you never know :P)
Are you using Sentry.io or a self hosted server?

P.S. not sure whether version `1.7.22` has been released yet, did you mean `1.7.21`?

**Comment by Bresiu** [comment]
@ninniuz 
> Does your mapping.txt file have line numbers in it? (you never know :P)

I think so, here are few example lines from generated proguard:

```
# compiler: R8
# compiler_version: 1.3.54
# min_api: 23
android.support.v4.graphics.drawable.IconCompatParcelizer -> android.support.v4.graphics.drawable.IconCompatParcelizer:
    1:1:void <init>():10:10 -> <init>
    1:1:androidx.core.graphics.drawable.IconCompat read(androidx.versionedparcelable.VersionedParcel):12:12 -> read
    1:1:void write(androidx.core.graphics.drawable.IconCompat,androidx.versionedparcelable.VersionedParcel):16:16 -> write
android.support.v4.media.MediaBrowserCompat$CustomActionCallback -> android.support.v4.media.a:
    void onError(java.lang.String,android.os.Bundle,android.os.Bundle) -> a
    void onProgressUpdate(java.lang.String,android.os.Bundle,android.os.Bundle) -> b
    void onResult(java.lang.String,android.os.Bundle,android.os.Bundle) -> c
android.support.v4.media.MediaBrowserCompat$CustomActionResultReceiver -> android.support.v4.media.MediaBrowserCompat$CustomActionResultReceiver:
    android.os.Bundle mExtras -> e
    android.support.v4.media.MediaBrowserCompat$CustomActionCallback mCallback -> f
    java.lang.String mAction -> d
    1:1:void onReceiveResult(int,android.os.Bundle):2310:2310 -> a
    2:2:void onReceiveResult(int,android.os.Bundle):2313:2313 -> a
    3:3:void onReceiveResult(int,android.os.Bundle):2325:2325 -> a
    4:4:void onReceiveResult(int,android.os.Bundle):2316:2316 -> a
    5:5:void onReceiveResult(int,android.os.Bundle):2319:2319 -> a
    6:6:void onReceiveResult(int,android.os.Bundle):2322:2322 -> a
```


> Are you using Sentry.io or a self hosted server?

Self hosted server

> P.S. not sure whether version `1.7.22` has been released yet, did you mean `1.7.21`?

Yes, my mistake. I am using the newest version released: `1.7.21`

**Comment by ninniuz** [comment]
> > Are you using Sentry.io or a self hosted server?
> 
> Self hosted server
> 

As far as I understood R8 support requires updates on the backend as well. I read it has been deployed to Sentry.io but I don't know how to update a self hosted server.

@bretthoerner can you please help us?

**Comment by bretthoerner** [comment]
Yeah R8 required backend changes, it only works on Sentry `master` currently.

**Comment by Bresiu** [comment]
Thanks for your help.

**Comment by realdadfish** [comment]
This is this PR, right? https://github.com/getsentry/sentry/pull/11906
So, people could just apply this patch to their local installation and not wait for Sentry 9.1 to be released to get support for R8 in the backend?

**Comment by filipkowicz** [comment]
@realdadfish it that working for you? 
for me even after updating to sentry 9.1 (on premise) error `A proguard mapping file does not contain line info` still occurs
mapping file tested with local proguard and same stacktrace - works well locally. Could you confirm that it is in 9.1.0

**Comment by realdadfish** [comment]
It worked in 9.1, but it broke again due to different reasons (incompatibility with AGP 3.4, #304, the upload therefor fails). I urge the maintainers since two weeks (#709) to release a fixed version, as two people from the community already independently provided a patch (#705 and #706), but they're playing the dead duck game.

**Comment by filipkowicz** [comment]
@realdadfish I see you mentioned bugs related to gradle plugin. Currently I'm doing it by hand (own gradle task) with `sentry-cli` so it's generated correctly and send to backend. sentry as far as i understand is able to match mapping file with log - by uuid but it cant retrace it correctly because of R8

**Comment by ArtemWidelab** [comment]
Looks like issues still occurs. If no, point me to the solution, please.

- I have a self-hosted sentry - 9.1.1
- I have an Android app with plugin - 1.7.27
- I have r8 enabled
- I see debug files on "Debug Information Files" page
- I see the obfuscated stack trace
- I see "A proguard mapping file does not contain line info"

**Comment by ninniuz** [comment]
@ArtemWidelab just tried myself on Sentry.io and everything seems to be ok.

Which version of AGP?
Version of R8 compiler?

@bruno-garcia

**Comment by bruno-garcia** [comment]
The Sentry Android Gradle Plugin version 1.7.27 has support to it. We've added back in February: https://github.com/getsentry/sentry-java/pull/678
There were changes to the server too at the time. But 9.1.1 is from April so surely includes it.
Could you please share a repro so we investigate it further?

**Comment by ArtemWidelab** [comment]
@ninniuz @bruno-garcia 
AS - 3.5
AGP - 3.5.0
R8 compiler - 1.5.64

body: [{"objectName": "proguard-mapping", "symbolType": "proguard", "dateCreated": "2019-09-17T08:40:46.997Z", "debugId": "f24b8da5-f715-5994-af32-8787ac7fc4f6", "data": {"features": ["mapping"]}, "id": "10", "size": 18321267, "sha1": "39c4274f0d767bb7b8622fce273d7c19fc4bbb18", "uuid": "f24b8da5-f715-5994-af32-8787ac7fc4f6", "cpuName": "any", "headers": {"Content-Type": "text/x-proguard+plain"}, "codeId": null}]

What else can I share?

**Comment by bruno-garcia** [comment]
As @ninniuz mentioned it worked against sentry.io it might be that it's an issue with sentry 9.1.1.
It'd hard to tell but since we can't reproduce in the current version of bits I'd suggest upgrading Sentry first.
