### ISSUE TITLE
Character limit in messages

### ISSUE THREAD

**Issue by pscheerer** [getsentry/sentry-java#689]
I want to send a java thread dump. But there is a character limit in the field "message". Other fields do not work as well. How is it possible to send more information to sentry?

**Comment by bretthoerner** [comment]
We'll need to add the threads interface to the `sentry-java` SDK: https://docs.sentry.io/development/sdk-dev/interfaces/threads/

We'll need one of these: https://github.com/getsentry/sentry-java/tree/master/sentry/src/main/java/io/sentry/event/interfaces

And one of these: https://github.com/getsentry/sentry-java/tree/master/sentry/src/main/java/io/sentry/marshaller/json

**Comment by marandaneto** [comment]
theres no limit in the message field anymore, also threads interface are available
