### ISSUE TITLE
1.7.22,sentry reported an error: Missing uploaded file (http status: 400)

### ISSUE THREAD

**Issue by andasl** [getsentry/sentry-java#694]
implementation 'io.sentry:sentry-android:1.7.22'
    implementation 'org.slf4j:slf4j-nop:1.7.25'

build variants:  release
（but debug is run success ）

error: API request failed
  caused by: sentry reported an error: Missing uploaded file (http status: 400)

**Comment by bruno-garcia** [comment]
@andasl It'll be tricky to find out what's going on with the information you gave us so far.
Could you please give us a repro?
I'm not sure what your code is trying to send to Sentry.

**Comment by bruno-garcia** [comment]
@andasl Just noticed you're not on the latest version.
[We've released lots of fixed on `v1.7.23`](https://github.com/getsentry/sentry-java/releases/tag/v1.7.23), could you please make sure you're on this version?

Feel free to reopen if the issue persists.
