### ISSUE TITLE
DSN Object Equals Method Broken

### ISSUE THREAD

**Issue by mayt017** [getsentry/sentry-java#695]
The DSN Object's equals method currently does not work as expected. Because the secret key is deprecated from the DSN, it is no longer required for a valid DSN object, however if the DSN is null, two equal DSN objects will throw a null pointer exception on the string comparison of these keys because null does not have an equals method. This can be resolved by using the Java standard library `Objects.equals` method as shown below.

### Broken Code Dsn.equals line 293
```java
        if (!secretKey.equals(dsn.secretKey)) {
            return false;
        }
```
### Example
```kotlin
    @Test(expected = NullPointerException::class)
    fun selfContainedCompleteExample() {
        val dsn1 = Dsn("http://publickey@host.com/0")
        val dsn2 = Dsn("http://publickey@host.com/0")
        assertThat(dsn1, equalTo(dsn2))
    }
```

### Solution
```java
       if (!Objects.equals(secretKey, dsn.secretKey)) {
            return false;
        }
```

### Solution Proof
```kotlin
    @Test
    fun solutionProof() {
        assertThat(true, equalTo(Objects.equals("test", "test")))
        assertThat(true, equalTo(Objects.equals(null, null)))
    }
```

**Comment by ninniuz** [comment]
`Object.equals` is not available on Android < 19. 
Maybe it is better to just add a simple utility that mimics it.
@bretthoerner there is no min API level enforced on Sentry for Android, isn't there?

**Comment by mayt017** [comment]
@ninniuz I can amend the PR to add this static method. It is a trivial change. Would you prefer a static method added to an existing String Utils class (if there is one)? Alternatively, I could simply modify the actual code to include null checks before evaluating `equals`.

**Comment by ninniuz** [comment]
@mayt017 I think either way would do ok (but you should probably wait for project owners to give advice).
There is a `Util` class which is used to, among other things, check if a string is `null` or empty (https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/util/Util.java#L26).
Maybe something like `Util.equals(Object a, Object b)`?

**Comment by mayt017** [comment]
That sounds good. I will amend the PR and await further instructions/advice from owners.

**Comment by justacodefan** [comment]
Closing as the PR is merged.
