### ISSUE TITLE
Sentry not populating context

### ISSUE THREAD

**Issue by nicolabeghin** [getsentry/sentry-java#697]
Hi everyone
I would like to understand if this is expected behavior or not: when using the Sentry Java client (on a desktop JavaFX app) we don't get the OS statistics (like OS version, available RAM, etc)

ref. https://docs.sentry.io/development/sdk-dev/interfaces/contexts/

is this supposed to happen? do we need to manually gather the info and populate the context to be sent?

thanks

**Comment by marandaneto** [comment]
yes, we don't collect device info automatically, for Desktop Apps, yet.

**Comment by adinauer** [comment]
Closed in favor of https://github.com/getsentry/sentry-java/issues/697

**Comment by adinauer** [comment]
Thanks @marandaneto the new issue is https://github.com/getsentry/sentry-java/issues/1996
