### ISSUE TITLE
Filter hibernate proxies from in app frames

### ISSUE THREAD

**Issue by SzczepanskiPeter** [getsentry/sentry-java#698]
Problem:

Hibernate proxies generate a non-deterministic class name which interferes with Sentry's event groupings.

Solution:

Add regex pattern to `in app` blacklist to filter matching regex exceptions from `in app` frames.

Generated Class: `Foo$HibernateProxy$SzXDkaYB`

**Comment by bruno-garcia** [comment]
@justacodefan's PR #719 was merged and published.
Please give it a try with the SDK version:
https://github.com/getsentry/sentry-java/releases/tag/v1.7.23

Feel free to reopen if the issue persists.
