### ISSUE TITLE
Gradle 5.5.1 creates strange directory on build.

### ISSUE THREAD

**Issue by mihakrajnc** [getsentry/sentry-java#703]
I just updated gradle to 5.5.1, Android Studio to 3.4 and Android Gradle Plugin to 3.4.0.

When doing a full build (`gradlew assemble`) Sentry (or what I assume is Sentry) creates a weird directory at the root of my project, with a `sentry-debug-meta.properties` file buried in it.

The dirctory that is created has this name:
`property(interface org.gradle.api.file.Directory, map(property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, ` (Yes that's the actual name of the directory).

Then the sub directories are the "full absolute path to my project", ending with a directory named `build))))`

![Screenshot 2019-04-23 at 14 12 21](https://user-images.githubusercontent.com/8857844/56580019-e4a37a80-65d1-11e9-8021-bf39181a2f1a.png)

**Comment by ninniuz** [comment]
This is a duplicate of #702

**Comment by mihakrajnc** [comment]
Ah damn, didn't notice it when searching :(
