### ISSUE TITLE
Stacktrace truncated

### ISSUE THREAD

**Issue by nicolabeghin** [getsentry/sentry-java#704]
Don't know if this is expected behavior or not, but when a stacktrace is sent through Sentry it's not preserved in full but truncated at around 120 chars.

**Comment by valinz** [comment]
When the message length is exceeding max message length, sentry will truncate the message ensuring that the maximum length isn't reached.  You can try to config larger  `maxmessagelength`.

**Comment by bruno-garcia** [comment]
I hope this was clarified. Feel free to reopen otherwise.
