### ISSUE TITLE
Performance / reliability properties of sentry-java & sentry-log4j?

### ISSUE THREAD

**Issue by joshrosen-stripe** [getsentry/sentry-java#712]
I'm interested in adding a `sentry-java` integration to a latency-sensitive production application via the `sentry-log4j` integration.

I have a few questions about performance and reliability properties of this library, mostly concerned around mitigating a few specific threats:

- What happens if the Sentry server is either completely unreachable or responds very slowly?
- Are all queues / thread pools / buffers / other forms of state bounded in size?
- Are all threads created by Sentry configured as daemon threads?
- Is there support for client-side rate-limiting / sampling to limit overall resource consumption?
  - My concern is that huge surges of exceptions could place excessive load on the service.
  - If such limiting exists, how early in the pipeline is it performed? For `sentry-log4j`, is this performed before or after collecting stacktraces?
- For `sentry-log4j`, is any significant work performed while holding the global Log4J  1.x appender lock (which is implicitly held during append calls)? 
  - In the past I've seen performance issues where a slow custom logger stalls the entire application by blocking while holding the Log4J lock.
  - #660 seems related to this concern.
- Can I force Sentry initialization to be performed eagerly at the start of my application?
- Can I disable the automatic registration of a default uncaught exception hander?
  - My concern is non-deterministic initialization order: I would prefer to explicitly register this myself. 
- Are there any performance benchmarks for this library?

I'll try to answer these questions by reading the source, but I also wanted to ask here because I suspect other prospective users might have similar questions.

**Comment by justacodefan** [comment]
I don't believe there are significant performance benchmarks for `sentry-java` and `sentry-log4j` but I can try and answer most of your questions. Aside from some additional CPU overhead and some I/O, there should be a negligible impact on performance but YMMV depending on whether you're referring to milliseconds or microseconds..

Some answers:

> What happens if the Sentry server is either completely unreachable or responds very slowly?

Events are sent from a Sentry managed single thread pool executor. Your application should not be impacted.

> Are all queues / thread pools / buffers / other forms of state bounded in size?

The only threads that Sentry creates are:

1. A thread for the managing thread, responsible for collecting the information when an exception is thrown (stack traces, preparing the event to send, etc).
2. A single thread executor (as noted above) to actually send the events across a connection

Additionally, you can also create your own connection and attach it to your SentryClient to perform however you'd like.

> Is there support for client-side rate-limiting / sampling to limit overall resource consumption?

No, but, events can be buffered to disk and sent asynchronously once the application restarts (in case of a fatal error, for example). Again, you could implement this in your own connection if you'd like. Finally, this would happen after the collection of stacktraces from `log4j`.

The issue you've mentioned should be addressed this week where we'll move to an `AsyncAppender` and hopefully avoiding this problem to begin with.

> Can I force Sentry initialization to be performed eagerly at the start of my application?

Yes, you can call `Sentry.init(dsn)` yourself at any point. Your main method sounds like a good place.

> Can I disable the automatic registration of a default uncaught exception hander?

Yes, see the DSN options available: https://docs.sentry.io/clients/java/config/#uncaught-exception-handler 

Additionally, you can register one yourself at a later time (by calling `SentryUncaughtExceptionHandler.setup()`) or create your own that simply delegates to Sentry (don't forget to call any original handlers as well).

Hope that helps, please let me know if you have more questions or would like further pointers to DSN options.

**Comment by joshrosen-stripe** [comment]
Thanks; this is very helpful! I'll re-open if I have further questions.
