### ISSUE TITLE
Gradle Plugin Not handling flavors/dimensions properly

### ISSUE THREAD

**Issue by nicusorflorin** [getsentry/sentry-java#716]
When you have multiple flavors/dimensions in the project, the sentry.properties file does not work when it is placed in a folder with a combination of flavors from different dimensions.

CC: @justacodefan

**Comment by justacodefan** [comment]
Thanks for reporting this. Would you be able to create a sample project that reproduces the issue?

**Comment by nicusorflorin** [comment]
I would be able, but I do not have the necessary time right now, we are having an upcoming deadline for the project containing this issue and we still have a lot of other tasks to complete.
The basic steps would be:
1.Create a project in android studio: “AndroidProject”
2.Create 2 flavor dimensions: “dimension1”, “dimension2”
3.Create 3 flavors: “flavor1” and set “dimension1” for it
		 “flavor2” and set “dimension1” for it
		 “flavor3” and set “dimension2” for it
4.Create 2 sentry projects: “SentryProject1” and “SentryProject2”
5.Set “SentryProject1” data in sentry.properties in the root folder of “AndroidProject”
6.Set “SentryProject2” data in sentry.properties in the source folder for one flavor/combination of flavors, ex: “..AndroidProject/app/src/flavor3”
7.Set build variant to something including flavor3(all of them should since we got only one flavor with “dimension2”), release variant.
8.Set autoupload for proguard mapping.
9.Compile
10.Notice that the mapping goes to “SentryProject1” instead of “SentryProject2”

Let me know if there is anything else I can do to help.

**Comment by nesterov-n** [comment]
Seems to be related to #671

**Comment by nicusorflorin** [comment]
yes, indeed it does, i'm on version 1.7.22

**Comment by nicusorflorin** [comment]
any progress on this?

**Comment by nicusorflorin** [comment]
it's been a month, this is a blocker for us... and still no update on it

**Comment by bruno-garcia** [comment]
@nicusorflorin Sorry for the delay.
I'm taking a look at this. At this time as the doc mentions we support only 1 `sentry.properties`.

On possible ways to get this fixed is to upload multiple `mappings.txt` to your project but whether we'll support multiple sentry projects during the same gradle build it's something we need to investigate further.

Perhaps adding the dimension and variation to the events would be a solution. This way on the same dashboard you can filter out your events with any combination you need even though they are under the same project.

Also, it would speed things up **a lot** if you could you please provide a repro.

**Comment by nicusorflorin** [comment]
the single sentry project idea is not a solution for us. It does not need to support multiple sentry projects during the same gradle build, once a build variant has been chosen it should go on it's coresponding sentry project. from my understanding this was already attempted in https://github.com/getsentry/sentry-java/releases/tag/v1.7.18 but it doesn't seem to be working properly, repro steps i provided in an above comment, but i will attempt to create a test project tomorrow for you guys

**Comment by nicusorflorin** [comment]
@justacodefan @bruno-garcia 
[SentryIssue716.zip](https://github.com/getsentry/sentry-java/files/3381133/SentryIssue716.zip)

as you can see i added flavor level sentry.properties in their src folders, and they are not recognized, even though there was a pr merged that says that it should, also as far as i could tell by looking in the source files of the plugin, sentry is looking in flavor src folders for the properties file, but for some reason doesn't recognize it or something

**Comment by bruno-garcia** [comment]
@nicusorflorin what PR are you referring to? To my knowledge we don't support multiple/nested `sentry.properties` files.

**Comment by nicusorflorin** [comment]
The issue nesterov mentions contains a version of the plugin that was supposed to have this feature. 1.7.18

The single project is not a solution because our project will have a flavor per client we cannot allow them to track their issues in the same sentry project. 

As I said, it seems to me from the source code that the plugin is already looking in the flavor src folder for the properties but it's ignoring it.

**Comment by nicusorflorin** [comment]
@bruno-garcia nvm that issue is about the build types, but there is someone commenting there that posted the paths the plugin should look into, and it is looking in the flavor folders first

**Comment by bruno-garcia** [comment]
> The single project is not a solution because our project will have a flavor per client we cannot allow them to track their issues in the same sentry project.

I'm sorry I didn't quite catch: What do you mean by 'track their issues in the same sentry project':
How do your clients track their issues in your Sentry projects?

**Comment by nicusorflorin** [comment]
Basically depending on the client, we would give them access to the project. And we cannot give access to the same project to different clients. If supporting multiple sentry.properties is an issue for you, another solution would be to be able to add properties to flavors for project name and dns, similar to the ones added for buildTypes

**Comment by bruno-garcia** [comment]
@nicusorflorin That's right that #671 already supports multiple `sentry.properties` but in your example you are defining a `dsn` which is not supported by `sentry.properties`. All the plugin does as of now it is to pass that to `sentry-cli` which reads properties like org Id, auth token and project id.

How are you passing the `DSN` to `Sentry.Init` as of now? We'd need to create a mechanism to define a `DSN` per dimension/flavor.

**Comment by nicusorflorin** [comment]
@bruno-garcia i am using the @string.xml of the project, which can be defined at flavor level. 
But really the fasted and easiest way to do it would be to add the properties to the flavors level, that you are already using for the buildTypes. either way would suit our needs though.

**Comment by bruno-garcia** [comment]
@nicusorflorin If you're using `@string.xml` and can already pick the right `DSN` by the right variation, then this really should be working already. 

I've tested having a `sentry.properties` inside the variation folder and it gets picked up and handed over to `sentry-cli` correctly. There must be something else going on with your setup. 

Are you sure you don't rely on the `dsn` you wrote in the `sentry.properties` file?
The example you gave us has a `dsn` in `sentry.properties`. Please remote that since it `DSN` means nothing to `sentry-cli` and it's not used when uploading the `proguard` mapping file. For that, we only need `org id`, `project id` and `auth token`.

Your repro attached doesn't really reproduce the issue. It simply shows a dimension/flavor setup and the `sentry.properties` inside one of the variations. I was able to use such properties file without issues.

**Comment by nicusorflorin** [comment]
@bruno-garcia well the dsn does get picked up, but as you said the proguard mapping uses the project id, which is defined in the sentry.properties . when you run the release build you can see in the build logs that the mapping doesn't not get uploaded. which means the sentry.properties is not pickedup. the one that is picked up is the one in the root folder of the app, which is mandatory to be defined, otherwise it doesn't compile

**Comment by bruno-garcia** [comment]
Ok I understand your situation. But I could not reproduce that. In my case it does get picked up. 

Could you please provide us with a repro so we can debug?

**Comment by nicusorflorin** [comment]
@bruno-garcia Are you sure? It gets picked on both sentrytest and sentrytest1 flavor? In the sample i send you only test1 gets picked. because i used it in the root folder sentry.properties file.

Basically, I switched the build variant to sentrytest1FreeRelease, ran a build on it, noticed that the mapping did get uploaded(because of the root folder properties), then i switched to build variant to sentrytestFreeRelease, ran a build, noticed that it's mapping didn't get uploaded. And that was it

**Comment by bruno-garcia** [comment]
It looks like the name of your folders are not matching what gradle looks for.

With two dimensions and two flavors, gradle ends up concatenating a combination of `flavorA` + `flavorB` where flavorA represents all flavors of the dimension A and flavorB all from dimension B.

Your repro has:

```gradle
    flavorDimensions("default", "apptype")

    productFlavors {
        create("free") {
            setDimension("apptype")
        }

        create("iap") {
            setDimension("apptype")
        }

        create("sentrytest") {
            applicationId = "com.sentry.testone"
            setDimension("default")
            versionCode = 1
            versionName = "1.0.0"
        }

        create("sentrytest1") {
            applicationId = "com.sentry.test"
            setDimension("default")
            versionCode = 1
            versionName = "1.0.0"
        }
``` 

So the folders gradle expects for the variant are:

`app/src/sentrytestFree/`
`app/src/sentrytestIap/`
`app/src/sentrytest1Iap/`
`app/src/sentrytest1Free`

If I rename one of your directories to the folder name above it works properly:

```
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/app/src/sentrytestFree/sentry.properties
Found at: /Users/bruno/Downloads/SentryIssue716/app/src/sentrytestFree/sentry.properties
```
Logging was added by me so you won't be seeing it unfortunately.

Before I was seeing:

```
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/app/src/release/sentry.properties
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/app/src/sentrytestFree/sentry.properties
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/app/src/release/sentrytestFree/sentry.properties
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/app/src/sentrytestFree/release/sentry.properties
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/src/release/sentry.properties
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/src/sentrytestFree/sentry.properties
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/src/release/sentrytestFree/sentry.properties
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/src/sentrytestFree/release/sentry.properties
Looking for sentry.properties in: /Users/bruno/Downloads/SentryIssue716/sentry.properties
Found at: /Users/bruno/Downloads/SentryIssue716/sentry.properties
```

**Comment by nicusorflorin** [comment]
well the flavor alone folders works for Android resources, and we use them to define flavor level data, that is independent of the build variant, can the plugin be modified to look into the flavor folder?

**Comment by bruno-garcia** [comment]
That folder is what gradle is returning from `variant.flavorName`. I enumerated all values of the `variant` and there was no path to simply the flavor name without having the dimension appended.

**Comment by nicusorflorin** [comment]
@bruno-garcia still, we need this to work without adding the same sentry.properties file to 4 locations, either make it work for flavorName or add properties for flavor level in groovy?

**Comment by bruno-garcia** [comment]
@nicusorflorin I understand. But if the API gradle gives us to get the `flavorName` includes the `dimension`, either this is a bug on `gradle` or it simply means once you add dimensions, you'd need to define values per flavor+dimension as opposed to only flavor.

`flavorName` would return the value as you expect if you don't use dimensions, is that correct?

**Comment by nicusorflorin** [comment]
@bruno-garcia I believe so, I'm not in the office anymore so I can't check, but the sample should show you exactly how it should behave.

**Comment by bruno-garcia** [comment]
@nicusorflorin I've merged a PR #737 following a suggesting from @ninniuz.

The code will look for `sentry.properties` in the `product flavor` directory. That is, if it didn't find it in the `flavor` directory. Super confusing but Gradle concatenates flavor names X dimensions.

**Comment by bruno-garcia** [comment]
@nicusorflorin Could you please try the [latest release 1.7.24](https://github.com/getsentry/sentry-java/releases/tag/v1.7.24)?

**Comment by nicusorflorin** [comment]
@bruno-garcia it seems to be working now, thanks!

**Comment by bruno-garcia** [comment]
Great to hear that. Thanks for raising this and helping through the fix.
