### ISSUE TITLE
Using sentry-logback how to set Dsn for different application Env ?

### ISSUE THREAD

**Issue by fanlushuai** [getsentry/sentry-java#723]

**Comment by fanlushuai** [comment]
I use spring boot and logback.

**Comment by fanlushuai** [comment]
I have found the way to set。
io.sentry.Sentry#getStoredClient  is the global init location.use io.sentry.Sentry#setStoredClient to change the init way ，replace init() by int(dsn)

**Comment by bruno-garcia** [comment]
Glad you sort it out.
