### ISSUE TITLE
[BUG] Sentry agent crashes program

### ISSUE THREAD

**Issue by andykais** [getsentry/sentry-java#728]
Hi all,

My team and I ran into a bug using the beta sentry agent where java would crash when trying to inspect certain variables in the stack. I have created a minimal repro of the issue here:

https://github.com/andykais/sentry-crash-reproduction

[edit]
adding some more environment info

sentry agent `v1.7.16`: https://github.com/getsentry/sentry-java/releases/tag/v1.7.16
```
java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```

reproduced on both Ubuntu `16.04 LTS` and macOS High Sierra

**Comment by bruno-garcia** [comment]
Thanks for raising this. I've opened a PR to address this issue.
The repro was extremely helpful. I used it to verify the patch solved the issue.

Please note I had to add `jackson` to `build.gradle` in order to run against my patch which was off of master instead of 1.7.16.

```gradle
    compile 'com.fasterxml.jackson.core:jackson-core:2.5.2'
```

**Comment by andykais** [comment]
Wow that was fast! Thanks guys! 🎉
