### ISSUE TITLE
Allow programmaticly setting environment

### ISSUE THREAD

**Issue by kyleramey** [getsentry/sentry-java#732]
Currently, it seems environment is only configurable during `Sentry.init()`. Would it be possible to get a method to modify the environment after initialization?

**Comment by bruno-garcia** [comment]
Could you please describe your use case? 
What scenario the environment is only available once the app is already running?

**Comment by kyleramey** [comment]
I have found that calling `Sentry.getContext().addTag("environment", envString) already works to accomplish this.

The use case is an Android app which is primarily a WebView where the environment is considered to be the webserver it's hitting. It can be changed without closing the app, so we would like to be able to filter by environment the issue occurred on.

**Comment by bruno-garcia** [comment]
Great to hear you've found a work around.
If this comes up again we'll point users to your solution unless it becomes obvious a better support to it should be added.
