### ISSUE TITLE
Android proguard mapping file - Error: Missing uploaded file

### ISSUE THREAD

**Issue by stephenrjohnson** [getsentry/sentry-java#734]
I'm running the sentry Gradle task on my build and on Jenkins and getting the following issue:

14:02:15 > Task :app:persistSentryProguardUuidsForReleaseRelease FAILED
14:02:15 INFO 2019-07-10 13:02:13.511351100 +00:00 Loaded config from /root/.sentryclirc
14:02:15 DEBUG 2019-07-10 13:02:13.512602 +00:00 sentry-cli version: 1.40.0, platform: "linux", architecture: "x86_64"
14:02:15 INFO 2019-07-10 13:02:13.513218500 +00:00 sentry-cli was invoked with the following command line: "/tmp/.sentry-cli3045534518321644862.exe" "upload-proguard" "--android-manifest" "/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml" "--write-properties" "/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties" "/var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt"
14:02:15 DEBUG 2019-07-10 13:02:13.666236900 +00:00 SHA1 for mapping file '/var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt': '5bbc05c3fc47cac5d312268bc989b361730f5e33'
14:02:15 > compressing mappings
14:02:15 > uploading mappings
14:02:15 DEBUG 2019-07-10 13:02:14.617716800 +00:00 request POST https://sentry.io/api/0/projects/(removed)/(removed)/files/dsyms/
14:02:15 DEBUG 2019-07-10 13:02:14.617765200 +00:00 using token authentication
14:02:15 DEBUG 2019-07-10 13:02:14.617778400 +00:00 sending form data
14:02:15 DEBUG 2019-07-10 13:02:14.617806400 +00:00 retry number 0, max retries: 0
14:02:15 DEBUG 2019-07-10 13:02:15.182969 +00:00 > POST /api/0/projects/(removed)/(removed)/files/dsyms/ HTTP/1.1
14:02:15 DEBUG 2019-07-10 13:02:15.183018500 +00:00 > Host: sentry.io
14:02:15 DEBUG 2019-07-10 13:02:15.183028700 +00:00 > Accept: /
14:02:15 DEBUG 2019-07-10 13:02:15.183039 +00:00 > Connection: TE
14:02:15 DEBUG 2019-07-10 13:02:15.183049100 +00:00 > TE: gzip
14:02:15 DEBUG 2019-07-10 13:02:15.183059600 +00:00 > User-Agent: sentry-cli/1.40.0
14:02:15 DEBUG 2019-07-10 13:02:15.183659500 +00:00 > Authorization: Bearer c10fc922***
14:02:15 DEBUG 2019-07-10 13:02:15.183698500 +00:00 > Content-Length: 1170478
14:02:15 DEBUG 2019-07-10 13:02:15.183713 +00:00 > Content-Type: multipart/form-data; boundary=------------------------
14:02:15 DEBUG 2019-07-10 13:02:15.334689100 +00:00 response status: 400
14:02:15 DEBUG 2019-07-10 13:02:15.334743 +00:00 body: {"detail":"Missing uploaded file"}
14:02:15 DEBUG 2019-07-10 13:02:15.335114900 +00:00 error: running update nagger
14:02:15 DEBUG 2019-07-10 13:02:15.335151 +00:00 skipping update nagger because session is not attended
14:02:15 error: API request failed
14:02:15 caused by: sentry reported an error: Missing uploaded file (http status: 400)
14:02:15 DEBUG 2019-07-10 13:02:15.335419500 +00:00 client close; no transport to shut down (from sentry)
14:02:15
14:02:15 FAILURE: Build failed with an exception.
14:02:15
14:02:15 * What went wrong:
14:02:15 Execution failed for task ':app:persistSentryProguardUuidsForReleaseRelease'.
14:02:15 > Process 'command '/tmp/.sentry-cli3045534518321644862.exe'' finished with non-zero exit value 1

So I logged into the box:

bash-4.4# ls  -lh /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml
-rw-r--r-- 1 root root 16K Jul 10 12:53 /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml
bash-4.4# ls -la /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties
-rw-r--r-- 1 root root 61 Jul 10 13:02 /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties
bash-4.4# ls -lha /var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt
-rw-r--r-- 1 root root 6.3M Jul 10 13:01 /var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt

**Comment by stephenrjohnson** [comment]
Could this be related to https://github.com/getsentry/sentry-java/issues/694 ?

**Comment by ninniuz** [comment]
> Could this be related to #694 ?

Yes it could. 

Do you get the same error if you manually try to upload the mapping file using `sentry-cli`?
If yes, it could be interesting to try with an updated version of `sentry-cli` (I am seeing currently the Sentry Gradle plugin is still using 1.40.0).

In the past, such errors where caused by issues in `sentry-cli`.

**Comment by stephenrjohnson** [comment]
If I run the command manually it works perfectly.

**Comment by stephenrjohnson** [comment]
Created https://github.com/getsentry/sentry-java/pull/735 with an updated sentry-cli version to see if that helps

**Comment by ninniuz** [comment]
@stephenrjohnson you could force the Sentry Gradle plugin to use a custom `sentry-cli` executable at runtime by setting its path in the [`cli.executable` property](https://github.com/getsentry/sentry-java/blob/3cccb1d36324df8c8a60ee46915b1c7d012a3d11/sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L37) inside your project's `sentry.properties` file (i.e. the one that is in your project's root dir).
Can you try this on your CI env?

**Comment by stephenrjohnson** [comment]
Not easily as our docker environment is immutable, but I'll give it a try, may take some time.

**Comment by bruno-garcia** [comment]
`sentry-cli`'s change logs from version 1.40 to 1.46 don't seem to have anything related to the `proguard` mapping upload. The only change sort of relevant is the `curl` version bump but that was to solve a segfault which doesn't happen here.

@ninniuz's right that ideally you'd pin the `sentry-cli` version and run the whole build. This way we can be sure it's only the `sentry-cli` version that's causing the issue. 
Perhaps check-in `sentry-cli` (it's a single binary) and set the path to it in the configuration.

**Comment by stephenrjohnson** [comment]
Still, have the issue 

root@7f79290ed5ad:/tmp# ./sentry-cli -V
sentry-cli 1.46.0

sentry.properties 
cli.executable=/tmp/sentry-cli

INFO    2019-07-11 10:13:33.582950900 +00:00 sentry-cli was invoked with the following command line: "/tmp/sentry-cli" "upload-proguard" "--android-manifest" "/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml" "--write-properties" "/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties" "/var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt"
11:13:35    DEBUG   2019-07-11 10:13:33.841477400 +00:00 SHA1 for mapping file '/var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt': '5bbc05c3fc47cac5d312268bc989b361730f5e33'
11:13:35  > compressing mappings
11:13:35  > uploading mappings
11:13:35    DEBUG   2019-07-11 10:13:35.253928800 +00:00 request POST https://sentry.io/api/0/projects/(removed)/(removed)/files/dsyms/
11:13:35    DEBUG   2019-07-11 10:13:35.253986800 +00:00 using token authentication
11:13:35    DEBUG   2019-07-11 10:13:35.254001700 +00:00 sending form data
11:13:35    DEBUG   2019-07-11 10:13:35.254030300 +00:00 retry number 0, max retries: 0
11:13:35  /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/transforms/proguard/staging/0.jar: D8: Type `libcore.io.Memory` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.c.g.ih$b.a(long, byte)`
11:13:36    DEBUG   2019-07-11 10:13:35.747447400 +00:00 > POST /api/0/projects/(removed)/files/dsyms/ HTTP/1.1
11:13:36    DEBUG   2019-07-11 10:13:35.747523100 +00:00 > Host: sentry.io
11:13:36    DEBUG   2019-07-11 10:13:35.747649500 +00:00 > Accept: */*
11:13:36    DEBUG   2019-07-11 10:13:35.747668300 +00:00 > Connection: TE
11:13:36    DEBUG   2019-07-11 10:13:35.747687100 +00:00 > TE: gzip
11:13:36    DEBUG   2019-07-11 10:13:35.747705400 +00:00 > User-Agent: sentry-cli/1.46.0
11:13:36    DEBUG   2019-07-11 10:13:35.748381300 +00:00 > Authorization: Bearer c10fc922***
11:13:36    DEBUG   2019-07-11 10:13:35.748429800 +00:00 > Content-Length: 1170478
11:13:36    DEBUG   2019-07-11 10:13:35.748445700 +00:00 > Content-Type: multipart/form-data; boundary=------------------------
11:13:36    DEBUG   2019-07-11 10:13:35.898067800 +00:00 response status: 400
11:13:36    DEBUG   2019-07-11 10:13:35.898159 +00:00 body: {"detail":"Missing uploaded file"}
11:13:36    DEBUG   2019-07-11 10:13:35.899670900 +00:00 error: running update nagger
11:13:36    DEBUG   2019-07-11 10:13:35.899734100 +00:00 skipping update nagger because session is not attended
11:13:36  error: API request failed
11:13:36    caused by: sentry reported an error: Missing uploaded file (http status: 400)
11:13:36    DEBUG   2019-07-11 10:13:35.900485 +00:00 client close; no transport to shut down  (from sentry)
11:13:36  
11:13:36  > Task :app:persistSentryProguardUuidsForReleaseRelease FAILED

**Comment by ninniuz** [comment]
> If I run the sentry-cli command manually it works perfectly, although that was with a newer sentry-cli.

You were running `sentry-cli` command manually from the same docker container that is failing on Gradle, weren't you?

What is odd is that, from the log output, `sentry-cli` is sending some bytes (Content-Length: 1170478) over the wire.

**Comment by stephenrjohnson** [comment]
I spawned the same container, downloaded the same sentry-cli client:

SENTRY_AUTH_TOKEN=(removed) /tmp/sentry-cli upload-proguard -p (removed) --org (removed) --android-manifest /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/staging/AndroidManifest.xml --write-properties /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/staging/mergeStagingAssets/out/sentry-debug-meta.properties /var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/staging/mapping.txt
> compressing mappings
> uploading mappings
> Uploaded a total of 0 new mapping files
* Closing connection 0

root@2147194ca912:/# /tmp/sentry-cli -V
sentry-cli 1.46.0

**Comment by mitsuhiko** [comment]
For some reason the multipart boundary seems incomplete. After the dashes there should be a random hex string. Could it be that some part of the debug information was cut off?

**Comment by stephenrjohnson** [comment]
Yea sorry that was removed in copy and paste error.  The boundary did have a random hex string after it.

**Comment by bruno-garcia** [comment]
Could you please set the environment variable `SENTRY_LOG_LEVEL` to `true`?
We've also expected to see the response headers but they are not included in your log. It's prefixed with `<` as opposed to `>` of the request headers.

Lastly, it'd be great if we had a repro of it to debug locally.

**Comment by stephenrjohnson** [comment]
The problem is that this bug only happens on this one repo in our organisation and only for a very specific set of circumstances. Unfortunately, I  can't share the repository.
I'm more than willing to run any commands that you want etc, it's strange as all the other products we build using this Gradle / Sentry setup work perfectly.  I can inform you that when we used to build this product and push the map files to our internal Sentry system it used to work and now we have moved to the hosted system we have been experiencing this problem when calling Sentry CLI through Gradle. 

So I've set the environment variable
SENTRY_LOG_LEVEL=true

11:08:05  > Task :app:persistSentryProguardUuidsForStagingStaging FAILED
11:08:05  > compressing mappings
11:08:05  > uploading mappings
11:08:05  error: API request failed
11:08:05    caused by: sentry reported an error: Missing uploaded file (http status: 400)
11:08:05  
11:08:05  Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
11:08:05  Please attach the full debug log to all bug reports.
11:08:05  
11:08:05  FAILURE: Build failed with an exception.
11:08:05  
11:08:05  * What went wrong:
11:08:05  Execution failed for task ':app:persistSentryProguardUuidsForStagingStaging'.
11:08:05  > Process 'command '/tmp/.sentry-cli205255703814570533.exe'' finished with non-zero exit value 1
11:08:05  
11:08:05  * Try:
11:08:05  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
11:08:05  
11:08:05  * Get more help at https://help.gradle.org
11:08:05  

But that produced even less logging. BTW this is with the Sentry CLI version set in the Gradle plugin I've removed the customer sentry CLI download and setting the CLI path etc.


So I've set the environment variable
SENTRY_LOG_LEVEL=debug

11:54:15  > Task :app:persistSentryProguardUuidsForReleaseRelease FAILED
11:54:15    INFO    2019-07-13 10:54:13.441455500 +00:00 Loaded config from /root/.sentryclirc
11:54:15    DEBUG   2019-07-13 10:54:13.442394500 +00:00 sentry-cli version: 1.40.0, platform: "linux", architecture: "x86_64"
11:54:15    INFO    2019-07-13 10:54:13.442428700 +00:00 sentry-cli was invoked with the following command line: "/tmp/.sentry-cli4185039579414876252.exe" "upload-proguard" "--android-manifest" "/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml" "--write-properties" "/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties" "/var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt"
11:54:15    DEBUG   2019-07-13 10:54:13.600411300 +00:00 SHA1 for mapping file '/var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt': '5bbc05c3fc47cac5d312268bc989b361730f5e33'
11:54:15  > compressing mappings
11:54:15  > uploading mappings
11:54:15    DEBUG   2019-07-13 10:54:14.635649200 +00:00 request POST https://sentry.io/api/0/projects/(removed)/(removed)/files/dsyms/
11:54:15    DEBUG   2019-07-13 10:54:14.635704400 +00:00 using token authentication
11:54:15    DEBUG   2019-07-13 10:54:14.635720400 +00:00 sending form data
11:54:15    DEBUG   2019-07-13 10:54:14.635757500 +00:00 retry number 0, max retries: 0
11:54:15    DEBUG   2019-07-13 10:54:15.017516300 +00:00 > POST /api/0/projects/(removed)/(removed)/files/dsyms/ HTTP/1.1
11:54:15    DEBUG   2019-07-13 10:54:15.017607500 +00:00 > Host: sentry.io
11:54:15    DEBUG   2019-07-13 10:54:15.017636200 +00:00 > Accept: */*
11:54:15    DEBUG   2019-07-13 10:54:15.017664100 +00:00 > Connection: TE
11:54:15    DEBUG   2019-07-13 10:54:15.017681700 +00:00 > TE: gzip
11:54:15    DEBUG   2019-07-13 10:54:15.017701700 +00:00 > User-Agent: sentry-cli/1.40.0
11:54:15    DEBUG   2019-07-13 10:54:15.018942900 +00:00 > Authorization: Bearer c10fc922***
11:54:15    DEBUG   2019-07-13 10:54:15.019002900 +00:00 > Content-Length: 1170478
11:54:15    DEBUG   2019-07-13 10:54:15.019025200 +00:00 > Content-Type: multipart/form-data; boundary=------------------------a48dafbf144a85e8
11:54:15    DEBUG   2019-07-13 10:54:15.181940800 +00:00 response status: 400
11:54:15    DEBUG   2019-07-13 10:54:15.182222800 +00:00 body: {"detail":"Missing uploaded file"}
11:54:15    DEBUG   2019-07-13 10:54:15.182901600 +00:00 error: running update nagger
11:54:15    DEBUG   2019-07-13 10:54:15.183087900 +00:00 skipping update nagger because session is not attended
11:54:15  error: API request failed
11:54:15    caused by: sentry reported an error: Missing uploaded file (http status: 400)
11:54:15    DEBUG   2019-07-13 10:54:15.184620900 +00:00 client close; no transport to shut down  (from sentry)

**Comment by stephenrjohnson** [comment]
So I've managed to get into a shell where the problem occurs, if I upload using the Gradle job or upload using the cli I still get this problem.

root@500cf547af01:/var/jenkins_home/workspace/mobile/meteor-android# /tmp/sentry-cli upload-proguard --org opensignal --project meteor-android --android-manifest app/build/intermediates/merged_manifests/release/AndroidManifest.xml --write-properties app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties app/build/outputs/mapping/release/mapping.txt
  INFO    2019-07-15 10:34:57.053961300 +00:00 Loaded config from /root/.sentryclirc
  DEBUG   2019-07-15 10:34:57.054033400 +00:00 sentry-cli version: 1.46.0, platform: "linux", architecture: "x86_64"
  INFO    2019-07-15 10:34:57.054068 +00:00 sentry-cli was invoked with the following command line: "/tmp/sentry-cli" "upload-proguard" "--org" "(removed)" "--project" "(removed)" "--android-manifest" "app/build/intermediates/merged_manifests/release/AndroidManifest.xml" "--write-properties" "app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties" "app/build/outputs/mapping/release/mapping.txt"
  DEBUG   2019-07-15 10:34:57.183979500 +00:00 SHA1 for mapping file 'app/build/outputs/mapping/release/mapping.txt': 'cf2475659c78a26ce063008ee10cdd662c44515c'
> compressing mappings
> uploading mappings
  DEBUG   2019-07-15 10:34:58.072822100 +00:00 request POST https://sentry.io/api/0/projects/(removed)/(removed)/files/dsyms/
  DEBUG   2019-07-15 10:34:58.073150100 +00:00 using token authentication
  DEBUG   2019-07-15 10:34:58.073423800 +00:00 sending form data
  DEBUG   2019-07-15 10:34:58.073739500 +00:00 retry number 0, max retries: 0
  DEBUG   2019-07-15 10:34:58.547551300 +00:00 > POST /api/0/projects/opensignal/meteor-android/files/dsyms/ HTTP/1.1
  DEBUG   2019-07-15 10:34:58.548057200 +00:00 > Host: sentry.io
  DEBUG   2019-07-15 10:34:58.548553500 +00:00 > Accept: */*
  DEBUG   2019-07-15 10:34:58.549040300 +00:00 > Connection: TE
  DEBUG   2019-07-15 10:34:58.549561200 +00:00 > TE: gzip
  DEBUG   2019-07-15 10:34:58.550105600 +00:00 > User-Agent: sentry-cli/1.46.0
  DEBUG   2019-07-15 10:34:58.551465100 +00:00 > Authorization: Bearer c10fc922***
  DEBUG   2019-07-15 10:34:58.551852300 +00:00 > Content-Length: 1170476
  DEBUG   2019-07-15 10:34:58.552185100 +00:00 > Content-Type: multipart/form-data; boundary=------------------------412d6f6c69357552
  DEBUG   2019-07-15 10:34:58.695251900 +00:00 < HTTP/1.1 400 BAD REQUEST
  DEBUG   2019-07-15 10:34:58.696644200 +00:00 < Server: nginx
  DEBUG   2019-07-15 10:34:58.698142500 +00:00 < Date: Mon, 15 Jul 2019 10:34:58 GMT
  DEBUG   2019-07-15 10:34:58.699347800 +00:00 < Content-Type: application/json
  DEBUG   2019-07-15 10:34:58.699463600 +00:00 < Content-Length: 34
  DEBUG   2019-07-15 10:34:58.699991100 +00:00 < Connection: keep-alive
  DEBUG   2019-07-15 10:34:58.700086500 +00:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2019-07-15 10:34:58.700833900 +00:00 < Content-Language: en
  DEBUG   2019-07-15 10:34:58.701629800 +00:00 < X-Content-Type-Options: nosniff
  DEBUG   2019-07-15 10:34:58.701775100 +00:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-07-15 10:34:58.702546500 +00:00 < Allow: GET, POST, DELETE, HEAD, OPTIONS
  DEBUG   2019-07-15 10:34:58.703668500 +00:00 < X-Frame-Options: deny
  DEBUG   2019-07-15 10:34:58.704599800 +00:00 < X-Served-By: web-17b74f97
  DEBUG   2019-07-15 10:34:58.705211 +00:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2019-07-15 10:34:58.707664200 +00:00 response status: 400
  DEBUG   2019-07-15 10:34:58.707702 +00:00 body: {"detail":"Missing uploaded file"}
  DEBUG   2019-07-15 10:34:58.708425100 +00:00 error: running update nagger
  INFO    2019-07-15 10:34:58.708531500 +00:00 Skipping update nagger update check
error: API request failed
  caused by: sentry reported an error: Missing uploaded file (http status: 400)
  DEBUG   2019-07-15 10:34:58.711820500 +00:00 client close; no transport to shut down  (from sentry)

root@500cf547af01:/var/jenkins_home/workspace/mobile/(removed)# ls app/build/intermediates/merged_manifests/release/AndroidManifest.xml -lh
-rw-r--r-- 1 root root 16K Jul 15 10:16 app/build/intermediates/merged_manifests/release/AndroidManifest.xml
root@500cf547af01:/var/jenkins_home/workspace/mobile/(removed)# ls -lh app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties
-rw-r--r-- 1 root root 61 Jul 15 10:34 app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties
root@500cf547af01:/var/jenkins_home/workspace/mobile/(removed)# ls -lh app/build/outputs/mapping/release/mapping.txt
-rw-r--r-- 1 root root 6.3M Jul 15 10:26 app/build/outputs/mapping/release/mapping.txt

**Comment by bruno-garcia** [comment]
@stephenrjohnson We've been trying to repro this (even from within a docker container) but it's uploading without issues.
Could you please zip it all up and send us by email or some dropbox link? Including the sentry-cli binary and configuration etc.

**Comment by stephenrjohnson** [comment]
The problem is that it's something about the docker / Jenkins build container, if I had it to start a tmux session and jump into that session then I can get sentry to fail at uploading either through using the Gradle task or sentry cli. 
If I start another docker container with that workspace mapped in then I can upload it using the Gradle task or sentry-cli. Unfortunately, I can't just zip up our source code and send it to you, if you could generate a sentry-cli with even more debugging I can pull that in and run it. Other than that, when I have time I could wire up a proxy and dump the traffic to Sentry.io

**Comment by mitsuhiko** [comment]
Shot in the dark but what file system is the proguard file on?

**Comment by stephenrjohnson** [comment]
ext4

**Comment by stephenrjohnson** [comment]
Well just updated another project to use Sentry.io and 

[2019-07-15T15:29:39.543Z] > Task :(yet another project):packageRelease
[2019-07-15T15:29:41.809Z] 
[2019-07-15T15:29:41.809Z] > Task :(yet another project):persistSentryProguardUuidsForReleaseRelease
[2019-07-15T15:29:41.809Z] > compressing mappings
[2019-07-15T15:29:41.809Z] > uploading mappings
[2019-07-15T15:29:42.381Z] error: API request failed
[2019-07-15T15:29:42.381Z]   caused by: sentry reported an error: Missing uploaded file (http status: 400)
[2019-07-15T15:29:42.381Z] 
[2019-07-15T15:29:42.381Z] Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
[2019-07-15T15:29:42.381Z] Please attach the full debug log to all bug reports.
[2019-07-15T15:29:42.381Z] 
[2019-07-15T15:29:42.381Z] > Task :(yet another project):persistSentryProguardUuidsForReleaseRelease FAILED
[2019-07-15T15:29:42.381Z] 
[2019-07-15T15:29:42.381Z] FAILURE: Build failed with an exception.

**Comment by ninniuz** [comment]
Same Jenkins docker container?
Same Sentry organisation?

> The problem is that this bug only happens on this one repo in our organisation and only for a very specific set of circumstances.

Are the other repos working on the same Jenkins docker container? Are they on different containers?

**Comment by stephenrjohnson** [comment]
Same Jenkins instance, same docker container, same Sentry organisation.  The thing is that it also breaks if I set the Jenkins environment up locally as well, using the same build container and same Sentry organisation but if I start that container (using the same command as Jenkins) go into it and run the commands it does work. 
So it's something weird between Jenkins, Docker and Sentry.io as our old internal hosted Sentry server did use to work.

**Comment by stephenrjohnson** [comment]
Seems like two requests 

https://sentry.io/api/0/projects/(removed)/(removed)/files/dsyms/ | COMPLETE | 400 | https | POST | application/json | /192.168.0.200 | 53757 | sentry.io/35.188.42.15 | 443 |  

and

https://sentry.io | EXCEPTION | 503 | https |   | text/html;charset=ISO-8859-1 | /192.168.0.200 | 53757 |   | 443 | com.xk72.proxy.http.HttpFieldsException: Invalid first line in request

**Comment by mitsuhiko** [comment]
Can you mail it to armin@sentry.io?

**Comment by stephenrjohnson** [comment]
Email sent

**Comment by mitsuhiko** [comment]
Thanks for the dump. There is a bug in the CLI tool where if the auth token contains newlines the HTTP request corrupts. I have added a workaround for this behavior now but until the release is through you can fix this issue by not embedding a newline into your release identifier. Most likely the problem comes because of some shell expansion somewhere in your toolchain.

**Comment by stephenrjohnson** [comment]
🤦‍♂ OK found the problem and fixing it now at my end.

**Comment by bruno-garcia** [comment]
I've just released the new Gradle plugin, version 1.7.25 which uses `sentry-cli` 1.45.0 that addresses the issue.
