### ISSUE TITLE
Use common SLF4J APIs instead of LOG4J directly to allow support of different LOG4J versions

### ISSUE THREAD

**Issue by hecvd** [getsentry/sentry-java#742]
Sentry should support the SLF4J API as a library is an interface that uses the Log4j (among others) implementation detected at runtime. Sentry should use Slf4j APIs to avoid tightly coupled logging libraries.

**Comment by bruno-garcia** [comment]
@hecvd not sure I follow. The SDK already uses `slf4j`:

https://github.com/getsentry/sentry-java/blob/6dcc2f4c30464cf26a45b38bf335b004c75999ae/sentry/pom.xml#L23-L24

Perhaps I'm missing something. Could you please clarify?

**Comment by hecvd** [comment]
Thanks Bruno. I got confused with the binding implementations and this other ticket: https://issues.apache.org/jira/browse/SENTRY-2088
