### ISSUE TITLE
prevent use of Settings.Secure.ANDROID_ID for identifying a user

### ISSUE THREAD

**Issue by rwarners** [getsentry/sentry-java#746]
In AndroidEventBuilderHelper `Settings.Secure.getString(ctx.getContentResolver(), Settings.Secure.ANDROID_ID)` is used and send as part of an event to Sentry. If the purpose is to identify if reports came from the same user, than a random (but persisted) value or at least hashed version would suffice. We consider the ANDROID_ID as something that can (eventually) personally identify a real user. We don't want that, but we cannot easily work around this as well.

**Comment by ninniuz** [comment]
> We don't want that, but we cannot easily work around this as well.
You do not want your users to be identified with the `Settings.Secure.ANDROID_ID`?

If you are looking for a way to customise this behavior, you can supply your own instance of `io.sentry.event.interfaces.UserInterface` to the SentryClient event builder.

Example:
```
Sentry.getStoredClient().addBuilderHelper { eventBuilder ->
    val user = getCurrentUser()
    val userInterface = UserInterface(user.id, user.username, null, user.email) 
    eventBuilder.withSentryInterface(userInterface)
}
```

**Comment by rwarners** [comment]
> You do not want your users to be identified with the Settings.Secure.ANDROID_ID?
Correct

Your suggestion makes sense, we will try this approach. Thank you.

**Comment by malenalbc** [comment]
Hello, is there a similar workaround on newest versions, like 3.0.0-alpha.1? I'm seeing `DefaultAndroidEventProcessor` is being instantiated on `SentryAndroid.init` and `eventProcessors` is not editable.

```
 String androidId = getAndroidId();
    if (androidId != null) {
      map.put(ANDROID_ID, androidId);
    }
```

How can we prevent the use of this if we don't want users be identified with `Settings.Secure.ANDROID_ID`?

**Comment by marandaneto** [comment]
@malenalbc use the `beforeSend` callback and filter this out

**Comment by malenalbc** [comment]
Hey, thanks for the quick answer. I already clean some of the values in the `beforeSend`:
```
     options.setBeforeSend { event, _ ->
                    event.contexts = event.contexts.apply {
                        val safeApp = this.app
                        safeApp.deviceAppHash = null
                        this.app = safeApp
                        val safeDevice = this.device
                        safeDevice.id = null
                        this.device = safeDevice
                    }
                    event.user = null
                    event
                }
```

Do these already take care of the Id, or is it another value that I'm missing?

**Comment by marandaneto** [comment]
@malenalbc that's all you need
