### ISSUE TITLE
 setUser does not work

### ISSUE THREAD

**Issue by freeholod** [getsentry/sentry-java#758]
Hi. I faced with two problems when integrating Sentry into a project.

1. I am trying to set the user before submitting a **Sentry.capture(event)** request. 

```
User user = authUtils.getMe();
UserBuilder userBuilder = new UserBuilder();
if (authUtils.getDomain() != null)userBuilder.setId(authUtils.getDomain() + "-" + user.getId());
userBuilder.setUsername(user.getNickName());
Sentry.getContext().setUser(userBuilder.build());
Sentry.capture(event);
```
The error immediately arrives in Sentry, but there is nothing besides the user ip. I tried before sending to check the object, which lies in the context **Sentry.getContext().getUser()** and everything is good there.

2. To the withExtra method, I send a query value that averages 2000 characters, including spaces. The field contains a bad graphQL query that caused an error. But in the web version, the query field is truncated to 400 characters. 
![Снимок экрана 2019-08-26 в 16 06 56](https://user-images.githubusercontent.com/12254463/63693226-2e200280-c81c-11e9-93a3-367754a11ef8.png)

And the sentry-java inscription below bothers me.

**Comment by freeholod** [comment]
I fixed the second point by overriding MAX_LENGTH_STRING, but what about the first?

**Comment by ninniuz** [comment]
@freeholod can you please try `Sentry.capture(EventBuilder eventBuilder)` instead of `Sentry.capture(Event event)`?

**Comment by freeholod** [comment]
@ninniuz It works! Thank. It is resolved.
