### ISSUE TITLE
Filtering Exception

### ISSUE THREAD

**Issue by Patrick0308** [getsentry/sentry-java#761]
I want to ignore some exception. May be we can formulate some filtering rules in properties file?

**Comment by bruno-garcia** [comment]
Isn't this something worth doing via code?
How would you like to define it via configuration?

**Comment by alexandrul** [comment]
Could be related to #575

**Comment by maciejwalkowiak** [comment]
In Java SDK v3 you can filter out evens by implementing custom `BeforeSendCallback`. This callback can be set on `SentryOptions` in following way if using manual Sentry configuration.

```java
Sentry.init(options -> {
      options.setBeforeSend(new SentryOptions.BeforeSendCallback() {
        @Override
        public @Nullable
        SentryEvent execute(@NotNull SentryEvent event, @Nullable Object hint) {
          if (containsException(event, MyException.class)) {
            return null;
          } else {
            return event;
          }
        }

        private <T> boolean containsException(@NotNull SentryEvent event, Class<T> clazz) {
        // add your implementation here
      });
    });
```

Make sure to check documentation to look how to configure this callback when using Spring Boot integration: https://docs.sentry.io/platforms/java/guides/spring-boot/

Closing for now, if it does not solve your issue please comment.

**Comment by IEnoobong** [comment]
Can't find the `SentryOptions.BeforeSendCallback` class using sentry 1.7.30

**Comment by marandaneto** [comment]
@IEnoobong only available thru Sentry SDK >= v2, please upgrade your SDK

**Comment by IEnoobong** [comment]
ok thanks! done
