### ISSUE TITLE
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message

### ISSUE THREAD

**Issue by pmrochaubi** [getsentry/sentry-java#765]
I'm running sentry-spring with sentry-logback on a service, deployed on kubernetes with docker and after upgrading my JRE to version 11 i get this exception in log's when trying to connect with the sentry server. The service runs on top of istio mesh and other services running on jdk 8 are able to connect with the sentry server without any issue.

Sentry tool version 1.7.27
Spring Boot version 2.1.6 RELEASE
Jre 11.0.2

Any ideia how can i solve this is issue

> [api-cfc946b75-r4k2w] 2019-09-18 23:01:16.903 i.s.c.A.lockdown - Initiated a temporary lockdown because of exception: An exception occurred while submitting the event to the Sentry server. 
> [api-cfc946b75-r4k2w] 2019-09-18 23:01:16.904 i.s.c.AsyncConnection - An exception occurred while sending the event to Sentry. 
> [api-cfc946b75-r4k2w] io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server. 
> [api-cfc946b75-r4k2w] 	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:205) 
> [api-cfc946b75-r4k2w] 	at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:75) 
> [api-cfc946b75-r4k2w] 	at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:185) 
> [api-cfc946b75-r4k2w] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
> [api-cfc946b75-r4k2w] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
> [api-cfc946b75-r4k2w] 	at java.base/java.lang.Thread.run(Thread.java:834) 
> [api-cfc946b75-r4k2w] Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message 
> [api-cfc946b75-r4k2w] 	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:439) 
> [api-cfc946b75-r4k2w] 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:184) 
> [api-cfc946b75-r4k2w] 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108) 
> [api-cfc946b75-r4k2w] 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152) 
> [api-cfc946b75-r4k2w] 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063) 
> [api-cfc946b75-r4k2w] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) 
> [api-cfc946b75-r4k2w] 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) 
> [api-cfc946b75-r4k2w] 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) 
> [api-cfc946b75-r4k2w] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168) 
> [api-cfc946b75-r4k2w] 	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:157) 
> [api-cfc946b75-r4k2w] 	... 5 common frames omitted 

`

**Comment by Patrick0308** [comment]
Maybe something wrong in sentry server.

**Comment by pmrochaubi** [comment]
@Patrick0308 nope, all good

**Comment by bruno-garcia** [comment]
Just by looking at the stack trace and message it's hard to tell exactly what's going on. There's an [issue on GitHub discussing the same exception message, on JDK 11](https://github.com/NationalSecurityAgency/ghidra/issues/101). The culprit there was unrelated to the application but an infrastructure one. All the SDK is doing is using `javax.net.ssl.SSLSession` which has been around since Java 1.4

Could you please try to connect the app straight to Sentry to make sure it's not related to Istio or anything else in your infrastructure?

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback. Please comment if the issue is still happening.
