### ISSUE TITLE
Display breadcrumbs with milliseconds

### ISSUE THREAD

**Issue by mrmitew** [getsentry/sentry-java#776]
Hello,

I am using the Android SDK.

Currently the format is HH:mm:ss, but I would be useful for me to also see at which millisecond a given breadcrumb was recorded. 

Would this be supported by the Sentry SDK and web dashboard, or I should add my own timestamp in the breadcrumbs message instead?

Thank you!

**Comment by bruno-garcia** [comment]
Thanks for raising! To be honest I'd expect it to have already milliseconds.
We should get this in.

**Comment by mrmitew** [comment]
Hello @bruno-garcia , thank you for your literally immediate reaction! I appreciate it!

Here's what's available to me as information in the web dashboard. Adding also the millis would be very insightful.

<img width="434" alt="Screen Shot 2019-10-07 at 5 04 08 PM" src="https://user-images.githubusercontent.com/8547755/66323737-8884a680-e924-11e9-9073-b825a925aa24.png">

**Comment by bruno-garcia** [comment]
I've just checked and it seems even when the SDKs send milliseconds, Sentry is only showing as in your screenshot, up to seconds precision. The crumbs are ordered by the milliseconds though.

In this SDK we serialize the timestamp here:

https://github.com/getsentry/sentry-java/blob/10da2f6ee67a957e0be97cf17703e4614eb7c71d/sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java#L299

We need to change this to add the precision

**Comment by bruno-garcia** [comment]
We still need to open an issue on getsentry/sentry.

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry/issues/14959

**Comment by dashed** [comment]
@mrmitew just a heads up, someone has kindly pushed a pull request to be able to display milliseconds, https://github.com/getsentry/sentry/pull/15195. It should be available on sentry.io soon.

**Comment by mrmitew** [comment]
That's awesome news! Thank you @pastDexter for the PR and @dashed for the heads up! Really appreciate it!
