### ISSUE TITLE
Setting the code's release version

### ISSUE THREAD

**Issue by dimipaun** [getsentry/sentry-java#781]
We seem to be able to set the code's version number in other languages, say Javascript:

```
Sentry.init({
  release: "my-project-name@2.3.12"
})
```

But there doesn't seem to be a way to do so through the Java SDK.

**Comment by bruno-garcia** [comment]
We should definitely have `release`.
Ideally on `SentryOptions` and applied to all outgoing events, when not already set (not to override something set to an explicit event).

**Comment by metlos** [comment]
This can be set using the `SentryClient#setRelease()`, I believe. That is not the same as in other languages though as you correctly note.

**Comment by metlos** [comment]
Hmm... I'm still learning this stuff :) release is also settable through an option on the DSN. But still not possible using a config prop :)

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1

possible thru `SentryOptions.setRelease(...)`
