### ISSUE TITLE
Check if Sentry is already initializated

### ISSUE THREAD

**Issue by profesorfalken** [getsentry/sentry-java#783]
Hello, 

I do not see how I can check if Sentry has been already initializated. 
At first I thought that it was enought to do something like: 

    if (Sentry.getStoredClient() == null) {

However, as I have seen in the code,  this is a singleton builder method, so the call will never return null as it is going to create a new instance if it does not exist.

Is there any other way to check if the initialization is done?

Thank you

**Comment by metlos** [comment]
Unfortunately, there is no way in the `Sentry` class to check that the client it provides has not yet been initialized.

You can always not use `Sentry.init(*)` methods and build and locate the client yourself, e.g. by using one of the static methods in `SentryClientFactory` or just by copying the logic in `Sentry.init()` and storing that somewhere in your own code. But that is kinda ugly and error prone.

At the same time, adding that check should not be difficult. Would you mind providing a PR for that?

**Comment by profesorfalken** [comment]
Hello, 

In fact we do not usually use Sentry.init but the factory to  create our client and handle our messages, but there are sometimes where we have not the control on the initialization, so we have to check it.

I have done a PR. No problem if you do not feel necessary to integrate it in the API.


Thank you for your time

**Comment by marandaneto** [comment]
v1.7.29 is out with this change, thank you all.
