### ISSUE TITLE
Maybe, it's time to change JDK minimal version to 1.8 ?

### ISSUE THREAD

**Issue by altro3** [getsentry/sentry-java#787]
Because first JDK 1.8 release was published 5.5 years ago and now I don't know any libraries, which work incorrect with JDK 1.8, maybe you can migrate your adapter to JDK 1.8?

If you do this, you could use Java 8 features, like java.time and could migrate to Spring Boot 2.2.0

**Comment by bruno-garcia** [comment]
@altro3 It's on the list. @metlos did a lot of work so we could make the change since there were dependencies that locked us down to 1.7, including hanging builds when running on JVM 1.8 on macOS.

**Comment by SrMouraSilva** [comment]
Hello, taking advantage of this thread about updating the JDK, I would like to know if there is any version of Sentry compatible with JDK 1.6.

Despite an old version, there are a good number of legacy systems that would benefit from this tool.

So I ask you to review a version update and, if you want to update, please document the driver versions compatible with their respective java versions.

**Comment by bruno-garcia** [comment]
Java 6 was dropped 6 years ago already:

<img width="951" alt="image" src="https://user-images.githubusercontent.com/1633368/74614488-4d6e5d00-50e6-11ea-8593-e34840569af8.png">

A client from back then would still be compatible with Sentry 10 but we are not planning to support Java 1.6 though.

**Comment by SrMouraSilva** [comment]
Okay, I appreciate the answer.

I will try to generate a jar from the prior code (https://github.com/getsentry/sentry-java/commit/fca7521357888074278da3958e6a776f921d58d3).

If you have any success, I will inform you.

**Comment by bruno-garcia** [comment]
Thanks. It might be interesting to you to keep a fork then. If anyone asks for Java 1.6 we'll make sure to point that way. This way collectively there could be some maintenance by the users of that version.

**Comment by marandaneto** [comment]
Sentry Java SDK v3 is min. Java 1.8
