### ISSUE TITLE
sentry-logback + tags aren't logged in other threads.

### ISSUE THREAD

**Issue by jeacott1** [getsentry/sentry-java#792]
hi all, 
  I'm trying to add tags to every sentry event via the sentry-logback (1.7.28) integration.
the MDC.put(..) understandably only works on the thread its invoked on,
but Sentry.getContext().addTag(name, value); seems to suffer from the same problem.
do I really have to wrap all my executors to get this working? what about 3rd party libs like quartz etc that also use threads?
Did I miss something? how do I tag all log events in my application?

thanks in advance.

**Comment by jeacott1** [comment]
couldn't find a good solution, so I've implemented 2 options that work for me.
PR here: https://github.com/getsentry/sentry-java/pull/794

**Comment by marandaneto** [comment]
v1.7.29 is out with this change, thank you all.
