### ISSUE TITLE
Allow to disable the SentryExceptionResolver 

### ISSUE THREAD

**Issue by u6f6o** [getsentry/sentry-java#795]
When we used the spring-boot-starter library for our services (~50 services), our sentry account was flooded with error reports because spring internally throws a lot of exceptions and the SentryExceptionResolver happily forwarded them all to sentry. We decided to write our own starter that is basically a copy of this one but without enabling the SentryExceptionResolver. 

I'd suggest to add an option to the configuration to enable or disable this resolver. Currently, the resolver is registered as a bean per default.

**Comment by kekcogen** [comment]
@u6f6o you can alway override SentryExceptionResolver with you bean and add custom logic.

**Comment by marandaneto** [comment]
@maciejwalkowiak is this an issue on v3?

**Comment by maciejwalkowiak** [comment]
Yes, v3 follows the same logic. We can add a flag to disable `SentryExceptionResolver` but I guess it's something for 3.1

**Comment by marandaneto** [comment]
sure, just to keep it open, thanks

**Comment by maciejwalkowiak** [comment]
We have added option to set exception resolver order: https://docs.sentry.io/platforms/java/guides/spring-boot/

For example `sentry.exception-resolver-order=2147483647` will prevent Sentry from reporting exceptions handled in any other Spring exception handler.

**Comment by seeersucker** [comment]
> We have added option to set exception resolver order: https://docs.sentry.io/platforms/java/guides/spring-boot/
> 
> For example `sentry.exception-resolver-order=2147483647` will prevent Sentry from reporting exceptions handled in any other Spring exception handler.

Good day Maciej Walkowiak, I set the **sentry.exception-resolver-order** as **2147483647** (without -) in the **application.yml** file, but, handled exceptions in the **GlobalExceptionHandler** are still captured and sent to Sentry, is there anything I can do about it? Thanks beforehand

**Comment by adinauer** [comment]
Hello @seeersucker I just tested this using our Spring Boot 3 sample and the following code:

```
@Component
public class MyOtherExceptionHandler implements HandlerExceptionResolver, Ordered {

  @Override
  public ModelAndView resolveException(HttpServletRequest request, HttpServletResponse response, Object handler, Exception ex) {
    return new ModelAndView("oopsview");
  }

  @Override
  public int getOrder() {
    return Ordered.HIGHEST_PRECEDENCE;
  }
}
```

Using the debugger I verified, it only runs the above code (`MyOtherExceptionHandler`) but not our `SentryExceptionResolver`.

What version of the SDK are you on?

Are you using a Sentry logging SDK that picks up the exception and sends it to Sentry?

How exactly are you setting the option in `application.yml`?

Can you please enable the `debug` option (`sentry.debug=true`) and check the JSON that is logged. It might give you more details on what captured the exception.
