### ISSUE TITLE
Configure automatic breadcrumbs for java application

### ISSUE THREAD

**Issue by JMARCH31** [getsentry/sentry-java#800]
Hello,
Is there any feature in order to set automatic breadcrumbs for java application?

I would like to set each log.info / warn into breadcrumbs.

I'm using log4j2 and already set up and having logs into sentry.

Thanks

**Comment by maciejwalkowiak** [comment]
Thanks for reporting! Starting from Java SDK 3.0 log4j2 and logback record bredcrumbs. Read more in the guide https://docs.sentry.io/platforms/java/guides/log4j2/#minimum-log-level
