### ISSUE TITLE
Incorrect docs timeoutIntervalMillis should be timeoutIntervalMs

### ISSUE THREAD

**Issue by gpeal** [getsentry/sentry-java#802]
The docs [here](https://docs.sentry.io/clients/java/integrations/#android) don't match the code [here](https://github.com/getsentry/sentry-java/blob/master/sentry-android/src/main/java/io/sentry/android/AndroidSentryClientFactory.java#L133)

**Comment by marandaneto** [comment]
@gpeal thanks for your message.
Good catch, we are gonna address it.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-docs/pull/1426
