### ISSUE TITLE
Issue release build Android

### ISSUE THREAD

**Issue by simoneventurini** [getsentry/sentry-java#803]
When i build my android app with proguard in release mode i have this error:
```
Execution failed for task ':app:persistSentryProguardUuidsForReleaseRelease'.
> Process 'command '/var/folders/97/21t3g9zx001fxvfrn0mlj_d80000gn/T/.sentry-cli2204076802679537370.exe'' finished with non-zero exit value 1
```
i'm using 
```
classpath 'io.sentry:sentry-android-gradle-plugin:1.7.27'
implementation 'io.sentry:sentry-android:1.7.27'
implementation 'org.slf4j:slf4j-nop:1.7.27'
```

If i change the version from 1.2.27 to 1.2.19 it works fine. But i would like use the latest version.

Thanks,
Simone

**Comment by marandaneto** [comment]
@simoneventurini thanks for your message.

the latest version is `1.7.29`, could you try with this one? if not, please answer the questions below.

Where is your `sentry.properties` placed?
Which version of `AS`, `AGP`, and `Gradle` do you have?

Thanks

**Comment by simoneventurini** [comment]
i've just tried to use the latest version 1.7.29 and now it works!

Thank you so much
Simone

**Comment by bruno-garcia** [comment]
Glad it's working. Feel free to reopen if needed

**Comment by wppiotrek** [comment]
I still have got this problem (on Windows 10) even though I use 'io.sentry:sentry-android-gradle-plugin:1.7.29'. Whenever I'm running tests there are created 12 (.sentry-cli[xxxx].exe) files each of 7,62 MB size at 'C:\Users\xxx\AppData\Local\Temp'

AndroidStudio 3.5.3
Gradle: 5.6.4

**Comment by bruno-garcia** [comment]
The original issue stated that `If i change the version from 1.2.27 to 1.2.19 it works fine. But i would like use the latest version.` so it seems you have a different issue.

Could you please raise a new issue, ideally with a small reproducible project so we can investigate?
