### ISSUE TITLE
Spring app deploy holding on to old Sentry

### ISSUE THREAD

**Issue by ryno1234** [getsentry/sentry-java#805]
We have a Wildfly 12 instance running a Spring application. We have a  class that implements `ServletContextListener` and within the `contextInitialized()` function, we initialize Sentry with our current POM Version for error version tracking.

    // ///////////////////////////////////
    // ServletContextListener
    // ///////////////////////////////////
    @SuppressWarnings("unchecked")
    @Override
    public void contextInitialized(ServletContextEvent event) {
    	
        MavenBuildInfo buildInfo = (MavenBuildInfo) SpringApplicationContext.getBean("mavenBuildInfo");
    	
        //Initializes Sentry for logging
        Sentry.init(SENTRY_DSN);
        String release = buildInfo.get("build.version");
        if(release.toUpperCase().contains("SNAPSHOT")) {
    		Sentry.getStoredClient().setEnvironment("dev");
        }else {
    		Sentry.getStoredClient().setEnvironment("prod");
        }
        Sentry.getStoredClient().setRelease(release);
        Sentry.getStoredClient().addTag("build", buildInfo.get("build.number"));
        
        SentryAppender sa = new SentryAppender();
        sa.setThreshold(Level.ERROR);
        sa.activateOptions();
        org.apache.log4j.Logger.getRootLogger().addAppender(sa);
    }

Last night we went to deploy a new version of the application. We fired up the JBoss CLI and issued our `deploy` command to deploy the new .war. Everything worked fine, our new version was deployed and the website was functioning as expected. 

I looked at Sentry's web interface just now and realized I had 54k events that have been sent to Sentry since our last deploy last night. Interestingly enough, the error comes from within Sentry itself.

```
java.lang.NoClassDefFoundError: io/sentry/marshaller/json/JsonMarshaller$2
at io.sentry.marshaller.json.JsonMarshaller.formatLevel(JsonMarshaller.java:363)
at io.sentry.marshaller.json.JsonMarshaller.writeContent(JsonMarshaller.java:205)
at io.sentry.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:161)
at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:170)
at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:76)
at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:185)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

Even more interesting is that the Release version specified in the tags of the error is the _prior release version_. Even as of just a few minutes ago, we are still receiving errors from Sentry *about* Sentry reporting a release that doesn't exist any longer and has since been overwritten during our deploy last night.

Why would Sentry have a lifespan past a deploy? I'm relatively new to Java (I'm a .Net dev) and have inherited this project. I'm not intimately familiar with Spring /Wildfly or their lifecycles. Does the Spring app not get entirely torn down during a new deploy? Why would Sentry be holding on to this old release version?

**Comment by bruno-garcia** [comment]
My guess is that those were cached events and the serialized version changed in between releases. Although it seems it couldn't load `JsonMarshaller` which is defined in the `sentry` package.
In any case, Sentry caps the number of cached events to 10, which * 12 servers couldn't be more than a bit over a hundred. 

It's strange that it bubbled from `AsyncConnection` since:

https://github.com/getsentry/sentry-java/blob/28a9b1c1fa02bf5c30c8efbfd263a156ff417677/sentry/src/main/java/io/sentry/connection/AsyncConnection.java#L191

Also, Sentry drops failed events. Is it possible you deploy overridden some files but kept some of the old release?
Maybe @metlos some input.

**Comment by ryno1234** [comment]
Hi @bruno-garcia, my server is *still* sending these events to Sentry at a rapid pass as I type this but we've reached our quota (now twice in the past 24 hours even after expanding our quota to 500K events) as of yesterday at 4pm Pacific.

**This is happening multiple times a second since our release:**
```
2020-01-06 23:42:18,862 ERROR [stderr] (sentry-pool-1-thread-2926484) Exception in thread "sentry-pool-1-thread-2926484" java.lang.NoClassDefFoundError: io/sentry/marshaller/json/JsonMarshaller$2
2020-01-06 23:42:18,862 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at io.sentry.marshaller.json.JsonMarshaller.formatLevel(JsonMarshaller.java:363)
2020-01-06 23:42:18,862 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at io.sentry.marshaller.json.JsonMarshaller.writeContent(JsonMarshaller.java:205)
2020-01-06 23:42:18,863 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at io.sentry.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:161)
2020-01-06 23:42:18,863 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:170)
2020-01-06 23:42:18,864 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:76)
2020-01-06 23:42:18,864 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:185)
2020-01-06 23:42:18,864 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-01-06 23:42:18,864 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-01-06 23:42:18,865 ERROR [stderr] (sentry-pool-1-thread-2926484) 	at java.lang.Thread.run(Thread.java:748)
```

We are running version 1.7.27-f6366.

The reason why I mention the frequency of messages is because this goes way beyond the cached events concept you mentioned. This is something else.

I'm not sure how a deploy would overwrite some files but not other. Again, I'm not intimately familiar with Wildfly or how the deploy works from the intricate details. I know we deploy using the JBoss CLI so it's like a hot deploy. I suppose if some files were in use or something similar that there could have been some items hanging around. Any insight you have into this would be appreciated.

We will be completely shutting down the JBoss instance later today (we have to coordinate the outage with our users), but when we do, we are hoping that will clear up this issue. Still, I'd like to understand *why* this happens.

**Comment by bruno-garcia** [comment]
I suggest you remove the sentry DSN (leave an empty string) and restart the service to disable the sdk while we figure this out.

**Comment by bruno-garcia** [comment]
Is it possible to make a copy of one of the deployment files so we can investigate? Worst case a memory dump. Based on the error the app can't find that class but that's part of the sdk so it could be it failed to copy to the release package somehow. Only from this stack trace it's hard to guess what's going on though

**Comment by ryno1234** [comment]
@bruno-garcia, a simple restart of Wildfly service fixed the problem. Something happened during the deploy that must of kept some Sentry information around holding on to old context, files, threads, who knows. Again, I'm not sure what all happens in a Wildfly deploy to tear down the application, but something seems to have persisted across deploys.

**Comment by bruno-garcia** [comment]
I’m glad it works now at least. It would be good to find out what happened there. Is it possible the service started before all files were deployed? That would explain this issue. In any way it should go into lockdown and not send so many events

**Comment by metlos** [comment]
> My guess is that those were cached events and the serialized version changed in between releases. Although it seems it couldn't load `JsonMarshaller` which is defined in the `sentry` package.
> In any case, Sentry caps the number of cached events to 10, which * 12 servers couldn't be more than a bit over a hundred.
> 
> It's strange that it bubbled from `AsyncConnection` since:
> 
> https://github.com/getsentry/sentry-java/blob/28a9b1c1fa02bf5c30c8efbfd263a156ff417677/sentry/src/main/java/io/sentry/connection/AsyncConnection.java#L191
> 
> Also, Sentry drops failed events. Is it possible you deploy overridden some files but kept some of the old release?
> Maybe @metlos some input.

`NoClassDefFoundError` is an `Error` and not a `RuntimeException` so we actually don't catch that. I would hazard to say that we should actually not catch it, because for example this particular error suggests a problem with the deployed jars while other errors include OOM, virtual machine and other rather unrecoverable errors.

As for the reasons why this happened, I only have to wildly (sic) guess that the sentry pool thread got stuck in some kind of infinite loop and wasn't reacting to interruption and/or was swallowing the interrupt flag preventing the thread pool from cancelling the jobs.

When deploying a new version of an application to an application server like Wildfly, the application server tries to stop the application and unload its classes, but cannot even see "rogue" threads like the one we seem to have been witnessing here.

What fascinates me is  that the runtime seems to have picked up new version code after the re-deploy (i.e. sentry was working ok, then re-deploy presumably also included a new version of sentry and suddenly we started seeing errors). Shame you weren't able to get a heap and thread dump before restarting the server. I would be interested in seeing the classloaders and stacktraces in the application server.

**Comment by maciejwalkowiak** [comment]
Seems like it was an edge, one time issue. Closing for now, please comment if error happens again.
