### ISSUE TITLE
New version 1.7.29 doesn't work on API lower than 19

### ISSUE THREAD

**Issue by BulatMukhutdin** [getsentry/sentry-java#809]
On low level APIs it crashes on line 
```
 io.sentry.Sentry.init(AndroidSentryClientFactory(this))
```
With java.lang.NoClassDefFoundError: java.util.Objects

**Comment by marandaneto** [comment]
@BulatMukhutdin hey, thanks for raising this issue.

True, the usage of https://developer.android.com/reference/java/util/Objects.html#requireNonNull(T,%20java.lang.String) is only possible when Android API >= 19

@bruno-garcia what's the min. supported API version for this SDK?

**Comment by bruno-garcia** [comment]
Since we don't have a test matrix here as we do for [sentry-android](https://github.com/getsentry/sentry-android), it's hard to tell. If this is the only blocker to support API 19, we could get rid of `Objects` and make a new release.

**Comment by marandaneto** [comment]
not sure if only this is enough, but it's worth a try.

ps: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9
this lib. uses `Jackson` 2.10 and since 2.8 it's only officially supported on API >= 19, but it `might` work on older versions.

**Comment by marandaneto** [comment]
@BulatMukhutdin hey, we have fixed it and it's gonna be available on the next release, stay tuned.

**Comment by marandaneto** [comment]
@BulatMukhutdin It's finally out: https://github.com/getsentry/sentry-java/releases/tag/v1.7.30
Let us know if you have any issues. Cheers!
