### ISSUE TITLE
Android kotlin is support?

### ISSUE THREAD

**Issue by ewgcat** [getsentry/sentry-java#812]

**Comment by marandaneto** [comment]
Hey @ewgcat what do you mean by _Android kotlin is support?_

Kotlin has fully Java Interoperability.
https://kotlinlang.org/docs/reference/java-interop.html

So the answer would be yes, and this SDK also supports Android
https://docs.sentry.io/clients/java/integrations/#android

Please reopen the issue if this is not what you were looking for.
