### ISSUE TITLE
map returned by Context.getTags/getExtras is not thread safe

### ISSUE THREAD

**Issue by mos8502** [getsentry/sentry-java#813]
The issue with `Context.getTags()` and `Context.getExtras()` is similar. 

All functions inside `Context` accessing tags is synchronized on the context object. 

However `Context.getTags()` returns an unmodifiable map by wrapping tags

```
public synchronized Map<String, String> getTags() {
    if (tags == null || tags.isEmpty()) {
        return Collections.emptyMap();
    }

    return Collections.unmodifiableMap(new HashMap<>(tags));
}
```

where `Collections.unmodifiableMap` only wraps the existing map and 

> Query operations on the returned map "read through" to the specified map

```
class Collections {
    ...
    public static <K, V> Map<K, V> unmodifiableMap(Map<? extends K, ? extends V> m) {
        return new Collections.UnmodifiableMap<>(m);
    }

    /**
     * @serial include
     */
    private static class UnmodifiableMap<K, V> implements Map<K, V>, Serializable {
        private static final long serialVersionUID = -1034234728574286014L;

        private final Map<? extends K, ? extends V> m;

        UnmodifiableMap(Map<? extends K, ? extends V> m) {
            if (m == null)
                throw new NullPointerException();
            this.m = m;
        }
       ...
    }
}
```

As a result - for example - if tags are modified through `Context` while iterating over the map returned by `Context.getTags()` a `ConcurrentModificationException` is going to be raised. Other unexpected behaviour due to race condition.

Simple reproduction of the issue:

```
Context context = new Context();

context.addTag("Today", "Monday");
context.addTag("Tomorrow", "Tuesday");

for (Map.Entry<String, String> entry : context.getTags().entrySet()) {
    context.addTag("DayAfterTomorrow", "Wednesday");
}
```

The issue is similar in case of extras.

**Comment by mos8502** [comment]
Possible solution this issue is to create a copy of tags/extras
```
public synchronized Map<String, String> getTags() {
    if (tags == null || tags.isEmpty()) {
        return Collections.emptyMap();
    }

    return new HashMap<>(tags);
}
```
Optionally it can still be wrapped in an unmodifiable map the keep the current behaviour of the map returned

**Comment by marandaneto** [comment]
@mos8502 thanks for raising this issue.

yep, there are a few ways of solving it, and this one (suggested) might be the easiest and still compatible with the past versions.

However, we could also replace the non-thread-safe list/map types to their respective thread-safe types, which is eg ConcurrentHashMap/CopyOnWriteArrayList, but it means we are gonna introduce a breaking change.

Let me get some opinions in here, what do you think @bruno-garcia @metlos

**Comment by bruno-garcia** [comment]
Thanks for raising this @mos8502 and @marandaneto for replying. Both approaches would do indeed.

It should be OK simply returning a new instance as opposed to adding the concurrent since those are ThreadLocal.

@metlos have opinions?

**Comment by marandaneto** [comment]
@mos8502 btw if you need a fix right away.

There are a few workarounds.

1) you may use `map.entrySet().iterator()` instead.
2) do not modify the map while looping it, create an `aux` map and add to them, so later loop into `aux` and call add/remove to the original map.

**Comment by metlos** [comment]
Given the the fact that all the methods on `Context` are synchronized, I think the intention was to use it concurrently.

Both copying the map and using a thread-safe map impl are valid fixes for the fact that it currently isn't thread-safe.

But the two approaches have different semantics. The copy essentially creates a snapshot at the time of the method invocation and any further modifications to the map through the `Context` methods are not visible (concurrent or not).

If we used `ConcurrentHashMap` the users of the map returned from `getTags()` could see different contents of the map at different times due to changes made to it concurrently.

So I think we need to answer this question first: do we want snapshot or live thread-safe access?

In any case, the fix needs to be accompanied by thorough javadocs. Thread-safety is never easy :)

**Comment by marandaneto** [comment]
@metlos very well said.

Just to keep on mind, the unified API which doesn't apply to this SDK, it doesn't expose getters, but only setters and removers by key.

**Comment by mos8502** [comment]
> @mos8502 btw if you need a fix right away.
> 
> There are a few workarounds (if not being called from multiple threads).
> 
> 1. you may use `map.entrySet().iterator()` instead.
> 2. do not modify the map while looping it, create an `aux` map and add to them, so later loop into `aux` and call add/remove to the original map.

We currently have a crash due to this in our Android App.
The ANR watchdog runs a separate thread "pinging" the Apps main thread. If it doesn't get a "pong" after a target time it will log an event which will eventually invoke `ContextBuilderHelper.helpBuildingEvent`which in term will execute the following piece of code

```
Map<String, String> tags = context.getTags();
if (!tags.isEmpty()) {
    for (Map.Entry<String, String> entry : tags.entrySet()) {
        eventBuilder.withTag(entry.getKey(), entry.getValue());
    }
}
```
So to apply the suggestions `ContextBuilderHelper` would need to be changed, but would not prevent the issue for other possible usages of tags. As a temporary fix I could replace  `ContextBuilderHelper` in our codebase but I don't consider that just as a temporary fix.

**Comment by mos8502** [comment]
> Given the the fact that all the methods on `Context` are synchronized, I think the intention was to use it concurrently.
> 
> Both copying the map and using a thread-safe map impl are valid fixes for the fact that it currently isn't thread-safe.
> 
> But the two approaches have different semantics. The copy essentially creates a snapshot at the time of the method invocation and any further modifications to the map through the `Context` methods are not visible (concurrent or not).
> 
> If we used `ConcurrentHashMap` the users of the map returned from `getTags()` could see different contents of the map at different times due to changes made to it concurrently.
> 
> So I think we need to answer this question first: do we want snapshot or live thread-safe access?
> 
> In any case, the fix needs to be accompanied by thorough javadocs. Thread-safety is never easy :)

Currently the only usage of `getTags`/`getExtras` is sentry-java that I can see is in `ContextBuilderHelper.helpBuildingEvent` where it is used to add tags/extras to the `EventBuilder`. 

So I'm just guessing about the intention, but it seems for this use case the helper is capturing a snapshot of tags/extras for the event. If my assumption is correct then it would be desirable to return a copy of the current values of tags/extras. 

However even with that extras and tags are returned separately, there is no guarantee that between fetching returning the tow maps another thread is no jumping in and modifying the one that is returned later. So if that's not a concern a `ConcurrentHasMap` seems like a better solution.

**Comment by bruno-garcia** [comment]
> So I think we need to answer this question first: do we want snapshot or live thread-safe access?

IMO `getTags` is useful to let one inspect the values but doesn't need (should?) to return the internal reference. Even if we turned into a concurrent, if one does `getTags`, reads values, decides what to do next, and does so. By the time that happens the values could have changed. The synchronization would need to be elsewhere and it doesn't seem like a real use-case here.

That said, it would make sense to return a copy and let the caller use the values without further contention.

If we can agree with this ^ I've opened #814 to address the issue.

**Comment by mos8502** [comment]
Sorry, was out due to long holiday in Australia. As #814 solves my original problem is there any point in keeping this issue open ? The discussion involved some other questions, but if those are still valid and are a concern, a separate issues can be opened for them. 

Also: when is the next planned release ?

**Comment by bruno-garcia** [comment]
Yes. It was open to close when a release is done. But I'll close now.
We hope to get a new release out soon

**Comment by bruno-garcia** [comment]
@mos8502 It's finally out: https://github.com/getsentry/sentry-java/releases/tag/v1.7.30
Let us know if you have any issues. Cheers!
