### ISSUE TITLE
Support pro guard mapping upload for bundle files

### ISSUE THREAD

**Issue by DanielHabenicht** [getsentry/sentry-java#818]
Currently, only uploading pro guard files for `apk` is supported (https://github.com/getsentry/sentry-java/issues/528). 

Uploading pro guard mapping files for bundles (`*.aab`) should be supported as well.

**Comment by marandaneto** [comment]
@DanielHabenicht thanks, we'll be looking into it soon.

**Comment by marandaneto** [comment]
@DanielHabenicht it might take a few hours to be available on mavenCentral, but a new version is published, please let us know if you find issues :)
https://github.com/getsentry/sentry-java/releases/tag/v1.7.31_gradle_plugin
