### ISSUE TITLE
Don't receive UncaughtException on Android 10

### ISSUE THREAD

**Issue by AlexKorvin** [getsentry/sentry-java#819]
Hello.

I'm using for project this version of Sentry:
`implementation 'io.sentry:sentry-android:1.7.27'`

And here how I init it in code:
`Sentry.init("dsn", new AndroidSentryClientFactory(context.getApplicationContext()));`

This logic works well for a device with Android 5.1.1 for Uncaught Exceptions (I can see crash on the server), but doesn't work for Android 10(no crash).

Also here are logs for both devices, maybe they will be useful.
For a device with Android 5.1.1:
`D/io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry from Android Context.
D/io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='net.ivpn.client.IVPNApplication@14bd0c56'
D/io.sentry.DefaultSentryClientFactory: Using an HTTPS connection to Sentry.
V/io.sentry.config.provider.JndiSupport: JNDI is not available: javax.naming.InitialContext
D/io.sentry.config.FileResourceLoader: The configuration file sentry.properties (which resolves to absolute path /sentry.properties) doesn't exist, is not a file or is not readable.
W/io.sentry.DefaultSentryClientFactory: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
D/io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/data/net.ivpn.client/cache/sentry-buffered-events
D/io.sentry.buffer.DiskBuffer: 0 stored events found in dir: /data/data/net.ivpn.client/cache/sentry-buffered-events
D/io.sentry.DefaultSentryClientFactory: The current environment doesn't provide access to servlets, or provides an unsupported version.
D/io.sentry.SentryClient: Adding 'io.sentry.event.helper.ContextBuilderHelper@1779502e' to the list of builder helpers.
D/io.sentry.SentryClientFactory: Configuring uncaught exception handler.
D/io.sentry.SentryClientFactory: default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$UncaughtHandler'
W/io.sentry.DefaultSentryClientFactory: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
D/io.sentry.SentryClient: Adding 'io.sentry.android.event.helper.AndroidEventBuilderHelper@26a957cf' to the list of builder helpers.
D/io.sentry.android.AndroidSentryClientFactory: ANR is='false'
V/io.sentry.SentryClientFactory: Uncaught exception received.
D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
D/io.sentry.event.EventBuilder$HostnameCache: Updating the hostname cache
D/io.sentry.buffer.DiskBuffer: Adding Event to offline storage: /data/data/net.ivpn.client/cache/sentry-buffered-events/43325094-8cbb-475b-bccf-1f0053f3582d.sentry-event
D/io.sentry.buffer.DiskBuffer: 1 stored events are now in dir: /data/data/net.ivpn.client/cache/sentry-buffered-events
D/io.sentry.buffer.DiskBuffer: Discarding Event from offline storage: /data/data/net.ivpn.client/cache/sentry-buffered-events/43325094-8cbb-475b-bccf-1f0053f3582d.sentry-event
`

And logs for Android 10:
`D/io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry from Android Context.
D/io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='net.ivpn.client.IVPNApplication@8cc3b59'
D/io.sentry.DefaultSentryClientFactory: Using an HTTPS connection to Sentry.
V/io.sentry.config.provider.JndiSupport: JNDI is not available: javax.naming.InitialContext
D/io.sentry.config.FileResourceLoader: The configuration file sentry.properties (which resolves to absolute path /sentry.properties) doesn't exist, is not a file or is not readable.
W/io.sentry.DefaultSentryClientFactory: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
D/io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/user/0/net.ivpn.client/cache/sentry-buffered-events
D/io.sentry.buffer.DiskBuffer: 0 stored events found in dir: /data/user/0/net.ivpn.client/cache/sentry-buffered-events
D/io.sentry.DefaultSentryClientFactory: The current environment doesn't provide access to servlets, or provides an unsupported version.
D/io.sentry.SentryClient: Adding 'io.sentry.event.helper.ContextBuilderHelper@9f8fc91' to the list of builder helpers.
D/io.sentry.SentryClientFactory: Configuring uncaught exception handler.
D/io.sentry.SentryClientFactory: default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$KillApplicationHandler'
W/io.sentry.DefaultSentryClientFactory: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
D/io.sentry.SentryClient: Adding 'io.sentry.android.event.helper.AndroidEventBuilderHelper@51de7f6' to the list of builder helpers.
D/io.sentry.android.AndroidSentryClientFactory: ANR is='false'
V/io.sentry.SentryClientFactory: Uncaught exception received.
D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
D/io.sentry.event.EventBuilder$HostnameCache: Updating the hostname cache
D/io.sentry.buffer.DiskBuffer: Adding Event to offline storage: /data/user/0/net.ivpn.client/cache/sentry-buffered-events/34ba270e-d302-49ba-9a4b-28b7b9e011b3.sentry-event
D/io.sentry.buffer.DiskBuffer: 1 stored events are now in dir: /data/user/0/net.ivpn.client/cache/sentry-buffered-events
D/io.sentry.buffer.DiskBuffer: Discarding Event from offline storage: /data/user/0/net.ivpn.client/cache/sentry-buffered-events/34ba270e-d302-49ba-9a4b-28b7b9e011b3.sentry-event
`

The only difference I can see is in what kind of UncaughtExceptionHandler class is used as default. 
For Android 10:
`class='com.android.internal.os.RuntimeInit$KillApplicationHandler'`
And for Android 5.1.1:
`class='com.android.internal.os.RuntimeInit$UncaughtHandler'`

Could someone help me with that?

**Comment by marandaneto** [comment]
@AlexKorvin hey, thanks for reporting this issue.
Could you try the latest version? `1.7.30`
I don't see `UncaughtExceptionHandler` being a problem.

Which device is it?

Also, I'd like to invite you to try out the brand new Sentry Android SDK https://github.com/getsentry/sentry-android :) feedback is welcomed, thanks.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
