### ISSUE TITLE
Add event filtering

### ISSUE THREAD

**Issue by fmartinou** [getsentry/sentry-java#824]
Hi,

Any plan to implement the [event filtering](https://docs.sentry.io/error-reporting/configuration/filtering/?platform=javascript) feature?

The `addShouldSendEventCallback` is fine to prevent some events to be sent but what if we just want to obfuscate some data before sending the event?

Regards

**Comment by marandaneto** [comment]
hey, @fmartinou are you using sentry-java on a server or android App.? thanks

**Comment by fmartinou** [comment]
Hi @marandaneto ,

I'm using sentry-java on servers apps (Spring Boot apps actually).

**Comment by marandaneto** [comment]
Hi @fmartinou I've just checked the sprint-boot package and it seems already available.
Have you checked https://github.com/getsentry/sentry-java/blob/master/sentry-spring-boot-starter/src/main/java/io/sentry/spring/autoconfigure/SentryAutoConfiguration.java#L98 ?

**Comment by fmartinou** [comment]
Like I said in my first message, `shouldSendEventCallback` can be used to prevent an event to be sent.  
My need is not to drop the event but to transform it for security reasons before sending it (for example masking payment card numbers...).

Because the Sentry Event object is immutable, I cannot mutate it in the `shouldSendEventCallback` (I just can return true/false to indicate if I want the event to be sent or not).

Do you see any way to implement something like that?

**Comment by marandaneto** [comment]
> Like I said in my first message, `shouldSendEventCallback` can be used to prevent an event to be sent.
> My need is not to drop the event but to transform it for security reasons before sending it (for example masking payment card numbers...).
> 
> Because the Sentry Event object is immutable, I cannot mutate it in the `shouldSendEventCallback` (I just can return true/false to indicate if I want the event to be sent or not).
> 
> Do you see any way to implement something like that?

hey, yep, my bad, sorry.

So yes, there's something ongoing, but I cannot tell you now for when this is gonna be done.
Our plan is to make our repo sentry-android/sentry-core the new sentry-java which follows our unified API and this feature is already there.

https://github.com/getsentry/sentry-android/blob/master/sentry-core/src/main/java/io/sentry/core/SentryOptions.java#L657

Right now this lives in the sentry-android repo only.

**Comment by fmartinou** [comment]
I understand.
I hope both projects could be merged soon...

Thank you!

**Comment by brandonweng-db** [comment]
Hi @marandaneto, thanks for working on this. 

This might be a silly question, but could we use `sentry-android/sentry-core` as an alternative to sentry-java on the server side? I see that there's a [sentry-core package](https://bintray.com/getsentry/sentry-android/io.sentry:sentry-core?tab=overview#)

**Comment by marandaneto** [comment]
hey @brandonweng-db it'd be possible but it's not prod. ready, by that I mean, this would require a bit of boilerplate on your side, we are gonna work on the new sentry-java SDK using sentry-core, indeed, but right now it's focused on the Android SDK needs, sentry-core is Java only, no Android FW dependencies.

**Comment by brandonweng-db** [comment]
I see, thanks for the quick response!
