### ISSUE TITLE
Thead leak in sentry-pool

### ISSUE THREAD

**Issue by vonox7** [getsentry/sentry-java#826]
When letting sentry run on a server machine for several days, every few days we get (on different projects with different architecture) a threadleak caused by sentry. Note that even when waiting hours the threads from the sentry-pool will not disappear (even when no further exceptions were logged) until we restart the whole application.

The threads were dumped via `Thread.getAllStackTraces()` and look all the same like the following thread (note that this is the 107th thread in the sentry thread pool!) :

```
sentry-pool-107-thread-1/main(daemon)-WAITING
jdk.internal.misc.Unsafe.park(Unsafe.java:-2)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:483)
java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:671)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.lang.Thread.run(Thread.java:834)
```

All dumped threads (redacted by threads that would reveal internal logic about the backend) are here: https://gist.github.com/vonox7/3f431334ab694fbffd7d86b072205414

Note that we did not specify any configuration parameters to sentry except disabling the default uncaught exception handler via `"uncaught.handler.enabled" to "false"` and providing our own defaultExceptionHandler via 
```
      sentry = SentryClientFactory.sentryClient(sentryDsn, defaultSentryClientFactory!!)!!
      val defaultExceptionHandler = Thread.getDefaultUncaughtExceptionHandler()

      Thread.setDefaultUncaughtExceptionHandler { thread, exception ->
        println(exception)
        sentry.sendEvent(...)
        defaultExceptionHandler?.uncaughtException(thread, exception)
      }
```

The sentry version is 1.7.30, but the error occured also in 1.7.16.

Expected behaviour: Sentry does not spawn more than 100 threads and will get back to a reasonable amount of threads when no further exceptions occour.

**Comment by metlos** [comment]
There are 2 numbers in the thread pool name. The first one is the number of created sentry clients, the second one is the "id" of the thread in a thread pool created for that client.

So it seems to me your application repeatedly creates new instances of sentry client, which should not be strictly necessary.

Could you confirm that could be the case?

**Comment by functionaldude** [comment]
Yes, our application repeatedly creates new instances of sentry client.

**Comment by metlos** [comment]
So the only suggestion I have is either to reuse a single instance of the client or to close the connection of the client once you are done with it using `SentryClient.closeConnection()` (https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/SentryClient.java#L268). That will ensure the thread pool is shut down.

**Comment by functionaldude** [comment]
Thank you, we will try that, and report back with the results!

**Comment by functionaldude** [comment]
So I investigated the thread leak and it turned out there are 2 possible ways to fix it: 
1. by calling `SentryClient.closeConnection()` after we are done 
2. by setting `async` to `false`

I've decided to go with option 2 because a SentryClient in our case just sends one or two events before it's closed.

**Comment by bruno-garcia** [comment]
Sounds like the issue is resolved. Feel free to reopen if that's not the case.
