### ISSUE TITLE
Disable ssl check

### ISSUE THREAD

**Issue by jflefebvre06** [getsentry/sentry-java#829]
Could you please add an option to disable ssl verifu (hostname, self signed certificats, ...)

**Comment by bruno-garcia** [comment]
It's supported by appending `naive+` to the URL scheme in the DSN. Like:

`naive+https://key@sentry.io/1`

**Comment by marandaneto** [comment]
Closing the issue, as it seems like the original issue has been resolved.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
