### ISSUE TITLE
How can I get/store last event id for user feedback custom integration?

### ISSUE THREAD

**Issue by ricardogobbo** [getsentry/sentry-java#835]
I'm developing a custom error page with a user feedback form submission, but I don't have any clue how can I get the event id. Do you have any suggestions?

I'm using Grails + Sentry plugin, but it helps if is in Spring.

**Comment by piotrblasiak** [comment]
I do it like this:

EventBuilder eventBuilder = new EventBuilder()
							.withLogger(getClass().getCanonicalName())
							.withLevel(Level.ERROR)
							.withMessage(throwable.getMessage())
							.withSentryInterface(new ExceptionInterface(throwable));
					
					final Event event = eventBuilder.build();
					reference = event.getId().toString().replaceAll("-", "");
					
					Sentry.capture(event);

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1

all `Sentry.captureMethods` return a `SentryId`
