### ISSUE TITLE
Add documentation for Spring Boot starter package

### ISSUE THREAD

**Issue by jasonab** [getsentry/sentry-java#837]
In the Sentry documentation, it explicitly says to not use the Spring integration class, if possible, because the logging integrations are superior

> A Sentry logging integration is more general and will capture errors (and possibly warnings, depending on your configuration) that occur inside or outside of a Spring controller. In most scenarios, using one of the logging integrations instead of sentry-spring is preferred.

But I see in #748 that we should be using the Spring Boot starter package to load up our configuration, then also configure a logging integration? It would be helpful if this approach were documented explicitly on the Sentry site.

**Comment by maciejwalkowiak** [comment]
Thanks @jasonab for reporting! Guide has been updated including how to set up Spring Boot with logging: https://docs.sentry.io/platforms/java/guides/spring-boot/
