### ISSUE TITLE
Can I build on Android without targetCompatibility 1.8 directives

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-java#839]
Hi there,

I am trying to use the SDK with minimal amount of changes to our current projects. Do you know what will happen if I dont' have those compatibility directives ? Are they required in all cases.

Thanks !

**Comment by bsergean** [comment]
I think the answer is no. Closing this :)

**Comment by marandaneto** [comment]
hey @bsergean this project is Java 7 compatible, maybe even 6.
we are talking about `sentry-android` v1.x here.

`sentry-android` v2 requires Java 8, we use lambadas, default interfaces, method references, etc...
Java 8 is enabled by default on Android since AGP 3.0
