### ISSUE TITLE
Question on unsafe "naive" HostnameVerifier

### ISSUE THREAD

**Issue by intrigus-lgtm** [getsentry/sentry-java#861]
Hi,
I've stumbled upon
https://github.com/getsentry/sentry-java/blob/cc4b3738e6d42d0a02eb69ae63388d0c408386a8/sentry/src/main/java/io/sentry/connection/HttpConnection.java#L53-L58
and I'm wondering WHY it is included?
I.e. what problem does this solve?
https://github.com/getsentry/sentry-java/blob/cc4b3738e6d42d0a02eb69ae63388d0c408386a8/sentry/src/main/java/io/sentry/connection/HttpConnection.java#L50-L52
talks about "wildcard certificates".
But what do wildcard certificates have to do with hostname verification?
And what does this have to do with truststores?

HTTPS works (AFAIK) like this:
1. User connects to server.
2. Server presents certificate including intermediate certificates.
3. User verifies that server's certificate including intermediate certificates are valid and lead to a trusted root certificate.
4. User verifies that the certificate the server sent also matches the server identity.
This means that the user verifies that the certificate `google.com` shows is actually for `google.com` and not for `malicious.site`.

I don't use sentry so I may miss the specific use-case, but as far as I understand sentry works like this:
1. User catches exception.
2. User sends exception to public and sentry-controlled server.
3. Therefore the server should have a valid certificate.

Or, does sentry also offer private servers that are controlled by customers?
In this case they should probably also have a valid certificate...

**Comment by marandaneto** [comment]
I believe this is necessary because of on-premise servers, but I'll let @bruno-garcia double-check this.

**Comment by bruno-garcia** [comment]
This is used by [on-prem](github.com/getsentry/onpremise) users as @marandaneto pointed out.
Users can host Sentry and use TLS with a self-signed cert. They simply ignore the cert validation from the client.

**Comment by intrigus-lgtm** [comment]
Sorry if this might be a stupid question, but WHERE are you ignoring certificate validation?
That is, where are these self-signed certs added to the app to trust?

The bypassSecurity=true stuff *should* not accept self-signed certificates, but only that I can present a certificate for `not.google.tld` when accesing `google.com`.
The certificate itself would still have to be added to the trust store or trusted in some other way.

So why is the disabled hostname verification needed?
Users that user on-premise servers should be able to get matching self-signed certificates with the right hostnames, shouldn't they?

Thanks for the quick response and your patience.

**Comment by bruno-garcia** [comment]
This option can be used by users who often have their clients and server on a private network and have no convern of any validation of the other endpoint. If that's not useful to you, there's no need to opt-in to the feature.

**Comment by bruno-garcia** [comment]
This has been added to the SDK [originally in sentry-java back in 2013](https://github.com/getsentry/sentry-java/commit/5a599b6d368e2aa7b25b8d9ab564eb4f92e075e4). It's an opt-in and unless you fiddle with `bypassSecurity` it will not take any effect.

**Comment by intrigus-lgtm** [comment]
It still seems to be the case that this option is not having the effect it claims to have.
It says:
> HostnameVerifier allowing wildcard certificates to work without adding them to the truststore.
It will **not** allow wildcard certificates to work.
It will **not** allow a certificate (that is currently untrusted) to work without adding it to the trust store.
It will **not** accept **any** self-signed certificate.

Therefore I see no real use for this...

Anyway, I think you can close this issue.


https://github.com/getsentry/sentry-java/issues/25#issuecomment-9482001
> The documentation on naive HTTPS is wrong. It simply tells Java to ignore the SSL hostname verification which is needed for wildcard certificates to work under JRE 6 or older. Java will still validate the certificate.

https://github.com/getsentry/sentry-java/issues/64#issuecomment-18806956
> getsentry.com only allows HTTPS, so you should use the "naive" version of the http connection (with `naive+https`) as indicated in the README file.

https://github.com/getsentry/sentry-java/issues/64#issuecomment-18809991
> I'll try to use the naive+https connector, however I've noticed that it still won't accept the certificate yet so I'll either have to import the StartSSL CA or wait until the SSL switch is made.

https://github.com/getsentry/sentry-java/issues/64#issuecomment-18812245
> Okay, I got a lot of things wrong then. Indeed the naive option only allows subdomains (which isn't supported in some versions of Java if the certificate isn't added to the truststore) but still checks the validity of the certificate.

**Comment by marandaneto** [comment]
you can use `options.setHostnameVerifier(...);` on App. init if necessary
