### ISSUE TITLE
Add APM for Java sdk

### ISSUE THREAD

**Issue by tlf30** [getsentry/sentry-java#876]
Would it be possible to get APM (Application Performance Monitoring) for Java?
Even the ability to manually build spans, transactions, and traces would be very useful when trying to get performance metrics across a large application deployment base. 

In the future this would be great to have server side for servlets.

Thanks,
Trevor

**Comment by marandaneto** [comment]
on the works https://github.com/getsentry/sentry-java/pull/971

**Comment by marandaneto** [comment]
it's already on Alpha, https://docs.sentry.io/platforms/java/performance/
