### ISSUE TITLE
Migration guide for `sentry` package.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#877]
A initial migration exists: https://docs.sentry.io/platforms/android/migrate/

https://github.com/getsentry/sentry-android/blob/feat/sentry-java/MIGRATION.md

Go through the docs of Java 1.x and revisit this

Note: Version 3.0 requires Relay (and Envelope support) so Sentry on-premise users need to upgrade to calver v20.6.0

Here we can keep track of new API and configuration changes:

**Comment by marandaneto** [comment]
for Android https://docs.sentry.io/platforms/android/migration/#migrating-from-sentry-android-2x-to-sentry-android-3x

**Comment by maciejwalkowiak** [comment]
@bruno-garcia can we close this?

**Comment by marandaneto** [comment]
guess so because of https://docs.sentry.io/platforms/java/migration/
we can iterate over it if customers are having issues during migration
