### ISSUE TITLE
Add deduplication of events based on exception weakref

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#884]
This approach was taken in different SDK, for example .NET:

https://github.com/getsentry/sentry-dotnet/blob/ba4e1f46c843eec57f1e93a2376b533b8d84ebfd/src/Sentry/Internal/DuplicateEventDetectionEventProcessor.cs#L41-L54

This was raised in this article: https://dev.to/focusedlabs/sentry-with-spring-boot-1jko
Would be nice to drop a comment there once the problem is solved.

Also, update the docs since then the integrations will play along more nicely.

**Comment by marandaneto** [comment]
@bruno-garcia @maciejwalkowiak we can close this, right?
