### ISSUE TITLE
How to add tag SentryAndroid?

### ISSUE THREAD

**Issue by TanDatDo** [getsentry/sentry-java#886]
Currently trying to add extra tag for SentryAndroid.init() via ScopeCallback, but seems like not working.

SentryAndroid.init(context, new Sentry.OptionsConfiguration<SentryAndroidOptions>() {
            @Override
            public void configure(SentryAndroidOptions options) {
                Sentry.configureScope(new ScopeCallback() {
                    @Override
                    public void run(Scope scope) {
                        Sentry.setTag(Constant.INSTALL_ID_SENTRY_KEY,"installId");
                    }
                });
            }
        });

How can we have extra tag for default AndroidSentry?

**Comment by bruno-garcia** [comment]
You can set the tag calling `Sentry.setTag` after you call `Sentry.init`.
There's no need to call that inside the callback. The callback is execute before the SDK initializes, it uses the object it configures to init.
