### ISSUE TITLE
Periodic No JSON data was found errors 

### ISSUE THREAD

**Issue by brandonweng-db** [getsentry/sentry-java#887]
Hi,

We're seeing some periodic request failures with the following error:
```
io.sentry.connection.ConnectionException: {"error":"No JSON data was found"}
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:216)
	at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:88)
	at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This is showing up when we use log4j integration and also when we manually send the exception to Sentry. Looking at nginx logs, the request body is indeed empty, however when we added an event hook to print the event on failure, it shows a normal event that's already made it to Sentry previously... Only thing I can think of is might be the marshaller being unable to serialize an event properly (but i couldn't find any debug/error logs for that)?

We're using an DSN with `https://` prefix and tired disabling compression.

Some similar issues I found, but I'm not sure if it applies: 
https://github.com/getsentry/sentry/issues/6978#issuecomment-500786454 
https://github.com/ozean12/sentryR/issues/2
https://github.com/getsentry/sentry-php/issues/871

Thanks!!

**Comment by marandaneto** [comment]
hey, can you provide more context please? SDK version, integration, etc...

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
