### ISSUE TITLE
Decide to move servlet support or not: https://github.com/getsentry/sentry-java/tree/master/sentry/src/main/java/io/sentry/servlet

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#889]
A proposal from @metlos is here: https://github.com/metlos/sentry-java-2.0/blob/master/integrations/sentry-servlet/src/main/java/io/sentry/servlet/SentryServletRequestListener.java

**Comment by marandaneto** [comment]
@bruno-garcia should we close this? we have the package `sentry-servlet` already
