### ISSUE TITLE
How do i debug sentry integration? Its not sending test error to server from my java code

### ISSUE THREAD

**Issue by Shubham1992** [getsentry/sentry-java#898]

**Comment by marandaneto** [comment]
can you provide more context, please?

**Comment by maciejwalkowiak** [comment]
@Shubham1992 when initializing Sentry, you can enable debug logs:

```java
Sentry.init(options -> {
    options.setDebug(true);
    // other options like DSN
});
```

Depending which integration you're using, setting debug can look slightly different. Please look into updated Java guides https://docs.sentry.io/platforms/java/

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
