### ISSUE TITLE
A binary image is referenced that is unknown.

### ISSUE THREAD

**Issue by JavanHuang123** [getsentry/sentry-java#905]
After we use sentry, we find that native crash will display as follows:
 "A binary image is referenced that is unknown."
May I ask what is the reason?

**Comment by marandaneto** [comment]
@JavanHuang123 any update on this? have you tried to integrate our plugin and tested on release mode?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
