### ISSUE TITLE
NDK events don't include breadcrumbs 

### ISSUE THREAD

**Issue by eakoli** [getsentry/sentry-java#907]
_Platform:_
- [x]  Android -> SDK 28, target 16
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [x]  NDK -> NDK 17 gcc/gnustl_static
- [ ]  React-Native -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle ->  4.10.2
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> 3.2.1
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes ->2.2.2
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_sentry-android installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of sentry-android:
**2.2.2**

---
I have the following issue:

Crash/events generated from the NDK later (sentry-native) don't include any of the breadcrumbs generated from the android side.

Is there a plan to marry the two frameworks so that regardless of which side triggers the event they get comparable events and associated data? 

The description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1

enable it on the manifest:

`<meta-data android:name="io.sentry.ndk.scope-sync.enable" android:value="true" />`
