### ISSUE TITLE
Crash not reported: 413 response code when uploading with large/many breadcrumbs

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-java#910]
_Platform:_
- [X]  Android -> compile 29 target 29, device is running 28
- [X]  Java -> 1.8/1.8
- [X]  Kotlin -> 1.3.72, jvmTarget 1.8

_IDE:_
- [X]  Android Studio -> 4.1 Canary 8

_Build system:_
- [X]  Gradle -> 6.3-all

_Android Gradle Plugin:_
- [X]  Yes -> 4.1.0-alpha08

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Proguard/R8:_
- [X]  Disabled

_sentry-android installed with:_
- [X] JCenter

The version of sentry-android:
**2.0.0**

---
I have the following issue:

The description goes here ...

**Steps to reproduce:**
- Force the app to crash

**Actual result:**
- No crash is uploaded to Sentry.

**Expected result:**
- Crash is uploaded to Sentry.

This doesn't happen for all of our crashes, afaict, just some.  The error in question is coming from a kotlin-multiplatform library, if that's relevant.

I've got the debugger hooked up, is there any way to gather additional information about why this isn't able to be written to disk quickly enough?

**Comment by bruno-garcia** [comment]
We decided not to truncate it for a few reasons:

* The max size of the payload changes overtime
* Truncating can affect the device performance negatively
* We can truncate breadcrumbs but multiple other areas of the event can be the cultprit such as user, extra and context
* The goal is to surface stats first so users can identify what areas are causing it and address the data before adding to Sentry's SDK

Ideally Sentry would have a dead letter queue with some sample events

**Comment by edenman** [comment]
1) Max payload size changes: filed #1695 
2) Truncating can affect device performance?  Really?  It's removing items from a list, we're not doing any serious calculation
3) Truncating breadcrumbs is the easiest and most obvious low-hanging fruit.  While it's true there could be other causes of a too-large payload, removing breadcrumbs would fix this issue for 90% of cases, I'm guessing
4) Exposing stats doesn't help me track down the crash.  The whole point of this library is to help me track down crashes in my app.
