### ISSUE TITLE
Detect app crashed last launch

### ISSUE THREAD

**Issue by chreck** [getsentry/sentry-java#911]
_Platform:_
- [x]  Android 
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    minSdkVersion 21
    targetSdkVersion 29
- [x]  Java 
        sourceCompatibility = 1.8
        targetCompatibility = 1.8

- [ ]  Kotlin
- [ ]  NDK

_IDE:_
- [x]  Android Studio 3.5.3

_Build system:_
- [x]  Gradle 5.4.1

_Android Gradle Plugin:_
- [x]  Yes 3.5.3

_Sentry Android Gradle Plugin:_
- [x]  Yes 1.7.31

_Proguard/R8:_
- [x]  Enabled
- [ ]  Disabled

_sentry-android installed with:_
- [x] JCenter

The version of sentry-android:
**2.0.0**

---
I have the following question:

If I have a crash in my mobile app which is happening during the startup, I do not get them in sentry. So my question is "How can I transmit the previous crash"? 

On iOS there is a possibility to detect if a previous crash happened or not. It is 
`[SentryClient.sharedClient crashedLastLaunch]` . On the iOS side of my mobile app I implemented manually

1. Init Sentry
2. detect if a crash was happening
3. wait 2 seconds (hope that the crash is transmitted)
5. initialise the app

Is there a similar possibility on the Android side, how can I see the open transmissions to sentry backend?

**Comment by marandaneto** [comment]
dup of #1125
