### ISSUE TITLE
User data missing in native crash report

### ISSUE THREAD

**Issue by AndrewVovk** [getsentry/sentry-java#913]
First of all, thanks for your brilliant error tracking software!

I'm using Sentry 2.0.0-alpha08 version.

Have set the User this way:
```
Sentry.configureScope(scope -> {
            User user = new User();
            user.setId(userId);
            user.setUsername(userName);
            user.setEmail(userEmail);
            scope.setUser(user);
        });
```

Java crashes are reported perfectly, including user data, but in native crash reports there's no username and e-mail, and userId differs from the one that I set.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1

enable it on the manifest:

`<meta-data android:name="io.sentry.ndk.scope-sync.enable" android:value="true" />`
