### ISSUE TITLE
Logging an exception with multiple causes

### ISSUE THREAD

**Issue by headsvk** [getsentry/sentry-java#914]
Hey guys,
I came across a need to log [GlideException](https://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/load/engine/GlideException.html) which specifies multiple root causes. I'd like to log it as a single event in Sentry so I was thinking this would be possible if I created an exception with multiple suppressed exceptions and Sentry would log them all by calling [getSuppressed](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#getSuppressed()).

What do you think about such a feature? Is there a reason suppressed exceptions are not logged now?
Thanks

**Comment by marandaneto** [comment]
hey @headsvk have you tried it? :) thanks

**Comment by headsvk** [comment]
ah no sorry, I forgot because I didn't need it in the end

**Comment by marandaneto** [comment]
just noticed this is a dup of #542
so I'll close this one, thanks
