### ISSUE TITLE
What's the proper way to flush Sentry's local event queue synchronously?

### ISSUE THREAD

**Issue by techyourchance** [getsentry/sentry-java#916]
Use case:
I want to ensure that all Sentry events are pushed upstream before I shut the application down.

What I tried:
`Sentry.flush(timeout) `
This sounds like what I want to do, but it didn't work reliably and Javadoc says that something isn't implemented there.

```
Sentry.flush(timeout)
Sentry.close()
```
This combo seems to work, but it's not clear from docs whether that's the way I should use, and whether it provides any guarantees at all.

**Comment by maciejwalkowiak** [comment]
I found a way to implement flush using improved version of `CountdownLatch`/`Phaser` - https://github.com/MatejTymes/JavaFixes/blob/master/src/main/java/javafixes/concurrency/ReusableCountLatch.java

It's a tiny class we could copy to our codebase. This will also enable users to use Java SDK with AWS Lambdas. Thoughts @bruno-garcia @marandaneto ?

**Comment by marandaneto** [comment]
> I found a way to implement flush using improved version of `CountdownLatch`/`Phaser` - https://github.com/MatejTymes/JavaFixes/blob/master/src/main/java/javafixes/concurrency/ReusableCountLatch.java
> 
> It's a tiny class we could copy to our codebase. This will also enable users to use Java SDK with AWS Lambdas. Thoughts @bruno-garcia @marandaneto ?

That sounds like a good approach for fixing a `// TODO: Flush transport` :)
