### ISSUE TITLE
Alpha release of 3.x breaks build

### ISSUE THREAD

**Issue by mrbar42** [getsentry/sentry-java#934]
_Platform:_
- [x]  Android
compileSdkVersion:29
targetSdkVersion:29
buildToolsVersion:29.0.3
- [x]  Kotlin 1.3.72 (1.8)

_IDE:_
- [x]  Android Studio

_Build system:_
- [x]  Gradle 5.6.4

_Android Gradle Plugin:_
- [x]  Yes 3.6.3

_Sentry Android Gradle Plugin:_
- [x]  No

_Proguard/R8:_
- [x]  Enabled

_Platform installed with:_
- [x] JCenter

The version of the SDK:
**3.0.0-alpha.3**

---
### I have the following issue:

Builds started failing with dependency resolution error where sentry could not been resolved correctly.

on Sep 17 you seem to have [pre-released an alpha version](https://github.com/getsentry/sentry-java/releases/tag/3.0.0-alpha.3) but unfortunately is was deployed to the [production repos](https://bintray.com/getsentry/sentry-android/io.sentry%3Asentry-android) under the `latest` **AND** `release` tags hence it became the absolute **default version** in cases where no explicit version was defined.

<details>
<summary>here's an excerpt from the maven-metadata.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>io.sentry</groupId>
  <artifactId>sentry-android</artifactId>
  <version>3.0.0-alpha.3</version>
  <versioning>
    <latest>3.0.0-alpha.3</latest>
    <release>3.0.0-alpha.3</release>
    <versions>
      <version>1.0.0-beta</version>
      <version>1.0.0-beta2</version>
      <version>1.0.0-beta3</version>
      <version>1.0.0</version>
```
</details>

In addition, regardless of the alpha-as-default situation, the dependency fails to resolve even when specifying the explicit version.
It looks like the sub-dependencies path is not fully available on jcenter
io.sentry:sentry-android -> io.sentry:sentry-android-core -> io.sentry:sentry (< this doesn't exist on jcenter)

the `3.0.0-alpha.3` was released to the general bintray but not to jcenter 

this works ↓
https://dl.bintray.com/getsentry/sentry-android/io/sentry/sentry/3.0.0-alpha.3/:sentry-3.0.0-alpha.3.pom
this doesn't exist ↓
https://jcenter.bintray.com/io/sentry/sentry/3.0.0-alpha.3/:sentry-3.0.0-alpha.3.pom

### Steps to reproduce:

1. define `jcenter()` in project's `build.gradle` under repositories

2. add sentry dependency with `latest` pointer or set the new alpha version
```gradle
implementation "io.sentry:sentry-android:latest.release"
# OR
implementation "io.sentry:sentry-android:3.0.0-alpha.3"
```

3. build

### Actual result:
build fails with error

```
Could not find io.sentry:sentry:3.0.0-alpha.3.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/io/sentry/sentry/3.0.0-alpha.3/sentry-3.0.0-alpha.3.pom
  - https://dl.google.com/dl/android/maven2/io/sentry/sentry/3.0.0-alpha.3/sentry-3.0.0-alpha.3.jar
  - https://repo.maven.apache.org/maven2/io/sentry/sentry/3.0.0-alpha.3/sentry-3.0.0-alpha.3.pom
  - https://repo.maven.apache.org/maven2/io/sentry/sentry/3.0.0-alpha.3/sentry-3.0.0-alpha.3.jar
  - https://jcenter.bintray.com/io/sentry/sentry/3.0.0-alpha.3/sentry-3.0.0-alpha.3.pom
  - https://jcenter.bintray.com/io/sentry/sentry/3.0.0-alpha.3/sentry-3.0.0-alpha.3.jar
Required by:
    project :app > io.sentry:sentry-android:3.0.0-alpha.3 > io.sentry:sentry-android-core:3.0.0-alpha.3
    project :app > io.sentry:sentry-android:3.0.0-alpha.3 > io.sentry:sentry-android-ndk:3.0.0-alpha.3
```

### Expected result:

non-broken production builds due to alpha releases

---

1. How come an alpha(!) version is released under the `release` tag?
2. why is there such disparity between repos

**Comment by bruno-garcia** [comment]
Thanks for raising this. It's odd that it became the default since this is a pre-release, we'd expect to have to be added manually.

The jcenter issue is known and we're in touch with bintray to figure it out.
In the meanwhile, please use the `bintray` feed to add the SDK (or stay in the 2.x stable version).

We'll update this issue as soon as we hear back from bintray

**Comment by marandaneto** [comment]
@mrbar42 thanks for raising this.

it'd be better for now to: implementation "io.sentry:sentry-android:2.+"

I don't think the maven-publish gradle plugin supports the `latest.release` either, so its basically the latest, not the latest stable one, I'd pin the version max to 2.+ but never to keep it open, I'll see if it's possible to do any work around about this.

About the missing packages on jcenter/mavencentral, yeah, we are trying to figure out to bintray (our proxy), why that package is not being synced.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/3.0.0-beta.1 should be fine on `jcenter`
