### ISSUE TITLE
Create build artifacts with zip'ed up packages

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#950]
Issue 1 of series: #951 #952

At the end of each build (or some publish task of sorts) we need to have all the files such as:

For a Jar, like `sentry`:
`sentry/build/publications/maven/pom-default.xml`
`sentry/build/publications/maven/module.json` - gradle module
`sentry/build/libs/*.jar` 3 jars: sources, docs, classes

Possibly rename the pom, for pushing to maven central. For example `pom-default.xml` becomes `package-version.pom`, if needed. At least this is the name when you download from maven central.

For an Aar like `sentry-android-core`:

`sentry-android-core/build/publications/release/...` the aar
`sentry-android-core/build/libs/*.jar` 2 jars: sources and javadoc
no actual bytecode jar to publish, only the AAR

Each set of files would be added to a zip named after the package, with the version appended:

sentry-3.0.0.zip
sentry-android-core-3.0.0.zip

These files would become build artifacts. The ultimate goal is to use these to publish with `craft`

**Comment by bruno-garcia** [comment]
Trying #990 to publish to zeus on top of the artifacts built in #979

**Comment by marandaneto** [comment]
@maciejwalkowiak could be closed as well right?

**Comment by maciejwalkowiak** [comment]
👍

**Comment by bruno-garcia** [comment]
🚀
