### ISSUE TITLE
Spring Boot "SentryServletContextInitializer" not found in v3

### ISSUE THREAD

**Issue by lehoffma** [getsentry/sentry-java#959]
Hello,
When updating to the newest API version most of the changes were easy enough to find (using scope instead of context etc.), but I couldn't find what the replacement for the Spring Boot HTTP integration is. I'm talking about this piece of code:

```java
@Bean
public ServletContextInitializer sentryServletContextInitializer() {
	return new io.sentry.spring.SentryServletContextInitializer();
}
```

This is also still part of the official [examples](https://github.com/getsentry/examples/blob/master/java/spring-boot/src/main/java/io/sentry/example/Application.java#L37) and I couldn't find any other place that mentions this or a possible replacement.

Thank you!

**Comment by marandaneto** [comment]
@lehoffma thanks for asking.

new docs are live https://docs.sentry.io/platforms/java/guides/spring-boot/ please have a look at it.
cc @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
@lehoffma with the newest SDK there is a dedicated Spring Boot Starter that auto-configures all the beans for you. The only thing you need to do is to set `sentry.dsn` property in `application.properites`. Let us know please if this solves your issues or if you find anything else missing. Thanks!

**Comment by lehoffma** [comment]
Using the autoconfigured version solved my problem for me. Thanks for the quick and helpful responses!
