### ISSUE TITLE
Generate CHANGELOG.md (Alexey did it for .NET)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#960]
/cc @Tyrrrz

**Comment by Tyrrrz** [comment]
Do you mean converting the existing GitHub release notes into CHANGELOG.md?

**Comment by bruno-garcia** [comment]
@Tyrrrz Basically the same thing you did for .NET but here there's a catch:

First releases are here: https://github.com/getsentry/sentry-android/releases

Only the last releases (3.0.0) from this repo, go into the changelog. The 1.7 releases don't since that code base doesn't exist here anymore. The changelog for that existss on that branch.

**Comment by bruno-garcia** [comment]
That nice GH action check too plz :shipit:

**Comment by Tyrrrz** [comment]
Added. Note that the action does not have any sort of ignore option so it will fail all PRs indiscriminately if they don't have a changelog.
