### ISSUE TITLE
Spring boot (using yml config) + Logback is not finding DSN

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#975]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**3.0.0**

---
I have the following issue:

When using Spring boot using application.yml + logback, SDK init fails due to missing DSN.

**Steps to reproduce:**
- Create a sample Spring boot App using Sentry spring boot + logback, config DSN using the application.yml

**Actual result:**
- SDK init fails due to missing DSN.

**Expected result:**
- App should start and report Sentry

**Comment by marandaneto** [comment]
config:
<img width="1256" alt="Screenshot 2020-10-13 at 09 25 22" src="https://user-images.githubusercontent.com/5731772/95829104-1b290400-0d36-11eb-96cb-d816bed39eec.png">

it throws here due to missing DSN:

<img width="615" alt="Screenshot 2020-10-13 at 09 21 07" src="https://user-images.githubusercontent.com/5731772/95828941-e452ee00-0d35-11eb-986d-9258b3430607.png">

this is user's SS, I noticed the `enabled` has extra spaces, but I don't think this is the issue, as the SDK fails for `dsn`

@maciejwalkowiak could you try this out using the `yml` file instead of the `properties` file? thanks

**Comment by maciejwalkowiak** [comment]
Is `SentryAppender` also configured in `logback.xml` file? When Spring Boot integration is used together with Logback, the appender is auto configured and there is no need to add it manually to Logback configuration. 

Complete Maven based example using `application.yml` file: https://github.com/maciejwalkowiak/sentry-spring-boot-logback-sample

**Comment by bruno-garcia** [comment]
Related issue: https://github.com/getsentry/sentry-java/issues/976

**Comment by bruno-garcia** [comment]
This was verified not to be an issue.
