### ISSUE TITLE
Logback: Use MDC as regular Tags

### ISSUE THREAD

**Issue by JulianSudendorf** [getsentry/sentry-java#978]
I'm trying to implement error tracing across the stack as suggested in the [best practices](https://docs.sentry.io/product/sentry-basics/guides/error-tracing/#configuring-sentry).

Our kotlin backend uses Logback extensively and we configured it to use the sentry appender, which works great.
In order to implement error tracing we extract the `transaction_id` from the custom header and put it in the MDC like this

```kotlin
val transactionId = extractFromHeaders()
MDC.put('transaction_id', transactionId)
```

However the [latest docs](https://docs.sentry.io/platforms/java/guides/logback/#mapped-tags) mention that
> By default all MDC parameters are stored under the “MDC” tab in Sentry.

Having the `transaction_id` not available under tags but only under the MDC tab makes it impossible to actual trace an error across applications.

Opening an issue here, since the [legacy docs](https://docs.sentry.io/platforms/java/legacy/logback/#mapped-tags) include the `mdcTags` configuration option to do exactly what I think I need to make this work. I couldn't find the point in time this specific change happened to find an alternative approach:
https://github.com/getsentry/sentry-java/blob/4a9b3cc961e74421b8c56b77cc4808c5ddae2d5b/sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java#L89-L96

The examples in this repo still mentions MDC being transformed to event tags:
https://github.com/getsentry/sentry-java/blob/5ebd49cbfd17eb66175e9247db6d27e4df84a56b/sentry-samples/sentry-samples-logback/src/main/java/io/sentry/samples/logback/Main.java#L14-L15

Is there any other way besides MDC to send tags while using the regular logging? Would there be any other approach to supply a `transaction_id` ?

**Comment by maciejwalkowiak** [comment]
You can set custom tags using `configureScope`:

```
Sentry.configureScope(scope -> {
    scope.setTag("my-tag", "tag-value");
});
```

Could you please give it a try and check if it works for your use case?

**Comment by JulianSudendorf** [comment]
Thank you for clarifying, works as intended!

I was not aware that you could simply set the scope to be picked up by the Logback appender!

**Comment by jessebutterfield** [comment]
We have really complicated logic that copies the MDC from parent threads to child threads in order to trace across futures and I was really hoping not to have to redo all this logic everywhere for the sentry scope. Is there a way to automatically update the scope to the current value of the mdc right before it logs? It seems like using this approach every time I copy over the mdc I'll also have to copy over the sentry scope.

**Comment by maciejwalkowiak** [comment]
We're tracking this change here: https://github.com/getsentry/sentry-java/issues/1148
