### ISSUE TITLE
SENTRY_TAGS environment variable doesn't work after upgrading from 1.7.30 to 3.0.0

### ISSUE THREAD

**Issue by bbednarek** [getsentry/sentry-java#981]
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [X]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? 
```
    targetCompatibility = sourceCompatibility = 14
```
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j -> If yes, which version?
- [X]  Logback -> If yes, which version? `1.2.3`
- [x]  Spring -> If yes, which version? `2.3.4.RELEASE`

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [X]  IntelliJ -> If yes, which version? `2020.2.2`
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [X] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**3.0.0**

---
I have the following issue:

We used to set following environment variable
```
"SENTRY_TAGS": "service:%s" %(self.name),
```
and tags were available in sentry 
![Screenshot 2020-10-14 at 17 10 06](https://user-images.githubusercontent.com/895578/96008784-33854580-0e40-11eb-8c24-26ac9dffddc8.png)

and after upgrading to version `3.0.0` this variable does't work any more.
![Screenshot 2020-10-14 at 17 11 43](https://user-images.githubusercontent.com/895578/96008932-5a437c00-0e40-11eb-87f6-0836efb69fd7.png)

**Steps to reproduce:**
Upgrade 
```
            dependency 'io.sentry:sentry-logback:1.7.30'
```
to
```
            dependency 'io.sentry:sentry-logback:3.0.0'
```

**Actual result:**
Tags are gone

**Expected result:**
Tags are present

**Comment by bruno-garcia** [comment]
Thank you for giving 3.x a try! We'll discuss this internally and get back to you soon.

**Comment by chrsblck** [comment]
I'm having some related issues with external config on `v3.1.0` as well. I can open another issue if you'd like, just let me know.

1. `SENTRY_IN_APP_INCLUDES` environment variable doesn't get applied to config (even when all configs are done via Env. variables)

2. If I combine `application.yml` with environment variables, all the config in `application.yml` is lost.

For example, if I set `SENTRY_DSN=...` and:
```
sentry:
  environment: Dev
```

I will only see the Sentry DSN configured, there will be no Sentry Env configured.

**Comment by bruno-garcia** [comment]
`SENTRY_IN_APP_INCLUDES` isn't included in the new SDK. The are some environment variables whch is default in all Sentry SDKs like `SENTRY_DSN`, `SENTRY_RELEASE` `SENTRY_ENVIRONMENT` which takes presedence over any value set via configuration or programatically, but other than that values can be configured either programatically: `Sentry.init(o -> o.inAppInclude(..)` or when using spring, via the application.properties|yaml.

We should make it clear on the docs that the old environment variables are not necessarily supported, it depends on what it was.

If values set via env var are not considered when you set stuff via configuration, that would be a problem. Would you mind raising an issue for that so we can investigate?

**Comment by chrsblck** [comment]
> We should make it clear on the docs that the old environment variables are not necessarily supported, it depends on what it was.

Yeah, that would be nice if it were documented which env. vars were supported.
