### ISSUE TITLE
Thread info is not present with 3.1.0 (Android-ANR)

### ISSUE THREAD

**Issue by ItsReddi** [getsentry/sentry-java#984]
_Platform:_
- [x]  Android

_IDE:_
- [x]  Android Studio

_Build system:_
- [x]  Gradle

_Sentry Android Gradle Plugin:_
- [x]  Yes
- [ ]  No

_Proguard/R8:_
- [x]  Enabled
- [ ]  Disabled

The version of the SDK:
**3.1.0**

---
I have the following issue:

After upgrading from `2.3.2` to `3.1.0` ANR reports do not include any thread informations.

**Steps to reproduce:**
- 1. use 2.3.2
- 2. example ANR
```
if (true) {
                    int a = 0;
                    while (true) {
                        a++;
                    }
                }
```
Result:
![grafik](https://user-images.githubusercontent.com/3147888/96109995-90840880-0edf-11eb-8c91-a7c9988dacd5.png)

- 3. switch to `3.1.0`
Result:
![grafik](https://user-images.githubusercontent.com/3147888/96110108-b4dfe500-0edf-11eb-88aa-efdd09335890.png)

**Comment by marandaneto** [comment]
thanks for raising this, would you mind to try again but enabling `SentryOptions.attachThreads`? thanks

**Comment by marandaneto** [comment]
this should have done the job: https://github.com/getsentry/sentry-java/blob/5ebd49cbfd17eb66175e9247db6d27e4df84a56b/sentry-android-core/src/main/java/io/sentry/android/core/ApplicationNotResponding.java#L24
I mean it does, but it doesn't look like having the whole stack traces or it's reporting the capturing thread but not the UI one.

**Comment by ItsReddi** [comment]
`SentryOptions.attachThreads` does not seem to make a difference.
Still no threads attached on ANR.
but im unsure it is correct how it is enabled?

![grafik](https://user-images.githubusercontent.com/3147888/96220067-5d498400-0f88-11eb-9854-b57cc5fb132f.png)

**Comment by marandaneto** [comment]
@ItsReddi this config is not available on the manifest config.

you need to: https://docs.sentry.io/platforms/android/usage/advanced-usage/#manual-instrumentation
and do `options.setAttachThreads(true)`

**Comment by ItsReddi** [comment]
I can confirm it works with `setAttachThreads(true)`

**Comment by marandaneto** [comment]
thanks, @ItsReddi we'll be looking into it, this flag should not have interfered in the ANR threads/stack traces if I am guessing it right.
you could use the `setAttachThreads` workaround for now :)

**Comment by ItsReddi** [comment]
Allright, but it would now add the thread info to any Event, also Exceptions, custom errors if i understand the `SentryOptions` Docs correct?

Any way to enabled that only for ANR?

**Comment by marandaneto** [comment]
true, this was enabled by default on sentry-android v2 anyway, so it's not really a problem to send all the threads info, the thing is, most of them are not useful for you to debug the issue.

unfortunately, it's not possible to enable only for ANR, this would be the bugfix, what you can do is, to use the `beforeSend` callback and filter them out based on the exception type (if not ANR).

**Comment by marandaneto** [comment]
just tested it out, https://github.com/getsentry/sentry-java/releases/tag/4.0.0-alpha.2 should give you stack traces of the main thread ootb, no need for `setAttachThreads` unless you want to see stack traces of all the running threads.

Thanks for reporting :)
