### ISSUE TITLE
sentry fails with excluded logback

### ISSUE THREAD

**Issue by tk7r** [getsentry/sentry-java#991]
i have only set the sentry.dsn property and the error is still there.
i have completely excluded logback completely from the classpath. As defined in the spring documentation for running the application with log4j2.

SentryProperties exposes a class "Level" from ch.qos.logback.classic. The simple existence of this class in the "public" api triggers the exception.

I am able to reproduce it only if I set one of the properties:

- `sentry.logging.minimum-breadcrumb-level`
- `sentry.logging.minimum-event-level`

`sentry.logging` sets properties only on Logback integration, it does not work at this stage with Log4j2.

If you have set these properties, could you please remove them and see if error still occurs? If it's not this issue - what properties have you set on `sentry` in `application.properties`?

_Originally posted by @maciejwalkowiak in https://github.com/getsentry/sentry-java/issue_comments/709622303_

**Comment by maciejwalkowiak** [comment]
This has been fixed with: https://github.com/getsentry/sentry-java/pull/987 and will be released in 3.1.1
