### ISSUE TITLE
release, server_name and component no longer picked up after upgrade to 3.x

### ISSUE THREAD

**Issue by francisdb** [getsentry/sentry-java#992]
I did not find a migration guide pointing to things that might break when migrating from 1.x to 3.x?

_Platform:_
*  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version? openjdk 11.0.8 2020-07-14
*  Logback -> If yes, which version? 1.2.3

_Build system:_
* Other -> If yes, which one? sbt

_Platform installed with:_
* Maven Central

The version of the SDK:
**3.1.0**

---
I have the following issue:

We tried sentry-logback `3.1.0` by just changing the version in our build, coming from `1.7.30`

First error came in but we no longer have `release`, `server_name` and `component` tags populated

### Steps to reproduce:

This is how we set them up
**Code**
```scala
// first line in `main` (scala)
System.setProperty("sentry.release", BuildInfo.version)
```

**env var**
SENTRY_SERVERNAME

**sentry.properties**
tags=component:xyz

### Actual result:

None of the above picked up by sentry

### Expected result

Same behavior as when using sentry-logback  `1.7.30`

**Comment by marandaneto** [comment]
dup of #981 ?

**Comment by francisdb** [comment]
> dup of #981 ?

Created a new ticket because we have different things missing and we use different ways to configure each of them

**Comment by marandaneto** [comment]
agreed, but the issue is pretty much the same, I'll talk about it internally, thanks

**Comment by dhufnagel** [comment]
At first I thought I was doing something wrong. But really, the properties were not picked up and now I know, that this is on purpose.. Too bad, as it is really convinient setting the properties and not having to do it manually. Specially if you use integrations like log4j2. 
The in-app-includes are also not configurable anymore (formerly known as stacktrace.app.packages).

**Comment by francisdb** [comment]
The old docs had this

> For many integrations the server name actually corresponds to the device hostname, even in situations where the machine is not actually a server. Most SDKs will attempt to auto-discover this value.

Is this still the case? If not can we somehow have it look up the hostname?
