### ISSUE TITLE
Support two instances of sentry client 

### ISSUE THREAD

**Issue by alexandresoler** [getsentry/sentry-java#993]
Hey guys,

I'm developing an Android SDK and I'm using the Sentry version 1.7.22
I'm getting my personal instance of Sentry with val mySentry = AndroidSentryClientFactory.sentryClient(sentryDSN)
Then, my integrator can use his Sentry in his code with the standard SentryClient with Sentry.init() and Sentry.capture() etc
Then, I can receive my events on my sentry server and he can receive his events on his server.

On the new 3.1.0 version, AndroidSentryClientFactory doesn't exist anymore.

Any solution?

Thanks

**Comment by marandaneto** [comment]
you need to migrate and follow the unified API conventions:

https://docs.sentry.io/platforms/android/migration/

you could create your own `Hub` instance, for example, the `Hub` doesn't add the default integrations btw, be aware of that.

**Comment by arunshankar87** [comment]
Thanks to @marandaneto, was able to achieve this. Just putting the steps if it can help others

1.7.27

Creating a client instance

```
SentryClient client = new AndroidSentryClientFactory(context).createSentryClient(new Dsn(dsn));
```

Capturing the event

```
EventBuilder eventBuilder = new EventBuilder()
            .withMessage(message)
            .withSentryInterface(new ExceptionInterface(e));
client.sendEvent(eventBuilder);
```

3.1.1 

Creating a hub instance

```
SentryOptions options = new SentryOptions();
options.setDsn(dsn);
options.setSerializer(new GsonSerializer(options.getLogger(), options.getEnvelopeReader()));
Hub hub = new Hub(options);
```

Capturing the event

```
SentryEvent event;
event = new SentryEvent(e);
Message sentryMessage = new Message();
sentryMessage.setFormatted(message);
event.setMessage(sentryMessage);
hub.captureEvent(event);
```

**Comment by rrodrigues** [comment]
Thanks @arunshankar87 for your steps.
I was being able to do this because I was missing the line
> `options.setSerializer(new GsonSerializer(options.getLogger(), options.getEnvelopeReader()));` 

Also I think that could be useful to have `AndroidOptionsInitializer.init` public.

**Comment by marandaneto** [comment]
@rrodrigues why would you need `AndroidOptionsInitializer.init` public?

Default integrations are supposed to be added only once, by the final App and not a library, otherwise, they would conflict, that's why it's not public.

**Comment by rrodrigues** [comment]
Because if the final app does not use sentry there are integrations that I would like to include anyway.
But you're right, maybe doing it blindly is not the best way.

**Comment by alexandresoler** [comment]
After the answer of @arunshankar87 , I can't find any informations in the documentation of how to add Android Context to a hub.
Actually sending event on the hub, I don't have any informations about mobile devices on events.

**Comment by arunshankar87** [comment]
@alexandresoler yeah it doesn't come by default. We need to set the DefaultAndroidEventProcessor as options, and that would include all the system properties to come through. But DefaultAndroidEventProcessor is not public. So I have used reflection to achieve this.

**Comment by marandaneto** [comment]
since v4.0.0, there's a default serializer set to the options already, so this is not necessary anymore:

`options.setSerializer(new GsonSerializer(options.getLogger(), options.getEnvelopeReader()));`

but only:

```
SentryOptions options = new SentryOptions();
options.setDsn(dsn);
Hub hub = new Hub(options);
```

**Comment by adinauer** [comment]
Currently our SDK is not meant to be used in Framework/Libraries. In fact, we don't officially support two instances of the SDK running in the same project pointing to different DSNs.

Of course, that could change in the future if we see more interest in this feature, but we don't have any plans at the moment.

**Comment by RobertApikyan** [comment]
> [@raulhernandezendesk](https://github.com/raulhernandezendesk) we have some official docs around this now, you can have a look here: https://docs.sentry.io/platforms/android/configuration/shared-environments/ Hope this helps!

Regarding the iOS SDKs, do you happen to know if this approach only applies to Android SDKs?

**Comment by markosopcic** [comment]
> [@raulhernandezendesk](https://github.com/raulhernandezendesk) we have some official docs around this now, you can have a look here: https://docs.sentry.io/platforms/android/configuration/shared-environments/ Hope this helps!

Hey, I've been looking at this example and trying it out, but I couldn't figure out how to actually sync the collected events with the API? They never seem to be sent when i configure the SDK this way. Also, i assume i would need to pass in an android context to this configuration _somewhere_, so it can store the error information locally and then also to send it to the API, but the provided example doesn't use it anywhere.

Any help is greatly appreciated ,thanks in advance.

**Comment by romtsn** [comment]
@RobertApikyan we've updated docs for iOS too: https://docs.sentry.io/platforms/apple/guides/ios/configuration/shared-environments/

@markosopcic for caching, yes, you will have to add the `SendCachedEnvelopeIntegration` and set `options.cacheDirPath` to something upfront (that's where you'd likely need `Context`), like so:
https://github.com/getsentry/sentry-java/blob/e2dce0b7ae88cde49ff74fe2c23e77949c449815/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L366-L374

as to why they are not being sent -- I'm not sure, but you can enable `options.isDebug = true` and watch logcat for what's going on in the SDK. Hope that helps!

**Comment by markosopcic** [comment]
> [@RobertApikyan](https://github.com/RobertApikyan) we've updated docs for iOS too: https://docs.sentry.io/platforms/apple/guides/ios/configuration/shared-environments/
> 
> [@markosopcic](https://github.com/markosopcic) for caching, yes, you will have to add the `SendCachedEnvelopeIntegration` and set `options.cacheDirPath` to something upfront (that's where you'd likely need `Context`), like so:
> 
> [sentry-java/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java](https://github.com/getsentry/sentry-java/blob/e2dce0b7ae88cde49ff74fe2c23e77949c449815/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L366-L374)
> 
> Lines 366 to 374 in [e2dce0b](/getsentry/sentry-java/commit/e2dce0b7ae88cde49ff74fe2c23e77949c449815)
> 
>  // read the startup crash marker here to avoid doing double-IO for the SendCachedEnvelope 
>  // integrations below 
>  LazyEvaluator<Boolean> startupCrashMarkerEvaluator = 
>      new LazyEvaluator<>(() -> AndroidEnvelopeCache.hasStartupCrashMarker(options)); 
>   
>  options.addIntegration( 
>      new SendCachedEnvelopeIntegration( 
>          new SendFireAndForgetEnvelopeSender(() -> options.getCacheDirPath()), 
>          startupCrashMarkerEvaluator)); 
> as to why they are not being sent -- I'm not sure, but you can enable `options.isDebug = true` and watch logcat for what's going on in the SDK. Hope that helps!

Hey, thanks for your reply!

Unfortunately, the `SendCachedEnvelopeIntegration` is package private so it can't be used outside of your sdk.

**Comment by romtsn** [comment]
Ah, right, you can use this one then (no need for the startup crash marker provider, which is probably for the better in case you're using our SDK within another SDK): https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SendCachedEnvelopeFireAndForgetIntegration.java
